# Library

In [1]:
import pandas as pd
import numpy as np
import os

# [로드] 제원정보

In [2]:
ods_fold = 'D:\과업\[한국환경공단]자동차_환경_빅데이터_구축_2차\data\ODS'
file_name = '[ODS]자동차_제원정보(한글컬럼)(2022.12.29).csv'
ods_path = os.path.join(ods_fold, file_name)

In [4]:
# about 
df = pd.read_csv(ods_path, encoding='cp949', low_memory=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545374 entries, 0 to 545373
Data columns (total 28 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   제원관리번호       545374 non-null  object
 1   차명           545272 non-null  object
 2   차종           545370 non-null  object
 3   차종 분류        531367 non-null  object
 4   차종 유형 (소분류)  531332 non-null  object
 5   자동차 형식       516295 non-null  object
 6   제작사 명        529017 non-null  object
 7   연료           503254 non-null  object
 8   엔진형식         494157 non-null  object
 9   공차중량         0 non-null       float64
 10  총 중량         541702 non-null  float64
 11  적재 중량        446181 non-null  float64
 12  엔진출력         471948 non-null  float64
 13  배기량          510521 non-null  float64
 14  승차 인원        545313 non-null  float64
 15  차량 길이        514786 non-null  float64
 16  차량 너비        514799 non-null  float64
 17  차량 높이        514732 non-null  float64
 18  원산지 명        540392 non-null  object
 19  미정           0 non-null       float64
 20  삭제 YN        545374 non-null  object
 21  승인 일자        532881 non-null  object
 22  구동 형식        114619 non-null  object
 23  변속기 종류       540165 non-null  object
 24  미정.1         1 non-null       object
 25  생성 일시        545374 non-null  object
 26  수정 일시        14578 non-null   object
 27  미정.2         545374 non-null  object
dtypes: float64(10), object(18)
memory usage: 116.5+ MB

In [5]:
col = pd.read_excel('analysis/ODSvsSTD/[정제]CEG_CAR_SRC_MIG.xlsx', sheet_name='ODS_col')
col

             컬럼           내용
0       UPDT_DT        수정 일시
1      CNFRM_DE        승인 일자
2       DELE_YN        삭제 YN
3       CRTN_DT        생성 일시
4      TOT_WGHT         총 중량
5      VHCTY_TY  차종 유형 (소분류)
6      VHCTY_CL        차종 분류
7         VHCTY           차종
8         VHCNM           차명
9       VHCL_HG        차량 높이
10      VHCL_WH        차량 너비
11      VHCL_LT        차량 길이
12      DRV_FRM        구동 형식
13       MKR_NM        제작사 명
14      SRCMNNO       제원관리번호
15   CRYNG_WGHT        적재 중량
16      CAR_FRM       자동차 형식
17    EMPV_WGHT         공차중량
18      PLOR_NM        원산지 명
19         FUEL           연료
20       EGINTY         엔진형식
21      EGINPWR         엔진출력
22   TKCAR_NMPR        승차 인원
23       DSPLVL          배기량
24  GEARBOX_KND       변속기 종류
25    REPCAR_NM           미정
26          RMK           미정
27      USER_ID           미정

In [6]:
col_dict = {b:a for a, b in zip(col['컬럼'], col['내용'])}
col_dict

{'수정 일시': 'UPDT_DT',
 '승인 일자': 'CNFRM_DE',
 '삭제 YN': 'DELE_YN',
 '생성 일시': 'CRTN_DT',
 '총 중량': 'TOT_WGHT',
 '차종 유형 (소분류)': 'VHCTY_TY',
 '차종 분류': 'VHCTY_CL',
 '차종': 'VHCTY',
 '차명': 'VHCNM',
 '차량 높이': 'VHCL_HG',
 '차량 너비': 'VHCL_WH',
 '차량 길이': 'VHCL_LT',
 '구동 형식': 'DRV_FRM',
 '제작사 명': 'MKR_NM',
 '제원관리번호': 'SRCMNNO',
 '적재 중량': 'CRYNG_WGHT',
 '자동차 형식': 'CAR_FRM',
 '공차중량': 'EMPV_WGHT',
 '원산지 명': 'PLOR_NM',
 '연료': 'FUEL',
 '엔진형식': 'EGINTY',
 '엔진출력': 'EGINPWR',
 '승차 인원': 'TKCAR_NMPR',
 '배기량': 'DSPLVL',
 '변속기 종류': 'GEARBOX_KND',
 '미정': 'USER_ID'}

# 결측치

In [8]:
an = df.isnull().sum().reset_index()
an.columns = ['한글컬럼', '결측치']

In [9]:
temp = []
for x in an['한글컬럼']:
    try:
        temp.append(col_dict[x])
    except:
        temp.append('미정')
an['컬럼'] = temp
an = an[['컬럼', '한글컬럼', '결측치']]
an

             컬럼         한글컬럼     결측치
0       SRCMNNO       제원관리번호       0
1         VHCNM           차명     102
2         VHCTY           차종       4
3      VHCTY_CL        차종 분류   14007
4      VHCTY_TY  차종 유형 (소분류)   14042
5       CAR_FRM       자동차 형식   29079
6        MKR_NM        제작사 명   16357
7          FUEL           연료   42120
8        EGINTY         엔진형식   51217
9     EMPV_WGHT         공차중량  545374
10     TOT_WGHT         총 중량    3672
11   CRYNG_WGHT        적재 중량   99193
12      EGINPWR         엔진출력   73426
13       DSPLVL          배기량   34853
14   TKCAR_NMPR        승차 인원      61
15      VHCL_LT        차량 길이   30588
16      VHCL_WH        차량 너비   30575
17      VHCL_HG        차량 높이   30642
18      PLOR_NM        원산지 명    4982
19      USER_ID           미정  545374
20      DELE_YN        삭제 YN       0
21     CNFRM_DE        승인 일자   12493
22      DRV_FRM        구동 형식  430755
23  GEARBOX_KND       변속기 종류    5209
24           미정         미정.1  545373
25      CRTN_DT        생성 일시       0
26      UPDT_DT        수정 일시  530796
27           미정         미정.2       0

## [출력] 정기검사 결측치

In [10]:
an.to_excel(f'analysis2/[BD1][통계]제원정보.xlsx', index=False)

# 코드 마지막