# Library

In [1]:
import pandas as pd
import os, datetime
import numpy as np
from tqdm import tqdm

# fold path

In [62]:
fold = 'D:/data/big2/BD1_4등급_데이터_점검1'
save_fold = 'D:/data/big2/BD1_4등급_데이터_점검1/result_emis_update'
save_fold2 = 'D:/data/big2/BD1_4등급_데이터_점검1/result_emis_update2'
save_error = 'D:/data/big2/BD1_4등급_데이터_점검1/result_emis_update2/error'
save_norm = 'D:/data/big2/BD1_4등급_데이터_점검1/result_emis_update2/norm'
save_nan = 'D:/data/big2/BD1_4등급_데이터_점검1/result_emis_update2/nan'
save_weird = 'D:/data/big2/BD1_4등급_데이터_점검1/result_emis_update2/weird'
analysis_fold = 'analysis2/result'

# File Load
- [병합]4등급_차량_리스트_양식_result
- 배인번호_업체확인_리스트(2023.03.08)04

## 4등급_차량_리스트_양식_result

In [3]:
# about 21s
file_name = '[병합]4등급_차량_리스트_양식_result_검사정보.csv'
df = pd.read_csv(os.path.join(fold, file_name), encoding='cp949', low_memory=False)

In [4]:
# 컬럼명 : 4등급_차량_리스트_양식_result
# '차대번호', '차량번호', '제원관리번호', '차종_원본', '용도', '최초등록일', '연식', '제작일자', '검사유효일', '배출가스인증번호', '등급', '차명', '차종분류', '차종유형', '자동차형식', '제작사명', '연료', '엔진형식', '총중량', '적재중량', '엔진출력', '배기량', '법정동코드', '시도명', '시군구명', '소유자구분', '말소여부', '일치유무'

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1153813 entries, 0 to 1153812
Data columns (total 64 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   차대번호       1153813 non-null  object
 1   차량번호_x     1153813 non-null  object
 2   제원관리번호     1153813 non-null  object
 3   차종_원본      1153813 non-null  object
 4   용도         1153813 non-null  object
 5   최초등록일      1153813 non-null  int64
 6   연식         1153813 non-null  int64
 7   제작일자       1153809 non-null  float64
 8   검사유효일      1153810 non-null  float64
 9   배출가스인증번호   1146663 non-null  object
 10  등급         1153813 non-null  int64
 11  차명_x       1153813 non-null  object
 12  차종분류       1153813 non-null  object
 13  차종유형       1153813 non-null  object
 14  자동차형식      1153812 non-null  object
 15  제작사명       1153795 non-null  object
 16  연료         1153813 non-null  object
 17  엔진형식_x     1153813 non-null  object
 18  총중량        1153813 non-null  float64
 19  적재중량       1153589 non-null  float64
 20  엔진출력       1153811 non-null  float64
 21  배기량        1153813 non-null  float64
 22  법정동코드      1153813 non-null  int64
 23  시도명        1153813 non-null  object
 24  시군구명       1153813 non-null  object
 25  소유자구분      1153813 non-null  object
 26  말소여부       1153813 non-null  object
 27  일치유무       1153813 non-null  object
 28  사용연료       1131176 non-null  object
 29  주행거리       1131063 non-null  float64
 30  차명_y       1131176 non-null  object
 31  차량번호_y     1131176 non-null  object
 32  차종         1131176 non-null  object
 33  차량연식       1131176 non-null  float64
 34  엔진형식_y     1131165 non-null  object
 35  검사방법       1131176 non-null  object
 36  검사일자       1131176 non-null  float64
 37  검사종류       1131176 non-null  object
 38  검사판정시각     1122501 non-null  object
 39  검사판정       1131176 non-null  object
 40  산소값        817299 non-null   float64
 41  이산화탄소값     817299 non-null   float64
 42  무부하매연판정1   1122497 non-null  object
 43  무부하매연판정2   44435 non-null    object
 44  무부하매연판정3   43534 non-null    object
 45  무부하매연판정4   43532 non-null    object
 46  무부하매연판정5   43532 non-null    object
 47  무부하매연판정6   46 non-null       object
 48  무부하매연허용치1  1122497 non-null  float64
 49  무부하매연허용치2  333612 non-null   float64
 50  무부하매연허용치3  333611 non-null   float64
 51  무부하매연허용치4  333609 non-null   float64
 52  무부하매연허용치5  333609 non-null   float64
 53  무부하매연허용치6  301714 non-null   float64
 54  무부하매연측정치1  1122501 non-null  float64
 55  무부하매연측정치2  367673 non-null   float64
 56  무부하매연측정치3  333613 non-null   float64
 57  무부하매연측정치4  333611 non-null   float64
 58  무부하매연측정치5  333611 non-null   float64
 59  무부하매연측정치6  301714 non-null   float64
 60  정기정밀       1131176 non-null  object
 61  vin10      1153813 non-null  object
 62  vin_year   1153810 non-null  float64
 63  DPF유무      1153813 non-null  object
dtypes: float64(24), int64(4), object(36)
memory usage: 563.4+ MB

In [6]:
df.isnull().sum()

차대번호              0
차량번호_x            0
제원관리번호            0
차종_원본             0
용도                0
              ...
무부하매연측정치6    852099
정기정밀          22637
vin10             0
vin_year          3
DPF유무             0
Length: 64, dtype: int64

In [7]:
df.columns

Index(['차대번호', '차량번호_x', '제원관리번호', '차종_원본', '용도', '최초등록일', '연식', '제작일자',
       '검사유효일', '배출가스인증번호', '등급', '차명_x', '차종분류', '차종유형', '자동차형식', '제작사명',
       '연료', '엔진형식_x', '총중량', '적재중량', '엔진출력', '배기량', '법정동코드', '시도명', '시군구명',
       '소유자구분', '말소여부', '일치유무', '사용연료', '주행거리', '차명_y', '차량번호_y', '차종', '차량연식',
       '엔진형식_y', '검사방법', '검사일자', '검사종류', '검사판정시각', '검사판정', '산소값', '이산화탄소값',
       '무부하매연판정1', '무부하매연판정2', '무부하매연판정3', '무부하매연판정4', '무부하매연판정5', '무부하매연판정6',
       '무부하매연허용치1', '무부하매연허용치2', '무부하매연허용치3', '무부하매연허용치4', '무부하매연허용치5',
       '무부하매연허용치6', '무부하매연측정치1', '무부하매연측정치2', '무부하매연측정치3', '무부하매연측정치4',
       '무부하매연측정치5', '무부하매연측정치6', '정기정밀', 'vin10', 'vin_year', 'DPF유무'],
      dtype='object')

In [8]:
# 1,153,813 행
df.shape

(1153813, 64)

### 컬럼명 수정

In [9]:
# 컬럼명 수정 : 인증번호 -> 배출가스인증번호
df1 = df.rename(columns={'인증번호':'배출가스인증번호'})
df1.columns

Index(['차대번호', '차량번호_x', '제원관리번호', '차종_원본', '용도', '최초등록일', '연식', '제작일자',
       '검사유효일', '배출가스인증번호', '등급', '차명_x', '차종분류', '차종유형', '자동차형식', '제작사명',
       '연료', '엔진형식_x', '총중량', '적재중량', '엔진출력', '배기량', '법정동코드', '시도명', '시군구명',
       '소유자구분', '말소여부', '일치유무', '사용연료', '주행거리', '차명_y', '차량번호_y', '차종', '차량연식',
       '엔진형식_y', '검사방법', '검사일자', '검사종류', '검사판정시각', '검사판정', '산소값', '이산화탄소값',
       '무부하매연판정1', '무부하매연판정2', '무부하매연판정3', '무부하매연판정4', '무부하매연판정5', '무부하매연판정6',
       '무부하매연허용치1', '무부하매연허용치2', '무부하매연허용치3', '무부하매연허용치4', '무부하매연허용치5',
       '무부하매연허용치6', '무부하매연측정치1', '무부하매연측정치2', '무부하매연측정치3', '무부하매연측정치4',
       '무부하매연측정치5', '무부하매연측정치6', '정기정밀', 'vin10', 'vin_year', 'DPF유무'],
      dtype='object')

In [10]:
df1.shape

(1153813, 64)

## [배인번호]업체확인_리스트

In [75]:
file_name = '배인번호_업체확인_리스트(2023.03.15)07.xlsx'
mod = pd.read_excel(os.path.join(fold, file_name), sheet_name='확인')

In [76]:
mod.shape

(4542, 11)

In [77]:
mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4542 entries, 0 to 4541
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   등급(현재)     4542 non-null   int64
 1   등급(수정)     4542 non-null   object
 2   배인번호(현재)   4542 non-null   object
 3   배인번호(수정)   4542 non-null   object
 4   차명         4542 non-null   object
 5   제작사        4542 non-null   object
 6   자동차형식      4542 non-null   object
 7   엔진형식       4542 non-null   object
 8   DPF유무(현재)  4542 non-null   object
 9   DPF유무(수정)  4542 non-null   object
 10  기타         919 non-null    object
dtypes: int64(1), object(10)
memory usage: 390.5+ KB

In [78]:
mod.columns

Index(['등급(현재)', '등급(수정)', '배인번호(현재)', '배인번호(수정)', '차명', '제작사', '자동차형식',
       '엔진형식', 'DPF유무(현재)', 'DPF유무(수정)', '기타'],
      dtype='object')

## 8MY-KM-13-19

In [79]:
km = pd.read_excel(os.path.join(fold, '8MY-KM-13-19_업체확인.xlsx'))
km.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제원관리번호  468 non-null    object
 1   인증번호    468 non-null    object
 2   차명      468 non-null    object
 3   코드      468 non-null    object
 4   등급      468 non-null    object
 5   DPF     468 non-null    object
dtypes: object(6)
memory usage: 22.1+ KB

In [80]:
km.head()

              제원관리번호       인증번호                차명  코드 등급 DPF
0  A0110003111493107  4MY-KM-06  봉고 1톤 4X4 장축 더블캡  PU  5   무
1  A0110003111753107  4MY-KM-06  봉고 1톤 4X4 장축 더블캡  PU  5   무
2  A0110003111783107  4MY-KM-06  봉고 1톤 4X4 장축 더블캡  PU  5   무
3  A0110003111803107  4MY-KM-06  봉고 1톤 4X4 장축 더블캡  PU  5   무
4  A0110003111963107  4MY-KM-06  봉고 1톤 4X4 장축 더블캡  PU  5   무

In [81]:
# 매칭조건 컬럼 : '배출가스인증번호', '자동차형식', '엔진형식'
# 매칭조건 컬럼 : '배출가스인증번호', '자동차형식', '엔진형식_x'
# 수정할 컬럼 : '배출가스인증번호', '등급', 'DPF유무'

In [82]:
mod.head()

,등급(현재),등급(수정),배인번호(현재),배인번호(수정),차명,제작사,자동차형식,엔진형식,DPF유무(현재),DPF유무(수정),기타
0,4,4,7MY-SM-14-36,7MY-SM-14-36,QM5,르노삼성자동차(주),H1D20-VC-0-11,M9R,유,유,NaN
1,4,4,7MY-SM-14-36,7MY-SM-14-36,QM5,르노삼성자동차(주),H1D20-VC-0-12,M9R,유,유,NaN
2,4,4,7MY-SM-14-36,7MY-SM-14-36,QM5,르노삼성자동차(주),H1D20-VC-0-21,M9R,유,유,NaN
3,4,4,7MY-SM-14-36,7MY-SM-14-36,QM5,르노삼성자동차(주),H1D20-VC-0-22,M9R,유,유,NaN
4,4,4,7MY-SM-14-36,7MY-SM-14-36,QM5,르노삼성자동차(주),H1D20-VC-0-31,M9R,유,유,NaN

# 수정사항 반영

In [88]:
# 매칭조건 컬럼 : '배출가스인증번호', '자동차형식', '엔진형식'
# 매칭조건 컬럼 : '배출가스인증번호', '자동차형식', '엔진형식_x'
# 수정할 컬럼 : '배출가스인증번호', '등급', 'DPF유무'

In [89]:
# 확인 샘플
# 수정
# '등급', 배출가스인증번호, 차명, 제작사명, 자동차형식, 엔진형식, 'DPF유무'
# 전 : 4, 4MY-DC-33, 대우11.5톤장축카고트럭(DPF), 타타대우상용차(주), K9ARF5, DV11, 무
# 후 : 5, 6MY-DC-23-17(적용X), 대우11.5톤장축카고트럭(DPF), 타타대우상용차(주), K9ARF5, DV11, 유

In [90]:
# df.loc[:5, ['배출가스인증번호', '등급', '차명', '자동차형식', '제작사명', '엔진형식']]
df1.loc[:5, ['배출가스인증번호', '등급', '차명_x', '자동차형식', '제작사명', '엔진형식_x']]

,배출가스인증번호,등급,차명_x,자동차형식,제작사명,엔진형식_x
0,9MY-KM-14-41,4,카니발,VQS96BB-G,기아자동차(주),D4HB
1,7MY-SY-14-60,4,액티언스포츠,Q5D20A2-008D,쌍용자동차(주),664951
2,9MY-KM-14-22,4,쏘렌토,XM75BA-S,기아자동차(주),D4HA
3,NaN,4,금강24㎘경질유탱크로리,KK-T23.5SD-415,"주식회사 카셈(KASEM Co.,Ltd)",ISM
4,9MY-KM-14-41,4,그랜드 카니발,VQLB6BA-S,기아자동차(주),D4HB
5,9MY-KM-14-22,4,쏘렌토,XM75BB-S,기아자동차(주),D4HA

In [91]:
# df.loc[df['배출가스인증번호'] == '4MY-DC-33', ['배출가스인증번호', '등급', '차명', '자동차형식', '제작사명', '엔진형식']]
df1.loc[df1['배출가스인증번호'] == '4MY-DC-33', ['배출가스인증번호', '등급', '차명_x', '자동차형식', '제작사명', '엔진형식_x', 'DPF유무']]

         배출가스인증번호  등급                차명_x   자동차형식        제작사명 엔진형식_x DPF유무
75251   4MY-DC-33   4  대우11.5톤장축카고트럭(DPF)  K9ARF5  타타대우상용차(주)   DV11     무
97568   4MY-DC-33   4  대우11.5톤장축카고트럭(DPF)  K9ARF5  타타대우상용차(주)   DV11     무
162876  4MY-DC-33   4  대우11.5톤장축카고트럭(DPF)  K9ARF5  타타대우상용차(주)   DV11     무
169067  4MY-DC-33   4  대우11.5톤장축카고트럭(DPF)  K9ARF5  타타대우상용차(주)   DV11     무
349831  4MY-DC-33   4  대우11.5톤장축카고트럭(DPF)  K9ARF5  타타대우상용차(주)   DV11     무
484265  4MY-DC-33   4  대우11.5톤장축카고트럭(DPF)  K9ARF5  타타대우상용차(주)   DV11     무
713111  4MY-DC-33   4  대우11.5톤장축카고트럭(DPF)  K9ARF5  타타대우상용차(주)   DV11     무

In [92]:
# 확인 샘플
# 수정
# 등급, 배출가스인증번호, 차명, 제작사명, 자동차형식, 엔진형식, 'DPF유무'
# 전 : 4, 7MY-MT-24-01, 만 트랙터, 만트럭버스코리아(주), TGA28.4806X2-2BLS, D2676LF05, 무
# 후 : 4, 7MY-MT-24-01, 만 트랙터, 만트럭버스코리아(주), TGA28.4806X2-2BLS, D2676LF05, 유

In [93]:
# df1.loc[df['배출가스인증번호'] == '7MY-MT-24-01', ['배출가스인증번호', '등급', '차명', '자동차형식', '제작사명', '엔진형식']]
df1.loc[df1['배출가스인증번호'] == '7MY-MT-24-01', ['배출가스인증번호', '등급', '차명_x', '자동차형식', '제작사명', '엔진형식_x', 'DPF유무']]

,배출가스인증번호,등급,차명_x,자동차형식,제작사명,엔진형식_x,DPF유무
2417,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무
3609,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무
29872,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무
30993,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무
32921,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무
...,...,...,...,...,...,...,...
1135425,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무
1138392,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무
1145376,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무
1146804,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무
1153494,7MY-MT-24-01,4,만 트랙터,TGX28.4806X2-2BLS,만트럭버스코리아(주),D2676LF05,무

## 컬럼 추가

In [94]:
df1['등급'].unique()

array([4], dtype=int64)

In [95]:
df1['배인번호_수정'] = df1['배출가스인증번호'].copy()
df1['등급_수정'] = df1['등급'].copy()
df1['엔진형식_x'] = df1['엔진형식_x'].astype('str')
df1['DPF유무_수정'] = np.nan
df1['확인유무'] = np.nan
df1['비고'] = np.nan

In [96]:
# df1[['배출가스인증번호', '등급', '등급_수정', '차명', '자동차형식', '제작사명', '엔진형식', 'DPF유무_수정', '확인유무', '비고']].head()
df1[['배출가스인증번호', '배인번호_수정', '등급', '등급_수정', '차명_x', '자동차형식', '제작사명', '엔진형식_x', 'DPF유무_수정', '확인유무', '비고']].head()

,배출가스인증번호,배인번호_수정,등급,등급_수정,차명_x,자동차형식,제작사명,엔진형식_x,DPF유무_수정,확인유무,비고
0,9MY-KM-14-41,9MY-KM-14-41,4,4,카니발,VQS96BB-G,기아자동차(주),D4HB,NaN,NaN,NaN
1,7MY-SY-14-60,7MY-SY-14-60,4,4,액티언스포츠,Q5D20A2-008D,쌍용자동차(주),664951,NaN,NaN,NaN
2,9MY-KM-14-22,9MY-KM-14-22,4,4,쏘렌토,XM75BA-S,기아자동차(주),D4HA,NaN,NaN,NaN
3,NaN,NaN,4,4,금강24㎘경질유탱크로리,KK-T23.5SD-415,"주식회사 카셈(KASEM Co.,Ltd)",ISM,NaN,NaN,NaN
4,9MY-KM-14-41,9MY-KM-14-41,4,4,그랜드 카니발,VQLB6BA-S,기아자동차(주),D4HB,NaN,NaN,NaN

## 수정 적용

In [97]:
pick_mod = mod[['등급(현재)', '등급(수정)', '배인번호(현재)', '배인번호(수정)', '차명', '자동차형식', '엔진형식', 'DPF유무(수정)']].values
len(pick_mod)

4542

In [98]:
# about 14m 20s
# '등급(현재)', '등급(수정)', '배인번호(현재)', '배인번호(수정)', '차명, '자동차형식', '엔진형식', 'DPF유무(수정)'
for p_grade, m_grade, p_emis, m_emis, car_name, car_form, engine_form, m_dpf in tqdm(pick_mod):
    df1.loc[(df1['배출가스인증번호'] == p_emis) & (df1['자동차형식'] == str(car_form)) & (df1['엔진형식_x'] == str(engine_form)), ['배인번호_수정', '등급_수정', 'DPF유무_수정', '확인유무']] = [m_emis, m_grade, m_dpf, 'Y']

100%|██████████| 4542/4542 [14:58<00:00,  5.05it/s]

In [99]:
# 1,153,813 행
df1.shape

(1153813, 69)

### 8MY-KM-13-19
- 특정 제원관리번호에만 적용

In [100]:
km.columns

Index(['제원관리번호', '인증번호', '차명', '코드', '등급', 'DPF'], dtype='object')

In [101]:
for srcno, m_emis, m_grade, m_dpf in tqdm(km[['제원관리번호', '인증번호', '등급', 'DPF']].values):
    df1.loc[(df1['제원관리번호'] == srcno) & (df1['배출가스인증번호'] == '8MY-KM-13-19'), ['배인번호_수정', '등급_수정', 'DPF유무_수정', '확인유무']] = [m_emis, m_grade, m_dpf, 'Y']

100%|██████████| 468/468 [01:03<00:00,  7.32it/s]

In [102]:
# 1,153,813 행
df1.shape

(1153813, 69)

### 수정사항 확인
- 4MY-DC-33 제작사확인_DPF유무 : 유
- 9MY-AD-14-04 제작사확인_DPF유무 : 유
- 5MY-AD-13-07 등급 : 3
- 5MY-SY-24-48 등급 : 5
- 8MY-KM-13-19

In [103]:
df1.loc[df1['배출가스인증번호'] == '4MY-DC-33', ['배출가스인증번호', '배인번호_수정', '등급', '등급_수정', '차명_x', '자동차형식', '제작사명', '엔진형식_x', 'DPF유무', 'DPF유무_수정', '확인유무', '비고']].head()

,배출가스인증번호,배인번호_수정,등급,등급_수정,차명_x,자동차형식,제작사명,엔진형식_x,DPF유무,DPF유무_수정,확인유무,비고
75251,4MY-DC-33,6MY-DC-23-17,4,5,대우11.5톤장축카고트럭(DPF),K9ARF5,타타대우상용차(주),DV11,무,유,Y,NaN
97568,4MY-DC-33,6MY-DC-23-17,4,5,대우11.5톤장축카고트럭(DPF),K9ARF5,타타대우상용차(주),DV11,무,유,Y,NaN
162876,4MY-DC-33,6MY-DC-23-17,4,5,대우11.5톤장축카고트럭(DPF),K9ARF5,타타대우상용차(주),DV11,무,유,Y,NaN
169067,4MY-DC-33,6MY-DC-23-17,4,5,대우11.5톤장축카고트럭(DPF),K9ARF5,타타대우상용차(주),DV11,무,유,Y,NaN
349831,4MY-DC-33,6MY-DC-23-17,4,5,대우11.5톤장축카고트럭(DPF),K9ARF5,타타대우상용차(주),DV11,무,유,Y,NaN

In [104]:
df1.loc[df1['배출가스인증번호'] == '9MY-AD-14-04', ['배출가스인증번호', '배인번호_수정', '등급', '등급_수정', '차명_x', '자동차형식', '제작사명', '엔진형식_x', 'DPF유무', 'DPF유무_수정', '확인유무', '비고']].head()

,배출가스인증번호,배인번호_수정,등급,등급_수정,차명_x,자동차형식,제작사명,엔진형식_x,DPF유무,DPF유무_수정,확인유무,비고
1239,9MY-AD-14-04,9MY-AD-14-04,4,4,Q5 2.0 TDI quattro,8R,아우디폭스바겐코리아(주),CAH,무,유,Y,NaN
2421,9MY-AD-14-04,9MY-AD-14-04,4,4,Q5 2.0 TDI quattro,8R,아우디폭스바겐코리아(주),CAH,무,유,Y,NaN
2794,9MY-AD-14-04,9MY-AD-14-04,4,4,Q5 2.0 TDI quattro,8R,아우디폭스바겐코리아(주),CAH,무,유,Y,NaN
4110,9MY-AD-14-04,9MY-AD-14-04,4,4,Q5 2.0 TDI quattro,8R,아우디폭스바겐코리아(주),CAH,무,유,Y,NaN
4969,9MY-AD-14-04,9MY-AD-14-04,4,4,Q5 2.0 TDI quattro,8R,아우디폭스바겐코리아(주),CAH,무,유,Y,NaN

In [105]:
df1.loc[df1['배출가스인증번호'] == '5MY-AD-13-07', ['배출가스인증번호', '배인번호_수정', '등급', '등급_수정', '차명_x', '자동차형식', '제작사명', '엔진형식_x', 'DPF유무', 'DPF유무_수정', '확인유무', '비고']].head()

,배출가스인증번호,배인번호_수정,등급,등급_수정,차명_x,자동차형식,제작사명,엔진형식_x,DPF유무,DPF유무_수정,확인유무,비고
2019,5MY-AD-13-07,5MY-AD-13-07,4,3,Touareg 3.0 TDI,7L,아우디폭스바겐코리아(주),BKS,무,유,Y,NaN
2538,5MY-AD-13-07,5MY-AD-13-07,4,3,Touareg 3.0 TDI,7L,아우디폭스바겐코리아(주),BKS,무,유,Y,NaN
10519,5MY-AD-13-07,5MY-AD-13-07,4,3,Touareg 3.0 TDI,7L,아우디폭스바겐코리아(주),BKS,무,유,Y,NaN
39063,5MY-AD-13-07,5MY-AD-13-07,4,3,Touareg 3.0 TDI,7L,아우디폭스바겐코리아(주),BKS,무,유,Y,NaN
58002,5MY-AD-13-07,5MY-AD-13-07,4,3,Touareg 3.0 TDI,7L,아우디폭스바겐코리아(주),BKS,무,유,Y,NaN

In [106]:
df1.loc[df1['배출가스인증번호'] == '5MY-SY-24-48', ['배출가스인증번호', '배인번호_수정', '등급', '등급_수정', '차명_x', '자동차형식', '제작사명', '엔진형식_x', 'DPF유무', 'DPF유무_수정', '확인유무', '비고']].head()

,배출가스인증번호,배인번호_수정,등급,등급_수정,차명_x,자동차형식,제작사명,엔진형식_x,DPF유무,DPF유무_수정,확인유무,비고
146341,5MY-SY-24-48,5MY-SY-24-48,4,5,액티언,C5D20A2-006,쌍용자동차(주),664951,무,무,Y,NaN
703424,5MY-SY-24-48,5MY-SY-24-48,4,5,액티언,C5D20A2-006,쌍용자동차(주),664951,무,무,Y,NaN

In [107]:
# df1.loc[:5, ['배출가스인증번호', '등급', '등급_수정', '차명', '자동차형식', '제작사명', '엔진형식', 'DPF유무_수정', '확인유무', '비고']]
df1.loc[:5, ['배출가스인증번호', '등급', '등급_수정', '차명_x', '자동차형식', '제작사명', '엔진형식_x', 'DPF유무', 'DPF유무_수정', '확인유무', '비고']]

,배출가스인증번호,등급,등급_수정,차명_x,자동차형식,제작사명,엔진형식_x,DPF유무,DPF유무_수정,확인유무,비고
0,9MY-KM-14-41,4,4,카니발,VQS96BB-G,기아자동차(주),D4HB,무,무,Y,NaN
1,7MY-SY-14-60,4,4,액티언스포츠,Q5D20A2-008D,쌍용자동차(주),664951,무,무,Y,NaN
2,9MY-KM-14-22,4,4,쏘렌토,XM75BA-S,기아자동차(주),D4HA,무,무,Y,NaN
3,NaN,4,4,금강24㎘경질유탱크로리,KK-T23.5SD-415,"주식회사 카셈(KASEM Co.,Ltd)",ISM,무,NaN,NaN,NaN
4,9MY-KM-14-41,4,4,그랜드 카니발,VQLB6BA-S,기아자동차(주),D4HB,무,무,Y,NaN
5,9MY-KM-14-22,4,4,쏘렌토,XM75BB-S,기아자동차(주),D4HA,무,무,Y,NaN

In [108]:
df1.loc[df1['배출가스인증번호'] == '8MY-KM-13-19', ['배출가스인증번호', '배인번호_수정', '등급', '등급_수정', '차명_x', '자동차형식', '제작사명', '엔진형식_x', 'DPF유무', 'DPF유무_수정', '확인유무', '비고']].head()

,배출가스인증번호,배인번호_수정,등급,등급_수정,차명_x,자동차형식,제작사명,엔진형식_x,DPF유무,DPF유무_수정,확인유무,비고
16,8MY-KM-13-19,7MY-KM-14-65,4,4,봉고Ⅲ 4륜구동,PUK4CB-F,기아자동차(주),J3,유,무,Y,NaN
21,8MY-KM-13-19,7MY-KM-14-65,4,4,봉고Ⅲ 파워게이트,PUL4AB-PGT-2,기아자동차(주),J3,유,무,Y,NaN
26,8MY-KM-13-19,7MY-KM-14-65,4,4,봉고Ⅲ 4륜구동,PUD4CC-F,기아자동차(주),J3,유,무,Y,NaN
28,8MY-KM-13-19,7MY-KM-14-65,4,4,봉고Ⅲ 1톤,SEL42K-L-A,기아자동차(주),J3,유,무,Y,NaN
41,8MY-KM-13-19,7MY-KM-14-65,4,4,봉고Ⅲ 4륜구동,SEK45J,기아자동차(주),J3,유,무,Y,NaN

In [109]:
# [해결] 4MY-PA-06 DPF유무_수정 결측값 1개 -> 자동차형식 2.0LN3DR 추가
# [해결] 5MY-PA-14-17 DPF유무_수정 결측값 55개 -> 무
# [해결] 5MY-AD-14-08 DPF유무_수정 결측값 4개 -> (수정) 자기인증면제 DPF유무_수정 '확인불가'로 수정
# [해결] 5MY-AD-14-12 DPF유무_수정 결측값 1개 -> 자동차형식 4E 추가
# [해결] 5MY-AD-14-18 DPF유무_수정 결측값 7개 -> (수정) 자기인증면제 자기인증면제 DPF유무_수정 '확인불가'로 수정
# [해결] 5MY-AD-14-19 DPF유무_수정 결측값 231개 -> 제번 : 02420009200011208, 02420009200001207, 02420009200031208 자동차형식 BMN 추가
# [해결] 6MY-AD-14-10 DPF유무_수정 결측값 1개 -> 자동차형식 CBW 추가
# [해결] 5MY-HB-24-02 DPF유무_수정 결측값 1개 -> (수정) 자기인증면제 DPF유무_수정 '무'로 수정
# [해결] 6MY-KM-14-57 DPF유무_수정 결측값 79개 -> 자동차형식 JB54A2-L, DEH42J8 추가
# [해결] 6MY-KM-14-61 DPF유무_수정 결측값 2개 -> (수정) 자기인증면제차량, (유지) 르노삼성자동차(주)
# [해결] 6MY-KM-24-81 DPF유무_수정 결측값 133개 -> 자동차형식 JC548N 추가, (유지) 나머지 제작사, (수정) 자기인증면제 차량
# [해결] 6MY-HD-24-12 DPF유무_수정 결측값 4212개 -> 엔진형식 오류 수정(D4FB로 수정)
# [해결] 7MY-SY-14-24 DPF유무_수정 결측값 3569개 -> 엔진형식_x 값 str 타입으로 변경
# [해결] 7MY-SY-14-60 DPF유무_수정 결측값 29437개 -> 엔진형식_x 값 str 타입으로 변경
# [해결] 7MY-SY-14-61 DPF유무_수정 결측값 1037개 -> 엔진형식_x 값 str 타입으로 변경
# [해결] 8MY-SY-13-14 DPF유무_수정 결측값 313개 -> 엔진형식_x 값 str 타입으로 변경
# [해결] 7MY-DB-24-40 DPF유무_수정 결측값 1개 -> 자동차형식 BS110CN-GP8P3A281F 값 추가
# [확인중..] 7MY-DB-24-42 3등급 차량 존재 -> 업체 메일에선 4등급만 존재
# [해결] 7MY-DB-24-43 DPF유무_수정 결측값 3개 -> 자동차형식 BH120-GP8R4S371S, BH119-GP7R4S442S, FX116-GP8R4S411S 추가
# [해결] 7MY-DB-24-44 DPF유무_수정 결측값 11개 -> 빠진 데이터 추가
# [해결] 6MY-HD-23-55 2대 등급 이상 -> (수정) 자기인증면제 차량 5등급으로 수정
# [해결] 7MY-HD-24-28 DPF유무_수정 결측값 3개 -> (수정) 자기인증면제 차량 DPF유무_수정 '유'로 수정
# [해결] 7MY-DC-23-69 DPF유무_수정 결측값 23개 -> 빠진 데이터 추가
# [해결] 7MY-DC-23-70 DPF유무_수정 결측값 25개 -> 빠진 데이터 추가

In [110]:
# [해결] 5MY-PA-13-20 DPF유무_수정 결측값 14개 -> 자동차형식 잘못 입력 수정 C71
# [해결] 5MY-HD-24-59 자기인증면제차량 DPF유무_수정 결측값 3대 -> 데이터 추가
# [해결] 6MY-HD-14-63 자기인증면제차량 DPF유무_수정 결측값 2대 -> 데이터 추가
# [해결] 6MY-HD-14-64 자기인증면제차량 DPF유무_수정 결측값 4대, 현대자동차(주) DPF유무_수정 결측값 740대 -> 데이터 추가
# [해결] 6MY-HD-24-100 자기인증면제차량 DPF유무_수정 결측값 21대 -> 데이터 추가
# [해결] 7MY-HD-14-45 자기인증면제차량 DPF유무_수정 결측값 2대 -> 데이터 추가
# [해결] 7MY-HD-14-47 자기인증면제차량 DPF유무_수정 결측값 2대 -> 데이터 추가
# [해결] 7MY-HD-24-08 자기인증면제차량 DPF유무_수정 결측값 1대 -> 데이터 추가
# [해결] 7MY-KM-14-64 자기인증면제차량 DPF유무_수정 결측값 3대 -> 데이터 추가
# [해결] 7MY-SM-14-36 자기인증면제차량 DPF유무_수정 결측값 4대 -> 데이터 추가
# [해결] 7MY-SY-14-60 자기인증면제차량 DPF유무_수정 결측값 1대 -> 데이터 추가
# [해결] 9MY-HD-14-21 자기인증면제차량 DPF유무_수정 결측값 10대 -> 데이터 추가

In [111]:
# [해결] 5MY-HD-24-56 자기인증면제차량 DPF유무_수정 결측값 1대 -> 데이터 추가
# [해결] 5MY-KM-24-57 자기인증면제차량 DPF유무_수정 결측값 2대 -> 데이터 추가
# [해결] 5MY-SY-23-58 자기인증면제차량 DPF유무_수정 결측값 1대 -> 데이터 추가
# [해결] 6MY-HD-14-97 자기인증면제차량 DPF유무_수정 결측값 3대 -> 데이터 추가
# [해결] 7MY-HD-14-46 자기인증면제차량 DPF유무_수정 결측값 2대 -> 데이터 추가
# [해결] 7MY-HD-14-68 자기인증면제차량 DPF유무_수정 결측값 3대 -> 데이터 추가
# [해결] 7MY-KM-14-63 자기인증면제차량 DPF유무_수정 결측값 1대 -> 데이터 추가
# 7MY-AD-14-04 자기인증면제차량 DPF유무_수정 결측값 1대 -> 데이터 추가

In [112]:
df1.loc[(df1['배출가스인증번호'] == '7MY-AD-14-04') & (df1['DPF유무_수정'].isnull() == True), ['배출가스인증번호', '배인번호_수정','제원관리번호', '제작사명', '자동차형식', '엔진형식_x', 'DPF유무_수정']].drop_duplicates(['자동차형식', '엔진형식_x'])

Empty DataFrame
Columns: [배출가스인증번호, 배인번호_수정, 제원관리번호, 제작사명, 자동차형식, 엔진형식_x, DPF유무_수정]
Index: []

# 제작사 이상 차량 분리
- 제작사 코드 dict 필요

In [113]:
df2 = df1.copy()
df2.shape

(1153813, 69)

In [114]:
df2['배출가스인증번호'] = df2['배출가스인증번호'].astype('str')

In [115]:
pcode_dict = {'DK':['에프씨에이코리아(주)'], 'PA':['(주)볼보자동차코리아', '(주)재규어랜드로버코리아'], 'HB':['한불모터스(주)'], 'AD':['아우디폭스바겐코리아(주)'], 'DC':['타타대우상용차(주)'], 'HD':['현대자동차(주)'], 'KM':['기아자동차(주)'], 'SK':['스카니아코리아그룹(주)'], 'SY':['쌍용자동차(주)'], 'VTK':['볼보트럭코리아(주)'], 'BK':['비엠더블유코리아(주)'], 'DB':['자일대우상용차 주식회사'], 'DW':['한국지엠주식회사'], 'GK':['지엠아시아퍼시픽지역본부 주식회사'], 'MK':['메르세데스벤츠코리아(주)'], 'DK':['다임러트럭코리아(주)'], 'MT':['만트럭버스코리아(주)'], 'SM':['르노삼성자동차(주)'], 'SY':['쌍용자동차(주)'], 'JL':['(주)재규어랜드로버코리아', '(주)볼보자동차코리아']}
len(pcode_dict)

18

## [출력] 배인번호별 샘플
+ weird 파일
    - 기존 수기로 분리한 샘플 : 4862
    - 자동 분리한 샘플 : 4849
    - 13대 차이 : 자기인증면제차량, 해당 제작사 차명이 아닌 차량
        - 배출가스인증번호, 차명
        - 5MY-HB-24-02, BMW
        - 6MY-KM-14-61, 카렌스
        - 6MY-KM-24-81, BENZ C220
        - 6MY-KM-24-81, BENZ C200 CDI T
        - 7MY-KM-14-63, BENZ R320
        - 5MY-HD-24-59, BMW X3 2.0d
        - 5MY-HD-24-59, BMW 320D
        - 5MY-HD-24-59, BMW 320d Touring
        - 7MY-SM-14-36, Mercedes Benz
        - 7MY-SM-14-36, BMW 320D
        - 7MY-SM-14-36, Mercedes-Benz B180
        - 7MY-SM-14-36, BMW 118D
        - 7MY-HD-24-28, HYUNDAI LIMOUSINE

In [119]:
# about 1m 44s
# 제작사코드에 안맞는 샘플
weird = pd.DataFrame()
for one in tqdm(df2['배출가스인증번호'].unique()):
    one_df = df2.loc[df2['배출가스인증번호'] == one].reset_index(drop=True)
    if 'nan' == one: # nan 값
        one_df.to_csv(os.path.join(save_nan, f'{one}.csv'), index=False, encoding='cp949')
    elif ('-' not in one) or ('0M' in one): # 비정상 배인번호
        one_df.to_csv(os.path.join(save_error, f'{one}.csv'), index=False, encoding='cp949')
    elif one.split('-')[1] == 'PP': # 비정상 배인번호(2섹션에 'PP')
        one_df.to_csv(os.path.join(save_error, f'{one}.csv'), index=False, encoding='cp949')
    else: # 정상 배인번호
        one_norm = pd.DataFrame()
        one_idx = []
        # 자기인증면제차량 -> 정상으로 분류
            # 그 중에서 제작사와 맞지 않는 차량 분류
        if '자기인증면제차량' in one_df['제작사명'].unique():
            self_car = one_df.loc[one_df['제작사명'] == '자기인증면제차량']
            if one == '5MY-HB-24-02':
                self_car = self_car.loc[self_car['차명_x'] != 'BMW']
            if one == '6MY-KM-14-61':
                self_car = self_car.loc[self_car['차명_x'] != '카렌스']
            if one == '6MY-KM-24-81':
                self_car = self_car.loc[self_car['차명_x'] != 'BENZ C220']
            if one == '6MY-KM-24-81':
                self_car = self_car.loc[self_car['차명_x'] != 'BENZ C200 CDI T']
            if one == '7MY-KM-14-63':
                self_car = self_car.loc[self_car['차명_x'] != 'BENZ R320']
            if one == '5MY-HD-24-59':
                self_car = self_car.loc[self_car['차명_x'] != 'BMW X3 2.0d']
            if one == '5MY-HD-24-59':
                self_car = self_car.loc[self_car['차명_x'] != 'BMW 320D']
            if one == '5MY-HD-24-59':
                self_car = self_car.loc[self_car['차명_x'] != 'BMW 320d Touring']
            if one == '7MY-SM-14-36':
                self_car = self_car.loc[self_car['차명_x'] != 'Mercedes Benz']
            if one == '7MY-SM-14-36':
                self_car = self_car.loc[self_car['차명_x'] != 'BMW 320D']
            if one == '7MY-SM-14-36':
                self_car = self_car.loc[self_car['차명_x'] != 'Mercedes-Benz B180']
            if one == '7MY-SM-14-36':
                self_car = self_car.loc[self_car['차명_x'] != 'BMW 118D']
            if one == '7MY-HD-24-28':
                self_car = self_car.loc[self_car['차명_x'] != 'HYUNDAI LIMOUSINE']
            one_norm = pd.concat([one_norm, self_car], ignore_index=True)
            one_idx = one_idx + list(self_car.index)
        # 제작사 코드에 맞는 제작사와 안맞는 제작사 분류
        for two in pcode_dict[one.split('-')[1]]:
            two_df = one_df.loc[one_df['제작사명'] == two]
            one_idx = one_idx + list(two_df.index)
            one_norm = pd.concat([one_norm, two_df], ignore_index=True)
        one_norm.to_csv(os.path.join(save_norm, f'{one}.csv'), index=False, encoding='cp949')
        one_weird = one_df.drop(one_idx)
        weird = pd.concat([weird, one_weird], ignore_index=True)
weird.to_csv(os.path.join(save_weird, 'weird.csv'), index=False, encoding='cp949')

100%|██████████| 206/206 [00:53<00:00,  3.88it/s]

### [출력] 배인번호별 샘플

In [128]:
df1_1 = df1.copy()

In [129]:
df1_1['배출가스인증번호'] = df1_1['배출가스인증번호'].astype('str')

In [130]:
df1_1['배출가스인증번호'].isnull().sum()

0

In [131]:
save_fold

'D:/data/big2/BD1_4등급_데이터_점검1/result_emis_update'

In [132]:
# about 51s
for one in tqdm(df1_1['배출가스인증번호'].unique()):
    temp = df1_1.loc[df1_1['배출가스인증번호'] == one].reset_index(drop=True)
    temp.to_csv(os.path.join(save_fold, f'{one}.csv'), index=False, encoding='cp949')

100%|██████████| 206/206 [00:50<00:00,  4.12it/s]

## 배인번호별 통계

In [191]:
# df1.groupby(['배출가스인증번호', '차명_x', '제작사명', '자동차형식', '엔진형식_x', 'DPF유무_수정', '확인유무'], dropna=False)['차대번호'].count()

### [출력] 배인번호별 통계

In [192]:
# df1.groupby(['배출가스인증번호', '제작사확인_DPF유무', '확인유무'], dropna=False)['차대번호'].count().to_excel('analysis2/DPF현행화/배인번호별_DPF유무수정별_확인유무.xlsx')

## 배인번호별, 배인번호_수정별, 등급별, DPF유무별, 제작사확인_DPF유무별 차대번호 개수

In [58]:
df1.groupby(['배출가스인증번호', '배인번호_수정', '제작사명', 'DPF유무', 'DPF유무_수정', '등급'], dropna=False)['차대번호'].count().unstack(level='등급')

등급                                                        4
배출가스인증번호     배인번호_수정      제작사명          DPF유무 DPF유무_수정
4MY-AD-20    4MY-AD-20    아우디폭스바겐코리아(주) 무     확인불가       29
4MY-DC-33    6MY-DC-23-17 타타대우상용차(주)    무     유           7
4MY-PA-06    확인불가         (주)볼보자동차코리아   무     확인불가       13
5MY-AD-13-06 5MY-AD-13-06 아우디폭스바겐코리아(주) 무     확인불가      347
                          자기인증면제차량      무     확인불가        1
...                                                     ...
NaN          NaN          한성자동차(주)      무     NaN         1
                          한아에스에스(주)     무     NaN         1
                          해광산업사         무     NaN         1
                          현대자동차(주)      무     NaN        11
                          NaN           무     NaN         1

[829 rows x 1 columns]

In [59]:
today_date = datetime.datetime.today().strftime("%Y.%m.%d_%p.%I.%M.%S")
today_date

'2023.03.10_PM.02.14.35'

### [출력] 통계

In [60]:
df1.groupby(['배출가스인증번호', '배인번호_수정', '제작사명', 'DPF유무', 'DPF유무_수정', '등급'], dropna=False)['차대번호'].count().unstack(level='등급').to_excel(os.path.join(analysis_fold, f'통계_배인번호별_배인번호수정별_제작사명별_등급별_DPF유무별_DPF유무수정별_차량대수_{today_date}.xlsx'))

# [출력] 수정파일

In [61]:
fold

'D:/data/big2/BD1_4등급_데이터_점검1'

In [62]:
today_date = datetime.datetime.today().strftime("%Y.%m.%d_%p.%I.%M.%S")
today_date

'2023.03.10_PM.02.14.58'

In [63]:
df1.columns

Index(['차대번호', '차량번호_x', '제원관리번호', '차종_원본', '용도', '최초등록일', '연식', '제작일자',
       '검사유효일', '배출가스인증번호', '등급', '차명_x', '차종분류', '차종유형', '자동차형식', '제작사명',
       '연료', '엔진형식_x', '총중량', '적재중량', '엔진출력', '배기량', '법정동코드', '시도명', '시군구명',
       '소유자구분', '말소여부', '일치유무', '사용연료', '주행거리', '차명_y', '차량번호_y', '차종', '차량연식',
       '엔진형식_y', '검사방법', '검사일자', '검사종류', '검사판정시각', '검사판정', '산소값', '이산화탄소값',
       '무부하매연판정1', '무부하매연판정2', '무부하매연판정3', '무부하매연판정4', '무부하매연판정5', '무부하매연판정6',
       '무부하매연허용치1', '무부하매연허용치2', '무부하매연허용치3', '무부하매연허용치4', '무부하매연허용치5',
       '무부하매연허용치6', '무부하매연측정치1', '무부하매연측정치2', '무부하매연측정치3', '무부하매연측정치4',
       '무부하매연측정치5', '무부하매연측정치6', '정기정밀', 'vin10', 'vin_year', 'DPF유무',
       '배인번호_수정', '등급_수정', 'DPF유무_수정', '확인유무', '비고', '제작사_확인불가'],
      dtype='object')

In [64]:
df2 = df1[['차대번호', '차량번호_x', '제원관리번호', '차종_원본', '용도', '최초등록일', '연식', '제작일자',
       '검사유효일', '배출가스인증번호', '등급', '차명_x', '차종분류', '차종유형', '자동차형식', '제작사명',
       '연료', '엔진형식_x', '총중량', '적재중량', '엔진출력', '배기량', '법정동코드', '시도명', '시군구명',
       '소유자구분', '말소여부', '일치유무']]
df2 = df2.rename(columns={'차량번호_x':'차량번호', '차명_x':'차명', '엔진형식_x':'엔진형식'})
df2.columns

Index(['차대번호', '차량번호', '제원관리번호', '차종_원본', '용도', '최초등록일', '연식', '제작일자', '검사유효일',
       '배출가스인증번호', '등급', '차명', '차종분류', '차종유형', '자동차형식', '제작사명', '연료', '엔진형식',
       '총중량', '적재중량', '엔진출력', '배기량', '법정동코드', '시도명', '시군구명', '소유자구분', '말소여부',
       '일치유무'],
      dtype='object')

In [65]:
# about 32s
df2.to_csv(os.path.join(fold, f'4등급_차량_리스트_양식_result_수정_{today_date}.csv'), index=False, encoding='cp949')

In [66]:
# about 32s
df2.iloc[:580000].to_csv(os.path.join(fold, f'4등급_차량_리스트_양식_result_수정_{today_date}_01.csv'), index=False, encoding='cp949')
df2.iloc[580000:].to_csv(os.path.join(fold, f'4등급_차량_리스트_양식_result_수정_{today_date}_02.csv'), index=False, encoding='cp949')

# 특정 배인번호 차량 확인

In [ ]:
df1.loc[(df1['배출가스인증번호'] == 'AMY-JL-13-9') | (df1['배출가스인증번호'] == '7MY-PA-13-11')]

,차대번호,차량번호_x,제원관리번호,차종_원본,용도,최초등록일,연식,제작일자,검사유효일,배출가스인증번호,...,무부하매연측정치1,무부하매연측정치2,무부하매연측정치3,무부하매연측정치4,무부하매연측정치5,무부하매연측정치6,정기정밀,vin10,vin_year,DPF유무
109,SALFA24C47H048936,63러5501,00920002900011307,승용,자가용,20080305,2007,20071001.0,20220414.0,7MY-PA-13-11,...,0.0,4280.0,NaN,NaN,NaN,NaN,정밀,7,2007.0,무
449,SALFA2BC0AH178531,32노6435,04220000900021309,승용,자가용,20100209,2010,20100205.0,20200208.0,AMY-JL-13-9,...,15.0,NaN,NaN,NaN,NaN,NaN,정기,A,2010.0,무
1242,SALFA2BC7AH178123,35조9499,04220000900021309,승용,자가용,20100409,2010,20100205.0,20200524.0,AMY-JL-13-9,...,3.0,4667.0,NaN,NaN,NaN,NaN,정밀,A,2010.0,무
1612,SALFA2BC4AH189225,26주7299,04220000900021309,승용,자가용,20100511,2010,20100506.0,20240612.0,AMY-JL-13-9,...,0.0,4208.0,0.0,0.0,0.0,0.0,정밀,A,2010.0,무
2321,SALFA2BC9AH164580,29소4495,04220000900021309,승용,자가용,20091123,2010,20091123.0,20191122.0,AMY-JL-13-9,...,0.0,4125.0,0.0,0.0,0.0,0.0,정밀,A,2010.0,무
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1134836,SALFA24C08H100967,68고4169,00920002900021307,승용,자가용,20080522,2008,20080515.0,20220521.0,7MY-PA-13-11,...,0.0,NaN,NaN,NaN,NaN,NaN,정기,8,2008.0,무
1146852,SALFA2BC9AH165020,140저3674,04220000900021309,승용,자가용,20100108,2010,20091102.0,20240306.0,AMY-JL-13-9,...,0.0,4180.0,NaN,NaN,NaN,NaN,정밀,A,2010.0,무
1149102,SALFA2BCXAH200230,37루4288,04220000900021309,승용,자가용,20100723,2010,20100722.0,20200722.0,AMY-JL-13-9,...,0.0,3880.0,NaN,NaN,NaN,NaN,정밀,A,2010.0,무
1150274,SALFA2BC8AH197697,20라6126,04220000900021309,승용,자가용,20100723,2010,20100611.0,20220722.0,AMY-JL-13-9,...,0.0,NaN,NaN,NaN,NaN,NaN,정기,A,2010.0,무
1152810,SALFA24C87H037387,48루9729,00920002900011307,승용,자가용,20070914,2007,20070703.0,20230913.0,7MY-PA-13-11,...,0.0,4280.0,NaN,NaN,NaN,NaN,정밀,7,2007.0,무

In [ ]:
df1.loc[(df1['배출가스인증번호'] == 'AMY-JL-13-9') | (df1['배출가스인증번호'] == '7MY-PA-13-11')].to_excel(os.path.join(analysis_fold, 'AMY-JL-13-9_and_7MY-PA-13-11.xlsx'), index=False)

In [ ]:
df1.loc[(df1['배출가스인증번호'] == '5MY-HB-24-02') | (df1['배출가스인증번호'] == '5MY-HB-24-03')]

,차대번호,차량번호_x,제원관리번호,차종_원본,용도,최초등록일,연식,제작일자,검사유효일,배출가스인증번호,...,무부하매연측정치1,무부하매연측정치2,무부하매연측정치3,무부하매연측정치4,무부하매연측정치5,무부하매연측정치6,정기정밀,vin10,vin_year,DPF유무
34743,KL90A3ABD6H006384,16루6370,00620000500121206,승용,자가용,20070220,2006,20070116.0,20230219.0,5MY-HB-24-02,...,1.0,NaN,NaN,NaN,NaN,NaN,정밀,6,2006.0,무
40794,KL90A3ABD6H006358,32소5253,00620000500121206,승용,자가용,20060928,2006,20060424.0,20200927.0,5MY-HB-24-02,...,2.0,NaN,NaN,NaN,NaN,NaN,정기,6,2006.0,무
51968,VF3EBRHME6Z002407,06머6104,00620000600011205,승용,자가용,20060315,2006,20051221.0,20200415.0,5MY-HB-24-03,...,7.0,0.0,0.0,0.0,0.0,0.0,정밀,6,2006.0,무
62374,KL90A3ABD6H006183,30수3886,00620000500081205,승용,자가용,20060529,2006,20051230.0,20180528.0,5MY-HB-24-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2006.0,무
66090,KL90A3ABD6H006331,05저1188,00620000500121206,승용,자가용,20060630,2006,20060627.0,20190701.0,5MY-HB-24-02,...,24.0,NaN,NaN,NaN,NaN,NaN,정밀,6,2006.0,무
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106097,KL90A3ABD6NZ00001,48누2889,00034817000181209,승용,자가용,20090213,2006,20090205.0,20210614.0,5MY-HB-24-02,...,0.0,0.0,0.0,0.0,0.0,0.0,정밀,6,2006.0,무
1141890,KL90A3ABD6H006174,04누7174,00620000500081205,승용,자가용,20060207,2006,20060207.0,20220206.0,5MY-HB-24-02,...,0.0,NaN,NaN,NaN,NaN,NaN,정기,6,2006.0,무
1142453,KL90A3ABD6H006063,21어7216,00620000500081205,승용,자가용,20051013,2006,20051008.0,20191012.0,5MY-HB-24-02,...,0.0,NaN,NaN,NaN,NaN,NaN,정밀,6,2006.0,무
1143160,KL90A3ABD6H006339,54라3464,00620000500121206,승용,자가용,20060818,2006,20060124.0,20240817.0,5MY-HB-24-02,...,4.0,NaN,NaN,NaN,NaN,NaN,정기,6,2006.0,무
1144461,KL90A3ABD6H006217,05수4718,00620000500121206,승용,자가용,20060306,2006,20060112.0,20240511.0,5MY-HB-24-02,...,1.0,NaN,NaN,NaN,NaN,NaN,정밀,6,2006.0,무

In [ ]:
df1.loc[(df1['배출가스인증번호'] == '5MY-HB-24-02') | (df1['배출가스인증번호'] == '5MY-HB-24-03')].to_excel(os.path.join(analysis_fold, '5MY-HB-24-02_and_5MY-HB-24-03.xlsx'), index=False)

In [ ]:
df1.loc[(df1['배출가스인증번호'] == '5MY-VTK-24-01') | (df1['배출가스인증번호'] == '7MY-VTK-24-01') | (df1['배출가스인증번호'] == '7MY-VTK-24-02')]

,차대번호,차량번호_x,제원관리번호,차종_원본,용도,최초등록일,연식,제작일자,검사유효일,배출가스인증번호,...,무부하매연측정치1,무부하매연측정치2,무부하매연측정치3,무부하매연측정치4,무부하매연측정치5,무부하매연측정치6,정기정밀,vin10,vin_year,DPF유무
1375,YV2ABS0C38A667922,인천98바5911,01120000500804307,특수,영업용,20080617,2008,20080519.0,20230312.0,7MY-VTK-24-01,...,1.0,1.0,1.0,1880.0,310.0,NaN,정밀,8,2008.0,무
1672,YV2ABS0C98A661686,경기99바9336,01120000500804307,특수,영업용,20080407,2008,20080325.0,20191119.0,7MY-VTK-24-01,...,0.0,NaN,NaN,NaN,NaN,NaN,정기,8,2008.0,무
3674,YV2ABS0C5AA691614,부산99사9893,01120000501024309,특수,영업용,20100311,2010,20091116.0,20201226.0,7MY-VTK-24-01,...,2.0,2.0,1.0,1840.0,275.0,NaN,정밀,A,2010.0,무
4273,YV2ABS0C28A664915,경남99사6949,01120000500724307,특수,영업용,20080502,2008,20080423.0,20220309.0,7MY-VTK-24-01,...,4.0,4.0,2.0,1880.0,270.0,NaN,정밀,8,2008.0,무
5030,YV2ABS0C5AA691239,경기99아4579,01120000501144309,특수,영업용,20100125,2010,20091116.0,20190724.0,7MY-VTK-24-01,...,2.0,0.0,0.0,1790.0,285.0,NaN,정밀,A,2010.0,무
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1149078,YV2JFY0C788876157,경기99아2325,01120000500754307,특수,영업용,20080307,2008,20080124.0,20201212.0,7MY-VTK-24-02,...,7.0,5.0,0.0,1800.0,275.0,NaN,정밀,8,2008.0,무
1150303,YV2ABS0C8AA693812,경북98사1855,01120000501054309,특수,영업용,20100416,2010,20100208.0,20210521.0,7MY-VTK-24-01,...,0.0,0.0,0.0,1770.0,363.0,0.0,정밀,A,2010.0,무
1152245,YV2ABS0C28A671444,광주99사3069,01120000500724307,특수,영업용,20080826,2008,20080714.0,20190930.0,7MY-VTK-24-01,...,9.0,11.0,18.0,1760.0,298.0,NaN,정밀,8,2008.0,무
1152683,YV2ABS0C39A680316,전남98사7904,01120000500954308,특수,영업용,20090806,2009,20090102.0,20200801.0,7MY-VTK-24-01,...,2.0,1.0,0.0,1810.0,265.0,NaN,정밀,9,2009.0,무
1153561,YV2JFY0C49A690960,경북98아8224,01120000500914308,특수,영업용,20091217,2009,20091022.0,20210426.0,7MY-VTK-24-02,...,1.0,NaN,NaN,NaN,NaN,NaN,정기,9,2009.0,무

In [ ]:
df1.loc[(df1['배출가스인증번호'] == '5MY-VTK-24-01') | (df1['배출가스인증번호'] == '7MY-VTK-24-01') | (df1['배출가스인증번호'] == '7MY-VTK-24-02')].to_excel(os.path.join(analysis_fold, '5MY-VTK-24-01_and_7MY-VTK-24-01_and_7MY-VTK-24-02.xlsx'), index=False)

# CODE End