# Library

In [1]:
import pandas as pd
# import modin.pandas as pd
import os
import numpy as np
from tqdm import tqdm

In [2]:
# 소수점 옵션
pd.options.display.float_format = '{:.2f}'.format
# pd.reset_option('display.float_format')

In [3]:
# 5. [e]배출가스인증 자동차정보(CEG_EMIS_CERTI_VEH_MIG)
# - STD_CEG_EMIS_CERTI_VEH_MIG.csv 없음.

## [Path] Fold

In [3]:
# file path(pandas)

# ODS : D:/과업/[한국환경공단]자동차_환경_빅데이터_구축_2차/data/ODS
# STD : D:/과업/[한국환경공단]자동차_환경_빅데이터_구축_2차/data/STD

ods_path = 'D:/data/big2/ODS'
std_path = 'D:/data/big2/STD'

## 1\. 자동차 등록정보(CEG_CAR_MIG)
- [⭕] STD_CEG_CAR_MIG_21.csv 파일 로드 오류

### 파일 병합

In [34]:
# # pandas : about 15 ~ 17m
# # modin : about 36m

# todf = pd.DataFrame()
# tsdf = pd.DataFrame()

# for i in tqdm(range(1, 31)):
#     try:
#         ods_file_name = f'ODS_CEG_CAR_MIG_{i}'
#         std_file_name = f'STD_CEG_CAR_MIG_{i}'
#         opath = os.path.join(ods_path, ods_file_name + '.csv')
#         spath = os.path.join(std_path, std_file_name + '.csv')
#         odf = pd.read_csv(opath, low_memory=False)
#         sdf = pd.read_csv(spath, low_memory=False)
#         todf = pd.concat([todf, odf], ignore_index=True)
#         tsdf = pd.concat([tsdf, sdf], ignore_index=True)
#     except:
#         print(f'ODS_CEG_CAR_MIG_{i}', f'STD_CEG_CAR_MIG_{i}')
#         pass
# todf.shape, tsdf.shape

100%|██████████| 30/30 [16:11<00:00, 32.38s/it]

((29534047, 32), (29415224, 25))

#### [출력] 통합파일

In [ ]:
# # 소요시간 : 약 18 ~ 22m
# todf.to_csv(os.path.join(ods_path, 'ODS_CEG_CAR_MIG.csv'))
# tsdf.to_csv(os.path.join(std_path, 'STD_CEG_CAR_MIG.csv'))

### [로드] 통합파일

In [5]:
# pandas :about 14m
name = 'CEG_CAR_MIG'
todf = pd.read_csv(os.path.join(ods_path, f'ODS_{name}.csv'), index_col=0)
tsdf = pd.read_csv(os.path.join(std_path, f'STD_{name}.csv'), index_col=0)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_4312\1836175094.py:4: DtypeWarning: Columns (14,16,19,27) have mixed types. Specify dtype option on import or set low_memory=False.
  todf = pd.read_csv(os.path.join(ods_path, f'ODS_{name}.csv'), index_col=0)

In [6]:
todf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29534047 entries, 0 to 29534046
Data columns (total 32 columns):
 #   Column             Dtype
---  ------             -----
 0   VHMNO              object
 1   VHRNO              object
 2   BSPL_LEDO_CD       int64
 3   OWNR_SE            object
 4   VHCTY              object
 5   PURPS              object
 6   NOW_OWNR_NM        object
 7   NOW_MBERNO         object
 8   BSPL_ADRS          object
 9   OWNR_ADRS          object
 10  VIN                object
 11  FST_REG_DE         int64
 12  VHCL_YRIDNW        int64
 13  VHCL_MNFCT_DE      object
 14  EMIS_INSP_EFCT_DE  float64
 15  SRCMNNO            object
 16  EMIS_CRTCNO        object
 17  EMIS_GRD           object
 18  LEM_YN             object
 19  LEM_KND            float64
 20  LEM_STRCHG_YN      object
 21  BSPL_ZIP           float64
 22  VHRNO_NUM_INFO     int64
 23  VHCL_ERSR_YN       object
 24  FST_OWNR_NM        object
 25  FST_MBERNO         object
 26  ACQS_DE            object
 27  ACQS_AMT           float64
 28  RMK                object
 29  CRTN_DT            object
 30  UPDT_DT            object
 31  USER_ID            object
dtypes: float64(4), int64(4), object(24)
memory usage: 7.3+ GB

In [7]:
todf.columns

Index(['VHMNO', 'VHRNO', 'BSPL_LEDO_CD', 'OWNR_SE', 'VHCTY', 'PURPS',
       'NOW_OWNR_NM', 'NOW_MBERNO', 'BSPL_ADRS', 'OWNR_ADRS', 'VIN',
       'FST_REG_DE', 'VHCL_YRIDNW', 'VHCL_MNFCT_DE', 'EMIS_INSP_EFCT_DE',
       'SRCMNNO', 'EMIS_CRTCNO', 'EMIS_GRD', 'LEM_YN', 'LEM_KND',
       'LEM_STRCHG_YN', 'BSPL_ZIP', 'VHRNO_NUM_INFO', 'VHCL_ERSR_YN',
       'FST_OWNR_NM', 'FST_MBERNO', 'ACQS_DE', 'ACQS_AMT', 'RMK', 'CRTN_DT',
       'UPDT_DT', 'USER_ID'],
      dtype='object')

In [ ]:
todf[].head()

In [5]:
tsdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29415224 entries, 0 to 29415223
Data columns (total 25 columns):
 #   Column               Dtype
---  ------               -----
 0   ACQS_AMT             float64
 1   ACQS_YMD             object
 2   BSPL_STDG_CD         int64
 3   VHCL_REG_DT          object
 4   EXHST_GAS_CERT_NO    object
 5   EXHST_GAS_GRD_CD     object
 6   EXTGAS_INSP_VLD_YMD  float64
 7   FRST_MBR_NO          object
 8   FRST_REG_YMD         int64
 9   LEM_KND_CD           object
 10  STRCT_CHG_YN         object
 11  LEM_YN               object
 12  NOW_MBR_NO           object
 13  VHCL_OWNR_CL_CD      object
 14  PURPS_CD2            object
 15  MANP_MNG_NO          object
 16  MDFCN_DT             object
 17  VHCL_ERSR_YN         object
 18  VHCL_FBCTN_YMD       object
 19  YRIDNW               int64
 20  VHCTY_CD             object
 21  VHCL_MNG_NO          object
 22  VHRNO_FGRE_INFO      int64
 23  VIN                  object
 24  VHRNO                object
dtypes: float64(2), int64(4), object(19)
memory usage: 5.7+ GB

In [14]:
t_info = {'컬럼_수':[todf.shape[1], tsdf.shape[1]], '행_수':[todf.shape[0], tsdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수       행_수
ODS    32  29534047
STD    25  29415224

### 컬럼 확인

In [15]:
todf.columns.to_list()

['VHMNO',
 'VHRNO',
 'BSPL_LEDO_CD',
 'OWNR_SE',
 'VHCTY',
 'PURPS',
 'NOW_OWNR_NM',
 'NOW_MBERNO',
 'BSPL_ADRS',
 'OWNR_ADRS',
 'VIN',
 'FST_REG_DE',
 'VHCL_YRIDNW',
 'VHCL_MNFCT_DE',
 'EMIS_INSP_EFCT_DE',
 'SRCMNNO',
 'EMIS_CRTCNO',
 'EMIS_GRD',
 'LEM_YN',
 'LEM_KND',
 'LEM_STRCHG_YN',
 'BSPL_ZIP',
 'VHRNO_NUM_INFO',
 'VHCL_ERSR_YN',
 'FST_OWNR_NM',
 'FST_MBERNO',
 'ACQS_DE',
 'ACQS_AMT',
 'RMK',
 'CRTN_DT',
 'UPDT_DT',
 'USER_ID']

In [10]:
olist = [
   'UPDT_DT', 
   'OWNR_SE', 
   'VHRNO', 
   'BSPL_LEDO_CD', 
   'CRTN_DT', 
   'PURPS', 
   'EMIS_INSP_EFCT_DE', 
   'EMIS_CRTCNO', 
   'NOW_MBERNO', 
   'ACQS_DE', 
   'ACQS_AMT', 
   'FST_MBERNO', 
   'FST_REG_DE', 
   'VHCTY', 
   'VHRNO_NUM_INFO', 
   'VHMNO', 
   'VHCL_MNFCT_DE', 
   'VHCL_YRIDNW', 
   'VHCL_ERSR_YN', 
   'VIN', 
   'SRCMNNO', 
   'EMIS_GRD', 
   'LEM_KND', 
   'LEM_STRCHG_YN', 
   'LEM_YN', 
    
   'NOW_OWNR_NM', 
   'BSPL_ADRS', 
   'OWNR_ADRS', 
   'BSPL_ZIP', 
   'FST_OWNR_NM', 
   'RMK', 
   'USER_ID', 
   ]

odict = {
    '컬럼':olist,
    '내용':
    ['수정 일시', 
   '소유자 구분', 
   '차량등록번호', 
   '본거지 법정동 코드', 
   '생성 일시', 
   '용도', 
   '배출가스검사유효일자', 
   '배출가스 인증번호', 
   '현재 회원번호', 
   '취득 일자', 
   '취득 금액', 
   '최초 회원번호', 
   '최초 등록 일자', 
   '차종', 
   '차량등록번호 숫자 정보', 
   '차량관리번호', 
   '차량 제작 일자', 
   '차량 연식', 
   '차량 말소 YN', 
   '차대번호', 
   '제원관리번호', 
   '배출가스 등급', 
   '저공해조치 종류', 
   '저공해조치 구조변경 YN', 
   '저공해조치 YN(미사용)', 
    
   'NOW_OWNR_NM', 
   'BSPL_ADRS', 
   'OWNR_ADRS', 
   'BSPL_ZIP', 
   'FST_OWNR_NM', 
   'RMK', 
   'USER_ID', ]
    }

ocol = pd.DataFrame(odict)
ocol

                   컬럼             내용
0             UPDT_DT          수정 일시
1             OWNR_SE         소유자 구분
2               VHRNO         차량등록번호
3        BSPL_LEDO_CD     본거지 법정동 코드
4             CRTN_DT          생성 일시
5               PURPS             용도
6   EMIS_INSP_EFCT_DE     배출가스검사유효일자
7         EMIS_CRTCNO      배출가스 인증번호
8          NOW_MBERNO        현재 회원번호
9             ACQS_DE          취득 일자
10           ACQS_AMT          취득 금액
11         FST_MBERNO        최초 회원번호
12         FST_REG_DE       최초 등록 일자
13              VHCTY             차종
14     VHRNO_NUM_INFO   차량등록번호 숫자 정보
15              VHMNO         차량관리번호
16      VHCL_MNFCT_DE       차량 제작 일자
17        VHCL_YRIDNW          차량 연식
18       VHCL_ERSR_YN       차량 말소 YN
19                VIN           차대번호
20            SRCMNNO         제원관리번호
21           EMIS_GRD        배출가스 등급
22            LEM_KND       저공해조치 종류
23      LEM_STRCHG_YN  저공해조치 구조변경 YN
24             LEM_YN  저공해조치 YN(미사용)
25        NOW_OWNR_NM             미정
26          BSPL_ADRS             미정
27          OWNR_ADRS             미정
28           BSPL_ZIP             미정
29        FST_OWNR_NM             미정
30                RMK             미정
31            USER_ID             미정

In [17]:
tsdf.columns.to_list()

['ACQS_AMT',
 'ACQS_YMD',
 'BSPL_STDG_CD',
 'VHCL_REG_DT',
 'EXHST_GAS_CERT_NO',
 'EXHST_GAS_GRD_CD',
 'EXTGAS_INSP_VLD_YMD',
 'FRST_MBR_NO',
 'FRST_REG_YMD',
 'LEM_KND_CD',
 'STRCT_CHG_YN',
 'LEM_YN',
 'NOW_MBR_NO',
 'VHCL_OWNR_CL_CD',
 'PURPS_CD2',
 'MANP_MNG_NO',
 'MDFCN_DT',
 'VHCL_ERSR_YN',
 'VHCL_FBCTN_YMD',
 'YRIDNW',
 'VHCTY_CD',
 'VHCL_MNG_NO',
 'VHRNO_FGRE_INFO',
 'VIN',
 'VHRNO']

In [11]:
slist = [
    'MDFCN_DT', 
    'VHCL_OWNR_CL_CD', 
    'VHRNO',
    'BSPL_STDG_CD', 
    'VHCL_REG_DT', 
    'PURPS_CD2', 
    'EXTGAS_INSP_VLD_YMD', 
    'EXHST_GAS_CERT_NO', 
    'NOW_MBR_NO', 
    'ACQS_YMD', 
    'ACQS_AMT', 
    'FRST_MBR_NO', 
    'FRST_REG_YMD', 
    'VHCTY_CD', 
    'VHRNO_FGRE_INFO', 
    'VHCL_MNG_NO', 
    'VHCL_FBCTN_YMD', 
    'YRIDNW', 
    'VHCL_ERSR_YN', 
    'VIN', 
    'MANP_MNG_NO', 
    'EXHST_GAS_GRD_CD', 
    'LEM_KND_CD', 
    'STRCT_CHG_YN', 
    'LEM_YN', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['수정일시', 
    '차량소유자분류코드', 
    '자동차등록번호',
    '본거지법정동코드', 
    '차량등록일시', 
    '용도코드2', 
    '배출가스검사유효일자', 
    '배출가스인증번호', 
    '현재회원번호', 
    '취득일자', 
    '취득금액', 
    '최초회원번호', 
    '최초등록일자', 
    '차종코드', 
    '자동차등록번호숫자정보', 
    '차량관리번호', 
    '차량제작일자', 
    '연식', 
    '차량말소여부', 
    '차대번호', 
    '제원관리번호', 
    '배출가스등급', 
    '저공해조치종류코드', 
    '구조변경여부', 
    '저공해조치여부',  ]
    }

scol = pd.DataFrame(sdict)
scol

                     컬럼           내용
0              MDFCN_DT         수정일시
1       VHCL_OWNR_CL_CD    차량소유자분류코드
2                 VHRNO      자동차등록번호
3          BSPL_STDG_CD     본거지법정동코드
4           VHCL_REG_DT       차량등록일시
5             PURPS_CD2        용도코드2
6   EXTGAS_INSP_VLD_YMD   배출가스검사유효일자
7     EXHST_GAS_CERT_NO     배출가스인증번호
8            NOW_MBR_NO       현재회원번호
9              ACQS_YMD         취득일자
10             ACQS_AMT         취득금액
11          FRST_MBR_NO       최초회원번호
12         FRST_REG_YMD       최초등록일자
13             VHCTY_CD         차종코드
14      VHRNO_FGRE_INFO  자동차등록번호숫자정보
15          VHCL_MNG_NO       차량관리번호
16       VHCL_FBCTN_YMD       차량제작일자
17               YRIDNW           연식
18         VHCL_ERSR_YN       차량말소여부
19                  VIN         차대번호
20          MANP_MNG_NO       제원관리번호
21     EXHST_GAS_GRD_CD       배출가스등급
22           LEM_KND_CD    저공해조치종류코드
23         STRCT_CHG_YN       구조변경여부
24               LEM_YN      저공해조치여부

### 데이터 info

In [11]:
# about
odf2 = todf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = tsdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,UPDT_DT,수정 일시,21887726,MDFCN_DT,수정일시,21716051.0,171675.0,7646321,7699173.0
1,OWNR_SE,소유자 구분,29534047,VHCL_OWNR_CL_CD,차량소유자분류코드,29415224.0,118823.0,0,0.0
2,VHRNO,차량등록번호,29534047,VHRNO,자동차등록번호,29415224.0,118823.0,0,0.0
3,BSPL_LEDO_CD,본거지 법정동 코드,29534047,BSPL_STDG_CD,본거지법정동코드,29415224.0,118823.0,0,0.0
4,CRTN_DT,생성 일시,29534047,VHCL_REG_DT,차량등록일시,29415224.0,118823.0,0,0.0

In [12]:
odf2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29534047 entries, 0 to 29534046
Data columns (total 32 columns):
 #   Column             Dtype
---  ------             -----
 0   UPDT_DT            object
 1   OWNR_SE            object
 2   VHRNO              object
 3   BSPL_LEDO_CD       int64
 4   CRTN_DT            object
 5   PURPS              object
 6   EMIS_INSP_EFCT_DE  float64
 7   EMIS_CRTCNO        object
 8   NOW_MBERNO         object
 9   ACQS_DE            object
 10  ACQS_AMT           float64
 11  FST_MBERNO         object
 12  FST_REG_DE         int64
 13  VHCTY              object
 14  VHRNO_NUM_INFO     int64
 15  VHMNO              object
 16  VHCL_MNFCT_DE      object
 17  VHCL_YRIDNW        int64
 18  VHCL_ERSR_YN       object
 19  VIN                object
 20  SRCMNNO            object
 21  EMIS_GRD           object
 22  LEM_KND            float64
 23  LEM_STRCHG_YN      object
 24  LEM_YN             object
 25  NOW_OWNR_NM        object
 26  BSPL_ADRS          object
 27  OWNR_ADRS          object
 28  BSPL_ZIP           float64
 29  FST_OWNR_NM        object
 30  RMK                object
 31  USER_ID            object
dtypes: float64(4), int64(4), object(24)
memory usage: 7.3+ GB

In [13]:
odf2['VIN'].isnull().sum()

0

In [14]:
sdf2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 29415224 entries, 0 to 29415223
Data columns (total 25 columns):
 #   Column               Dtype
---  ------               -----
 0   MDFCN_DT             object
 1   VHCL_OWNR_CL_CD      object
 2   VHRNO                object
 3   BSPL_STDG_CD         int64
 4   VHCL_REG_DT          object
 5   PURPS_CD2            object
 6   EXTGAS_INSP_VLD_YMD  float64
 7   EXHST_GAS_CERT_NO    object
 8   NOW_MBR_NO           object
 9   ACQS_YMD             object
 10  ACQS_AMT             float64
 11  FRST_MBR_NO          object
 12  FRST_REG_YMD         int64
 13  VHCTY_CD             object
 14  VHRNO_FGRE_INFO      int64
 15  VHCL_MNG_NO          object
 16  VHCL_FBCTN_YMD       object
 17  YRIDNW               int64
 18  VHCL_ERSR_YN         object
 19  VIN                  object
 20  MANP_MNG_NO          object
 21  EXHST_GAS_GRD_CD     object
 22  LEM_KND_CD           object
 23  STRCT_CHG_YN         object
 24  LEM_YN               object
dtypes: float64(2), int64(4), object(19)
memory usage: 5.7+ GB

In [15]:
sdf2['VIN'].isnull().sum()

0

### [출력] 컬럼명, 결측치 통계

In [46]:
name = 'CEG_CAR_MIG'

In [47]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

C:\Users\kbjung\AppData\Local\Temp\ipykernel_15588\1252313295.py:6: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  texcel.save()

[정제]CEG_CAR_MIG.xlsx 출력완료.

### [분석]

#### 차대번호(VIN) 개수 차이

In [ ]:
# about 1m
len(set(odf2['VIN'].unique())), len(set(sdf2['VIN'].unique()))

(28521650, 28403389)

In [ ]:
temp = set(odf2['VIN'].unique()) - set(sdf2['VIN'].unique())
len(temp)

1118137

#### 제원관리번호 unique

In [ ]:
len(odf2['SRCMNNO'].unique()), len(sdf2['MANP_MNG_NO'].unique())

(254065, 254212)

In [ ]:
temp = set(odf2['SRCMNNO'].unique()) - set(sdf2['MANP_MNG_NO'].unique())
len(temp)

6461

### 말소 차량 제거

In [6]:
todf['VHCL_ERSR_YN'].unique()

array(['N', 'Y'], dtype=object)

In [7]:
todf['VHCL_ERSR_YN'].value_counts()

N    25693532
Y     3840515
Name: VHCL_ERSR_YN, dtype: int64

In [8]:
todf.shape

(29534047, 32)

In [ ]:
# about 3m
odf3 = todf[todf['VHCL_ERSR_YN'] == 'N'].reset_index(drop=True)
odf3.shape

In [10]:
tsdf['VHCL_ERSR_YN'].unique()

array(['Y', 'N'], dtype=object)

In [11]:
tsdf['VHCL_ERSR_YN'].value_counts()

N    25623617
Y     3791607
Name: VHCL_ERSR_YN, dtype: int64

In [12]:
tsdf.shape

(29415224, 25)

In [13]:
# about 2m
sdf3 = tsdf[tsdf['VHCL_ERSR_YN'] == 'N'].reset_index(drop=True)
sdf3.shape

(25623617, 25)

In [24]:
# # about 16m
# odf3.to_csv(os.path.join(ods_path, f'ODS_{name}(말소제거).csv'), index=False)
# sdf3.to_csv(os.path.join(ods_path, f'STD_{name}(말소제거).csv'), index=False)

#### [로드] 말소제거 데이터

In [6]:
# about 11m 10s
name = 'CEG_CAR_MIG'
odf3 = pd.read_csv(os.path.join(ods_path, f'ODS_{name}(말소제거).csv'), low_memory=False)
sdf3 = pd.read_csv(os.path.join(std_path, f'STD_{name}(말소제거).csv'), low_memory=False)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21372\1405534301.py:3: DtypeWarning: Columns (13,15,18,26) have mixed types. Specify dtype option on import or set low_memory=False.
  odf3 = pd.read_csv(os.path.join(ods_path, f'ODS_{name}(말소제거).csv'))
C:\Users\kbjung\AppData\Local\Temp\ipykernel_21372\1405534301.py:4: DtypeWarning: Columns (1,9,15,18) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf3 = pd.read_csv(os.path.join(std_path, f'STD_{name}(말소제거).csv'))

In [8]:
t_info = {'컬럼_수':[odf3.shape[1], sdf3.shape[1]], '행_수':[odf3.shape[0], sdf3.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수       행_수
ODS    32  25693532
STD    25  25623617

In [12]:
# about 3m 25s
odf4 = odf3[olist]
ocount = odf4.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf4 = sdf3[slist]
scount = sdf4.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf4.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf4.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,UPDT_DT,수정 일시,18048294,MDFCN_DT,수정일시,17925522.0,122772.0,7645238,7698095.0
1,OWNR_SE,소유자 구분,25693532,VHCL_OWNR_CL_CD,차량소유자분류코드,25623617.0,69915.0,0,0.0
2,VHRNO,차량등록번호,25693532,VHRNO,자동차등록번호,25623617.0,69915.0,0,0.0
3,BSPL_LEDO_CD,본거지 법정동 코드,25693532,BSPL_STDG_CD,본거지법정동코드,25623617.0,69915.0,0,0.0
4,CRTN_DT,생성 일시,25693532,VHCL_REG_DT,차량등록일시,25623617.0,69915.0,0,0.0

#### [출력] 컬럼명, 결측치 통계

In [13]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}(말소적용).xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}(말소적용).xlsx 출력완료.')

[정제]CEG_CAR_MIG(말소적용).xlsx 출력완료.

#### [분석]

##### 차대번호(VIN) 개수 차이

In [ ]:
# about 1m
len(set(odf3['VIN'].unique())), len(set(sdf3['VIN'].unique()))

(28521650, 28403389)

In [ ]:
temp = set(odf3['VIN'].unique()) - set(sdf3['VIN'].unique())
len(temp)

1118137

##### 제원관리번호 unique

In [ ]:
len(odf3['SRCMNNO'].unique()), len(sdf3['MANP_MNG_NO'].unique())

(254065, 254212)

In [ ]:
temp = set(odf3['SRCMNNO'].unique()) - set(sdf3['MANP_MNG_NO'].unique())
len(temp)

6461

## 2\. 자동차 제원정보(CEG_CAR_SRC_MIG)

### 파일명 설정

In [4]:
name = 'CEG_CAR_SRC_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

28 25
(545374, 28) (545374, 25)

In [5]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS    28  545374
STD    25  545374

### 컬럼 확인

In [6]:
odf.columns.to_list()

['SRCMNNO',
 'VHCNM',
 'VHCTY',
 'VHCTY_CL',
 'VHCTY_TY',
 'CAR_FRM',
 'MKR_NM',
 'FUEL',
 'EGINTY',
 'EMPV_WGHT',
 'TOT_WGHT',
 'CRYNG_WGHT',
 'EGINPWR',
 'DSPLVL',
 'TKCAR_NMPR',
 'VHCL_LT',
 'VHCL_WH',
 'VHCL_HG',
 'PLOR_NM',
 'REPCAR_NM',
 'DELE_YN',
 'CNFRM_DE',
 'DRV_FRM',
 'GEARBOX_KND',
 'RMK',
 'CRTN_DT',
 'UPDT_DT',
 'USER_ID']

In [11]:
olist = [
    'UPDT_DT', 
    'CNFRM_DE', 
    'DELE_YN', 
    'CRTN_DT', 
    'TOT_WGHT', 
    'VHCTY_TY', 
    'VHCTY_CL', 
    'VHCTY', 
    'VHCNM', 
    'VHCL_HG',
    'VHCL_WH', 
    'VHCL_LT', 
    'DRV_FRM', 
    'MKR_NM', 
    'SRCMNNO', 
    'CRYNG_WGHT',
    'CAR_FRM',
    'EMPV_WGHT', 
    'PLOR_NM', 
    'FUEL', 
    'EGINTY', 
    'EGINPWR', 
    'TKCAR_NMPR', 
    'DSPLVL', 
    'GEARBOX_KND',
    
    'REPCAR_NM', 
    'RMK', 
    'USER_ID',
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['수정 일시', 
    '승인 일자', 
    '삭제 YN', 
    '생성 일시', 
    '총 중량', 
    '차종 유형 (소분류)', 
    '차종 분류', 
    '차종', 
    '차명', 
    '차량 높이',
    '차량 너비', 
    '차량 길이', 
    '구동 형식', 
    '제작사 명', 
    '제원관리번호', 
    '적재 중량',
    '자동차 형식',
    '공차중량', 
    '원산지 명', 
    '연료', 
    '엔진형식', 
    '엔진출력', 
    '승차 인원', 
    '배기량', 
    '변속기 종류',
    
    'REPCAR_NM', 
    'RMK', 
    'USER_ID',]
    }

ocol = pd.DataFrame(odict)
ocol

             컬럼           내용
0       UPDT_DT        수정 일시
1      CNFRM_DE        승인 일자
2       DELE_YN        삭제 YN
3       CRTN_DT        생성 일시
4      TOT_WGHT         총 중량
5      VHCTY_TY  차종 유형 (소분류)
6      VHCTY_CL        차종 분류
7         VHCTY           차종
8         VHCNM           차명
9       VHCL_HG        차량 높이
10      VHCL_WH        차량 너비
11      VHCL_LT        차량 길이
12      DRV_FRM        구동 형식
13       MKR_NM        제작사 명
14      SRCMNNO       제원관리번호
15   CRYNG_WGHT        적재 중량
16      CAR_FRM       자동차 형식
17    EMPV_WGHT         공차중량
18      PLOR_NM        원산지 명
19         FUEL           연료
20       EGINTY         엔진형식
21      EGINPWR         엔진출력
22   TKCAR_NMPR        승차 인원
23       DSPLVL          배기량
24  GEARBOX_KND       변속기 종류
25    REPCAR_NM           미정
26          RMK           미정
27      USER_ID           미정

In [12]:
sdf.columns.to_list()

['VHCL_FRM',
 'APRV_YMD',
 'VHCL_REG_DT',
 'CRYNG_WGHT',
 'DEL_YN',
 'VHCL_DRVE_FRM_CD',
 'DSPLVL',
 'EGIN_OTPT',
 'EGIN_TY',
 'EMPV_WGHT',
 'FUEL_CD',
 'GEARBOX_KND_CD',
 'MNFCTR_NM',
 'FBCTN_NTN_NM',
 'MANP_MNG_NO',
 'TKCAR_PSCP',
 'TOTL_WGHT',
 'MDFCN_DT',
 'OVRHG',
 'OVRLH',
 'OVRWD',
 'VHCNM',
 'VHCTY_CD',
 'VHCTY_CL_CD',
 'VHCTY_TY_CD2']

In [13]:
slist = [
    'MDFCN_DT', 
    'APRV_YMD', 
    'DEL_YN',
    'VHCL_REG_DT', 
    'TOTL_WGHT', 
    'VHCTY_TY_CD2',
    'VHCTY_CL_CD', 
    'VHCTY_CD', 
    'VHCNM', 
    'OVRHG', 
    'OVRWD',
    'OVRLH', 
    'VHCL_DRVE_FRM_CD', 
    'MNFCTR_NM', 
    'MANP_MNG_NO',
    'CRYNG_WGHT', 
    'VHCL_FRM', 
    'EMPV_WGHT',
    'FBCTN_NTN_NM', 
    'FUEL_CD', 
    'EGIN_TY', 
    'EGIN_OTPT', 
    'TKCAR_PSCP', 
    'DSPLVL', 
    'GEARBOX_KND_CD', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['수정일시', 
    '승인일자', 
    '삭제여부',
    '차량등록일시', 
    '총중량', 
    '차종유형코드2',
    '차종분류코드', 
    '차종코드', 
    '차명', 
    '전고', 
    '전폭',
    '전장', 
    '차량구동형식코드', 
    '제작사명', 
    '제원관리번호',
    '적재중량', 
    '차량형식', 
    '공차중량',
    '제작국명', 
    '연료코드', 
    '엔진형식', 
    '엔진출력', 
    '승차정원', 
    '배기량', 
    '변속기종류코드', ]
    }

scol = pd.DataFrame(sdict)
scol

                  컬럼        내용
0           MDFCN_DT      수정일시
1           APRV_YMD      승인일자
2             DEL_YN      삭제여부
3        VHCL_REG_DT    차량등록일시
4          TOTL_WGHT       총중량
5       VHCTY_TY_CD2   차종유형코드2
6        VHCTY_CL_CD    차종분류코드
7           VHCTY_CD      차종코드
8              VHCNM        차명
9              OVRHG        전고
10             OVRWD        전폭
11             OVRLH        전장
12  VHCL_DRVE_FRM_CD  차량구동형식코드
13         MNFCTR_NM      제작사명
14       MANP_MNG_NO    제원관리번호
15        CRYNG_WGHT      적재중량
16          VHCL_FRM      차량형식
17         EMPV_WGHT      공차중량
18      FBCTN_NTN_NM      제작국명
19           FUEL_CD      연료코드
20           EGIN_TY      엔진형식
21         EGIN_OTPT      엔진출력
22        TKCAR_PSCP      승차정원
23            DSPLVL       배기량
24    GEARBOX_KND_CD   변속기종류코드

### 데이터 info

In [14]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,UPDT_DT,수정 일시,14578,MDFCN_DT,수정일시,14578.0,0.0,530796,530796.0
1,CNFRM_DE,승인 일자,532881,APRV_YMD,승인일자,532881.0,0.0,12493,12493.0
2,DELE_YN,삭제 YN,545374,DEL_YN,삭제여부,545374.0,0.0,0,0.0
3,CRTN_DT,생성 일시,545374,VHCL_REG_DT,차량등록일시,545374.0,0.0,0,0.0
4,TOT_WGHT,총 중량,541702,TOTL_WGHT,총중량,541702.0,0.0,3672,3672.0

### [출력] 컬럼명, 결측치 통계

In [ ]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### [분석]

#### 제원관리번호 unique

In [36]:
len(odf2['SRCMNNO'].unique()), len(sdf2['MANP_MNG_NO'].unique())

(545374, 545374)

In [37]:
temp = set(odf2['SRCMNNO'].unique()) - set(sdf2['MANP_MNG_NO'].unique())
len(temp)

0

#### 차종코드

In [38]:
odf2['VHCTY'].unique()

array(['T', 'V', 'P', 'S', nan], dtype=object)

In [39]:
sdf2['VHCTY_CD'].unique()

array(['A31P', 'A31V', 'A31T', 'A31S', nan], dtype=object)

#### 차종분류코드

In [40]:
odf2['VHCTY_CL'].unique()

array(['특수용도형-특수용도형', '특수', '특수용도형-피견인', '일반', '다목적', '밴', '일반형-픽업',
       '일반형-카고', '기타', '견인', '특수작업형', '특수용도형-탱크로리', '덤프', '구난', '승용겸화물',
       '특수용도형', nan], dtype=object)

In [41]:
sdf2['VHCTY_CL_CD'].unique()

array(['A2826', 'A2819', 'A2818', 'A2809', 'A2814', 'A2821', 'A2816',
       'A2824', 'A2810', 'A2815', 'A2813', 'A2820', 'A2823', 'A2822',
       'A2825', 'A2812', nan], dtype=object)

In [42]:
sdf2['VHCTY_TY_CD2'].unique()

array(['A30L', 'A30M', 'A30S', nan, 'A30C'], dtype=object)

## 3\. 배출가스 인증정보(CEG_EMIS_CERTI_MIG)

In [23]:
name = 'CEG_EMIS_CERTI_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

23 21
(79725, 23) (79670, 21)

In [24]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수    행_수
ODS    23  79725
STD    21  79670

### 컬럼 확인

In [25]:
odf.columns.to_list()

['EMIS_CRTCNO',
 'EMIS_CRTC_SNO',
 'EMIS_CRTC_1_SE',
 'EMIS_CRTC_2_SE',
 'DMSTC_INCM_MKR_SE',
 'EMIS_VHCTY',
 'FUEL',
 'SAME_VHCTY_TY',
 'EMIS_CRTC_DE',
 'MKR_NM',
 'MNFCT_NM',
 'PLOR_NM',
 'EMIS_CRTC_STUS',
 'EMIS_CRTC_UNAVBL_DE',
 'EMIS_CRTC_UNAVBL_RESN',
 'ORGCAR_SRCMNNO',
 'REPCAR_EMIS_CRTCNO',
 'REPCAR_VIN',
 'EMIS_PERM_STDR_CD',
 'EMIS_GRD',
 'RECP_FILE_NM',
 'STRE_DE',
 'SRCMNNO']

In [26]:
olist = [
    'STRE_DE', 
    'MKR_NM', 
    'FUEL', 
    'EMIS_CRTC_DE', 
    'EMIS_CRTCNO', 
    'EMIS_PERM_STDR_CD', 
    'EMIS_VHCTY', 
    'EMIS_CRTC_UNAVBL_RESN', 
    'EMIS_CRTC_2_SE',
    'EMIS_CRTC_STUS',
    'EMIS_CRTC_SNO', 
    'EMIS_CRTC_UNAVBL_DE', 
    'EMIS_CRTC_1_SE', 
    'EMIS_GRD',
    'SAME_VHCTY_TY',
    'REPCAR_VIN', 
    'REPCAR_EMIS_CRTCNO', 
    'ORGCAR_SRCMNNO',
    'DMSTC_INCM_MKR_SE', 
    'MNFCT_NM', 
    'PLOR_NM', 

    'RECP_FILE_NM', 
    'SRCMNNO',
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['저장 일자', 
    '제작사 명', 
    '연료', 
    '배출가스 인증 일자', 
    '배출가스인증번호', 
    '배출가스 허용 기준 코드', 
    '배출가스 차종', 
    '배출가스 인증 무효 사유', 
    '배출가스 인증 2 구분',
    '배출가스 인증 상태',
    '배출가스 인증 일련번호', 
    '배출가스 인증 무효 일자', 
    '배출가스 인증 1 구분', 
    '배출가스 등급',
    '동일 차종 유형',
    '대표차 차대번호', 
    '대표차 배출가스 인증번호', 
    '기본차 제원관리번호',
    '국내 수입 제작사 구분', 
    '제조사 명', 
    '원산지 명', 

    '미정', 
    '미정',]
    }

ocol = pd.DataFrame(odict)
ocol

                       컬럼             내용
0                 STRE_DE          저장 일자
1                  MKR_NM          제작사 명
2                    FUEL             연료
3            EMIS_CRTC_DE     배출가스 인증 일자
4             EMIS_CRTCNO       배출가스인증번호
5       EMIS_PERM_STDR_CD  배출가스 허용 기준 코드
6              EMIS_VHCTY        배출가스 차종
7   EMIS_CRTC_UNAVBL_RESN  배출가스 인증 무효 사유
8          EMIS_CRTC_2_SE   배출가스 인증 2 구분
9          EMIS_CRTC_STUS     배출가스 인증 상태
10          EMIS_CRTC_SNO   배출가스 인증 일련번호
11    EMIS_CRTC_UNAVBL_DE  배출가스 인증 무효 일자
12         EMIS_CRTC_1_SE   배출가스 인증 1 구분
13               EMIS_GRD        배출가스 등급
14          SAME_VHCTY_TY       동일 차종 유형
15             REPCAR_VIN       대표차 차대번호
16     REPCAR_EMIS_CRTCNO  대표차 배출가스 인증번호
17         ORGCAR_SRCMNNO     기본차 제원관리번호
18      DMSTC_INCM_MKR_SE   국내 수입 제작사 구분
19               MNFCT_NM          제조사 명
20                PLOR_NM          원산지 명
21           RECP_FILE_NM             미정
22                SRCMNNO             미정

In [27]:
sdf.columns.to_list()

['DMSTC_IMP_MNFCTR_SE',
 'EXHST_GAS_CERT_NO',
 'EXHST_GAS_CERT_SE1',
 'EXHST_GAS_CERT_SE2',
 'EXHST_GAS_CERT_YMD',
 'EXHST_GAS_CERT_SN',
 'EXTGAS_CET_STS_CD',
 'EXTGAS_CET_UNVBL_YMD',
 'EXTGAS_CET_UNVBL_REN',
 'EXHST_GAS_GRD',
 'EXTGAS_CET_PRM_CRTCD',
 'VHCTY_CD',
 'FUEL_CD',
 'MNFCTR_NM',
 'MKR_NAME',
 'MANP_MNG_NO',
 'FBCTN_NTN_NM',
 'RPRSVH_EXTGAS_CET_NO',
 'RPRS_CAR_VIN',
 'VHCTY_TY_CD',
 'DATA_STRG_YMD']

In [28]:
slist = [
    'DATA_STRG_YMD', 
    'MNFCTR_NM', 
    'FUEL_CD',
    'EXHST_GAS_CERT_YMD', 
    'EXHST_GAS_CERT_NO', 
    'EXTGAS_CET_PRM_CRTCD', 
    'VHCTY_CD', 
    'EXTGAS_CET_UNVBL_REN',
    'EXHST_GAS_CERT_SE2', 
    'EXTGAS_CET_STS_CD', 
    'EXHST_GAS_CERT_SN',
    'EXTGAS_CET_UNVBL_YMD', 
    'EXHST_GAS_CERT_SE1',
    'EXHST_GAS_GRD', 
    'VHCTY_TY_CD', 
    'RPRS_CAR_VIN', 
    'RPRSVH_EXTGAS_CET_NO', 
    'MANP_MNG_NO', 
    'DMSTC_IMP_MNFCTR_SE', 
    'MKR_NAME', 
    'FBCTN_NTN_NM',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['자료저장일자', 
    '제작사명', 
    '연료코드',
    '배출가스인증일자', 
    '배출가스인증번호', 
    '배출가스인증허용기준코드', 
    '차종코드', 
    '배출가스인증무효사유',
    '배출가스인증구분2', 
    '배출가스인증상태코드', 
    '배출가스인증일련번호',
    '배출가스인증무효일자', 
    '배출가스인증구분1',
    '배출가스등급', 
    '차종유형코드', 
    '대표차차대번호', 
    '대표차배출가스인증번호', 
    '제원관리번호', 
    '국내수입제작사구분', 
    '제조사명', 
    '제작국명',]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼            내용
0          DATA_STRG_YMD        자료저장일자
1              MNFCTR_NM          제작사명
2                FUEL_CD          연료코드
3     EXHST_GAS_CERT_YMD      배출가스인증일자
4      EXHST_GAS_CERT_NO      배출가스인증번호
5   EXTGAS_CET_PRM_CRTCD  배출가스인증허용기준코드
6               VHCTY_CD          차종코드
7   EXTGAS_CET_UNVBL_REN    배출가스인증무효사유
8     EXHST_GAS_CERT_SE2     배출가스인증구분2
9      EXTGAS_CET_STS_CD    배출가스인증상태코드
10     EXHST_GAS_CERT_SN    배출가스인증일련번호
11  EXTGAS_CET_UNVBL_YMD    배출가스인증무효일자
12    EXHST_GAS_CERT_SE1     배출가스인증구분1
13         EXHST_GAS_GRD        배출가스등급
14           VHCTY_TY_CD        차종유형코드
15          RPRS_CAR_VIN       대표차차대번호
16  RPRSVH_EXTGAS_CET_NO   대표차배출가스인증번호
17           MANP_MNG_NO        제원관리번호
18   DMSTC_IMP_MNFCTR_SE     국내수입제작사구분
19              MKR_NAME          제조사명
20          FBCTN_NTN_NM          제작국명

### 데이터 info

In [29]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,STRE_DE,저장 일자,79715,DATA_STRG_YMD,자료저장일자,79660.0,55.0,10,10.0
1,MKR_NM,제작사 명,78956,MNFCTR_NM,제작사명,78901.0,55.0,769,769.0
2,FUEL,연료,79493,FUEL_CD,연료코드,79435.0,58.0,232,235.0
3,EMIS_CRTC_DE,배출가스 인증 일자,79670,EXHST_GAS_CERT_YMD,배출가스인증일자,79615.0,55.0,55,55.0
4,EMIS_CRTCNO,배출가스인증번호,79725,EXHST_GAS_CERT_NO,배출가스인증번호,79670.0,55.0,0,0.0

### [출력] 컬럼명, 결측치 통계

In [30]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

[정제]CEG_EMIS_CERTI_MIG.xlsx 출력완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_19096\1252313295.py:6: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  texcel.save()

### [분석]

#### 제원관리번호

In [53]:
len(odf2['ORGCAR_SRCMNNO'].unique()), len(sdf2['MANP_MNG_NO'].unique())

(48224, 48224)

In [54]:
len(set(odf2['ORGCAR_SRCMNNO'].unique()) - set(sdf2['MANP_MNG_NO'].unique()))

0

#### 차종코드

In [57]:
odf2['EMIS_VHCTY'].unique()

array(['PS', 'PL', 'PX', 'FM', 'L0', 'PM', 'FL', 'FS', 'P1', 'P3', 'FX',
       'P2', nan, 'F3', 'F2', 'P0'], dtype=object)

In [58]:
sdf2['VHCTY_CD'].unique()

array(['FX', 'FL', 'L0', 'PS', 'P1', 'FM', 'PX', 'PM', 'PL', 'P2', nan,
       'FS', 'P3', 'F3', 'F2', 'P0'], dtype=object)

#### 차종유형코드

In [55]:
odf2['SAME_VHCTY_TY'].unique()

array([nan, '6AD5.0PD1BCD7L14', '6AD2.0PG54F14', ..., 'NHT2.5PGHA12',
       'MPK2.0PGH5F12', 'MSY1597TG5Z14'], dtype=object)

In [56]:
sdf2['VHCTY_TY_CD'].unique()

array(['DA7698TED1FBC14', 'FDA5132TED1FBC14', 'FDA2987TED14', ...,
       'MGD6.2PG5F14', 'MPK2.0PGH5F12', 'MSY1597TG5Z14'], dtype=object)

## 4\. 배출가스 인증시험(CEG_EMIS_CERTI_TEST_MIG)

In [31]:
name = 'CEG_EMIS_CERTI_TEST_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

23 21
(86406, 23) (86406, 21)

In [32]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수    행_수
ODS    23  86406
STD    21  86406

### 컬럼 확인

In [33]:
odf.columns.to_list()

['EMIS_CRTCNO',
 'EMIS_CRTC_SNO',
 'EMIS_TEST_MOD_VAL',
 'CO_PERM_STDR_VAL',
 'CO_TEST_RSLT',
 'NMOG_PERM_STDR_VAL',
 'NMOG_TEST_RSLT',
 'NMHC_PERM_STDR_VAL',
 'NMHC_TEST_RSLT',
 'HC_PERM_STDR_VAL',
 'HC_TEST_RSLT',
 'NOX_PERM_STDR_VAL',
 'NOX_TEST_RSLT',
 'NMOG_NOX_PERM_STDR_VAL',
 'NMOG_NOX_TEST_RSLT',
 'HC_NOX_PERM_STDR_VAL',
 'HC_NOX_TEST_RSLT',
 'PM_PERM_STDR_VAL',
 'PM_TEST_RSLT',
 'PN_PERM_STDR_VAL',
 'PN_TEST_RSLT',
 'RECP_FILE_NM',
 'STRE_DE']

In [34]:
olist = [
    'PN_PERM_STDR_VAL', 
    'NOX_PERM_STDR_VAL', 
    'PM_PERM_STDR_VAL', 
    'NOX_TEST_RSLT',
    'PN_TEST_RSLT', 
    'CO_PERM_STDR_VAL',
    'CO_TEST_RSLT', 
    'EMIS_CRTCNO', 
    'EMIS_CRTC_SNO', 
    'EMIS_TEST_MOD_VAL', 
    'HC_PERM_STDR_VAL',
    'HC_NOX_PERM_STDR_VAL',
    'HC_NOX_TEST_RSLT', 
    'HC_TEST_RSLT', 
    'NMHC_PERM_STDR_VAL', 
    'NMHC_TEST_RSLT', 
    'NMOG_PERM_STDR_VAL', 
    'NMOG_NOX_PERM_STDR_VAL', 
    'NMOG_NOX_TEST_RSLT', 
    'NMOG_TEST_RSLT',
    'PM_TEST_RSLT',

    'RECP_FILE_NM', 
    'STRE_DE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['입자개수 허용 기준 값', 
    '질소산화물 허용 기준 값', 
    '입자상물질 허용 기준 값', 
    '질소산화물 시험 결과',
    '입자개수 시험 결과', 
    '일산화탄소 허용 기준 값',
    '일산화탄소 시험 결과', 
    '배출가스 인증번호', 
    '배출가스 인증 일련번호', 
    '배출가스 시험 모드 값', 
    '탄화수소3 허용 기준 값',
    '탄화수소3 질소산화물 허용 기준 값',
    '탄화수소3 질소산화물 시험 결과', 
    '탄화수소3 시험 결과', 
    '탄화수소2 허용 기준 값', 
    '탄화수소2 시험 결과', 
    '탄화수소1 허용 기준 값', 
    '탄화수소1 질소산화물 허용 기준 값', 
    '탄화수소1 질소산화물 시험 결과', 
    '탄화수소1 시험 결과',
    '입자상물질 시험 결과',

    '미정', 
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼                   내용
0         PN_PERM_STDR_VAL         입자개수 허용 기준 값
1        NOX_PERM_STDR_VAL        질소산화물 허용 기준 값
2         PM_PERM_STDR_VAL        입자상물질 허용 기준 값
3            NOX_TEST_RSLT          질소산화물 시험 결과
4             PN_TEST_RSLT           입자개수 시험 결과
5         CO_PERM_STDR_VAL        일산화탄소 허용 기준 값
6             CO_TEST_RSLT          일산화탄소 시험 결과
7              EMIS_CRTCNO            배출가스 인증번호
8            EMIS_CRTC_SNO         배출가스 인증 일련번호
9        EMIS_TEST_MOD_VAL         배출가스 시험 모드 값
10        HC_PERM_STDR_VAL        탄화수소3 허용 기준 값
11    HC_NOX_PERM_STDR_VAL  탄화수소3 질소산화물 허용 기준 값
12        HC_NOX_TEST_RSLT    탄화수소3 질소산화물 시험 결과
13            HC_TEST_RSLT          탄화수소3 시험 결과
14      NMHC_PERM_STDR_VAL        탄화수소2 허용 기준 값
15          NMHC_TEST_RSLT          탄화수소2 시험 결과
16      NMOG_PERM_STDR_VAL        탄화수소1 허용 기준 값
17  NMOG_NOX_PERM_STDR_VAL  탄화수소1 질소산화물 허용 기준 값
18      NMOG_NOX_TEST_RSLT    탄화수소1 질소산화물 시험 결과
19          NMOG_TEST_RSLT          탄화수소1 시험 결과
20            PM_TEST_RSLT          입자상물질 시험 결과
21            RECP_FILE_NM                   미정
22                 STRE_DE                   미정

In [35]:
sdf.columns.to_list()

['COX_PRMT_VAL',
 'COX_TEST_RSLT',
 'EXHST_GAS_CERT_NO',
 'EXHST_GAS_CERT_SN',
 'FBVH_EXTGAS_TES_TYCD',
 'HC3_NOX_PRMT_VAL',
 'HC3_NOX_TES_RSLTVL',
 'HC3_PRMT_VAL',
 'HC3_TEST_RSLT_VAL',
 'HC2_PRMT_VAL',
 'HC2_TEST_RSLT_VAL',
 'HC1_NOX_PRMT_VAL',
 'HC1_NOX_TES_RSLTVL',
 'HC1_PRMT_VAL',
 'HC_TEST_RSLT_VAL',
 'NOX_PRMT_VAL',
 'NOX_TEST_RSLT_VAL',
 'PM_CRTR_VAL',
 'PM_CRTR',
 'PARTCL_CNT_CRTR_VAL',
 'PN_CRTR']

In [36]:
slist = [
    'PARTCL_CNT_CRTR_VAL', 
    'NOX_PRMT_VAL', 
    'PM_CRTR_VAL', 
    'NOX_TEST_RSLT_VAL', 
    'PN_CRTR',
    'COX_PRMT_VAL', 
    'COX_TEST_RSLT', 
    'EXHST_GAS_CERT_NO',
    'EXHST_GAS_CERT_SN', 
    'FBVH_EXTGAS_TES_TYCD', 
    'HC3_PRMT_VAL', 
    'HC3_NOX_PRMT_VAL',
    'HC3_NOX_TES_RSLTVL', 
    'HC3_TEST_RSLT_VAL',
    'HC2_PRMT_VAL', 
    'HC2_TEST_RSLT_VAL', 
    'HC1_PRMT_VAL', 
    'HC1_NOX_PRMT_VAL',
    'HC1_NOX_TES_RSLTVL', 
    'HC_TEST_RSLT_VAL',
    'PM_CRTR', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['입자개수기준값', 
    '질소산화물허용값', 
    'PM기준값', 
    '질소산화물시험결과값', 
    'PM기준',
    '일산화탄소허용기준값', 
    '일산화탄소시험결과', 
    '배출가스인증번호',
    '배출가스인증일련번호', 
    '제작차배출가스시험유형코드', 
    '탄화수소3허용값', 
    '탄화수소3질소산화물허용값',
    '탄화수소3질소산화물시험결과값', 
    '탄화수소3시험결과값',
    '탄화수소2허용값', 
    '탄화수소2시험결과값', 
    '탄화수소1허용값', 
    '탄화수소1질소산화물허용값',
    '탄화수소1질소산화물시험결과값', 
    '탄화수소시험결과값',
    'PM기준', ]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼               내용
0    PARTCL_CNT_CRTR_VAL          입자개수기준값
1           NOX_PRMT_VAL         질소산화물허용값
2            PM_CRTR_VAL            PM기준값
3      NOX_TEST_RSLT_VAL       질소산화물시험결과값
4                PN_CRTR             PM기준
5           COX_PRMT_VAL       일산화탄소허용기준값
6          COX_TEST_RSLT        일산화탄소시험결과
7      EXHST_GAS_CERT_NO         배출가스인증번호
8      EXHST_GAS_CERT_SN       배출가스인증일련번호
9   FBVH_EXTGAS_TES_TYCD    제작차배출가스시험유형코드
10          HC3_PRMT_VAL         탄화수소3허용값
11      HC3_NOX_PRMT_VAL    탄화수소3질소산화물허용값
12    HC3_NOX_TES_RSLTVL  탄화수소3질소산화물시험결과값
13     HC3_TEST_RSLT_VAL       탄화수소3시험결과값
14          HC2_PRMT_VAL         탄화수소2허용값
15     HC2_TEST_RSLT_VAL       탄화수소2시험결과값
16          HC1_PRMT_VAL         탄화수소1허용값
17      HC1_NOX_PRMT_VAL    탄화수소1질소산화물허용값
18    HC1_NOX_TES_RSLTVL  탄화수소1질소산화물시험결과값
19      HC_TEST_RSLT_VAL        탄화수소시험결과값
20               PM_CRTR             PM기준

### 데이터 info

In [37]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,PN_PERM_STDR_VAL,입자개수 허용 기준 값,1978,PARTCL_CNT_CRTR_VAL,입자개수기준값,1978.0,0.0,84428,84428.0
1,NOX_PERM_STDR_VAL,질소산화물 허용 기준 값,13893,NOX_PRMT_VAL,질소산화물허용값,13893.0,0.0,72513,72513.0
2,PM_PERM_STDR_VAL,입자상물질 허용 기준 값,2770,PM_CRTR_VAL,PM기준값,2770.0,0.0,83636,83636.0
3,NOX_TEST_RSLT,질소산화물 시험 결과,16856,NOX_TEST_RSLT_VAL,질소산화물시험결과값,16856.0,0.0,69550,69550.0
4,PN_TEST_RSLT,입자개수 시험 결과,0,PN_CRTR,PM기준,0.0,0.0,86406,86406.0

### [출력] 컬럼명, 결측치 통계

In [38]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

[정제]CEG_EMIS_CERTI_TEST_MIG.xlsx 출력완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_19096\1252313295.py:6: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  texcel.save()

## 5\. [e]배출가스인증 자동차정보(CEG_EMIS_CERTI_VEH_MIG)
- [❌] STD_CEG_EMIS_CERTI_VEH_MIG.csv 없음.

In [3]:
name = 'CEG_EMIS_CERTI_VEH_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'D:/과업/[한국환경공단]자동차_환경_빅데이터_구축_2차/data/STD\\STD_CEG_EMIS_CERTI_VEH_MIG.csv'

In [ ]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

### 컬럼 확인

In [ ]:
odf.columns.to_list()

In [ ]:
olist = [
    'CO_PERM_STDR_VAL',
    'CO_TEST_RSLT', 
    'EMIS_CRTCNO', 
    'EMIS_CRTC_SNO', 
    'EMIS_TEST_MOD_VAL', 
    'HC_NOX_PERM_STDR_VAL',
    'HC_NOX_TEST_RSLT', 
    'HC_PERM_STDR_VAL',
    'HC_TEST_RSLT', 
    'NMHC_PERM_STDR_VAL', 
    'NMHC_TEST_RSLT', 
    'NMOG_NOX_PERM_STDR_VAL', 
    'NMOG_NOX_TEST_RSLT', 
    'NMOG_PERM_STDR_VAL', 
    'NMOG_TEST_RSLT',
    'NOX_PERM_STDR_VAL', 
    'NOX_TEST_RSLT',
    'PM_PERM_STDR_VAL', 
    'PM_TEST_RSLT',
    'PN_PERM_STDR_VAL', 
    'PN_TEST_RSLT', 

    'RECP_FILE_NM', 
    'STRE_DE'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['일산화탄소 허용 기준 값', 
    '일산화탄소 시험 결과', 
    '배출가스 인증번호', 
    '배출가스 인증 일련번호', 
    '배출가스 시험 모드 값', 
    '탄화수소3 질소산화물 허용 기준 값', 
    '탄화수소3 질소산화물 시험 결과', 
    '탄화수소3 허용 기준 값', 
    '탄화수소3 시험 결과', 
    '탄화수소2 허용 기준 값', 
    '탄화수소2 시험 결과', 
    '탄화수소1 질소산화물 허용 기준 값', 
    '탄화수소1 질소산화물 시험 결과', 
    '탄화수소1 허용 기준 값', 
    '탄화수소1 시험 결과', 
    '질소산화물 허용 기준 값', 
    '질소산화물 시험 결과', 
    '입자상물질 허용 기준 값', 
    '입자상물질 시험 결과', 
    '입자개수 허용 기준 값', 
    '입자개수 시험 결과',
     
    '미정', 
    '미정']
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼                   내용
0         CO_PERM_STDR_VAL        일산화탄소 허용 기준 값
1             CO_TEST_RSLT          일산화탄소 시험 결과
2              EMIS_CRTCNO            배출가스 인증번호
3            EMIS_CRTC_SNO         배출가스 인증 일련번호
4        EMIS_TEST_MOD_VAL         배출가스 시험 모드 값
5     HC_NOX_PERM_STDR_VAL  탄화수소3 질소산화물 허용 기준 값
6         HC_NOX_TEST_RSLT    탄화수소3 질소산화물 시험 결과
7         HC_PERM_STDR_VAL        탄화수소3 허용 기준 값
8             HC_TEST_RSLT          탄화수소3 시험 결과
9       NMHC_PERM_STDR_VAL        탄화수소2 허용 기준 값
10          NMHC_TEST_RSLT          탄화수소2 시험 결과
11  NMOG_NOX_PERM_STDR_VAL  탄화수소1 질소산화물 허용 기준 값
12      NMOG_NOX_TEST_RSLT    탄화수소1 질소산화물 시험 결과
13      NMOG_PERM_STDR_VAL        탄화수소1 허용 기준 값
14          NMOG_TEST_RSLT          탄화수소1 시험 결과
15       NOX_PERM_STDR_VAL        질소산화물 허용 기준 값
16           NOX_TEST_RSLT          질소산화물 시험 결과
17        PM_PERM_STDR_VAL        입자상물질 허용 기준 값
18            PM_TEST_RSLT          입자상물질 시험 결과
19        PN_PERM_STDR_VAL         입자개수 허용 기준 값
20            PN_TEST_RSLT           입자개수 시험 결과
21            RECP_FILE_NM                   미정
22                 STRE_DE                   미정

In [ ]:
sdf.columns.to_list()

In [ ]:
slist = [
    'COX_PRMT_VAL', 
    'COX_TEST_RSLT', 
    'EXHST_GAS_CERT_NO',
    'EXHST_GAS_CERT_SN', 
    'FBVH_EXTGAS_TES_TYCD', 
    'HC3_NOX_PRMT_VAL',
    'HC3_NOX_TES_RSLTVL', 
    'HC3_PRMT_VAL', 
    'HC3_TEST_RSLT_VAL',
    'HC2_PRMT_VAL', 
    'HC2_TEST_RSLT_VAL', 
    'HC1_NOX_PRMT_VAL',
    'HC1_NOX_TES_RSLTVL', 
    'HC1_PRMT_VAL', 
    'HC_TEST_RSLT_VAL',
    'NOX_PRMT_VAL', 
    'NOX_TEST_RSLT_VAL', 
    'PM_CRTR_VAL', 
    'PM_CRTR',
    'PARTCL_CNT_CRTR_VAL', 
    'PN_CRTR'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['일산화탅소허용기준값', 
    '일산화탅소시험결과', 
    '배출가스인증번호', 
    '배출가스인증일련번호', 
    '제작차배출가스시험유형코드', 
    '탄화수소3질소산화물허용값', 
    '탄화수소3질소산화물시험결과값', 
    '탄화수소3허용값', 
    '탄화수소3시험결과값', 
    '탄화수소2허용값', 
    '탄화수소2시험결과값', 
    '탄화수소1질소산화물허용값', 
    '탄화수소1질소산화물시험결과값', 
    '탄화수소1허용값', 
    '탄화수소시험결과값', 
    '질소산화물허용값', 
    '질소산화물시험결과값', 
    'PM기준값', 
    'PM기준', 
    '입자개수기준값', 
    'PM기준']
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼               내용
0           COX_PRMT_VAL       일산화탅소허용기준값
1          COX_TEST_RSLT        일산화탅소시험결과
2      EXHST_GAS_CERT_NO         배출가스인증번호
3      EXHST_GAS_CERT_SN       배출가스인증일련번호
4   FBVH_EXTGAS_TES_TYCD    제작차배출가스시험유형코드
5       HC3_NOX_PRMT_VAL    탄화수소3질소산화물허용값
6     HC3_NOX_TES_RSLTVL  탄화수소3질소산화물시험결과값
7           HC3_PRMT_VAL         탄화수소3허용값
8      HC3_TEST_RSLT_VAL       탄화수소3시험결과값
9           HC2_PRMT_VAL         탄화수소2허용값
10     HC2_TEST_RSLT_VAL       탄화수소2시험결과값
11      HC1_NOX_PRMT_VAL    탄화수소1질소산화물허용값
12    HC1_NOX_TES_RSLTVL  탄화수소1질소산화물시험결과값
13          HC1_PRMT_VAL         탄화수소1허용값
14      HC_TEST_RSLT_VAL        탄화수소시험결과값
15          NOX_PRMT_VAL         질소산화물허용값
16     NOX_TEST_RSLT_VAL       질소산화물시험결과값
17           PM_CRTR_VAL            PM기준값
18               PM_CRTR             PM기준
19   PARTCL_CNT_CRTR_VAL          입자개수기준값
20               PN_CRTR             PM기준

### 데이터 info

In [ ]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

### [출력] 컬럼명, 결측치 통계

In [ ]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### ODS만 진행

In [17]:
name = 'CEG_EMIS_CERTI_VEH_MIG'
ods_file_name = f'ODS_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
print(len(odf.columns))
print(odf.shape)

25
(109269, 25)

In [18]:
t_info = {'컬럼_수':[odf.shape[1]], '행_수':[odf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS'])
t_df

     컬럼_수     행_수
ODS    25  109269

#### 컬럼 확인

In [19]:
odf.columns.to_list()

['EMIS_CRTCNO',
 'EMIS_CRTC_SNO',
 'VHCL_SNO',
 'VHCNM',
 'CAR_FRM',
 'VIN',
 'EMIS_VHCTY',
 'VHCL_YRIDNW',
 'DRV_FRM',
 'PURPS',
 'GEARBOX_KND',
 'EMPV_WGHT',
 'TOT_WGHT',
 'EGINTY',
 'DSPLVL',
 'FUEL',
 'EGINPWR',
 'VHCL_LT_INFO',
 'VHCL_WH_INFO',
 'VHCL_HG_INFO',
 'TKCAR_NMPR_INFO',
 'TIRE_MG_PRE_DTL',
 'TIRE_MG_RR_DTL',
 'RECP_FILE_NM',
 'STRE_DE']

In [20]:
olist = [
    'EMIS_VHCTY',
    'EMPV_WGHT',
    'PURPS',
    'EMIS_CRTCNO',
    'EMIS_CRTC_SNO',
    'DSPLVL',
    'DRV_FRM',
    'FUEL',
    'EGINTY',
    'EGINPWR',
    'VIN',
    'TKCAR_NMPR_INFO',
    'GEARBOX_KND',
    'STRE_DE', 
    'VHCL_LT_INFO',
    'VHCL_WH_INFO',
    'VHCL_HG_INFO',
    'VHCL_YRIDNW',
    'VHCL_SNO',
    'VHCNM',
    'TOT_WGHT',
    'CAR_FRM',

    'TIRE_MG_PRE_DTL',
    'TIRE_MG_RR_DTL',
    'RECP_FILE_NM',
    ]

odict = {
    '컬럼':olist,
    '내용':
    [
    '배출가스 차종',
    '공차중량',
    '용도',
    '배출가스 인증번호',
    '배출가스 인증 일련번호',
    '배기량',
    '구동 형식',
    '연료',
    '엔진형식',
    '엔진출력',
    '차대번호',
    '승차 인원 정보',
    '변속기 종류',
    '저장 일자', 
    '차량 길이 정보',
    '차량 너비 정보',
    '차량 높이 정보',
    '차량 연식',
    '차량 일련번호',
    '차명',
    '총 중량',
    '자동차 형식',

    '미정',
    '미정',
    '미정',
    ]
    }

ocol = pd.DataFrame(odict)
ocol

                 컬럼            내용
0        EMIS_VHCTY       배출가스 차종
1         EMPV_WGHT          공차중량
2             PURPS            용도
3       EMIS_CRTCNO     배출가스 인증번호
4     EMIS_CRTC_SNO  배출가스 인증 일련번호
5            DSPLVL           배기량
6           DRV_FRM         구동 형식
7              FUEL            연료
8            EGINTY          엔진형식
9           EGINPWR          엔진출력
10              VIN          차대번호
11  TKCAR_NMPR_INFO      승차 인원 정보
12      GEARBOX_KND        변속기 종류
13          STRE_DE         저장 일자
14     VHCL_LT_INFO      차량 길이 정보
15     VHCL_WH_INFO      차량 너비 정보
16     VHCL_HG_INFO      차량 높이 정보
17      VHCL_YRIDNW         차량 연식
18         VHCL_SNO       차량 일련번호
19            VHCNM            차명
20         TOT_WGHT          총 중량
21          CAR_FRM        자동차 형식
22  TIRE_MG_PRE_DTL            미정
23   TIRE_MG_RR_DTL            미정
24     RECP_FILE_NM            미정

#### 데이터 info

In [21]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

ocount['ODS_mcount'] = odf2.shape[0] - ocount['ocount']
ocount.head()

          oindex          ocol  ocount  ODS_mcount
0     EMIS_VHCTY       배출가스 차종   84041       25228
1      EMPV_WGHT          공차중량  109166         103
2          PURPS            용도   96950       12319
3    EMIS_CRTCNO     배출가스 인증번호  109269           0
4  EMIS_CRTC_SNO  배출가스 인증 일련번호  109269           0

#### [출력] [ODS]컬럼명, 결측치 통계

In [ ]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제][ODS]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제][ODS]{name}.xlsx 출력완료.')

## 6\. 제작차 배출 허용 기준(CEG_EMIS_STD_MIG)

In [39]:
name = 'CEG_EMIS_STD_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

21 21
(1212, 21) (1212, 21)

In [40]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    21  1212
STD    21  1212

### 컬럼 확인

In [41]:
odf.columns.to_list()

['EMIS_PERM_STDR_CD',
 'EMIS_PERM_STDR_SML_SE',
 'FUEL_GRP',
 'EMIS_VHCTY',
 'TEST_BGIN_WGHT',
 'TEST_END_WGHT',
 'APLI_DE',
 'EMIS_TEST_MOD_VAL',
 'CO_PERM_STDR_VAL',
 'NMOG_PERM_STDR_VAL',
 'NMHC_PERM_STDR_VAL',
 'HC_PERM_STDR_VAL',
 'NOX_PERM_STDR_VAL',
 'NMOG_NOX_PERM_STDR_VAL',
 'HC_NOX_PERM_STDR_VAL',
 'PM_PERM_STDR_VAL',
 'PN_PERM_STDR_VAL',
 'EMIS_PERM_STDR_SE',
 'EMIS_GRD_USE_YN',
 'EMIS_GRD',
 'EMIS_PERM_STDR_LEVL']

In [42]:
olist = [
    'APLI_DE',
    'TEST_END_WGHT',
    'TEST_BGIN_WGHT',
    'PN_PERM_STDR_VAL',
    'PM_PERM_STDR_VAL',
    'CO_PERM_STDR_VAL',
    'NMOG_PERM_STDR_VAL',
    'NOX_PERM_STDR_VAL',
    'EMIS_GRD',
    'EMIS_GRD_USE_YN',
    'EMIS_PERM_STDR_CD',
    'EMIS_PERM_STDR_LEVL',
    'EMIS_PERM_STDR_SE',
    'EMIS_VHCTY',
    'EMIS_TEST_MOD_VAL',
    'EMIS_PERM_STDR_SML_SE',
    'FUEL_GRP',
    'HC_NOX_PERM_STDR_VAL',
    'HC_PERM_STDR_VAL',
    'NMHC_PERM_STDR_VAL',
    'NMOG_NOX_PERM_STDR_VAL'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['적용 일자',
    '시험 끝 중량',
    '시험 시작 중량',
    '입자개수 허용 기준 값',
    '입자상물질 허용 기준 값',
    '일산화탄소 허용 기준 값',
    '탄화수소1 허용 기준 값',
    '질소산화물 허용 기준 값',
    '배출가스 등급',
    '배출가스 등급 사용 YN',
    '배출가스 허용 기준 코드',
    '배출가스 허용 기준 수준',
    '배출가스 허용 기준 구분',
    '배출가스 차종',
    '배출가스 시험 모드 값',
    '배출가스 허용 기준 소 구분',
    '연료 그룹',
    '탄화수소3 질소산화물 허용 기준 값',
    '탄화수소3 허용기준 값',
    '탄화수소2 허용 기준 값',
    '탄화수소1 질소산화물 허용 기준 값']
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼                   내용
0                  APLI_DE                적용 일자
1            TEST_END_WGHT              시험 끝 중량
2           TEST_BGIN_WGHT             시험 시작 중량
3         PN_PERM_STDR_VAL         입자개수 허용 기준 값
4         PM_PERM_STDR_VAL        입자상물질 허용 기준 값
5         CO_PERM_STDR_VAL        일산화탄소 허용 기준 값
6       NMOG_PERM_STDR_VAL        탄화수소1 허용 기준 값
7        NOX_PERM_STDR_VAL        질소산화물 허용 기준 값
8                 EMIS_GRD              배출가스 등급
9          EMIS_GRD_USE_YN        배출가스 등급 사용 YN
10       EMIS_PERM_STDR_CD        배출가스 허용 기준 코드
11     EMIS_PERM_STDR_LEVL        배출가스 허용 기준 수준
12       EMIS_PERM_STDR_SE        배출가스 허용 기준 구분
13              EMIS_VHCTY              배출가스 차종
14       EMIS_TEST_MOD_VAL         배출가스 시험 모드 값
15   EMIS_PERM_STDR_SML_SE      배출가스 허용 기준 소 구분
16                FUEL_GRP                연료 그룹
17    HC_NOX_PERM_STDR_VAL  탄화수소3 질소산화물 허용 기준 값
18        HC_PERM_STDR_VAL         탄화수소3 허용기준 값
19      NMHC_PERM_STDR_VAL        탄화수소2 허용 기준 값
20  NMOG_NOX_PERM_STDR_VAL  탄화수소1 질소산화물 허용 기준 값

In [43]:
sdf.columns.to_list()

['APLCN_YMD',
 'COX_PRMT_VAL',
 'EXHST_GAS_GRD_CD',
 'EXHST_GAS_GRD_USE_YN',
 'EXHST_GAS_CERT_PRMT_CRTR_CD',
 'EXHST_GAS_CERT_PRMT_CRTR_LEVL',
 'EXHST_GAS_CERT_PRMT_CRTR_SE',
 'EXHST_GAS_CERT_PRMT_CRTRSCL_SE',
 'EXHST_GAS_TEST_MOD',
 'EXHST_GAS_INSP_VHCTY',
 'FUEL_CL_CD',
 'HC3_NOX_PRMT_VAL',
 'HC3_PRMT_VAL',
 'HC2_PRMT_VAL',
 'HC1_NOX_PRMT_VAL',
 'HC1_PRMT_VAL',
 'NOX_PRMT_VAL',
 'PARTCLT_PRMT_VAL',
 'PARTCL_CNT_CRTR_VAL',
 'TEST_BGNG_WGHT',
 'TEST_END_WGHT']

In [44]:
slist = [
    'APLCN_YMD',
    'TEST_END_WGHT',
    'TEST_BGNG_WGHT',
    'PARTCL_CNT_CRTR_VAL',
    'PARTCLT_PRMT_VAL',
    'COX_PRMT_VAL',
    'HC1_PRMT_VAL',
    'NOX_PRMT_VAL',
    'EXHST_GAS_GRD_CD',
    'EXHST_GAS_GRD_USE_YN',
    'EXHST_GAS_CERT_PRMT_CRTR_CD',
    'EXHST_GAS_CERT_PRMT_CRTR_LEVL',
    'EXHST_GAS_CERT_PRMT_CRTR_SE',
    'EXHST_GAS_INSP_VHCTY',
    'EXHST_GAS_TEST_MOD',
    'EXHST_GAS_CERT_PRMT_CRTRSCL_SE',
    'FUEL_CL_CD',
    'HC3_NOX_PRMT_VAL',
    'HC3_PRMT_VAL',
    'HC2_PRMT_VAL',
    'HC1_NOX_PRMT_VAL'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['적용일자',
    '시험종료중량',
    '시험시작중량',
    '입자개수기준값',
    '입자상허용값',
    '일산화탄소허용기준값',
    '탄화수소1허용값',
    '질소산화물허용값',
    '배출가스등급코드',
    '배출가스등급사용여부',
    '배출가스인증허용기준코드',
    '배출가스인증허용기준수준',
    '배출가스인증허용기준구분',
    '배출가스검사차종',
    '배출가스시험모드',
    '배출가스인증허용기준소분류구분',
    '연료분류코드',
    '탄화수소3질소산화물허용값',
    '탄화수소3허용값',
    '탄화수소2허용값',
    '탄화수소1질소산화물허용값']
    }

scol = pd.DataFrame(sdict)
scol

                                컬럼               내용
0                        APLCN_YMD             적용일자
1                    TEST_END_WGHT           시험종료중량
2                   TEST_BGNG_WGHT           시험시작중량
3              PARTCL_CNT_CRTR_VAL          입자개수기준값
4                 PARTCLT_PRMT_VAL           입자상허용값
5                     COX_PRMT_VAL       일산화탄소허용기준값
6                     HC1_PRMT_VAL         탄화수소1허용값
7                     NOX_PRMT_VAL         질소산화물허용값
8                 EXHST_GAS_GRD_CD         배출가스등급코드
9             EXHST_GAS_GRD_USE_YN       배출가스등급사용여부
10     EXHST_GAS_CERT_PRMT_CRTR_CD     배출가스인증허용기준코드
11   EXHST_GAS_CERT_PRMT_CRTR_LEVL     배출가스인증허용기준수준
12     EXHST_GAS_CERT_PRMT_CRTR_SE     배출가스인증허용기준구분
13            EXHST_GAS_INSP_VHCTY         배출가스검사차종
14              EXHST_GAS_TEST_MOD         배출가스시험모드
15  EXHST_GAS_CERT_PRMT_CRTRSCL_SE  배출가스인증허용기준소분류구분
16                      FUEL_CL_CD           연료분류코드
17                HC3_NOX_PRMT_VAL    탄화수소3질소산화물허용값
18                    HC3_PRMT_VAL         탄화수소3허용값
19                    HC2_PRMT_VAL         탄화수소2허용값
20                HC1_NOX_PRMT_VAL    탄화수소1질소산화물허용값

### 데이터 info

In [45]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,APLI_DE,적용 일자,1212,APLCN_YMD,적용일자,1212,0,0,0
1,TEST_END_WGHT,시험 끝 중량,1212,TEST_END_WGHT,시험종료중량,1212,0,0,0
2,TEST_BGIN_WGHT,시험 시작 중량,1212,TEST_BGNG_WGHT,시험시작중량,1212,0,0,0
3,PN_PERM_STDR_VAL,입자개수 허용 기준 값,64,PARTCL_CNT_CRTR_VAL,입자개수기준값,64,0,1148,1148
4,PM_PERM_STDR_VAL,입자상물질 허용 기준 값,651,PARTCLT_PRMT_VAL,입자상허용값,651,0,561,561

### [출력] 컬럼명, 결측치 통계

In [46]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

[정제]CEG_EMIS_STD_MIG.xlsx 출력완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_19096\1252313295.py:6: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  texcel.save()

## 7\. 대표차명(CEG_STD_CAR_MIG)

In [191]:
name = 'CEG_STD_CAR_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

7 7
(1541, 7) (1541, 7)

In [192]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS     7  1541
STD     7  1541

### 컬럼 확인

In [193]:
odf.columns.to_list()

['REPCAR_NM', 'MKR_NM', 'PLOR_NM', 'RMK', 'CRTN_DT', 'UPDT_DT', 'USER_ID']

In [194]:
olist = [
    'USER_ID',
    'UPDT_DT', 
    'RMK', 
    'REPCAR_NM', 
    'PLOR_NM', 
    'MKR_NM', 
    'CRTN_DT', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['사용자 아이디',
    '수정 일시', 
    '비고', 
    '대표차 명', 
    '원산지 명', 
    '제작사 명', 
    '생성 일시',]
    }

ocol = pd.DataFrame(odict)
ocol

          컬럼       내용
0    USER_ID  사용자 아이디
1    UPDT_DT    수정 일시
2        RMK       비고
3  REPCAR_NM    대표차 명
4    PLOR_NM    원산지 명
5     MKR_NM    제작사 명
6    CRTN_DT    생성 일시

In [195]:
sdf.columns.to_list()

['MNFCTR_NM', 'PLOR_NM', 'RPRS_VHCNM', 'RMK', 'MDFCN_DT', 'USER_ID', 'CRT_DT']

In [196]:
slist = [
    'USER_ID', 
    'MDFCN_DT', 
    'RMK', 
    'RPRS_VHCNM', 
    'PLOR_NM', 
    'MNFCTR_NM', 
    'CRT_DT',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['사용자ID', 
    '수정일시', 
    '비고', 
    '대표차명', 
    '원산지명', 
    '제작사명', 
    '생성일시',]
    }

scol = pd.DataFrame(sdict)
scol

           컬럼     내용
0     USER_ID  사용자ID
1    MDFCN_DT   수정일시
2         RMK     비고
3  RPRS_VHCNM   대표차명
4     PLOR_NM   원산지명
5   MNFCTR_NM   제작사명
6      CRT_DT   생성일시

### 데이터 info

In [197]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,USER_ID,사용자 아이디,1541,USER_ID,사용자ID,1541,0,0,0
1,UPDT_DT,수정 일시,6,MDFCN_DT,수정일시,6,0,1535,1535
2,RMK,비고,90,RMK,비고,90,0,1451,1451
3,REPCAR_NM,대표차 명,1541,RPRS_VHCNM,대표차명,1541,0,0,0
4,PLOR_NM,원산지 명,1541,PLOR_NM,원산지명,1541,0,0,0

### [출력] 컬럼명, 결측치 통계

In [198]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

## 8\. 저감장치 클리닝 상세 정보(DLM_TB_ERP_CLEANING_DTL)

In [199]:
name = 'DLM_TB_ERP_CLEANING_DTL'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

59 13
(896011, 59) (897348, 13)

In [200]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS    59  896011
STD    13  897348

### 컬럼 확인

In [201]:
odf.columns.to_list()

['REDUC_REG_NO',
 'CLNING_MNGT_NO',
 'MKR_CD',
 'CLNING_DE',
 'CLNING_KND',
 'CLNING_CST',
 'CLNING_ENTRPS_NM',
 'DRVNG_DSTNC',
 'CLNING_PRGRE_STUS',
 'SBSIDY_TRGT_YN',
 'SBSIDY_TRGT_EXCLU_RESN',
 'LOCGOV_CNFRM_DE',
 'LOCGOV_CNFRMR_NM',
 'MKR_PAPE_ATT_YN',
 'SBSIDY_PYMT_DCSN_DE',
 'SBSIDY_PYMT_IDNTFR_NM',
 'CTNT',
 'CLNING_BTRC_TRGT_YN',
 'CLNING_BTRC_RESN',
 'INPT_DE',
 'RETR_NM',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'CLNING_LST_DE',
 'CLNING_WHL_SE',
 'CLNING_RMND_SBSIDY',
 'BF_SMO_DNSTY',
 'PST_SMO_DNSTY',
 'BF_VENTL_PSSR',
 'PST_VENTL_PSSR',
 'CLNING_RQEST_GRP_NO',
 'SBSIDY_RQT_DE',
 'SBSIDY_APLICT_NM',
 'CLNING_PYMT_DE',
 'CLNING_BIZ_YR',
 'CLNING_PYMT_YN',
 'CLNING_GRNTY_WHL_SE',
 'CLNING_REC_CNT_ELPSD',
 'INST_ID',
 'CLNING_SPEL_RESN_RESN',
 'CLNING_ETC_SPEL_RESN',
 'RCPT_LOCGOV_CD',
 'NOW_VHRNO',
 'STRCHG_DE',
 'RMK',
 'CLNING_WHL_ETC_SE',
 'CHK_YN',
 'CHK_YN1',
 'EXCA_YR',
 'EXCA_DE',
 'EXCA_YN',
 'EXCA_ETC',
 'ASOC_RQT_YN',
 'CHG_EQUIP_SER_NO',
 'M_CHK_PLAN_MONTH',
 'ATT_LGCLFL',
 'ATT_PHYSCL',
 'DELETE_YN',
 'DELETE_REASON']

In [202]:
olist = [
    'CLNING_GRNTY_WHL_SE',
    'CLNING_KND',
    'CLNING_ENTRPS_NM',
    'CLNING_DE',
    'SBSIDY_TRGT_YN',
    'BF_SMO_DNSTY',
    'BF_VENTL_PSSR',
    'REDUC_REG_NO',
    'PST_VENTL_PSSR',
    'CLNING_PRGRE_STUS',
    'DRVNG_DSTNC',
    'PST_SMO_DNSTY',

    'CLNING_MNGT_NO',
    'MKR_CD',
    'CLNING_CST',
    'SBSIDY_TRGT_EXCLU_RESN',
    'LOCGOV_CNFRM_DE',
    'LOCGOV_CNFRMR_NM',
    'MKR_PAPE_ATT_YN',
    'SBSIDY_PYMT_DCSN_DE',
    'SBSIDY_PYMT_IDNTFR_NM',
    'CTNT',
    'CLNING_BTRC_TRGT_YN',
    'CLNING_BTRC_RESN',
    'INPT_DE',
    'RETR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'CLNING_LST_DE',
    'CLNING_WHL_SE',
    'CLNING_RMND_SBSIDY',
    'CLNING_RQEST_GRP_NO',
    'SBSIDY_RQT_DE',
    'SBSIDY_APLICT_NM',
    'CLNING_PYMT_DE',
    'CLNING_BIZ_YR',
    'CLNING_PYMT_YN',
    'CLNING_REC_CNT_ELPSD',
    'INST_ID',
    'CLNING_SPEL_RESN_RESN',
    'CLNING_ETC_SPEL_RESN',
    'RCPT_LOCGOV_CD',
    'NOW_VHRNO',
    'STRCHG_DE',
    'RMK',
    'CLNING_WHL_ETC_SE',
    'CHK_YN',
    'CHK_YN1',
    'EXCA_YR',
    'EXCA_DE',
    'EXCA_YN',
    'EXCA_ETC',
    'ASOC_RQT_YN',
    'CHG_EQUIP_SER_NO',
    'M_CHK_PLAN_MONTH',
    'ATT_LGCLFL',
    'ATT_PHYSCL',
    'DELETE_YN',
    'DELETE_REASON', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['클리닝보증기간구분',
    '클리닝종류',
    '클리닝업체명',
    '클리닝일자',
    '보조금대상YN',
    '전매연농도',
    '전배기압력',
    '저감등록번호',
    '후배기압력',
    '클리닝진행상태',
    '주행거리',
    '후매연농도',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼         내용
0      CLNING_GRNTY_WHL_SE  클리닝보증기간구분
1               CLNING_KND      클리닝종류
2         CLNING_ENTRPS_NM     클리닝업체명
3                CLNING_DE      클리닝일자
4           SBSIDY_TRGT_YN    보조금대상YN
5             BF_SMO_DNSTY      전매연농도
6            BF_VENTL_PSSR      전배기압력
7             REDUC_REG_NO     저감등록번호
8           PST_VENTL_PSSR      후배기압력
9        CLNING_PRGRE_STUS    클리닝진행상태
10             DRVNG_DSTNC       주행거리
11           PST_SMO_DNSTY      후매연농도
12          CLNING_MNGT_NO         미정
13                  MKR_CD         미정
14              CLNING_CST         미정
15  SBSIDY_TRGT_EXCLU_RESN         미정
16         LOCGOV_CNFRM_DE         미정
17        LOCGOV_CNFRMR_NM         미정
18         MKR_PAPE_ATT_YN         미정
19     SBSIDY_PYMT_DCSN_DE         미정
20   SBSIDY_PYMT_IDNTFR_NM         미정
21                    CTNT         미정
22     CLNING_BTRC_TRGT_YN         미정
23        CLNING_BTRC_RESN         미정
24                 INPT_DE         미정
25                 RETR_NM         미정
26             LST_CHNG_DE         미정
27             LST_EDIR_NM         미정
28           CLNING_LST_DE         미정
29           CLNING_WHL_SE         미정
30      CLNING_RMND_SBSIDY         미정
31     CLNING_RQEST_GRP_NO         미정
32           SBSIDY_RQT_DE         미정
33        SBSIDY_APLICT_NM         미정
34          CLNING_PYMT_DE         미정
35           CLNING_BIZ_YR         미정
36          CLNING_PYMT_YN         미정
37    CLNING_REC_CNT_ELPSD         미정
38                 INST_ID         미정
39   CLNING_SPEL_RESN_RESN         미정
40    CLNING_ETC_SPEL_RESN         미정
41          RCPT_LOCGOV_CD         미정
42               NOW_VHRNO         미정
43               STRCHG_DE         미정
44                     RMK         미정
45       CLNING_WHL_ETC_SE         미정
46                  CHK_YN         미정
47                 CHK_YN1         미정
48                 EXCA_YR         미정
49                 EXCA_DE         미정
50                 EXCA_YN         미정
51                EXCA_ETC         미정
52             ASOC_RQT_YN         미정
53        CHG_EQUIP_SER_NO         미정
54        M_CHK_PLAN_MONTH         미정
55              ATT_LGCLFL         미정
56              ATT_PHYSCL         미정
57               DELETE_YN         미정
58           DELETE_REASON         미정

In [203]:
sdf.columns.to_list()

['BF_SMO_CCNTRA',
 'BF_VENTL_PSSR',
 'CLNING_YMD',
 'CLNING_ENTRPS_NM',
 'CLNING_GRNTE_WHL_SE_CD',
 'CLNING_KND_CD',
 'CLNING_PRGRS_STTS',
 'DRVNG_DSTNC',
 'PST_SMO_CCNTRA',
 'PST_VENTL_PSSR',
 'REDUC_REG_NO',
 'SBSIDY_TRGT_YN',
 'CRTN_DT']

In [204]:
slist = [
    'CLNING_GRNTE_WHL_SE_CD',
    'CLNING_KND_CD',
    'CLNING_ENTRPS_NM',
    'CLNING_YMD',
    'SBSIDY_TRGT_YN',
    'BF_SMO_CCNTRA',
    'BF_VENTL_PSSR',
    'REDUC_REG_NO',
    'PST_VENTL_PSSR',
    'CLNING_PRGRS_STTS',
    'DRVNG_DSTNC',
    'PST_SMO_CCNTRA',

    'CRTN_DT',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['클리닝보증기간구분코드',
    '클리닝종류코드',
    '클리닝업체명',
    '클리닝일자',
    '보조금대상여부',
    '이전매연농도',
    '이전배기압력',
    '저감등록번호',
    '후배기압력',
    '클리닝진행상태',
    '주행거리',
    '후매연농도',

    '미정',]
    }

scol = pd.DataFrame(sdict)
scol

                        컬럼           내용
0   CLNING_GRNTE_WHL_SE_CD  클리닝보증기간구분코드
1            CLNING_KND_CD      클리닝종류코드
2         CLNING_ENTRPS_NM       클리닝업체명
3               CLNING_YMD        클리닝일자
4           SBSIDY_TRGT_YN      보조금대상여부
5            BF_SMO_CCNTRA       이전매연농도
6            BF_VENTL_PSSR       이전배기압력
7             REDUC_REG_NO       저감등록번호
8           PST_VENTL_PSSR        후배기압력
9        CLNING_PRGRS_STTS      클리닝진행상태
10             DRVNG_DSTNC         주행거리
11          PST_SMO_CCNTRA        후매연농도
12                 CRTN_DT           미정

### 데이터 info

In [205]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CLNING_GRNTY_WHL_SE,클리닝보증기간구분,896001,CLNING_GRNTE_WHL_SE_CD,클리닝보증기간구분코드,897338.0,-1337.0,10,10.0
1,CLNING_KND,클리닝종류,896007,CLNING_KND_CD,클리닝종류코드,897344.0,-1337.0,4,4.0
2,CLNING_ENTRPS_NM,클리닝업체명,896007,CLNING_ENTRPS_NM,클리닝업체명,897344.0,-1337.0,4,4.0
3,CLNING_DE,클리닝일자,896009,CLNING_YMD,클리닝일자,897346.0,-1337.0,2,2.0
4,SBSIDY_TRGT_YN,보조금대상YN,896010,SBSIDY_TRGT_YN,보조금대상여부,897347.0,-1337.0,1,1.0

### [출력] 컬럼명, 결측치 통계

In [206]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

## 9\. 사후관리 사후점검(DLM_TB_ERP_CLEAN_SCREEN)

In [207]:
name = 'DLM_TB_ERP_CLEAN_SCREEN'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

40 8
(64951, 40) (64951, 8)

In [208]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수    행_수
ODS    40  64951
STD     8  64951

### 컬럼 확인

In [209]:
odf.columns.to_list()

['CHK_RCPT_NO',
 'REDUC_REG_NO',
 'RCPT_DE',
 'CHK_DE',
 'CHK_ODR',
 'RCPT_SIGNGU',
 'EXTRNS_REMDEL_STUS',
 'SLF_DGNSS_DVICE',
 'FUEL_SPLORE_PICK',
 'PLLTN_DNSTY_MEASUVL',
 'SMO_CO_VAL',
 'SMO_HC_VAL',
 'CHK_RSLT',
 'DIRTN_MTTR',
 'RCPT_RESN_01_YN',
 'RCPT_RESN_02_YN',
 'RCPT_RESN_03_YN',
 'RCPT_RESN_04_YN',
 'RCPT_RESN_05_YN',
 'RCPT_RESN_06_YN',
 'RCPT_RESN_07_YN',
 'RCPT_RESN_08_YN',
 'RCPT_RESN_09_YN',
 'RCPT_RESN_10_YN',
 'RCPT_RESN_11_YN',
 'RCPT_ETC_RESN',
 'BPLC_ADRS',
 'BPLC_TELNO',
 'BPLC_RPRSTV_NM',
 'REG_INST_CD',
 'INPT_DE',
 'RETR_NM',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'TRTMNT_MTTR_1_YN',
 'TRTMNT_MTTR_2_YN',
 'TRTMNT_MTTR_3_YN',
 'TRTMNT_MTTR_4_YN',
 'TRTMNT_DTLS',
 'RETR_ID']

In [210]:
olist = [
    'CHK_DE',
    'CHK_ODR',
    'TRTMNT_DTLS',
    'DIRTN_MTTR',
    'PLLTN_DNSTY_MEASUVL',
    'REDUC_REG_NO',
    'CHK_RSLT',
    'EXTRNS_REMDEL_STUS',

    'CHK_RCPT_NO',
    'RCPT_DE',
    'RCPT_SIGNGU',
    'SLF_DGNSS_DVICE',
    'FUEL_SPLORE_PICK',
    'SMO_CO_VAL',
    'SMO_HC_VAL',
    'RCPT_RESN_01_YN',
    'RCPT_RESN_02_YN',
    'RCPT_RESN_03_YN',
    'RCPT_RESN_04_YN',
    'RCPT_RESN_05_YN',
    'RCPT_RESN_06_YN',
    'RCPT_RESN_07_YN',
    'RCPT_RESN_08_YN',
    'RCPT_RESN_09_YN',
    'RCPT_RESN_10_YN',
    'RCPT_RESN_11_YN',
    'RCPT_ETC_RESN',
    'BPLC_ADRS',
    'BPLC_TELNO',
    'BPLC_RPRSTV_NM',
    'REG_INST_CD',
    'INPT_DE',
    'RETR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'TRTMNT_MTTR_1_YN',
    'TRTMNT_MTTR_2_YN',
    'TRTMNT_MTTR_3_YN',
    'TRTMNT_MTTR_4_YN',
    'RETR_ID', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['점검일자',
    '점검차수',
    '조치내역',
    '지시사항',
    '오염농도측정값',
    '저감등록번호',
    '점검결과',
    '부착개조상태',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

ocol = pd.DataFrame(odict)
ocol

                     컬럼       내용
0                CHK_DE     점검일자
1               CHK_ODR     점검차수
2           TRTMNT_DTLS     조치내역
3            DIRTN_MTTR     지시사항
4   PLLTN_DNSTY_MEASUVL  오염농도측정값
5          REDUC_REG_NO   저감등록번호
6              CHK_RSLT     점검결과
7    EXTRNS_REMDEL_STUS   부착개조상태
8           CHK_RCPT_NO       미정
9               RCPT_DE       미정
10          RCPT_SIGNGU       미정
11      SLF_DGNSS_DVICE       미정
12     FUEL_SPLORE_PICK       미정
13           SMO_CO_VAL       미정
14           SMO_HC_VAL       미정
15      RCPT_RESN_01_YN       미정
16      RCPT_RESN_02_YN       미정
17      RCPT_RESN_03_YN       미정
18      RCPT_RESN_04_YN       미정
19      RCPT_RESN_05_YN       미정
20      RCPT_RESN_06_YN       미정
21      RCPT_RESN_07_YN       미정
22      RCPT_RESN_08_YN       미정
23      RCPT_RESN_09_YN       미정
24      RCPT_RESN_10_YN       미정
25      RCPT_RESN_11_YN       미정
26        RCPT_ETC_RESN       미정
27            BPLC_ADRS       미정
28           BPLC_TELNO       미정
29       BPLC_RPRSTV_NM       미정
30          REG_INST_CD       미정
31              INPT_DE       미정
32              RETR_NM       미정
33          LST_CHNG_DE       미정
34          LST_EDIR_NM       미정
35     TRTMNT_MTTR_1_YN       미정
36     TRTMNT_MTTR_2_YN       미정
37     TRTMNT_MTTR_3_YN       미정
38     TRTMNT_MTTR_4_YN       미정
39              RETR_ID       미정

In [211]:
sdf.columns.to_list()

['CHCK_DT',
 'CHCK_ODR_CD',
 'CHCK_RSLT_CD',
 'DIRTN_MTTR_CD',
 'DVIE_EXTNS_REMDL_STS_CD',
 'PLLTN_CCNTRA_MSTVL',
 'RDCDVC_REG_NO',
 'ACTN_BRKWN']

In [212]:
slist = [
    'CHCK_DT',
    'CHCK_ODR_CD',
    'ACTN_BRKWN',
    'DIRTN_MTTR_CD',
    'PLLTN_CCNTRA_MSTVL',
    'RDCDVC_REG_NO',
    'CHCK_RSLT_CD',
    'DVIE_EXTNS_REMDL_STS_CD',

    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['점검일시',
    '점검차수코드',
    '조치내역',
    '지시사항코드',
    '오염농도측정값',
    '저감장치등록번호',
    '점검결과코드',
    '장치부착개조상태',]
    }

scol = pd.DataFrame(sdict)
scol

                        컬럼        내용
0                  CHCK_DT      점검일시
1              CHCK_ODR_CD    점검차수코드
2               ACTN_BRKWN      조치내역
3            DIRTN_MTTR_CD    지시사항코드
4       PLLTN_CCNTRA_MSTVL   오염농도측정값
5            RDCDVC_REG_NO  저감장치등록번호
6             CHCK_RSLT_CD    점검결과코드
7  DVIE_EXTNS_REMDL_STS_CD  장치부착개조상태

### 데이터 info

In [213]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CHK_DE,점검일자,64951,CHCK_DT,점검일시,64951.0,0.0,0,0.0
1,CHK_ODR,점검차수,50015,CHCK_ODR_CD,점검차수코드,50015.0,0.0,14936,14936.0
2,TRTMNT_DTLS,조치내역,1697,ACTN_BRKWN,조치내역,1697.0,0.0,63254,63254.0
3,DIRTN_MTTR,지시사항,11070,DIRTN_MTTR_CD,지시사항코드,11069.0,1.0,53881,53882.0
4,PLLTN_DNSTY_MEASUVL,오염농도측정값,62121,PLLTN_CCNTRA_MSTVL,오염농도측정값,62121.0,0.0,2830,2830.0

### [출력] 컬럼명, 결측치 통계

In [214]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

## 10\. 노후차 조기폐차 관리정보(수도권)(DLM_TB_ERP_EARLY_ERASE_AEA)

In [4]:
name = 'DLM_TB_ERP_EARLY_ERASE_AEA'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

177 15
(770311, 177) (770117, 15)

In [5]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS   177  770311
STD    15  770117

### 컬럼 확인

In [6]:
odf.columns.to_list()

['ELPDSRC_MNGT_NO',
 'ELPDSRC_STUS_CD',
 'RDCDVC_SE',
 'INST_ID_CD',
 'OWNR_NM',
 'USER_BIZRNO',
 'USER_TELNO',
 'FXNUM',
 'USER_ZIP',
 'USER_1_ADRS',
 'USER_2_ADRS',
 'RCPT_SIDO',
 'RCPT_SIGNGU',
 'VHRNO',
 'VIN',
 'VHCL_YRIDNW',
 'EGINCTY',
 'VHCL_PSCP',
 'VHCL_WGHT',
 'TOT_WGHT',
 'CRYNG_WGHT',
 'VHCNM',
 'VHCL_FRM',
 'VHCTY',
 'VHCL_PURPS',
 'FST_REG_DE',
 'SCRCAR_REG_DRVNG_DSTNC',
 'SCRCAR_ERA_DRVNG_DSTNC',
 'VHCL_FUEL',
 'PRCINSP_DE',
 'INSPOF_NM',
 'PRCINSP_JDGMNT_YN',
 'PRCINSP_RSLT_VAL',
 'PRCINSP_JDGMNT_STDR_VAL',
 'RCPT_DE',
 'INPT_DE',
 'RETR_NM',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_TRGT_1_AT',
 'ELPDSRC_TRGT_2_AT',
 'ELPDSRC_TRGT_3_AT',
 'ELPDSRC_TRGT_4_AT',
 'ELPDSRC_TRGT_5_AT',
 'ELPDSRC_TRGT_6_AT',
 'ELPDSRC_TRGT_7_AT',
 'ELPDSRC_TRGT_CNFRM_REG_DE',
 'ELPDSRC_TRGT_CNFRM_REGR_NM',
 'PYMT_CNFRM_YN',
 'EXPC_SPRT_AMT',
 'DCIS_SPRT_AMT',
 'SBSIDY_UNPAY_RESN',
 'SBSIDY_RQEST_DE',
 'SBSIDY_RQEST_REGR_NM',
 'DOC_CNFRM_NO',
 'DOC_OUTT_DE',
 'INSP_RQT_SIWA_MTHD',
 'INSP_RQT_DE',
 'INSP_RQT_TM',
 'VRSC_ENTRPS_NM',
 'AGENT_ZIP',
 'AGENT_1_ADRS',
 'AGENT_2_ADRS',
 'AGENT_TELNO',
 'AGENT_CRTC_NO',
 'INSP_RQT_REG_DE',
 'INSP_RQT_REGR_NM',
 'PFMINPC_DE',
 'PFMINPC_1_ITM',
 'PFMINPC_2_ITM',
 'PFMINPC_3_ITM',
 'PFMINPC_4_ITM',
 'PFMINPC_5_ITM',
 'PFMINPC_ETC_ITM',
 'PFMINPC_ITM_ETC_CMPNT_NM',
 'PFMINPC_FILE_ATT_YN',
 'PFMINPC_ELPDSRC_YN',
 'PFMINPC_ELPDSRC_IMPSBL_RESN',
 'PFMINPC_REG_DE',
 'PFMINPC_REGR_NM',
 'PFMINPC_PAPE_OUTT_DE',
 'TRTMNT_DE',
 'ERSR_DE',
 'NCAR_PUCH_PLAN_DE',
 'NCAR_PUCH_PLAN_VHCL_NM',
 'SCRCAR_ENTRPS_NM',
 'SCRCAR_ENTRPS_ZIP',
 'SCRCAR_ENTRPS_1_ADRS',
 'SCRCAR_ENTRPS_2_ADRS',
 'ELPDSRC_ATT_FILE_1_YN',
 'ELPDSRC_ATT_FILE_2_YN',
 'ELPDSRC_ATT_FILE_3_YN',
 'ELPDSRC_REG_DE',
 'ELPDSRC_REGR_NM',
 'ELPDSRC_LST_CNFRM_YN',
 'ELPDSRC_LST_UNAP_RESN',
 'SBSIDY_PYMT_DE',
 'SBSIDY_BIZ_YR',
 'ELPDSRC_LST_CNFRM_DE',
 'ELPDSRC_LST_APRR_NM',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'LWBCT_YN',
 'NOW_VHRNO',
 'ELPDSRC_ATT_FILE_4_YN',
 'BANK_NM',
 'BANK_ACC_NO',
 'PRCINSP_SE',
 'RCPT_LOCGOV_CD',
 'RPRSTV_NM',
 'BIZCND',
 'TYPBIZ',
 'EMAIL',
 'RCPT_SE',
 'INSP_SE',
 'ELPDSRC_TRGT_AT_ETC_RESN',
 'HST_MNGT_NO',
 'CTNT',
 'VHCTY_SE',
 'ELPDSRC_GRP',
 'BTHDY',
 'JURIRNO',
 'STDR_YM',
 'STDR_AMT',
 'WHL_EXCS_CNFRM_DE',
 'WHL_EXCS_APRR_NM',
 'MNFCT_DE',
 'OLD_SIDO',
 'OLD_SIGNGU',
 'OLD_RCPT_LOCGOV_CD',
 'OLD_1_ADRS',
 'OLD_2_ADRS',
 'OLD_VHCL_PURPS',
 'BAI_ID',
 'ADITOR_NM',
 'REG_NO',
 'RQEST_ARVL_DE',
 'RQEST_ARVL_YN',
 'BIL_CNFRMR_NM',
 'ADD_AMT',
 'SAMNS_CNFRM',
 'ADD_RQEST_ARVL_YN',
 'ADD_RQEST_ARVL_DE',
 'ADD_RQEST_CNFRMR_NM',
 'ATT_PAPE_CNFRM_AT',
 'BEF_STUS_CD',
 'WAREHOUSING_DE',
 'WAREHOUSING_YN',
 'MNTNG_IMPR_YN',
 'MNTNG_IMPR_AMT',
 'ELPDSRC_ATT_FILE_5_YN',
 'ELPDSRC_VRSC_INST_NO',
 'SMAL_BUSIN_YN',
 'INPT_MTHD_FLAG',
 'ELPDSRC_ATT_FILE_7_YN',
 'STNDRD',
 'ENGINE_RPM',
 'MAKER',
 'CAR_GRADE',
 'AID_RJCT_DE',
 'IMG_LGCLFL1',
 'IMG_PHYSCL1',
 'IMG_LGCLFL2',
 'IMG_PHYSCL2',
 'IMG_LGCLFL3',
 'IMG_PHYSCL3',
 'IMG_LGCLFL4',
 'IMG_PHYSCL4',
 'PRE_SCRAP_CAR_YN',
 'DEP_YN',
 'VIRT_ACC_NO',
 'ELCTY_HYDRO_CAR_ADD_AMT',
 'PFMINPC_ITSL_APPRNC',
 'PFMINPC_BUFFER_DVICE',
 'PFMINPC_WINDOW',
 'PFMINPC_TIRE',
 'PFMINPC_ASSMI_DEVICE',
 'PFMINPC_ELPDSRC_GNRLZ_RESN']

In [7]:
olist = [
    'VHRNO',
    'VIN',
    'ELPDSRC_LST_CNFRM_YN',
    'ELPDSRC_STUS_CD',
    'ERSR_DE',
    'RCPT_SIDO',
    'RDCDVC_SE',
    'MNTNG_IMPR_YN',
    'SCRCAR_REG_DRVNG_DSTNC',

    'ELPDSRC_MNGT_NO',
    'INST_ID_CD',
    'OWNR_NM',
    'USER_BIZRNO',
    'USER_TELNO',
    'FXNUM',
    'USER_ZIP',
    'USER_1_ADRS',
    'USER_2_ADRS',
    'RCPT_SIGNGU',
    'VHCL_YRIDNW',
    'EGINCTY',
    'VHCL_PSCP',
    'VHCL_WGHT',
    'TOT_WGHT',
    'CRYNG_WGHT',
    'VHCNM',
    'VHCL_FRM',
    'VHCTY',
    'VHCL_PURPS',
    'FST_REG_DE',
    'SCRCAR_ERA_DRVNG_DSTNC',
    'VHCL_FUEL',
    'PRCINSP_DE',
    'INSPOF_NM',
    'PRCINSP_JDGMNT_YN',
    'PRCINSP_RSLT_VAL',
    'PRCINSP_JDGMNT_STDR_VAL',
    'RCPT_DE',
    'INPT_DE',
    'RETR_NM',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_TRGT_1_AT',
    'ELPDSRC_TRGT_2_AT',
    'ELPDSRC_TRGT_3_AT',
    'ELPDSRC_TRGT_4_AT',
    'ELPDSRC_TRGT_5_AT',
    'ELPDSRC_TRGT_6_AT',
    'ELPDSRC_TRGT_7_AT',
    'ELPDSRC_TRGT_CNFRM_REG_DE',
    'ELPDSRC_TRGT_CNFRM_REGR_NM',
    'PYMT_CNFRM_YN',
    'EXPC_SPRT_AMT',
    'DCIS_SPRT_AMT',
    'SBSIDY_UNPAY_RESN',
    'SBSIDY_RQEST_DE',
    'SBSIDY_RQEST_REGR_NM',
    'DOC_CNFRM_NO',
    'DOC_OUTT_DE',
    'INSP_RQT_SIWA_MTHD',
    'INSP_RQT_DE',
    'INSP_RQT_TM',
    'VRSC_ENTRPS_NM',
    'AGENT_ZIP',
    'AGENT_1_ADRS',
    'AGENT_2_ADRS',
    'AGENT_TELNO',
    'AGENT_CRTC_NO',
    'INSP_RQT_REG_DE',
    'INSP_RQT_REGR_NM',
    'PFMINPC_DE',
    'PFMINPC_1_ITM',
    'PFMINPC_2_ITM',
    'PFMINPC_3_ITM',
    'PFMINPC_4_ITM',
    'PFMINPC_5_ITM',
    'PFMINPC_ETC_ITM',
    'PFMINPC_ITM_ETC_CMPNT_NM',
    'PFMINPC_FILE_ATT_YN',
    'PFMINPC_ELPDSRC_YN',
    'PFMINPC_ELPDSRC_IMPSBL_RESN',
    'PFMINPC_REG_DE',
    'PFMINPC_REGR_NM',
    'PFMINPC_PAPE_OUTT_DE',
    'TRTMNT_DE',
    'NCAR_PUCH_PLAN_DE',
    'NCAR_PUCH_PLAN_VHCL_NM',
    'SCRCAR_ENTRPS_NM',
    'SCRCAR_ENTRPS_ZIP',
    'SCRCAR_ENTRPS_1_ADRS',
    'SCRCAR_ENTRPS_2_ADRS',
    'ELPDSRC_ATT_FILE_1_YN',
    'ELPDSRC_ATT_FILE_2_YN',
    'ELPDSRC_ATT_FILE_3_YN',
    'ELPDSRC_REG_DE',
    'ELPDSRC_REGR_NM',
    'ELPDSRC_LST_UNAP_RESN',
    'SBSIDY_PYMT_DE',
    'SBSIDY_BIZ_YR',
    'ELPDSRC_LST_CNFRM_DE',
    'ELPDSRC_LST_APRR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'LWBCT_YN',
    'NOW_VHRNO',
    'ELPDSRC_ATT_FILE_4_YN',
    'BANK_NM',
    'BANK_ACC_NO',
    'PRCINSP_SE',
    'RCPT_LOCGOV_CD',
    'RPRSTV_NM',
    'BIZCND',
    'TYPBIZ',
    'EMAIL',
    'RCPT_SE',
    'INSP_SE',
    'ELPDSRC_TRGT_AT_ETC_RESN',
    'HST_MNGT_NO',
    'CTNT',
    'VHCTY_SE',
    'ELPDSRC_GRP',
    'BTHDY',
    'JURIRNO',
    'STDR_YM',
    'STDR_AMT',
    'WHL_EXCS_CNFRM_DE',
    'WHL_EXCS_APRR_NM',
    'MNFCT_DE',
    'OLD_SIDO',
    'OLD_SIGNGU',
    'OLD_RCPT_LOCGOV_CD',
    'OLD_1_ADRS',
    'OLD_2_ADRS',
    'OLD_VHCL_PURPS',
    'BAI_ID',
    'ADITOR_NM',
    'REG_NO',
    'RQEST_ARVL_DE',
    'RQEST_ARVL_YN',
    'BIL_CNFRMR_NM',
    'ADD_AMT',
    'SAMNS_CNFRM',
    'ADD_RQEST_ARVL_YN',
    'ADD_RQEST_ARVL_DE',
    'ADD_RQEST_CNFRMR_NM',
    'ATT_PAPE_CNFRM_AT',
    'BEF_STUS_CD',
    'WAREHOUSING_DE',
    'WAREHOUSING_YN',
    'MNTNG_IMPR_AMT',
    'ELPDSRC_ATT_FILE_5_YN',
    'ELPDSRC_VRSC_INST_NO',
    'SMAL_BUSIN_YN',
    'INPT_MTHD_FLAG',
    'ELPDSRC_ATT_FILE_7_YN',
    'STNDRD',
    'ENGINE_RPM',
    'MAKER',
    'CAR_GRADE',
    'AID_RJCT_DE',
    'IMG_LGCLFL1',
    'IMG_PHYSCL1',
    'IMG_LGCLFL2',
    'IMG_PHYSCL2',
    'IMG_LGCLFL3',
    'IMG_PHYSCL3',
    'IMG_LGCLFL4',
    'IMG_PHYSCL4',
    'PRE_SCRAP_CAR_YN',
    'DEP_YN',
    'VIRT_ACC_NO',
    'ELCTY_HYDRO_CAR_ADD_AMT',
    'PFMINPC_ITSL_APPRNC',
    'PFMINPC_BUFFER_DVICE',
    'PFMINPC_WINDOW',
    'PFMINPC_TIRE',
    'PFMINPC_ASSMI_DEVICE',
    'PFMINPC_ELPDSRC_GNRLZ_RESN', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    [
    '차량등록번호',
    '차대번호',
    '조기폐차최종승인YN',
    '조기폐차상태코드',
    '말소일자',
    '접수시도',
    '저감장치구분',
    '저감장치 미개발(부착불가)여부',
    '폐차등록주행거리',

    'ELPDSRC_MNGT_NO',
    'INST_ID_CD',
    'OWNR_NM',
    'USER_BIZRNO',
    'USER_TELNO',
    'FXNUM',
    'USER_ZIP',
    'USER_1_ADRS',
    'USER_2_ADRS',
    'RCPT_SIGNGU',
    'VHCL_YRIDNW',
    'EGINCTY',
    'VHCL_PSCP',
    'VHCL_WGHT',
    'TOT_WGHT',
    'CRYNG_WGHT',
    'VHCNM',
    'VHCL_FRM',
    'VHCTY',
    'VHCL_PURPS',
    'FST_REG_DE',
    'SCRCAR_ERA_DRVNG_DSTNC',
    'VHCL_FUEL',
    'PRCINSP_DE',
    'INSPOF_NM',
    'PRCINSP_JDGMNT_YN',
    'PRCINSP_RSLT_VAL',
    'PRCINSP_JDGMNT_STDR_VAL',
    'RCPT_DE',
    'INPT_DE',
    'RETR_NM',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_TRGT_1_AT',
    'ELPDSRC_TRGT_2_AT',
    'ELPDSRC_TRGT_3_AT',
    'ELPDSRC_TRGT_4_AT',
    'ELPDSRC_TRGT_5_AT',
    'ELPDSRC_TRGT_6_AT',
    'ELPDSRC_TRGT_7_AT',
    'ELPDSRC_TRGT_CNFRM_REG_DE',
    'ELPDSRC_TRGT_CNFRM_REGR_NM',
    'PYMT_CNFRM_YN',
    'EXPC_SPRT_AMT',
    'DCIS_SPRT_AMT',
    'SBSIDY_UNPAY_RESN',
    'SBSIDY_RQEST_DE',
    'SBSIDY_RQEST_REGR_NM',
    'DOC_CNFRM_NO',
    'DOC_OUTT_DE',
    'INSP_RQT_SIWA_MTHD',
    'INSP_RQT_DE',
    'INSP_RQT_TM',
    'VRSC_ENTRPS_NM',
    'AGENT_ZIP',
    'AGENT_1_ADRS',
    'AGENT_2_ADRS',
    'AGENT_TELNO',
    'AGENT_CRTC_NO',
    'INSP_RQT_REG_DE',
    'INSP_RQT_REGR_NM',
    'PFMINPC_DE',
    'PFMINPC_1_ITM',
    'PFMINPC_2_ITM',
    'PFMINPC_3_ITM',
    'PFMINPC_4_ITM',
    'PFMINPC_5_ITM',
    'PFMINPC_ETC_ITM',
    'PFMINPC_ITM_ETC_CMPNT_NM',
    'PFMINPC_FILE_ATT_YN',
    'PFMINPC_ELPDSRC_YN',
    'PFMINPC_ELPDSRC_IMPSBL_RESN',
    'PFMINPC_REG_DE',
    'PFMINPC_REGR_NM',
    'PFMINPC_PAPE_OUTT_DE',
    'TRTMNT_DE',
    'NCAR_PUCH_PLAN_DE',
    'NCAR_PUCH_PLAN_VHCL_NM',
    'SCRCAR_ENTRPS_NM',
    'SCRCAR_ENTRPS_ZIP',
    'SCRCAR_ENTRPS_1_ADRS',
    'SCRCAR_ENTRPS_2_ADRS',
    'ELPDSRC_ATT_FILE_1_YN',
    'ELPDSRC_ATT_FILE_2_YN',
    'ELPDSRC_ATT_FILE_3_YN',
    'ELPDSRC_REG_DE',
    'ELPDSRC_REGR_NM',
    'ELPDSRC_LST_UNAP_RESN',
    'SBSIDY_PYMT_DE',
    'SBSIDY_BIZ_YR',
    'ELPDSRC_LST_CNFRM_DE',
    'ELPDSRC_LST_APRR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'LWBCT_YN',
    'NOW_VHRNO',
    'ELPDSRC_ATT_FILE_4_YN',
    'BANK_NM',
    'BANK_ACC_NO',
    'PRCINSP_SE',
    'RCPT_LOCGOV_CD',
    'RPRSTV_NM',
    'BIZCND',
    'TYPBIZ',
    'EMAIL',
    'RCPT_SE',
    'INSP_SE',
    'ELPDSRC_TRGT_AT_ETC_RESN',
    'HST_MNGT_NO',
    'CTNT',
    'VHCTY_SE',
    'ELPDSRC_GRP',
    'BTHDY',
    'JURIRNO',
    'STDR_YM',
    'STDR_AMT',
    'WHL_EXCS_CNFRM_DE',
    'WHL_EXCS_APRR_NM',
    'MNFCT_DE',
    'OLD_SIDO',
    'OLD_SIGNGU',
    'OLD_RCPT_LOCGOV_CD',
    'OLD_1_ADRS',
    'OLD_2_ADRS',
    'OLD_VHCL_PURPS',
    'BAI_ID',
    'ADITOR_NM',
    'REG_NO',
    'RQEST_ARVL_DE',
    'RQEST_ARVL_YN',
    'BIL_CNFRMR_NM',
    'ADD_AMT',
    'SAMNS_CNFRM',
    'ADD_RQEST_ARVL_YN',
    'ADD_RQEST_ARVL_DE',
    'ADD_RQEST_CNFRMR_NM',
    'ATT_PAPE_CNFRM_AT',
    'BEF_STUS_CD',
    'WAREHOUSING_DE',
    'WAREHOUSING_YN',
    'MNTNG_IMPR_AMT',
    'ELPDSRC_ATT_FILE_5_YN',
    'ELPDSRC_VRSC_INST_NO',
    'SMAL_BUSIN_YN',
    'INPT_MTHD_FLAG',
    'ELPDSRC_ATT_FILE_7_YN',
    'STNDRD',
    'ENGINE_RPM',
    'MAKER',
    'CAR_GRADE',
    'AID_RJCT_DE',
    'IMG_LGCLFL1',
    'IMG_PHYSCL1',
    'IMG_LGCLFL2',
    'IMG_PHYSCL2',
    'IMG_LGCLFL3',
    'IMG_PHYSCL3',
    'IMG_LGCLFL4',
    'IMG_PHYSCL4',
    'PRE_SCRAP_CAR_YN',
    'DEP_YN',
    'VIRT_ACC_NO',
    'ELCTY_HYDRO_CAR_ADD_AMT',
    'PFMINPC_ITSL_APPRNC',
    'PFMINPC_BUFFER_DVICE',
    'PFMINPC_WINDOW',
    'PFMINPC_TIRE',
    'PFMINPC_ASSMI_DEVICE',
    'PFMINPC_ELPDSRC_GNRLZ_RESN',
    ]
    }

ocol = pd.DataFrame(odict)
ocol

                             컬럼                          내용
0                         VHRNO                      차량등록번호
1                           VIN                        차대번호
2          ELPDSRC_LST_CNFRM_YN                  조기폐차최종승인YN
3               ELPDSRC_STUS_CD                    조기폐차상태코드
4                       ERSR_DE                        말소일자
..                          ...                         ...
172        PFMINPC_BUFFER_DVICE        PFMINPC_BUFFER_DVICE
173              PFMINPC_WINDOW              PFMINPC_WINDOW
174                PFMINPC_TIRE                PFMINPC_TIRE
175        PFMINPC_ASSMI_DEVICE        PFMINPC_ASSMI_DEVICE
176  PFMINPC_ELPDSRC_GNRLZ_RESN  PFMINPC_ELPDSRC_GNRLZ_RESN

[177 rows x 2 columns]

In [8]:
sdf.columns.to_list()

['ELPDSRC_LST_APRV_YN',
 'ELPDSRC_STTS_CD',
 'ERSR_YMD',
 'RDCDVC_EXTRNS_YN',
 'STDG_CTPV_NM',
 'LEM_KND_CD',
 'SCCAR_REG_DRVNG_DSNC',
 'VHRNO',
 'VIN',
 'CRTN_DT',
 'STDG_SGG_NM',
 'SCRCAR_ENTRPS_NM',
 'ELPDSRC_LAST_APRV_YMD',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_MNG_NO']

In [9]:
slist = [
    'VHRNO',
    'VIN',
    'ELPDSRC_LST_APRV_YN',
    'ELPDSRC_STTS_CD',
    'ERSR_YMD',
    'STDG_CTPV_NM',
    'LEM_KND_CD',
    'RDCDVC_EXTRNS_YN',
    'SCCAR_REG_DRVNG_DSNC',

    'CRTN_DT',
    'STDG_SGG_NM',
    'SCRCAR_ENTRPS_NM',
    'ELPDSRC_LAST_APRV_YMD',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_MNG_NO',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['자동차등록번호',
    '차대번호',
    '조기폐차최종승인여부',
    '조기폐차상태코드',
    '말소일자',
    '법정동시도명',
    '저공해조치종류코드',
    '저감장치부착여부',
    '폐차등록주행거리',

    'CRTN_DT',
    'STDG_SGG_NM',
    'SCRCAR_ENTRPS_NM',
    'ELPDSRC_LAST_APRV_YMD',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_MNG_NO',]
    }

scol = pd.DataFrame(sdict)
scol

                       컬럼                     내용
0                   VHRNO                자동차등록번호
1                     VIN                   차대번호
2     ELPDSRC_LST_APRV_YN             조기폐차최종승인여부
3         ELPDSRC_STTS_CD               조기폐차상태코드
4                ERSR_YMD                   말소일자
5            STDG_CTPV_NM                 법정동시도명
6              LEM_KND_CD              저공해조치종류코드
7        RDCDVC_EXTRNS_YN               저감장치부착여부
8    SCCAR_REG_DRVNG_DSNC               폐차등록주행거리
9                 CRTN_DT                CRTN_DT
10            STDG_SGG_NM            STDG_SGG_NM
11       SCRCAR_ENTRPS_NM       SCRCAR_ENTRPS_NM
12  ELPDSRC_LAST_APRV_YMD  ELPDSRC_LAST_APRV_YMD
13         SBSIDY_TRGT_YN         SBSIDY_TRGT_YN
14         ELPDSRC_MNG_NO         ELPDSRC_MNG_NO

### 데이터 info

In [10]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,VHRNO,차량등록번호,770311,VHRNO,자동차등록번호,770117.00,194.00,0,0.00
1,VIN,차대번호,770311,VIN,차대번호,770117.00,194.00,0,0.00
2,ELPDSRC_LST_CNFRM_YN,조기폐차최종승인YN,680625,ELPDSRC_LST_APRV_YN,조기폐차최종승인여부,679295.00,1330.00,89686,90822.00
3,ELPDSRC_STUS_CD,조기폐차상태코드,770311,ELPDSRC_STTS_CD,조기폐차상태코드,770117.00,194.00,0,0.00
4,ERSR_DE,말소일자,684061,ERSR_YMD,말소일자,683275.00,786.00,86250,86842.00

### [출력] 컬럼명, 결측치 통계

In [11]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

[정제]DLM_TB_ERP_EARLY_ERASE_AEA.xlsx 출력완료.

### [분석]

#### 차대번호

In [112]:
len(odf2['VIN'].unique()), len(sdf2['VIN'].unique())

(726685, 726531)

In [113]:
len(set(odf2['VIN'].unique()) - set(sdf2['VIN'].unique()))

154

#### 자동차등록번호

In [114]:
odf2['VHRNO'].unique()

array(['73부5582', '93소6048', '경기74도2843', ..., '95가6781', '34라7344',
       '16노1683'], dtype=object)

In [115]:
sdf2['VHRNO'].unique()

array(['86버2178', '경기45고8541', '60부4671', ..., '인천73도1071', '경기71로3834',
       '39다4211'], dtype=object)

## 11\. 노후차 조기폐차 관리정보(수도권 외)(DLM_TB_ERP_EARLY_ERASE_LGV)

In [12]:
name = 'DLM_TB_ERP_EARLY_ERASE_LGV'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

170 14
(291353, 170) (291353, 14)

In [13]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS   170  291353
STD    14  291353

### 컬럼 확인

In [14]:
odf.columns.to_list()

['ELPDSRC_MNGT_NO',
 'ELPDSRC_STUS_CD',
 'RDCDVC_SE',
 'INST_ID_CD',
 'OWNR_NM',
 'USER_BIZRNO',
 'USER_TELNO',
 'FXNUM',
 'USER_ZIP',
 'USER_1_ADRS',
 'USER_2_ADRS',
 'RCPT_SIDO',
 'RCPT_SIGNGU',
 'VHRNO',
 'VIN',
 'VHCL_YRIDNW',
 'EGINCTY',
 'VHCL_PSCP',
 'VHCL_WGHT',
 'TOT_WGHT',
 'CRYNG_WGHT',
 'VHCNM',
 'VHCL_FRM',
 'VHCTY',
 'VHCL_PURPS',
 'FST_REG_DE',
 'SCRCAR_REG_DRVNG_DSTNC',
 'SCRCAR_ERA_DRVNG_DSTNC',
 'VHCL_FUEL',
 'PRCINSP_DE',
 'INSPOF_NM',
 'PRCINSP_JDGMNT_YN',
 'PRCINSP_RSLT_VAL',
 'PRCINSP_JDGMNT_STDR_VAL',
 'RCPT_DE',
 'INPT_DE',
 'RETR_NM',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_TRGT_1_AT',
 'ELPDSRC_TRGT_2_AT',
 'ELPDSRC_TRGT_3_AT',
 'ELPDSRC_TRGT_4_AT',
 'ELPDSRC_TRGT_5_AT',
 'ELPDSRC_TRGT_6_AT',
 'ELPDSRC_TRGT_7_AT',
 'ELPDSRC_TRGT_CNFRM_REG_DE',
 'ELPDSRC_TRGT_CNFRM_REGR_NM',
 'PYMT_CNFRM_YN',
 'EXPC_SPRT_AMT',
 'DCIS_SPRT_AMT',
 'SBSIDY_UNPAY_RESN',
 'SBSIDY_RQEST_DE',
 'SBSIDY_RQEST_REGR_NM',
 'DOC_CNFRM_NO',
 'DOC_OUTT_DE',
 'INSP_RQT_SIWA_MTHD',
 'INSP_RQT_DE',
 'INSP_RQT_TM',
 'VRSC_ENTRPS_NM',
 'AGENT_ZIP',
 'AGENT_1_ADRS',
 'AGENT_2_ADRS',
 'AGENT_TELNO',
 'AGENT_CRTC_NO',
 'INSP_RQT_REG_DE',
 'INSP_RQT_REGR_NM',
 'PFMINPC_DE',
 'PFMINPC_1_ITM',
 'PFMINPC_2_ITM',
 'PFMINPC_3_ITM',
 'PFMINPC_4_ITM',
 'PFMINPC_5_ITM',
 'PFMINPC_ETC_ITM',
 'PFMINPC_ITM_ETC_CMPNT_NM',
 'PFMINPC_FILE_ATT_YN',
 'PFMINPC_ELPDSRC_YN',
 'PFMINPC_ELPDSRC_IMPSBL_RESN',
 'PFMINPC_REG_DE',
 'PFMINPC_REGR_NM',
 'PFMINPC_PAPE_OUTT_DE',
 'TRTMNT_DE',
 'ERSR_DE',
 'NCAR_PUCH_PLAN_DE',
 'NCAR_PUCH_PLAN_VHCL_NM',
 'SCRCAR_ENTRPS_NM',
 'SCRCAR_ENTRPS_ZIP',
 'SCRCAR_ENTRPS_1_ADRS',
 'SCRCAR_ENTRPS_2_ADRS',
 'ELPDSRC_ATT_FILE_1_YN',
 'ELPDSRC_ATT_FILE_2_YN',
 'ELPDSRC_ATT_FILE_3_YN',
 'ELPDSRC_REG_DE',
 'ELPDSRC_REGR_NM',
 'ELPDSRC_LST_CNFRM_YN',
 'ELPDSRC_LST_UNAP_RESN',
 'SBSIDY_PYMT_DE',
 'SBSIDY_BIZ_YR',
 'ELPDSRC_LST_CNFRM_DE',
 'ELPDSRC_LST_APRR_NM',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'LWBCT_YN',
 'NOW_VHRNO',
 'ELPDSRC_ATT_FILE_4_YN',
 'BANK_NM',
 'BANK_ACC_NO',
 'PRCINSP_SE',
 'RCPT_LOCGOV_CD',
 'RPRSTV_NM',
 'BIZCND',
 'TYPBIZ',
 'EMAIL',
 'RCPT_SE',
 'INSP_SE',
 'ELPDSRC_TRGT_AT_ETC_RESN',
 'HST_MNGT_NO',
 'CTNT',
 'VHCTY_SE',
 'ELPDSRC_GRP',
 'BTHDY',
 'JURIRNO',
 'STDR_YM',
 'STDR_AMT',
 'WHL_EXCS_CNFRM_DE',
 'WHL_EXCS_APRR_NM',
 'MNFCT_DE',
 'OLD_SIDO',
 'OLD_SIGNGU',
 'OLD_RCPT_LOCGOV_CD',
 'OLD_1_ADRS',
 'OLD_2_ADRS',
 'OLD_VHCL_PURPS',
 'BAI_ID',
 'ADITOR_NM',
 'REG_NO',
 'RQEST_ARVL_DE',
 'RQEST_ARVL_YN',
 'BIL_CNFRMR_NM',
 'ADD_AMT',
 'SAMNS_CNFRM',
 'ADD_RQEST_ARVL_YN',
 'ADD_RQEST_ARVL_DE',
 'ADD_RQEST_CNFRMR_NM',
 'ATT_PAPE_CNFRM_AT',
 'BEF_STUS_CD',
 'WAREHOUSING_DE',
 'WAREHOUSING_YN',
 'MNTNG_IMPR_YN',
 'MNTNG_IMPR_AMT',
 'ELPDSRC_ATT_FILE_5_YN',
 'SMAL_BUSIN_YN',
 'INPT_MTHD_FLAG',
 'ELPDSRC_ATT_FILE_7_YN',
 'AID_RJCT_DE',
 'IMG_LGCLFL1',
 'IMG_PHYSCL1',
 'IMG_LGCLFL2',
 'IMG_PHYSCL2',
 'IMG_LGCLFL3',
 'IMG_PHYSCL3',
 'IMG_LGCLFL4',
 'IMG_PHYSCL4',
 'PRE_SCRAP_CAR_YN',
 'ELCTY_HYDRO_CAR_ADD_AMT',
 'PFMINPC_ITSL_APPRNC',
 'PFMINPC_BUFFER_DVICE',
 'PFMINPC_WINDOW',
 'PFMINPC_TIRE',
 'PFMINPC_ASSMI_DEVICE',
 'PFMINPC_ELPDSRC_GNRLZ_RESN']

In [15]:
olist = [
    'RCPT_SIDO',
    'RDCDVC_SE',
    'MNTNG_IMPR_YN',
    'ELPDSRC_LST_CNFRM_YN',
    'ERSR_DE',
    'SCRCAR_REG_DRVNG_DSTNC',
    'VHRNO',
    'VIN',
    'ELPDSRC_STUS_CD',

    'ELPDSRC_MNGT_NO',
    'INST_ID_CD',
    'OWNR_NM',
    'USER_BIZRNO',
    'USER_TELNO',
    'FXNUM',
    'USER_ZIP',
    'USER_1_ADRS',
    'USER_2_ADRS',
    'RCPT_SIGNGU',
    'VHCL_YRIDNW',
    'EGINCTY',
    'VHCL_PSCP',
    'VHCL_WGHT',
    'TOT_WGHT',
    'CRYNG_WGHT',
    'VHCNM',
    'VHCL_FRM',
    'VHCTY',
    'VHCL_PURPS',
    'FST_REG_DE',
    'SCRCAR_ERA_DRVNG_DSTNC',
    'VHCL_FUEL',
    'PRCINSP_DE',
    'INSPOF_NM',
    'PRCINSP_JDGMNT_YN',
    'PRCINSP_RSLT_VAL',
    'PRCINSP_JDGMNT_STDR_VAL',
    'RCPT_DE',
    'INPT_DE',
    'RETR_NM',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_TRGT_1_AT',
    'ELPDSRC_TRGT_2_AT',
    'ELPDSRC_TRGT_3_AT',
    'ELPDSRC_TRGT_4_AT',
    'ELPDSRC_TRGT_5_AT',
    'ELPDSRC_TRGT_6_AT',
    'ELPDSRC_TRGT_7_AT',
    'ELPDSRC_TRGT_CNFRM_REG_DE',
    'ELPDSRC_TRGT_CNFRM_REGR_NM',
    'PYMT_CNFRM_YN',
    'EXPC_SPRT_AMT',
    'DCIS_SPRT_AMT',
    'SBSIDY_UNPAY_RESN',
    'SBSIDY_RQEST_DE',
    'SBSIDY_RQEST_REGR_NM',
    'DOC_CNFRM_NO',
    'DOC_OUTT_DE',
    'INSP_RQT_SIWA_MTHD',
    'INSP_RQT_DE',
    'INSP_RQT_TM',
    'VRSC_ENTRPS_NM',
    'AGENT_ZIP',
    'AGENT_1_ADRS',
    'AGENT_2_ADRS',
    'AGENT_TELNO',
    'AGENT_CRTC_NO',
    'INSP_RQT_REG_DE',
    'INSP_RQT_REGR_NM',
    'PFMINPC_DE',
    'PFMINPC_1_ITM',
    'PFMINPC_2_ITM',
    'PFMINPC_3_ITM',
    'PFMINPC_4_ITM',
    'PFMINPC_5_ITM',
    'PFMINPC_ETC_ITM',
    'PFMINPC_ITM_ETC_CMPNT_NM',
    'PFMINPC_FILE_ATT_YN',
    'PFMINPC_ELPDSRC_YN',
    'PFMINPC_ELPDSRC_IMPSBL_RESN',
    'PFMINPC_REG_DE',
    'PFMINPC_REGR_NM',
    'PFMINPC_PAPE_OUTT_DE',
    'TRTMNT_DE',
    'NCAR_PUCH_PLAN_DE',
    'NCAR_PUCH_PLAN_VHCL_NM',
    'SCRCAR_ENTRPS_NM',
    'SCRCAR_ENTRPS_ZIP',
    'SCRCAR_ENTRPS_1_ADRS',
    'SCRCAR_ENTRPS_2_ADRS',
    'ELPDSRC_ATT_FILE_1_YN',
    'ELPDSRC_ATT_FILE_2_YN',
    'ELPDSRC_ATT_FILE_3_YN',
    'ELPDSRC_REG_DE',
    'ELPDSRC_REGR_NM',
    'ELPDSRC_LST_UNAP_RESN',
    'SBSIDY_PYMT_DE',
    'SBSIDY_BIZ_YR',
    'ELPDSRC_LST_CNFRM_DE',
    'ELPDSRC_LST_APRR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'LWBCT_YN',
    'NOW_VHRNO',
    'ELPDSRC_ATT_FILE_4_YN',
    'BANK_NM',
    'BANK_ACC_NO',
    'PRCINSP_SE',
    'RCPT_LOCGOV_CD',
    'RPRSTV_NM',
    'BIZCND',
    'TYPBIZ',
    'EMAIL',
    'RCPT_SE',
    'INSP_SE',
    'ELPDSRC_TRGT_AT_ETC_RESN',
    'HST_MNGT_NO',
    'CTNT',
    'VHCTY_SE',
    'ELPDSRC_GRP',
    'BTHDY',
    'JURIRNO',
    'STDR_YM',
    'STDR_AMT',
    'WHL_EXCS_CNFRM_DE',
    'WHL_EXCS_APRR_NM',
    'MNFCT_DE',
    'OLD_SIDO',
    'OLD_SIGNGU',
    'OLD_RCPT_LOCGOV_CD',
    'OLD_1_ADRS',
    'OLD_2_ADRS',
    'OLD_VHCL_PURPS',
    'BAI_ID',
    'ADITOR_NM',
    'REG_NO',
    'RQEST_ARVL_DE',
    'RQEST_ARVL_YN',
    'BIL_CNFRMR_NM',
    'ADD_AMT',
    'SAMNS_CNFRM',
    'ADD_RQEST_ARVL_YN',
    'ADD_RQEST_ARVL_DE',
    'ADD_RQEST_CNFRMR_NM',
    'ATT_PAPE_CNFRM_AT',
    'BEF_STUS_CD',
    'WAREHOUSING_DE',
    'WAREHOUSING_YN',
    'MNTNG_IMPR_AMT',
    'ELPDSRC_ATT_FILE_5_YN',
    'SMAL_BUSIN_YN',
    'INPT_MTHD_FLAG',
    'ELPDSRC_ATT_FILE_7_YN',
    'AID_RJCT_DE',
    'IMG_LGCLFL1',
    'IMG_PHYSCL1',
    'IMG_LGCLFL2',
    'IMG_PHYSCL2',
    'IMG_LGCLFL3',
    'IMG_PHYSCL3',
    'IMG_LGCLFL4',
    'IMG_PHYSCL4',
    'PRE_SCRAP_CAR_YN',
    'ELCTY_HYDRO_CAR_ADD_AMT',
    'PFMINPC_ITSL_APPRNC',
    'PFMINPC_BUFFER_DVICE',
    'PFMINPC_WINDOW',
    'PFMINPC_TIRE',
    'PFMINPC_ASSMI_DEVICE',
    'PFMINPC_ELPDSRC_GNRLZ_RESN', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    [
    '접수시도',
    '저감장치구분',
    '저감장치 부착불가 여부',
    '조기폐차최종승인YN',
    '말소일자',
    '폐차등록주행거리',
    '차량등록번호',
    '차대번호',
    '조기폐차상태코드',

    'ELPDSRC_MNGT_NO',
    'INST_ID_CD',
    'OWNR_NM',
    'USER_BIZRNO',
    'USER_TELNO',
    'FXNUM',
    'USER_ZIP',
    'USER_1_ADRS',
    'USER_2_ADRS',
    'RCPT_SIGNGU',
    'VHCL_YRIDNW',
    'EGINCTY',
    'VHCL_PSCP',
    'VHCL_WGHT',
    'TOT_WGHT',
    'CRYNG_WGHT',
    'VHCNM',
    'VHCL_FRM',
    'VHCTY',
    'VHCL_PURPS',
    'FST_REG_DE',
    'SCRCAR_ERA_DRVNG_DSTNC',
    'VHCL_FUEL',
    'PRCINSP_DE',
    'INSPOF_NM',
    'PRCINSP_JDGMNT_YN',
    'PRCINSP_RSLT_VAL',
    'PRCINSP_JDGMNT_STDR_VAL',
    'RCPT_DE',
    'INPT_DE',
    'RETR_NM',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_TRGT_1_AT',
    'ELPDSRC_TRGT_2_AT',
    'ELPDSRC_TRGT_3_AT',
    'ELPDSRC_TRGT_4_AT',
    'ELPDSRC_TRGT_5_AT',
    'ELPDSRC_TRGT_6_AT',
    'ELPDSRC_TRGT_7_AT',
    'ELPDSRC_TRGT_CNFRM_REG_DE',
    'ELPDSRC_TRGT_CNFRM_REGR_NM',
    'PYMT_CNFRM_YN',
    'EXPC_SPRT_AMT',
    'DCIS_SPRT_AMT',
    'SBSIDY_UNPAY_RESN',
    'SBSIDY_RQEST_DE',
    'SBSIDY_RQEST_REGR_NM',
    'DOC_CNFRM_NO',
    'DOC_OUTT_DE',
    'INSP_RQT_SIWA_MTHD',
    'INSP_RQT_DE',
    'INSP_RQT_TM',
    'VRSC_ENTRPS_NM',
    'AGENT_ZIP',
    'AGENT_1_ADRS',
    'AGENT_2_ADRS',
    'AGENT_TELNO',
    'AGENT_CRTC_NO',
    'INSP_RQT_REG_DE',
    'INSP_RQT_REGR_NM',
    'PFMINPC_DE',
    'PFMINPC_1_ITM',
    'PFMINPC_2_ITM',
    'PFMINPC_3_ITM',
    'PFMINPC_4_ITM',
    'PFMINPC_5_ITM',
    'PFMINPC_ETC_ITM',
    'PFMINPC_ITM_ETC_CMPNT_NM',
    'PFMINPC_FILE_ATT_YN',
    'PFMINPC_ELPDSRC_YN',
    'PFMINPC_ELPDSRC_IMPSBL_RESN',
    'PFMINPC_REG_DE',
    'PFMINPC_REGR_NM',
    'PFMINPC_PAPE_OUTT_DE',
    'TRTMNT_DE',
    'NCAR_PUCH_PLAN_DE',
    'NCAR_PUCH_PLAN_VHCL_NM',
    'SCRCAR_ENTRPS_NM',
    'SCRCAR_ENTRPS_ZIP',
    'SCRCAR_ENTRPS_1_ADRS',
    'SCRCAR_ENTRPS_2_ADRS',
    'ELPDSRC_ATT_FILE_1_YN',
    'ELPDSRC_ATT_FILE_2_YN',
    'ELPDSRC_ATT_FILE_3_YN',
    'ELPDSRC_REG_DE',
    'ELPDSRC_REGR_NM',
    'ELPDSRC_LST_UNAP_RESN',
    'SBSIDY_PYMT_DE',
    'SBSIDY_BIZ_YR',
    'ELPDSRC_LST_CNFRM_DE',
    'ELPDSRC_LST_APRR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'LWBCT_YN',
    'NOW_VHRNO',
    'ELPDSRC_ATT_FILE_4_YN',
    'BANK_NM',
    'BANK_ACC_NO',
    'PRCINSP_SE',
    'RCPT_LOCGOV_CD',
    'RPRSTV_NM',
    'BIZCND',
    'TYPBIZ',
    'EMAIL',
    'RCPT_SE',
    'INSP_SE',
    'ELPDSRC_TRGT_AT_ETC_RESN',
    'HST_MNGT_NO',
    'CTNT',
    'VHCTY_SE',
    'ELPDSRC_GRP',
    'BTHDY',
    'JURIRNO',
    'STDR_YM',
    'STDR_AMT',
    'WHL_EXCS_CNFRM_DE',
    'WHL_EXCS_APRR_NM',
    'MNFCT_DE',
    'OLD_SIDO',
    'OLD_SIGNGU',
    'OLD_RCPT_LOCGOV_CD',
    'OLD_1_ADRS',
    'OLD_2_ADRS',
    'OLD_VHCL_PURPS',
    'BAI_ID',
    'ADITOR_NM',
    'REG_NO',
    'RQEST_ARVL_DE',
    'RQEST_ARVL_YN',
    'BIL_CNFRMR_NM',
    'ADD_AMT',
    'SAMNS_CNFRM',
    'ADD_RQEST_ARVL_YN',
    'ADD_RQEST_ARVL_DE',
    'ADD_RQEST_CNFRMR_NM',
    'ATT_PAPE_CNFRM_AT',
    'BEF_STUS_CD',
    'WAREHOUSING_DE',
    'WAREHOUSING_YN',
    'MNTNG_IMPR_AMT',
    'ELPDSRC_ATT_FILE_5_YN',
    'SMAL_BUSIN_YN',
    'INPT_MTHD_FLAG',
    'ELPDSRC_ATT_FILE_7_YN',
    'AID_RJCT_DE',
    'IMG_LGCLFL1',
    'IMG_PHYSCL1',
    'IMG_LGCLFL2',
    'IMG_PHYSCL2',
    'IMG_LGCLFL3',
    'IMG_PHYSCL3',
    'IMG_LGCLFL4',
    'IMG_PHYSCL4',
    'PRE_SCRAP_CAR_YN',
    'ELCTY_HYDRO_CAR_ADD_AMT',
    'PFMINPC_ITSL_APPRNC',
    'PFMINPC_BUFFER_DVICE',
    'PFMINPC_WINDOW',
    'PFMINPC_TIRE',
    'PFMINPC_ASSMI_DEVICE',
    'PFMINPC_ELPDSRC_GNRLZ_RESN',
    ]
    }

ocol = pd.DataFrame(odict)
ocol

                             컬럼                          내용
0                     RCPT_SIDO                        접수시도
1                     RDCDVC_SE                      저감장치구분
2                 MNTNG_IMPR_YN                저감장치 부착불가 여부
3          ELPDSRC_LST_CNFRM_YN                  조기폐차최종승인YN
4                       ERSR_DE                        말소일자
..                          ...                         ...
165        PFMINPC_BUFFER_DVICE        PFMINPC_BUFFER_DVICE
166              PFMINPC_WINDOW              PFMINPC_WINDOW
167                PFMINPC_TIRE                PFMINPC_TIRE
168        PFMINPC_ASSMI_DEVICE        PFMINPC_ASSMI_DEVICE
169  PFMINPC_ELPDSRC_GNRLZ_RESN  PFMINPC_ELPDSRC_GNRLZ_RESN

[170 rows x 2 columns]

In [16]:
sdf.columns.to_list()

['RDCDVC_EXTRNS_YN',
 'LEM_KND_CD',
 'STDG_CTPV_NM',
 'ELPDSRC_STTS_CD',
 'ELPDSRC_LST_APRV_YN',
 'ERSR_YMD',
 'VIN',
 'VHRNO',
 'SCCAR_REG_DRVNG_DSNC',
 'STDG_SGG_NM',
 'SCRCAR_ENTRPS_NM',
 'ELPDSRC_LAST_APRV_YMD',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_MNG_NO']

In [17]:
slist = [
    'STDG_CTPV_NM',
    'LEM_KND_CD',
    'RDCDVC_EXTRNS_YN',
    'ELPDSRC_LST_APRV_YN',
    'ERSR_YMD',
    'SCCAR_REG_DRVNG_DSNC',
    'VHRNO',
    'VIN',
    'ELPDSRC_STTS_CD',

    'STDG_SGG_NM',
    'SCRCAR_ENTRPS_NM',
    'ELPDSRC_LAST_APRV_YMD',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_MNG_NO',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    [
    '법정동시도명',
    '저공해조치종류코드',
    '저감장치부착여부',
    '조기폐차최종승인여부',
    '말소일자',
    '폐차등록주행거리',
    '자동차등록번호',
    '차대번호',
    '조기폐차상태코드',

    'STDG_SGG_NM',
    'SCRCAR_ENTRPS_NM',
    'ELPDSRC_LAST_APRV_YMD',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_MNG_NO',
    ]
    }

scol = pd.DataFrame(sdict)
scol

                       컬럼                     내용
0            STDG_CTPV_NM                 법정동시도명
1              LEM_KND_CD              저공해조치종류코드
2        RDCDVC_EXTRNS_YN               저감장치부착여부
3     ELPDSRC_LST_APRV_YN             조기폐차최종승인여부
4                ERSR_YMD                   말소일자
5    SCCAR_REG_DRVNG_DSNC               폐차등록주행거리
6                   VHRNO                자동차등록번호
7                     VIN                   차대번호
8         ELPDSRC_STTS_CD               조기폐차상태코드
9             STDG_SGG_NM            STDG_SGG_NM
10       SCRCAR_ENTRPS_NM       SCRCAR_ENTRPS_NM
11  ELPDSRC_LAST_APRV_YMD  ELPDSRC_LAST_APRV_YMD
12         SBSIDY_TRGT_YN         SBSIDY_TRGT_YN
13         ELPDSRC_MNG_NO         ELPDSRC_MNG_NO

### 데이터 info

In [18]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,RCPT_SIDO,접수시도,291353,STDG_CTPV_NM,법정동시도명,291353.00,0.00,0,0.00
1,RDCDVC_SE,저감장치구분,291353,LEM_KND_CD,저공해조치종류코드,291353.00,0.00,0,0.00
2,MNTNG_IMPR_YN,저감장치 부착불가 여부,291353,RDCDVC_EXTRNS_YN,저감장치부착여부,291353.00,0.00,0,0.00
3,ELPDSRC_LST_CNFRM_YN,조기폐차최종승인YN,128589,ELPDSRC_LST_APRV_YN,조기폐차최종승인여부,128589.00,0.00,162764,162764.00
4,ERSR_DE,말소일자,134151,ERSR_YMD,말소일자,134151.00,0.00,157202,157202.00

### [출력] 컬럼명, 결측치 통계

In [19]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

[정제]DLM_TB_ERP_EARLY_ERASE_LGV.xlsx 출력완료.

### [분석]

#### 차대번호

In [123]:
len(odf2['VIN'].unique()), len(sdf2['VIN'].unique())

(273773, 273773)

In [124]:
len(set(odf2['VIN'].unique()) - set(sdf2['VIN'].unique()))

0

#### 자동차등록번호

In [85]:
odf2['VHRNO'].unique()

array(['60다6989', '50모3406', '35마2904', ..., '서울55로5608', '05버4210',
       '64주8535'], dtype=object)

In [86]:
sdf2['VHRNO'].unique()

array(['70저4653', '52어8161', '67어5081', ..., '40서5406', '87저7702',
       '50보6931'], dtype=object)

## 12\. 사후관리 무상점검 정보(DLM_TB_ERP_FREE_INSPEC)

In [125]:
name = 'DLM_TB_ERP_FREE_INSPEC'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

41 8
(629, 41) (629, 8)

In [126]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수  행_수
ODS    41  629
STD     8  629

### 컬럼 확인

In [127]:
odf.columns.to_list()

['CHK_MNGT_NO',
 'REDUC_REG_NO',
 'VHRNO',
 'VIN',
 'MKR_CD',
 'RCPT_LOCGOV_CD',
 'PRGRE_STUS',
 'USER_ZIP',
 'USER_1_ADRS',
 'USER_2_ADRS',
 'USER_TELNO',
 'CHK_DE',
 'CHK_CST',
 'CHK_ENTRPS_NM',
 'BF_DRVNG_DSTNC',
 'AFTR_DRVNG_DSTNC',
 'INST_ID',
 'INPT_DE',
 'RETR_NM',
 'SBSIDY_TRGT_YN',
 'SBSIDY_TRGT_EXCLU_RESN',
 'LOCGOV_CNFRM_DE',
 'LOCGOV_CNFRMR_NM',
 'LOCGOV_INPT_DE',
 'CLNING_RQEST_GRP_NO',
 'SBSIDY_RQT_DE',
 'SBSIDY_APLICT_NM',
 'SBSIDY_RQT_INPT_DE',
 'SBSIDY_PYMT_DE',
 'SBSIDY_BIZ_YR',
 'SBSIDY_PYMT_YN',
 'SBSIDY_PYMT_DCSN_DE',
 'SBSIDY_PYMT_IDNTFR_NM',
 'SBSIDY_PYMT_REG_DE',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'FUEL_SMO',
 'COST_YEAR',
 'COST_DATE',
 'COST_TYPE',
 'COST_NOTE']

In [128]:
olist = [
    'VHRNO',
    'VIN',
    'SBSIDY_TRGT_YN',
    'CHK_ENTRPS_NM',
    'CHK_DE',
    'AFTR_DRVNG_DSTNC',
    'PRGRE_STUS',
    'REDUC_REG_NO',

    'CHK_MNGT_NO',
    'MKR_CD',
    'RCPT_LOCGOV_CD',
    'USER_ZIP',
    'USER_1_ADRS',
    'USER_2_ADRS',
    'USER_TELNO',
    'CHK_CST',
    'BF_DRVNG_DSTNC',
    'INST_ID',
    'INPT_DE',
    'RETR_NM',
    'SBSIDY_TRGT_EXCLU_RESN',
    'LOCGOV_CNFRM_DE',
    'LOCGOV_CNFRMR_NM',
    'LOCGOV_INPT_DE',
    'CLNING_RQEST_GRP_NO',
    'SBSIDY_RQT_DE',
    'SBSIDY_APLICT_NM',
    'SBSIDY_RQT_INPT_DE',
    'SBSIDY_PYMT_DE',
    'SBSIDY_BIZ_YR',
    'SBSIDY_PYMT_YN',
    'SBSIDY_PYMT_DCSN_DE',
    'SBSIDY_PYMT_IDNTFR_NM',
    'SBSIDY_PYMT_REG_DE',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'FUEL_SMO',
    'COST_YEAR',
    'COST_DATE',
    'COST_TYPE',
    'COST_NOTE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차량등록번호',
    '차대번호',
    '보조금대상YN',
    '점검업체명',
    '점검일자',
    '이후주행거리',
    '무상점검진행상태',
    '저감등록번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼        내용
0                    VHRNO    차량등록번호
1                      VIN      차대번호
2           SBSIDY_TRGT_YN   보조금대상YN
3            CHK_ENTRPS_NM     점검업체명
4                   CHK_DE      점검일자
5         AFTR_DRVNG_DSTNC    이후주행거리
6               PRGRE_STUS  무상점검진행상태
7             REDUC_REG_NO    저감등록번호
8              CHK_MNGT_NO        미정
9                   MKR_CD        미정
10          RCPT_LOCGOV_CD        미정
11                USER_ZIP        미정
12             USER_1_ADRS        미정
13             USER_2_ADRS        미정
14              USER_TELNO        미정
15                 CHK_CST        미정
16          BF_DRVNG_DSTNC        미정
17                 INST_ID        미정
18                 INPT_DE        미정
19                 RETR_NM        미정
20  SBSIDY_TRGT_EXCLU_RESN        미정
21         LOCGOV_CNFRM_DE        미정
22        LOCGOV_CNFRMR_NM        미정
23          LOCGOV_INPT_DE        미정
24     CLNING_RQEST_GRP_NO        미정
25           SBSIDY_RQT_DE        미정
26        SBSIDY_APLICT_NM        미정
27      SBSIDY_RQT_INPT_DE        미정
28          SBSIDY_PYMT_DE        미정
29           SBSIDY_BIZ_YR        미정
30          SBSIDY_PYMT_YN        미정
31     SBSIDY_PYMT_DCSN_DE        미정
32   SBSIDY_PYMT_IDNTFR_NM        미정
33      SBSIDY_PYMT_REG_DE        미정
34             LST_CHNG_DE        미정
35             LST_EDIR_NM        미정
36                FUEL_SMO        미정
37               COST_YEAR        미정
38               COST_DATE        미정
39               COST_TYPE        미정
40               COST_NOTE        미정

In [129]:
sdf.columns.to_list()

['AFTR_DRVNG_DSTNC',
 'CHCK_YMD',
 'GRTUI_CHCK_PRGRS_STS',
 'REDUC_REG_NO',
 'VHRNO',
 'VIN',
 'CHCK_ENTRPS_NM',
 'SBSIDY_TRGT_YN']

In [130]:
slist = [
    'VHRNO',
    'VIN',
    'SBSIDY_TRGT_YN',
    'CHCK_ENTRPS_NM',
    'CHCK_YMD',
    'AFTR_DRVNG_DSTNC',
    'GRTUI_CHCK_PRGRS_STS',
    'REDUC_REG_NO',

    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차량등록번호',
    '차대번호',
    '보조금대상여부',
    '점검업체명',
    '점검일자',
    '이후주행거리',
    '무상점검진행상태',
    '저감등록번호',]
    }

scol = pd.DataFrame(sdict)
scol

                     컬럼        내용
0                 VHRNO    차량등록번호
1                   VIN      차대번호
2        SBSIDY_TRGT_YN   보조금대상여부
3        CHCK_ENTRPS_NM     점검업체명
4              CHCK_YMD      점검일자
5      AFTR_DRVNG_DSTNC    이후주행거리
6  GRTUI_CHCK_PRGRS_STS  무상점검진행상태
7          REDUC_REG_NO    저감등록번호

### 데이터 info

In [131]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,VHRNO,차량등록번호,629,VHRNO,차량등록번호,629.0,0.0,0,0.0
1,VIN,차대번호,628,VIN,차대번호,628.0,0.0,1,1.0
2,SBSIDY_TRGT_YN,보조금대상YN,628,SBSIDY_TRGT_YN,보조금대상여부,628.0,0.0,1,1.0
3,CHK_ENTRPS_NM,점검업체명,629,CHCK_ENTRPS_NM,점검업체명,629.0,0.0,0,0.0
4,CHK_DE,점검일자,629,CHCK_YMD,점검일자,629.0,0.0,0,0.0

### [출력] 컬럼명, 결측치 통계

In [240]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### [분석]

#### 차대번호

In [132]:
len(odf2['VIN'].unique()), len(sdf2['VIN'].unique())

(629, 629)

In [133]:
len(set(odf2['VIN'].unique()) - set(sdf2['VIN'].unique()))

0

#### 자동차등록번호

In [136]:
len(odf2['VHRNO'].unique())

628

In [137]:
len(sdf2['VHRNO'].unique())

628

## 13\. 저감장치 인증등록번호(DLM_TB_ERP_RED_TYPE)

In [138]:
name = 'DLM_TB_ERP_RED_TYPE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

32 13
(1961, 32) (1961, 13)

In [139]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    32  1961
STD    13  1961

### 컬럼 확인

In [140]:
odf.columns.to_list()

['SEQ_NO',
 'MKR_CD',
 'CRTC_MODL_NO',
 'RDCDVC_SE',
 'RDCDVC_KND',
 'REDUC_VHCTY_SE',
 'SBSIDY_AMT',
 'SBSIDY_SLFBDN_AMT',
 'SBSIDY_BIZ_YR',
 'TDMS_SBSIDY_AMT',
 'LWBCT_SBSIDY_AMT',
 'LWBCT_TDMS_SBSIDY_AMT',
 'CRTC_MODL_KND',
 'PFMCRTC_RSLT_INPT_DE',
 'PFMCRTC_RSLT_RETR_NM',
 'PFMCRTC_VENTL_TMPR_VAL',
 'PFMCRTC_VENTL_TMPR_1_STDR',
 'PFMCRTC_VENTL_TMPR_2_STDR',
 'PFMCRTC_VENTL_PSSR_VAL',
 'PFMCRTC_VENTL_PSSR_1_STDR',
 'PFMCRTC_VENTL_PSSR_2_STDR',
 'RDCDVC_EGIN_NM',
 'PM_REDUC_EFCNY',
 'REG_DE',
 'REGR_NM',
 'LST_CHNG_DT',
 'LST_EDIR_NM',
 'PM_LST_REDUC_EFCNY',
 'JEWEL_VAL',
 'SCRAP_VAL',
 'EX_VAL',
 'LST_CHNG_DE']

In [141]:
olist = [
    'REDUC_VHCTY_SE',
    'SEQ_NO',
    'RDCDVC_EGIN_NM',
    'PM_LST_REDUC_EFCNY',
    'PFMCRTC_VENTL_TMPR_VAL',
    'CRTC_MODL_KND',
    'PFMCRTC_VENTL_TMPR_1_STDR',
    'PFMCRTC_VENTL_PSSR_VAL',
    'PFMCRTC_VENTL_PSSR_2_STDR',
    'CRTC_MODL_NO',
    'PFMCRTC_VENTL_PSSR_1_STDR',
    'PFMCRTC_VENTL_TMPR_2_STDR',

    'MKR_CD',
    'RDCDVC_SE',
    'RDCDVC_KND',
    'SBSIDY_AMT',
    'SBSIDY_SLFBDN_AMT',
    'SBSIDY_BIZ_YR',
    'TDMS_SBSIDY_AMT',
    'LWBCT_SBSIDY_AMT',
    'LWBCT_TDMS_SBSIDY_AMT',
    'PFMCRTC_RSLT_INPT_DE',
    'PFMCRTC_RSLT_RETR_NM',
    'PM_REDUC_EFCNY',
    'REG_DE',
    'REGR_NM',
    'LST_CHNG_DT',
    'LST_EDIR_NM',
    'JEWEL_VAL',
    'SCRAP_VAL',
    'EX_VAL',
    'LST_CHNG_DE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['저감차종구분',
    '일련번호',
    '저감장치엔진명',
    'PM최종저감효율',
    '성능인증배기온도값',
    '인증모델종류',
    '성능인증배기온도1기준',
    '성능인증배기압력값',
    '성능인증배기압력2기준',
    '인증모델번호',
    '성능인증배기압력1기준',
    '성능인증배기온도2기준',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                           컬럼           내용
0              REDUC_VHCTY_SE       저감차종구분
1                      SEQ_NO         일련번호
2              RDCDVC_EGIN_NM      저감장치엔진명
3          PM_LST_REDUC_EFCNY     PM최종저감효율
4      PFMCRTC_VENTL_TMPR_VAL    성능인증배기온도값
5               CRTC_MODL_KND       인증모델종류
6   PFMCRTC_VENTL_TMPR_1_STDR  성능인증배기온도1기준
7      PFMCRTC_VENTL_PSSR_VAL    성능인증배기압력값
8   PFMCRTC_VENTL_PSSR_2_STDR  성능인증배기압력2기준
9                CRTC_MODL_NO       인증모델번호
10  PFMCRTC_VENTL_PSSR_1_STDR  성능인증배기압력1기준
11  PFMCRTC_VENTL_TMPR_2_STDR  성능인증배기온도2기준
12                     MKR_CD           미정
13                  RDCDVC_SE           미정
14                 RDCDVC_KND           미정
15                 SBSIDY_AMT           미정
16          SBSIDY_SLFBDN_AMT           미정
17              SBSIDY_BIZ_YR           미정
18            TDMS_SBSIDY_AMT           미정
19           LWBCT_SBSIDY_AMT           미정
20      LWBCT_TDMS_SBSIDY_AMT           미정
21       PFMCRTC_RSLT_INPT_DE           미정
22       PFMCRTC_RSLT_RETR_NM           미정
23             PM_REDUC_EFCNY           미정
24                     REG_DE           미정
25                    REGR_NM           미정
26                LST_CHNG_DT           미정
27                LST_EDIR_NM           미정
28                  JEWEL_VAL           미정
29                  SCRAP_VAL           미정
30                     EX_VAL           미정
31                LST_CHNG_DE           미정

In [142]:
sdf.columns.to_list()

['CERT_MODL_KND',
 'CERT_MODL_NO',
 'PFMCRTC_VENTL_PSSR1_CRTR',
 'PFMCRTC_VENTL_PSSR2_CRTR',
 'PFMCRTC_VENTL_PSSR_VAL',
 'PFMCRTC_VENTL_TMPRT1_CRTR',
 'PFMCRTC_VENTL_TMPRT2_CRTR',
 'PFMCRTC_VENTL_TMPRT_VAL',
 'PM_LAST_REDUC_EFCNY',
 'RDCDVC_EGIN_NM',
 'REDUC_VHCTY_SE_CD',
 'SN',
 'MNFCTR_CD']

In [143]:
slist = [
    'REDUC_VHCTY_SE_CD',
    'SN',
    'RDCDVC_EGIN_NM',
    'PM_LAST_REDUC_EFCNY',
    'PFMCRTC_VENTL_TMPRT_VAL',
    'CERT_MODL_KND',
    'PFMCRTC_VENTL_TMPRT1_CRTR',
    'PFMCRTC_VENTL_PSSR_VAL',
    'PFMCRTC_VENTL_PSSR2_CRTR',
    'CERT_MODL_NO',
    'PFMCRTC_VENTL_PSSR1_CRTR',
    'PFMCRTC_VENTL_TMPRT2_CRTR',

    'MNFCTR_CD', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['저감차종구분코드',
    '일련번호',
    '저감장치엔진명',
    'PM최종저감효율',
    '성능인증배기온도값',
    '인증모델종류',
    '성능인증배기온도1기준',
    '성능인증배기압력값',
    '성능인증배기압력2기준',
    '인증모델번호',
    '성능인증배기압력1기준',
    '성능인증배기온도2기준',

    '미정', ]
    }

scol = pd.DataFrame(sdict)
scol

                           컬럼           내용
0           REDUC_VHCTY_SE_CD     저감차종구분코드
1                          SN         일련번호
2              RDCDVC_EGIN_NM      저감장치엔진명
3         PM_LAST_REDUC_EFCNY     PM최종저감효율
4     PFMCRTC_VENTL_TMPRT_VAL    성능인증배기온도값
5               CERT_MODL_KND       인증모델종류
6   PFMCRTC_VENTL_TMPRT1_CRTR  성능인증배기온도1기준
7      PFMCRTC_VENTL_PSSR_VAL    성능인증배기압력값
8    PFMCRTC_VENTL_PSSR2_CRTR  성능인증배기압력2기준
9                CERT_MODL_NO       인증모델번호
10   PFMCRTC_VENTL_PSSR1_CRTR  성능인증배기압력1기준
11  PFMCRTC_VENTL_TMPRT2_CRTR  성능인증배기온도2기준
12                  MNFCTR_CD           미정

### 데이터 info

In [144]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,REDUC_VHCTY_SE,저감차종구분,1589,REDUC_VHCTY_SE_CD,저감차종구분코드,1589.0,0.0,372,372.0
1,SEQ_NO,일련번호,1961,SN,일련번호,1961.0,0.0,0,0.0
2,RDCDVC_EGIN_NM,저감장치엔진명,1816,RDCDVC_EGIN_NM,저감장치엔진명,1816.0,0.0,145,145.0
3,PM_LST_REDUC_EFCNY,PM최종저감효율,1199,PM_LAST_REDUC_EFCNY,PM최종저감효율,1199.0,0.0,762,762.0
4,PFMCRTC_VENTL_TMPR_VAL,성능인증배기온도값,752,PFMCRTC_VENTL_TMPRT_VAL,성능인증배기온도값,752.0,0.0,1209,1209.0

### [출력] 컬럼명, 결측치 통계

In [248]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

## 14\. 저감사업 성능유지 확인검사(DLM_TB_PFM_FILE)

In [145]:
name = 'DLM_TB_PFM_FILE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

65 14
(418131, 65) (418131, 14)

In [146]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS    65  418131
STD    14  418131

### 컬럼 확인

In [147]:
odf.columns.to_list()

['REDUC_REG_NO',
 'PFMCFINPC_NO',
 'VHRNO',
 'VIN',
 'PFMCFINPC_DE',
 'STRCHG_DE',
 'RCPT_LOCGOV_CD',
 'INSPOF_CD',
 'FILE_NM',
 'NTJDMT_RESN',
 'DRVNG_TMPR_DISTRB_JDGMNT',
 'PFMCFINPC_SMO_DNSTY',
 'PFMCFINPC_EGINPWR',
 'INSP_KND',
 'INSP_SCAL_SE',
 'INSP_CST',
 'CNFRMR_NM',
 'PFMCFINPC_GNRLZ_JDGMNT',
 'SMO_CND_JDGMNT',
 'CRTC_MODL_NO',
 'MKR_CD',
 'CRTC_CND_INSP_REG_YN',
 'CRTC_CND_INSP_REGR_NM',
 'CRTC_CND_INSP_REG_DE',
 'RETR_NM',
 'INPT_DE',
 'LST_CHNG_DT',
 'LST_EDIR_NM',
 'RDCDVC_SE',
 'RDCDVC_KND',
 'VHCNM',
 'VHCL_YRIDNW',
 'EGINTY',
 'FST_REG_DE',
 'CRTC_TMPR_STDR',
 'CRTC_TMPR_PROVS_ACML_DISTRB',
 'STDR_ACML_DISTRB_PROVS_TMPR',
 'CRTC_PSSR_STDR',
 'CRTC_PSSR_PROVS_ACML_DISTRB',
 'STDR_ACML_DISTRB_PROVS_PSSR',
 'INSPOF_NM',
 'FILE_BAK_YN',
 'RINSP_CNT',
 'IMPPRTY_RESN',
 'EXCS_RT',
 'OWNR_NM',
 'OWNR_1_ADRS',
 'OWNR_2_ADRS',
 'OWNR_TELNO',
 'OWNR_BTHDY',
 'INSPOF_RPRSTV_NM',
 'FILE_EXTPR_NM',
 'PFMINPC_CST_PYMT_CNFRM_DE',
 'PFMINPC_CST_PYMT_APRR_NM',
 'PFMINPC_CST_CNFRM_YN',
 'PFMINPC_CST_PYMT_DE',
 'PFMINPC_CST_PYMT_BIZ_YR',
 'INSP_TM_INFO',
 'CTNT',
 'INSP_IMPPRTY_TRTMNT_REG_DE',
 'INSP_IMPPRTY_TRTMNT_YN',
 'DVICE_AS_TRTMNT_DE',
 'DVICE_AS_TRTMNT_DTL',
 'INSP_IMPPRTY_RESN',
 'PFMCFINPC_DE_CHNG_RESN']

In [148]:
olist = [
    'SMO_CND_JDGMNT',
    'PFMCFINPC_GNRLZ_JDGMNT',
    'REDUC_REG_NO',
    'PFMCFINPC_SMO_DNSTY',
    'INSP_KND',
    'VIN',
    'PFMCFINPC_DE',
    'PFMCFINPC_NO',
    'INSPOF_NM',
    'VHRNO',

    'STRCHG_DE',
    'RCPT_LOCGOV_CD',
    'INSPOF_CD',
    'FILE_NM',
    'NTJDMT_RESN',
    'DRVNG_TMPR_DISTRB_JDGMNT',
    'PFMCFINPC_EGINPWR',
    'INSP_SCAL_SE',
    'INSP_CST',
    'CNFRMR_NM',
    'CRTC_MODL_NO',
    'MKR_CD',
    'CRTC_CND_INSP_REG_YN',
    'CRTC_CND_INSP_REGR_NM',
    'CRTC_CND_INSP_REG_DE',
    'RETR_NM',
    'INPT_DE',
    'LST_CHNG_DT',
    'LST_EDIR_NM',
    'RDCDVC_SE',
    'RDCDVC_KND',
    'VHCNM',
    'VHCL_YRIDNW',
    'EGINTY',
    'FST_REG_DE',
    'CRTC_TMPR_STDR',
    'CRTC_TMPR_PROVS_ACML_DISTRB',
    'STDR_ACML_DISTRB_PROVS_TMPR',
    'CRTC_PSSR_STDR',
    'CRTC_PSSR_PROVS_ACML_DISTRB',
    'STDR_ACML_DISTRB_PROVS_PSSR',
    'FILE_BAK_YN',
    'RINSP_CNT',
    'IMPPRTY_RESN',
    'EXCS_RT',
    'OWNR_NM',
    'OWNR_1_ADRS',
    'OWNR_2_ADRS',
    'OWNR_TELNO',
    'OWNR_BTHDY',
    'INSPOF_RPRSTV_NM',
    'FILE_EXTPR_NM',
    'PFMINPC_CST_PYMT_CNFRM_DE',
    'PFMINPC_CST_PYMT_APRR_NM',
    'PFMINPC_CST_CNFRM_YN',
    'PFMINPC_CST_PYMT_DE',
    'PFMINPC_CST_PYMT_BIZ_YR',
    'INSP_TM_INFO',
    'CTNT',
    'INSP_IMPPRTY_TRTMNT_REG_DE',
    'INSP_IMPPRTY_TRTMNT_YN',
    'DVICE_AS_TRTMNT_DE',
    'DVICE_AS_TRTMNT_DTL',
    'INSP_IMPPRTY_RESN',
    'PFMCFINPC_DE_CHNG_RESN', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['매연조건판정',
    '성능확인검사종합판정',
    '저감등록번호',
    '성능확인검사매연농도',
    '검사종류',
    '차대번호',
    '성능확인검사일자',
    '성능확인검사번호',
    '검사소명',
    '차량등록번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼          내용
0           SMO_CND_JDGMNT      매연조건판정
1   PFMCFINPC_GNRLZ_JDGMNT  성능확인검사종합판정
2             REDUC_REG_NO      저감등록번호
3      PFMCFINPC_SMO_DNSTY  성능확인검사매연농도
4                 INSP_KND        검사종류
..                     ...         ...
60  INSP_IMPPRTY_TRTMNT_YN          미정
61      DVICE_AS_TRTMNT_DE          미정
62     DVICE_AS_TRTMNT_DTL          미정
63       INSP_IMPPRTY_RESN          미정
64  PFMCFINPC_DE_CHNG_RESN          미정

[65 rows x 2 columns]

In [149]:
sdf.columns.to_list()

['INSPOF_NM',
 'INSP_KND_CD',
 'PFMCFINPC_YMD',
 'PFMCFINPC_GNRLZ_JGMT',
 'PFMCFINPC_NO',
 'PFMCFINPC_SMO_CNTRVL',
 'RDCDVC_REG_NO',
 'SMO_CND_JGMT_CD',
 'VHRNO',
 'VIN',
 'MAXM_OTPT_MSRMT_VAL',
 'STRCT_CHG_YMD',
 'RDCDVC_SE_CD',
 'RDCDVC_KND']

In [150]:
slist = [
    'SMO_CND_JGMT_CD',
    'PFMCFINPC_GNRLZ_JGMT',
    'RDCDVC_REG_NO',
    'PFMCFINPC_SMO_CNTRVL',
    'INSP_KND_CD',
    'VIN',
    'PFMCFINPC_YMD',
    'PFMCFINPC_NO',
    'INSPOF_NM',
    'VHRNO',

    'MAXM_OTPT_MSRMT_VAL',
    'STRCT_CHG_YMD',
    'RDCDVC_SE_CD',
    'RDCDVC_KND', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['매연조건판정코드',
    '성능확인검사종합판정',
    '저감장치등록번호',
    '성능확인검사매연농도값',
    '검사종류코드',
    '차대번호',
    '성능확인검사일자',
    '성능확인검사번호',
    '검사소명',
    '자동차등록번호',

    '미정',
    '미정',
    '미정',
    '미정', ]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼           내용
0        SMO_CND_JGMT_CD     매연조건판정코드
1   PFMCFINPC_GNRLZ_JGMT   성능확인검사종합판정
2          RDCDVC_REG_NO     저감장치등록번호
3   PFMCFINPC_SMO_CNTRVL  성능확인검사매연농도값
4            INSP_KND_CD       검사종류코드
5                    VIN         차대번호
6          PFMCFINPC_YMD     성능확인검사일자
7           PFMCFINPC_NO     성능확인검사번호
8              INSPOF_NM         검사소명
9                  VHRNO      자동차등록번호
10   MAXM_OTPT_MSRMT_VAL           미정
11         STRCT_CHG_YMD           미정
12          RDCDVC_SE_CD           미정
13            RDCDVC_KND           미정

### 데이터 info

In [151]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,SMO_CND_JDGMNT,매연조건판정,416681,SMO_CND_JGMT_CD,매연조건판정코드,416681.0,0.0,1450,1450.0
1,PFMCFINPC_GNRLZ_JDGMNT,성능확인검사종합판정,417140,PFMCFINPC_GNRLZ_JGMT,성능확인검사종합판정,417140.0,0.0,991,991.0
2,REDUC_REG_NO,저감등록번호,418117,RDCDVC_REG_NO,저감장치등록번호,418117.0,0.0,14,14.0
3,PFMCFINPC_SMO_DNSTY,성능확인검사매연농도,401461,PFMCFINPC_SMO_CNTRVL,성능확인검사매연농도값,401461.0,0.0,16670,16670.0
4,INSP_KND,검사종류,415979,INSP_KND_CD,검사종류코드,415979.0,0.0,2152,2152.0

### [출력] 컬럼명, 결측치 통계

In [256]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### [분석]

#### 차대번호

In [152]:
len(odf2['VIN'].unique()), len(sdf2['VIN'].unique())

(391679, 391679)

In [153]:
len(set(odf2['VIN'].unique()) - set(sdf2['VIN'].unique()))

0

#### 자동차등록번호

In [154]:
len(odf2['VHRNO'].unique())

390289

In [155]:
len(sdf2['VHRNO'].unique())

390289

In [156]:
len(set(odf2['VHRNO'].unique()) - set(sdf2['VHRNO'].unique()))

0

## 15\. 운행제한 발령정보(N_IS_ISSUE)

In [96]:
name = 'N_IS_ISSUE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

16 4
(1785, 16) (1785, 4)

In [97]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    16  1785
STD     4  1785

### 컬럼 확인

In [98]:
odf.columns.to_list()

['GNFD_NO',
 'RPST_GNFD_NO',
 'DNSTY_STDR_ID',
 'TY_STDR_ID',
 'GNFD_NM',
 'GNFD_EXEC_CND_FLAG',
 'GNFD_EXEC_RESRV_DT',
 'BEFT_ESTBS_ID',
 'DC',
 'GNFD_EXC_FLAG',
 'HMPG_INDIC_YN',
 'LCINFO_API_YN',
 'REG_ID',
 'REG_DT',
 'UPDT_ID',
 'UPDT_DT']

In [99]:
olist = [
    'TY_STDR_ID',
    'UPDT_DT', 
    'DNSTY_STDR_ID',
    'GNFD_NO',

    'RPST_GNFD_NO',
    'GNFD_NM',
    'GNFD_EXEC_CND_FLAG',
    'GNFD_EXEC_RESRV_DT',
    'BEFT_ESTBS_ID',
    'DC',
    'GNFD_EXC_FLAG',
    'HMPG_INDIC_YN',
    'LCINFO_API_YN',
    'REG_ID',
    'REG_DT',
    'UPDT_ID',
    ]

odict = {
    '컬럼':olist,
    '내용':
    [
    '유형 구분',
    '수정 일시', 
    '농도기준 발령구분',
    '발령 번호',

    'RPST_GNFD_NO',
    'GNFD_NM',
    'GNFD_EXEC_CND_FLAG',
    'GNFD_EXEC_RESRV_DT',
    'BEFT_ESTBS_ID',
    'DC',
    'GNFD_EXC_FLAG',
    'HMPG_INDIC_YN',
    'LCINFO_API_YN',
    'REG_ID',
    'REG_DT',
    'UPDT_ID',
    ]
    }

ocol = pd.DataFrame(odict)
ocol

                    컬럼         내용
0           TY_STDR_ID      유형 구분
1              UPDT_DT      수정 일시
2        DNSTY_STDR_ID  농도기준 발령구분
3              GNFD_NO      발령 번호
4         RPST_GNFD_NO         미정
5              GNFD_NM         미정
6   GNFD_EXEC_CND_FLAG         미정
7   GNFD_EXEC_RESRV_DT         미정
8        BEFT_ESTBS_ID         미정
9                   DC         미정
10       GNFD_EXC_FLAG         미정
11       HMPG_INDIC_YN         미정
12       LCINFO_API_YN         미정
13              REG_ID         미정
14              REG_DT         미정
15             UPDT_ID         미정

In [100]:
sdf.columns.to_list()

['CCNTRA_CRTR_GNFD_SE', 'GNFD_NO', 'TY_SE', 'MDFCN_DT']

In [101]:
slist = [
    'TY_SE', 
    'MDFCN_DT', 
    'CCNTRA_CRTR_GNFD_SE', 
    'GNFD_NO', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['유형구분', 
    '수정일시', 
    '농도기준발령구분', 
    '발령번호', ]
    }

scol = pd.DataFrame(sdict)
scol

                    컬럼        내용
0                TY_SE      유형구분
1             MDFCN_DT      수정일시
2  CCNTRA_CRTR_GNFD_SE  농도기준발령구분
3              GNFD_NO      발령번호

### 데이터 info

In [102]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,TY_STDR_ID,유형 구분,1785,TY_SE,유형구분,1785.0,0.0,0,0.0
1,UPDT_DT,수정 일시,1652,MDFCN_DT,수정일시,1652.0,0.0,133,133.0
2,DNSTY_STDR_ID,농도기준 발령구분,1785,CCNTRA_CRTR_GNFD_SE,농도기준발령구분,1785.0,0.0,0,0.0
3,GNFD_NO,발령 번호,1785,GNFD_NO,발령번호,1785.0,0.0,0,0.0
4,RPST_GNFD_NO,미정,1785,NaN,NaN,NaN,NaN,0,NaN

### [출력] 컬럼명, 결측치 통계

In [264]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### [분석]

#### 차대번호

In [104]:
len(odf2['VIN'].unique()), len(sdf2['VIN'].unique())

KeyError: 'VIN'

In [ ]:
len(set(odf2['VIN'].unique()) - set(odf2['VIN'].unique()))

0

#### 자동차등록번호

In [ ]:
odf2['VHRNO'].unique()

array(['60다6989', '50모3406', '35마2904', ..., '서울55로5608', '05버4210',
       '64주8535'], dtype=object)

In [ ]:
sdf2['VHRNO'].unique()

array(['70저4653', '52어8161', '67어5081', ..., '40서5406', '87저7702',
       '50보6931'], dtype=object)

## 16\. [e] 비상시 및 계절제 단속발령(N_IS_ISSUE_DISCLOSURE)
- [⭕] ODS, STD 없음.

In [4]:
name = 'N_IS_ISSUE_DISCLOSURE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'D:/과업/[한국환경공단]자동차_환경_빅데이터_구축_2차/data/ODS\\ODS_N_IS_ISSUE_DISCLOSURE.csv'

In [ ]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    16  1785
STD     4  1785

### 컬럼 확인

In [ ]:
odf.columns.to_list()

['GNFD_NO',
 'RPST_GNFD_NO',
 'DNSTY_STDR_ID',
 'TY_STDR_ID',
 'GNFD_NM',
 'GNFD_EXEC_CND_FLAG',
 'GNFD_EXEC_RESRV_DT',
 'BEFT_ESTBS_ID',
 'DC',
 'GNFD_EXC_FLAG',
 'HMPG_INDIC_YN',
 'LCINFO_API_YN',
 'REG_ID',
 'REG_DT',
 'UPDT_ID',
 'UPDT_DT']

In [ ]:
olist = [
    'TY_STDR_ID',
    'UPDT_DT', 
    'DNSTY_STDR_ID',
    'GNFD_NO',

    'RPST_GNFD_NO',
    'GNFD_NM',
    'GNFD_EXEC_CND_FLAG',
    'GNFD_EXEC_RESRV_DT',
    'BEFT_ESTBS_ID',
    'DC',
    'GNFD_EXC_FLAG',
    'HMPG_INDIC_YN',
    'LCINFO_API_YN',
    'REG_ID',
    'REG_DT',
    'UPDT_ID',
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['유형 구분',
    '수정 일시', 
    '농도기준 발령구분',
    '발령 번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

ocol = pd.DataFrame(odict)
ocol

                    컬럼         내용
0           TY_STDR_ID      유형 구분
1              UPDT_DT      수정 일시
2        DNSTY_STDR_ID  농도기준 발령구분
3              GNFD_NO      발령 번호
4         RPST_GNFD_NO         미정
5              GNFD_NM         미정
6   GNFD_EXEC_CND_FLAG         미정
7   GNFD_EXEC_RESRV_DT         미정
8        BEFT_ESTBS_ID         미정
9                   DC         미정
10       GNFD_EXC_FLAG         미정
11       HMPG_INDIC_YN         미정
12       LCINFO_API_YN         미정
13              REG_ID         미정
14              REG_DT         미정
15             UPDT_ID         미정

In [ ]:
sdf.columns.to_list()

['CCNTRA_CRTR_GNFD_SE', 'GNFD_NO', 'TY_SE', 'MDFCN_DT']

In [ ]:
slist = [
    'TY_SE', 
    'MDFCN_DT', 
    'CCNTRA_CRTR_GNFD_SE', 
    'GNFD_NO', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['유형구분', 
    '수정일시', 
    '농도기준발령구분', 
    '발령번호', ]
    }

scol = pd.DataFrame(sdict)
scol

                    컬럼        내용
0                TY_SE      유형구분
1             MDFCN_DT      수정일시
2  CCNTRA_CRTR_GNFD_SE  농도기준발령구분
3              GNFD_NO      발령번호

### 데이터 info

In [ ]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

                oindex  ocount               sindex  scount   차이
0           TY_STDR_ID    1785                TY_SE  1785.0  0.0
1              UPDT_DT    1652             MDFCN_DT  1652.0  0.0
2        DNSTY_STDR_ID    1785  CCNTRA_CRTR_GNFD_SE  1785.0  0.0
3              GNFD_NO    1785              GNFD_NO  1785.0  0.0
4         RPST_GNFD_NO    1785                  NaN     NaN  NaN
5              GNFD_NM    1785                  NaN     NaN  NaN
6   GNFD_EXEC_CND_FLAG    1785                  NaN     NaN  NaN
7   GNFD_EXEC_RESRV_DT    1784                  NaN     NaN  NaN
8        BEFT_ESTBS_ID       0                  NaN     NaN  NaN
9                   DC    1785                  NaN     NaN  NaN
10       GNFD_EXC_FLAG    1785                  NaN     NaN  NaN
11       HMPG_INDIC_YN    1785                  NaN     NaN  NaN
12       LCINFO_API_YN    1785                  NaN     NaN  NaN
13              REG_ID    1785                  NaN     NaN  NaN
14              REG_DT    1785                  NaN     NaN  NaN
15             UPDT_ID    1652                  NaN     NaN  NaN

### [출력] 컬럼명, 결측치 통계

In [ ]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### STD만 진행

In [3]:
# about 
name = 'N_IS_ISSUE_DISCLOSURE'
std_file_name = f'STD_{name}'
spath = os.path.join(std_path, std_file_name + '.csv')
sdf = pd.read_csv(spath, low_memory=False)
print(len(sdf.columns))
print(sdf.shape)

6
(80378264, 6)

In [4]:
t_info = {'컬럼_수':[sdf.shape[1]], '행_수':[sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['STD'])
t_df

     컬럼_수       행_수
STD     6  80378264

#### 컬럼 확인

In [5]:
sdf.columns.to_list()

['DSCL_DT', 'GNFD_NO', 'LEZ_CDN_GNO_TG_RG_CD', 'VHCL_MNG_NO', 'VIN', 'VHRNO']

In [6]:
slist = [
    'DSCL_DT', 
    'LEZ_CDN_GNO_TG_RG_CD', 
    'VHCL_MNG_NO', 
    'VIN', 
    'VHRNO', 
    'GNFD_NO', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    [
    '적발일시', 
    '운행제한단속발령대상지역코드', 
    '차량관리번호', 
    '차대번호', 
    '차량등록번호', 
    '발령번호', 
    ]
    }

scol = pd.DataFrame(sdict)
scol

                     컬럼              내용
0               DSCL_DT            적발일시
1  LEZ_CDN_GNO_TG_RG_CD  운행제한단속발령대상지역코드
2           VHCL_MNG_NO          차량관리번호
3                   VIN            차대번호
4                 VHRNO          차량등록번호
5               GNFD_NO            발령번호

#### 데이터 info

In [7]:
sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]
scount['STD_mcount'] = sdf2.shape[0] - scount['scount']
scount.head()

                 sindex            scol    scount  STD_mcount
0               DSCL_DT            적발일시  80378264           0
1  LEZ_CDN_GNO_TG_RG_CD  운행제한단속발령대상지역코드  80378264           0
2           VHCL_MNG_NO          차량관리번호  80378264           0
3                   VIN            차대번호  80378264           0
4                 VHRNO          차량등록번호  80378264           0

In [9]:
sdf2.isnull().sum()

DSCL_DT                 0
LEZ_CDN_GNO_TG_RG_CD    0
VHCL_MNG_NO             0
VIN                     0
VHRNO                   0
GNFD_NO                 0
dtype: int64

#### [출력] [STD]컬럼명, 결측치 통계

In [ ]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제][STD]{name}.xlsx') as texcel:
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    scount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제][STD]{name}.xlsx 출력완료.')

## 17\. 운행제한 단속정보(N_US_DISCLOSURE)

In [157]:
name = 'N_US_DISCLOSURE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

17 6
(3090035, 17) (3075037, 6)

In [158]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수      행_수
ODS    17  3090035
STD     6  3075037

### 컬럼 확인

In [159]:
odf.columns.to_list()

['NO',
 'ODR_YM',
 'REG_SIDO_CD',
 'REG_SIGNGU_CD',
 'DISCL_TY',
 'REGLT_AREA_CD',
 'TFCLNE_ID',
 'DISCL_DEHMS',
 'VHMNO',
 'VIN',
 'VHRNO',
 'FILE_NM',
 'ORG_FILE_CURS_NM',
 'THUMB_FILE_CURS_NM',
 'DTL_FILE_CURS_NM',
 'REG_ID',
 'REG_DT']

In [160]:
olist = [
    'DISCL_DEHMS',
    'VIN',
    'VHRNO',
    'DISCL_TY',
    'REGLT_AREA_CD',
    'VHMNO',

    'NO',
    'ODR_YM',
    'REG_SIDO_CD',
    'REG_SIGNGU_CD',
    'TFCLNE_ID',
    'FILE_NM',
    'ORG_FILE_CURS_NM',
    'THUMB_FILE_CURS_NM',
    'DTL_FILE_CURS_NM',
    'REG_ID',
    'REG_DT', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    [
    '적발일시',
    '차대번호',
    '차량등록번호',
    '적발유형',
    '단속지역코드',
    '차량관리번호',

    'NO',
    'ODR_YM',
    'REG_SIDO_CD',
    'REG_SIGNGU_CD',
    'TFCLNE_ID',
    'FILE_NM',
    'ORG_FILE_CURS_NM',
    'THUMB_FILE_CURS_NM',
    'DTL_FILE_CURS_NM',
    'REG_ID',
    'REG_DT', 
    ]
    }

ocol = pd.DataFrame(odict)
ocol

                    컬럼      내용
0          DISCL_DEHMS    적발일시
1                  VIN    차대번호
2                VHRNO  차량등록번호
3             DISCL_TY    적발유형
4        REGLT_AREA_CD  단속지역코드
5                VHMNO  차량관리번호
6                   NO      미정
7               ODR_YM      미정
8          REG_SIDO_CD      미정
9        REG_SIGNGU_CD      미정
10           TFCLNE_ID      미정
11             FILE_NM      미정
12    ORG_FILE_CURS_NM      미정
13  THUMB_FILE_CURS_NM      미정
14    DTL_FILE_CURS_NM      미정
15              REG_ID      미정
16              REG_DT      미정

In [161]:
sdf.columns.to_list()

['DSCL_DT', 'DSCL_TY_CD', 'CRDN_RGN_CD', 'VHCL_MNG_NO', 'VIN', 'VHRNO']

In [162]:
slist = [
    'DSCL_DT', 
    'VIN', 
    'VHRNO', 
    'DSCL_TY_CD', 
    'CRDN_RGN_CD', 
    'VHCL_MNG_NO', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['적발일시', 
    '차대번호', 
    '차량등록번호', 
    '적발유형코드', 
    '단속지역코드', 
    '차량관리번호', ]
    }

scol = pd.DataFrame(sdict)
scol

            컬럼      내용
0      DSCL_DT    적발일시
1          VIN    차대번호
2        VHRNO  차량등록번호
3   DSCL_TY_CD  적발유형코드
4  CRDN_RGN_CD  단속지역코드
5  VHCL_MNG_NO  차량관리번호

### 데이터 info

In [163]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,DISCL_DEHMS,적발일시,3090035,DSCL_DT,적발일시,3075037.0,14998.0,0,0.0
1,VIN,차대번호,3090035,VIN,차대번호,3075037.0,14998.0,0,0.0
2,VHRNO,차량등록번호,3090035,VHRNO,차량등록번호,3075037.0,14998.0,0,0.0
3,DISCL_TY,적발유형,3090035,DSCL_TY_CD,적발유형코드,3075037.0,14998.0,0,0.0
4,REGLT_AREA_CD,단속지역코드,3090035,CRDN_RGN_CD,단속지역코드,3075037.0,14998.0,0,0.0

### [출력] 컬럼명, 결측치 통계

In [272]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### [분석]

#### 차대번호

In [164]:
len(odf2['VIN'].unique()), len(sdf2['VIN'].unique())

(85755, 85594)

In [165]:
len(set(odf2['VIN'].unique()) - set(sdf2['VIN'].unique()))

170

#### 자동차등록번호

In [166]:
len(odf2['VHRNO'].unique())

85881

In [167]:
len(sdf2['VHRNO'].unique())

85764

In [168]:
len(set(odf2['VHRNO'].unique()) - set(sdf2['VHRNO'].unique()))

117

## 18\. 정밀검사 검사정보(TB_EET_HIS_ME)
- [⭕] ODS, STD 없음

In [ ]:
# about 21m
name = 'TB_EET_HIS_ME'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

In [5]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수       행_수
ODS    75  28682228
STD    48  28513858

### 컬럼 확인

In [6]:
odf.columns.to_list()

['SMO_CHK_ORG_NM',
 'SMO_CHK_DATE',
 'SMO_CHK_TYPE',
 'SMO_CHK_REG_NO',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'CAR_SPEC_REG_NO',
 'CAR_NM',
 'CAR_TYPE_NM',
 'USAGE',
 'CAR_YEAR',
 'CAR_FUEL_NM',
 'CAR_MILE',
 'CAR_LENGTH',
 'CAR_WIDTH',
 'CAR_HEIGHT',
 'ENGINE_TYPE',
 'ENGINE_CAPACITY',
 'ENGINE_POWER',
 'CAR_WEIGHT',
 'TOT_WEIGHT',
 'CAR_PASSENGER',
 'CONT',
 'FIRST_REG_DATE',
 'SMO_CHK_EXP_DATE',
 'SMO_FUN_CHK_JUDGE_YN',
 'SMO_FUN_CHK_FAIL_ITEM',
 'SMO_CHK_METHOD',
 'UNLOAD_SMO_VAL1',
 'UNLOAD_SMO_LIM1',
 'UNLOAD_SMO_JUDGE1',
 'UNLOAD_SMO_VAL2',
 'UNLOAD_SMO_LIM2',
 'UNLOAD_SMO_JUDGE2',
 'UNLOAD_SMO_VAL3',
 'UNLOAD_SMO_LIM3',
 'UNLOAD_SMO_JUDGE3',
 'UNLOAD_SMO_VAL4',
 'UNLOAD_SMO_LIM4',
 'UNLOAD_SMO_JUDGE4',
 'UNLOAD_SMO_VAL5',
 'UNLOAD_SMO_LIM5',
 'UNLOAD_SMO_JUDGE5',
 'CO2_VAL',
 'ENGINE_TOR_LIM',
 'ENGINE_TOR_VAL',
 'O2_VAL',
 'AIR_TEMPERATURE',
 'AIR_PRESSURE',
 'SMO_CHK_JUDGE_YN',
 'RE_INS_DATE2',
 'SMO_CHK_EXP_DATE2',
 'SMO_FUN_CHK_REC_NM',
 'SMO_CHK_REC_NM',
 'SMO_CHK_ORG_OWNER_NM',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'ETC_CONT4',
 'ETC_CONT5',
 'SRC_TBL',
 'SMO_CLOCK_INFO',
 'CMB_SMO_CHK_REG_NO',
 'JOB_DATE',
 'UNLOAD_SMO_VAL6',
 'UNLOAD_SMO_LIM6',
 'UNLOAD_SMO_JUDGE6',
 'FILE_NM',
 'MAKE_REG_DATE',
 'DATA_GBN',
 'DELETE_GBN',
 'DELETE_REASON1',
 'DELETE_REASON2',
 'DELETE_REASON3',
 'DELETE_REASON4']

In [7]:
olist = [
    'CAR_FUEL_NM',
    'CAR_MILE',
    'CAR_NM',
    'CAR_REG_NO',
    'CAR_SER_NO',
    'CAR_TYPE_NM',
    'CAR_YEAR',
    'CMB_SMO_CHK_REG_NO',
    'CO2_VAL',
    'ENGINE_TOR_LIM',
    'ENGINE_TOR_VAL',
    'ENGINE_TYPE',
    'O2_VAL',
    'RE_INS_DATE2',
    'SMO_CHK_DATE',
    'SMO_CHK_JUDGE_YN',
    'SMO_CHK_METHOD',
    'SMO_CHK_ORG_NM',
    'SMO_CHK_REG_NO',
    'SMO_CHK_TYPE',
    'SMO_CLOCK_INFO',
    'UNLOAD_SMO_JUDGE1',
    'UNLOAD_SMO_JUDGE2',
    'UNLOAD_SMO_JUDGE3',
    'UNLOAD_SMO_JUDGE4',
    'UNLOAD_SMO_JUDGE5',
    'UNLOAD_SMO_JUDGE6',
    'UNLOAD_SMO_LIM1',
    'UNLOAD_SMO_LIM2',
    'UNLOAD_SMO_LIM3',
    'UNLOAD_SMO_LIM4',
    'UNLOAD_SMO_LIM5',
    'UNLOAD_SMO_LIM6',
    'UNLOAD_SMO_VAL1',
    'UNLOAD_SMO_VAL2',
    'UNLOAD_SMO_VAL3',
    'UNLOAD_SMO_VAL4',
    'UNLOAD_SMO_VAL5',
    'UNLOAD_SMO_VAL6',
    'USAGE',

    'SMO_CHK_EXP_DATE',

    'SMO_CHK_EXP_DATE2',

    'CAR_SPEC_REG_NO',
    'CAR_LENGTH',
    'CAR_WIDTH',
    'CAR_HEIGHT',
    'ENGINE_CAPACITY',
    'ENGINE_POWER',
    'CAR_WEIGHT',
    'TOT_WEIGHT',
    'CAR_PASSENGER',
    'CONT',
    'FIRST_REG_DATE',
    'SMO_FUN_CHK_JUDGE_YN',
    'SMO_FUN_CHK_FAIL_ITEM',
    'AIR_TEMPERATURE',
    'AIR_PRESSURE',
    'SMO_FUN_CHK_REC_NM',
    'SMO_CHK_REC_NM',
    'SMO_CHK_ORG_OWNER_NM',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'ETC_CONT4',
    'ETC_CONT5',
    'SRC_TBL',
    'JOB_DATE',
    'FILE_NM',
    'MAKE_REG_DATE',
    'DATA_GBN',
    'DELETE_GBN',
    'DELETE_REASON1',
    'DELETE_REASON2',
    'DELETE_REASON3',
    'DELETE_REASON4', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    [
    '사용연료',
    '주행거리',
    '차명',
    '차량번호',
    '차대번호',
    '차종',
    '차량연식',
    '정밀검사 검사소코드',
    '이산화탄소값',
    '최대출력허용치',
    '최대출력측정값',
    '엔진형식',
    '산소값',
    '재검사기간',
    '정밀검사일자',
    '정밀검사판정',
    '정밀검사측정방법',
    '정밀검사소명',
    '정밀검사접수번호',
    '정밀검사종류',
    '정밀검사시각정보',
    '무부하매연판정1',
    '무부하매연판정2',
    '무부하매연판정3',
    '무부하매연판정4',
    '무부하매연판정5',
    '무부하매연판정6',
    '무부하매연허용치1',
    '무부하매연허용치2',
    '무부하매연허용치3',
    '무부하매연허용치4',
    '무부하매연허용치5',
    '무부하매연허용치6',
    '무부하매연측정치1',
    '무부하매연측정치2',
    '무부하매연측정치3',
    '무부하매연측정치4',
    '무부하매연측정치5',
    '무부하매연측정치6',
    '차량용도',

    '정밀검사유효기간',

    '정밀검사유효기간2',

    'CAR_SPEC_REG_NO',
    'CAR_LENGTH',
    'CAR_WIDTH',
    'CAR_HEIGHT',
    'ENGINE_CAPACITY',
    'ENGINE_POWER',
    'CAR_WEIGHT',
    'TOT_WEIGHT',
    'CAR_PASSENGER',
    'CONT',
    'FIRST_REG_DATE',
    'SMO_FUN_CHK_JUDGE_YN',
    'SMO_FUN_CHK_FAIL_ITEM',
    'AIR_TEMPERATURE',
    'AIR_PRESSURE',
    'SMO_FUN_CHK_REC_NM',
    'SMO_CHK_REC_NM',
    'SMO_CHK_ORG_OWNER_NM',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'ETC_CONT4',
    'ETC_CONT5',
    'SRC_TBL',
    'JOB_DATE',
    'FILE_NM',
    'MAKE_REG_DATE',
    'DATA_GBN',
    'DELETE_GBN',
    'DELETE_REASON1',
    'DELETE_REASON2',
    'DELETE_REASON3',
    'DELETE_REASON4',
    ]
    }

ocol = pd.DataFrame(odict)
ocol

                컬럼    내용
0      CAR_FUEL_NM  사용연료
1         CAR_MILE  주행거리
2           CAR_NM    차명
3       CAR_REG_NO  차량번호
4       CAR_SER_NO  차대번호
..             ...   ...
70      DELETE_GBN    미정
71  DELETE_REASON1    미정
72  DELETE_REASON2    미정
73  DELETE_REASON3    미정
74  DELETE_REASON4    미정

[75 rows x 2 columns]

In [8]:
sdf.columns.to_list()

['VIN',
 'FUEL_CD',
 'PRCINSP_DRVNG_DSTNC',
 'SMO_CODE',
 'VHCTY_CD',
 'VHCTY_TY_CD2',
 'VHCTY_CL_CD',
 'VHCNM',
 'VHRNO',
 'VHCTY_TY_CD1',
 'MODL_YR',
 'UNTY_RCPT_NO',
 'PRCINSP_CO2_VAL',
 'PREC_MAXM_OTPT_PRMVL',
 'PREC_MAXM_OTPT_MSTVL',
 'PRCINSP_EGIN_TY',
 'PRCINSP_O2_VAL',
 'PRCINSP_RINSP_WHL',
 'PRCINSP_YMD',
 'PRCINSP_JGMT',
 'PRCINSP_MSRMT_MTHD_CD',
 'PRECISN_INSPOF_NM',
 'PRCINSP_RCPT_NO',
 'PRCINSP_KND_CD',
 'PRCINSP_HR_INFO',
 'PREC_NLOD_SMO_JT_YN1',
 'PREC_NLOD_SMO_JT_YN2',
 'PREC_NLOD_SMO_JT_YN3',
 'PREC_NLOD_SMO_JT_YN4',
 'PREC_NLOD_SMO_JT_YN5',
 'PREC_NLOD_SMO_JT_YN6',
 'PREC_NLOD_SMO_PRMVL1',
 'PREC_NLOD_SMO_PRMVL2',
 'PREC_NLOD_SMO_PRMVL3',
 'PREC_NLOD_SMO_PRMVL4',
 'PREC_NLOD_SMO_PRMVL5',
 'PREC_NLOD_SMO_PRMVL6',
 'PREC_NLOD_SMO_MSTVL1',
 'PREC_NLOD_SMO_MSTVL2',
 'PREC_NLOD_SMO_MSTVL3',
 'PREC_NLOD_SMO_MSTVL4',
 'PREC_NLOD_SMO_MSTVL5',
 'PREC_NLOD_SMO_MSTVL6',
 'PREC_VHCL_PURPS_CD',
 'PRC_BF_VDWL_EXPRYDY',
 'FNCINSP_JGMT_YN',
 'AIR_TMPRT',
 'AIR_PSSR']

In [9]:
slist = [
    'FUEL_CD',
    'PRCINSP_DRVNG_DSTNC',
    'VHCNM',
    'VHRNO',
    'VIN',
    'VHCTY_TY_CD1',
    'MODL_YR',
    'UNTY_RCPT_NO',
    'PRCINSP_CO2_VAL',
    'PREC_MAXM_OTPT_PRMVL',
    'PREC_MAXM_OTPT_MSTVL',
    'PRCINSP_EGIN_TY',
    'PRCINSP_O2_VAL',
    'PRCINSP_RINSP_WHL',
    'PRCINSP_YMD',
    'PRCINSP_JGMT',
    'PRCINSP_MSRMT_MTHD_CD',
    'PRECISN_INSPOF_NM',
    'PRCINSP_RCPT_NO',
    'PRCINSP_KND_CD',
    'PRCINSP_HR_INFO',
    'PREC_NLOD_SMO_JT_YN1',
    'PREC_NLOD_SMO_JT_YN2',
    'PREC_NLOD_SMO_JT_YN3',
    'PREC_NLOD_SMO_JT_YN4',
    'PREC_NLOD_SMO_JT_YN5',
    'PREC_NLOD_SMO_JT_YN6',
    'PREC_NLOD_SMO_PRMVL1',
    'PREC_NLOD_SMO_PRMVL2',
    'PREC_NLOD_SMO_PRMVL3',
    'PREC_NLOD_SMO_PRMVL4',
    'PREC_NLOD_SMO_PRMVL5',
    'PREC_NLOD_SMO_PRMVL6',
    'PREC_NLOD_SMO_MSTVL1',
    'PREC_NLOD_SMO_MSTVL2',
    'PREC_NLOD_SMO_MSTVL3',
    'PREC_NLOD_SMO_MSTVL4',
    'PREC_NLOD_SMO_MSTVL5',
    'PREC_NLOD_SMO_MSTVL6',
    'PREC_VHCL_PURPS_CD',
    'VHCTY_CD',
    'VHCTY_CL_CD',
    'VHCTY_TY_CD2',
    'SMO_CODE',
    'PRC_BF_VDWL_EXPRYDY',

    'FNCINSP_JGMT_YN',
    'AIR_TMPRT',
    'AIR_PSSR',  
    ]

sdict = {
    '컬럼':slist,
    '내용':
    [
    '연료코드',
    '정밀검사주행거리',
    '차명',
    '자동차등록번호',
    '차대번호',
    '차종유형코드1',
    '모델연도',
    '통합접수번호',
    '정밀검사이산화탄소값',
    '정밀검사최대출력허용값',
    '정밀검사최대출력측정값',
    '정밀검사엔진형식',
    '정밀검사산소값',
    '정밀검사재검사기간',
    '정밀검사일자',
    '정밀검사판정',
    '정밀검사측정방법',
    '정밀검사소명',
    '정밀검사접수번호',
    '정밀검사종류코드',
    '정밀검사시간정보',
    '정밀검사무부하매연판정여부1',
    '정밀검사무부하매연판정여부2',
    '정밀검사무부하매연판정여부3',
    '정밀검사무부하매연판정여부4',
    '정밀검사무부하매연판정여부5',
    '정밀검사무부하매연판정여부6',
    '정밀검사무부하매연허용값1',
    '정밀검사무부하매연허용값2',
    '정밀검사무부하매연허용값3',
    '정밀검사무부하매연허용값4',
    '정밀검사무부하매연허용값5',
    '정밀검사무부하매연허용값6',
    '정밀검사무부하매연측정값1',
    '정밀검사무부하매연측정값2',
    '정밀검사무부하매연측정값3',
    '정밀검사무부하매연측정값4',
    '정밀검사무부하매연측정값5',
    '정밀검사무부하매연측정값6',
    '정밀검사차량용도코드',
    '차종유형코드1',
    '차종분류코드',
    '차종유형코드2',
    '검사소코드',
    '정밀검사전유효기간만료일',

    'FNCINSP_JGMT_YN',
    'AIR_TMPRT',
    'AIR_PSSR',
    ]
    }

scol = pd.DataFrame(sdict)
scol

                       컬럼              내용
0                 FUEL_CD            연료코드
1     PRCINSP_DRVNG_DSTNC        정밀검사주행거리
2                   VHCNM              차명
3                   VHRNO         자동차등록번호
4                     VIN            차대번호
5            VHCTY_TY_CD1         차종유형코드1
6                 MODL_YR            모델연도
7            UNTY_RCPT_NO          통합접수번호
8         PRCINSP_CO2_VAL      정밀검사이산화탄소값
9    PREC_MAXM_OTPT_PRMVL     정밀검사최대출력허용값
10   PREC_MAXM_OTPT_MSTVL     정밀검사최대출력측정값
11        PRCINSP_EGIN_TY        정밀검사엔진형식
12         PRCINSP_O2_VAL         정밀검사산소값
13      PRCINSP_RINSP_WHL       정밀검사재검사기간
14            PRCINSP_YMD          정밀검사일자
15           PRCINSP_JGMT          정밀검사판정
16  PRCINSP_MSRMT_MTHD_CD        정밀검사측정방법
17      PRECISN_INSPOF_NM          정밀검사소명
18        PRCINSP_RCPT_NO        정밀검사접수번호
19         PRCINSP_KND_CD        정밀검사종류코드
20        PRCINSP_HR_INFO        정밀검사시간정보
21   PREC_NLOD_SMO_JT_YN1  정밀검사무부하매연판정여부1
22   PREC_NLOD_SMO_JT_YN2  정밀검사무부하매연판정여부2
23   PREC_NLOD_SMO_JT_YN3  정밀검사무부하매연판정여부3
24   PREC_NLOD_SMO_JT_YN4  정밀검사무부하매연판정여부4
25   PREC_NLOD_SMO_JT_YN5  정밀검사무부하매연판정여부5
26   PREC_NLOD_SMO_JT_YN6  정밀검사무부하매연판정여부6
27   PREC_NLOD_SMO_PRMVL1   정밀검사무부하매연허용값1
28   PREC_NLOD_SMO_PRMVL2   정밀검사무부하매연허용값2
29   PREC_NLOD_SMO_PRMVL3   정밀검사무부하매연허용값3
30   PREC_NLOD_SMO_PRMVL4   정밀검사무부하매연허용값4
31   PREC_NLOD_SMO_PRMVL5   정밀검사무부하매연허용값5
32   PREC_NLOD_SMO_PRMVL6   정밀검사무부하매연허용값6
33   PREC_NLOD_SMO_MSTVL1   정밀검사무부하매연측정값1
34   PREC_NLOD_SMO_MSTVL2   정밀검사무부하매연측정값2
35   PREC_NLOD_SMO_MSTVL3   정밀검사무부하매연측정값3
36   PREC_NLOD_SMO_MSTVL4   정밀검사무부하매연측정값4
37   PREC_NLOD_SMO_MSTVL5   정밀검사무부하매연측정값5
38   PREC_NLOD_SMO_MSTVL6   정밀검사무부하매연측정값6
39     PREC_VHCL_PURPS_CD      정밀검사차량용도코드
40               VHCTY_CD         차종유형코드1
41            VHCTY_CL_CD          차종분류코드
42           VHCTY_TY_CD2         차종유형코드2
43               SMO_CODE           검사소코드
44    PRC_BF_VDWL_EXPRYDY    정밀검사전유효기간만료일
45        FNCINSP_JGMT_YN              미정
46              AIR_TMPRT              미정
47               AIR_PSSR              미정

### 데이터 info

In [10]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CAR_FUEL_NM,사용연료,28682227,FUEL_CD,연료코드,28513857.0,168370.0,1,1.0
1,CAR_MILE,주행거리,28682220,PRCINSP_DRVNG_DSTNC,정밀검사주행거리,28513850.0,168370.0,8,8.0
2,CAR_NM,차명,28682228,VHCNM,차명,28513858.0,168370.0,0,0.0
3,CAR_REG_NO,차량번호,28682228,VHRNO,자동차등록번호,28513858.0,168370.0,0,0.0
4,CAR_SER_NO,차대번호,28682228,VIN,차대번호,28513858.0,168370.0,0,0.0

### [출력] 컬럼명, 결측치 통계

In [11]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

[정제]TB_EET_HIS_ME.xlsx 출력완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_1516\1252313295.py:6: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  texcel.save()

## 19\. 저감장치 부착AS(TB_ERP_ATT_AS)

In [169]:
name = 'TB_ERP_ATT_AS'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

16 6
(20838, 16) (20838, 6)

In [170]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수    행_수
ODS    16  20838
STD     6  20838

### 컬럼 확인

In [171]:
odf.columns.to_list()

['ERP_REG_NO',
 'AS_DATE',
 'AS_CONT',
 'AS_REASON',
 'AS_MONEY',
 'AS_MONEY_METHOD',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'ATT_DATE',
 'MAKER_ORG_CD',
 'CONF_CHG_DATE',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'REC_DATE',
 'REC_NM']

In [172]:
olist = [
    'CAR_SER_NO',
    'ERP_REG_NO',
    'AS_REASON',
    'AS_DATE',
    'AS_CONT',

    'AS_MONEY',
    'AS_MONEY_METHOD',
    'CAR_REG_NO',
    'ATT_DATE',
    'MAKER_ORG_CD',
    'CONF_CHG_DATE',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'REC_DATE',
    'REC_NM',  
    ]

odict = {
    '컬럼':olist,
    '내용':
    [
    '차대번호',
    '저감등록번호',
    'AS 사유',
    'AS 일자',
    'AS 횟수',

    'AS_MONEY',
    'AS_MONEY_METHOD',
    'CAR_REG_NO',
    'ATT_DATE',
    'MAKER_ORG_CD',
    'CONF_CHG_DATE',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'REC_DATE',
    'REC_NM',
      ]
    }

ocol = pd.DataFrame(odict)
ocol

                 컬럼      내용
0        CAR_SER_NO    차대번호
1        ERP_REG_NO  저감등록번호
2         AS_REASON   AS 사유
3           AS_DATE   AS 일자
4           AS_CONT   AS 횟수
5          AS_MONEY      미정
6   AS_MONEY_METHOD      미정
7        CAR_REG_NO      미정
8          ATT_DATE      미정
9      MAKER_ORG_CD      미정
10    CONF_CHG_DATE      미정
11        ETC_CONT1      미정
12        ETC_CONT2      미정
13        ETC_CONT3      미정
14         REC_DATE      미정
15           REC_NM      미정

In [173]:
sdf.columns.to_list()

['AS_NCNT', 'AS_YMD', 'AS_RESN', 'VIN', 'REDUC_REG_NO', 'VHRNO']

In [174]:
slist = [
    'VIN', 
    'REDUC_REG_NO', 
    'AS_RESN', 
    'AS_YMD', 
    'AS_NCNT', 

    'VHRNO',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    [
    '차대번호', 
    '저감등록번호', 
    'AS사유', 
    'AS일자', 
    'AS횟수', 

    'VHRNO',
    ]
    }

scol = pd.DataFrame(sdict)
scol

             컬럼      내용
0           VIN    차대번호
1  REDUC_REG_NO  저감등록번호
2       AS_RESN    AS사유
3        AS_YMD    AS일자
4       AS_NCNT    AS횟수
5         VHRNO      미정

### 데이터 info

In [175]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CAR_SER_NO,차대번호,20833,VIN,차대번호,20833.0,0.0,5,5.0
1,ERP_REG_NO,저감등록번호,20838,REDUC_REG_NO,저감등록번호,20838.0,0.0,0,0.0
2,AS_REASON,AS 사유,20461,AS_RESN,AS사유,20461.0,0.0,377,377.0
3,AS_DATE,AS 일자,20838,AS_YMD,AS일자,20838.0,0.0,0,0.0
4,AS_CONT,AS 횟수,20838,AS_NCNT,AS횟수,20838.0,0.0,0,0.0

### [출력] 컬럼명, 결측치 통계

In [280]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### [분석]

#### 차대번호

In [176]:
len(odf2['CAR_SER_NO'].unique()), len(sdf2['VIN'].unique())

(10305, 10305)

In [177]:
len(set(odf2['CAR_SER_NO'].unique()) - set(sdf2['VIN'].unique()))

0

## 20\. 저감장치 부착이력(TB_ERP_ATT_HIS)
- [⭕] STD 없음
- 파일명 수정(STD_ERP_ATT_HIS -> STD_TB_ERP_ATT_HIS)

In [14]:
name = 'TB_ERP_ATT_HIS'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

103 16
(810777, 103) (810777, 16)

In [15]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS   103  810777
STD    16  810777

### 컬럼 확인

In [16]:
odf.columns.to_list()

['ERP_REG_NO',
 'SIDO',
 'SIGUNGU',
 'CAR_REG_NO',
 'CURR_CAR_REG_NO',
 'CAR_SER_NO',
 'CAR_TYPE_NM',
 'USAGE',
 'CAR_YEAR',
 'FIRST_REG_DATE',
 'CAR_OWNER_NM',
 'USER_CONTACT_TEL_NO',
 'ATT_ORG_NM',
 'CURR_SIGUNGU',
 'ATT_DATE',
 'EMI_RED_TYPE1',
 'EMI_RED_TYPE2',
 'REG_MODEL_NO',
 'EQUIP_SER_NO',
 'SMO_CHK_ORG_NM',
 'CONF_CHG_DATE',
 'CAR_MILE',
 'MAKER_ORG_CD',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'ETC_CONT4',
 'ETC_CONT5',
 'SRC_TBL',
 'CAR_NM',
 'REC_DATE',
 'REC_NM',
 'APL_LAF_CD',
 'ERP_AID_YN',
 'ERP_NOT_AID_REASON',
 'ERP_CHK_STS',
 'M_DOC_ATTACH_YN',
 'P_CHK_DATE',
 'P_CHK_NM',
 'ERP_AID_CONFIRM_YN',
 'M_CHK_DATE',
 'M_CHK_NM',
 'G_CHK_DATE',
 'G_CHK_NM',
 'AIR_MONEY_DATE',
 'LAF_REC_DATE',
 'LAF_REC_NM',
 'AIR_MONEY',
 'AIR_MONEY_ME',
 'AID_YEAR',
 'Y_CHK_DATE',
 'Y_CHK_NM',
 'TOT_WEIGHT',
 'LAS_CHG_DATE',
 'LAS_CHG_NM',
 'EMI_RED_REMOVE_YN',
 'CALL_DATE',
 'CALL_RES_INFO',
 'CAR_DISP',
 'ENGINE_TYPE',
 'DISP_TEMPERATURE',
 'MAX_PRESSURE',
 'AVG_PRESSURE',
 'AEA_ASSO_PRINT_ENABLE',
 'TH_CHK_STS',
 'CHG_INFO_CD',
 'AEA_ASSO_PRINT_DATE',
 'T_CHK_DATE',
 'T_CHK_NM',
 'Z_CHK_DATE',
 'Z_CHK_NM',
 'INFO_CHK_ORG_CD',
 'INFO_CHK_NM',
 'INFO_CHK_DATE',
 'INFO_RETURN_REASON',
 'RETURN_CHK_DATE',
 'CAR_OWNER_ADDR1',
 'CAR_OWNER_ADDR2',
 'CAR_OWNER_POSTNO',
 'PM_EFF_VAL',
 'CAR_TYPE_GB',
 'LOW_INCOME_GRP_YN',
 'TDMS_YN',
 'REST_MONEY',
 'FNS_MONEY_YN',
 'AIR_MONEY_ME_DATE',
 'AIR_MONEY_ME_NM',
 'PAY_MONEY',
 'Z_AIR_MONEY',
 'AIR_MONEY_EQUIP',
 'AIR_MONEY_EX',
 'CAR_OWNER_GB',
 'T_REG_DATE',
 'T_REASON',
 'T_REASON_DTL',
 'DOC_NO',
 'SUBSIDY_REC_YN',
 'MAIN_EXP_REC_YN',
 'ENGINE_POWER',
 'CAR_FUEL_NM',
 'CAR_WEIGHT',
 'CAR_PASSENGER',
 'THREE_WAY_CATALYST_RETURN_YN']

In [17]:
olist = [
    'EMI_RED_TYPE2',
    'PM_EFF_VAL',
    'TDMS_YN',
    'CONF_CHG_DATE',
    'ATT_ORG_NM',
    'ATT_DATE',
    'T_CHK_DATE',
    'CAR_REG_NO',
    'CAR_SER_NO',
    'CAR_MILE',
    'EMI_RED_REMOVE_YN',
    'EMI_RED_TYPE1',
    'ERP_REG_NO',
    'RETURN_CHK_DATE',
    'EQUIP_SER_NO',
    'THREE_WAY_CATALYST_RETURN_YN',   

    'SIDO',
    'SIGUNGU',
    'CURR_CAR_REG_NO',
    'CAR_TYPE_NM',
    'USAGE',
    'CAR_YEAR',
    'FIRST_REG_DATE',
    'CAR_OWNER_NM',
    'USER_CONTACT_TEL_NO',
    'CURR_SIGUNGU',
    'REG_MODEL_NO',
    'SMO_CHK_ORG_NM',
    'MAKER_ORG_CD',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'ETC_CONT4',
    'ETC_CONT5',
    'SRC_TBL',
    'CAR_NM',
    'REC_DATE',
    'REC_NM',
    'APL_LAF_CD',
    'ERP_AID_YN',
    'ERP_NOT_AID_REASON',
    'ERP_CHK_STS',
    'M_DOC_ATTACH_YN',
    'P_CHK_DATE',
    'P_CHK_NM',
    'ERP_AID_CONFIRM_YN',
    'M_CHK_DATE',
    'M_CHK_NM',
    'G_CHK_DATE',
    'G_CHK_NM',
    'AIR_MONEY_DATE',
    'LAF_REC_DATE',
    'LAF_REC_NM',
    'AIR_MONEY',
    'AIR_MONEY_ME',
    'AID_YEAR',
    'Y_CHK_DATE',
    'Y_CHK_NM',
    'TOT_WEIGHT',
    'LAS_CHG_DATE',
    'LAS_CHG_NM',
    'CALL_DATE',
    'CALL_RES_INFO',
    'CAR_DISP',
    'ENGINE_TYPE',
    'DISP_TEMPERATURE',
    'MAX_PRESSURE',
    'AVG_PRESSURE',
    'AEA_ASSO_PRINT_ENABLE',
    'TH_CHK_STS',
    'CHG_INFO_CD',
    'AEA_ASSO_PRINT_DATE',
    'T_CHK_NM',
    'Z_CHK_DATE',
    'Z_CHK_NM',
    'INFO_CHK_ORG_CD',
    'INFO_CHK_NM',
    'INFO_CHK_DATE',
    'INFO_RETURN_REASON',
    'CAR_OWNER_ADDR1',
    'CAR_OWNER_ADDR2',
    'CAR_OWNER_POSTNO',
    'CAR_TYPE_GB',
    'LOW_INCOME_GRP_YN',
    'REST_MONEY',
    'FNS_MONEY_YN',
    'AIR_MONEY_ME_DATE',
    'AIR_MONEY_ME_NM',
    'PAY_MONEY',
    'Z_AIR_MONEY',
    'AIR_MONEY_EQUIP',
    'AIR_MONEY_EX',
    'CAR_OWNER_GB',
    'T_REG_DATE',
    'T_REASON',
    'T_REASON_DTL',
    'DOC_NO',
    'SUBSIDY_REC_YN',
    'MAIN_EXP_REC_YN',
    'ENGINE_POWER',
    'CAR_FUEL_NM',
    'CAR_WEIGHT',
    'CAR_PASSENGER',
    ]

odict = {
    '컬럼':olist,
    '내용':
    [
    '저감장치종류',
    'PM최종저감효율',
    'TDMS부착여부',
    '구조변경일자',
    '부착업체명',
    '부착일자',
    '탈거승인일',
    '차량번호',
    '차대번호',
    '주행거리',
    '저감장치반납여부',
    '저감장치구분',
    '저감등록번호',
    '재장착확인일자',
    '장치일련번호',
    '삼원촉매장치반납여부',   

    'SIDO',
    'SIGUNGU',
    'CURR_CAR_REG_NO',
    'CAR_TYPE_NM',
    'USAGE',
    'CAR_YEAR',
    'FIRST_REG_DATE',
    'CAR_OWNER_NM',
    'USER_CONTACT_TEL_NO',
    'CURR_SIGUNGU',
    'REG_MODEL_NO',
    'SMO_CHK_ORG_NM',
    'MAKER_ORG_CD',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'ETC_CONT4',
    'ETC_CONT5',
    'SRC_TBL',
    'CAR_NM',
    'REC_DATE',
    'REC_NM',
    'APL_LAF_CD',
    'ERP_AID_YN',
    'ERP_NOT_AID_REASON',
    'ERP_CHK_STS',
    'M_DOC_ATTACH_YN',
    'P_CHK_DATE',
    'P_CHK_NM',
    'ERP_AID_CONFIRM_YN',
    'M_CHK_DATE',
    'M_CHK_NM',
    'G_CHK_DATE',
    'G_CHK_NM',
    'AIR_MONEY_DATE',
    'LAF_REC_DATE',
    'LAF_REC_NM',
    'AIR_MONEY',
    'AIR_MONEY_ME',
    'AID_YEAR',
    'Y_CHK_DATE',
    'Y_CHK_NM',
    'TOT_WEIGHT',
    'LAS_CHG_DATE',
    'LAS_CHG_NM',
    'CALL_DATE',
    'CALL_RES_INFO',
    'CAR_DISP',
    'ENGINE_TYPE',
    'DISP_TEMPERATURE',
    'MAX_PRESSURE',
    'AVG_PRESSURE',
    'AEA_ASSO_PRINT_ENABLE',
    'TH_CHK_STS',
    'CHG_INFO_CD',
    'AEA_ASSO_PRINT_DATE',
    'T_CHK_NM',
    'Z_CHK_DATE',
    'Z_CHK_NM',
    'INFO_CHK_ORG_CD',
    'INFO_CHK_NM',
    'INFO_CHK_DATE',
    'INFO_RETURN_REASON',
    'CAR_OWNER_ADDR1',
    'CAR_OWNER_ADDR2',
    'CAR_OWNER_POSTNO',
    'CAR_TYPE_GB',
    'LOW_INCOME_GRP_YN',
    'REST_MONEY',
    'FNS_MONEY_YN',
    'AIR_MONEY_ME_DATE',
    'AIR_MONEY_ME_NM',
    'PAY_MONEY',
    'Z_AIR_MONEY',
    'AIR_MONEY_EQUIP',
    'AIR_MONEY_EX',
    'CAR_OWNER_GB',
    'T_REG_DATE',
    'T_REASON',
    'T_REASON_DTL',
    'DOC_NO',
    'SUBSIDY_REC_YN',
    'MAIN_EXP_REC_YN',
    'ENGINE_POWER',
    'CAR_FUEL_NM',
    'CAR_WEIGHT',
    'CAR_PASSENGER',
    ]
    }

ocol = pd.DataFrame(odict)
ocol

                  컬럼        내용
0      EMI_RED_TYPE2    저감장치종류
1         PM_EFF_VAL  PM최종저감효율
2            TDMS_YN  TDMS부착여부
3      CONF_CHG_DATE    구조변경일자
4         ATT_ORG_NM     부착업체명
..               ...       ...
98   MAIN_EXP_REC_YN        미정
99      ENGINE_POWER        미정
100      CAR_FUEL_NM        미정
101       CAR_WEIGHT        미정
102    CAR_PASSENGER        미정

[103 rows x 2 columns]

In [18]:
sdf.columns.to_list()

['DVICE_EXTRNS_YMD',
 'DVIE_EXTNS_ENTRPS_NM',
 'DRVNG_DSTNC',
 'VHRNO',
 'VIN',
 'STRCT_CHG_YMD',
 'RDCDVC_RTN_YN',
 'RDCDVC_SE',
 'RDCDVC_KND_CD',
 'DVICE_SN',
 'REDUC_REG_NO',
 'PM_LAST_REDUC_EFCNY',
 'REMNTNG_IDNTY_YMD',
 'TDMS_EXTRNS_YN',
 'THRWYCTL_DVIE_RTN_YN',
 'REMV_APRV_YMD']

In [19]:
slist = [
    'RDCDVC_KND_CD',
    'PM_LAST_REDUC_EFCNY',
    'TDMS_EXTRNS_YN',
    'STRCT_CHG_YMD',
    'DVIE_EXTNS_ENTRPS_NM',
    'DVICE_EXTRNS_YMD',
    'REMV_APRV_YMD', 
    'VHRNO',
    'VIN',
    'DRVNG_DSTNC',
    'RDCDVC_RTN_YN',
    'RDCDVC_SE',
    'REDUC_REG_NO',
    'REMNTNG_IDNTY_YMD',
    'DVICE_SN',
    'THRWYCTL_DVIE_RTN_YN',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['저감장치종류코드',
    'PM최종저감효율',
    'TDMS부착여부',
    '구조변경일자',
    '장치부착업체명',
    '장치부착일자',
    '탈거승인일자', 
    '자동차등록번호',
    '차대번호',
    '주행거리',
    '저감장치반납여부',
    '저감장치구분',
    '저감등록번호',
    '재장착확인일자',
    '장치일련번호',
    '삼원촉매장치반납여부',]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼          내용
0          RDCDVC_KND_CD    저감장치종류코드
1    PM_LAST_REDUC_EFCNY    PM최종저감효율
2         TDMS_EXTRNS_YN    TDMS부착여부
3          STRCT_CHG_YMD      구조변경일자
4   DVIE_EXTNS_ENTRPS_NM     장치부착업체명
5       DVICE_EXTRNS_YMD      장치부착일자
6          REMV_APRV_YMD      탈거승인일자
7                  VHRNO     자동차등록번호
8                    VIN        차대번호
9            DRVNG_DSTNC        주행거리
10         RDCDVC_RTN_YN    저감장치반납여부
11             RDCDVC_SE      저감장치구분
12          REDUC_REG_NO      저감등록번호
13     REMNTNG_IDNTY_YMD     재장착확인일자
14              DVICE_SN      장치일련번호
15  THRWYCTL_DVIE_RTN_YN  삼원촉매장치반납여부

### 데이터 info

In [20]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,EMI_RED_TYPE2,저감장치종류,586898,RDCDVC_KND_CD,저감장치종류코드,556312.0,30586.0,223879,254465.0
1,PM_EFF_VAL,PM최종저감효율,84460,PM_LAST_REDUC_EFCNY,PM최종저감효율,84460.0,0.0,726317,726317.0
2,TDMS_YN,TDMS부착여부,204951,TDMS_EXTRNS_YN,TDMS부착여부,204951.0,0.0,605826,605826.0
3,CONF_CHG_DATE,구조변경일자,810777,STRCT_CHG_YMD,구조변경일자,810777.0,0.0,0,0.0
4,ATT_ORG_NM,부착업체명,801632,DVIE_EXTNS_ENTRPS_NM,장치부착업체명,801632.0,0.0,9145,9145.0

### [출력] 컬럼명, 결측치 통계

In [21]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

[정제]TB_ERP_ATT_HIS.xlsx 출력완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_1516\1252313295.py:6: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  texcel.save()

## 21\. 요소수 정보(TB_ERP_UREAWATER)

In [178]:
name = 'TB_ERP_UREAWATER'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

7 3
(80, 7) (80, 3)

In [179]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수  행_수
ODS     7   80
STD     3   80

### 컬럼 확인

In [180]:
odf.columns.to_list()

['ERP_REG_NO',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'REC_DATE',
 'REC_NM',
 'LAS_CHG_DATE',
 'LAS_CHG_NM']

In [181]:
olist = [
    'CAR_SER_NO',
    'ERP_REG_NO',
    'CAR_REG_NO',

    'REC_DATE',
    'REC_NM',
    'LAS_CHG_DATE',
    'LAS_CHG_NM', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차대번호',
    '저감등록번호',
    '차량번호',

    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

             컬럼      내용
0    CAR_SER_NO    차대번호
1    ERP_REG_NO  저감등록번호
2    CAR_REG_NO    차량번호
3      REC_DATE      미정
4        REC_NM      미정
5  LAS_CHG_DATE      미정
6    LAS_CHG_NM      미정

In [182]:
sdf.columns.to_list()

['VHCL_MNG_NO', 'VIN', 'REDUC_REG_NO']

In [183]:
slist = [
    'VIN', 
    'REDUC_REG_NO',
    'VHCL_MNG_NO', 

    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차대번호', 
    '저감등록번호',
    '차량관리번호', ]
    }

scol = pd.DataFrame(sdict)
scol

             컬럼      내용
0           VIN    차대번호
1  REDUC_REG_NO  저감등록번호
2   VHCL_MNG_NO  차량관리번호

### 데이터 info

In [184]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CAR_SER_NO,차대번호,80,VIN,차대번호,80.0,0.0,0,0.0
1,ERP_REG_NO,저감등록번호,80,REDUC_REG_NO,저감등록번호,80.0,0.0,0,0.0
2,CAR_REG_NO,차량번호,80,VHCL_MNG_NO,차량관리번호,80.0,0.0,0,0.0
3,REC_DATE,미정,80,NaN,NaN,NaN,NaN,0,NaN
4,REC_NM,미정,80,NaN,NaN,NaN,NaN,0,NaN

### [출력] 컬럼명, 결측치 통계

In [288]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### [분석]

#### 차대번호

In [185]:
len(odf2['CAR_SER_NO'].unique()), len(sdf2['VIN'].unique())

(80, 80)

In [186]:
len(set(odf2['CAR_SER_NO'].unique()) - set(sdf2['VIN'].unique()))

0

#### 차량관리번호

In [189]:
len(odf2['CAR_REG_NO'].unique())

80

In [190]:
len(sdf2['VHCL_MNG_NO'].unique())

80

In [191]:
len(set(odf2['CAR_REG_NO'].unique()) - set(sdf2['VHCL_MNG_NO'].unique()))

0

## 22\. 요소수 상세정보(TB_ERP_UREAWATER_DTL)

In [289]:
name = 'TB_ERP_UREAWATER_DTL'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

14 8
(155, 14) (155, 8)

In [290]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수  행_수
ODS    14  155
STD     8  155

### 컬럼 확인

In [291]:
odf.columns.to_list()

['ERP_REG_NO',
 'UREAWATER_CHK_STS',
 'UREAWATER_LITER',
 'REMAIN_UREAWATER_LITER',
 'UREAWATER_MONEY',
 'REMAIN_UREAWATER_MONEY',
 'UREAWATER_COUNT',
 'UREAWATER_DATE',
 'UREAWATER_NM',
 'LAS_CHG_DATE',
 'LAS_CHG_NM',
 'UREAWATER_FINAL_DATE',
 'UREAWATER_FINAL_NM',
 'RETURN_REASON']

In [292]:
olist = [
    'ERP_REG_NO',
    'REMAIN_UREAWATER_MONEY',
    'UREAWATER_CHK_STS',
    'UREAWATER_DATE',
    'REMAIN_UREAWATER_LITER',
    'UREAWATER_MONEY',
    'UREAWATER_LITER',
    'UREAWATER_COUNT',
    
    'UREAWATER_NM',
    'LAS_CHG_DATE',
    'LAS_CHG_NM',
    'UREAWATER_FINAL_DATE',
    'UREAWATER_FINAL_NM',
    'RETURN_REASON', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['저감등록번호',
    '요소수보충잔여비용',
    '요소수보충진행상태',
    '요소수보충일자',
    '요소수보충잔여리터',
    '요소수보충비용',
    '요소수보충리터',
    '요소수보충횟수',
    
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼         내용
0               ERP_REG_NO     저감등록번호
1   REMAIN_UREAWATER_MONEY  요소수보충잔여비용
2        UREAWATER_CHK_STS  요소수보충진행상태
3           UREAWATER_DATE    요소수보충일자
4   REMAIN_UREAWATER_LITER  요소수보충잔여리터
5          UREAWATER_MONEY    요소수보충비용
6          UREAWATER_LITER    요소수보충리터
7          UREAWATER_COUNT    요소수보충횟수
8             UREAWATER_NM         미정
9             LAS_CHG_DATE         미정
10              LAS_CHG_NM         미정
11    UREAWATER_FINAL_DATE         미정
12      UREAWATER_FINAL_NM         미정
13           RETURN_REASON         미정

In [293]:
sdf.columns.to_list()

['REDUC_REG_NO',
 'UREA_SUPPL_RMND_QT',
 'UREA_SUPPL_RMND_CST',
 'UREA_SUPPL_PRGRS_STTS',
 'UREA_SUPPL_NCNT',
 'UREA_SUPPL_YMD',
 'UREA_SUPPL_QT',
 'UREA_SUPPL_CST']

In [294]:
slist = [
    'REDUC_REG_NO',
    'UREA_SUPPL_RMND_CST',
    'UREA_SUPPL_PRGRS_STTS',
    'UREA_SUPPL_YMD',
    'UREA_SUPPL_RMND_QT',
    'UREA_SUPPL_CST', 
    'UREA_SUPPL_QT',
    'UREA_SUPPL_NCNT',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['저감등록번호',
    '요소수보충잔여비용',
    '요소수보충진행상태',
    '요소수보충일자',
    '요소수보충잔여량',
    '요소수보충비용', 
    '요소수보충량',
    '요소수보충횟수',]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼         내용
0           REDUC_REG_NO     저감등록번호
1    UREA_SUPPL_RMND_CST  요소수보충잔여비용
2  UREA_SUPPL_PRGRS_STTS  요소수보충진행상태
3         UREA_SUPPL_YMD    요소수보충일자
4     UREA_SUPPL_RMND_QT   요소수보충잔여량
5         UREA_SUPPL_CST    요소수보충비용
6          UREA_SUPPL_QT     요소수보충량
7        UREA_SUPPL_NCNT    요소수보충횟수

### 데이터 info

In [295]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,ERP_REG_NO,저감등록번호,155,REDUC_REG_NO,저감등록번호,155.0,0.0,0,0.0
1,REMAIN_UREAWATER_MONEY,요소수보충잔여비용,155,UREA_SUPPL_RMND_CST,요소수보충잔여비용,155.0,0.0,0,0.0
2,UREAWATER_CHK_STS,요소수보충진행상태,155,UREA_SUPPL_PRGRS_STTS,요소수보충진행상태,155.0,0.0,0,0.0
3,UREAWATER_DATE,요소수보충일자,155,UREA_SUPPL_YMD,요소수보충일자,155.0,0.0,0,0.0
4,REMAIN_UREAWATER_LITER,요소수보충잔여리터,155,UREA_SUPPL_RMND_QT,요소수보충잔여량,155.0,0.0,0,0.0

### [출력] 컬럼명, 결측치 통계

In [296]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

## 23\. 전문정비(TB_ERR_RES)
- STD
    - 컬럼명
        - 'VHRNO' # VHCL_MNG_NO(6. 테이블정의서_v1.0)

In [226]:
name = 'TB_ERR_RES'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

42 16
(54617, 42) (54617, 16)

In [227]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수    행_수
ODS    42  54617
STD    16  54617

### 컬럼 확인

In [228]:
odf.columns.to_list()

['REPAIR_ORG_NM',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'REPAIR_DATE',
 'REPAIR_REG_NO',
 'RE_SMO_CHK_REG_NO',
 'CAR_NM',
 'CAR_YEAR',
 'CAR_OWNER_NM',
 'OFFICE_NM',
 'REPAIR_NM',
 'CAR_FUEL_NM',
 'FIRST_REG_DATE',
 'CAR_MILE',
 'REPAIR_COST',
 'WAR_REPAIR_YN',
 'RE_INS_DATE',
 'WAR_DATE',
 'WAR_KM',
 'REPAIR_COMMENT',
 'LOAD_CO',
 'LOAD_HC',
 'LOAD_NOX',
 'LOAD_SMOKE',
 'LOAD_TORK',
 'UNLOAD_CO',
 'UNLOAD_HC',
 'UNLOAD_SMOKE',
 'UNLOAD_NAM',
 'REPAIR_COMMENT_ETC',
 'REC_DATE',
 'REC_NM',
 'LAS_CHG_DATE',
 'LAS_CHG_NM',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'ETC_CONT4',
 'ETC_CONT5',
 'SRC_TBL',
 'FILE_NM',
 'JOB_DATE']

In [229]:
olist = [
    'LOAD_CO',
    'CAR_SER_NO',
    'CAR_REG_NO',
    'CAR_MILE',
    'LOAD_HC',
    'LOAD_NOX',
    'LOAD_SMOKE',
    'LOAD_TORK',
    'UNLOAD_SMOKE',
    'UNLOAD_NAM',
    'UNLOAD_HC',
    'UNLOAD_CO',
    'REPAIR_REG_NO',
    'REPAIR_ORG_NM',
    'RE_SMO_CHK_REG_NO',
    'REPAIR_DATE',

    'CAR_NM',
    'CAR_YEAR',
    'CAR_OWNER_NM',
    'OFFICE_NM',
    'REPAIR_NM',
    'CAR_FUEL_NM',
    'FIRST_REG_DATE',
    'REPAIR_COST',
    'WAR_REPAIR_YN',
    'RE_INS_DATE',
    'WAR_DATE',
    'WAR_KM',
    'REPAIR_COMMENT',
    'REPAIR_COMMENT_ETC',
    'REC_DATE',
    'REC_NM',
    'LAS_CHG_DATE',
    'LAS_CHG_NM',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'ETC_CONT4',
    'ETC_CONT5',
    'SRC_TBL',
    'FILE_NM',
    'JOB_DATE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['부하일산화탄소측정치',
    '차대번호',
    '차량등록번호',
    '주행거리',
    '부하탄화수소측정치',
    '부하질소산화물측정치',
    '부하매연측정치',
    '부하토크측정치',
    '무부하매연측정치',
    '무부하공기과잉률',
    '무부하탄화수소',
    '무부하일산화탄소',
    '전문정비접수번호',
    '전문정비업소명',
    '정밀재검사접수번호',
    '전문정비일',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                    컬럼          내용
0              LOAD_CO  부하일산화탄소측정치
1           CAR_SER_NO        차대번호
2           CAR_REG_NO      차량등록번호
3             CAR_MILE        주행거리
4              LOAD_HC   부하탄화수소측정치
5             LOAD_NOX  부하질소산화물측정치
6           LOAD_SMOKE     부하매연측정치
7            LOAD_TORK     부하토크측정치
8         UNLOAD_SMOKE    무부하매연측정치
9           UNLOAD_NAM    무부하공기과잉률
10           UNLOAD_HC     무부하탄화수소
11           UNLOAD_CO    무부하일산화탄소
12       REPAIR_REG_NO    전문정비접수번호
13       REPAIR_ORG_NM     전문정비업소명
14   RE_SMO_CHK_REG_NO   정밀재검사접수번호
15         REPAIR_DATE       전문정비일
16              CAR_NM          미정
17            CAR_YEAR          미정
18        CAR_OWNER_NM          미정
19           OFFICE_NM          미정
20           REPAIR_NM          미정
21         CAR_FUEL_NM          미정
22      FIRST_REG_DATE          미정
23         REPAIR_COST          미정
24       WAR_REPAIR_YN          미정
25         RE_INS_DATE          미정
26            WAR_DATE          미정
27              WAR_KM          미정
28      REPAIR_COMMENT          미정
29  REPAIR_COMMENT_ETC          미정
30            REC_DATE          미정
31              REC_NM          미정
32        LAS_CHG_DATE          미정
33          LAS_CHG_NM          미정
34           ETC_CONT1          미정
35           ETC_CONT2          미정
36           ETC_CONT3          미정
37           ETC_CONT4          미정
38           ETC_CONT5          미정
39             SRC_TBL          미정
40             FILE_NM          미정
41            JOB_DATE          미정

In [230]:
sdf.columns.to_list()

['DRVNG_DSTNC',
 'VHRNO',
 'VIN',
 'LOD_COX_MEVLU',
 'LOD_HC_MEVLU',
 'LOD_NOX_MEVLU',
 'LOD_SMO_MEVLU',
 'LOD_TQ_MEVLU',
 'OVHUL_YMD',
 'SPCY_OVHUL_BIZPLC_NM',
 'OVHUL_RCPT_NO',
 'PRCINSP_RINSP_RCPT_NO',
 'NOLOD_COX_MEVLU',
 'NOLOD_HC_MEVLU',
 'NOLOD_AIR_EXCRT_MEVLU',
 'NOLOD_SMO_MEVLU']

In [231]:
slist = [
    'LOD_COX_MEVLU',
    'VIN',
    'VHRNO', # VHCL_MNG_NO
    'DRVNG_DSTNC',
    'LOD_HC_MEVLU',
    'LOD_NOX_MEVLU',
    'LOD_SMO_MEVLU',
    'LOD_TQ_MEVLU',
    'NOLOD_SMO_MEVLU', 
    'NOLOD_AIR_EXCRT_MEVLU',
    'NOLOD_HC_MEVLU',
    'NOLOD_COX_MEVLU',
    'OVHUL_RCPT_NO',
    'SPCY_OVHUL_BIZPLC_NM',
    'PRCINSP_RINSP_RCPT_NO',
    'OVHUL_YMD',

    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['부하일산화탄소측정치',
    '차대번호',
    '차량관리번호',
    '주행거리',
    '부하탄화수소측정치',
    '부하질소산화물측정치',
    '부하매연측정치',
    '부하토크측정치',
    '무부하매연측정치', 
    '무부하공기과잉률측정치',
    '무부하탄화수소측정치',
    '무부하일산화탄소측정치',
    '정비접수번호',
    '전문정비사업소명',
    '정밀재검사접수번호',
    '정비일자',]
    }

scol = pd.DataFrame(sdict)
scol

                       컬럼           내용
0           LOD_COX_MEVLU   부하일산화탄소측정치
1                     VIN         차대번호
2                   VHRNO       차량관리번호
3             DRVNG_DSTNC         주행거리
4            LOD_HC_MEVLU    부하탄화수소측정치
5           LOD_NOX_MEVLU   부하질소산화물측정치
6           LOD_SMO_MEVLU      부하매연측정치
7            LOD_TQ_MEVLU      부하토크측정치
8         NOLOD_SMO_MEVLU     무부하매연측정치
9   NOLOD_AIR_EXCRT_MEVLU  무부하공기과잉률측정치
10         NOLOD_HC_MEVLU   무부하탄화수소측정치
11        NOLOD_COX_MEVLU  무부하일산화탄소측정치
12          OVHUL_RCPT_NO       정비접수번호
13   SPCY_OVHUL_BIZPLC_NM     전문정비사업소명
14  PRCINSP_RINSP_RCPT_NO    정밀재검사접수번호
15              OVHUL_YMD         정비일자

### 데이터 info

In [232]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,LOAD_CO,부하일산화탄소측정치,53884,LOD_COX_MEVLU,부하일산화탄소측정치,53884.0,0.0,733,733.0
1,CAR_SER_NO,차대번호,51051,VIN,차대번호,51051.0,0.0,3566,3566.0
2,CAR_REG_NO,차량등록번호,54617,VHRNO,차량관리번호,54617.0,0.0,0,0.0
3,CAR_MILE,주행거리,54617,DRVNG_DSTNC,주행거리,54617.0,0.0,0,0.0
4,LOAD_HC,부하탄화수소측정치,53886,LOD_HC_MEVLU,부하탄화수소측정치,53886.0,0.0,731,731.0

### [출력] 컬럼명, 결측치 통계

In [304]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### [분석]

#### 차대번호

In [233]:
len(odf2['CAR_SER_NO'].unique()), len(sdf2['VIN'].unique())

(43771, 43770)

In [234]:
len(set(odf2['CAR_SER_NO'].unique()) - set(sdf2['VIN'].unique()))

14

In [235]:
set(odf2['CAR_SER_NO'].unique()) - set(sdf2['VIN'].unique())

{'110244230031 ',
 '269911305321 ',
 '280042206875 ',
 '280242208147 ',
 '289634200065 ',
 '410042131770 ',
 '410042232119 ',
 '410142234477 ',
 '410242235271 ',
 '440034310415 ',
 '449734294125 ',
 '449934294746 ',
 '449934394840 ',
 '480134235443 '}

#### 차량관리번호

In [236]:
len(odf2['CAR_REG_NO'].unique())

46780

In [237]:
len(sdf2['VHRNO'].unique())

46780

In [238]:
len(set(odf2['CAR_REG_NO'].unique()) - set(sdf2['VHRNO'].unique()))

0

## 24\. 전문정비상세(TB_ERR_RES_DET)

In [216]:
name = 'TB_ERR_RES_DET'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

24 8
(106818, 24) (106818, 8)

In [217]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS    24  106818
STD     8  106818

### 컬럼 확인

In [218]:
odf.columns.to_list()

['REPAIR_ORG_NM',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'REPAIR_DATE',
 'REPAIR_REG_NO',
 'RE_SMO_CHK_REG_NO',
 'REPAIR_PART_CD',
 'REPAIR_CONT_CD',
 'REPAIR_PART1_YN',
 'REPAIR_PART2_YN',
 'REPAIR_PART3_YN',
 'REPAIR_PART4_YN',
 'REC_DATE',
 'REC_NM',
 'LAS_CHG_DATE',
 'LAS_CHG_NM',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'ETC_CONT4',
 'ETC_CONT5',
 'SRC_TBL',
 'FILE_NM',
 'JOB_DATE']

In [219]:
olist = [
    'CAR_REG_NO',
    'CAR_SER_NO',
    'RE_SMO_CHK_REG_NO',
    'REPAIR_REG_NO',
    'REPAIR_DATE',
    'REPAIR_ORG_NM',
    'REPAIR_PART_CD',
    'REPAIR_CONT_CD',

    'REPAIR_PART1_YN',
    'REPAIR_PART2_YN',
    'REPAIR_PART3_YN',
    'REPAIR_PART4_YN',
    'REC_DATE',
    'REC_NM',
    'LAS_CHG_DATE',
    'LAS_CHG_NM',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'ETC_CONT4',
    'ETC_CONT5',
    'SRC_TBL',
    'FILE_NM',
    'JOB_DATE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차량번호',
    '차대번호',
    '정밀재검사접수번호',
    '전문정비접수번호',
    '전문정비일',
    '전문정비업소명',
    '정비부품코드',
    '정비내용코드',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

ocol = pd.DataFrame(odict)
ocol

                   컬럼         내용
0          CAR_REG_NO       차량번호
1          CAR_SER_NO       차대번호
2   RE_SMO_CHK_REG_NO  정밀재검사접수번호
3       REPAIR_REG_NO   전문정비접수번호
4         REPAIR_DATE      전문정비일
5       REPAIR_ORG_NM    전문정비업소명
6      REPAIR_PART_CD     정비부품코드
7      REPAIR_CONT_CD     정비내용코드
8     REPAIR_PART1_YN         미정
9     REPAIR_PART2_YN         미정
10    REPAIR_PART3_YN         미정
11    REPAIR_PART4_YN         미정
12           REC_DATE         미정
13             REC_NM         미정
14       LAS_CHG_DATE         미정
15         LAS_CHG_NM         미정
16          ETC_CONT1         미정
17          ETC_CONT2         미정
18          ETC_CONT3         미정
19          ETC_CONT4         미정
20          ETC_CONT5         미정
21            SRC_TBL         미정
22            FILE_NM         미정
23           JOB_DATE         미정

In [220]:
sdf.columns.to_list()

['VHRNO',
 'VIN',
 'OVHUL_CN',
 'OVHUL_YMD',
 'SPCY_OVHUL_BIZPLC_NM',
 'OVHUL_CMPNT_NM',
 'OVHUL_RCPT_NO',
 'PRCINSP_RINSP_RCPT_NO']

In [221]:
slist = [
    'VHRNO', # VHCL_MNG_NO
    'VIN',
    'PRCINSP_RINSP_RCPT_NO', 
    'OVHUL_RCPT_NO',
    'OVHUL_YMD',
    'SPCY_OVHUL_BIZPLC_NM',
    'OVHUL_CMPNT_NM',
    'OVHUL_CN',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차량관리번호',
    '차대번호',
    '정밀재검사접수번호', 
    '정비접수번호',
    '전문정비일',
    '전문정비사업소명',
    '정비부품명',
    '정비내용',]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼         내용
0                  VHRNO     차량관리번호
1                    VIN       차대번호
2  PRCINSP_RINSP_RCPT_NO  정밀재검사접수번호
3          OVHUL_RCPT_NO     정비접수번호
4              OVHUL_YMD      전문정비일
5   SPCY_OVHUL_BIZPLC_NM   전문정비사업소명
6         OVHUL_CMPNT_NM      정비부품명
7               OVHUL_CN       정비내용

### 데이터 info

In [222]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CAR_REG_NO,차량번호,106818,VHRNO,차량관리번호,106818.0,0.0,0,0.0
1,CAR_SER_NO,차대번호,94670,VIN,차대번호,94670.0,0.0,12148,12148.0
2,RE_SMO_CHK_REG_NO,정밀재검사접수번호,0,PRCINSP_RINSP_RCPT_NO,정밀재검사접수번호,0.0,0.0,106818,106818.0
3,REPAIR_REG_NO,전문정비접수번호,106818,OVHUL_RCPT_NO,정비접수번호,106818.0,0.0,0,0.0
4,REPAIR_DATE,전문정비일,106818,OVHUL_YMD,전문정비일,106818.0,0.0,0,0.0

### [출력] 컬럼명, 결측치 통계

In [312]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

### [분석]

#### 차대번호

In [223]:
len(odf2['CAR_SER_NO'].unique()), len(sdf2['VIN'].unique())

(40927, 40927)

In [224]:
len(set(odf2['CAR_SER_NO'].unique()) - set(sdf2['VIN'].unique()))

13

In [225]:
set(odf2['CAR_SER_NO'].unique()) - set(sdf2['VIN'].unique())

{'110244230031 ',
 '269911305321 ',
 '280042206875 ',
 '280242208147 ',
 '289634200065 ',
 '410042131770 ',
 '410042232119 ',
 '410142234477 ',
 '410242235271 ',
 '440034310415 ',
 '449734294125 ',
 '449934294746 ',
 '480134235443 '}

#### 차량관리번호

In [213]:
len(odf2['CAR_REG_NO'].unique())

46133

In [214]:
len(sdf2['VHRNO'].unique())

46133

In [ ]:
len(set(odf2['CAR_REG_NO'].unique()) - set(sdf2['VHRNO'].unique()))

0

## 25\. 정기검사 검사정보(TB_JGT_HIS)
- [⭕] ODS, STD 없음

In [5]:
# about 10m 10s
name = 'TB_JGT_HIS'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

63 48
(22006426, 63) (21863532, 48)

In [6]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수       행_수
ODS    63  22006426
STD    48  21863532

### 컬럼 확인

In [7]:
odf.columns.to_list()

['JG_ORG_NM',
 'JG_CHK_DATE',
 'JG_CHK_TYPE',
 'JEBSU_NO',
 'TO_JEBSU_NO',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'CAR_TYPE',
 'CAR_NM',
 'CAR_TYPE_NM',
 'USAGE',
 'CAR_YEAR',
 'CAR_FUEL_NM',
 'CAR_MILE',
 'CAR_LENGTH',
 'CAR_WIDTH',
 'CAR_HEIGHT',
 'ENGINE_TYPE',
 'ENGINE_CAPACITY',
 'ENGINE_POWER',
 'CAR_WEIGHT',
 'TOT_WEIGHT',
 'CAR_PASSENGER',
 'CONT',
 'FIRST_REG_DATE',
 'MAKE_DATE',
 'EXP_DATE',
 'FUN_JUDGE_YN',
 'FUN_FAIL_ITEM',
 'CHK_METHOD',
 'UNLOAD_SMO_VAL1',
 'UNLOAD_SMO_LIM1',
 'UNLOAD_SMO_JUDGE1',
 'UNLOAD_SMO_VAL2',
 'UNLOAD_SMO_LIM2',
 'UNLOAD_SMO_JUDGE2',
 'UNLOAD_SMO_VAL3',
 'UNLOAD_SMO_LIM3',
 'UNLOAD_SMO_JUDGE3',
 'UNLOAD_SMO_VAL4',
 'UNLOAD_SMO_LIM4',
 'UNLOAD_SMO_JUDGE4',
 'UNLOAD_SMO_VAL5',
 'UNLOAD_SMO_LIM5',
 'UNLOAD_SMO_JUDGE5',
 'UNLOAD_SMO_VAL6',
 'UNLOAD_SMO_LIM6',
 'UNLOAD_SMO_JUDGE6',
 'CO2_VAL',
 'ENGINE_TOR_LIM',
 'ENGINE_TOR_VAL',
 'O2_VAL',
 'AIR_TEMPER',
 'AIR_PRESS',
 'JUDGE_YN',
 'RE_CHK_DATE',
 'CHK_EXP_DATE',
 'FUN_CHKR_NM',
 'SMO_CHKR_NM',
 'MNG_CHKR_NM',
 'JUDGE_DATE',
 'DT_GUBUN',
 'FILE_NM']

In [8]:
olist = [
    'CAR_FUEL_NM',
    'CAR_MILE',
    'CAR_NM',
    'CAR_REG_NO',
    'CAR_SER_NO',
    'CAR_TYPE_NM',
    'CAR_YEAR',
    'CHK_METHOD',
    'CO2_VAL',
    'ENGINE_TOR_LIM',
    'ENGINE_TOR_VAL',
    'ENGINE_TYPE',
    'JEBSU_NO',
    'JG_CHK_DATE',
    'JG_CHK_TYPE',
    'JG_ORG_NM',
    'JUDGE_DATE',
    'JUDGE_YN',
    'O2_VAL',
    'RE_CHK_DATE',
    'UNLOAD_SMO_JUDGE1',
    'UNLOAD_SMO_JUDGE2',
    'UNLOAD_SMO_JUDGE3',
    'UNLOAD_SMO_JUDGE4',
    'UNLOAD_SMO_JUDGE5',
    'UNLOAD_SMO_JUDGE6',
    'UNLOAD_SMO_LIM1',
    'UNLOAD_SMO_LIM2',
    'UNLOAD_SMO_LIM3',
    'UNLOAD_SMO_LIM4',
    'UNLOAD_SMO_LIM5',
    'UNLOAD_SMO_LIM6',
    'UNLOAD_SMO_VAL1',
    'UNLOAD_SMO_VAL2',
    'UNLOAD_SMO_VAL3',
    'UNLOAD_SMO_VAL4',
    'UNLOAD_SMO_VAL5',
    'UNLOAD_SMO_VAL6',
    'USAGE',
    'EXP_DATE',
    'CHK_EXP_DATE',

    'TO_JEBSU_NO',
    'CAR_TYPE',
    'CAR_LENGTH',
    'CAR_WIDTH',
    'CAR_HEIGHT',
    'ENGINE_CAPACITY',
    'ENGINE_POWER',
    'CAR_WEIGHT',
    'TOT_WEIGHT',
    'CAR_PASSENGER',
    'CONT',
    'FIRST_REG_DATE',
    'MAKE_DATE',
    'FUN_JUDGE_YN',
    'FUN_FAIL_ITEM',
    'AIR_TEMPER',
    'AIR_PRESS',
    'FUN_CHKR_NM',
    'SMO_CHKR_NM',
    'MNG_CHKR_NM',
    'DT_GUBUN',
    'FILE_NM',  
    ]

odict = {
    '컬럼':olist,
    '내용':
    [
    '사용연료',
    '주행거리',
    '차명',
    '차량번호',
    '차대번호',
    '차종',
    '차량연식',
    '검사방법',
    '이산화탄소값',
    '최대출력허용치',
    '최대출력측정값',
    '엔진형식',
    '검사접수번호',
    '정기검사일자',
    '검사종류',
    '검사소명',
    '검사판정시각',
    '정기검사판정',
    '산소값',
    '재검사기간',
    '무부하매연판정1',
    '무부하매연판정2',
    '무부하매연판정3',
    '무부하매연판정4',
    '무부하매연판정5',
    '무부하매연판정6',
    '무부하매연허용치1',
    '무부하매연허용치2',
    '무부하매연허용치3',
    '무부하매연허용치4',
    '무부하매연허용치5',
    '무부하매연허용치6',
    '무부하매연측정치1',
    '무부하매연측정치2',
    '무부하매연측정치3',
    '무부하매연측정치4',
    '무부하매연측정치5',
    '무부하매연측정치6',
    '차량용도',
    '검사전유효기간만료일',
    '검사유효기간',

    'TO_JEBSU_NO',
    'CAR_TYPE',
    'CAR_LENGTH',
    'CAR_WIDTH',
    'CAR_HEIGHT',
    'ENGINE_CAPACITY',
    'ENGINE_POWER',
    'CAR_WEIGHT',
    'TOT_WEIGHT',
    'CAR_PASSENGER',
    'CONT',
    'FIRST_REG_DATE',
    'MAKE_DATE',
    'FUN_JUDGE_YN',
    'FUN_FAIL_ITEM',
    'AIR_TEMPER',
    'AIR_PRESS',
    'FUN_CHKR_NM',
    'SMO_CHKR_NM',
    'MNG_CHKR_NM',
    'DT_GUBUN',
    'FILE_NM', 
    ]
    }

ocol = pd.DataFrame(odict)
ocol

             컬럼    내용
0   CAR_FUEL_NM  사용연료
1      CAR_MILE  주행거리
2        CAR_NM    차명
3    CAR_REG_NO  차량번호
4    CAR_SER_NO  차대번호
..          ...   ...
58  FUN_CHKR_NM    미정
59  SMO_CHKR_NM    미정
60  MNG_CHKR_NM    미정
61     DT_GUBUN    미정
62      FILE_NM    미정

[63 rows x 2 columns]

In [9]:
sdf.columns.to_list()

['FDRM_DRVNG_DSTNC',
 'FUEL_CD',
 'SMO_CODE',
 'VHCTY_CD',
 'VHCTY_TY_CD2',
 'VHCTY_CL_CD',
 'VHCNM',
 'VHRNO',
 'VIN',
 'VHCTY_TY_CD1',
 'MODL_YR',
 'FDRM_INSP_INSP_MTHD_CD',
 'FDRM_INSP_CO2_VAL',
 'FDRM_MAXM_OTPT_PRMVL',
 'FDRM_MAXM_OTPT_MSTVL',
 'FDRM_INSP_EGIN_TY',
 'INSP_RCPT_NO',
 'FDRM_INSP_YMD',
 'FDRM_INSP_KND_CD',
 'INSPOF_NM',
 'INSP_RSLT_JGMT_TM',
 'FDRM_INSP_JGMT',
 'FDRM_INSP_O2_VAL',
 'FDRM_INSP_RINSP_WHL',
 'FDRM_NLOD_SMO_JT_YN1',
 'FDRM_NLOD_SMO_JT_YN2',
 'FDRM_NLOD_SMO_JT_YN3',
 'FDRM_NLOD_SMO_JT_YN4',
 'FDRM_NLOD_SMO_JT_YN5',
 'FDRM_NLOD_SMO_JT_YN6',
 'FDRM_NLOD_SMO_PRMVL1',
 'FDRM_NLOD_SMO_PRMVL2',
 'FDRM_NLOD_SMO_PRMVL3',
 'FDRM_NLOD_SMO_PRMVL4',
 'FDRM_NLOD_SMO_PRMVL5',
 'FDRM_NLOD_SMO_PRMVL6',
 'FDRM_NLOD_SMO_MSTVL1',
 'FDRM_NLOD_SMO_MSTVL2',
 'FDRM_NLOD_SMO_MSTVL3',
 'FDRM_NLOD_SMO_MSTVL4',
 'FDRM_NLOD_SMO_MSTVL5',
 'FDRM_NLOD_SMO_MSTVL6',
 'FDRM_VHCL_PURPS_CD',
 'FDRM_BF_VDWL_EXPRYDY',
 'FNCINSP_JGMT_YN',
 'AIR_TMPRT',
 'AIR_PSSR',
 'INSP_AFTR_UPDT_EXPRY']

In [10]:
slist = [
    'FUEL_CD',
    'FDRM_DRVNG_DSTNC',
    'VHCNM',
    'VHRNO',
    'VIN',
    'VHCTY_TY_CD1',
    'MODL_YR',
    'FDRM_INSP_INSP_MTHD_CD',
    'FDRM_INSP_CO2_VAL',
    'FDRM_MAXM_OTPT_PRMVL',
    'FDRM_MAXM_OTPT_MSTVL',
    'FDRM_INSP_EGIN_TY',
    'INSP_RCPT_NO',
    'FDRM_INSP_YMD',
    'FDRM_INSP_KND_CD',
    'INSPOF_NM',
    'INSP_RSLT_JGMT_TM',
    'FDRM_INSP_JGMT',
    'FDRM_INSP_O2_VAL',
    'FDRM_INSP_RINSP_WHL',
    'FDRM_NLOD_SMO_JT_YN1',
    'FDRM_NLOD_SMO_JT_YN2',
    'FDRM_NLOD_SMO_JT_YN3',
    'FDRM_NLOD_SMO_JT_YN4',
    'FDRM_NLOD_SMO_JT_YN5',
    'FDRM_NLOD_SMO_JT_YN6',
    'FDRM_NLOD_SMO_PRMVL1',
    'FDRM_NLOD_SMO_PRMVL2',
    'FDRM_NLOD_SMO_PRMVL3',
    'FDRM_NLOD_SMO_PRMVL4',
    'FDRM_NLOD_SMO_PRMVL5',
    'FDRM_NLOD_SMO_PRMVL6',
    'FDRM_NLOD_SMO_MSTVL1',
    'FDRM_NLOD_SMO_MSTVL2',
    'FDRM_NLOD_SMO_MSTVL3',
    'FDRM_NLOD_SMO_MSTVL4',
    'FDRM_NLOD_SMO_MSTVL5',
    'FDRM_NLOD_SMO_MSTVL6',
    'FDRM_VHCL_PURPS_CD',
    'FDRM_BF_VDWL_EXPRYDY',

    'SMO_CODE',
    'VHCTY_CD',
    'VHCTY_TY_CD2',
    'VHCTY_CL_CD',
    'FNCINSP_JGMT_YN',
    'AIR_TMPRT',
    'AIR_PSSR',
    'INSP_AFTR_UPDT_EXPRY', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['연료코드',
    '정기검사주행거리',
    '차명',
    '자동차등록번호',
    '차대번호',
    '차종유형코드1',
    '모델연도',
    '정기검사검사방법',
    '정기검사이산화탄소값',
    '정기검사최대출력허용값',
    '정기검사최대출력측정값',
    '정기검사엔진형식',
    '검사접수번호',
    '정기검사일자',
    '정기검사종류코드',
    '검사소명',
    '검사결과판정시각',
    '정기검사판정',
    '정기검사산소값',
    '정기검사재검사기간',
    '정기검사무부하매연판정여부1',
    '정기검사무부하매연판정여부2',
    '정기검사무부하매연판정여부3',
    '정기검사무부하매연판정여부4',
    '정기검사무부하매연판정여부5',
    '정기검사무부하매연판정여부6',
    '정기검사무부하매연허용값1',
    '정기검사무부하매연허용값2',
    '정기검사무부하매연허용값3',
    '정기검사무부하매연허용값4',
    '정기검사무부하매연허용값5',
    '정기검사무부하매연허용값6',
    '정기검사무부하매연측정값1', 
    '정기검사무부하매연측정값2',
    '정기검사무부하매연측정값3',
    '정기검사무부하매연측정값4',
    '정기검사무부하매연측정값5',
    '정기검사무부하매연측정값6',
    '차량용도코드', 
    '정기검사전유효기간만료일',

    'SMO_CODE',
    'VHCTY_CD',
    'VHCTY_TY_CD2',
    'VHCTY_CL_CD',
    'FNCINSP_JGMT_YN',
    'AIR_TMPRT',
    'AIR_PSSR',
    'INSP_AFTR_UPDT_EXPRY',
    ]
    }

scol = pd.DataFrame(sdict)
scol

                        컬럼              내용
0                  FUEL_CD            연료코드
1         FDRM_DRVNG_DSTNC        정기검사주행거리
2                    VHCNM              차명
3                    VHRNO         자동차등록번호
4                      VIN            차대번호
5             VHCTY_TY_CD1         차종유형코드1
6                  MODL_YR            모델연도
7   FDRM_INSP_INSP_MTHD_CD        정기검사검사방법
8        FDRM_INSP_CO2_VAL      정기검사이산화탄소값
9     FDRM_MAXM_OTPT_PRMVL     정기검사최대출력허용값
10    FDRM_MAXM_OTPT_MSTVL     정기검사최대출력측정값
11       FDRM_INSP_EGIN_TY        정기검사엔진형식
12            INSP_RCPT_NO          검사접수번호
13           FDRM_INSP_YMD          정기검사일자
14        FDRM_INSP_KND_CD        정기검사종류코드
15               INSPOF_NM            검사소명
16       INSP_RSLT_JGMT_TM        검사결과판정시각
17          FDRM_INSP_JGMT          정기검사판정
18        FDRM_INSP_O2_VAL         정기검사산소값
19     FDRM_INSP_RINSP_WHL       정기검사재검사기간
20    FDRM_NLOD_SMO_JT_YN1  정기검사무부하매연판정여부1
21    FDRM_NLOD_SMO_JT_YN2  정기검사무부하매연판정여부2
22    FDRM_NLOD_SMO_JT_YN3  정기검사무부하매연판정여부3
23    FDRM_NLOD_SMO_JT_YN4  정기검사무부하매연판정여부4
24    FDRM_NLOD_SMO_JT_YN5  정기검사무부하매연판정여부5
25    FDRM_NLOD_SMO_JT_YN6  정기검사무부하매연판정여부6
26    FDRM_NLOD_SMO_PRMVL1   정기검사무부하매연허용값1
27    FDRM_NLOD_SMO_PRMVL2   정기검사무부하매연허용값2
28    FDRM_NLOD_SMO_PRMVL3   정기검사무부하매연허용값3
29    FDRM_NLOD_SMO_PRMVL4   정기검사무부하매연허용값4
30    FDRM_NLOD_SMO_PRMVL5   정기검사무부하매연허용값5
31    FDRM_NLOD_SMO_PRMVL6   정기검사무부하매연허용값6
32    FDRM_NLOD_SMO_MSTVL1   정기검사무부하매연측정값1
33    FDRM_NLOD_SMO_MSTVL2   정기검사무부하매연측정값2
34    FDRM_NLOD_SMO_MSTVL3   정기검사무부하매연측정값3
35    FDRM_NLOD_SMO_MSTVL4   정기검사무부하매연측정값4
36    FDRM_NLOD_SMO_MSTVL5   정기검사무부하매연측정값5
37    FDRM_NLOD_SMO_MSTVL6   정기검사무부하매연측정값6
38      FDRM_VHCL_PURPS_CD          차량용도코드
39    FDRM_BF_VDWL_EXPRYDY    정기검사전유효기간만료일
40                SMO_CODE              미정
41                VHCTY_CD              미정
42            VHCTY_TY_CD2              미정
43             VHCTY_CL_CD              미정
44         FNCINSP_JGMT_YN              미정
45               AIR_TMPRT              미정
46                AIR_PSSR              미정
47    INSP_AFTR_UPDT_EXPRY              미정

### 데이터 info

In [11]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CAR_FUEL_NM,사용연료,21840008,FUEL_CD,연료코드,21698399.00,141609.00,166418,165133.00
1,CAR_MILE,주행거리,21969980,FDRM_DRVNG_DSTNC,정기검사주행거리,21827293.00,142687.00,36446,36239.00
2,CAR_NM,차명,22006426,VHCNM,차명,21863532.00,142894.00,0,0.00
3,CAR_REG_NO,차량번호,22006426,VHRNO,자동차등록번호,21863532.00,142894.00,0,0.00
4,CAR_SER_NO,차대번호,22006426,VIN,차대번호,21863532.00,142894.00,0,0.00

### [출력] 컬럼명, 결측치 통계

In [12]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

[정제]TB_JGT_HIS.xlsx 출력완료.

## 26\. 정기검사 검사소정보(TB_JGT_VIO)

In [313]:
name = 'TB_JGT_VIO'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

4 4
(1961, 4) (1961, 4)

In [314]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS     4  1961
STD     4  1961

### 컬럼 확인

In [315]:
odf.columns.to_list()

['VIO_CD', 'VIO_NM', 'VIO_TYPE', 'SIDO_NM']

In [316]:
olist = [
    'SIDO_NM', 
    'VIO_TYPE', 
    'VIO_CD', 
    'VIO_NM', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['시도명', 
    '검사소구분', 
    '검사소코드', 
    '검사소명', ]
    }

ocol = pd.DataFrame(odict)
ocol

         컬럼     내용
0   SIDO_NM    시도명
1  VIO_TYPE  검사소구분
2    VIO_CD  검사소코드
3    VIO_NM   검사소명

In [317]:
sdf.columns.to_list()

['CTPV_NM', 'FDRM_INSP_INSPOF_CD', 'INSPOF_SE_CD', 'INSPOF_NM']

In [318]:
slist = [
    'CTPV_NM', 
    'INSPOF_SE_CD', 
    'FDRM_INSP_INSPOF_CD', 
    'INSPOF_NM', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['시도명', 
    '검사소구분코드', 
    '정기검사검사소코드', 
    '검사소명', ]
    }

scol = pd.DataFrame(sdict)
scol

                    컬럼         내용
0              CTPV_NM        시도명
1         INSPOF_SE_CD    검사소구분코드
2  FDRM_INSP_INSPOF_CD  정기검사검사소코드
3            INSPOF_NM       검사소명

### 데이터 info

In [319]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,SIDO_NM,시도명,1961,CTPV_NM,시도명,1961,0,0,0
1,VIO_TYPE,검사소구분,1961,INSPOF_SE_CD,검사소구분코드,1961,0,0,0
2,VIO_CD,검사소코드,1961,FDRM_INSP_INSPOF_CD,정기검사검사소코드,1961,0,0,0
3,VIO_NM,검사소명,1961,INSPOF_NM,검사소명,1961,0,0,0

### [출력] 컬럼명, 결측치 통계

In [320]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

## 27\. 자동차 검사소정보(TB_MECAR_VIO)

In [321]:
name = 'TB_MECAR_VIO'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

28 4
(1045, 28) (1045, 4)

In [322]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    28  1045
STD     4  1045

### 컬럼 확인

In [323]:
odf.columns.to_list()

['VIO_CD',
 'VIO_NM',
 'VIO_TYPE',
 'RECV_DATE',
 'CONF_DATE',
 'BIZ_YN',
 'J_YN',
 'G_YN',
 'S_YN',
 'H_YN',
 'SIDO_CD',
 'SIGUNGU_CD',
 'SIDO_NM',
 'SIGUNGU_NM',
 'TEL_NO',
 'POST_NO',
 'ADDR1',
 'ADDR2',
 'X_COORD',
 'Y_COORD',
 'ORG_ID',
 'DO_VIO_CD',
 'KECO_S_YN',
 'REC_DATE',
 'REC_NM',
 'CHG_DATE',
 'CHG_NM',
 'T_YN']

In [324]:
olist = [
    'VIO_NM',
    'VIO_CD',
    'SIDO_NM',
    'VIO_TYPE',

    'RECV_DATE',
    'CONF_DATE',
    'BIZ_YN',
    'J_YN',
    'G_YN',
    'S_YN',
    'H_YN',
    'SIDO_CD',
    'SIGUNGU_CD',
    'SIGUNGU_NM',
    'TEL_NO',
    'POST_NO',
    'ADDR1',
    'ADDR2',
    'X_COORD',
    'Y_COORD',
    'ORG_ID',
    'DO_VIO_CD',
    'KECO_S_YN',
    'REC_DATE',
    'REC_NM',
    'CHG_DATE',
    'CHG_NM',
    'T_YN', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['검사소명',
    '검사소코드',
    '시도명',
    '검사소구분',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

            컬럼     내용
0       VIO_NM   검사소명
1       VIO_CD  검사소코드
2      SIDO_NM    시도명
3     VIO_TYPE  검사소구분
4    RECV_DATE     미정
5    CONF_DATE     미정
6       BIZ_YN     미정
7         J_YN     미정
8         G_YN     미정
9         S_YN     미정
10        H_YN     미정
11     SIDO_CD     미정
12  SIGUNGU_CD     미정
13  SIGUNGU_NM     미정
14      TEL_NO     미정
15     POST_NO     미정
16       ADDR1     미정
17       ADDR2     미정
18     X_COORD     미정
19     Y_COORD     미정
20      ORG_ID     미정
21   DO_VIO_CD     미정
22   KECO_S_YN     미정
23    REC_DATE     미정
24      REC_NM     미정
25    CHG_DATE     미정
26      CHG_NM     미정
27        T_YN     미정

In [325]:
sdf.columns.to_list()

['STDG_CTPV_NM', 'MECAR_INSPOF_CD', 'INSPOF_NM', 'INSPOF_SE_CD']

In [326]:
slist = [
    'INSPOF_NM', 
    'MECAR_INSPOF_CD', 
    'STDG_CTPV_NM', 
    'INSPOF_SE_CD', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['검사소명', 
    'MECAR검사소코드', 
    '법정동시도명', 
    '검사소구분코드', ]
    }

scol = pd.DataFrame(sdict)
scol

                컬럼          내용
0        INSPOF_NM        검사소명
1  MECAR_INSPOF_CD  MECAR검사소코드
2     STDG_CTPV_NM      법정동시도명
3     INSPOF_SE_CD     검사소구분코드

### 데이터 info

In [327]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,VIO_NM,검사소명,1045,INSPOF_NM,검사소명,1045.0,0.0,0,0.0
1,VIO_CD,검사소코드,1045,MECAR_INSPOF_CD,MECAR검사소코드,1045.0,0.0,0,0.0
2,SIDO_NM,시도명,1045,STDG_CTPV_NM,법정동시도명,1045.0,0.0,0,0.0
3,VIO_TYPE,검사소구분,1045,INSPOF_SE_CD,검사소구분코드,1045.0,0.0,0,0.0
4,RECV_DATE,미정,134,NaN,NaN,NaN,NaN,911,NaN

### [출력] 컬럼명, 결측치 통계

In [328]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

## 28\. RSD 수시점검(TB_RSD_FINAL)
- [⭕] ODS 없음

In [14]:
name = 'TB_RSD_FINAL'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

74 30
(13318300, 74) (13297620, 30)

In [15]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수       행_수
ODS    74  13318300
STD    30  13297620

### 컬럼 확인

In [16]:
odf.columns.to_list()

['IDX',
 'UNIT',
 'SITECODE',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'RSD_DATE',
 'RSD_TIME',
 'CO',
 'PPMHC',
 'PPMNO',
 'CAR_NM',
 'USAGE',
 'CAR_TYPE_NM',
 'CAR_YEAR',
 'CAR_FUEL_NM',
 'CAR_WEIGHT',
 'TOT_WEIGHT',
 'ENGINE_CAPACITY',
 'ENGINE_POWER',
 'FIRST_REG_DATE',
 'MAKE_REG_DATE',
 'SMO_CHK_EXP_DATE',
 'SPEED',
 'ACCEL',
 'VSP',
 'UVSMOKE',
 'FILE_NM',
 'IRSMOKE',
 'SMO_CHK_METHOD',
 'UNLOAD_SMO_LIM1',
 'UNLOAD_SMO_VAL1',
 'UNLOAD_SMO_LIM2',
 'UNLOAD_SMO_VAL2',
 'UNLOAD_SMO_LIM3',
 'UNLOAD_SMO_VAL3',
 'UNLOAD_SMO_LIM4',
 'UNLOAD_SMO_VAL4',
 'UNLOAD_SMO_LIM5',
 'UNLOAD_SMO_VAL5',
 'UNLOAD_SMO_LIM6',
 'UNLOAD_SMO_VAL6',
 'SIDO',
 'SIGUNGU',
 'REG_REGION',
 'RSD_MONTH',
 'RSD_FILE_NM',
 'STD_TAG',
 'USAGE_EX',
 'CAR_TYPE_CD',
 'USAGE_CD',
 'CAR_FUEL_CD',
 'SMO_CHK_CD',
 'STD_TAG2',
 'IMAGENAME',
 'LAST_CHK_EXP_DATE',
 'PPMHCHEX',
 'SAMPLES',
 'REC_DATE',
 'CONF_YN',
 'CONF_FLAG',
 'SELECTION_DATE',
 'SELECTION_USER',
 'CONFIRM_DATE',
 'CONFIRM_USER',
 'SIDO_CD',
 'SIGUNGU_CD',
 'SIDO_NM',
 'SIGUNGU_NM',
 'GE_CHK',
 'ENGINE_TYPE',
 'SRC_REG_NO',
 'OPACITYMAX',
 'UNIT_GB',
 'PPM_NO2']

In [17]:
olist = [
    'ACCEL',
    'CAR_FUEL_NM',
    'CAR_REG_NO',
    'CAR_SER_NO',
    'CAR_WEIGHT',
    'CAR_YEAR',
    'CO',
    'ENGINE_TYPE',
    'GE_CHK',
    'IRSMOKE',
    'OPACITYMAX',
    'PPMHC',
    'PPMHCHEX',
    'PPMNO',
    'PPM_NO2',
    'RSD_DATE',
    'RSD_TIME',
    'SIDO_NM',
    'SIGUNGU_NM',
    'SITECODE',
    'SPEED',
    'UNIT',
    'UNIT_GB',
    'USAGE_EX',
    'UVSMOKE',
    'VSP',

    'IDX',
    'CAR_NM',
    'USAGE',
    'CAR_TYPE_NM',
    'TOT_WEIGHT',
    'ENGINE_CAPACITY',
    'ENGINE_POWER',
    'FIRST_REG_DATE',
    'MAKE_REG_DATE',
    'SMO_CHK_EXP_DATE',
    'FILE_NM',
    'SMO_CHK_METHOD',
    'UNLOAD_SMO_LIM1',
    'UNLOAD_SMO_VAL1',
    'UNLOAD_SMO_LIM2',
    'UNLOAD_SMO_VAL2',
    'UNLOAD_SMO_LIM3',
    'UNLOAD_SMO_VAL3',
    'UNLOAD_SMO_LIM4',
    'UNLOAD_SMO_VAL4',
    'UNLOAD_SMO_LIM5',
    'UNLOAD_SMO_VAL5',
    'UNLOAD_SMO_LIM6',
    'UNLOAD_SMO_VAL6',
    'SIDO',
    'SIGUNGU',
    'REG_REGION',
    'RSD_MONTH',
    'RSD_FILE_NM',
    'STD_TAG',
    'CAR_TYPE_CD',
    'USAGE_CD',
    'CAR_FUEL_CD',
    'SMO_CHK_CD',
    'STD_TAG2',
    'IMAGENAME',
    'LAST_CHK_EXP_DATE',
    'SAMPLES',
    'REC_DATE',
    'CONF_YN',
    'CONF_FLAG',
    'SELECTION_DATE',
    'SELECTION_USER',
    'CONFIRM_DATE',
    'CONFIRM_USER',
    'SIDO_CD',
    'SIGUNGU_CD',
    'SRC_REG_NO',
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['엑셀',
    '차량연료',
    '차량번호',
    '차대번호',
    '공차중량',
    '모델연도',
    '일산화탄소측정치',
    '엔진형식',
    '과다구분',
    'IRSMOKE',
    '최대 불투명도(매연측정값)',
    'HC측정치',
    'PPMHCHEX',
    'NOX측정치',
    'PPM_NO2',
    '측정일자',
    '측정시각',
    '법정동 시도명',
    '법정동시군구명',
    '측정위치코드',
    '차량현재속도',
    '장비코드',
    '측정기구분',
    '용도명칭',
    '매연측정치',
    'VSP',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    ]
    }

ocol = pd.DataFrame(odict)
ocol

              컬럼    내용
0          ACCEL    엑셀
1    CAR_FUEL_NM  차량연료
2     CAR_REG_NO  차량번호
3     CAR_SER_NO  차대번호
4     CAR_WEIGHT  공차중량
..           ...   ...
69  CONFIRM_DATE    미정
70  CONFIRM_USER    미정
71       SIDO_CD    미정
72    SIGUNGU_CD    미정
73    SRC_REG_NO    미정

[74 rows x 2 columns]

In [18]:
sdf.columns.to_list()

['VHCL_ACCLL',
 'FUEL_CD',
 'VHRNO',
 'VIN',
 'EMPV_WGHT',
 'MODL_YR',
 'COX_MEVLU',
 'EGIN_TY',
 'CTINU_EXCVE_SE',
 'IR_INSP_SMO_VAL',
 'SMO_MSRMT_MAXM_UCRVL',
 'HC_MEVLU',
 'HC_HEX_MEVLU',
 'NOX_MEVLU',
 'NO2_MEVLU',
 'MSRMT_YMD',
 'MSRMT_TM',
 'STDG_CTPV_NM',
 'STDG_SGG_NM',
 'MSRMT_LOC_CD',
 'VHCL_NOW_VE',
 'EQMT_CD',
 'MSRR_SE',
 'PURPS_CD1',
 'SMO_MEVLU',
 'VSP',
 'VHCTY_CL_CD',
 'VHCTY_CD',
 'VHCTY_TY_CD2',
 'KEY']

In [19]:
slist = [
    'VHCL_ACCLL',
    'FUEL_CD',
    'VHRNO',
    'VIN',
    'EMPV_WGHT',
    'MODL_YR',
    'COX_MEVLU',
    'EGIN_TY',
    'CTINU_EXCVE_SE',
    'IR_INSP_SMO_VAL',
    'SMO_MSRMT_MAXM_UCRVL',
    'HC_MEVLU',
    'HC_HEX_MEVLU',
    'NOX_MEVLU',
    'NO2_MEVLU',
    'MSRMT_YMD',
    'MSRMT_TM',
    'STDG_CTPV_NM',
    'STDG_SGG_NM',
    'MSRMT_LOC_CD',
    'VHCL_NOW_VE',
    'EQMT_CD',
    'MSRR_SE',
    'PURPS_CD1',
    'SMO_MEVLU',
    'VSP',
    
    'VHCTY_CL_CD',
    'VHCTY_CD',
    'VHCTY_TY_CD2',
    'KEY', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차량가속도',
    '연료코드',
    '자동차등록번호',
    '차대번호',
    '공차중량',
    '모델연도',
    '일산화탄소측정치',
    '엔진형식',
    '연속과다구분',
    '적외선검사매연값',
    '매연측정최대불투명도값',
    '탄화수소측정치',
    '탄화수소육불화우라늄측정치',
    '질소산화물측정치',
    '이산화질소측정치',
    '측정일자',
    '측정시각',
    '법정동시도명',
    '법정동시군구명',
    '측정위치코드',
    '차량현재속도',
    '장비코드',
    '측정기구분',
    '용도코드1',
    '매연측정치',
    'VSP',
    
    '미정',
    '미정',
    '미정',
    '미정', 
    ]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼             내용
0             VHCL_ACCLL          차량가속도
1                FUEL_CD           연료코드
2                  VHRNO        자동차등록번호
3                    VIN           차대번호
4              EMPV_WGHT           공차중량
5                MODL_YR           모델연도
6              COX_MEVLU       일산화탄소측정치
7                EGIN_TY           엔진형식
8         CTINU_EXCVE_SE         연속과다구분
9        IR_INSP_SMO_VAL       적외선검사매연값
10  SMO_MSRMT_MAXM_UCRVL    매연측정최대불투명도값
11              HC_MEVLU        탄화수소측정치
12          HC_HEX_MEVLU  탄화수소육불화우라늄측정치
13             NOX_MEVLU       질소산화물측정치
14             NO2_MEVLU       이산화질소측정치
15             MSRMT_YMD           측정일자
16              MSRMT_TM           측정시각
17          STDG_CTPV_NM         법정동시도명
18           STDG_SGG_NM        법정동시군구명
19          MSRMT_LOC_CD         측정위치코드
20           VHCL_NOW_VE         차량현재속도
21               EQMT_CD           장비코드
22               MSRR_SE          측정기구분
23             PURPS_CD1          용도코드1
24             SMO_MEVLU          매연측정치
25                   VSP            VSP
26           VHCTY_CL_CD             미정
27              VHCTY_CD             미정
28          VHCTY_TY_CD2             미정
29                   KEY             미정

### 데이터 info

In [20]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,ACCEL,엑셀,13318300,VHCL_ACCLL,차량가속도,13297620.0,20680.0,0,0.0
1,CAR_FUEL_NM,차량연료,13318300,FUEL_CD,연료코드,13297620.0,20680.0,0,0.0
2,CAR_REG_NO,차량번호,13318300,VHRNO,자동차등록번호,13297620.0,20680.0,0,0.0
3,CAR_SER_NO,차대번호,13318300,VIN,차대번호,13297620.0,20680.0,0,0.0
4,CAR_WEIGHT,공차중량,13318300,EMPV_WGHT,공차중량,13297620.0,20680.0,0,0.0

### [출력] 컬럼명, 결측치 통계

In [21]:
with pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx') as texcel:
    ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
    scol.to_excel(texcel, sheet_name='STD_col', index=False)
    t_df.to_excel(texcel, sheet_name='shape', index=True)
    oscount.to_excel(texcel, sheet_name='count', index=False)
print(f'[정제]{name}.xlsx 출력완료.')

[정제]TB_RSD_FINAL.xlsx 출력완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_16868\1252313295.py:6: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  texcel.save()

# 코드 마지막