# Library

In [1]:
import pandas as pd
# import modin.pandas as pd
import os
import numpy as np
from tqdm import tqdm

## [load] file

In [2]:
# file path(pandas)

# ODS : D:/과업/[한국환경공단]자동차_환경_빅데이터_구축_2차/data/ODS
# STD : D:/과업/[한국환경공단]자동차_환경_빅데이터_구축_2차/data/STD

ods_path = 'D:/과업/[한국환경공단]자동차_환경_빅데이터_구축_2차/data/ODS'
std_path = 'D:/과업/[한국환경공단]자동차_환경_빅데이터_구축_2차/data/STD'

In [ ]:
# # file path(modin)

# # ODS : data/ODS
# # STD : data/STD

# ods_path = 'data/ODS'
# std_path = 'data/STD'

## 1\. [e]자동차 등록정보(CEG_CAR_MIG)
- STD_CEG_CAR_MIG_21.csv 파일 로드 오류

### [Test]파일 병합

In [6]:
# pandas : about 15 ~ 17m
# modin : about 36m

todf = pd.DataFrame()
tsdf = pd.DataFrame()

for i in tqdm(range(1, 31)):
    try:
        ods_file_name = f'ODS_CEG_CAR_MIG_{i}'
        std_file_name = f'STD_CEG_CAR_MIG_{i}'
        opath = os.path.join(ods_path, ods_file_name + '.csv')
        spath = os.path.join(std_path, std_file_name + '.csv')
        odf = pd.read_csv(opath, low_memory=False)
        sdf = pd.read_csv(spath, low_memory=False)
        todf = pd.concat([todf, odf], ignore_index=True)
        tsdf = pd.concat([tsdf, sdf], ignore_index=True)
    except:
        pass
todf.shape, tsdf.shape

100%|██████████| 30/30 [17:40<00:00, 35.34s/it]

((28534047, 32), (28415224, 25))

### [출력] 통합파일

In [7]:
# 소요시간 : 약 22m
todf.to_csv(os.path.join(ods_path, 'ODS_CEG_CAR_MIG.csv'))
tsdf.to_csv(os.path.join(std_path, 'STD_CEG_CAR_MIG.csv'))

### [로드] 통합파일

In [3]:
# # pandas :about 14m 
# # modin : 

# todf = pd.read_csv(os.path.join(ods_path, 'ODS_CEG_CAR_MIG.csv'), index_col=0)
# tsdf = pd.read_csv(os.path.join(std_path, 'STD_CEG_CAR_MIG.csv'), index_col=0)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_23520\3230808500.py:4: DtypeWarning: Columns (14,16,19,27) have mixed types. Specify dtype option on import or set low_memory=False.
  todf = pd.read_csv(os.path.join(ods_path, 'ODS_CEG_CAR_MIG.csv'), index_col=0)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_23520\3230808500.py:5: DtypeWarning: Columns (14,16,19,27) have mixed types. Specify dtype option on import or set low_memory=False.
  tsdf = pd.read_csv(os.path.join(std_path, 'STD_CEG_CAR_MIG.csv'), index_col=0)

In [4]:
t_info = {'컬럼_수':[todf.shape[1], tsdf.shape[1]], '행_수':[todf.shape[0], tsdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수       행_수
ODS    32  28534047
STD    32  28534047

### 컬럼 확인

In [50]:
todf.columns.to_list()

['VHMNO',
 'VHRNO',
 'BSPL_LEDO_CD',
 'OWNR_SE',
 'VHCTY',
 'PURPS',
 'NOW_OWNR_NM',
 'NOW_MBERNO',
 'BSPL_ADRS',
 'OWNR_ADRS',
 'VIN',
 'FST_REG_DE',
 'VHCL_YRIDNW',
 'VHCL_MNFCT_DE',
 'EMIS_INSP_EFCT_DE',
 'SRCMNNO',
 'EMIS_CRTCNO',
 'EMIS_GRD',
 'LEM_YN',
 'LEM_KND',
 'LEM_STRCHG_YN',
 'BSPL_ZIP',
 'VHRNO_NUM_INFO',
 'VHCL_ERSR_YN',
 'FST_OWNR_NM',
 'FST_MBERNO',
 'ACQS_DE',
 'ACQS_AMT',
 'RMK',
 'CRTN_DT',
 'UPDT_DT',
 'USER_ID']

In [51]:
olist = [
   'UPDT_DT', 
   'OWNR_SE', 
   'VHRNO', 
   'BSPL_LEDO_CD', 
   'CRTN_DT', 
   'PURPS', 
   'EMIS_INSP_EFCT_DE', 
   'EMIS_CRTCNO', 
   'NOW_MBERNO', 
   'ACQS_DE', 
   'ACQS_AMT', 
   'FST_MBERNO', 
   'FST_REG_DE', 
   'VHCTY', 
   'VHRNO_NUM_INFO', 
   'VHMNO', 
   'VHCL_MNFCT_DE', 
   'VHCL_YRIDNW', 
   'VHCL_ERSR_YN', 
   'VIN', 
   'SRCMNNO', 
   'EMIS_GRD', 
   'LEM_KND', 
   'LEM_STRCHG_YN', 
   'LEM_YN', 
    
   'NOW_OWNR_NM', 
   'BSPL_ADRS', 
   'OWNR_ADRS', 
   'BSPL_ZIP', 
   'FST_OWNR_NM', 
   'RMK', 
   'USER_ID', 
   ]

odict = {
    '컬럼':olist,
    '내용':
    ['수정 일시', 
   '소유자 구분', 
   '차량등록번호', 
   '본거지 법정동 코드', 
   '생성 일시', 
   '용도', 
   '배출가스검사유효일자', 
   '배출가스 인증번호', 
   '현재 회원번호', 
   '취득 일자', 
   '취득 금액', 
   '최초 회원번호', 
   '최초 등록 일자', 
   '차종', 
   '차량등록번호 숫자 정보', 
   '차량관리번호', 
   '차량 제작 일자', 
   '차량 연식', 
   '차량 말소 YN', 
   '차대번호', 
   '제원관리번호', 
   '배출가스 등급', 
   '저공해조치 종류', 
   '저공해조치 구조변경 YN', 
   '저공해조치 YN(미사용)', 
    
   '미정', 
   '미정', 
   '미정', 
   '미정', 
   '미정', 
   '미정', 
   '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                   컬럼             내용
0             UPDT_DT          수정 일시
1             OWNR_SE         소유자 구분
2               VHRNO         차량등록번호
3        BSPL_LEDO_CD     본거지 법정동 코드
4             CRTN_DT          생성 일시
5               PURPS             용도
6   EMIS_INSP_EFCT_DE     배출가스검사유효일자
7         EMIS_CRTCNO      배출가스 인증번호
8          NOW_MBERNO        현재 회원번호
9             ACQS_DE          취득 일자
10           ACQS_AMT          취득 금액
11         FST_MBERNO        최초 회원번호
12         FST_REG_DE       최초 등록 일자
13              VHCTY             차종
14     VHRNO_NUM_INFO   차량등록번호 숫자 정보
15              VHMNO         차량관리번호
16      VHCL_MNFCT_DE       차량 제작 일자
17        VHCL_YRIDNW          차량 연식
18       VHCL_ERSR_YN       차량 말소 YN
19                VIN           차대번호
20            SRCMNNO         제원관리번호
21           EMIS_GRD        배출가스 등급
22            LEM_KND       저공해조치 종류
23      LEM_STRCHG_YN  저공해조치 구조변경 YN
24             LEM_YN  저공해조치 YN(미사용)
25        NOW_OWNR_NM             미정
26          BSPL_ADRS             미정
27          OWNR_ADRS             미정
28           BSPL_ZIP             미정
29        FST_OWNR_NM             미정
30                RMK             미정
31            USER_ID             미정

In [52]:
sdf.columns.to_list()

['ACQS_AMT',
 'ACQS_YMD',
 'BSPL_STDG_CD',
 'VHCL_REG_DT',
 'EXHST_GAS_CERT_NO',
 'EXHST_GAS_GRD_CD',
 'EXTGAS_INSP_VLD_YMD',
 'FRST_MBR_NO',
 'FRST_REG_YMD',
 'LEM_KND_CD',
 'STRCT_CHG_YN',
 'LEM_YN',
 'NOW_MBR_NO',
 'VHCL_OWNR_CL_CD',
 'PURPS_CD2',
 'MANP_MNG_NO',
 'MDFCN_DT',
 'VHCL_ERSR_YN',
 'VHCL_FBCTN_YMD',
 'YRIDNW',
 'VHCTY_CD',
 'VHCL_MNG_NO',
 'VHRNO_FGRE_INFO',
 'VIN',
 'VHRNO']

In [56]:
slist = [
    'MDFCN_DT', 
    'VHCL_OWNR_CL_CD', 
    'VHRNO',
    'BSPL_STDG_CD', 
    'VHCL_REG_DT', 
    'PURPS_CD2', 
    'EXTGAS_INSP_VLD_YMD', 
    'EXHST_GAS_CERT_NO', 
    'NOW_MBR_NO', 
    'ACQS_YMD', 
    'ACQS_AMT', 
    'FRST_MBR_NO', 
    'FRST_REG_YMD', 
    'VHCTY_CD', 
    'VHRNO_FGRE_INFO', 
    'VHCL_MNG_NO', 
    'VHCL_FBCTN_YMD', 
    'YRIDNW', 
    'VHCL_ERSR_YN', 
    'VIN', 
    'MANP_MNG_NO', 
    'EXHST_GAS_GRD_CD', 
    'LEM_KND_CD', 
    'STRCT_CHG_YN', 
    'LEM_YN', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['수정일시', 
    '차량소유자분류코드', 
    '자동차등록번호',
    '본거지법정동코드', 
    '차량등록일시', 
    '용도코드2', 
    '배출가스검사유효일자', 
    '배출가스인증번호', 
    '현재회원번호', 
    '취득일자', 
    '취득금액', 
    '최초회원번호', 
    '최초등록일자', 
    '차종코드', 
    '자동차등록번호숫자정보', 
    '차량관리번호', 
    '차량제작일자', 
    '연식', 
    '차량말소여부', 
    '차대번호', 
    '제원관리번호', 
    '배출가스등급', 
    '저공해조치종류코드', 
    '구조변경여부', 
    '저공해조치여부',  ]
    }

scol = pd.DataFrame(sdict)
scol

                     컬럼           내용
0              MDFCN_DT         수정일시
1       VHCL_OWNR_CL_CD    차량소유자분류코드
2                 VHRNO      자동차등록번호
3          BSPL_STDG_CD     본거지법정동코드
4           VHCL_REG_DT       차량등록일시
5             PURPS_CD2        용도코드2
6   EXTGAS_INSP_VLD_YMD   배출가스검사유효일자
7     EXHST_GAS_CERT_NO     배출가스인증번호
8            NOW_MBR_NO       현재회원번호
9              ACQS_YMD         취득일자
10             ACQS_AMT         취득금액
11          FRST_MBR_NO       최초회원번호
12         FRST_REG_YMD       최초등록일자
13             VHCTY_CD         차종코드
14      VHRNO_FGRE_INFO  자동차등록번호숫자정보
15          VHCL_MNG_NO       차량관리번호
16       VHCL_FBCTN_YMD       차량제작일자
17               YRIDNW           연식
18         VHCL_ERSR_YN       차량말소여부
19                  VIN         차대번호
20          MANP_MNG_NO       제원관리번호
21     EXHST_GAS_GRD_CD       배출가스등급
22           LEM_KND_CD    저공해조치종류코드
23         STRCT_CHG_YN       구조변경여부
24               LEM_YN      저공해조치여부

### 데이터 info

In [57]:
odf2 = todf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = tsdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

MemoryError: Unable to allocate 4.02 GiB for an array with shape (19, 28415224) and data type object

### [출력]

In [ ]:
name = 'CEG_CAR_MIG'

In [ ]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

### 컬럼명 및 컬럼별 데이터 수 비교

In [329]:
def fuc(num):
   # 파일명, 파일경로 설정
   ods_file_name = f'ODS_CEG_CAR_MIG_{num}'
   std_file_name = f'STD_CEG_CAR_MIG_{num}'
   opath = os.path.join(ods_path, ods_file_name + '.csv')
   spath = os.path.join(std_path, std_file_name + '.csv')
   odf = pd.read_csv(opath, low_memory=False)
   sdf = pd.read_csv(spath, low_memory=False)

   # 분석
   olist = [
   'ACQS_AMT', 
   'ACQS_DE', 
   'BSPL_LEDO_CD', 
   'CRTN_DT', 
   'EMIS_CRTCNO', 
   'EMIS_GRD', 
   'EMIS_INSP_EFCT_DE', 
   'FST_MBERNO', 
   'FST_REG_DE', 
   'LEM_KND', 
   'LEM_STRCHG_YN', 
   'LEM_YN', 
   'NOW_MBERNO', 
   'OWNR_SE', 
   'PURPS', 
   'SRCMNNO', 
   'UPDT_DT', 
   'VHCL_ERSR_YN', 
   'VHCL_MNFCT_DE', 
   'VHCL_YRIDNW', 
   'VHCTY', 
   'VHMNO', 
   'VHRNO_NUM_INFO', 
   'VIN', 'VHRNO', 
   'NOW_OWNR_NM', 
   'BSPL_ADRS', 
   'OWNR_ADRS', 
   'BSPL_ZIP', 
   'FST_OWNR_NM', 
   'RMK', 
   'USER_ID'
   ]
   slist = [
   'ACQS_AMT', 
   'ACQS_YMD', 
   'BSPL_STDG_CD', 
   'VHCL_REG_DT', 
   'EXHST_GAS_CERT_NO', 
   'EXHST_GAS_GRD_CD', 
   'EXTGAS_INSP_VLD_YMD', 
   'FRST_MBR_NO', 
   'FRST_REG_YMD', 
   'LEM_KND_CD', 
   'STRCT_CHG_YN', 
   'LEM_YN', 
   'NOW_MBR_NO', 
   'VHCL_OWNR_CL_CD', 
   'PURPS_CD2', 
   'MANP_MNG_NO', 
   'MDFCN_DT', 
   'VHCL_ERSR_YN', 
   'VHCL_FBCTN_YMD', 
   'YRIDNW', 
   'VHCTY_CD', 
   'VHCL_MNG_NO', 
   'VHRNO_FGRE_INFO', 
   'VIN', 
   'VHRNO'
   ]
   odict = {
   '컬럼':olist,
   '내용':['취득금액', '취득일자', '본거지 법정동 코드', '생성 일시', '배출가스 인증번호', '배출가스 등급', '배출가스검사유효일자', '최초 회원번호', '최초 등록 일자', '저공해조치 종류', '저공해조치 구조변경 YN', '저공해조치 YN(미사용)', '현재 회원번호', '소유자 구분', '용도', '제원관리번호', '수정 일시', '차량 말소 YN', '차량 제작 일자', '차량 연식', '차종', '차량관리번호', '차량등록번호 숫자 정보', '차대번호', '미정', '미정', '미정', '미정', '미정', '미정', '미정', '미정']
   }
   ocol = pd.DataFrame(odict)

   sdict = {
      '컬럼':slist,
      '내용':['취득금액', '취득일자', '본거지법정동코드', '차량등록일시', '배출가스인증번호', '배출가스등급', '배출가스검사유효일자', '최초회원번호', '최초등록일자', '저공해조치종류코드', '구조변경여부', '저공해조치여부', '현재회원번호', '차량소유자분류코드', '용도코드2', '제원관리번호', '수정일시', '차량말소여부', '차량제작일자', '연식', '차종코드', '차량관리번호', np.nan, '차대번호', '미정']
      }
   scol = pd.DataFrame(sdict)

   odf2 = odf[olist]
   sdf2 = sdf[slist]

   ocount = odf2.count().reset_index()
   ocount.columns = ['oindex', 'ocount']

   scount = sdf2.count().reset_index()
   scount.columns = ['sindex', 'scount']
   oscount = pd.concat([ocount, scount], axis=1)
   oscount['차이'] = oscount['ocount'] - oscount['scount']

   # 분석 결과 파일로 출력
   texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
   ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
   scol.to_excel(texcel, sheet_name='STD_col', index=False)
   oscount.to_excel(texcel, sheet_name='count', index=False)
   # odf2.count().reset_index().to_excel(texcel, sheet_name='ODS_count',index=False)
   # sdf2.count().reset_index().to_excel(texcel, sheet_name='STD_count',index=False)
   texcel.save()
   
   print(f'======== {ods_file_name}_vs_{std_file_name} 비교 ========')
   print(f'ODS의 shape : {odf2.shape}, STD의 shape : {sdf2.shape}')
   print(f'"[정제]{ods_file_name}_vs_{std_file_name}.xlsx" 파일 출력 완료.')
   
   return oscount

In [330]:
tocount = np.array([0.0]*32)
tscount = np.array([0.0]*32)

for n in tqdm(range(1, 31)):
    try:
        temp = fuc(n)
        tocount += temp['ocount'].to_numpy()
        tscount += temp['scount'].to_numpy()
    except:
        pass

  0%|          | 0/30 [00:00<?, ?it/s]C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:7: DtypeWarning: Columns (13,15,26) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
  3%|▎         | 1/30 [00:20<10:03, 20.83s/it]

======== ODS_CEG_CAR_MIG_1_vs_STD_CEG_CAR_MIG_1 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_1_vs_STD_CEG_CAR_MIG_1.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:7: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
  7%|▋         | 2/30 [00:42<09:55, 21.26s/it]

======== ODS_CEG_CAR_MIG_2_vs_STD_CEG_CAR_MIG_2 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_2_vs_STD_CEG_CAR_MIG_2.xlsx" 파일 출력 완료.

 10%|█         | 3/30 [01:04<09:39, 21.47s/it]

======== ODS_CEG_CAR_MIG_3_vs_STD_CEG_CAR_MIG_3 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_3_vs_STD_CEG_CAR_MIG_3.xlsx" 파일 출력 완료.

 13%|█▎        | 4/30 [01:25<09:15, 21.37s/it]

======== ODS_CEG_CAR_MIG_4_vs_STD_CEG_CAR_MIG_4 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_4_vs_STD_CEG_CAR_MIG_4.xlsx" 파일 출력 완료.

 17%|█▋        | 5/30 [01:46<08:52, 21.32s/it]

======== ODS_CEG_CAR_MIG_5_vs_STD_CEG_CAR_MIG_5 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_5_vs_STD_CEG_CAR_MIG_5.xlsx" 파일 출력 완료.

 20%|██        | 6/30 [02:07<08:29, 21.25s/it]

======== ODS_CEG_CAR_MIG_6_vs_STD_CEG_CAR_MIG_6 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_6_vs_STD_CEG_CAR_MIG_6.xlsx" 파일 출력 완료.

 23%|██▎       | 7/30 [02:28<08:07, 21.20s/it]

======== ODS_CEG_CAR_MIG_7_vs_STD_CEG_CAR_MIG_7 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_7_vs_STD_CEG_CAR_MIG_7.xlsx" 파일 출력 완료.

 27%|██▋       | 8/30 [02:50<07:46, 21.22s/it]

======== ODS_CEG_CAR_MIG_8_vs_STD_CEG_CAR_MIG_8 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_8_vs_STD_CEG_CAR_MIG_8.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:7: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
 30%|███       | 9/30 [03:11<07:26, 21.24s/it]

======== ODS_CEG_CAR_MIG_9_vs_STD_CEG_CAR_MIG_9 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_9_vs_STD_CEG_CAR_MIG_9.xlsx" 파일 출력 완료.

 33%|███▎      | 10/30 [03:32<07:03, 21.17s/it]

======== ODS_CEG_CAR_MIG_10_vs_STD_CEG_CAR_MIG_10 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_10_vs_STD_CEG_CAR_MIG_10.xlsx" 파일 출력 완료.

 37%|███▋      | 11/30 [03:53<06:41, 21.15s/it]

======== ODS_CEG_CAR_MIG_11_vs_STD_CEG_CAR_MIG_11 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_11_vs_STD_CEG_CAR_MIG_11.xlsx" 파일 출력 완료.

 40%|████      | 12/30 [04:14<06:20, 21.13s/it]

======== ODS_CEG_CAR_MIG_12_vs_STD_CEG_CAR_MIG_12 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_12_vs_STD_CEG_CAR_MIG_12.xlsx" 파일 출력 완료.

 43%|████▎     | 13/30 [04:35<05:59, 21.16s/it]

======== ODS_CEG_CAR_MIG_13_vs_STD_CEG_CAR_MIG_13 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_13_vs_STD_CEG_CAR_MIG_13.xlsx" 파일 출력 완료.

 47%|████▋     | 14/30 [04:56<05:37, 21.08s/it]

======== ODS_CEG_CAR_MIG_14_vs_STD_CEG_CAR_MIG_14 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_14_vs_STD_CEG_CAR_MIG_14.xlsx" 파일 출력 완료.

 50%|█████     | 15/30 [05:17<05:15, 21.05s/it]

======== ODS_CEG_CAR_MIG_15_vs_STD_CEG_CAR_MIG_15 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_15_vs_STD_CEG_CAR_MIG_15.xlsx" 파일 출력 완료.

 53%|█████▎    | 16/30 [05:38<04:54, 21.05s/it]

======== ODS_CEG_CAR_MIG_16_vs_STD_CEG_CAR_MIG_16 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_16_vs_STD_CEG_CAR_MIG_16.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:7: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 57%|█████▋    | 17/30 [05:59<04:33, 21.05s/it]

======== ODS_CEG_CAR_MIG_17_vs_STD_CEG_CAR_MIG_17 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_17_vs_STD_CEG_CAR_MIG_17.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 60%|██████    | 18/30 [06:20<04:12, 21.06s/it]

======== ODS_CEG_CAR_MIG_18_vs_STD_CEG_CAR_MIG_18 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_18_vs_STD_CEG_CAR_MIG_18.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 63%|██████▎   | 19/30 [06:41<03:51, 21.06s/it]

======== ODS_CEG_CAR_MIG_19_vs_STD_CEG_CAR_MIG_19 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_19_vs_STD_CEG_CAR_MIG_19.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 67%|██████▋   | 20/30 [07:03<03:31, 21.15s/it]

======== ODS_CEG_CAR_MIG_20_vs_STD_CEG_CAR_MIG_20 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_20_vs_STD_CEG_CAR_MIG_20.xlsx" 파일 출력 완료.

 70%|███████   | 21/30 [07:14<02:42, 18.10s/it]C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 73%|███████▎  | 22/30 [07:36<02:34, 19.26s/it]

======== ODS_CEG_CAR_MIG_22_vs_STD_CEG_CAR_MIG_22 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_22_vs_STD_CEG_CAR_MIG_22.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 77%|███████▋  | 23/30 [07:57<02:20, 20.00s/it]

======== ODS_CEG_CAR_MIG_23_vs_STD_CEG_CAR_MIG_23 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_23_vs_STD_CEG_CAR_MIG_23.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 80%|████████  | 24/30 [08:19<02:03, 20.59s/it]

======== ODS_CEG_CAR_MIG_24_vs_STD_CEG_CAR_MIG_24 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_24_vs_STD_CEG_CAR_MIG_24.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 83%|████████▎ | 25/30 [08:41<01:44, 20.92s/it]

======== ODS_CEG_CAR_MIG_25_vs_STD_CEG_CAR_MIG_25 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_25_vs_STD_CEG_CAR_MIG_25.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 87%|████████▋ | 26/30 [09:03<01:24, 21.14s/it]

======== ODS_CEG_CAR_MIG_26_vs_STD_CEG_CAR_MIG_26 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_26_vs_STD_CEG_CAR_MIG_26.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 90%|█████████ | 27/30 [09:24<01:03, 21.24s/it]

======== ODS_CEG_CAR_MIG_27_vs_STD_CEG_CAR_MIG_27 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_27_vs_STD_CEG_CAR_MIG_27.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 93%|█████████▎| 28/30 [09:45<00:42, 21.25s/it]

======== ODS_CEG_CAR_MIG_28_vs_STD_CEG_CAR_MIG_28 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_28_vs_STD_CEG_CAR_MIG_28.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (1,9,15,18) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 97%|█████████▋| 29/30 [10:07<00:21, 21.23s/it]

======== ODS_CEG_CAR_MIG_29_vs_STD_CEG_CAR_MIG_29 비교 ========
ODS의 shape : (1000000, 32), STD의 shape : (1000000, 25)
"[정제]ODS_CEG_CAR_MIG_29_vs_STD_CEG_CAR_MIG_29.xlsx" 파일 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_21760\3818399303.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
100%|██████████| 30/30 [10:17<00:00, 20.58s/it]

======== ODS_CEG_CAR_MIG_30_vs_STD_CEG_CAR_MIG_30 비교 ========
ODS의 shape : (534047, 32), STD의 shape : (415224, 25)
"[정제]ODS_CEG_CAR_MIG_30_vs_STD_CEG_CAR_MIG_30.xlsx" 파일 출력 완료.

In [331]:
olist = [
    'ACQS_AMT', 
    'ACQS_DE', 
    'BSPL_LEDO_CD', 
    'CRTN_DT', 
    'EMIS_CRTCNO', 
    'EMIS_GRD', 
    'EMIS_INSP_EFCT_DE', 
    'FST_MBERNO', 
    'FST_REG_DE', 
    'LEM_KND', 
    'LEM_STRCHG_YN', 
    'LEM_YN', 
    'NOW_MBERNO', 
    'OWNR_SE', 
    'PURPS', 
    'SRCMNNO', 
    'UPDT_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_MNFCT_DE', 
    'VHCL_YRIDNW', 
    'VHCTY', 
    'VHMNO', 
    'VHRNO_NUM_INFO', 
    'VIN', 'VHRNO', 
    'NOW_OWNR_NM', 
    'BSPL_ADRS', 
    'OWNR_ADRS', 
    'BSPL_ZIP', 
    'FST_OWNR_NM', 
    'RMK', 
    'USER_ID'
    ]
odict = {
    '컬럼':olist,
    '내용':['취득금액', '취득일자', '본거지 법정동 코드', '생성 일시', '배출가스 인증번호', '배출가스 등급', '배출가스검사유효일자', '최초 회원번호', '최초 등록 일자', '저공해조치 종류', '저공해조치 구조변경 YN', '저공해조치 YN(미사용)', '현재 회원번호', '소유자 구분', '용도', '제원관리번호', '수정 일시', '차량 말소 YN', '차량 제작 일자', '차량 연식', '차종', '차량관리번호', '차량등록번호 숫자 정보', '차대번호', '미정', '미정', '미정', '미정', '미정', '미정', '미정', '미정']
    }
ocol = pd.DataFrame(odict)
ocol

                   컬럼             내용
0            ACQS_AMT           취득금액
1             ACQS_DE           취득일자
2        BSPL_LEDO_CD     본거지 법정동 코드
3             CRTN_DT          생성 일시
4         EMIS_CRTCNO      배출가스 인증번호
5            EMIS_GRD        배출가스 등급
6   EMIS_INSP_EFCT_DE     배출가스검사유효일자
7          FST_MBERNO        최초 회원번호
8          FST_REG_DE       최초 등록 일자
9             LEM_KND       저공해조치 종류
10      LEM_STRCHG_YN  저공해조치 구조변경 YN
11             LEM_YN  저공해조치 YN(미사용)
12         NOW_MBERNO        현재 회원번호
13            OWNR_SE         소유자 구분
14              PURPS             용도
15            SRCMNNO         제원관리번호
16            UPDT_DT          수정 일시
17       VHCL_ERSR_YN       차량 말소 YN
18      VHCL_MNFCT_DE       차량 제작 일자
19        VHCL_YRIDNW          차량 연식
20              VHCTY             차종
21              VHMNO         차량관리번호
22     VHRNO_NUM_INFO   차량등록번호 숫자 정보
23                VIN           차대번호
24              VHRNO             미정
25        NOW_OWNR_NM             미정
26          BSPL_ADRS             미정
27          OWNR_ADRS             미정
28           BSPL_ZIP             미정
29        FST_OWNR_NM             미정
30                RMK             미정
31            USER_ID             미정

In [332]:
slist = [
    'ACQS_AMT', 
    'ACQS_YMD', 
    'BSPL_STDG_CD', 
    'VHCL_REG_DT', 
    'EXHST_GAS_CERT_NO', 
    'EXHST_GAS_GRD_CD', 
    'EXTGAS_INSP_VLD_YMD', 
    'FRST_MBR_NO', 
    'FRST_REG_YMD', 
    'LEM_KND_CD', 
    'STRCT_CHG_YN', 
    'LEM_YN', 
    'NOW_MBR_NO', 
    'VHCL_OWNR_CL_CD', 
    'PURPS_CD2', 
    'MANP_MNG_NO', 
    'MDFCN_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_FBCTN_YMD', 
    'YRIDNW', 
    'VHCTY_CD', 
    'VHCL_MNG_NO', 
    'VHRNO_FGRE_INFO', 
    'VIN', 
    'VHRNO'
    ]
sdict = {
       '컬럼':slist,
       '내용':['취득금액', '취득일자', '본거지법정동코드', '차량등록일시', '배출가스인증번호', '배출가스등급', '배출가스검사유효일자', '최초회원번호', '최초등록일자', '저공해조치종류코드', '구조변경여부', '저공해조치여부', '현재회원번호', '차량소유자분류코드', '용도코드2', '제원관리번호', '수정일시', '차량말소여부', '차량제작일자', '연식', '차종코드', '차량관리번호', np.nan, '차대번호', '미정']
       }
scol = pd.DataFrame(sdict)
scol

                     컬럼          내용
0              ACQS_AMT        취득금액
1              ACQS_YMD        취득일자
2          BSPL_STDG_CD    본거지법정동코드
3           VHCL_REG_DT      차량등록일시
4     EXHST_GAS_CERT_NO    배출가스인증번호
5      EXHST_GAS_GRD_CD      배출가스등급
6   EXTGAS_INSP_VLD_YMD  배출가스검사유효일자
7           FRST_MBR_NO      최초회원번호
8          FRST_REG_YMD      최초등록일자
9            LEM_KND_CD   저공해조치종류코드
10         STRCT_CHG_YN      구조변경여부
11               LEM_YN     저공해조치여부
12           NOW_MBR_NO      현재회원번호
13      VHCL_OWNR_CL_CD   차량소유자분류코드
14            PURPS_CD2       용도코드2
15          MANP_MNG_NO      제원관리번호
16             MDFCN_DT        수정일시
17         VHCL_ERSR_YN      차량말소여부
18       VHCL_FBCTN_YMD      차량제작일자
19               YRIDNW          연식
20             VHCTY_CD        차종코드
21          VHCL_MNG_NO      차량관리번호
22      VHRNO_FGRE_INFO         NaN
23                  VIN        차대번호
24                VHRNO          미정

In [333]:
total_count = pd.concat([ocol, scol], axis=1)
total_count.columns = ['ODS_col', 'ODS_count', 'STD_col', 'STD_count']
total_count

              ODS_col      ODS_count              STD_col   STD_count
0            ACQS_AMT           취득금액             ACQS_AMT        취득금액
1             ACQS_DE           취득일자             ACQS_YMD        취득일자
2        BSPL_LEDO_CD     본거지 법정동 코드         BSPL_STDG_CD    본거지법정동코드
3             CRTN_DT          생성 일시          VHCL_REG_DT      차량등록일시
4         EMIS_CRTCNO      배출가스 인증번호    EXHST_GAS_CERT_NO    배출가스인증번호
5            EMIS_GRD        배출가스 등급     EXHST_GAS_GRD_CD      배출가스등급
6   EMIS_INSP_EFCT_DE     배출가스검사유효일자  EXTGAS_INSP_VLD_YMD  배출가스검사유효일자
7          FST_MBERNO        최초 회원번호          FRST_MBR_NO      최초회원번호
8          FST_REG_DE       최초 등록 일자         FRST_REG_YMD      최초등록일자
9             LEM_KND       저공해조치 종류           LEM_KND_CD   저공해조치종류코드
10      LEM_STRCHG_YN  저공해조치 구조변경 YN         STRCT_CHG_YN      구조변경여부
11             LEM_YN  저공해조치 YN(미사용)               LEM_YN     저공해조치여부
12         NOW_MBERNO        현재 회원번호           NOW_MBR_NO      현재회원번호
13            OWNR_SE         소유자 구분      VHCL_OWNR_CL_CD   차량소유자분류코드
14              PURPS             용도            PURPS_CD2       용도코드2
15            SRCMNNO         제원관리번호          MANP_MNG_NO      제원관리번호
16            UPDT_DT          수정 일시             MDFCN_DT        수정일시
17       VHCL_ERSR_YN       차량 말소 YN         VHCL_ERSR_YN      차량말소여부
18      VHCL_MNFCT_DE       차량 제작 일자       VHCL_FBCTN_YMD      차량제작일자
19        VHCL_YRIDNW          차량 연식               YRIDNW          연식
20              VHCTY             차종             VHCTY_CD        차종코드
21              VHMNO         차량관리번호          VHCL_MNG_NO      차량관리번호
22     VHRNO_NUM_INFO   차량등록번호 숫자 정보      VHRNO_FGRE_INFO         NaN
23                VIN           차대번호                  VIN        차대번호
24              VHRNO             미정                VHRNO          미정
25        NOW_OWNR_NM             미정                  NaN         NaN
26          BSPL_ADRS             미정                  NaN         NaN
27          OWNR_ADRS             미정                  NaN         NaN
28           BSPL_ZIP             미정                  NaN         NaN
29        FST_OWNR_NM             미정                  NaN         NaN
30                RMK             미정                  NaN         NaN
31            USER_ID             미정                  NaN         NaN

In [334]:
tocount

array([28150030., 28106125., 28534047., 28534047., 25177959., 28534015.,
       28533413., 28499737., 28534047.,   485612., 28534042., 27224405.,
       28524399., 28534047., 28534047., 28534047., 21219185., 28534047.,
       28109503., 28534047., 28534033., 28534047., 28534047., 28534047.,
       28534047., 28534045., 28534026., 28534044.,        0., 28534011.,
        9238485., 28534046.])

In [335]:
tscount

array([28034244., 27990333., 28415224., 28415224., 25121146., 28415192.,
       28414590., 28380914., 28415224.,   484560., 28415219., 27105633.,
       28405576., 28415224., 28415224., 28415224., 21033082., 28415224.,
       27990681., 28415224., 28415210., 28415224., 28415224., 28415224.,
       28415224.,       nan,       nan,       nan,       nan,       nan,
             nan,       nan])

In [336]:
total_count['ODS_count'] = tocount
total_count['STD_count'] = tscount

In [337]:
total_count

              ODS_col   ODS_count              STD_col   STD_count
0            ACQS_AMT  28150030.0             ACQS_AMT  28034244.0
1             ACQS_DE  28106125.0             ACQS_YMD  27990333.0
2        BSPL_LEDO_CD  28534047.0         BSPL_STDG_CD  28415224.0
3             CRTN_DT  28534047.0          VHCL_REG_DT  28415224.0
4         EMIS_CRTCNO  25177959.0    EXHST_GAS_CERT_NO  25121146.0
5            EMIS_GRD  28534015.0     EXHST_GAS_GRD_CD  28415192.0
6   EMIS_INSP_EFCT_DE  28533413.0  EXTGAS_INSP_VLD_YMD  28414590.0
7          FST_MBERNO  28499737.0          FRST_MBR_NO  28380914.0
8          FST_REG_DE  28534047.0         FRST_REG_YMD  28415224.0
9             LEM_KND    485612.0           LEM_KND_CD    484560.0
10      LEM_STRCHG_YN  28534042.0         STRCT_CHG_YN  28415219.0
11             LEM_YN  27224405.0               LEM_YN  27105633.0
12         NOW_MBERNO  28524399.0           NOW_MBR_NO  28405576.0
13            OWNR_SE  28534047.0      VHCL_OWNR_CL_CD  28415224.0
14              PURPS  28534047.0            PURPS_CD2  28415224.0
15            SRCMNNO  28534047.0          MANP_MNG_NO  28415224.0
16            UPDT_DT  21219185.0             MDFCN_DT  21033082.0
17       VHCL_ERSR_YN  28534047.0         VHCL_ERSR_YN  28415224.0
18      VHCL_MNFCT_DE  28109503.0       VHCL_FBCTN_YMD  27990681.0
19        VHCL_YRIDNW  28534047.0               YRIDNW  28415224.0
20              VHCTY  28534033.0             VHCTY_CD  28415210.0
21              VHMNO  28534047.0          VHCL_MNG_NO  28415224.0
22     VHRNO_NUM_INFO  28534047.0      VHRNO_FGRE_INFO  28415224.0
23                VIN  28534047.0                  VIN  28415224.0
24              VHRNO  28534047.0                VHRNO  28415224.0
25        NOW_OWNR_NM  28534045.0                  NaN         NaN
26          BSPL_ADRS  28534026.0                  NaN         NaN
27          OWNR_ADRS  28534044.0                  NaN         NaN
28           BSPL_ZIP         0.0                  NaN         NaN
29        FST_OWNR_NM  28534011.0                  NaN         NaN
30                RMK   9238485.0                  NaN         NaN
31            USER_ID  28534046.0                  NaN         NaN

In [338]:
# ODS : 1000000*(29-1) + 534047
# STD : 1000000*(29-1) + 415224

total_count['diff'] = total_count['ODS_count'] - total_count['STD_count']
total_count['ODS_mcount'] = 28534047 - total_count['ODS_count']
total_count['STD_mcount'] = 28415224 - total_count['STD_count']
total_count['ocol'] = ocol['내용']
total_count['scol'] = scol['내용']
total_count = total_count[['ODS_col', 'ocol', 'ODS_count', 'STD_col', 'scol', 'STD_count', 'diff', 'ODS_mcount', 'STD_mcount']]
total_count

,ODS_col,ocol,ODS_count,STD_col,scol,STD_count,diff,ODS_mcount,STD_mcount
0,ACQS_AMT,취득금액,28150030.0,ACQS_AMT,취득금액,28034244.0,115786.0,384017.0,380980.0
1,ACQS_DE,취득일자,28106125.0,ACQS_YMD,취득일자,27990333.0,115792.0,427922.0,424891.0
2,BSPL_LEDO_CD,본거지 법정동 코드,28534047.0,BSPL_STDG_CD,본거지법정동코드,28415224.0,118823.0,0.0,0.0
3,CRTN_DT,생성 일시,28534047.0,VHCL_REG_DT,차량등록일시,28415224.0,118823.0,0.0,0.0
4,EMIS_CRTCNO,배출가스 인증번호,25177959.0,EXHST_GAS_CERT_NO,배출가스인증번호,25121146.0,56813.0,3356088.0,3294078.0
5,EMIS_GRD,배출가스 등급,28534015.0,EXHST_GAS_GRD_CD,배출가스등급,28415192.0,118823.0,32.0,32.0
6,EMIS_INSP_EFCT_DE,배출가스검사유효일자,28533413.0,EXTGAS_INSP_VLD_YMD,배출가스검사유효일자,28414590.0,118823.0,634.0,634.0
7,FST_MBERNO,최초 회원번호,28499737.0,FRST_MBR_NO,최초회원번호,28380914.0,118823.0,34310.0,34310.0
8,FST_REG_DE,최초 등록 일자,28534047.0,FRST_REG_YMD,최초등록일자,28415224.0,118823.0,0.0,0.0
9,LEM_KND,저공해조치 종류,485612.0,LEM_KND_CD,저공해조치종류코드,484560.0,1052.0,28048435.0,27930664.0
10,LEM_STRCHG_YN,저공해조치 구조변경 YN,28534042.0,STRCT_CHG_YN,구조변경여부,28415219.0,118823.0,5.0,5.0
11,LEM_YN,저공해조치 YN(미사용),27224405.0,LEM_YN,저공해조치여부,27105633.0,118772.0,1309642.0,1309591.0
12,NOW_MBERNO,현재 회원번호,28524399.0,NOW_MBR_NO,현재회원번호,28405576.0,118823.0,9648.0,9648.0
13,OWNR_SE,소유자 구분,28534047.0,VHCL_OWNR_CL_CD,차량소유자분류코드,28415224.0,118823.0,0.0,0.0
14,PURPS,용도,28534047.0,PURPS_CD2,용도코드2,28415224.0,118823.0,0.0,0.0
15,SRCMNNO,제원관리번호,28534047.0,MANP_MNG_NO,제원관리번호,28415224.0,118823.0,0.0,0.0
16,UPDT_DT,수정 일시,21219185.0,MDFCN_DT,수정일시,21033082.0,186103.0,7314862.0,7382142.0
17,VHCL_ERSR_YN,차량 말소 YN,28534047.0,VHCL_ERSR_YN,차량말소여부,28415224.0,118823.0,0.0,0.0
18,VHCL_MNFCT_DE,차량 제작 일자,28109503.0,VHCL_FBCTN_YMD,차량제작일자,27990681.0,118822.0,424544.0,424543.0
19,VHCL_YRIDNW,차량 연식,28534047.0,YRIDNW,연식,28415224.0,118823.0,0.0,0.0
20,VHCTY,차종,28534033.0,VHCTY_CD,차종코드,28415210.0,118823.0,14.0,14.0
21,VHMNO,차량관리번호,28534047.0,VHCL_MNG_NO,차량관리번호,28415224.0,118823.0,0.0,0.0
22,VHRNO_NUM_INFO,차량등록번호 숫자 정보,28534047.0,VHRNO_FGRE_INFO,NaN,28415224.0,118823.0,0.0,0.0
23,VIN,차대번호,28534047.0,VIN,차대번호,28415224.0,118823.0,0.0,0.0
24,VHRNO,미정,28534047.0,VHRNO,미정,28415224.0,118823.0,0.0,0.0
25,NOW_OWNR_NM,미정,28534045.0,NaN,NaN,NaN,NaN,2.0,NaN
26,BSPL_ADRS,미정,28534026.0,NaN,NaN,NaN,NaN,21.0,NaN
27,OWNR_ADRS,미정,28534044.0,NaN,NaN,NaN,NaN,3.0,NaN
28,BSPL_ZIP,미정,0.0,NaN,NaN,NaN,NaN,28534047.0,NaN
29,FST_OWNR_NM,미정,28534011.0,NaN,NaN,NaN,NaN,36.0,NaN
30,RMK,미정,9238485.0,NaN,NaN,NaN,NaN,19295562.0,NaN
31,USER_ID,미정,28534046.0,NaN,NaN,NaN,NaN,1.0,NaN

In [339]:
total_count.to_excel('analysis/ODSvsSTD/[정제]CEG_CAR_MIG.xlsx', index=False)

### test

#### 파일명 설정

In [56]:
num = 4
ods_file_name = f'ODS_CEG_CAR_MIG_{num}'
std_file_name = f'STD_CEG_CAR_MIG_{num}'

In [57]:
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')

In [58]:
odf = pd.read_csv(opath)
sdf = pd.read_csv(spath)

#### 등록정보 분석

In [59]:
odf.columns

Index(['VHMNO', 'VHRNO', 'BSPL_LEDO_CD', 'OWNR_SE', 'VHCTY', 'PURPS',
       'NOW_OWNR_NM', 'NOW_MBERNO', 'BSPL_ADRS', 'OWNR_ADRS', 'VIN',
       'FST_REG_DE', 'VHCL_YRIDNW', 'VHCL_MNFCT_DE', 'EMIS_INSP_EFCT_DE',
       'SRCMNNO', 'EMIS_CRTCNO', 'EMIS_GRD', 'LEM_YN', 'LEM_KND',
       'LEM_STRCHG_YN', 'BSPL_ZIP', 'VHRNO_NUM_INFO', 'VHCL_ERSR_YN',
       'FST_OWNR_NM', 'FST_MBERNO', 'ACQS_DE', 'ACQS_AMT', 'RMK', 'CRTN_DT',
       'UPDT_DT', 'USER_ID'],
      dtype='object')

In [60]:
sdf.columns

Index(['ACQS_AMT', 'ACQS_YMD', 'BSPL_STDG_CD', 'VHCL_REG_DT',
       'EXHST_GAS_CERT_NO', 'EXHST_GAS_GRD_CD', 'EXTGAS_INSP_VLD_YMD',
       'FRST_MBR_NO', 'FRST_REG_YMD', 'LEM_KND_CD', 'STRCT_CHG_YN', 'LEM_YN',
       'NOW_MBR_NO', 'VHCL_OWNR_CL_CD', 'PURPS_CD2', 'MANP_MNG_NO', 'MDFCN_DT',
       'VHCL_ERSR_YN', 'VHCL_FBCTN_YMD', 'YRIDNW', 'VHCTY_CD', 'VHCL_MNG_NO',
       'VHRNO_FGRE_INFO', 'VIN', 'VHRNO'],
      dtype='object')

In [61]:
len(odf.columns), len(sdf.columns)

(32, 25)

In [62]:
odf.shape, sdf.shape

((1000000, 32), (1000000, 25))

##### 동일한 내용의 컬럼 확인

In [63]:
olist = [
    'ACQS_AMT', 
    'ACQS_DE', 
    'BSPL_LEDO_CD', 
    'CRTN_DT', 
    'EMIS_CRTCNO', 
    'EMIS_GRD', 
    'EMIS_INSP_EFCT_DE', 
    'FST_MBERNO', 
    'FST_REG_DE', 
    'LEM_KND', 
    'LEM_STRCHG_YN', 
    'LEM_YN', 
    'NOW_MBERNO', 
    'OWNR_SE', 
    'PURPS', 
    'SRCMNNO', 
    'UPDT_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_MNFCT_DE', 
    'VHCL_YRIDNW', 
    'VHCTY', 
    'VHMNO', 
    'VHRNO_NUM_INFO', 
    'VIN', 'VHRNO', 
    'NOW_OWNR_NM', 
    'BSPL_ADRS', 
    'OWNR_ADRS', 
    'BSPL_ZIP', 
    'FST_OWNR_NM', 
    'RMK', 
    'USER_ID'
    ]

In [64]:
odict = {
    '컬럼':olist,
    '내용':['취득금액', '취득일자', '본거지 법정동 코드', '생성 일시', '배출가스 인증번호', '배출가스 등급', '배출가스검사유효일자', '최초 회원번호', '최초 등록 일자', '저공해조치 종류', '저공해조치 구조변경 YN', '저공해조치 YN(미사용)', '현재 회원번호', '소유자 구분', '용도', '제원관리번호', '수정 일시', '차량 말소 YN', '차량 제작 일자', '차량 연식', '차종', '차량관리번호', '차량등록번호 숫자 정보', '차대번호', '미정', '미정', '미정', '미정', '미정', '미정', '미정', '미정']
    }

In [65]:
ocol = pd.DataFrame(odict)
ocol

                   컬럼             내용
0            ACQS_AMT           취득금액
1             ACQS_DE           취득일자
2        BSPL_LEDO_CD     본거지 법정동 코드
3             CRTN_DT          생성 일시
4         EMIS_CRTCNO      배출가스 인증번호
5            EMIS_GRD        배출가스 등급
6   EMIS_INSP_EFCT_DE     배출가스검사유효일자
7          FST_MBERNO        최초 회원번호
8          FST_REG_DE       최초 등록 일자
9             LEM_KND       저공해조치 종류
10      LEM_STRCHG_YN  저공해조치 구조변경 YN
11             LEM_YN  저공해조치 YN(미사용)
12         NOW_MBERNO        현재 회원번호
13            OWNR_SE         소유자 구분
14              PURPS             용도
15            SRCMNNO         제원관리번호
16            UPDT_DT          수정 일시
17       VHCL_ERSR_YN       차량 말소 YN
18      VHCL_MNFCT_DE       차량 제작 일자
19        VHCL_YRIDNW          차량 연식
20              VHCTY             차종
21              VHMNO         차량관리번호
22     VHRNO_NUM_INFO   차량등록번호 숫자 정보
23                VIN           차대번호
24              VHRNO             미정
25        NOW_OWNR_NM             미정
26          BSPL_ADRS             미정
27          OWNR_ADRS             미정
28           BSPL_ZIP             미정
29        FST_OWNR_NM             미정
30                RMK             미정
31            USER_ID             미정

In [66]:
# ocol.to_excel(f'analysis/ODSvsSTD/[정제][col]{ods_file_name}.xlsx', index=False)

In [67]:
slist = [
    'ACQS_AMT', 
    'ACQS_YMD', 
    'BSPL_STDG_CD', 
    'VHCL_REG_DT', 
    'EXHST_GAS_CERT_NO', 
    'EXHST_GAS_GRD_CD', 
    'EXTGAS_INSP_VLD_YMD', 
    'FRST_MBR_NO', 
    'FRST_REG_YMD', 
    'LEM_KND_CD', 
    'STRCT_CHG_YN', 
    'LEM_YN', 
    'NOW_MBR_NO', 
    'VHCL_OWNR_CL_CD', 
    'PURPS_CD2', 
    'MANP_MNG_NO', 
    'MDFCN_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_FBCTN_YMD', 
    'YRIDNW', 
    'VHCTY_CD', 
    'VHCL_MNG_NO', 
    'VHRNO_FGRE_INFO', 
    'VIN', 
    'VHRNO'
    ]

In [68]:
sdict = {
       '컬럼':slist,
       '내용':['취득금액', '취득일자', '본거지법정동코드', '차량등록일시', '배출가스인증번호', '배출가스등급', '배출가스검사유효일자', '최초회원번호', '최초등록일자', '저공해조치종류코드', '구조변경여부', '저공해조치여부', '현재회원번호', '차량소유자분류코드', '용도코드2', '제원관리번호', '수정일시', '차량말소여부', '차량제작일자', '연식', '차종코드', '차량관리번호', np.nan, '차대번호', '미정']
       }

In [69]:
scol = pd.DataFrame(sdict)
scol

                     컬럼          내용
0              ACQS_AMT        취득금액
1              ACQS_YMD        취득일자
2          BSPL_STDG_CD    본거지법정동코드
3           VHCL_REG_DT      차량등록일시
4     EXHST_GAS_CERT_NO    배출가스인증번호
5      EXHST_GAS_GRD_CD      배출가스등급
6   EXTGAS_INSP_VLD_YMD  배출가스검사유효일자
7           FRST_MBR_NO      최초회원번호
8          FRST_REG_YMD      최초등록일자
9            LEM_KND_CD   저공해조치종류코드
10         STRCT_CHG_YN      구조변경여부
11               LEM_YN     저공해조치여부
12           NOW_MBR_NO      현재회원번호
13      VHCL_OWNR_CL_CD   차량소유자분류코드
14            PURPS_CD2       용도코드2
15          MANP_MNG_NO      제원관리번호
16             MDFCN_DT        수정일시
17         VHCL_ERSR_YN      차량말소여부
18       VHCL_FBCTN_YMD      차량제작일자
19               YRIDNW          연식
20             VHCTY_CD        차종코드
21          VHCL_MNG_NO      차량관리번호
22      VHRNO_FGRE_INFO         NaN
23                  VIN        차대번호
24                VHRNO          미정

In [70]:
# scol.to_excel(f'analysis/ODSvsSTD/[정제][col]{std_file_name}.xlsx', index=False)

###### 데이터 info 확인

In [71]:
odf1_1 = odf[olist]
odf1_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ACQS_AMT           964979 non-null   float64
 1   ACQS_DE            965439 non-null   float64
 2   BSPL_LEDO_CD       1000000 non-null  int64
 3   CRTN_DT            1000000 non-null  object
 4   EMIS_CRTCNO        868166 non-null   object
 5   EMIS_GRD           1000000 non-null  object
 6   EMIS_INSP_EFCT_DE  999996 non-null   float64
 7   FST_MBERNO         1000000 non-null  object
 8   FST_REG_DE         1000000 non-null  int64
 9   LEM_KND            101089 non-null   float64
 10  LEM_STRCHG_YN      1000000 non-null  object
 11  LEM_YN             999949 non-null   object
 12  NOW_MBERNO         1000000 non-null  object
 13  OWNR_SE            1000000 non-null  object
 14  PURPS              1000000 non-null  object
 15  SRCMNNO            1000000 non-null  object
 16  UPDT_DT            771436 non-null   object
 17  VHCL_ERSR_YN       1000000 non-null  object
 18  VHCL_MNFCT_DE      999981 non-null   float64
 19  VHCL_YRIDNW        1000000 non-null  int64
 20  VHCTY              1000000 non-null  object
 21  VHMNO              1000000 non-null  object
 22  VHRNO_NUM_INFO     1000000 non-null  int64
 23  VIN                1000000 non-null  object
 24  VHRNO              1000000 non-null  object
 25  NOW_OWNR_NM        1000000 non-null  object
 26  BSPL_ADRS          1000000 non-null  object
 27  OWNR_ADRS          1000000 non-null  object
 28  BSPL_ZIP           0 non-null        float64
 29  FST_OWNR_NM        1000000 non-null  object
 30  RMK                79548 non-null    object
 31  USER_ID            1000000 non-null  object
dtypes: float64(6), int64(4), object(22)
memory usage: 244.1+ MB

In [72]:
ocount = odf1_1.count().reset_index()
ocount.columns = ['index', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]
ocount

                index   ocount
0            ACQS_AMT   964979
1             ACQS_DE   965439
2        BSPL_LEDO_CD  1000000
3             CRTN_DT  1000000
4         EMIS_CRTCNO   868166
5            EMIS_GRD  1000000
6   EMIS_INSP_EFCT_DE   999996
7          FST_MBERNO  1000000
8          FST_REG_DE  1000000
9             LEM_KND   101089
10      LEM_STRCHG_YN  1000000
11             LEM_YN   999949
12         NOW_MBERNO  1000000
13            OWNR_SE  1000000
14              PURPS  1000000
15            SRCMNNO  1000000
16            UPDT_DT   771436
17       VHCL_ERSR_YN  1000000
18      VHCL_MNFCT_DE   999981
19        VHCL_YRIDNW  1000000
20              VHCTY  1000000
21              VHMNO  1000000
22     VHRNO_NUM_INFO  1000000
23                VIN  1000000
24              VHRNO  1000000
25        NOW_OWNR_NM  1000000
26          BSPL_ADRS  1000000
27          OWNR_ADRS  1000000
28           BSPL_ZIP        0
29        FST_OWNR_NM  1000000
30                RMK    79548
31            USER_ID  1000000

In [73]:
# odf1_1.count().reset_index().to_excel(f'analysis/ODSvsSTD/[정제][count]{ods_file_name}.xlsx', index=False)

In [74]:
sdf1_1 = sdf[slist]
sdf1_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 25 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   ACQS_AMT             987951 non-null   float64
 1   ACQS_YMD             988042 non-null   float64
 2   BSPL_STDG_CD         1000000 non-null  int64
 3   VHCL_REG_DT          1000000 non-null  object
 4   EXHST_GAS_CERT_NO    890589 non-null   object
 5   EXHST_GAS_GRD_CD     1000000 non-null  object
 6   EXTGAS_INSP_VLD_YMD  999997 non-null   float64
 7   FRST_MBR_NO          1000000 non-null  object
 8   FRST_REG_YMD         1000000 non-null  int64
 9   LEM_KND_CD           30025 non-null    object
 10  STRCT_CHG_YN         1000000 non-null  object
 11  LEM_YN               999965 non-null   object
 12  NOW_MBR_NO           1000000 non-null  object
 13  VHCL_OWNR_CL_CD      1000000 non-null  object
 14  PURPS_CD2            1000000 non-null  object
 15  MANP_MNG_NO          1000000 non-null  object
 16  MDFCN_DT             762134 non-null   object
 17  VHCL_ERSR_YN         1000000 non-null  object
 18  VHCL_FBCTN_YMD       999992 non-null   float64
 19  YRIDNW               1000000 non-null  int64
 20  VHCTY_CD             1000000 non-null  object
 21  VHCL_MNG_NO          1000000 non-null  object
 22  VHRNO_FGRE_INFO      1000000 non-null  int64
 23  VIN                  1000000 non-null  object
 24  VHRNO                1000000 non-null  object
dtypes: float64(4), int64(4), object(17)
memory usage: 190.7+ MB

In [75]:
scount = sdf1_1.count().reset_index()
scount.columns = ['index', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]
scount

                  index   scount
0              ACQS_AMT   987951
1              ACQS_YMD   988042
2          BSPL_STDG_CD  1000000
3           VHCL_REG_DT  1000000
4     EXHST_GAS_CERT_NO   890589
5      EXHST_GAS_GRD_CD  1000000
6   EXTGAS_INSP_VLD_YMD   999997
7           FRST_MBR_NO  1000000
8          FRST_REG_YMD  1000000
9            LEM_KND_CD    30025
10         STRCT_CHG_YN  1000000
11               LEM_YN   999965
12           NOW_MBR_NO  1000000
13      VHCL_OWNR_CL_CD  1000000
14            PURPS_CD2  1000000
15          MANP_MNG_NO  1000000
16             MDFCN_DT   762134
17         VHCL_ERSR_YN  1000000
18       VHCL_FBCTN_YMD   999992
19               YRIDNW  1000000
20             VHCTY_CD  1000000
21          VHCL_MNG_NO  1000000
22      VHRNO_FGRE_INFO  1000000
23                  VIN  1000000
24                VHRNO  1000000

In [76]:
# sdf1_1.count().reset_index().to_excel(f'analysis/ODSvsSTD/[정제][count]{std_file_name}.xlsx', index=False)

In [77]:
oscount = pd.concat([ocount, scount], axis=1)
oscount

                index   ocount                index     scount
0            ACQS_AMT   964979             ACQS_AMT   987951.0
1             ACQS_DE   965439             ACQS_YMD   988042.0
2        BSPL_LEDO_CD  1000000         BSPL_STDG_CD  1000000.0
3             CRTN_DT  1000000          VHCL_REG_DT  1000000.0
4         EMIS_CRTCNO   868166    EXHST_GAS_CERT_NO   890589.0
5            EMIS_GRD  1000000     EXHST_GAS_GRD_CD  1000000.0
6   EMIS_INSP_EFCT_DE   999996  EXTGAS_INSP_VLD_YMD   999997.0
7          FST_MBERNO  1000000          FRST_MBR_NO  1000000.0
8          FST_REG_DE  1000000         FRST_REG_YMD  1000000.0
9             LEM_KND   101089           LEM_KND_CD    30025.0
10      LEM_STRCHG_YN  1000000         STRCT_CHG_YN  1000000.0
11             LEM_YN   999949               LEM_YN   999965.0
12         NOW_MBERNO  1000000           NOW_MBR_NO  1000000.0
13            OWNR_SE  1000000      VHCL_OWNR_CL_CD  1000000.0
14              PURPS  1000000            PURPS_CD2  1000000.0
15            SRCMNNO  1000000          MANP_MNG_NO  1000000.0
16            UPDT_DT   771436             MDFCN_DT   762134.0
17       VHCL_ERSR_YN  1000000         VHCL_ERSR_YN  1000000.0
18      VHCL_MNFCT_DE   999981       VHCL_FBCTN_YMD   999992.0
19        VHCL_YRIDNW  1000000               YRIDNW  1000000.0
20              VHCTY  1000000             VHCTY_CD  1000000.0
21              VHMNO  1000000          VHCL_MNG_NO  1000000.0
22     VHRNO_NUM_INFO  1000000      VHRNO_FGRE_INFO  1000000.0
23                VIN  1000000                  VIN  1000000.0
24              VHRNO  1000000                VHRNO  1000000.0
25        NOW_OWNR_NM  1000000                  NaN        NaN
26          BSPL_ADRS  1000000                  NaN        NaN
27          OWNR_ADRS  1000000                  NaN        NaN
28           BSPL_ZIP        0                  NaN        NaN
29        FST_OWNR_NM  1000000                  NaN        NaN
30                RMK    79548                  NaN        NaN
31            USER_ID  1000000                  NaN        NaN

In [78]:
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] =  odf.shape[0] - oscount['ocount']
oscount['STD_mcount'] =  sdf.shape[0] - oscount['scount']
oscount

                index   ocount                index     scount       차이
0            ACQS_AMT   964979             ACQS_AMT   987951.0 -22972.0
1             ACQS_DE   965439             ACQS_YMD   988042.0 -22603.0
2        BSPL_LEDO_CD  1000000         BSPL_STDG_CD  1000000.0      0.0
3             CRTN_DT  1000000          VHCL_REG_DT  1000000.0      0.0
4         EMIS_CRTCNO   868166    EXHST_GAS_CERT_NO   890589.0 -22423.0
5            EMIS_GRD  1000000     EXHST_GAS_GRD_CD  1000000.0      0.0
6   EMIS_INSP_EFCT_DE   999996  EXTGAS_INSP_VLD_YMD   999997.0     -1.0
7          FST_MBERNO  1000000          FRST_MBR_NO  1000000.0      0.0
8          FST_REG_DE  1000000         FRST_REG_YMD  1000000.0      0.0
9             LEM_KND   101089           LEM_KND_CD    30025.0  71064.0
10      LEM_STRCHG_YN  1000000         STRCT_CHG_YN  1000000.0      0.0
11             LEM_YN   999949               LEM_YN   999965.0    -16.0
12         NOW_MBERNO  1000000           NOW_MBR_NO  1000000.0      0.0
13            OWNR_SE  1000000      VHCL_OWNR_CL_CD  1000000.0      0.0
14              PURPS  1000000            PURPS_CD2  1000000.0      0.0
15            SRCMNNO  1000000          MANP_MNG_NO  1000000.0      0.0
16            UPDT_DT   771436             MDFCN_DT   762134.0   9302.0
17       VHCL_ERSR_YN  1000000         VHCL_ERSR_YN  1000000.0      0.0
18      VHCL_MNFCT_DE   999981       VHCL_FBCTN_YMD   999992.0    -11.0
19        VHCL_YRIDNW  1000000               YRIDNW  1000000.0      0.0
20              VHCTY  1000000             VHCTY_CD  1000000.0      0.0
21              VHMNO  1000000          VHCL_MNG_NO  1000000.0      0.0
22     VHRNO_NUM_INFO  1000000      VHRNO_FGRE_INFO  1000000.0      0.0
23                VIN  1000000                  VIN  1000000.0      0.0
24              VHRNO  1000000                VHRNO  1000000.0      0.0
25        NOW_OWNR_NM  1000000                  NaN        NaN      NaN
26          BSPL_ADRS  1000000                  NaN        NaN      NaN
27          OWNR_ADRS  1000000                  NaN        NaN      NaN
28           BSPL_ZIP        0                  NaN        NaN      NaN
29        FST_OWNR_NM  1000000                  NaN        NaN      NaN
30                RMK    79548                  NaN        NaN      NaN
31            USER_ID  1000000                  NaN        NaN      NaN

#### [출력] 분석내용

In [63]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
oscount.to_excel(texcel, sheet_name='count', index=False)
# odf1_1.count().reset_index().to_excel(texcel, sheet_name='ODS_count',index=False)
# sdf1_1.count().reset_index().to_excel(texcel, sheet_name='STD_count',index=False)
texcel.save()

## 2\. 자동차 제원정보 데이터 비교(CEG_CAR_SRC_MIG)

### 파일명 설정

In [148]:
name = 'CEG_CAR_SRC_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

28 25
(545374, 28) (545374, 25)

In [149]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS    28  545374
STD    25  545374

### 컬럼 확인

In [150]:
odf.columns.to_list()

['SRCMNNO',
 'VHCNM',
 'VHCTY',
 'VHCTY_CL',
 'VHCTY_TY',
 'CAR_FRM',
 'MKR_NM',
 'FUEL',
 'EGINTY',
 'EMPV_WGHT',
 'TOT_WGHT',
 'CRYNG_WGHT',
 'EGINPWR',
 'DSPLVL',
 'TKCAR_NMPR',
 'VHCL_LT',
 'VHCL_WH',
 'VHCL_HG',
 'PLOR_NM',
 'REPCAR_NM',
 'DELE_YN',
 'CNFRM_DE',
 'DRV_FRM',
 'GEARBOX_KND',
 'RMK',
 'CRTN_DT',
 'UPDT_DT',
 'USER_ID']

In [151]:
olist = [
    'CAR_FRM',
    'CNFRM_DE', 
    'CRTN_DT', 
    'CRYNG_WGHT',
    'DELE_YN', 
    'DRV_FRM', 
    'DSPLVL', 
    'EGINPWR', 
    'EGINTY', 
    'EMPV_WGHT', 
    'FUEL', 
    'GEARBOX_KND',
    'MKR_NM', 
    'PLOR_NM', 
    'SRCMNNO', 
    'TKCAR_NMPR', 
    'TOT_WGHT', 
    'UPDT_DT', 
    'VHCL_HG',
    'VHCL_LT', 
    'VHCL_WH', 
    'VHCNM', 
    'VHCTY', 
    'VHCTY_CL', 
    'VHCTY_TY', 

    'REPCAR_NM', 
    'RMK', 
    'USER_ID'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['자동차 형식', 
    '승인 일자', 
    '생성 일시', 
    '적재 중량', 
    '삭제 YN', 
    '구동 형식', 
    '배기량', 
    '엔진출력', 
    '엔진형식', 
    '공차중량', 
    '연료', 
    '변속기 종류', 
    '제작사 명', 
    '원산지 명', 
    '제원관리번호', 
    '승차 인원', 
    '총 중량', 
    '수정 일시', 
    '차량 높이', 
    '차량 길이', 
    '차량 너비', 
    '차명', 
    '차종', 
    '차종 분류', 
    '차종 유형 (소분류)',
     
    '미정', 
    '미정', 
    '미정']
    }

ocol = pd.DataFrame(odict)
ocol

             컬럼           내용
0       CAR_FRM       자동차 형식
1      CNFRM_DE        승인 일자
2       CRTN_DT        생성 일시
3    CRYNG_WGHT        적재 중량
4       DELE_YN        삭제 YN
5       DRV_FRM        구동 형식
6        DSPLVL          배기량
7       EGINPWR         엔진출력
8        EGINTY         엔진형식
9     EMPV_WGHT         공차중량
10         FUEL           연료
11  GEARBOX_KND       변속기 종류
12       MKR_NM        제작사 명
13      PLOR_NM        원산지 명
14      SRCMNNO       제원관리번호
15   TKCAR_NMPR        승차 인원
16     TOT_WGHT         총 중량
17      UPDT_DT        수정 일시
18      VHCL_HG        차량 높이
19      VHCL_LT        차량 길이
20      VHCL_WH        차량 너비
21        VHCNM           차명
22        VHCTY           차종
23     VHCTY_CL        차종 분류
24     VHCTY_TY  차종 유형 (소분류)
25    REPCAR_NM           미정
26          RMK           미정
27      USER_ID           미정

In [152]:
sdf.columns.to_list()

['VHCL_FRM',
 'APRV_YMD',
 'VHCL_REG_DT',
 'CRYNG_WGHT',
 'DEL_YN',
 'VHCL_DRVE_FRM_CD',
 'DSPLVL',
 'EGIN_OTPT',
 'EGIN_TY',
 'EMPV_WGHT',
 'FUEL_CD',
 'GEARBOX_KND_CD',
 'MNFCTR_NM',
 'FBCTN_NTN_NM',
 'MANP_MNG_NO',
 'TKCAR_PSCP',
 'TOTL_WGHT',
 'MDFCN_DT',
 'OVRHG',
 'OVRLH',
 'OVRWD',
 'VHCNM',
 'VHCTY_CD',
 'VHCTY_CL_CD',
 'VHCTY_TY_CD2']

In [153]:
slist = [
    'VHCL_FRM', 
    'APRV_YMD', 
    'VHCL_REG_DT', 
    'CRYNG_WGHT', 
    'DEL_YN',
    'VHCL_DRVE_FRM_CD', 
    'DSPLVL', 
    'EGIN_OTPT', 
    'EGIN_TY', 
    'EMPV_WGHT',
    'FUEL_CD', 
    'GEARBOX_KND_CD', 
    'MNFCTR_NM', 
    'FBCTN_NTN_NM', 
    'MANP_MNG_NO',
    'TKCAR_PSCP', 
    'TOTL_WGHT', 
    'MDFCN_DT', 
    'OVRHG', 
    'OVRLH', 
    'OVRWD',
    'VHCNM', 
    'VHCTY_CD', 
    'VHCTY_CL_CD', 
    'VHCTY_TY_CD2'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차량형식', 
    '승인일자', 
    '차량등록일시', 
    '적재중량', 
    '삭제여부', 
    '차량구동형식코드', 
    '배기량', 
    '엔진출력', 
    '엔진형식', 
    '공차중량', 
    '연료코드', 
    '변속기종류코드', 
    '제작사명', 
    '제작국명', 
    '제원관리번호', 
    '승차정원', 
    '총중량', 
    '수정일시', 
    '전고', 
    '전장', 
    '전폭', 
    '차명', 
    '차종코드', 
    '차종분류코드', 
    '차종유형코드2']
    }

scol = pd.DataFrame(sdict)
scol

                  컬럼        내용
0           VHCL_FRM      차량형식
1           APRV_YMD      승인일자
2        VHCL_REG_DT    차량등록일시
3         CRYNG_WGHT      적재중량
4             DEL_YN      삭제여부
5   VHCL_DRVE_FRM_CD  차량구동형식코드
6             DSPLVL       배기량
7          EGIN_OTPT      엔진출력
8            EGIN_TY      엔진형식
9          EMPV_WGHT      공차중량
10           FUEL_CD      연료코드
11    GEARBOX_KND_CD   변속기종류코드
12         MNFCTR_NM      제작사명
13      FBCTN_NTN_NM      제작국명
14       MANP_MNG_NO    제원관리번호
15        TKCAR_PSCP      승차정원
16         TOTL_WGHT       총중량
17          MDFCN_DT      수정일시
18             OVRHG        전고
19             OVRLH        전장
20             OVRWD        전폭
21             VHCNM        차명
22          VHCTY_CD      차종코드
23       VHCTY_CL_CD    차종분류코드
24      VHCTY_TY_CD2   차종유형코드2

### 데이터 info

In [155]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_loss_count,STD_loss_count
0,CAR_FRM,자동차 형식,516295,VHCL_FRM,차량형식,516295.0,0.0,29079,29079.0
1,CNFRM_DE,승인 일자,532881,APRV_YMD,승인일자,532881.0,0.0,12493,12493.0
2,CRTN_DT,생성 일시,545374,VHCL_REG_DT,차량등록일시,545374.0,0.0,0,0.0
3,CRYNG_WGHT,적재 중량,446181,CRYNG_WGHT,적재중량,446181.0,0.0,99193,99193.0
4,DELE_YN,삭제 YN,545374,DEL_YN,삭제여부,545374.0,0.0,0,0.0

### [출력]

In [156]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 3\. 배출가스 인증정보(CEG_EMIS_CERTI_MIG)

In [157]:
name = 'CEG_EMIS_CERTI_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

23 21
(79725, 23) (79670, 21)

### 컬럼 확인

In [158]:
odf.columns.to_list()

['EMIS_CRTCNO',
 'EMIS_CRTC_SNO',
 'EMIS_CRTC_1_SE',
 'EMIS_CRTC_2_SE',
 'DMSTC_INCM_MKR_SE',
 'EMIS_VHCTY',
 'FUEL',
 'SAME_VHCTY_TY',
 'EMIS_CRTC_DE',
 'MKR_NM',
 'MNFCT_NM',
 'PLOR_NM',
 'EMIS_CRTC_STUS',
 'EMIS_CRTC_UNAVBL_DE',
 'EMIS_CRTC_UNAVBL_RESN',
 'ORGCAR_SRCMNNO',
 'REPCAR_EMIS_CRTCNO',
 'REPCAR_VIN',
 'EMIS_PERM_STDR_CD',
 'EMIS_GRD',
 'RECP_FILE_NM',
 'STRE_DE',
 'SRCMNNO']

In [159]:
olist = [
    'DMSTC_INCM_MKR_SE', 
    'EMIS_CRTCNO', 
    'EMIS_CRTC_1_SE', 
    'EMIS_CRTC_2_SE',
    'EMIS_CRTC_DE', 
    'EMIS_CRTC_SNO', 
    'EMIS_CRTC_STUS',
    'EMIS_CRTC_UNAVBL_DE', 
    'EMIS_CRTC_UNAVBL_RESN', 
    'EMIS_GRD',
    'EMIS_PERM_STDR_CD', 
    'EMIS_VHCTY', 
    'FUEL', 
    'MKR_NM', 
    'MNFCT_NM', 
    'ORGCAR_SRCMNNO',
    'PLOR_NM', 
    'REPCAR_EMIS_CRTCNO', 
    'REPCAR_VIN', 
    'SAME_VHCTY_TY',
    'STRE_DE', 
    
    'RECP_FILE_NM', 
    'SRCMNNO'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['국내 수입 제작사 구분', 
    '배출가스인증번호', 
    '배출가스 인증 1 구분', 
    '배출가스 인증 2 구분', 
    '배출가스 인증 일자', 
    '배출가스 인증 일련번호', 
    '배출가스 인증 상태', 
    '배출가스 인증 무효 일자', 
    '배출가스 인증 무효 사유', 
    '배출가스 등급', 
    '배출가스 허용 기준 코드', 
    '배출가스 차종', 
    '연료', 
    '제작사 명', 
    '제조사 명', 
    '기본차 제원관리번호', 
    '원산지 명', 
    '대표차 배출가스 인증번호', 
    '대표차 차대번호', 
    '동일 차종 유형', 
    '저장 일자',
     
    '미정', 
    '미정']
    }

ocol = pd.DataFrame(odict)
ocol

                       컬럼             내용
0       DMSTC_INCM_MKR_SE   국내 수입 제작사 구분
1             EMIS_CRTCNO       배출가스인증번호
2          EMIS_CRTC_1_SE   배출가스 인증 1 구분
3          EMIS_CRTC_2_SE   배출가스 인증 2 구분
4            EMIS_CRTC_DE     배출가스 인증 일자
5           EMIS_CRTC_SNO   배출가스 인증 일련번호
6          EMIS_CRTC_STUS     배출가스 인증 상태
7     EMIS_CRTC_UNAVBL_DE  배출가스 인증 무효 일자
8   EMIS_CRTC_UNAVBL_RESN  배출가스 인증 무효 사유
9                EMIS_GRD        배출가스 등급
10      EMIS_PERM_STDR_CD  배출가스 허용 기준 코드
11             EMIS_VHCTY        배출가스 차종
12                   FUEL             연료
13                 MKR_NM          제작사 명
14               MNFCT_NM          제조사 명
15         ORGCAR_SRCMNNO     기본차 제원관리번호
16                PLOR_NM          원산지 명
17     REPCAR_EMIS_CRTCNO  대표차 배출가스 인증번호
18             REPCAR_VIN       대표차 차대번호
19          SAME_VHCTY_TY       동일 차종 유형
20                STRE_DE          저장 일자
21           RECP_FILE_NM             미정
22                SRCMNNO             미정

In [160]:
sdf.columns.to_list()

['DMSTC_IMP_MNFCTR_SE',
 'EXHST_GAS_CERT_NO',
 'EXHST_GAS_CERT_SE1',
 'EXHST_GAS_CERT_SE2',
 'EXHST_GAS_CERT_YMD',
 'EXHST_GAS_CERT_SN',
 'EXTGAS_CET_STS_CD',
 'EXTGAS_CET_UNVBL_YMD',
 'EXTGAS_CET_UNVBL_REN',
 'EXHST_GAS_GRD',
 'EXTGAS_CET_PRM_CRTCD',
 'VHCTY_CD',
 'FUEL_CD',
 'MNFCTR_NM',
 'MKR_NAME',
 'MANP_MNG_NO',
 'FBCTN_NTN_NM',
 'RPRSVH_EXTGAS_CET_NO',
 'RPRS_CAR_VIN',
 'VHCTY_TY_CD',
 'DATA_STRG_YMD']

In [161]:
slist = [
    'DMSTC_IMP_MNFCTR_SE', 
    'EXHST_GAS_CERT_NO', 
    'EXHST_GAS_CERT_SE1',
    'EXHST_GAS_CERT_SE2', 
    'EXHST_GAS_CERT_YMD', 
    'EXHST_GAS_CERT_SN',
    'EXTGAS_CET_STS_CD', 
    'EXTGAS_CET_UNVBL_YMD', 
    'EXTGAS_CET_UNVBL_REN',
    'EXHST_GAS_GRD', 
    'EXTGAS_CET_PRM_CRTCD', 
    'VHCTY_CD', 
    'FUEL_CD',
    'MNFCTR_NM', 
    'MKR_NAME', 
    'MANP_MNG_NO', 
    'FBCTN_NTN_NM',
    'RPRSVH_EXTGAS_CET_NO', 
    'RPRS_CAR_VIN', 
    'VHCTY_TY_CD', 
    'DATA_STRG_YMD'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['국내수입제작사구분', 
    '배출가스인증번호', 
    '배출가스인증구분1', 
    '배출가스인증구분2', 
    '배출가스인증일자', 
    '배출가스인증일련번호', 
    '배출가스인증상태코드', 
    '배출가스인증무효사유', 
    '배출가스인증무효사유', 
    '배출가스등급', 
    '배출가스인증허용기준코드', 
    '차종코드', 
    '연료코드', 
    '제작사명', 
    '제조사명', 
    '제원관리번호', 
    '제작국명', 
    '대표차배출가스인증번호', 
    '대표차차대번호', 
    '차종유형코드', 
    '자료저장일자']
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼            내용
0    DMSTC_IMP_MNFCTR_SE     국내수입제작사구분
1      EXHST_GAS_CERT_NO      배출가스인증번호
2     EXHST_GAS_CERT_SE1     배출가스인증구분1
3     EXHST_GAS_CERT_SE2     배출가스인증구분2
4     EXHST_GAS_CERT_YMD      배출가스인증일자
5      EXHST_GAS_CERT_SN    배출가스인증일련번호
6      EXTGAS_CET_STS_CD    배출가스인증상태코드
7   EXTGAS_CET_UNVBL_YMD    배출가스인증무효사유
8   EXTGAS_CET_UNVBL_REN    배출가스인증무효사유
9          EXHST_GAS_GRD        배출가스등급
10  EXTGAS_CET_PRM_CRTCD  배출가스인증허용기준코드
11              VHCTY_CD          차종코드
12               FUEL_CD          연료코드
13             MNFCTR_NM          제작사명
14              MKR_NAME          제조사명
15           MANP_MNG_NO        제원관리번호
16          FBCTN_NTN_NM          제작국명
17  RPRSVH_EXTGAS_CET_NO   대표차배출가스인증번호
18          RPRS_CAR_VIN       대표차차대번호
19           VHCTY_TY_CD        차종유형코드
20         DATA_STRG_YMD        자료저장일자

### 데이터 info

In [162]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,OSD_loss_count,STD_loss_count
0,DMSTC_INCM_MKR_SE,국내 수입 제작사 구분,79038,DMSTC_IMP_MNFCTR_SE,국내수입제작사구분,78984.0,54.0,687,686.0
1,EMIS_CRTCNO,배출가스인증번호,79725,EXHST_GAS_CERT_NO,배출가스인증번호,79670.0,55.0,0,0.0
2,EMIS_CRTC_1_SE,배출가스 인증 1 구분,79725,EXHST_GAS_CERT_SE1,배출가스인증구분1,79670.0,55.0,0,0.0
3,EMIS_CRTC_2_SE,배출가스 인증 2 구분,79436,EXHST_GAS_CERT_SE2,배출가스인증구분2,79383.0,53.0,289,287.0
4,EMIS_CRTC_DE,배출가스 인증 일자,79670,EXHST_GAS_CERT_YMD,배출가스인증일자,79615.0,55.0,55,55.0

### [출력]

In [164]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 4\. 배출가스 인증시험(CEG_EMIS_CERTI_TEST_MIG)

In [173]:
name = 'CEG_EMIS_CERTI_TEST_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

23 21
(86406, 23) (86406, 21)

### 컬럼 확인

In [174]:
odf.columns.to_list()

['EMIS_CRTCNO',
 'EMIS_CRTC_SNO',
 'EMIS_TEST_MOD_VAL',
 'CO_PERM_STDR_VAL',
 'CO_TEST_RSLT',
 'NMOG_PERM_STDR_VAL',
 'NMOG_TEST_RSLT',
 'NMHC_PERM_STDR_VAL',
 'NMHC_TEST_RSLT',
 'HC_PERM_STDR_VAL',
 'HC_TEST_RSLT',
 'NOX_PERM_STDR_VAL',
 'NOX_TEST_RSLT',
 'NMOG_NOX_PERM_STDR_VAL',
 'NMOG_NOX_TEST_RSLT',
 'HC_NOX_PERM_STDR_VAL',
 'HC_NOX_TEST_RSLT',
 'PM_PERM_STDR_VAL',
 'PM_TEST_RSLT',
 'PN_PERM_STDR_VAL',
 'PN_TEST_RSLT',
 'RECP_FILE_NM',
 'STRE_DE']

In [175]:
olist = [
    'CO_PERM_STDR_VAL',
    'CO_TEST_RSLT', 
    'EMIS_CRTCNO', 
    'EMIS_CRTC_SNO', 
    'EMIS_TEST_MOD_VAL', 
    'HC_NOX_PERM_STDR_VAL',
    'HC_NOX_TEST_RSLT', 
    'HC_PERM_STDR_VAL',
    'HC_TEST_RSLT', 
    'NMHC_PERM_STDR_VAL', 
    'NMHC_TEST_RSLT', 
    'NMOG_NOX_PERM_STDR_VAL', 
    'NMOG_NOX_TEST_RSLT', 
    'NMOG_PERM_STDR_VAL', 
    'NMOG_TEST_RSLT',
    'NOX_PERM_STDR_VAL', 
    'NOX_TEST_RSLT',
    'PM_PERM_STDR_VAL', 
    'PM_TEST_RSLT',
    'PN_PERM_STDR_VAL', 
    'PN_TEST_RSLT', 

    'RECP_FILE_NM', 
    'STRE_DE'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['일산화탄소 허용 기준 값', 
    '일산화탄소 시험 결과', 
    '배출가스 인증번호', 
    '배출가스 인증 일련번호', 
    '배출가스 시험 모드 값', 
    '탄화수소3 질소산화물 허용 기준 값', 
    '탄화수소3 질소산화물 시험 결과', 
    '탄화수소3 허용 기준 값', 
    '탄화수소3 시험 결과', 
    '탄화수소2 허용 기준 값', 
    '탄화수소2 시험 결과', 
    '탄화수소1 질소산화물 허용 기준 값', 
    '탄화수소1 질소산화물 시험 결과', 
    '탄화수소1 허용 기준 값', 
    '탄화수소1 시험 결과', 
    '질소산화물 허용 기준 값', 
    '질소산화물 시험 결과', 
    '입자상물질 허용 기준 값', 
    '입자상물질 시험 결과', 
    '입자개수 허용 기준 값', 
    '입자개수 시험 결과',
     
    '미정', 
    '미정']
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼                   내용
0         CO_PERM_STDR_VAL        일산화탄소 허용 기준 값
1             CO_TEST_RSLT          일산화탄소 시험 결과
2              EMIS_CRTCNO            배출가스 인증번호
3            EMIS_CRTC_SNO         배출가스 인증 일련번호
4        EMIS_TEST_MOD_VAL         배출가스 시험 모드 값
5     HC_NOX_PERM_STDR_VAL  탄화수소3 질소산화물 허용 기준 값
6         HC_NOX_TEST_RSLT    탄화수소3 질소산화물 시험 결과
7         HC_PERM_STDR_VAL        탄화수소3 허용 기준 값
8             HC_TEST_RSLT          탄화수소3 시험 결과
9       NMHC_PERM_STDR_VAL        탄화수소2 허용 기준 값
10          NMHC_TEST_RSLT          탄화수소2 시험 결과
11  NMOG_NOX_PERM_STDR_VAL  탄화수소1 질소산화물 허용 기준 값
12      NMOG_NOX_TEST_RSLT    탄화수소1 질소산화물 시험 결과
13      NMOG_PERM_STDR_VAL        탄화수소1 허용 기준 값
14          NMOG_TEST_RSLT          탄화수소1 시험 결과
15       NOX_PERM_STDR_VAL        질소산화물 허용 기준 값
16           NOX_TEST_RSLT          질소산화물 시험 결과
17        PM_PERM_STDR_VAL        입자상물질 허용 기준 값
18            PM_TEST_RSLT          입자상물질 시험 결과
19        PN_PERM_STDR_VAL         입자개수 허용 기준 값
20            PN_TEST_RSLT           입자개수 시험 결과
21            RECP_FILE_NM                   미정
22                 STRE_DE                   미정

In [176]:
sdf.columns.to_list()

['COX_PRMT_VAL',
 'COX_TEST_RSLT',
 'EXHST_GAS_CERT_NO',
 'EXHST_GAS_CERT_SN',
 'FBVH_EXTGAS_TES_TYCD',
 'HC3_NOX_PRMT_VAL',
 'HC3_NOX_TES_RSLTVL',
 'HC3_PRMT_VAL',
 'HC3_TEST_RSLT_VAL',
 'HC2_PRMT_VAL',
 'HC2_TEST_RSLT_VAL',
 'HC1_NOX_PRMT_VAL',
 'HC1_NOX_TES_RSLTVL',
 'HC1_PRMT_VAL',
 'HC_TEST_RSLT_VAL',
 'NOX_PRMT_VAL',
 'NOX_TEST_RSLT_VAL',
 'PM_CRTR_VAL',
 'PM_CRTR',
 'PARTCL_CNT_CRTR_VAL',
 'PN_CRTR']

In [177]:
slist = [
    'COX_PRMT_VAL', 
    'COX_TEST_RSLT', 
    'EXHST_GAS_CERT_NO',
    'EXHST_GAS_CERT_SN', 
    'FBVH_EXTGAS_TES_TYCD', 
    'HC3_NOX_PRMT_VAL',
    'HC3_NOX_TES_RSLTVL', 
    'HC3_PRMT_VAL', 
    'HC3_TEST_RSLT_VAL',
    'HC2_PRMT_VAL', 
    'HC2_TEST_RSLT_VAL', 
    'HC1_NOX_PRMT_VAL',
    'HC1_NOX_TES_RSLTVL', 
    'HC1_PRMT_VAL', 
    'HC_TEST_RSLT_VAL',
    'NOX_PRMT_VAL', 
    'NOX_TEST_RSLT_VAL', 
    'PM_CRTR_VAL', 
    'PM_CRTR',
    'PARTCL_CNT_CRTR_VAL', 
    'PN_CRTR'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['일산화탅소허용기준값', 
    '일산화탅소시험결과', 
    '배출가스인증번호', 
    '배출가스인증일련번호', 
    '제작차배출가스시험유형코드', 
    '탄화수소3질소산화물허용값', 
    '탄화수소3질소산화물시험결과값', 
    '탄화수소3허용값', 
    '탄화수소3시험결과값', 
    '탄화수소2허용값', 
    '탄화수소2시험결과값', 
    '탄화수소1질소산화물허용값', 
    '탄화수소1질소산화물시험결과값', 
    '탄화수소1허용값', 
    '탄화수소시험결과값', 
    '질소산화물허용값', 
    '질소산화물시험결과값', 
    'PM기준값', 
    'PM기준', 
    '입자개수기준값', 
    'PM기준']
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼               내용
0           COX_PRMT_VAL       일산화탅소허용기준값
1          COX_TEST_RSLT        일산화탅소시험결과
2      EXHST_GAS_CERT_NO         배출가스인증번호
3      EXHST_GAS_CERT_SN       배출가스인증일련번호
4   FBVH_EXTGAS_TES_TYCD    제작차배출가스시험유형코드
5       HC3_NOX_PRMT_VAL    탄화수소3질소산화물허용값
6     HC3_NOX_TES_RSLTVL  탄화수소3질소산화물시험결과값
7           HC3_PRMT_VAL         탄화수소3허용값
8      HC3_TEST_RSLT_VAL       탄화수소3시험결과값
9           HC2_PRMT_VAL         탄화수소2허용값
10     HC2_TEST_RSLT_VAL       탄화수소2시험결과값
11      HC1_NOX_PRMT_VAL    탄화수소1질소산화물허용값
12    HC1_NOX_TES_RSLTVL  탄화수소1질소산화물시험결과값
13          HC1_PRMT_VAL         탄화수소1허용값
14      HC_TEST_RSLT_VAL        탄화수소시험결과값
15          NOX_PRMT_VAL         질소산화물허용값
16     NOX_TEST_RSLT_VAL       질소산화물시험결과값
17           PM_CRTR_VAL            PM기준값
18               PM_CRTR             PM기준
19   PARTCL_CNT_CRTR_VAL          입자개수기준값
20               PN_CRTR             PM기준

### 데이터 info

In [182]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CO_PERM_STDR_VAL,일산화탄소 허용 기준 값,16761,COX_PRMT_VAL,일산화탅소허용기준값,16761.0,0.0,69645,69645.0
1,CO_TEST_RSLT,일산화탄소 시험 결과,17868,COX_TEST_RSLT,일산화탅소시험결과,17868.0,0.0,68538,68538.0
2,EMIS_CRTCNO,배출가스 인증번호,86406,EXHST_GAS_CERT_NO,배출가스인증번호,86406.0,0.0,0,0.0
3,EMIS_CRTC_SNO,배출가스 인증 일련번호,86406,EXHST_GAS_CERT_SN,배출가스인증일련번호,86406.0,0.0,0,0.0
4,EMIS_TEST_MOD_VAL,배출가스 시험 모드 값,85442,FBVH_EXTGAS_TES_TYCD,제작차배출가스시험유형코드,85442.0,0.0,964,964.0

### [출력]

In [183]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 5\. [e]배출가스인증 자동차정보(CEG_EMIS_CERTI_VEH_MIG)
- 파일 없음 : STD_CEG_EMIS_CERTI_VEH_MIG.csv

In [ ]:
name = 'CEG_EMIS_CERTI_VEH_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

### 컬럼 확인

In [ ]:
odf.columns.to_list()

In [ ]:
olist = [
    'CO_PERM_STDR_VAL',
    'CO_TEST_RSLT', 
    'EMIS_CRTCNO', 
    'EMIS_CRTC_SNO', 
    'EMIS_TEST_MOD_VAL', 
    'HC_NOX_PERM_STDR_VAL',
    'HC_NOX_TEST_RSLT', 
    'HC_PERM_STDR_VAL',
    'HC_TEST_RSLT', 
    'NMHC_PERM_STDR_VAL', 
    'NMHC_TEST_RSLT', 
    'NMOG_NOX_PERM_STDR_VAL', 
    'NMOG_NOX_TEST_RSLT', 
    'NMOG_PERM_STDR_VAL', 
    'NMOG_TEST_RSLT',
    'NOX_PERM_STDR_VAL', 
    'NOX_TEST_RSLT',
    'PM_PERM_STDR_VAL', 
    'PM_TEST_RSLT',
    'PN_PERM_STDR_VAL', 
    'PN_TEST_RSLT', 

    'RECP_FILE_NM', 
    'STRE_DE'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['일산화탄소 허용 기준 값', 
    '일산화탄소 시험 결과', 
    '배출가스 인증번호', 
    '배출가스 인증 일련번호', 
    '배출가스 시험 모드 값', 
    '탄화수소3 질소산화물 허용 기준 값', 
    '탄화수소3 질소산화물 시험 결과', 
    '탄화수소3 허용 기준 값', 
    '탄화수소3 시험 결과', 
    '탄화수소2 허용 기준 값', 
    '탄화수소2 시험 결과', 
    '탄화수소1 질소산화물 허용 기준 값', 
    '탄화수소1 질소산화물 시험 결과', 
    '탄화수소1 허용 기준 값', 
    '탄화수소1 시험 결과', 
    '질소산화물 허용 기준 값', 
    '질소산화물 시험 결과', 
    '입자상물질 허용 기준 값', 
    '입자상물질 시험 결과', 
    '입자개수 허용 기준 값', 
    '입자개수 시험 결과',
     
    '미정', 
    '미정']
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼                   내용
0         CO_PERM_STDR_VAL        일산화탄소 허용 기준 값
1             CO_TEST_RSLT          일산화탄소 시험 결과
2              EMIS_CRTCNO            배출가스 인증번호
3            EMIS_CRTC_SNO         배출가스 인증 일련번호
4        EMIS_TEST_MOD_VAL         배출가스 시험 모드 값
5     HC_NOX_PERM_STDR_VAL  탄화수소3 질소산화물 허용 기준 값
6         HC_NOX_TEST_RSLT    탄화수소3 질소산화물 시험 결과
7         HC_PERM_STDR_VAL        탄화수소3 허용 기준 값
8             HC_TEST_RSLT          탄화수소3 시험 결과
9       NMHC_PERM_STDR_VAL        탄화수소2 허용 기준 값
10          NMHC_TEST_RSLT          탄화수소2 시험 결과
11  NMOG_NOX_PERM_STDR_VAL  탄화수소1 질소산화물 허용 기준 값
12      NMOG_NOX_TEST_RSLT    탄화수소1 질소산화물 시험 결과
13      NMOG_PERM_STDR_VAL        탄화수소1 허용 기준 값
14          NMOG_TEST_RSLT          탄화수소1 시험 결과
15       NOX_PERM_STDR_VAL        질소산화물 허용 기준 값
16           NOX_TEST_RSLT          질소산화물 시험 결과
17        PM_PERM_STDR_VAL        입자상물질 허용 기준 값
18            PM_TEST_RSLT          입자상물질 시험 결과
19        PN_PERM_STDR_VAL         입자개수 허용 기준 값
20            PN_TEST_RSLT           입자개수 시험 결과
21            RECP_FILE_NM                   미정
22                 STRE_DE                   미정

In [ ]:
sdf.columns.to_list()

In [ ]:
slist = [
    'COX_PRMT_VAL', 
    'COX_TEST_RSLT', 
    'EXHST_GAS_CERT_NO',
    'EXHST_GAS_CERT_SN', 
    'FBVH_EXTGAS_TES_TYCD', 
    'HC3_NOX_PRMT_VAL',
    'HC3_NOX_TES_RSLTVL', 
    'HC3_PRMT_VAL', 
    'HC3_TEST_RSLT_VAL',
    'HC2_PRMT_VAL', 
    'HC2_TEST_RSLT_VAL', 
    'HC1_NOX_PRMT_VAL',
    'HC1_NOX_TES_RSLTVL', 
    'HC1_PRMT_VAL', 
    'HC_TEST_RSLT_VAL',
    'NOX_PRMT_VAL', 
    'NOX_TEST_RSLT_VAL', 
    'PM_CRTR_VAL', 
    'PM_CRTR',
    'PARTCL_CNT_CRTR_VAL', 
    'PN_CRTR'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['일산화탅소허용기준값', 
    '일산화탅소시험결과', 
    '배출가스인증번호', 
    '배출가스인증일련번호', 
    '제작차배출가스시험유형코드', 
    '탄화수소3질소산화물허용값', 
    '탄화수소3질소산화물시험결과값', 
    '탄화수소3허용값', 
    '탄화수소3시험결과값', 
    '탄화수소2허용값', 
    '탄화수소2시험결과값', 
    '탄화수소1질소산화물허용값', 
    '탄화수소1질소산화물시험결과값', 
    '탄화수소1허용값', 
    '탄화수소시험결과값', 
    '질소산화물허용값', 
    '질소산화물시험결과값', 
    'PM기준값', 
    'PM기준', 
    '입자개수기준값', 
    'PM기준']
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼               내용
0           COX_PRMT_VAL       일산화탅소허용기준값
1          COX_TEST_RSLT        일산화탅소시험결과
2      EXHST_GAS_CERT_NO         배출가스인증번호
3      EXHST_GAS_CERT_SN       배출가스인증일련번호
4   FBVH_EXTGAS_TES_TYCD    제작차배출가스시험유형코드
5       HC3_NOX_PRMT_VAL    탄화수소3질소산화물허용값
6     HC3_NOX_TES_RSLTVL  탄화수소3질소산화물시험결과값
7           HC3_PRMT_VAL         탄화수소3허용값
8      HC3_TEST_RSLT_VAL       탄화수소3시험결과값
9           HC2_PRMT_VAL         탄화수소2허용값
10     HC2_TEST_RSLT_VAL       탄화수소2시험결과값
11      HC1_NOX_PRMT_VAL    탄화수소1질소산화물허용값
12    HC1_NOX_TES_RSLTVL  탄화수소1질소산화물시험결과값
13          HC1_PRMT_VAL         탄화수소1허용값
14      HC_TEST_RSLT_VAL        탄화수소시험결과값
15          NOX_PRMT_VAL         질소산화물허용값
16     NOX_TEST_RSLT_VAL       질소산화물시험결과값
17           PM_CRTR_VAL            PM기준값
18               PM_CRTR             PM기준
19   PARTCL_CNT_CRTR_VAL          입자개수기준값
20               PN_CRTR             PM기준

### 데이터 info

In [ ]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

### [출력]

In [ ]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 6\. 제작차 배출 허용 기준(CEG_EMIS_STD_MIG)

In [184]:
name = 'CEG_EMIS_STD_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

21 21
(1212, 21) (1212, 21)

### 컬럼 확인

In [185]:
odf.columns.to_list()

['EMIS_PERM_STDR_CD',
 'EMIS_PERM_STDR_SML_SE',
 'FUEL_GRP',
 'EMIS_VHCTY',
 'TEST_BGIN_WGHT',
 'TEST_END_WGHT',
 'APLI_DE',
 'EMIS_TEST_MOD_VAL',
 'CO_PERM_STDR_VAL',
 'NMOG_PERM_STDR_VAL',
 'NMHC_PERM_STDR_VAL',
 'HC_PERM_STDR_VAL',
 'NOX_PERM_STDR_VAL',
 'NMOG_NOX_PERM_STDR_VAL',
 'HC_NOX_PERM_STDR_VAL',
 'PM_PERM_STDR_VAL',
 'PN_PERM_STDR_VAL',
 'EMIS_PERM_STDR_SE',
 'EMIS_GRD_USE_YN',
 'EMIS_GRD',
 'EMIS_PERM_STDR_LEVL']

In [186]:
olist = [
    'APLI_DE',
    'TEST_END_WGHT',
    'TEST_BGIN_WGHT',
    'PN_PERM_STDR_VAL',
    'PM_PERM_STDR_VAL',
    'CO_PERM_STDR_VAL',
    'NMOG_PERM_STDR_VAL',
    'NOX_PERM_STDR_VAL',
    'EMIS_GRD',
    'EMIS_GRD_USE_YN',
    'EMIS_PERM_STDR_CD',
    'EMIS_PERM_STDR_LEVL',
    'EMIS_PERM_STDR_SE',
    'EMIS_VHCTY',
    'EMIS_TEST_MOD_VAL',
    'EMIS_PERM_STDR_SML_SE',
    'FUEL_GRP',
    'HC_NOX_PERM_STDR_VAL',
    'HC_PERM_STDR_VAL',
    'NMHC_PERM_STDR_VAL',
    'NMOG_NOX_PERM_STDR_VAL'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['적용 일자',
    '시험 끝 중량',
    '시험 시작 중량',
    '입자개수 허용 기준 값',
    '입자상물질 허용 기준 값',
    '일산화탄소 허용 기준 값',
    '탄화수소1 허용 기준 값',
    '질소산화물 허용 기준 값',
    '배출가스 등급',
    '배출가스 등급 사용 YN',
    '배출가스 허용 기준 코드',
    '배출가스 허용 기준 수준',
    '배출가스 허용 기준 구분',
    '배출가스 차종',
    '배출가스 시험 모드 값',
    '배출가스 허용 기준 소 구분',
    '연료 그룹',
    '탄화수소3 질소산화물 허용 기준 값',
    '탄화수소3 허용기준 값',
    '탄화수소2 허용 기준 값',
    '탄화수소1 질소산화물 허용 기준 값']
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼                   내용
0                  APLI_DE                적용 일자
1            TEST_END_WGHT              시험 끝 중량
2           TEST_BGIN_WGHT             시험 시작 중량
3         PN_PERM_STDR_VAL         입자개수 허용 기준 값
4         PM_PERM_STDR_VAL        입자상물질 허용 기준 값
5         CO_PERM_STDR_VAL        일산화탄소 허용 기준 값
6       NMOG_PERM_STDR_VAL        탄화수소1 허용 기준 값
7        NOX_PERM_STDR_VAL        질소산화물 허용 기준 값
8                 EMIS_GRD              배출가스 등급
9          EMIS_GRD_USE_YN        배출가스 등급 사용 YN
10       EMIS_PERM_STDR_CD        배출가스 허용 기준 코드
11     EMIS_PERM_STDR_LEVL        배출가스 허용 기준 수준
12       EMIS_PERM_STDR_SE        배출가스 허용 기준 구분
13              EMIS_VHCTY              배출가스 차종
14       EMIS_TEST_MOD_VAL         배출가스 시험 모드 값
15   EMIS_PERM_STDR_SML_SE      배출가스 허용 기준 소 구분
16                FUEL_GRP                연료 그룹
17    HC_NOX_PERM_STDR_VAL  탄화수소3 질소산화물 허용 기준 값
18        HC_PERM_STDR_VAL         탄화수소3 허용기준 값
19      NMHC_PERM_STDR_VAL        탄화수소2 허용 기준 값
20  NMOG_NOX_PERM_STDR_VAL  탄화수소1 질소산화물 허용 기준 값

In [187]:
sdf.columns.to_list()

['APLCN_YMD',
 'COX_PRMT_VAL',
 'EXHST_GAS_GRD_CD',
 'EXHST_GAS_GRD_USE_YN',
 'EXHST_GAS_CERT_PRMT_CRTR_CD',
 'EXHST_GAS_CERT_PRMT_CRTR_LEVL',
 'EXHST_GAS_CERT_PRMT_CRTR_SE',
 'EXHST_GAS_CERT_PRMT_CRTRSCL_SE',
 'EXHST_GAS_TEST_MOD',
 'EXHST_GAS_INSP_VHCTY',
 'FUEL_CL_CD',
 'HC3_NOX_PRMT_VAL',
 'HC3_PRMT_VAL',
 'HC2_PRMT_VAL',
 'HC1_NOX_PRMT_VAL',
 'HC1_PRMT_VAL',
 'NOX_PRMT_VAL',
 'PARTCLT_PRMT_VAL',
 'PARTCL_CNT_CRTR_VAL',
 'TEST_BGNG_WGHT',
 'TEST_END_WGHT']

In [188]:
slist = [
    'APLCN_YMD',
    'TEST_END_WGHT',
    'TEST_BGNG_WGHT',
    'PARTCL_CNT_CRTR_VAL',
    'PARTCLT_PRMT_VAL',
    'COX_PRMT_VAL',
    'HC1_PRMT_VAL',
    'NOX_PRMT_VAL',
    'EXHST_GAS_GRD_CD',
    'EXHST_GAS_GRD_USE_YN',
    'EXHST_GAS_CERT_PRMT_CRTR_CD',
    'EXHST_GAS_CERT_PRMT_CRTR_LEVL',
    'EXHST_GAS_CERT_PRMT_CRTR_SE',
    'EXHST_GAS_INSP_VHCTY',
    'EXHST_GAS_TEST_MOD',
    'EXHST_GAS_CERT_PRMT_CRTRSCL_SE',
    'FUEL_CL_CD',
    'HC3_NOX_PRMT_VAL',
    'HC3_PRMT_VAL',
    'HC2_PRMT_VAL',
    'HC1_NOX_PRMT_VAL'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['적용일자',
    '시험종료중량',
    '시험시작중량',
    '입자개수기준값',
    '입자상허용값',
    '일산화탄소허용기준값',
    '탄화수소1허용값',
    '질소산화물허용값',
    '배출가스등급코드',
    '배출가스등급사용여부',
    '배출가스인증허용기준코드',
    '배출가스인증허용기준수준',
    '배출가스인증허용기준구분',
    '배출가스검사차종',
    '배출가스시험모드',
    '배출가스인증허용기준소분류구분',
    '연료분류코드',
    '탄화수소3질소산화물허용값',
    '탄화수소3허용값',
    '탄화수소2허용값',
    '탄화수소1질소산화물허용값']
    }

scol = pd.DataFrame(sdict)
scol

                                컬럼               내용
0                        APLCN_YMD             적용일자
1                    TEST_END_WGHT           시험종료중량
2                   TEST_BGNG_WGHT           시험시작중량
3              PARTCL_CNT_CRTR_VAL          입자개수기준값
4                 PARTCLT_PRMT_VAL           입자상허용값
5                     COX_PRMT_VAL       일산화탄소허용기준값
6                     HC1_PRMT_VAL         탄화수소1허용값
7                     NOX_PRMT_VAL         질소산화물허용값
8                 EXHST_GAS_GRD_CD         배출가스등급코드
9             EXHST_GAS_GRD_USE_YN       배출가스등급사용여부
10     EXHST_GAS_CERT_PRMT_CRTR_CD     배출가스인증허용기준코드
11   EXHST_GAS_CERT_PRMT_CRTR_LEVL     배출가스인증허용기준수준
12     EXHST_GAS_CERT_PRMT_CRTR_SE     배출가스인증허용기준구분
13            EXHST_GAS_INSP_VHCTY         배출가스검사차종
14              EXHST_GAS_TEST_MOD         배출가스시험모드
15  EXHST_GAS_CERT_PRMT_CRTRSCL_SE  배출가스인증허용기준소분류구분
16                      FUEL_CL_CD           연료분류코드
17                HC3_NOX_PRMT_VAL    탄화수소3질소산화물허용값
18                    HC3_PRMT_VAL         탄화수소3허용값
19                    HC2_PRMT_VAL         탄화수소2허용값
20                HC1_NOX_PRMT_VAL    탄화수소1질소산화물허용값

### 데이터 info

In [189]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,APLI_DE,적용 일자,1212,APLCN_YMD,적용일자,1212,0,0,0
1,TEST_END_WGHT,시험 끝 중량,1212,TEST_END_WGHT,시험종료중량,1212,0,0,0
2,TEST_BGIN_WGHT,시험 시작 중량,1212,TEST_BGNG_WGHT,시험시작중량,1212,0,0,0
3,PN_PERM_STDR_VAL,입자개수 허용 기준 값,64,PARTCL_CNT_CRTR_VAL,입자개수기준값,64,0,1148,1148
4,PM_PERM_STDR_VAL,입자상물질 허용 기준 값,651,PARTCLT_PRMT_VAL,입자상허용값,651,0,561,561

### [출력]

In [190]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 7\. 대표차명(CEG_STD_CAR_MIG)

In [191]:
name = 'CEG_STD_CAR_MIG'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

7 7
(1541, 7) (1541, 7)

In [192]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS     7  1541
STD     7  1541

### 컬럼 확인

In [193]:
odf.columns.to_list()

['REPCAR_NM', 'MKR_NM', 'PLOR_NM', 'RMK', 'CRTN_DT', 'UPDT_DT', 'USER_ID']

In [194]:
olist = [
    'USER_ID',
    'UPDT_DT', 
    'RMK', 
    'REPCAR_NM', 
    'PLOR_NM', 
    'MKR_NM', 
    'CRTN_DT', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['사용자 아이디',
    '수정 일시', 
    '비고', 
    '대표차 명', 
    '원산지 명', 
    '제작사 명', 
    '생성 일시',]
    }

ocol = pd.DataFrame(odict)
ocol

          컬럼       내용
0    USER_ID  사용자 아이디
1    UPDT_DT    수정 일시
2        RMK       비고
3  REPCAR_NM    대표차 명
4    PLOR_NM    원산지 명
5     MKR_NM    제작사 명
6    CRTN_DT    생성 일시

In [195]:
sdf.columns.to_list()

['MNFCTR_NM', 'PLOR_NM', 'RPRS_VHCNM', 'RMK', 'MDFCN_DT', 'USER_ID', 'CRT_DT']

In [196]:
slist = [
    'USER_ID', 
    'MDFCN_DT', 
    'RMK', 
    'RPRS_VHCNM', 
    'PLOR_NM', 
    'MNFCTR_NM', 
    'CRT_DT',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['사용자ID', 
    '수정일시', 
    '비고', 
    '대표차명', 
    '원산지명', 
    '제작사명', 
    '생성일시',]
    }

scol = pd.DataFrame(sdict)
scol

           컬럼     내용
0     USER_ID  사용자ID
1    MDFCN_DT   수정일시
2         RMK     비고
3  RPRS_VHCNM   대표차명
4     PLOR_NM   원산지명
5   MNFCTR_NM   제작사명
6      CRT_DT   생성일시

### 데이터 info

In [197]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,USER_ID,사용자 아이디,1541,USER_ID,사용자ID,1541,0,0,0
1,UPDT_DT,수정 일시,6,MDFCN_DT,수정일시,6,0,1535,1535
2,RMK,비고,90,RMK,비고,90,0,1451,1451
3,REPCAR_NM,대표차 명,1541,RPRS_VHCNM,대표차명,1541,0,0,0
4,PLOR_NM,원산지 명,1541,PLOR_NM,원산지명,1541,0,0,0

### [출력]

In [198]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 8\. 저감장치 클리닝 상세 정보(DLM_TB_ERP_CLEANING_DTL)

In [199]:
name = 'DLM_TB_ERP_CLEANING_DTL'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

59 13
(896011, 59) (897348, 13)

In [200]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS    59  896011
STD    13  897348

### 컬럼 확인

In [201]:
odf.columns.to_list()

['REDUC_REG_NO',
 'CLNING_MNGT_NO',
 'MKR_CD',
 'CLNING_DE',
 'CLNING_KND',
 'CLNING_CST',
 'CLNING_ENTRPS_NM',
 'DRVNG_DSTNC',
 'CLNING_PRGRE_STUS',
 'SBSIDY_TRGT_YN',
 'SBSIDY_TRGT_EXCLU_RESN',
 'LOCGOV_CNFRM_DE',
 'LOCGOV_CNFRMR_NM',
 'MKR_PAPE_ATT_YN',
 'SBSIDY_PYMT_DCSN_DE',
 'SBSIDY_PYMT_IDNTFR_NM',
 'CTNT',
 'CLNING_BTRC_TRGT_YN',
 'CLNING_BTRC_RESN',
 'INPT_DE',
 'RETR_NM',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'CLNING_LST_DE',
 'CLNING_WHL_SE',
 'CLNING_RMND_SBSIDY',
 'BF_SMO_DNSTY',
 'PST_SMO_DNSTY',
 'BF_VENTL_PSSR',
 'PST_VENTL_PSSR',
 'CLNING_RQEST_GRP_NO',
 'SBSIDY_RQT_DE',
 'SBSIDY_APLICT_NM',
 'CLNING_PYMT_DE',
 'CLNING_BIZ_YR',
 'CLNING_PYMT_YN',
 'CLNING_GRNTY_WHL_SE',
 'CLNING_REC_CNT_ELPSD',
 'INST_ID',
 'CLNING_SPEL_RESN_RESN',
 'CLNING_ETC_SPEL_RESN',
 'RCPT_LOCGOV_CD',
 'NOW_VHRNO',
 'STRCHG_DE',
 'RMK',
 'CLNING_WHL_ETC_SE',
 'CHK_YN',
 'CHK_YN1',
 'EXCA_YR',
 'EXCA_DE',
 'EXCA_YN',
 'EXCA_ETC',
 'ASOC_RQT_YN',
 'CHG_EQUIP_SER_NO',
 'M_CHK_PLAN_MONTH',
 'ATT_LGCLFL',
 'ATT_PHYSCL',
 'DELETE_YN',
 'DELETE_REASON']

In [202]:
olist = [
    'CLNING_GRNTY_WHL_SE',
    'CLNING_KND',
    'CLNING_ENTRPS_NM',
    'CLNING_DE',
    'SBSIDY_TRGT_YN',
    'BF_SMO_DNSTY',
    'BF_VENTL_PSSR',
    'REDUC_REG_NO',
    'PST_VENTL_PSSR',
    'CLNING_PRGRE_STUS',
    'DRVNG_DSTNC',
    'PST_SMO_DNSTY',

    'CLNING_MNGT_NO',
    'MKR_CD',
    'CLNING_CST',
    'SBSIDY_TRGT_EXCLU_RESN',
    'LOCGOV_CNFRM_DE',
    'LOCGOV_CNFRMR_NM',
    'MKR_PAPE_ATT_YN',
    'SBSIDY_PYMT_DCSN_DE',
    'SBSIDY_PYMT_IDNTFR_NM',
    'CTNT',
    'CLNING_BTRC_TRGT_YN',
    'CLNING_BTRC_RESN',
    'INPT_DE',
    'RETR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'CLNING_LST_DE',
    'CLNING_WHL_SE',
    'CLNING_RMND_SBSIDY',
    'CLNING_RQEST_GRP_NO',
    'SBSIDY_RQT_DE',
    'SBSIDY_APLICT_NM',
    'CLNING_PYMT_DE',
    'CLNING_BIZ_YR',
    'CLNING_PYMT_YN',
    'CLNING_REC_CNT_ELPSD',
    'INST_ID',
    'CLNING_SPEL_RESN_RESN',
    'CLNING_ETC_SPEL_RESN',
    'RCPT_LOCGOV_CD',
    'NOW_VHRNO',
    'STRCHG_DE',
    'RMK',
    'CLNING_WHL_ETC_SE',
    'CHK_YN',
    'CHK_YN1',
    'EXCA_YR',
    'EXCA_DE',
    'EXCA_YN',
    'EXCA_ETC',
    'ASOC_RQT_YN',
    'CHG_EQUIP_SER_NO',
    'M_CHK_PLAN_MONTH',
    'ATT_LGCLFL',
    'ATT_PHYSCL',
    'DELETE_YN',
    'DELETE_REASON', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['클리닝보증기간구분',
    '클리닝종류',
    '클리닝업체명',
    '클리닝일자',
    '보조금대상YN',
    '전매연농도',
    '전배기압력',
    '저감등록번호',
    '후배기압력',
    '클리닝진행상태',
    '주행거리',
    '후매연농도',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼         내용
0      CLNING_GRNTY_WHL_SE  클리닝보증기간구분
1               CLNING_KND      클리닝종류
2         CLNING_ENTRPS_NM     클리닝업체명
3                CLNING_DE      클리닝일자
4           SBSIDY_TRGT_YN    보조금대상YN
5             BF_SMO_DNSTY      전매연농도
6            BF_VENTL_PSSR      전배기압력
7             REDUC_REG_NO     저감등록번호
8           PST_VENTL_PSSR      후배기압력
9        CLNING_PRGRE_STUS    클리닝진행상태
10             DRVNG_DSTNC       주행거리
11           PST_SMO_DNSTY      후매연농도
12          CLNING_MNGT_NO         미정
13                  MKR_CD         미정
14              CLNING_CST         미정
15  SBSIDY_TRGT_EXCLU_RESN         미정
16         LOCGOV_CNFRM_DE         미정
17        LOCGOV_CNFRMR_NM         미정
18         MKR_PAPE_ATT_YN         미정
19     SBSIDY_PYMT_DCSN_DE         미정
20   SBSIDY_PYMT_IDNTFR_NM         미정
21                    CTNT         미정
22     CLNING_BTRC_TRGT_YN         미정
23        CLNING_BTRC_RESN         미정
24                 INPT_DE         미정
25                 RETR_NM         미정
26             LST_CHNG_DE         미정
27             LST_EDIR_NM         미정
28           CLNING_LST_DE         미정
29           CLNING_WHL_SE         미정
30      CLNING_RMND_SBSIDY         미정
31     CLNING_RQEST_GRP_NO         미정
32           SBSIDY_RQT_DE         미정
33        SBSIDY_APLICT_NM         미정
34          CLNING_PYMT_DE         미정
35           CLNING_BIZ_YR         미정
36          CLNING_PYMT_YN         미정
37    CLNING_REC_CNT_ELPSD         미정
38                 INST_ID         미정
39   CLNING_SPEL_RESN_RESN         미정
40    CLNING_ETC_SPEL_RESN         미정
41          RCPT_LOCGOV_CD         미정
42               NOW_VHRNO         미정
43               STRCHG_DE         미정
44                     RMK         미정
45       CLNING_WHL_ETC_SE         미정
46                  CHK_YN         미정
47                 CHK_YN1         미정
48                 EXCA_YR         미정
49                 EXCA_DE         미정
50                 EXCA_YN         미정
51                EXCA_ETC         미정
52             ASOC_RQT_YN         미정
53        CHG_EQUIP_SER_NO         미정
54        M_CHK_PLAN_MONTH         미정
55              ATT_LGCLFL         미정
56              ATT_PHYSCL         미정
57               DELETE_YN         미정
58           DELETE_REASON         미정

In [203]:
sdf.columns.to_list()

['BF_SMO_CCNTRA',
 'BF_VENTL_PSSR',
 'CLNING_YMD',
 'CLNING_ENTRPS_NM',
 'CLNING_GRNTE_WHL_SE_CD',
 'CLNING_KND_CD',
 'CLNING_PRGRS_STTS',
 'DRVNG_DSTNC',
 'PST_SMO_CCNTRA',
 'PST_VENTL_PSSR',
 'REDUC_REG_NO',
 'SBSIDY_TRGT_YN',
 'CRTN_DT']

In [204]:
slist = [
    'CLNING_GRNTE_WHL_SE_CD',
    'CLNING_KND_CD',
    'CLNING_ENTRPS_NM',
    'CLNING_YMD',
    'SBSIDY_TRGT_YN',
    'BF_SMO_CCNTRA',
    'BF_VENTL_PSSR',
    'REDUC_REG_NO',
    'PST_VENTL_PSSR',
    'CLNING_PRGRS_STTS',
    'DRVNG_DSTNC',
    'PST_SMO_CCNTRA',

    'CRTN_DT',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['클리닝보증기간구분코드',
    '클리닝종류코드',
    '클리닝업체명',
    '클리닝일자',
    '보조금대상여부',
    '이전매연농도',
    '이전배기압력',
    '저감등록번호',
    '후배기압력',
    '클리닝진행상태',
    '주행거리',
    '후매연농도',

    '미정',]
    }

scol = pd.DataFrame(sdict)
scol

                        컬럼           내용
0   CLNING_GRNTE_WHL_SE_CD  클리닝보증기간구분코드
1            CLNING_KND_CD      클리닝종류코드
2         CLNING_ENTRPS_NM       클리닝업체명
3               CLNING_YMD        클리닝일자
4           SBSIDY_TRGT_YN      보조금대상여부
5            BF_SMO_CCNTRA       이전매연농도
6            BF_VENTL_PSSR       이전배기압력
7             REDUC_REG_NO       저감등록번호
8           PST_VENTL_PSSR        후배기압력
9        CLNING_PRGRS_STTS      클리닝진행상태
10             DRVNG_DSTNC         주행거리
11          PST_SMO_CCNTRA        후매연농도
12                 CRTN_DT           미정

### 데이터 info

In [205]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CLNING_GRNTY_WHL_SE,클리닝보증기간구분,896001,CLNING_GRNTE_WHL_SE_CD,클리닝보증기간구분코드,897338.0,-1337.0,10,10.0
1,CLNING_KND,클리닝종류,896007,CLNING_KND_CD,클리닝종류코드,897344.0,-1337.0,4,4.0
2,CLNING_ENTRPS_NM,클리닝업체명,896007,CLNING_ENTRPS_NM,클리닝업체명,897344.0,-1337.0,4,4.0
3,CLNING_DE,클리닝일자,896009,CLNING_YMD,클리닝일자,897346.0,-1337.0,2,2.0
4,SBSIDY_TRGT_YN,보조금대상YN,896010,SBSIDY_TRGT_YN,보조금대상여부,897347.0,-1337.0,1,1.0

### [출력]

In [206]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 9\. 사후관리 사후점검(DLM_TB_ERP_CLEAN_SCREEN)

In [207]:
name = 'DLM_TB_ERP_CLEAN_SCREEN'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

40 8
(64951, 40) (64951, 8)

In [208]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수    행_수
ODS    40  64951
STD     8  64951

### 컬럼 확인

In [209]:
odf.columns.to_list()

['CHK_RCPT_NO',
 'REDUC_REG_NO',
 'RCPT_DE',
 'CHK_DE',
 'CHK_ODR',
 'RCPT_SIGNGU',
 'EXTRNS_REMDEL_STUS',
 'SLF_DGNSS_DVICE',
 'FUEL_SPLORE_PICK',
 'PLLTN_DNSTY_MEASUVL',
 'SMO_CO_VAL',
 'SMO_HC_VAL',
 'CHK_RSLT',
 'DIRTN_MTTR',
 'RCPT_RESN_01_YN',
 'RCPT_RESN_02_YN',
 'RCPT_RESN_03_YN',
 'RCPT_RESN_04_YN',
 'RCPT_RESN_05_YN',
 'RCPT_RESN_06_YN',
 'RCPT_RESN_07_YN',
 'RCPT_RESN_08_YN',
 'RCPT_RESN_09_YN',
 'RCPT_RESN_10_YN',
 'RCPT_RESN_11_YN',
 'RCPT_ETC_RESN',
 'BPLC_ADRS',
 'BPLC_TELNO',
 'BPLC_RPRSTV_NM',
 'REG_INST_CD',
 'INPT_DE',
 'RETR_NM',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'TRTMNT_MTTR_1_YN',
 'TRTMNT_MTTR_2_YN',
 'TRTMNT_MTTR_3_YN',
 'TRTMNT_MTTR_4_YN',
 'TRTMNT_DTLS',
 'RETR_ID']

In [210]:
olist = [
    'CHK_DE',
    'CHK_ODR',
    'TRTMNT_DTLS',
    'DIRTN_MTTR',
    'PLLTN_DNSTY_MEASUVL',
    'REDUC_REG_NO',
    'CHK_RSLT',
    'EXTRNS_REMDEL_STUS',

    'CHK_RCPT_NO',
    'RCPT_DE',
    'RCPT_SIGNGU',
    'SLF_DGNSS_DVICE',
    'FUEL_SPLORE_PICK',
    'SMO_CO_VAL',
    'SMO_HC_VAL',
    'RCPT_RESN_01_YN',
    'RCPT_RESN_02_YN',
    'RCPT_RESN_03_YN',
    'RCPT_RESN_04_YN',
    'RCPT_RESN_05_YN',
    'RCPT_RESN_06_YN',
    'RCPT_RESN_07_YN',
    'RCPT_RESN_08_YN',
    'RCPT_RESN_09_YN',
    'RCPT_RESN_10_YN',
    'RCPT_RESN_11_YN',
    'RCPT_ETC_RESN',
    'BPLC_ADRS',
    'BPLC_TELNO',
    'BPLC_RPRSTV_NM',
    'REG_INST_CD',
    'INPT_DE',
    'RETR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'TRTMNT_MTTR_1_YN',
    'TRTMNT_MTTR_2_YN',
    'TRTMNT_MTTR_3_YN',
    'TRTMNT_MTTR_4_YN',
    'RETR_ID', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['점검일자',
    '점검차수',
    '조치내역',
    '지시사항',
    '오염농도측정값',
    '저감등록번호',
    '점검결과',
    '부착개조상태',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

ocol = pd.DataFrame(odict)
ocol

                     컬럼       내용
0                CHK_DE     점검일자
1               CHK_ODR     점검차수
2           TRTMNT_DTLS     조치내역
3            DIRTN_MTTR     지시사항
4   PLLTN_DNSTY_MEASUVL  오염농도측정값
5          REDUC_REG_NO   저감등록번호
6              CHK_RSLT     점검결과
7    EXTRNS_REMDEL_STUS   부착개조상태
8           CHK_RCPT_NO       미정
9               RCPT_DE       미정
10          RCPT_SIGNGU       미정
11      SLF_DGNSS_DVICE       미정
12     FUEL_SPLORE_PICK       미정
13           SMO_CO_VAL       미정
14           SMO_HC_VAL       미정
15      RCPT_RESN_01_YN       미정
16      RCPT_RESN_02_YN       미정
17      RCPT_RESN_03_YN       미정
18      RCPT_RESN_04_YN       미정
19      RCPT_RESN_05_YN       미정
20      RCPT_RESN_06_YN       미정
21      RCPT_RESN_07_YN       미정
22      RCPT_RESN_08_YN       미정
23      RCPT_RESN_09_YN       미정
24      RCPT_RESN_10_YN       미정
25      RCPT_RESN_11_YN       미정
26        RCPT_ETC_RESN       미정
27            BPLC_ADRS       미정
28           BPLC_TELNO       미정
29       BPLC_RPRSTV_NM       미정
30          REG_INST_CD       미정
31              INPT_DE       미정
32              RETR_NM       미정
33          LST_CHNG_DE       미정
34          LST_EDIR_NM       미정
35     TRTMNT_MTTR_1_YN       미정
36     TRTMNT_MTTR_2_YN       미정
37     TRTMNT_MTTR_3_YN       미정
38     TRTMNT_MTTR_4_YN       미정
39              RETR_ID       미정

In [211]:
sdf.columns.to_list()

['CHCK_DT',
 'CHCK_ODR_CD',
 'CHCK_RSLT_CD',
 'DIRTN_MTTR_CD',
 'DVIE_EXTNS_REMDL_STS_CD',
 'PLLTN_CCNTRA_MSTVL',
 'RDCDVC_REG_NO',
 'ACTN_BRKWN']

In [212]:
slist = [
    'CHCK_DT',
    'CHCK_ODR_CD',
    'ACTN_BRKWN',
    'DIRTN_MTTR_CD',
    'PLLTN_CCNTRA_MSTVL',
    'RDCDVC_REG_NO',
    'CHCK_RSLT_CD',
    'DVIE_EXTNS_REMDL_STS_CD',

    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['점검일시',
    '점검차수코드',
    '조치내역',
    '지시사항코드',
    '오염농도측정값',
    '저감장치등록번호',
    '점검결과코드',
    '장치부착개조상태',]
    }

scol = pd.DataFrame(sdict)
scol

                        컬럼        내용
0                  CHCK_DT      점검일시
1              CHCK_ODR_CD    점검차수코드
2               ACTN_BRKWN      조치내역
3            DIRTN_MTTR_CD    지시사항코드
4       PLLTN_CCNTRA_MSTVL   오염농도측정값
5            RDCDVC_REG_NO  저감장치등록번호
6             CHCK_RSLT_CD    점검결과코드
7  DVIE_EXTNS_REMDL_STS_CD  장치부착개조상태

### 데이터 info

In [213]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CHK_DE,점검일자,64951,CHCK_DT,점검일시,64951.0,0.0,0,0.0
1,CHK_ODR,점검차수,50015,CHCK_ODR_CD,점검차수코드,50015.0,0.0,14936,14936.0
2,TRTMNT_DTLS,조치내역,1697,ACTN_BRKWN,조치내역,1697.0,0.0,63254,63254.0
3,DIRTN_MTTR,지시사항,11070,DIRTN_MTTR_CD,지시사항코드,11069.0,1.0,53881,53882.0
4,PLLTN_DNSTY_MEASUVL,오염농도측정값,62121,PLLTN_CCNTRA_MSTVL,오염농도측정값,62121.0,0.0,2830,2830.0

### [출력]

In [214]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 10\. 노후차 조기폐차 관리정보(수도권)(DLM_TB_ERP_EARLY_ERASE_AEA)

In [215]:
name = 'DLM_TB_ERP_EARLY_ERASE_AEA'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

177 15
(770311, 177) (770117, 15)

In [216]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS   177  770311
STD    15  770117

### 컬럼 확인

In [217]:
odf.columns.to_list()

['ELPDSRC_MNGT_NO',
 'ELPDSRC_STUS_CD',
 'RDCDVC_SE',
 'INST_ID_CD',
 'OWNR_NM',
 'USER_BIZRNO',
 'USER_TELNO',
 'FXNUM',
 'USER_ZIP',
 'USER_1_ADRS',
 'USER_2_ADRS',
 'RCPT_SIDO',
 'RCPT_SIGNGU',
 'VHRNO',
 'VIN',
 'VHCL_YRIDNW',
 'EGINCTY',
 'VHCL_PSCP',
 'VHCL_WGHT',
 'TOT_WGHT',
 'CRYNG_WGHT',
 'VHCNM',
 'VHCL_FRM',
 'VHCTY',
 'VHCL_PURPS',
 'FST_REG_DE',
 'SCRCAR_REG_DRVNG_DSTNC',
 'SCRCAR_ERA_DRVNG_DSTNC',
 'VHCL_FUEL',
 'PRCINSP_DE',
 'INSPOF_NM',
 'PRCINSP_JDGMNT_YN',
 'PRCINSP_RSLT_VAL',
 'PRCINSP_JDGMNT_STDR_VAL',
 'RCPT_DE',
 'INPT_DE',
 'RETR_NM',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_TRGT_1_AT',
 'ELPDSRC_TRGT_2_AT',
 'ELPDSRC_TRGT_3_AT',
 'ELPDSRC_TRGT_4_AT',
 'ELPDSRC_TRGT_5_AT',
 'ELPDSRC_TRGT_6_AT',
 'ELPDSRC_TRGT_7_AT',
 'ELPDSRC_TRGT_CNFRM_REG_DE',
 'ELPDSRC_TRGT_CNFRM_REGR_NM',
 'PYMT_CNFRM_YN',
 'EXPC_SPRT_AMT',
 'DCIS_SPRT_AMT',
 'SBSIDY_UNPAY_RESN',
 'SBSIDY_RQEST_DE',
 'SBSIDY_RQEST_REGR_NM',
 'DOC_CNFRM_NO',
 'DOC_OUTT_DE',
 'INSP_RQT_SIWA_MTHD',
 'INSP_RQT_DE',
 'INSP_RQT_TM',
 'VRSC_ENTRPS_NM',
 'AGENT_ZIP',
 'AGENT_1_ADRS',
 'AGENT_2_ADRS',
 'AGENT_TELNO',
 'AGENT_CRTC_NO',
 'INSP_RQT_REG_DE',
 'INSP_RQT_REGR_NM',
 'PFMINPC_DE',
 'PFMINPC_1_ITM',
 'PFMINPC_2_ITM',
 'PFMINPC_3_ITM',
 'PFMINPC_4_ITM',
 'PFMINPC_5_ITM',
 'PFMINPC_ETC_ITM',
 'PFMINPC_ITM_ETC_CMPNT_NM',
 'PFMINPC_FILE_ATT_YN',
 'PFMINPC_ELPDSRC_YN',
 'PFMINPC_ELPDSRC_IMPSBL_RESN',
 'PFMINPC_REG_DE',
 'PFMINPC_REGR_NM',
 'PFMINPC_PAPE_OUTT_DE',
 'TRTMNT_DE',
 'ERSR_DE',
 'NCAR_PUCH_PLAN_DE',
 'NCAR_PUCH_PLAN_VHCL_NM',
 'SCRCAR_ENTRPS_NM',
 'SCRCAR_ENTRPS_ZIP',
 'SCRCAR_ENTRPS_1_ADRS',
 'SCRCAR_ENTRPS_2_ADRS',
 'ELPDSRC_ATT_FILE_1_YN',
 'ELPDSRC_ATT_FILE_2_YN',
 'ELPDSRC_ATT_FILE_3_YN',
 'ELPDSRC_REG_DE',
 'ELPDSRC_REGR_NM',
 'ELPDSRC_LST_CNFRM_YN',
 'ELPDSRC_LST_UNAP_RESN',
 'SBSIDY_PYMT_DE',
 'SBSIDY_BIZ_YR',
 'ELPDSRC_LST_CNFRM_DE',
 'ELPDSRC_LST_APRR_NM',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'LWBCT_YN',
 'NOW_VHRNO',
 'ELPDSRC_ATT_FILE_4_YN',
 'BANK_NM',
 'BANK_ACC_NO',
 'PRCINSP_SE',
 'RCPT_LOCGOV_CD',
 'RPRSTV_NM',
 'BIZCND',
 'TYPBIZ',
 'EMAIL',
 'RCPT_SE',
 'INSP_SE',
 'ELPDSRC_TRGT_AT_ETC_RESN',
 'HST_MNGT_NO',
 'CTNT',
 'VHCTY_SE',
 'ELPDSRC_GRP',
 'BTHDY',
 'JURIRNO',
 'STDR_YM',
 'STDR_AMT',
 'WHL_EXCS_CNFRM_DE',
 'WHL_EXCS_APRR_NM',
 'MNFCT_DE',
 'OLD_SIDO',
 'OLD_SIGNGU',
 'OLD_RCPT_LOCGOV_CD',
 'OLD_1_ADRS',
 'OLD_2_ADRS',
 'OLD_VHCL_PURPS',
 'BAI_ID',
 'ADITOR_NM',
 'REG_NO',
 'RQEST_ARVL_DE',
 'RQEST_ARVL_YN',
 'BIL_CNFRMR_NM',
 'ADD_AMT',
 'SAMNS_CNFRM',
 'ADD_RQEST_ARVL_YN',
 'ADD_RQEST_ARVL_DE',
 'ADD_RQEST_CNFRMR_NM',
 'ATT_PAPE_CNFRM_AT',
 'BEF_STUS_CD',
 'WAREHOUSING_DE',
 'WAREHOUSING_YN',
 'MNTNG_IMPR_YN',
 'MNTNG_IMPR_AMT',
 'ELPDSRC_ATT_FILE_5_YN',
 'ELPDSRC_VRSC_INST_NO',
 'SMAL_BUSIN_YN',
 'INPT_MTHD_FLAG',
 'ELPDSRC_ATT_FILE_7_YN',
 'STNDRD',
 'ENGINE_RPM',
 'MAKER',
 'CAR_GRADE',
 'AID_RJCT_DE',
 'IMG_LGCLFL1',
 'IMG_PHYSCL1',
 'IMG_LGCLFL2',
 'IMG_PHYSCL2',
 'IMG_LGCLFL3',
 'IMG_PHYSCL3',
 'IMG_LGCLFL4',
 'IMG_PHYSCL4',
 'PRE_SCRAP_CAR_YN',
 'DEP_YN',
 'VIRT_ACC_NO',
 'ELCTY_HYDRO_CAR_ADD_AMT',
 'PFMINPC_ITSL_APPRNC',
 'PFMINPC_BUFFER_DVICE',
 'PFMINPC_WINDOW',
 'PFMINPC_TIRE',
 'PFMINPC_ASSMI_DEVICE',
 'PFMINPC_ELPDSRC_GNRLZ_RESN']

In [218]:
olist = [
    'VHRNO',
    'VIN',
    'ELPDSRC_LST_CNFRM_YN',
    'ELPDSRC_STUS_CD',
    'ERSR_DE',
    'RCPT_SIDO',
    'RDCDVC_SE',
    'MNTNG_IMPR_YN',
    'SCRCAR_REG_DRVNG_DSTNC',

    'ELPDSRC_MNGT_NO',
    'INST_ID_CD',
    'OWNR_NM',
    'USER_BIZRNO',
    'USER_TELNO',
    'FXNUM',
    'USER_ZIP',
    'USER_1_ADRS',
    'USER_2_ADRS',
    'RCPT_SIGNGU',
    'VHCL_YRIDNW',
    'EGINCTY',
    'VHCL_PSCP',
    'VHCL_WGHT',
    'TOT_WGHT',
    'CRYNG_WGHT',
    'VHCNM',
    'VHCL_FRM',
    'VHCTY',
    'VHCL_PURPS',
    'FST_REG_DE',
    'SCRCAR_ERA_DRVNG_DSTNC',
    'VHCL_FUEL',
    'PRCINSP_DE',
    'INSPOF_NM',
    'PRCINSP_JDGMNT_YN',
    'PRCINSP_RSLT_VAL',
    'PRCINSP_JDGMNT_STDR_VAL',
    'RCPT_DE',
    'INPT_DE',
    'RETR_NM',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_TRGT_1_AT',
    'ELPDSRC_TRGT_2_AT',
    'ELPDSRC_TRGT_3_AT',
    'ELPDSRC_TRGT_4_AT',
    'ELPDSRC_TRGT_5_AT',
    'ELPDSRC_TRGT_6_AT',
    'ELPDSRC_TRGT_7_AT',
    'ELPDSRC_TRGT_CNFRM_REG_DE',
    'ELPDSRC_TRGT_CNFRM_REGR_NM',
    'PYMT_CNFRM_YN',
    'EXPC_SPRT_AMT',
    'DCIS_SPRT_AMT',
    'SBSIDY_UNPAY_RESN',
    'SBSIDY_RQEST_DE',
    'SBSIDY_RQEST_REGR_NM',
    'DOC_CNFRM_NO',
    'DOC_OUTT_DE',
    'INSP_RQT_SIWA_MTHD',
    'INSP_RQT_DE',
    'INSP_RQT_TM',
    'VRSC_ENTRPS_NM',
    'AGENT_ZIP',
    'AGENT_1_ADRS',
    'AGENT_2_ADRS',
    'AGENT_TELNO',
    'AGENT_CRTC_NO',
    'INSP_RQT_REG_DE',
    'INSP_RQT_REGR_NM',
    'PFMINPC_DE',
    'PFMINPC_1_ITM',
    'PFMINPC_2_ITM',
    'PFMINPC_3_ITM',
    'PFMINPC_4_ITM',
    'PFMINPC_5_ITM',
    'PFMINPC_ETC_ITM',
    'PFMINPC_ITM_ETC_CMPNT_NM',
    'PFMINPC_FILE_ATT_YN',
    'PFMINPC_ELPDSRC_YN',
    'PFMINPC_ELPDSRC_IMPSBL_RESN',
    'PFMINPC_REG_DE',
    'PFMINPC_REGR_NM',
    'PFMINPC_PAPE_OUTT_DE',
    'TRTMNT_DE',
    'NCAR_PUCH_PLAN_DE',
    'NCAR_PUCH_PLAN_VHCL_NM',
    'SCRCAR_ENTRPS_NM',
    'SCRCAR_ENTRPS_ZIP',
    'SCRCAR_ENTRPS_1_ADRS',
    'SCRCAR_ENTRPS_2_ADRS',
    'ELPDSRC_ATT_FILE_1_YN',
    'ELPDSRC_ATT_FILE_2_YN',
    'ELPDSRC_ATT_FILE_3_YN',
    'ELPDSRC_REG_DE',
    'ELPDSRC_REGR_NM',
    'ELPDSRC_LST_UNAP_RESN',
    'SBSIDY_PYMT_DE',
    'SBSIDY_BIZ_YR',
    'ELPDSRC_LST_CNFRM_DE',
    'ELPDSRC_LST_APRR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'LWBCT_YN',
    'NOW_VHRNO',
    'ELPDSRC_ATT_FILE_4_YN',
    'BANK_NM',
    'BANK_ACC_NO',
    'PRCINSP_SE',
    'RCPT_LOCGOV_CD',
    'RPRSTV_NM',
    'BIZCND',
    'TYPBIZ',
    'EMAIL',
    'RCPT_SE',
    'INSP_SE',
    'ELPDSRC_TRGT_AT_ETC_RESN',
    'HST_MNGT_NO',
    'CTNT',
    'VHCTY_SE',
    'ELPDSRC_GRP',
    'BTHDY',
    'JURIRNO',
    'STDR_YM',
    'STDR_AMT',
    'WHL_EXCS_CNFRM_DE',
    'WHL_EXCS_APRR_NM',
    'MNFCT_DE',
    'OLD_SIDO',
    'OLD_SIGNGU',
    'OLD_RCPT_LOCGOV_CD',
    'OLD_1_ADRS',
    'OLD_2_ADRS',
    'OLD_VHCL_PURPS',
    'BAI_ID',
    'ADITOR_NM',
    'REG_NO',
    'RQEST_ARVL_DE',
    'RQEST_ARVL_YN',
    'BIL_CNFRMR_NM',
    'ADD_AMT',
    'SAMNS_CNFRM',
    'ADD_RQEST_ARVL_YN',
    'ADD_RQEST_ARVL_DE',
    'ADD_RQEST_CNFRMR_NM',
    'ATT_PAPE_CNFRM_AT',
    'BEF_STUS_CD',
    'WAREHOUSING_DE',
    'WAREHOUSING_YN',
    'MNTNG_IMPR_AMT',
    'ELPDSRC_ATT_FILE_5_YN',
    'ELPDSRC_VRSC_INST_NO',
    'SMAL_BUSIN_YN',
    'INPT_MTHD_FLAG',
    'ELPDSRC_ATT_FILE_7_YN',
    'STNDRD',
    'ENGINE_RPM',
    'MAKER',
    'CAR_GRADE',
    'AID_RJCT_DE',
    'IMG_LGCLFL1',
    'IMG_PHYSCL1',
    'IMG_LGCLFL2',
    'IMG_PHYSCL2',
    'IMG_LGCLFL3',
    'IMG_PHYSCL3',
    'IMG_LGCLFL4',
    'IMG_PHYSCL4',
    'PRE_SCRAP_CAR_YN',
    'DEP_YN',
    'VIRT_ACC_NO',
    'ELCTY_HYDRO_CAR_ADD_AMT',
    'PFMINPC_ITSL_APPRNC',
    'PFMINPC_BUFFER_DVICE',
    'PFMINPC_WINDOW',
    'PFMINPC_TIRE',
    'PFMINPC_ASSMI_DEVICE',
    'PFMINPC_ELPDSRC_GNRLZ_RESN', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차량등록번호',
    '차대번호',
    '조기폐차최종승인YN',
    '조기폐차상태코드',
    '말소일자',
    '접수시도',
    '저감장치구분',
    '저감장치 미개발(부착불가)여부',
    '폐차등록주행거리',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                             컬럼          내용
0                         VHRNO      차량등록번호
1                           VIN        차대번호
2          ELPDSRC_LST_CNFRM_YN  조기폐차최종승인YN
3               ELPDSRC_STUS_CD    조기폐차상태코드
4                       ERSR_DE        말소일자
..                          ...         ...
172        PFMINPC_BUFFER_DVICE          미정
173              PFMINPC_WINDOW          미정
174                PFMINPC_TIRE          미정
175        PFMINPC_ASSMI_DEVICE          미정
176  PFMINPC_ELPDSRC_GNRLZ_RESN          미정

[177 rows x 2 columns]

In [219]:
sdf.columns.to_list()

['ELPDSRC_LST_APRV_YN',
 'ELPDSRC_STTS_CD',
 'ERSR_YMD',
 'RDCDVC_EXTRNS_YN',
 'STDG_CTPV_NM',
 'LEM_KND_CD',
 'SCCAR_REG_DRVNG_DSNC',
 'VHRNO',
 'VIN',
 'CRTN_DT',
 'STDG_SGG_NM',
 'SCRCAR_ENTRPS_NM',
 'ELPDSRC_LAST_APRV_YMD',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_MNG_NO']

In [220]:
slist = [
    'VHRNO',
    'VIN',
    'ELPDSRC_LST_APRV_YN',
    'ELPDSRC_STTS_CD',
    'ERSR_YMD',
    'STDG_CTPV_NM',
    'LEM_KND_CD',
    'RDCDVC_EXTRNS_YN',
    'SCCAR_REG_DRVNG_DSNC',

    'CRTN_DT',
    'STDG_SGG_NM',
    'SCRCAR_ENTRPS_NM',
    'ELPDSRC_LAST_APRV_YMD',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_MNG_NO',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['자동차등록번호',
    '차대번호',
    '조기폐차최종승인여부',
    '조기폐차상태코드',
    '말소일자',
    '법정동시도명',
    '저공해조치종류코드',
    '저감장치부착여부',
    '폐차등록주행거리',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

scol = pd.DataFrame(sdict)
scol

                       컬럼          내용
0                   VHRNO     자동차등록번호
1                     VIN        차대번호
2     ELPDSRC_LST_APRV_YN  조기폐차최종승인여부
3         ELPDSRC_STTS_CD    조기폐차상태코드
4                ERSR_YMD        말소일자
5            STDG_CTPV_NM      법정동시도명
6              LEM_KND_CD   저공해조치종류코드
7        RDCDVC_EXTRNS_YN    저감장치부착여부
8    SCCAR_REG_DRVNG_DSNC    폐차등록주행거리
9                 CRTN_DT          미정
10            STDG_SGG_NM          미정
11       SCRCAR_ENTRPS_NM          미정
12  ELPDSRC_LAST_APRV_YMD          미정
13         SBSIDY_TRGT_YN          미정
14         ELPDSRC_MNG_NO          미정

### 데이터 info

In [222]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,VHRNO,차량등록번호,770311,VHRNO,자동차등록번호,770117.0,194.0,0,0.0
1,VIN,차대번호,770311,VIN,차대번호,770117.0,194.0,0,0.0
2,ELPDSRC_LST_CNFRM_YN,조기폐차최종승인YN,680625,ELPDSRC_LST_APRV_YN,조기폐차최종승인여부,679295.0,1330.0,89686,90822.0
3,ELPDSRC_STUS_CD,조기폐차상태코드,770311,ELPDSRC_STTS_CD,조기폐차상태코드,770117.0,194.0,0,0.0
4,ERSR_DE,말소일자,684061,ERSR_YMD,말소일자,683275.0,786.0,86250,86842.0

### [출력]

In [223]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 11\. 노후차 조기폐차 관리정보(수도권 외)(DLM_TB_ERP_EARLY_ERASE_LGV)

In [224]:
name = 'DLM_TB_ERP_EARLY_ERASE_LGV'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

170 14
(291353, 170) (291353, 14)

In [225]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS   170  291353
STD    14  291353

### 컬럼 확인

In [226]:
odf.columns.to_list()

['ELPDSRC_MNGT_NO',
 'ELPDSRC_STUS_CD',
 'RDCDVC_SE',
 'INST_ID_CD',
 'OWNR_NM',
 'USER_BIZRNO',
 'USER_TELNO',
 'FXNUM',
 'USER_ZIP',
 'USER_1_ADRS',
 'USER_2_ADRS',
 'RCPT_SIDO',
 'RCPT_SIGNGU',
 'VHRNO',
 'VIN',
 'VHCL_YRIDNW',
 'EGINCTY',
 'VHCL_PSCP',
 'VHCL_WGHT',
 'TOT_WGHT',
 'CRYNG_WGHT',
 'VHCNM',
 'VHCL_FRM',
 'VHCTY',
 'VHCL_PURPS',
 'FST_REG_DE',
 'SCRCAR_REG_DRVNG_DSTNC',
 'SCRCAR_ERA_DRVNG_DSTNC',
 'VHCL_FUEL',
 'PRCINSP_DE',
 'INSPOF_NM',
 'PRCINSP_JDGMNT_YN',
 'PRCINSP_RSLT_VAL',
 'PRCINSP_JDGMNT_STDR_VAL',
 'RCPT_DE',
 'INPT_DE',
 'RETR_NM',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_TRGT_1_AT',
 'ELPDSRC_TRGT_2_AT',
 'ELPDSRC_TRGT_3_AT',
 'ELPDSRC_TRGT_4_AT',
 'ELPDSRC_TRGT_5_AT',
 'ELPDSRC_TRGT_6_AT',
 'ELPDSRC_TRGT_7_AT',
 'ELPDSRC_TRGT_CNFRM_REG_DE',
 'ELPDSRC_TRGT_CNFRM_REGR_NM',
 'PYMT_CNFRM_YN',
 'EXPC_SPRT_AMT',
 'DCIS_SPRT_AMT',
 'SBSIDY_UNPAY_RESN',
 'SBSIDY_RQEST_DE',
 'SBSIDY_RQEST_REGR_NM',
 'DOC_CNFRM_NO',
 'DOC_OUTT_DE',
 'INSP_RQT_SIWA_MTHD',
 'INSP_RQT_DE',
 'INSP_RQT_TM',
 'VRSC_ENTRPS_NM',
 'AGENT_ZIP',
 'AGENT_1_ADRS',
 'AGENT_2_ADRS',
 'AGENT_TELNO',
 'AGENT_CRTC_NO',
 'INSP_RQT_REG_DE',
 'INSP_RQT_REGR_NM',
 'PFMINPC_DE',
 'PFMINPC_1_ITM',
 'PFMINPC_2_ITM',
 'PFMINPC_3_ITM',
 'PFMINPC_4_ITM',
 'PFMINPC_5_ITM',
 'PFMINPC_ETC_ITM',
 'PFMINPC_ITM_ETC_CMPNT_NM',
 'PFMINPC_FILE_ATT_YN',
 'PFMINPC_ELPDSRC_YN',
 'PFMINPC_ELPDSRC_IMPSBL_RESN',
 'PFMINPC_REG_DE',
 'PFMINPC_REGR_NM',
 'PFMINPC_PAPE_OUTT_DE',
 'TRTMNT_DE',
 'ERSR_DE',
 'NCAR_PUCH_PLAN_DE',
 'NCAR_PUCH_PLAN_VHCL_NM',
 'SCRCAR_ENTRPS_NM',
 'SCRCAR_ENTRPS_ZIP',
 'SCRCAR_ENTRPS_1_ADRS',
 'SCRCAR_ENTRPS_2_ADRS',
 'ELPDSRC_ATT_FILE_1_YN',
 'ELPDSRC_ATT_FILE_2_YN',
 'ELPDSRC_ATT_FILE_3_YN',
 'ELPDSRC_REG_DE',
 'ELPDSRC_REGR_NM',
 'ELPDSRC_LST_CNFRM_YN',
 'ELPDSRC_LST_UNAP_RESN',
 'SBSIDY_PYMT_DE',
 'SBSIDY_BIZ_YR',
 'ELPDSRC_LST_CNFRM_DE',
 'ELPDSRC_LST_APRR_NM',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'LWBCT_YN',
 'NOW_VHRNO',
 'ELPDSRC_ATT_FILE_4_YN',
 'BANK_NM',
 'BANK_ACC_NO',
 'PRCINSP_SE',
 'RCPT_LOCGOV_CD',
 'RPRSTV_NM',
 'BIZCND',
 'TYPBIZ',
 'EMAIL',
 'RCPT_SE',
 'INSP_SE',
 'ELPDSRC_TRGT_AT_ETC_RESN',
 'HST_MNGT_NO',
 'CTNT',
 'VHCTY_SE',
 'ELPDSRC_GRP',
 'BTHDY',
 'JURIRNO',
 'STDR_YM',
 'STDR_AMT',
 'WHL_EXCS_CNFRM_DE',
 'WHL_EXCS_APRR_NM',
 'MNFCT_DE',
 'OLD_SIDO',
 'OLD_SIGNGU',
 'OLD_RCPT_LOCGOV_CD',
 'OLD_1_ADRS',
 'OLD_2_ADRS',
 'OLD_VHCL_PURPS',
 'BAI_ID',
 'ADITOR_NM',
 'REG_NO',
 'RQEST_ARVL_DE',
 'RQEST_ARVL_YN',
 'BIL_CNFRMR_NM',
 'ADD_AMT',
 'SAMNS_CNFRM',
 'ADD_RQEST_ARVL_YN',
 'ADD_RQEST_ARVL_DE',
 'ADD_RQEST_CNFRMR_NM',
 'ATT_PAPE_CNFRM_AT',
 'BEF_STUS_CD',
 'WAREHOUSING_DE',
 'WAREHOUSING_YN',
 'MNTNG_IMPR_YN',
 'MNTNG_IMPR_AMT',
 'ELPDSRC_ATT_FILE_5_YN',
 'SMAL_BUSIN_YN',
 'INPT_MTHD_FLAG',
 'ELPDSRC_ATT_FILE_7_YN',
 'AID_RJCT_DE',
 'IMG_LGCLFL1',
 'IMG_PHYSCL1',
 'IMG_LGCLFL2',
 'IMG_PHYSCL2',
 'IMG_LGCLFL3',
 'IMG_PHYSCL3',
 'IMG_LGCLFL4',
 'IMG_PHYSCL4',
 'PRE_SCRAP_CAR_YN',
 'ELCTY_HYDRO_CAR_ADD_AMT',
 'PFMINPC_ITSL_APPRNC',
 'PFMINPC_BUFFER_DVICE',
 'PFMINPC_WINDOW',
 'PFMINPC_TIRE',
 'PFMINPC_ASSMI_DEVICE',
 'PFMINPC_ELPDSRC_GNRLZ_RESN']

In [227]:
olist = [
    'RCPT_SIDO',
    'RDCDVC_SE',
    'MNTNG_IMPR_YN',
    'ELPDSRC_LST_CNFRM_YN',
    'ERSR_DE',
    'SCRCAR_REG_DRVNG_DSTNC',
    'VHRNO',
    'VIN',
    'ELPDSRC_STUS_CD',

    'ELPDSRC_MNGT_NO',
    'INST_ID_CD',
    'OWNR_NM',
    'USER_BIZRNO',
    'USER_TELNO',
    'FXNUM',
    'USER_ZIP',
    'USER_1_ADRS',
    'USER_2_ADRS',
    'RCPT_SIGNGU',
    'VHCL_YRIDNW',
    'EGINCTY',
    'VHCL_PSCP',
    'VHCL_WGHT',
    'TOT_WGHT',
    'CRYNG_WGHT',
    'VHCNM',
    'VHCL_FRM',
    'VHCTY',
    'VHCL_PURPS',
    'FST_REG_DE',
    'SCRCAR_ERA_DRVNG_DSTNC',
    'VHCL_FUEL',
    'PRCINSP_DE',
    'INSPOF_NM',
    'PRCINSP_JDGMNT_YN',
    'PRCINSP_RSLT_VAL',
    'PRCINSP_JDGMNT_STDR_VAL',
    'RCPT_DE',
    'INPT_DE',
    'RETR_NM',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_TRGT_1_AT',
    'ELPDSRC_TRGT_2_AT',
    'ELPDSRC_TRGT_3_AT',
    'ELPDSRC_TRGT_4_AT',
    'ELPDSRC_TRGT_5_AT',
    'ELPDSRC_TRGT_6_AT',
    'ELPDSRC_TRGT_7_AT',
    'ELPDSRC_TRGT_CNFRM_REG_DE',
    'ELPDSRC_TRGT_CNFRM_REGR_NM',
    'PYMT_CNFRM_YN',
    'EXPC_SPRT_AMT',
    'DCIS_SPRT_AMT',
    'SBSIDY_UNPAY_RESN',
    'SBSIDY_RQEST_DE',
    'SBSIDY_RQEST_REGR_NM',
    'DOC_CNFRM_NO',
    'DOC_OUTT_DE',
    'INSP_RQT_SIWA_MTHD',
    'INSP_RQT_DE',
    'INSP_RQT_TM',
    'VRSC_ENTRPS_NM',
    'AGENT_ZIP',
    'AGENT_1_ADRS',
    'AGENT_2_ADRS',
    'AGENT_TELNO',
    'AGENT_CRTC_NO',
    'INSP_RQT_REG_DE',
    'INSP_RQT_REGR_NM',
    'PFMINPC_DE',
    'PFMINPC_1_ITM',
    'PFMINPC_2_ITM',
    'PFMINPC_3_ITM',
    'PFMINPC_4_ITM',
    'PFMINPC_5_ITM',
    'PFMINPC_ETC_ITM',
    'PFMINPC_ITM_ETC_CMPNT_NM',
    'PFMINPC_FILE_ATT_YN',
    'PFMINPC_ELPDSRC_YN',
    'PFMINPC_ELPDSRC_IMPSBL_RESN',
    'PFMINPC_REG_DE',
    'PFMINPC_REGR_NM',
    'PFMINPC_PAPE_OUTT_DE',
    'TRTMNT_DE',
    'NCAR_PUCH_PLAN_DE',
    'NCAR_PUCH_PLAN_VHCL_NM',
    'SCRCAR_ENTRPS_NM',
    'SCRCAR_ENTRPS_ZIP',
    'SCRCAR_ENTRPS_1_ADRS',
    'SCRCAR_ENTRPS_2_ADRS',
    'ELPDSRC_ATT_FILE_1_YN',
    'ELPDSRC_ATT_FILE_2_YN',
    'ELPDSRC_ATT_FILE_3_YN',
    'ELPDSRC_REG_DE',
    'ELPDSRC_REGR_NM',
    'ELPDSRC_LST_UNAP_RESN',
    'SBSIDY_PYMT_DE',
    'SBSIDY_BIZ_YR',
    'ELPDSRC_LST_CNFRM_DE',
    'ELPDSRC_LST_APRR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'LWBCT_YN',
    'NOW_VHRNO',
    'ELPDSRC_ATT_FILE_4_YN',
    'BANK_NM',
    'BANK_ACC_NO',
    'PRCINSP_SE',
    'RCPT_LOCGOV_CD',
    'RPRSTV_NM',
    'BIZCND',
    'TYPBIZ',
    'EMAIL',
    'RCPT_SE',
    'INSP_SE',
    'ELPDSRC_TRGT_AT_ETC_RESN',
    'HST_MNGT_NO',
    'CTNT',
    'VHCTY_SE',
    'ELPDSRC_GRP',
    'BTHDY',
    'JURIRNO',
    'STDR_YM',
    'STDR_AMT',
    'WHL_EXCS_CNFRM_DE',
    'WHL_EXCS_APRR_NM',
    'MNFCT_DE',
    'OLD_SIDO',
    'OLD_SIGNGU',
    'OLD_RCPT_LOCGOV_CD',
    'OLD_1_ADRS',
    'OLD_2_ADRS',
    'OLD_VHCL_PURPS',
    'BAI_ID',
    'ADITOR_NM',
    'REG_NO',
    'RQEST_ARVL_DE',
    'RQEST_ARVL_YN',
    'BIL_CNFRMR_NM',
    'ADD_AMT',
    'SAMNS_CNFRM',
    'ADD_RQEST_ARVL_YN',
    'ADD_RQEST_ARVL_DE',
    'ADD_RQEST_CNFRMR_NM',
    'ATT_PAPE_CNFRM_AT',
    'BEF_STUS_CD',
    'WAREHOUSING_DE',
    'WAREHOUSING_YN',
    'MNTNG_IMPR_AMT',
    'ELPDSRC_ATT_FILE_5_YN',
    'SMAL_BUSIN_YN',
    'INPT_MTHD_FLAG',
    'ELPDSRC_ATT_FILE_7_YN',
    'AID_RJCT_DE',
    'IMG_LGCLFL1',
    'IMG_PHYSCL1',
    'IMG_LGCLFL2',
    'IMG_PHYSCL2',
    'IMG_LGCLFL3',
    'IMG_PHYSCL3',
    'IMG_LGCLFL4',
    'IMG_PHYSCL4',
    'PRE_SCRAP_CAR_YN',
    'ELCTY_HYDRO_CAR_ADD_AMT',
    'PFMINPC_ITSL_APPRNC',
    'PFMINPC_BUFFER_DVICE',
    'PFMINPC_WINDOW',
    'PFMINPC_TIRE',
    'PFMINPC_ASSMI_DEVICE',
    'PFMINPC_ELPDSRC_GNRLZ_RESN', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['접수시도',
    '저감장치구분',
    '저감장치 부착불가 여부',
    '조기폐차최종승인YN',
    '말소일자',
    '폐차등록주행거리',
    '차량등록번호',
    '차대번호',
    '조기폐차상태코드',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                             컬럼            내용
0                     RCPT_SIDO          접수시도
1                     RDCDVC_SE        저감장치구분
2                 MNTNG_IMPR_YN  저감장치 부착불가 여부
3          ELPDSRC_LST_CNFRM_YN    조기폐차최종승인YN
4                       ERSR_DE          말소일자
..                          ...           ...
165        PFMINPC_BUFFER_DVICE            미정
166              PFMINPC_WINDOW            미정
167                PFMINPC_TIRE            미정
168        PFMINPC_ASSMI_DEVICE            미정
169  PFMINPC_ELPDSRC_GNRLZ_RESN            미정

[170 rows x 2 columns]

In [228]:
sdf.columns.to_list()

['RDCDVC_EXTRNS_YN',
 'LEM_KND_CD',
 'STDG_CTPV_NM',
 'ELPDSRC_STTS_CD',
 'ELPDSRC_LST_APRV_YN',
 'ERSR_YMD',
 'VIN',
 'VHRNO',
 'SCCAR_REG_DRVNG_DSNC',
 'STDG_SGG_NM',
 'SCRCAR_ENTRPS_NM',
 'ELPDSRC_LAST_APRV_YMD',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_MNG_NO']

In [229]:
slist = [
    'STDG_CTPV_NM',
    'LEM_KND_CD',
    'RDCDVC_EXTRNS_YN',
    'ELPDSRC_LST_APRV_YN',
    'ERSR_YMD',
    'SCCAR_REG_DRVNG_DSNC',
    'VHRNO',
    'VIN',
    'ELPDSRC_STTS_CD',

    'STDG_SGG_NM',
    'SCRCAR_ENTRPS_NM',
    'ELPDSRC_LAST_APRV_YMD',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_MNG_NO',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['법정동시도명',
    '저공해조치종류코드',
    '저감장치부착여부',
    '조기폐차최종승인여부',
    '말소일자',
    '폐차등록주행거리',
    '자동차등록번호',
    '차대번호',
    '조기폐차상태코드',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

scol = pd.DataFrame(sdict)
scol

                       컬럼          내용
0            STDG_CTPV_NM      법정동시도명
1              LEM_KND_CD   저공해조치종류코드
2        RDCDVC_EXTRNS_YN    저감장치부착여부
3     ELPDSRC_LST_APRV_YN  조기폐차최종승인여부
4                ERSR_YMD        말소일자
5    SCCAR_REG_DRVNG_DSNC    폐차등록주행거리
6                   VHRNO     자동차등록번호
7                     VIN        차대번호
8         ELPDSRC_STTS_CD    조기폐차상태코드
9             STDG_SGG_NM          미정
10       SCRCAR_ENTRPS_NM          미정
11  ELPDSRC_LAST_APRV_YMD          미정
12         SBSIDY_TRGT_YN          미정
13         ELPDSRC_MNG_NO          미정

### 데이터 info

In [231]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,RCPT_SIDO,접수시도,291353,STDG_CTPV_NM,법정동시도명,291353.0,0.0,0,0.0
1,RDCDVC_SE,저감장치구분,291353,LEM_KND_CD,저공해조치종류코드,291353.0,0.0,0,0.0
2,MNTNG_IMPR_YN,저감장치 부착불가 여부,291353,RDCDVC_EXTRNS_YN,저감장치부착여부,291353.0,0.0,0,0.0
3,ELPDSRC_LST_CNFRM_YN,조기폐차최종승인YN,128589,ELPDSRC_LST_APRV_YN,조기폐차최종승인여부,128589.0,0.0,162764,162764.0
4,ERSR_DE,말소일자,134151,ERSR_YMD,말소일자,134151.0,0.0,157202,157202.0

### [출력]

In [232]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 12\. 사후관리 무상점검 정보(DLM_TB_ERP_FREE_INSPEC)

In [233]:
name = 'DLM_TB_ERP_FREE_INSPEC'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

41 8
(629, 41) (629, 8)

In [234]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수  행_수
ODS    41  629
STD     8  629

### 컬럼 확인

In [235]:
odf.columns.to_list()

['CHK_MNGT_NO',
 'REDUC_REG_NO',
 'VHRNO',
 'VIN',
 'MKR_CD',
 'RCPT_LOCGOV_CD',
 'PRGRE_STUS',
 'USER_ZIP',
 'USER_1_ADRS',
 'USER_2_ADRS',
 'USER_TELNO',
 'CHK_DE',
 'CHK_CST',
 'CHK_ENTRPS_NM',
 'BF_DRVNG_DSTNC',
 'AFTR_DRVNG_DSTNC',
 'INST_ID',
 'INPT_DE',
 'RETR_NM',
 'SBSIDY_TRGT_YN',
 'SBSIDY_TRGT_EXCLU_RESN',
 'LOCGOV_CNFRM_DE',
 'LOCGOV_CNFRMR_NM',
 'LOCGOV_INPT_DE',
 'CLNING_RQEST_GRP_NO',
 'SBSIDY_RQT_DE',
 'SBSIDY_APLICT_NM',
 'SBSIDY_RQT_INPT_DE',
 'SBSIDY_PYMT_DE',
 'SBSIDY_BIZ_YR',
 'SBSIDY_PYMT_YN',
 'SBSIDY_PYMT_DCSN_DE',
 'SBSIDY_PYMT_IDNTFR_NM',
 'SBSIDY_PYMT_REG_DE',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'FUEL_SMO',
 'COST_YEAR',
 'COST_DATE',
 'COST_TYPE',
 'COST_NOTE']

In [236]:
olist = [
    'VHRNO',
    'VIN',
    'SBSIDY_TRGT_YN',
    'CHK_ENTRPS_NM',
    'CHK_DE',
    'AFTR_DRVNG_DSTNC',
    'PRGRE_STUS',
    'REDUC_REG_NO',

    'CHK_MNGT_NO',
    'MKR_CD',
    'RCPT_LOCGOV_CD',
    'USER_ZIP',
    'USER_1_ADRS',
    'USER_2_ADRS',
    'USER_TELNO',
    'CHK_CST',
    'BF_DRVNG_DSTNC',
    'INST_ID',
    'INPT_DE',
    'RETR_NM',
    'SBSIDY_TRGT_EXCLU_RESN',
    'LOCGOV_CNFRM_DE',
    'LOCGOV_CNFRMR_NM',
    'LOCGOV_INPT_DE',
    'CLNING_RQEST_GRP_NO',
    'SBSIDY_RQT_DE',
    'SBSIDY_APLICT_NM',
    'SBSIDY_RQT_INPT_DE',
    'SBSIDY_PYMT_DE',
    'SBSIDY_BIZ_YR',
    'SBSIDY_PYMT_YN',
    'SBSIDY_PYMT_DCSN_DE',
    'SBSIDY_PYMT_IDNTFR_NM',
    'SBSIDY_PYMT_REG_DE',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'FUEL_SMO',
    'COST_YEAR',
    'COST_DATE',
    'COST_TYPE',
    'COST_NOTE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차량등록번호',
    '차대번호',
    '보조금대상YN',
    '점검업체명',
    '점검일자',
    '이후주행거리',
    '무상점검진행상태',
    '저감등록번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼        내용
0                    VHRNO    차량등록번호
1                      VIN      차대번호
2           SBSIDY_TRGT_YN   보조금대상YN
3            CHK_ENTRPS_NM     점검업체명
4                   CHK_DE      점검일자
5         AFTR_DRVNG_DSTNC    이후주행거리
6               PRGRE_STUS  무상점검진행상태
7             REDUC_REG_NO    저감등록번호
8              CHK_MNGT_NO        미정
9                   MKR_CD        미정
10          RCPT_LOCGOV_CD        미정
11                USER_ZIP        미정
12             USER_1_ADRS        미정
13             USER_2_ADRS        미정
14              USER_TELNO        미정
15                 CHK_CST        미정
16          BF_DRVNG_DSTNC        미정
17                 INST_ID        미정
18                 INPT_DE        미정
19                 RETR_NM        미정
20  SBSIDY_TRGT_EXCLU_RESN        미정
21         LOCGOV_CNFRM_DE        미정
22        LOCGOV_CNFRMR_NM        미정
23          LOCGOV_INPT_DE        미정
24     CLNING_RQEST_GRP_NO        미정
25           SBSIDY_RQT_DE        미정
26        SBSIDY_APLICT_NM        미정
27      SBSIDY_RQT_INPT_DE        미정
28          SBSIDY_PYMT_DE        미정
29           SBSIDY_BIZ_YR        미정
30          SBSIDY_PYMT_YN        미정
31     SBSIDY_PYMT_DCSN_DE        미정
32   SBSIDY_PYMT_IDNTFR_NM        미정
33      SBSIDY_PYMT_REG_DE        미정
34             LST_CHNG_DE        미정
35             LST_EDIR_NM        미정
36                FUEL_SMO        미정
37               COST_YEAR        미정
38               COST_DATE        미정
39               COST_TYPE        미정
40               COST_NOTE        미정

In [237]:
sdf.columns.to_list()

['AFTR_DRVNG_DSTNC',
 'CHCK_YMD',
 'GRTUI_CHCK_PRGRS_STS',
 'REDUC_REG_NO',
 'VHRNO',
 'VIN',
 'CHCK_ENTRPS_NM',
 'SBSIDY_TRGT_YN']

In [238]:
slist = [
    'VHRNO',
    'VIN',
    'SBSIDY_TRGT_YN',
    'CHCK_ENTRPS_NM',
    'CHCK_YMD',
    'AFTR_DRVNG_DSTNC',
    'GRTUI_CHCK_PRGRS_STS',
    'REDUC_REG_NO',

    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차량등록번호',
    '차대번호',
    '보조금대상여부',
    '점검업체명',
    '점검일자',
    '이후주행거리',
    '무상점검진행상태',
    '저감등록번호',]
    }

scol = pd.DataFrame(sdict)
scol

                     컬럼        내용
0                 VHRNO    차량등록번호
1                   VIN      차대번호
2        SBSIDY_TRGT_YN   보조금대상여부
3        CHCK_ENTRPS_NM     점검업체명
4              CHCK_YMD      점검일자
5      AFTR_DRVNG_DSTNC    이후주행거리
6  GRTUI_CHCK_PRGRS_STS  무상점검진행상태
7          REDUC_REG_NO    저감등록번호

### 데이터 info

In [239]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,VHRNO,차량등록번호,629,VHRNO,차량등록번호,629.0,0.0,0,0.0
1,VIN,차대번호,628,VIN,차대번호,628.0,0.0,1,1.0
2,SBSIDY_TRGT_YN,보조금대상YN,628,SBSIDY_TRGT_YN,보조금대상여부,628.0,0.0,1,1.0
3,CHK_ENTRPS_NM,점검업체명,629,CHCK_ENTRPS_NM,점검업체명,629.0,0.0,0,0.0
4,CHK_DE,점검일자,629,CHCK_YMD,점검일자,629.0,0.0,0,0.0

### [출력]

In [240]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 13\. 저감장치 인증등록번호(DLM_TB_ERP_RED_TYPE)

In [241]:
name = 'DLM_TB_ERP_RED_TYPE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

32 13
(1961, 32) (1961, 13)

In [242]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    32  1961
STD    13  1961

### 컬럼 확인

In [243]:
odf.columns.to_list()

['SEQ_NO',
 'MKR_CD',
 'CRTC_MODL_NO',
 'RDCDVC_SE',
 'RDCDVC_KND',
 'REDUC_VHCTY_SE',
 'SBSIDY_AMT',
 'SBSIDY_SLFBDN_AMT',
 'SBSIDY_BIZ_YR',
 'TDMS_SBSIDY_AMT',
 'LWBCT_SBSIDY_AMT',
 'LWBCT_TDMS_SBSIDY_AMT',
 'CRTC_MODL_KND',
 'PFMCRTC_RSLT_INPT_DE',
 'PFMCRTC_RSLT_RETR_NM',
 'PFMCRTC_VENTL_TMPR_VAL',
 'PFMCRTC_VENTL_TMPR_1_STDR',
 'PFMCRTC_VENTL_TMPR_2_STDR',
 'PFMCRTC_VENTL_PSSR_VAL',
 'PFMCRTC_VENTL_PSSR_1_STDR',
 'PFMCRTC_VENTL_PSSR_2_STDR',
 'RDCDVC_EGIN_NM',
 'PM_REDUC_EFCNY',
 'REG_DE',
 'REGR_NM',
 'LST_CHNG_DT',
 'LST_EDIR_NM',
 'PM_LST_REDUC_EFCNY',
 'JEWEL_VAL',
 'SCRAP_VAL',
 'EX_VAL',
 'LST_CHNG_DE']

In [244]:
olist = [
    'REDUC_VHCTY_SE',
    'SEQ_NO',
    'RDCDVC_EGIN_NM',
    'PM_LST_REDUC_EFCNY',
    'PFMCRTC_VENTL_TMPR_VAL',
    'CRTC_MODL_KND',
    'PFMCRTC_VENTL_TMPR_1_STDR',
    'PFMCRTC_VENTL_PSSR_VAL',
    'PFMCRTC_VENTL_PSSR_2_STDR',
    'CRTC_MODL_NO',
    'PFMCRTC_VENTL_PSSR_1_STDR',
    'PFMCRTC_VENTL_TMPR_2_STDR',

    'MKR_CD',
    'RDCDVC_SE',
    'RDCDVC_KND',
    'SBSIDY_AMT',
    'SBSIDY_SLFBDN_AMT',
    'SBSIDY_BIZ_YR',
    'TDMS_SBSIDY_AMT',
    'LWBCT_SBSIDY_AMT',
    'LWBCT_TDMS_SBSIDY_AMT',
    'PFMCRTC_RSLT_INPT_DE',
    'PFMCRTC_RSLT_RETR_NM',
    'PM_REDUC_EFCNY',
    'REG_DE',
    'REGR_NM',
    'LST_CHNG_DT',
    'LST_EDIR_NM',
    'JEWEL_VAL',
    'SCRAP_VAL',
    'EX_VAL',
    'LST_CHNG_DE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['저감차종구분',
    '일련번호',
    '저감장치엔진명',
    'PM최종저감효율',
    '성능인증배기온도값',
    '인증모델종류',
    '성능인증배기온도1기준',
    '성능인증배기압력값',
    '성능인증배기압력2기준',
    '인증모델번호',
    '성능인증배기압력1기준',
    '성능인증배기온도2기준',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                           컬럼           내용
0              REDUC_VHCTY_SE       저감차종구분
1                      SEQ_NO         일련번호
2              RDCDVC_EGIN_NM      저감장치엔진명
3          PM_LST_REDUC_EFCNY     PM최종저감효율
4      PFMCRTC_VENTL_TMPR_VAL    성능인증배기온도값
5               CRTC_MODL_KND       인증모델종류
6   PFMCRTC_VENTL_TMPR_1_STDR  성능인증배기온도1기준
7      PFMCRTC_VENTL_PSSR_VAL    성능인증배기압력값
8   PFMCRTC_VENTL_PSSR_2_STDR  성능인증배기압력2기준
9                CRTC_MODL_NO       인증모델번호
10  PFMCRTC_VENTL_PSSR_1_STDR  성능인증배기압력1기준
11  PFMCRTC_VENTL_TMPR_2_STDR  성능인증배기온도2기준
12                     MKR_CD           미정
13                  RDCDVC_SE           미정
14                 RDCDVC_KND           미정
15                 SBSIDY_AMT           미정
16          SBSIDY_SLFBDN_AMT           미정
17              SBSIDY_BIZ_YR           미정
18            TDMS_SBSIDY_AMT           미정
19           LWBCT_SBSIDY_AMT           미정
20      LWBCT_TDMS_SBSIDY_AMT           미정
21       PFMCRTC_RSLT_INPT_DE           미정
22       PFMCRTC_RSLT_RETR_NM           미정
23             PM_REDUC_EFCNY           미정
24                     REG_DE           미정
25                    REGR_NM           미정
26                LST_CHNG_DT           미정
27                LST_EDIR_NM           미정
28                  JEWEL_VAL           미정
29                  SCRAP_VAL           미정
30                     EX_VAL           미정
31                LST_CHNG_DE           미정

In [245]:
sdf.columns.to_list()

['CERT_MODL_KND',
 'CERT_MODL_NO',
 'PFMCRTC_VENTL_PSSR1_CRTR',
 'PFMCRTC_VENTL_PSSR2_CRTR',
 'PFMCRTC_VENTL_PSSR_VAL',
 'PFMCRTC_VENTL_TMPRT1_CRTR',
 'PFMCRTC_VENTL_TMPRT2_CRTR',
 'PFMCRTC_VENTL_TMPRT_VAL',
 'PM_LAST_REDUC_EFCNY',
 'RDCDVC_EGIN_NM',
 'REDUC_VHCTY_SE_CD',
 'SN',
 'MNFCTR_CD']

In [246]:
slist = [
    'REDUC_VHCTY_SE_CD',
    'SN',
    'RDCDVC_EGIN_NM',
    'PM_LAST_REDUC_EFCNY',
    'PFMCRTC_VENTL_TMPRT_VAL',
    'CERT_MODL_KND',
    'PFMCRTC_VENTL_TMPRT1_CRTR',
    'PFMCRTC_VENTL_PSSR_VAL',
    'PFMCRTC_VENTL_PSSR2_CRTR',
    'CERT_MODL_NO',
    'PFMCRTC_VENTL_PSSR1_CRTR',
    'PFMCRTC_VENTL_TMPRT2_CRTR',

    'MNFCTR_CD', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['저감차종구분코드',
    '일련번호',
    '저감장치엔진명',
    'PM최종저감효율',
    '성능인증배기온도값',
    '인증모델종류',
    '성능인증배기온도1기준',
    '성능인증배기압력값',
    '성능인증배기압력2기준',
    '인증모델번호',
    '성능인증배기압력1기준',
    '성능인증배기온도2기준',

    '미정', ]
    }

scol = pd.DataFrame(sdict)
scol

                           컬럼           내용
0           REDUC_VHCTY_SE_CD     저감차종구분코드
1                          SN         일련번호
2              RDCDVC_EGIN_NM      저감장치엔진명
3         PM_LAST_REDUC_EFCNY     PM최종저감효율
4     PFMCRTC_VENTL_TMPRT_VAL    성능인증배기온도값
5               CERT_MODL_KND       인증모델종류
6   PFMCRTC_VENTL_TMPRT1_CRTR  성능인증배기온도1기준
7      PFMCRTC_VENTL_PSSR_VAL    성능인증배기압력값
8    PFMCRTC_VENTL_PSSR2_CRTR  성능인증배기압력2기준
9                CERT_MODL_NO       인증모델번호
10   PFMCRTC_VENTL_PSSR1_CRTR  성능인증배기압력1기준
11  PFMCRTC_VENTL_TMPRT2_CRTR  성능인증배기온도2기준
12                  MNFCTR_CD           미정

### 데이터 info

In [247]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,REDUC_VHCTY_SE,저감차종구분,1589,REDUC_VHCTY_SE_CD,저감차종구분코드,1589.0,0.0,372,372.0
1,SEQ_NO,일련번호,1961,SN,일련번호,1961.0,0.0,0,0.0
2,RDCDVC_EGIN_NM,저감장치엔진명,1816,RDCDVC_EGIN_NM,저감장치엔진명,1816.0,0.0,145,145.0
3,PM_LST_REDUC_EFCNY,PM최종저감효율,1199,PM_LAST_REDUC_EFCNY,PM최종저감효율,1199.0,0.0,762,762.0
4,PFMCRTC_VENTL_TMPR_VAL,성능인증배기온도값,752,PFMCRTC_VENTL_TMPRT_VAL,성능인증배기온도값,752.0,0.0,1209,1209.0

### [출력]

In [248]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 14\. 저감사업 성능유지 확인검사(DLM_TB_PFM_FILE)

In [249]:
name = 'DLM_TB_PFM_FILE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

65 14
(418131, 65) (418131, 14)

In [250]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS    65  418131
STD    14  418131

### 컬럼 확인

In [251]:
odf.columns.to_list()

['REDUC_REG_NO',
 'PFMCFINPC_NO',
 'VHRNO',
 'VIN',
 'PFMCFINPC_DE',
 'STRCHG_DE',
 'RCPT_LOCGOV_CD',
 'INSPOF_CD',
 'FILE_NM',
 'NTJDMT_RESN',
 'DRVNG_TMPR_DISTRB_JDGMNT',
 'PFMCFINPC_SMO_DNSTY',
 'PFMCFINPC_EGINPWR',
 'INSP_KND',
 'INSP_SCAL_SE',
 'INSP_CST',
 'CNFRMR_NM',
 'PFMCFINPC_GNRLZ_JDGMNT',
 'SMO_CND_JDGMNT',
 'CRTC_MODL_NO',
 'MKR_CD',
 'CRTC_CND_INSP_REG_YN',
 'CRTC_CND_INSP_REGR_NM',
 'CRTC_CND_INSP_REG_DE',
 'RETR_NM',
 'INPT_DE',
 'LST_CHNG_DT',
 'LST_EDIR_NM',
 'RDCDVC_SE',
 'RDCDVC_KND',
 'VHCNM',
 'VHCL_YRIDNW',
 'EGINTY',
 'FST_REG_DE',
 'CRTC_TMPR_STDR',
 'CRTC_TMPR_PROVS_ACML_DISTRB',
 'STDR_ACML_DISTRB_PROVS_TMPR',
 'CRTC_PSSR_STDR',
 'CRTC_PSSR_PROVS_ACML_DISTRB',
 'STDR_ACML_DISTRB_PROVS_PSSR',
 'INSPOF_NM',
 'FILE_BAK_YN',
 'RINSP_CNT',
 'IMPPRTY_RESN',
 'EXCS_RT',
 'OWNR_NM',
 'OWNR_1_ADRS',
 'OWNR_2_ADRS',
 'OWNR_TELNO',
 'OWNR_BTHDY',
 'INSPOF_RPRSTV_NM',
 'FILE_EXTPR_NM',
 'PFMINPC_CST_PYMT_CNFRM_DE',
 'PFMINPC_CST_PYMT_APRR_NM',
 'PFMINPC_CST_CNFRM_YN',
 'PFMINPC_CST_PYMT_DE',
 'PFMINPC_CST_PYMT_BIZ_YR',
 'INSP_TM_INFO',
 'CTNT',
 'INSP_IMPPRTY_TRTMNT_REG_DE',
 'INSP_IMPPRTY_TRTMNT_YN',
 'DVICE_AS_TRTMNT_DE',
 'DVICE_AS_TRTMNT_DTL',
 'INSP_IMPPRTY_RESN',
 'PFMCFINPC_DE_CHNG_RESN']

In [252]:
olist = [
    'SMO_CND_JDGMNT',
    'PFMCFINPC_GNRLZ_JDGMNT',
    'REDUC_REG_NO',
    'PFMCFINPC_SMO_DNSTY',
    'INSP_KND',
    'VIN',
    'PFMCFINPC_DE',
    'PFMCFINPC_NO',
    'INSPOF_NM',
    'VHRNO',

    'STRCHG_DE',
    'RCPT_LOCGOV_CD',
    'INSPOF_CD',
    'FILE_NM',
    'NTJDMT_RESN',
    'DRVNG_TMPR_DISTRB_JDGMNT',
    'PFMCFINPC_EGINPWR',
    'INSP_SCAL_SE',
    'INSP_CST',
    'CNFRMR_NM',
    'CRTC_MODL_NO',
    'MKR_CD',
    'CRTC_CND_INSP_REG_YN',
    'CRTC_CND_INSP_REGR_NM',
    'CRTC_CND_INSP_REG_DE',
    'RETR_NM',
    'INPT_DE',
    'LST_CHNG_DT',
    'LST_EDIR_NM',
    'RDCDVC_SE',
    'RDCDVC_KND',
    'VHCNM',
    'VHCL_YRIDNW',
    'EGINTY',
    'FST_REG_DE',
    'CRTC_TMPR_STDR',
    'CRTC_TMPR_PROVS_ACML_DISTRB',
    'STDR_ACML_DISTRB_PROVS_TMPR',
    'CRTC_PSSR_STDR',
    'CRTC_PSSR_PROVS_ACML_DISTRB',
    'STDR_ACML_DISTRB_PROVS_PSSR',
    'FILE_BAK_YN',
    'RINSP_CNT',
    'IMPPRTY_RESN',
    'EXCS_RT',
    'OWNR_NM',
    'OWNR_1_ADRS',
    'OWNR_2_ADRS',
    'OWNR_TELNO',
    'OWNR_BTHDY',
    'INSPOF_RPRSTV_NM',
    'FILE_EXTPR_NM',
    'PFMINPC_CST_PYMT_CNFRM_DE',
    'PFMINPC_CST_PYMT_APRR_NM',
    'PFMINPC_CST_CNFRM_YN',
    'PFMINPC_CST_PYMT_DE',
    'PFMINPC_CST_PYMT_BIZ_YR',
    'INSP_TM_INFO',
    'CTNT',
    'INSP_IMPPRTY_TRTMNT_REG_DE',
    'INSP_IMPPRTY_TRTMNT_YN',
    'DVICE_AS_TRTMNT_DE',
    'DVICE_AS_TRTMNT_DTL',
    'INSP_IMPPRTY_RESN',
    'PFMCFINPC_DE_CHNG_RESN', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['매연조건판정',
    '성능확인검사종합판정',
    '저감등록번호',
    '성능확인검사매연농도',
    '검사종류',
    '차대번호',
    '성능확인검사일자',
    '성능확인검사번호',
    '검사소명',
    '차량등록번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼          내용
0           SMO_CND_JDGMNT      매연조건판정
1   PFMCFINPC_GNRLZ_JDGMNT  성능확인검사종합판정
2             REDUC_REG_NO      저감등록번호
3      PFMCFINPC_SMO_DNSTY  성능확인검사매연농도
4                 INSP_KND        검사종류
..                     ...         ...
60  INSP_IMPPRTY_TRTMNT_YN          미정
61      DVICE_AS_TRTMNT_DE          미정
62     DVICE_AS_TRTMNT_DTL          미정
63       INSP_IMPPRTY_RESN          미정
64  PFMCFINPC_DE_CHNG_RESN          미정

[65 rows x 2 columns]

In [253]:
sdf.columns.to_list()

['INSPOF_NM',
 'INSP_KND_CD',
 'PFMCFINPC_YMD',
 'PFMCFINPC_GNRLZ_JGMT',
 'PFMCFINPC_NO',
 'PFMCFINPC_SMO_CNTRVL',
 'RDCDVC_REG_NO',
 'SMO_CND_JGMT_CD',
 'VHRNO',
 'VIN',
 'MAXM_OTPT_MSRMT_VAL',
 'STRCT_CHG_YMD',
 'RDCDVC_SE_CD',
 'RDCDVC_KND']

In [254]:
slist = [
    'SMO_CND_JGMT_CD',
    'PFMCFINPC_GNRLZ_JGMT',
    'RDCDVC_REG_NO',
    'PFMCFINPC_SMO_CNTRVL',
    'INSP_KND_CD',
    'VIN',
    'PFMCFINPC_YMD',
    'PFMCFINPC_NO',
    'INSPOF_NM',
    'VHRNO',

    'MAXM_OTPT_MSRMT_VAL',
    'STRCT_CHG_YMD',
    'RDCDVC_SE_CD',
    'RDCDVC_KND', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['매연조건판정코드',
    '성능확인검사종합판정',
    '저감장치등록번호',
    '성능확인검사매연농도값',
    '검사종류코드',
    '차대번호',
    '성능확인검사일자',
    '성능확인검사번호',
    '검사소명',
    '자동차등록번호',

    '미정',
    '미정',
    '미정',
    '미정', ]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼           내용
0        SMO_CND_JGMT_CD     매연조건판정코드
1   PFMCFINPC_GNRLZ_JGMT   성능확인검사종합판정
2          RDCDVC_REG_NO     저감장치등록번호
3   PFMCFINPC_SMO_CNTRVL  성능확인검사매연농도값
4            INSP_KND_CD       검사종류코드
5                    VIN         차대번호
6          PFMCFINPC_YMD     성능확인검사일자
7           PFMCFINPC_NO     성능확인검사번호
8              INSPOF_NM         검사소명
9                  VHRNO      자동차등록번호
10   MAXM_OTPT_MSRMT_VAL           미정
11         STRCT_CHG_YMD           미정
12          RDCDVC_SE_CD           미정
13            RDCDVC_KND           미정

### 데이터 info

In [255]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,SMO_CND_JDGMNT,매연조건판정,416681,SMO_CND_JGMT_CD,매연조건판정코드,416681.0,0.0,1450,1450.0
1,PFMCFINPC_GNRLZ_JDGMNT,성능확인검사종합판정,417140,PFMCFINPC_GNRLZ_JGMT,성능확인검사종합판정,417140.0,0.0,991,991.0
2,REDUC_REG_NO,저감등록번호,418117,RDCDVC_REG_NO,저감장치등록번호,418117.0,0.0,14,14.0
3,PFMCFINPC_SMO_DNSTY,성능확인검사매연농도,401461,PFMCFINPC_SMO_CNTRVL,성능확인검사매연농도값,401461.0,0.0,16670,16670.0
4,INSP_KND,검사종류,415979,INSP_KND_CD,검사종류코드,415979.0,0.0,2152,2152.0

### [출력]

In [256]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 15\. 운행제한 발령정보(N_IS_ISSUE)

In [257]:
name = 'N_IS_ISSUE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

16 4
(1785, 16) (1785, 4)

In [258]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    16  1785
STD     4  1785

### 컬럼 확인

In [259]:
odf.columns.to_list()

['GNFD_NO',
 'RPST_GNFD_NO',
 'DNSTY_STDR_ID',
 'TY_STDR_ID',
 'GNFD_NM',
 'GNFD_EXEC_CND_FLAG',
 'GNFD_EXEC_RESRV_DT',
 'BEFT_ESTBS_ID',
 'DC',
 'GNFD_EXC_FLAG',
 'HMPG_INDIC_YN',
 'LCINFO_API_YN',
 'REG_ID',
 'REG_DT',
 'UPDT_ID',
 'UPDT_DT']

In [260]:
olist = [
    'TY_STDR_ID',
    'UPDT_DT', 
    'DNSTY_STDR_ID',
    'GNFD_NO',

    'RPST_GNFD_NO',
    'GNFD_NM',
    'GNFD_EXEC_CND_FLAG',
    'GNFD_EXEC_RESRV_DT',
    'BEFT_ESTBS_ID',
    'DC',
    'GNFD_EXC_FLAG',
    'HMPG_INDIC_YN',
    'LCINFO_API_YN',
    'REG_ID',
    'REG_DT',
    'UPDT_ID',
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['유형 구분',
    '수정 일시', 
    '농도기준 발령구분',
    '발령 번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

ocol = pd.DataFrame(odict)
ocol

                    컬럼         내용
0           TY_STDR_ID      유형 구분
1              UPDT_DT      수정 일시
2        DNSTY_STDR_ID  농도기준 발령구분
3              GNFD_NO      발령 번호
4         RPST_GNFD_NO         미정
5              GNFD_NM         미정
6   GNFD_EXEC_CND_FLAG         미정
7   GNFD_EXEC_RESRV_DT         미정
8        BEFT_ESTBS_ID         미정
9                   DC         미정
10       GNFD_EXC_FLAG         미정
11       HMPG_INDIC_YN         미정
12       LCINFO_API_YN         미정
13              REG_ID         미정
14              REG_DT         미정
15             UPDT_ID         미정

In [261]:
sdf.columns.to_list()

['CCNTRA_CRTR_GNFD_SE', 'GNFD_NO', 'TY_SE', 'MDFCN_DT']

In [262]:
slist = [
    'TY_SE', 
    'MDFCN_DT', 
    'CCNTRA_CRTR_GNFD_SE', 
    'GNFD_NO', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['유형구분', 
    '수정일시', 
    '농도기준발령구분', 
    '발령번호', ]
    }

scol = pd.DataFrame(sdict)
scol

                    컬럼        내용
0                TY_SE      유형구분
1             MDFCN_DT      수정일시
2  CCNTRA_CRTR_GNFD_SE  농도기준발령구분
3              GNFD_NO      발령번호

### 데이터 info

In [263]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,TY_STDR_ID,유형 구분,1785,TY_SE,유형구분,1785.0,0.0,0,0.0
1,UPDT_DT,수정 일시,1652,MDFCN_DT,수정일시,1652.0,0.0,133,133.0
2,DNSTY_STDR_ID,농도기준 발령구분,1785,CCNTRA_CRTR_GNFD_SE,농도기준발령구분,1785.0,0.0,0,0.0
3,GNFD_NO,발령 번호,1785,GNFD_NO,발령번호,1785.0,0.0,0,0.0
4,RPST_GNFD_NO,미정,1785,NaN,NaN,NaN,NaN,0,NaN

### [출력]

In [264]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 16\. [e]비상시 및 계절제 단속발령(N_IS_ISSUE_DISCLOSURE)
- ODS, STD 둘다 없음.

In [36]:
name = 'N_IS_ISSUE_DISCLOSURE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/ODS\\ODS_N_IS_ISSUE_DISCLOSURE.csv'

In [ ]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    16  1785
STD     4  1785

### 컬럼 확인

In [ ]:
odf.columns.to_list()

['GNFD_NO',
 'RPST_GNFD_NO',
 'DNSTY_STDR_ID',
 'TY_STDR_ID',
 'GNFD_NM',
 'GNFD_EXEC_CND_FLAG',
 'GNFD_EXEC_RESRV_DT',
 'BEFT_ESTBS_ID',
 'DC',
 'GNFD_EXC_FLAG',
 'HMPG_INDIC_YN',
 'LCINFO_API_YN',
 'REG_ID',
 'REG_DT',
 'UPDT_ID',
 'UPDT_DT']

In [ ]:
olist = [
    'TY_STDR_ID',
    'UPDT_DT', 
    'DNSTY_STDR_ID',
    'GNFD_NO',

    'RPST_GNFD_NO',
    'GNFD_NM',
    'GNFD_EXEC_CND_FLAG',
    'GNFD_EXEC_RESRV_DT',
    'BEFT_ESTBS_ID',
    'DC',
    'GNFD_EXC_FLAG',
    'HMPG_INDIC_YN',
    'LCINFO_API_YN',
    'REG_ID',
    'REG_DT',
    'UPDT_ID',
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['유형 구분',
    '수정 일시', 
    '농도기준 발령구분',
    '발령 번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

ocol = pd.DataFrame(odict)
ocol

                    컬럼         내용
0           TY_STDR_ID      유형 구분
1              UPDT_DT      수정 일시
2        DNSTY_STDR_ID  농도기준 발령구분
3              GNFD_NO      발령 번호
4         RPST_GNFD_NO         미정
5              GNFD_NM         미정
6   GNFD_EXEC_CND_FLAG         미정
7   GNFD_EXEC_RESRV_DT         미정
8        BEFT_ESTBS_ID         미정
9                   DC         미정
10       GNFD_EXC_FLAG         미정
11       HMPG_INDIC_YN         미정
12       LCINFO_API_YN         미정
13              REG_ID         미정
14              REG_DT         미정
15             UPDT_ID         미정

In [ ]:
sdf.columns.to_list()

['CCNTRA_CRTR_GNFD_SE', 'GNFD_NO', 'TY_SE', 'MDFCN_DT']

In [ ]:
slist = [
    'TY_SE', 
    'MDFCN_DT', 
    'CCNTRA_CRTR_GNFD_SE', 
    'GNFD_NO', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['유형구분', 
    '수정일시', 
    '농도기준발령구분', 
    '발령번호', ]
    }

scol = pd.DataFrame(sdict)
scol

                    컬럼        내용
0                TY_SE      유형구분
1             MDFCN_DT      수정일시
2  CCNTRA_CRTR_GNFD_SE  농도기준발령구분
3              GNFD_NO      발령번호

### 데이터 info

In [ ]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

                oindex  ocount               sindex  scount   차이
0           TY_STDR_ID    1785                TY_SE  1785.0  0.0
1              UPDT_DT    1652             MDFCN_DT  1652.0  0.0
2        DNSTY_STDR_ID    1785  CCNTRA_CRTR_GNFD_SE  1785.0  0.0
3              GNFD_NO    1785              GNFD_NO  1785.0  0.0
4         RPST_GNFD_NO    1785                  NaN     NaN  NaN
5              GNFD_NM    1785                  NaN     NaN  NaN
6   GNFD_EXEC_CND_FLAG    1785                  NaN     NaN  NaN
7   GNFD_EXEC_RESRV_DT    1784                  NaN     NaN  NaN
8        BEFT_ESTBS_ID       0                  NaN     NaN  NaN
9                   DC    1785                  NaN     NaN  NaN
10       GNFD_EXC_FLAG    1785                  NaN     NaN  NaN
11       HMPG_INDIC_YN    1785                  NaN     NaN  NaN
12       LCINFO_API_YN    1785                  NaN     NaN  NaN
13              REG_ID    1785                  NaN     NaN  NaN
14              REG_DT    1785                  NaN     NaN  NaN
15             UPDT_ID    1652                  NaN     NaN  NaN

### [출력]

In [ ]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 17\. 운행제한 단속정보(N_US_DISCLOSURE)

In [265]:
name = 'N_US_DISCLOSURE'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

17 6
(3090035, 17) (3075037, 6)

In [266]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수      행_수
ODS    17  3090035
STD     6  3075037

### 컬럼 확인

In [267]:
odf.columns.to_list()

['NO',
 'ODR_YM',
 'REG_SIDO_CD',
 'REG_SIGNGU_CD',
 'DISCL_TY',
 'REGLT_AREA_CD',
 'TFCLNE_ID',
 'DISCL_DEHMS',
 'VHMNO',
 'VIN',
 'VHRNO',
 'FILE_NM',
 'ORG_FILE_CURS_NM',
 'THUMB_FILE_CURS_NM',
 'DTL_FILE_CURS_NM',
 'REG_ID',
 'REG_DT']

In [268]:
olist = [
    'DISCL_DEHMS',
    'VIN',
    'VHRNO',
    'DISCL_TY',
    'REGLT_AREA_CD',
    'VHMNO',

    'NO',
    'ODR_YM',
    'REG_SIDO_CD',
    'REG_SIGNGU_CD',
    'TFCLNE_ID',
    'FILE_NM',
    'ORG_FILE_CURS_NM',
    'THUMB_FILE_CURS_NM',
    'DTL_FILE_CURS_NM',
    'REG_ID',
    'REG_DT', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['적발일시',
    '차대번호',
    '차량등록번호',
    '적발유형',
    '단속지역코드',
    '차량관리번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                    컬럼      내용
0          DISCL_DEHMS    적발일시
1                  VIN    차대번호
2                VHRNO  차량등록번호
3             DISCL_TY    적발유형
4        REGLT_AREA_CD  단속지역코드
5                VHMNO  차량관리번호
6                   NO      미정
7               ODR_YM      미정
8          REG_SIDO_CD      미정
9        REG_SIGNGU_CD      미정
10           TFCLNE_ID      미정
11             FILE_NM      미정
12    ORG_FILE_CURS_NM      미정
13  THUMB_FILE_CURS_NM      미정
14    DTL_FILE_CURS_NM      미정
15              REG_ID      미정
16              REG_DT      미정

In [269]:
sdf.columns.to_list()

['DSCL_DT', 'DSCL_TY_CD', 'CRDN_RGN_CD', 'VHCL_MNG_NO', 'VIN', 'VHRNO']

In [270]:
slist = [
    'DSCL_DT', 
    'VIN', 
    'VHRNO', 
    'DSCL_TY_CD', 
    'CRDN_RGN_CD', 
    'VHCL_MNG_NO', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['적발일시', 
    '차대번호', 
    '차량등록번호', 
    '적발유형코드', 
    '단속지역코드', 
    '차량관리번호', ]
    }

scol = pd.DataFrame(sdict)
scol

            컬럼      내용
0      DSCL_DT    적발일시
1          VIN    차대번호
2        VHRNO  차량등록번호
3   DSCL_TY_CD  적발유형코드
4  CRDN_RGN_CD  단속지역코드
5  VHCL_MNG_NO  차량관리번호

### 데이터 info

In [271]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,DISCL_DEHMS,적발일시,3090035,DSCL_DT,적발일시,3075037.0,14998.0,0,0.0
1,VIN,차대번호,3090035,VIN,차대번호,3075037.0,14998.0,0,0.0
2,VHRNO,차량등록번호,3090035,VHRNO,차량등록번호,3075037.0,14998.0,0,0.0
3,DISCL_TY,적발유형,3090035,DSCL_TY_CD,적발유형코드,3075037.0,14998.0,0,0.0
4,REGLT_AREA_CD,단속지역코드,3090035,CRDN_RGN_CD,단속지역코드,3075037.0,14998.0,0,0.0

### [출력]

In [272]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 18\. [e]정밀검사 검사정보(TB_EET_HIS_ME)
- ODS, STD 없음

In [46]:
name = 'TB_EET_HIS_ME'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/ODS\\ODS_TB_EET_HIS_ME.csv'

In [ ]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수      행_수
ODS    17  3090035
STD     6  3075037

### 컬럼 확인

In [ ]:
odf.columns.to_list()

['NO',
 'ODR_YM',
 'REG_SIDO_CD',
 'REG_SIGNGU_CD',
 'DISCL_TY',
 'REGLT_AREA_CD',
 'TFCLNE_ID',
 'DISCL_DEHMS',
 'VHMNO',
 'VIN',
 'VHRNO',
 'FILE_NM',
 'ORG_FILE_CURS_NM',
 'THUMB_FILE_CURS_NM',
 'DTL_FILE_CURS_NM',
 'REG_ID',
 'REG_DT']

In [ ]:
olist = [
    'DISCL_DEHMS',
    'VIN',
    'VHRNO',
    'DISCL_TY',
    'REGLT_AREA_CD',
    'VHMNO',

    'NO',
    'ODR_YM',
    'REG_SIDO_CD',
    'REG_SIGNGU_CD',
    'TFCLNE_ID',
    'FILE_NM',
    'ORG_FILE_CURS_NM',
    'THUMB_FILE_CURS_NM',
    'DTL_FILE_CURS_NM',
    'REG_ID',
    'REG_DT', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['적발일시',
    '차대번호',
    '차량등록번호',
    '적발유형',
    '단속지역코드',
    '차량관리번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                    컬럼      내용
0          DISCL_DEHMS    적발일시
1                  VIN    차대번호
2                VHRNO  차량등록번호
3             DISCL_TY    적발유형
4        REGLT_AREA_CD  단속지역코드
5                VHMNO  차량관리번호
6                   NO      미정
7               ODR_YM      미정
8          REG_SIDO_CD      미정
9        REG_SIGNGU_CD      미정
10           TFCLNE_ID      미정
11             FILE_NM      미정
12    ORG_FILE_CURS_NM      미정
13  THUMB_FILE_CURS_NM      미정
14    DTL_FILE_CURS_NM      미정
15              REG_ID      미정
16              REG_DT      미정

In [ ]:
sdf.columns.to_list()

['DSCL_DT', 'DSCL_TY_CD', 'CRDN_RGN_CD', 'VHCL_MNG_NO', 'VIN', 'VHRNO']

In [ ]:
slist = [
    'DSCL_DT', 
    'VIN', 
    'VHRNO', 
    'DSCL_TY_CD', 
    'CRDN_RGN_CD', 
    'VHCL_MNG_NO', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['적발일시', 
    '차대번호', 
    '차량등록번호', 
    '적발유형코드', 
    '단속지역코드', 
    '차량관리번호', ]
    }

scol = pd.DataFrame(sdict)
scol

            컬럼      내용
0      DSCL_DT    적발일시
1          VIN    차대번호
2        VHRNO  차량등록번호
3   DSCL_TY_CD  적발유형코드
4  CRDN_RGN_CD  단속지역코드
5  VHCL_MNG_NO  차량관리번호

### 데이터 info

In [ ]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

                oindex   ocount       sindex     scount       차이
0          DISCL_DEHMS  3090035      DSCL_DT  3075037.0  14998.0
1                  VIN  3090035          VIN  3075037.0  14998.0
2                VHRNO  3090035        VHRNO  3075037.0  14998.0
3             DISCL_TY  3090035   DSCL_TY_CD  3075037.0  14998.0
4        REGLT_AREA_CD  3090035  CRDN_RGN_CD  3075037.0  14998.0
5                VHMNO  3090035  VHCL_MNG_NO  3075037.0  14998.0
6                   NO  3090035          NaN        NaN      NaN
7               ODR_YM  3090035          NaN        NaN      NaN
8          REG_SIDO_CD  3090035          NaN        NaN      NaN
9        REG_SIGNGU_CD  3090035          NaN        NaN      NaN
10           TFCLNE_ID  3090035          NaN        NaN      NaN
11             FILE_NM  3090035          NaN        NaN      NaN
12    ORG_FILE_CURS_NM  3079798          NaN        NaN      NaN
13  THUMB_FILE_CURS_NM  3079072          NaN        NaN      NaN
14    DTL_FILE_CURS_NM  3079072          NaN        NaN      NaN
15              REG_ID  3090035          NaN        NaN      NaN
16              REG_DT  3090035          NaN        NaN      NaN

### [출력]

In [ ]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 19\. 저감장치 부착AS(TB_ERP_ATT_AS)

In [273]:
name = 'TB_ERP_ATT_AS'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

16 6
(20838, 16) (20838, 6)

In [274]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수    행_수
ODS    16  20838
STD     6  20838

### 컬럼 확인

In [275]:
odf.columns.to_list()

['ERP_REG_NO',
 'AS_DATE',
 'AS_CONT',
 'AS_REASON',
 'AS_MONEY',
 'AS_MONEY_METHOD',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'ATT_DATE',
 'MAKER_ORG_CD',
 'CONF_CHG_DATE',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'REC_DATE',
 'REC_NM']

In [276]:
olist = [
    'CAR_SER_NO',
    'ERP_REG_NO',
    'AS_REASON',
    'AS_DATE',
    'AS_CONT',

    'AS_MONEY',
    'AS_MONEY_METHOD',
    'CAR_REG_NO',
    'ATT_DATE',
    'MAKER_ORG_CD',
    'CONF_CHG_DATE',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'REC_DATE',
    'REC_NM',  
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차대번호',
    '저감등록번호',
    'AS 사유',
    'AS 일자',
    'AS 횟수',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                 컬럼      내용
0        CAR_SER_NO    차대번호
1        ERP_REG_NO  저감등록번호
2         AS_REASON   AS 사유
3           AS_DATE   AS 일자
4           AS_CONT   AS 횟수
5          AS_MONEY      미정
6   AS_MONEY_METHOD      미정
7        CAR_REG_NO      미정
8          ATT_DATE      미정
9      MAKER_ORG_CD      미정
10    CONF_CHG_DATE      미정
11        ETC_CONT1      미정
12        ETC_CONT2      미정
13        ETC_CONT3      미정
14         REC_DATE      미정
15           REC_NM      미정

In [277]:
sdf.columns.to_list()

['AS_NCNT', 'AS_YMD', 'AS_RESN', 'VIN', 'REDUC_REG_NO', 'VHRNO']

In [278]:
slist = [
    'VIN', 
    'REDUC_REG_NO', 
    'AS_RESN', 
    'AS_YMD', 
    'AS_NCNT', 

    'VHRNO',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차대번호', 
    '저감등록번호', 
    'AS사유', 
    'AS일자', 
    'AS횟수', 

    '미정', ]
    }

scol = pd.DataFrame(sdict)
scol

             컬럼      내용
0           VIN    차대번호
1  REDUC_REG_NO  저감등록번호
2       AS_RESN    AS사유
3        AS_YMD    AS일자
4       AS_NCNT    AS횟수
5         VHRNO      미정

### 데이터 info

In [279]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CAR_SER_NO,차대번호,20833,VIN,차대번호,20833.0,0.0,5,5.0
1,ERP_REG_NO,저감등록번호,20838,REDUC_REG_NO,저감등록번호,20838.0,0.0,0,0.0
2,AS_REASON,AS 사유,20461,AS_RESN,AS사유,20461.0,0.0,377,377.0
3,AS_DATE,AS 일자,20838,AS_YMD,AS일자,20838.0,0.0,0,0.0
4,AS_CONT,AS 횟수,20838,AS_NCNT,AS횟수,20838.0,0.0,0,0.0

### [출력]

In [280]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 20\. [e]저감장치 부착이력(TB_ERP_ATT_HIS)
- STD 파일 없음

In [55]:
name = 'TB_ERP_ATT_HIS'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/STD\\STD_TB_ERP_ATT_HIS.csv'

In [ ]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수    행_수
ODS    16  20838
STD     6  20838

### 컬럼 확인

In [ ]:
odf.columns.to_list()

['ERP_REG_NO',
 'AS_DATE',
 'AS_CONT',
 'AS_REASON',
 'AS_MONEY',
 'AS_MONEY_METHOD',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'ATT_DATE',
 'MAKER_ORG_CD',
 'CONF_CHG_DATE',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'REC_DATE',
 'REC_NM']

In [ ]:
olist = [
    'CAR_SER_NO',
    'ERP_REG_NO',
    'AS_REASON',
    'AS_DATE',
    'AS_CONT',

    'AS_MONEY',
    'AS_MONEY_METHOD',
    'CAR_REG_NO',
    'ATT_DATE',
    'MAKER_ORG_CD',
    'CONF_CHG_DATE',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'REC_DATE',
    'REC_NM',  
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차대번호',
    '저감등록번호',
    'AS 사유',
    'AS 일자',
    'AS 횟수',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                 컬럼      내용
0        CAR_SER_NO    차대번호
1        ERP_REG_NO  저감등록번호
2         AS_REASON   AS 사유
3           AS_DATE   AS 일자
4           AS_CONT   AS 횟수
5          AS_MONEY      미정
6   AS_MONEY_METHOD      미정
7        CAR_REG_NO      미정
8          ATT_DATE      미정
9      MAKER_ORG_CD      미정
10    CONF_CHG_DATE      미정
11        ETC_CONT1      미정
12        ETC_CONT2      미정
13        ETC_CONT3      미정
14         REC_DATE      미정
15           REC_NM      미정

In [ ]:
sdf.columns.to_list()

['AS_NCNT', 'AS_YMD', 'AS_RESN', 'VIN', 'REDUC_REG_NO', 'VHRNO']

In [ ]:
slist = [
    'VIN', 
    'REDUC_REG_NO', 
    'AS_RESN', 
    'AS_YMD', 
    'AS_NCNT', 

    'VHRNO',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차대번호', 
    '저감등록번호', 
    'AS사유', 
    'AS일자', 
    'AS횟수', 

    '미정', ]
    }

scol = pd.DataFrame(sdict)
scol

             컬럼      내용
0           VIN    차대번호
1  REDUC_REG_NO  저감등록번호
2       AS_RESN    AS사유
3        AS_YMD    AS일자
4       AS_NCNT    AS횟수
5         VHRNO      미정

### 데이터 info

In [ ]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

             oindex  ocount        sindex   scount   차이
0        CAR_SER_NO   20833           VIN  20833.0  0.0
1        ERP_REG_NO   20838  REDUC_REG_NO  20838.0  0.0
2         AS_REASON   20461       AS_RESN  20461.0  0.0
3           AS_DATE   20838        AS_YMD  20838.0  0.0
4           AS_CONT   20838       AS_NCNT  20838.0  0.0
5          AS_MONEY   20838         VHRNO  20838.0  0.0
6   AS_MONEY_METHOD   19037           NaN      NaN  NaN
7        CAR_REG_NO   20838           NaN      NaN  NaN
8          ATT_DATE   19454           NaN      NaN  NaN
9      MAKER_ORG_CD   20838           NaN      NaN  NaN
10    CONF_CHG_DATE    7960           NaN      NaN  NaN
11        ETC_CONT1   20838           NaN      NaN  NaN
12        ETC_CONT2       0           NaN      NaN  NaN
13        ETC_CONT3       0           NaN      NaN  NaN
14         REC_DATE       0           NaN      NaN  NaN
15           REC_NM       0           NaN      NaN  NaN

### [출력]

In [ ]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 21\. 요소수 정보(TB_ERP_UREAWATER)

In [281]:
name = 'TB_ERP_UREAWATER'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

7 3
(80, 7) (80, 3)

In [282]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수  행_수
ODS     7   80
STD     3   80

### 컬럼 확인

In [283]:
odf.columns.to_list()

['ERP_REG_NO',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'REC_DATE',
 'REC_NM',
 'LAS_CHG_DATE',
 'LAS_CHG_NM']

In [284]:
olist = [
    'CAR_SER_NO',
    'ERP_REG_NO',
    'CAR_REG_NO',

    'REC_DATE',
    'REC_NM',
    'LAS_CHG_DATE',
    'LAS_CHG_NM', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차대번호',
    '저감등록번호',
    '차량번호',

    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

             컬럼      내용
0    CAR_SER_NO    차대번호
1    ERP_REG_NO  저감등록번호
2    CAR_REG_NO    차량번호
3      REC_DATE      미정
4        REC_NM      미정
5  LAS_CHG_DATE      미정
6    LAS_CHG_NM      미정

In [285]:
sdf.columns.to_list()

['VHCL_MNG_NO', 'VIN', 'REDUC_REG_NO']

In [286]:
slist = [
    'VIN', 
    'REDUC_REG_NO',
    'VHCL_MNG_NO', 

    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차대번호', 
    '저감등록번호',
    '차량관리번호', ]
    }

scol = pd.DataFrame(sdict)
scol

             컬럼      내용
0           VIN    차대번호
1  REDUC_REG_NO  저감등록번호
2   VHCL_MNG_NO  차량관리번호

### 데이터 info

In [287]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CAR_SER_NO,차대번호,80,VIN,차대번호,80.0,0.0,0,0.0
1,ERP_REG_NO,저감등록번호,80,REDUC_REG_NO,저감등록번호,80.0,0.0,0,0.0
2,CAR_REG_NO,차량번호,80,VHCL_MNG_NO,차량관리번호,80.0,0.0,0,0.0
3,REC_DATE,미정,80,NaN,NaN,NaN,NaN,0,NaN
4,REC_NM,미정,80,NaN,NaN,NaN,NaN,0,NaN

### [출력]

In [288]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 22\. 요소수 상세정보(TB_ERP_UREAWATER_DTL)

In [289]:
name = 'TB_ERP_UREAWATER_DTL'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

14 8
(155, 14) (155, 8)

In [290]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수  행_수
ODS    14  155
STD     8  155

### 컬럼 확인

In [291]:
odf.columns.to_list()

['ERP_REG_NO',
 'UREAWATER_CHK_STS',
 'UREAWATER_LITER',
 'REMAIN_UREAWATER_LITER',
 'UREAWATER_MONEY',
 'REMAIN_UREAWATER_MONEY',
 'UREAWATER_COUNT',
 'UREAWATER_DATE',
 'UREAWATER_NM',
 'LAS_CHG_DATE',
 'LAS_CHG_NM',
 'UREAWATER_FINAL_DATE',
 'UREAWATER_FINAL_NM',
 'RETURN_REASON']

In [292]:
olist = [
    'ERP_REG_NO',
    'REMAIN_UREAWATER_MONEY',
    'UREAWATER_CHK_STS',
    'UREAWATER_DATE',
    'REMAIN_UREAWATER_LITER',
    'UREAWATER_MONEY',
    'UREAWATER_LITER',
    'UREAWATER_COUNT',
    
    'UREAWATER_NM',
    'LAS_CHG_DATE',
    'LAS_CHG_NM',
    'UREAWATER_FINAL_DATE',
    'UREAWATER_FINAL_NM',
    'RETURN_REASON', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['저감등록번호',
    '요소수보충잔여비용',
    '요소수보충진행상태',
    '요소수보충일자',
    '요소수보충잔여리터',
    '요소수보충비용',
    '요소수보충리터',
    '요소수보충횟수',
    
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                        컬럼         내용
0               ERP_REG_NO     저감등록번호
1   REMAIN_UREAWATER_MONEY  요소수보충잔여비용
2        UREAWATER_CHK_STS  요소수보충진행상태
3           UREAWATER_DATE    요소수보충일자
4   REMAIN_UREAWATER_LITER  요소수보충잔여리터
5          UREAWATER_MONEY    요소수보충비용
6          UREAWATER_LITER    요소수보충리터
7          UREAWATER_COUNT    요소수보충횟수
8             UREAWATER_NM         미정
9             LAS_CHG_DATE         미정
10              LAS_CHG_NM         미정
11    UREAWATER_FINAL_DATE         미정
12      UREAWATER_FINAL_NM         미정
13           RETURN_REASON         미정

In [293]:
sdf.columns.to_list()

['REDUC_REG_NO',
 'UREA_SUPPL_RMND_QT',
 'UREA_SUPPL_RMND_CST',
 'UREA_SUPPL_PRGRS_STTS',
 'UREA_SUPPL_NCNT',
 'UREA_SUPPL_YMD',
 'UREA_SUPPL_QT',
 'UREA_SUPPL_CST']

In [294]:
slist = [
    'REDUC_REG_NO',
    'UREA_SUPPL_RMND_CST',
    'UREA_SUPPL_PRGRS_STTS',
    'UREA_SUPPL_YMD',
    'UREA_SUPPL_RMND_QT',
    'UREA_SUPPL_CST', 
    'UREA_SUPPL_QT',
    'UREA_SUPPL_NCNT',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['저감등록번호',
    '요소수보충잔여비용',
    '요소수보충진행상태',
    '요소수보충일자',
    '요소수보충잔여량',
    '요소수보충비용', 
    '요소수보충량',
    '요소수보충횟수',]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼         내용
0           REDUC_REG_NO     저감등록번호
1    UREA_SUPPL_RMND_CST  요소수보충잔여비용
2  UREA_SUPPL_PRGRS_STTS  요소수보충진행상태
3         UREA_SUPPL_YMD    요소수보충일자
4     UREA_SUPPL_RMND_QT   요소수보충잔여량
5         UREA_SUPPL_CST    요소수보충비용
6          UREA_SUPPL_QT     요소수보충량
7        UREA_SUPPL_NCNT    요소수보충횟수

### 데이터 info

In [295]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,ERP_REG_NO,저감등록번호,155,REDUC_REG_NO,저감등록번호,155.0,0.0,0,0.0
1,REMAIN_UREAWATER_MONEY,요소수보충잔여비용,155,UREA_SUPPL_RMND_CST,요소수보충잔여비용,155.0,0.0,0,0.0
2,UREAWATER_CHK_STS,요소수보충진행상태,155,UREA_SUPPL_PRGRS_STTS,요소수보충진행상태,155.0,0.0,0,0.0
3,UREAWATER_DATE,요소수보충일자,155,UREA_SUPPL_YMD,요소수보충일자,155.0,0.0,0,0.0
4,REMAIN_UREAWATER_LITER,요소수보충잔여리터,155,UREA_SUPPL_RMND_QT,요소수보충잔여량,155.0,0.0,0,0.0

### [출력]

In [296]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 23\. 전문정비(TB_ERR_RES)
- STD
    - 컬럼명
        - 'VHRNO' # VHCL_MNG_NO(6. 테이블정의서_v1.0)

In [297]:
name = 'TB_ERR_RES'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

42 16
(54617, 42) (54617, 16)

In [298]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수    행_수
ODS    42  54617
STD    16  54617

### 컬럼 확인

In [299]:
odf.columns.to_list()

['REPAIR_ORG_NM',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'REPAIR_DATE',
 'REPAIR_REG_NO',
 'RE_SMO_CHK_REG_NO',
 'CAR_NM',
 'CAR_YEAR',
 'CAR_OWNER_NM',
 'OFFICE_NM',
 'REPAIR_NM',
 'CAR_FUEL_NM',
 'FIRST_REG_DATE',
 'CAR_MILE',
 'REPAIR_COST',
 'WAR_REPAIR_YN',
 'RE_INS_DATE',
 'WAR_DATE',
 'WAR_KM',
 'REPAIR_COMMENT',
 'LOAD_CO',
 'LOAD_HC',
 'LOAD_NOX',
 'LOAD_SMOKE',
 'LOAD_TORK',
 'UNLOAD_CO',
 'UNLOAD_HC',
 'UNLOAD_SMOKE',
 'UNLOAD_NAM',
 'REPAIR_COMMENT_ETC',
 'REC_DATE',
 'REC_NM',
 'LAS_CHG_DATE',
 'LAS_CHG_NM',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'ETC_CONT4',
 'ETC_CONT5',
 'SRC_TBL',
 'FILE_NM',
 'JOB_DATE']

In [300]:
olist = [
    'LOAD_CO',
    'CAR_SER_NO',
    'CAR_REG_NO',
    'CAR_MILE',
    'LOAD_HC',
    'LOAD_NOX',
    'LOAD_SMOKE',
    'LOAD_TORK',
    'UNLOAD_SMOKE',
    'UNLOAD_NAM',
    'UNLOAD_HC',
    'UNLOAD_CO',
    'REPAIR_REG_NO',
    'REPAIR_ORG_NM',
    'RE_SMO_CHK_REG_NO',
    'REPAIR_DATE',

    'CAR_NM',
    'CAR_YEAR',
    'CAR_OWNER_NM',
    'OFFICE_NM',
    'REPAIR_NM',
    'CAR_FUEL_NM',
    'FIRST_REG_DATE',
    'REPAIR_COST',
    'WAR_REPAIR_YN',
    'RE_INS_DATE',
    'WAR_DATE',
    'WAR_KM',
    'REPAIR_COMMENT',
    'REPAIR_COMMENT_ETC',
    'REC_DATE',
    'REC_NM',
    'LAS_CHG_DATE',
    'LAS_CHG_NM',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'ETC_CONT4',
    'ETC_CONT5',
    'SRC_TBL',
    'FILE_NM',
    'JOB_DATE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['부하일산화탄소측정치',
    '차대번호',
    '차량등록번호',
    '주행거리',
    '부하탄화수소측정치',
    '부하질소산화물측정치',
    '부하매연측정치',
    '부하토크측정치',
    '무부하매연측정치',
    '무부하공기과잉률',
    '무부하탄화수소',
    '무부하일산화탄소',
    '전문정비접수번호',
    '전문정비업소명',
    '정밀재검사접수번호',
    '전문정비일',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

                    컬럼          내용
0              LOAD_CO  부하일산화탄소측정치
1           CAR_SER_NO        차대번호
2           CAR_REG_NO      차량등록번호
3             CAR_MILE        주행거리
4              LOAD_HC   부하탄화수소측정치
5             LOAD_NOX  부하질소산화물측정치
6           LOAD_SMOKE     부하매연측정치
7            LOAD_TORK     부하토크측정치
8         UNLOAD_SMOKE    무부하매연측정치
9           UNLOAD_NAM    무부하공기과잉률
10           UNLOAD_HC     무부하탄화수소
11           UNLOAD_CO    무부하일산화탄소
12       REPAIR_REG_NO    전문정비접수번호
13       REPAIR_ORG_NM     전문정비업소명
14   RE_SMO_CHK_REG_NO   정밀재검사접수번호
15         REPAIR_DATE       전문정비일
16              CAR_NM          미정
17            CAR_YEAR          미정
18        CAR_OWNER_NM          미정
19           OFFICE_NM          미정
20           REPAIR_NM          미정
21         CAR_FUEL_NM          미정
22      FIRST_REG_DATE          미정
23         REPAIR_COST          미정
24       WAR_REPAIR_YN          미정
25         RE_INS_DATE          미정
26            WAR_DATE          미정
27              WAR_KM          미정
28      REPAIR_COMMENT          미정
29  REPAIR_COMMENT_ETC          미정
30            REC_DATE          미정
31              REC_NM          미정
32        LAS_CHG_DATE          미정
33          LAS_CHG_NM          미정
34           ETC_CONT1          미정
35           ETC_CONT2          미정
36           ETC_CONT3          미정
37           ETC_CONT4          미정
38           ETC_CONT5          미정
39             SRC_TBL          미정
40             FILE_NM          미정
41            JOB_DATE          미정

In [301]:
sdf.columns.to_list()

['DRVNG_DSTNC',
 'VHRNO',
 'VIN',
 'LOD_COX_MEVLU',
 'LOD_HC_MEVLU',
 'LOD_NOX_MEVLU',
 'LOD_SMO_MEVLU',
 'LOD_TQ_MEVLU',
 'OVHUL_YMD',
 'SPCY_OVHUL_BIZPLC_NM',
 'OVHUL_RCPT_NO',
 'PRCINSP_RINSP_RCPT_NO',
 'NOLOD_COX_MEVLU',
 'NOLOD_HC_MEVLU',
 'NOLOD_AIR_EXCRT_MEVLU',
 'NOLOD_SMO_MEVLU']

In [302]:
slist = [
    'LOD_COX_MEVLU',
    'VIN',
    'VHRNO', # VHCL_MNG_NO
    'DRVNG_DSTNC',
    'LOD_HC_MEVLU',
    'LOD_NOX_MEVLU',
    'LOD_SMO_MEVLU',
    'LOD_TQ_MEVLU',
    'NOLOD_SMO_MEVLU', 
    'NOLOD_AIR_EXCRT_MEVLU',
    'NOLOD_HC_MEVLU',
    'NOLOD_COX_MEVLU',
    'OVHUL_RCPT_NO',
    'SPCY_OVHUL_BIZPLC_NM',
    'PRCINSP_RINSP_RCPT_NO',
    'OVHUL_YMD',

    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['부하일산화탄소측정치',
    '차대번호',
    '차량관리번호',
    '주행거리',
    '부하탄화수소측정치',
    '부하질소산화물측정치',
    '부하매연측정치',
    '부하토크측정치',
    '무부하매연측정치', 
    '무부하공기과잉률측정치',
    '무부하탄화수소측정치',
    '무부하일산화탄소측정치',
    '정비접수번호',
    '전문정비사업소명',
    '정밀재검사접수번호',
    '정비일자',]
    }

scol = pd.DataFrame(sdict)
scol

                       컬럼           내용
0           LOD_COX_MEVLU   부하일산화탄소측정치
1                     VIN         차대번호
2                   VHRNO       차량관리번호
3             DRVNG_DSTNC         주행거리
4            LOD_HC_MEVLU    부하탄화수소측정치
5           LOD_NOX_MEVLU   부하질소산화물측정치
6           LOD_SMO_MEVLU      부하매연측정치
7            LOD_TQ_MEVLU      부하토크측정치
8         NOLOD_SMO_MEVLU     무부하매연측정치
9   NOLOD_AIR_EXCRT_MEVLU  무부하공기과잉률측정치
10         NOLOD_HC_MEVLU   무부하탄화수소측정치
11        NOLOD_COX_MEVLU  무부하일산화탄소측정치
12          OVHUL_RCPT_NO       정비접수번호
13   SPCY_OVHUL_BIZPLC_NM     전문정비사업소명
14  PRCINSP_RINSP_RCPT_NO    정밀재검사접수번호
15              OVHUL_YMD         정비일자

### 데이터 info

In [303]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,LOAD_CO,부하일산화탄소측정치,53884,LOD_COX_MEVLU,부하일산화탄소측정치,53884.0,0.0,733,733.0
1,CAR_SER_NO,차대번호,51051,VIN,차대번호,51051.0,0.0,3566,3566.0
2,CAR_REG_NO,차량등록번호,54617,VHRNO,차량관리번호,54617.0,0.0,0,0.0
3,CAR_MILE,주행거리,54617,DRVNG_DSTNC,주행거리,54617.0,0.0,0,0.0
4,LOAD_HC,부하탄화수소측정치,53886,LOD_HC_MEVLU,부하탄화수소측정치,53886.0,0.0,731,731.0

### [출력]

In [304]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 24\. 전문정비상세(TB_ERR_RES_DET)

In [305]:
name = 'TB_ERR_RES_DET'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

24 8
(106818, 24) (106818, 8)

In [306]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS    24  106818
STD     8  106818

### 컬럼 확인

In [307]:
odf.columns.to_list()

['REPAIR_ORG_NM',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'REPAIR_DATE',
 'REPAIR_REG_NO',
 'RE_SMO_CHK_REG_NO',
 'REPAIR_PART_CD',
 'REPAIR_CONT_CD',
 'REPAIR_PART1_YN',
 'REPAIR_PART2_YN',
 'REPAIR_PART3_YN',
 'REPAIR_PART4_YN',
 'REC_DATE',
 'REC_NM',
 'LAS_CHG_DATE',
 'LAS_CHG_NM',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'ETC_CONT4',
 'ETC_CONT5',
 'SRC_TBL',
 'FILE_NM',
 'JOB_DATE']

In [308]:
olist = [
    'CAR_REG_NO',
    'CAR_SER_NO',
    'RE_SMO_CHK_REG_NO',
    'REPAIR_REG_NO',
    'REPAIR_DATE',
    'REPAIR_ORG_NM',
    'REPAIR_PART_CD',
    'REPAIR_CONT_CD',

    'REPAIR_PART1_YN',
    'REPAIR_PART2_YN',
    'REPAIR_PART3_YN',
    'REPAIR_PART4_YN',
    'REC_DATE',
    'REC_NM',
    'LAS_CHG_DATE',
    'LAS_CHG_NM',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'ETC_CONT4',
    'ETC_CONT5',
    'SRC_TBL',
    'FILE_NM',
    'JOB_DATE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차량번호',
    '차대번호',
    '정밀재검사접수번호',
    '전문정비접수번호',
    '전문정비일',
    '전문정비업소명',
    '정비부품코드',
    '정비내용코드',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

ocol = pd.DataFrame(odict)
ocol

                   컬럼         내용
0          CAR_REG_NO       차량번호
1          CAR_SER_NO       차대번호
2   RE_SMO_CHK_REG_NO  정밀재검사접수번호
3       REPAIR_REG_NO   전문정비접수번호
4         REPAIR_DATE      전문정비일
5       REPAIR_ORG_NM    전문정비업소명
6      REPAIR_PART_CD     정비부품코드
7      REPAIR_CONT_CD     정비내용코드
8     REPAIR_PART1_YN         미정
9     REPAIR_PART2_YN         미정
10    REPAIR_PART3_YN         미정
11    REPAIR_PART4_YN         미정
12           REC_DATE         미정
13             REC_NM         미정
14       LAS_CHG_DATE         미정
15         LAS_CHG_NM         미정
16          ETC_CONT1         미정
17          ETC_CONT2         미정
18          ETC_CONT3         미정
19          ETC_CONT4         미정
20          ETC_CONT5         미정
21            SRC_TBL         미정
22            FILE_NM         미정
23           JOB_DATE         미정

In [309]:
sdf.columns.to_list()

['VHRNO',
 'VIN',
 'OVHUL_CN',
 'OVHUL_YMD',
 'SPCY_OVHUL_BIZPLC_NM',
 'OVHUL_CMPNT_NM',
 'OVHUL_RCPT_NO',
 'PRCINSP_RINSP_RCPT_NO']

In [310]:
slist = [
    'VHRNO', # VHCL_MNG_NO
    'VIN',
    'PRCINSP_RINSP_RCPT_NO', 
    'OVHUL_RCPT_NO',
    'OVHUL_YMD',
    'SPCY_OVHUL_BIZPLC_NM',
    'OVHUL_CMPNT_NM',
    'OVHUL_CN',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차량관리번호',
    '차대번호',
    '정밀재검사접수번호', 
    '정비접수번호',
    '전문정비일',
    '전문정비사업소명',
    '정비부품명',
    '정비내용',]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼         내용
0                  VHRNO     차량관리번호
1                    VIN       차대번호
2  PRCINSP_RINSP_RCPT_NO  정밀재검사접수번호
3          OVHUL_RCPT_NO     정비접수번호
4              OVHUL_YMD      전문정비일
5   SPCY_OVHUL_BIZPLC_NM   전문정비사업소명
6         OVHUL_CMPNT_NM      정비부품명
7               OVHUL_CN       정비내용

### 데이터 info

In [311]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,CAR_REG_NO,차량번호,106818,VHRNO,차량관리번호,106818.0,0.0,0,0.0
1,CAR_SER_NO,차대번호,94670,VIN,차대번호,94670.0,0.0,12148,12148.0
2,RE_SMO_CHK_REG_NO,정밀재검사접수번호,0,PRCINSP_RINSP_RCPT_NO,정밀재검사접수번호,0.0,0.0,106818,106818.0
3,REPAIR_REG_NO,전문정비접수번호,106818,OVHUL_RCPT_NO,정비접수번호,106818.0,0.0,0,0.0
4,REPAIR_DATE,전문정비일,106818,OVHUL_YMD,전문정비일,106818.0,0.0,0,0.0

### [출력]

In [312]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 25\. [e]정기검사 검사정보(TB_JGT_HIS)
- ODS, STD 파일 없음

In [88]:
name = 'TB_JGT_HIS'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/ODS\\ODS_TB_JGT_HIS.csv'

In [ ]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수     행_수
ODS    24  106818
STD     8  106818

### 컬럼 확인

In [ ]:
odf.columns.to_list()

['REPAIR_ORG_NM',
 'CAR_REG_NO',
 'CAR_SER_NO',
 'REPAIR_DATE',
 'REPAIR_REG_NO',
 'RE_SMO_CHK_REG_NO',
 'REPAIR_PART_CD',
 'REPAIR_CONT_CD',
 'REPAIR_PART1_YN',
 'REPAIR_PART2_YN',
 'REPAIR_PART3_YN',
 'REPAIR_PART4_YN',
 'REC_DATE',
 'REC_NM',
 'LAS_CHG_DATE',
 'LAS_CHG_NM',
 'ETC_CONT1',
 'ETC_CONT2',
 'ETC_CONT3',
 'ETC_CONT4',
 'ETC_CONT5',
 'SRC_TBL',
 'FILE_NM',
 'JOB_DATE']

In [ ]:
olist = [
    'CAR_REG_NO',
    'CAR_SER_NO',
    'RE_SMO_CHK_REG_NO',
    'REPAIR_REG_NO',
    'REPAIR_DATE',
    'REPAIR_ORG_NM',
    'REPAIR_PART_CD',
    'REPAIR_CONT_CD',

    'REPAIR_PART1_YN',
    'REPAIR_PART2_YN',
    'REPAIR_PART3_YN',
    'REPAIR_PART4_YN',
    'REC_DATE',
    'REC_NM',
    'LAS_CHG_DATE',
    'LAS_CHG_NM',
    'ETC_CONT1',
    'ETC_CONT2',
    'ETC_CONT3',
    'ETC_CONT4',
    'ETC_CONT5',
    'SRC_TBL',
    'FILE_NM',
    'JOB_DATE', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['차량번호',
    '차대번호',
    '정밀재검사접수번호',
    '전문정비접수번호',
    '전문정비일',
    '전문정비업소명',
    '정비부품코드',
    '정비내용코드',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',]
    }

ocol = pd.DataFrame(odict)
ocol

                   컬럼         내용
0          CAR_REG_NO       차량번호
1          CAR_SER_NO       차대번호
2   RE_SMO_CHK_REG_NO  정밀재검사접수번호
3       REPAIR_REG_NO   전문정비접수번호
4         REPAIR_DATE      전문정비일
5       REPAIR_ORG_NM    전문정비업소명
6      REPAIR_PART_CD     정비부품코드
7      REPAIR_CONT_CD     정비내용코드
8     REPAIR_PART1_YN         미정
9     REPAIR_PART2_YN         미정
10    REPAIR_PART3_YN         미정
11    REPAIR_PART4_YN         미정
12           REC_DATE         미정
13             REC_NM         미정
14       LAS_CHG_DATE         미정
15         LAS_CHG_NM         미정
16          ETC_CONT1         미정
17          ETC_CONT2         미정
18          ETC_CONT3         미정
19          ETC_CONT4         미정
20          ETC_CONT5         미정
21            SRC_TBL         미정
22            FILE_NM         미정
23           JOB_DATE         미정

In [ ]:
sdf.columns.to_list()

['VHRNO',
 'VIN',
 'OVHUL_CN',
 'OVHUL_YMD',
 'SPCY_OVHUL_BIZPLC_NM',
 'OVHUL_CMPNT_NM',
 'OVHUL_RCPT_NO',
 'PRCINSP_RINSP_RCPT_NO']

In [ ]:
slist = [
    'VHRNO', # VHCL_MNG_NO
    'VIN',
    'PRCINSP_RINSP_RCPT_NO', 
    'OVHUL_RCPT_NO',
    'OVHUL_YMD',
    'SPCY_OVHUL_BIZPLC_NM',
    'OVHUL_CMPNT_NM',
    'OVHUL_CN',
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['차량관리번호',
    '차대번호',
    '정밀재검사접수번호', 
    '정비접수번호',
    '전문정비일',
    '전문정비사업소명',
    '정비부품명',
    '정비내용',]
    }

scol = pd.DataFrame(sdict)
scol

                      컬럼         내용
0                  VHRNO     차량관리번호
1                    VIN       차대번호
2  PRCINSP_RINSP_RCPT_NO  정밀재검사접수번호
3          OVHUL_RCPT_NO     정비접수번호
4              OVHUL_YMD      전문정비일
5   SPCY_OVHUL_BIZPLC_NM   전문정비사업소명
6         OVHUL_CMPNT_NM      정비부품명
7               OVHUL_CN       정비내용

### 데이터 info

In [ ]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount

               oindex  ocount                 sindex    scount   차이
0          CAR_REG_NO  106818                  VHRNO  106818.0  0.0
1          CAR_SER_NO   94670                    VIN   94670.0  0.0
2   RE_SMO_CHK_REG_NO       0  PRCINSP_RINSP_RCPT_NO       0.0  0.0
3       REPAIR_REG_NO  106818          OVHUL_RCPT_NO  106818.0  0.0
4         REPAIR_DATE  106818              OVHUL_YMD  106818.0  0.0
5       REPAIR_ORG_NM  106818   SPCY_OVHUL_BIZPLC_NM  106818.0  0.0
6      REPAIR_PART_CD  106817         OVHUL_CMPNT_NM  106817.0  0.0
7      REPAIR_CONT_CD  106817               OVHUL_CN  106817.0  0.0
8     REPAIR_PART1_YN  106818                    NaN       NaN  NaN
9     REPAIR_PART2_YN  106818                    NaN       NaN  NaN
10    REPAIR_PART3_YN  106818                    NaN       NaN  NaN
11    REPAIR_PART4_YN  106818                    NaN       NaN  NaN
12           REC_DATE       0                    NaN       NaN  NaN
13             REC_NM       0                    NaN       NaN  NaN
14       LAS_CHG_DATE       0                    NaN       NaN  NaN
15         LAS_CHG_NM       0                    NaN       NaN  NaN
16          ETC_CONT1       0                    NaN       NaN  NaN
17          ETC_CONT2       0                    NaN       NaN  NaN
18          ETC_CONT3       0                    NaN       NaN  NaN
19          ETC_CONT4       0                    NaN       NaN  NaN
20          ETC_CONT5       0                    NaN       NaN  NaN
21            SRC_TBL  106818                    NaN       NaN  NaN
22            FILE_NM   15622                    NaN       NaN  NaN
23           JOB_DATE   15860                    NaN       NaN  NaN

### [출력]

In [ ]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 26\. 정기검사 검사소정보(TB_JGT_VIO)

In [313]:
name = 'TB_JGT_VIO'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

4 4
(1961, 4) (1961, 4)

In [314]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS     4  1961
STD     4  1961

### 컬럼 확인

In [315]:
odf.columns.to_list()

['VIO_CD', 'VIO_NM', 'VIO_TYPE', 'SIDO_NM']

In [316]:
olist = [
    'SIDO_NM', 
    'VIO_TYPE', 
    'VIO_CD', 
    'VIO_NM', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['시도명', 
    '검사소구분', 
    '검사소코드', 
    '검사소명', ]
    }

ocol = pd.DataFrame(odict)
ocol

         컬럼     내용
0   SIDO_NM    시도명
1  VIO_TYPE  검사소구분
2    VIO_CD  검사소코드
3    VIO_NM   검사소명

In [317]:
sdf.columns.to_list()

['CTPV_NM', 'FDRM_INSP_INSPOF_CD', 'INSPOF_SE_CD', 'INSPOF_NM']

In [318]:
slist = [
    'CTPV_NM', 
    'INSPOF_SE_CD', 
    'FDRM_INSP_INSPOF_CD', 
    'INSPOF_NM', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['시도명', 
    '검사소구분코드', 
    '정기검사검사소코드', 
    '검사소명', ]
    }

scol = pd.DataFrame(sdict)
scol

                    컬럼         내용
0              CTPV_NM        시도명
1         INSPOF_SE_CD    검사소구분코드
2  FDRM_INSP_INSPOF_CD  정기검사검사소코드
3            INSPOF_NM       검사소명

### 데이터 info

In [319]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,SIDO_NM,시도명,1961,CTPV_NM,시도명,1961,0,0,0
1,VIO_TYPE,검사소구분,1961,INSPOF_SE_CD,검사소구분코드,1961,0,0,0
2,VIO_CD,검사소코드,1961,FDRM_INSP_INSPOF_CD,정기검사검사소코드,1961,0,0,0
3,VIO_NM,검사소명,1961,INSPOF_NM,검사소명,1961,0,0,0

### [출력]

In [320]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 27\. 자동차 검사소정보(TB_MECAR_VIO)

In [321]:
name = 'TB_MECAR_VIO'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

28 4
(1045, 28) (1045, 4)

In [322]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    28  1045
STD     4  1045

### 컬럼 확인

In [323]:
odf.columns.to_list()

['VIO_CD',
 'VIO_NM',
 'VIO_TYPE',
 'RECV_DATE',
 'CONF_DATE',
 'BIZ_YN',
 'J_YN',
 'G_YN',
 'S_YN',
 'H_YN',
 'SIDO_CD',
 'SIGUNGU_CD',
 'SIDO_NM',
 'SIGUNGU_NM',
 'TEL_NO',
 'POST_NO',
 'ADDR1',
 'ADDR2',
 'X_COORD',
 'Y_COORD',
 'ORG_ID',
 'DO_VIO_CD',
 'KECO_S_YN',
 'REC_DATE',
 'REC_NM',
 'CHG_DATE',
 'CHG_NM',
 'T_YN']

In [324]:
olist = [
    'VIO_NM',
    'VIO_CD',
    'SIDO_NM',
    'VIO_TYPE',

    'RECV_DATE',
    'CONF_DATE',
    'BIZ_YN',
    'J_YN',
    'G_YN',
    'S_YN',
    'H_YN',
    'SIDO_CD',
    'SIGUNGU_CD',
    'SIGUNGU_NM',
    'TEL_NO',
    'POST_NO',
    'ADDR1',
    'ADDR2',
    'X_COORD',
    'Y_COORD',
    'ORG_ID',
    'DO_VIO_CD',
    'KECO_S_YN',
    'REC_DATE',
    'REC_NM',
    'CHG_DATE',
    'CHG_NM',
    'T_YN', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['검사소명',
    '검사소코드',
    '시도명',
    '검사소구분',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

            컬럼     내용
0       VIO_NM   검사소명
1       VIO_CD  검사소코드
2      SIDO_NM    시도명
3     VIO_TYPE  검사소구분
4    RECV_DATE     미정
5    CONF_DATE     미정
6       BIZ_YN     미정
7         J_YN     미정
8         G_YN     미정
9         S_YN     미정
10        H_YN     미정
11     SIDO_CD     미정
12  SIGUNGU_CD     미정
13  SIGUNGU_NM     미정
14      TEL_NO     미정
15     POST_NO     미정
16       ADDR1     미정
17       ADDR2     미정
18     X_COORD     미정
19     Y_COORD     미정
20      ORG_ID     미정
21   DO_VIO_CD     미정
22   KECO_S_YN     미정
23    REC_DATE     미정
24      REC_NM     미정
25    CHG_DATE     미정
26      CHG_NM     미정
27        T_YN     미정

In [325]:
sdf.columns.to_list()

['STDG_CTPV_NM', 'MECAR_INSPOF_CD', 'INSPOF_NM', 'INSPOF_SE_CD']

In [326]:
slist = [
    'INSPOF_NM', 
    'MECAR_INSPOF_CD', 
    'STDG_CTPV_NM', 
    'INSPOF_SE_CD', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['검사소명', 
    'MECAR검사소코드', 
    '법정동시도명', 
    '검사소구분코드', ]
    }

scol = pd.DataFrame(sdict)
scol

                컬럼          내용
0        INSPOF_NM        검사소명
1  MECAR_INSPOF_CD  MECAR검사소코드
2     STDG_CTPV_NM      법정동시도명
3     INSPOF_SE_CD     검사소구분코드

### 데이터 info

In [327]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount['ocol'] = ocol['내용']
ocount = ocount[['oindex', 'ocol', 'ocount']]

sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount['scol'] = scol['내용']
scount = scount[['sindex', 'scol', 'scount']]

oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount['ODS_mcount'] = odf2.shape[0] - oscount['ocount']
oscount['STD_mcount'] = sdf2.shape[0] - oscount['scount']
oscount.head()

,oindex,ocol,ocount,sindex,scol,scount,차이,ODS_mcount,STD_mcount
0,VIO_NM,검사소명,1045,INSPOF_NM,검사소명,1045.0,0.0,0,0.0
1,VIO_CD,검사소코드,1045,MECAR_INSPOF_CD,MECAR검사소코드,1045.0,0.0,0,0.0
2,SIDO_NM,시도명,1045,STDG_CTPV_NM,법정동시도명,1045.0,0.0,0,0.0
3,VIO_TYPE,검사소구분,1045,INSPOF_SE_CD,검사소구분코드,1045.0,0.0,0,0.0
4,RECV_DATE,미정,134,NaN,NaN,NaN,NaN,911,NaN

### [출력]

In [328]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 28\. RSD 수시점검(TB_RSD_FINAL)
- ODS 없음

In [105]:
name = 'TB_RSD_FINAL'
ods_file_name = f'ODS_{name}'
std_file_name = f'STD_{name}'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/ODS\\ODS_TB_RSD_FINAL.csv'

In [ ]:
t_info = {'컬럼_수':[odf.shape[1], sdf.shape[1]], '행_수':[odf.shape[0], sdf.shape[0]]}
t_df = pd.DataFrame(t_info, index=['ODS', 'STD'])
t_df

     컬럼_수   행_수
ODS    28  1045
STD     4  1045

### 컬럼 확인

In [ ]:
odf.columns.to_list()

['VIO_CD',
 'VIO_NM',
 'VIO_TYPE',
 'RECV_DATE',
 'CONF_DATE',
 'BIZ_YN',
 'J_YN',
 'G_YN',
 'S_YN',
 'H_YN',
 'SIDO_CD',
 'SIGUNGU_CD',
 'SIDO_NM',
 'SIGUNGU_NM',
 'TEL_NO',
 'POST_NO',
 'ADDR1',
 'ADDR2',
 'X_COORD',
 'Y_COORD',
 'ORG_ID',
 'DO_VIO_CD',
 'KECO_S_YN',
 'REC_DATE',
 'REC_NM',
 'CHG_DATE',
 'CHG_NM',
 'T_YN']

In [ ]:
olist = [
    'VIO_NM',
    'VIO_CD',
    'SIDO_NM',
    'VIO_TYPE',

    'RECV_DATE',
    'CONF_DATE',
    'BIZ_YN',
    'J_YN',
    'G_YN',
    'S_YN',
    'H_YN',
    'SIDO_CD',
    'SIGUNGU_CD',
    'SIGUNGU_NM',
    'TEL_NO',
    'POST_NO',
    'ADDR1',
    'ADDR2',
    'X_COORD',
    'Y_COORD',
    'ORG_ID',
    'DO_VIO_CD',
    'KECO_S_YN',
    'REC_DATE',
    'REC_NM',
    'CHG_DATE',
    'CHG_NM',
    'T_YN', 
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['검사소명',
    '검사소코드',
    '시도명',
    '검사소구분',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정', ]
    }

ocol = pd.DataFrame(odict)
ocol

            컬럼     내용
0       VIO_NM   검사소명
1       VIO_CD  검사소코드
2      SIDO_NM    시도명
3     VIO_TYPE  검사소구분
4    RECV_DATE     미정
5    CONF_DATE     미정
6       BIZ_YN     미정
7         J_YN     미정
8         G_YN     미정
9         S_YN     미정
10        H_YN     미정
11     SIDO_CD     미정
12  SIGUNGU_CD     미정
13  SIGUNGU_NM     미정
14      TEL_NO     미정
15     POST_NO     미정
16       ADDR1     미정
17       ADDR2     미정
18     X_COORD     미정
19     Y_COORD     미정
20      ORG_ID     미정
21   DO_VIO_CD     미정
22   KECO_S_YN     미정
23    REC_DATE     미정
24      REC_NM     미정
25    CHG_DATE     미정
26      CHG_NM     미정
27        T_YN     미정

In [ ]:
sdf.columns.to_list()

['STDG_CTPV_NM', 'MECAR_INSPOF_CD', 'INSPOF_NM', 'INSPOF_SE_CD']

In [ ]:
slist = [
    'INSPOF_NM', 
    'MECAR_INSPOF_CD', 
    'STDG_CTPV_NM', 
    'INSPOF_SE_CD', 
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['검사소명', 
    'MECAR검사소코드', 
    '법정동시도명', 
    '검사소구분코드', ]
    }

scol = pd.DataFrame(sdict)
scol

                컬럼          내용
0        INSPOF_NM        검사소명
1  MECAR_INSPOF_CD  MECAR검사소코드
2     STDG_CTPV_NM      법정동시도명
3     INSPOF_SE_CD     검사소구분코드

### 데이터 info

In [ ]:
odf2 = odf[olist]
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
sdf2 = sdf[slist]
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
oscount = pd.concat([ocount, scount], axis=1)
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount

        oindex  ocount           sindex  scount   차이
0       VIO_NM    1045        INSPOF_NM  1045.0  0.0
1       VIO_CD    1045  MECAR_INSPOF_CD  1045.0  0.0
2      SIDO_NM    1045     STDG_CTPV_NM  1045.0  0.0
3     VIO_TYPE    1045     INSPOF_SE_CD  1045.0  0.0
4    RECV_DATE     134              NaN     NaN  NaN
5    CONF_DATE     134              NaN     NaN  NaN
6       BIZ_YN    1045              NaN     NaN  NaN
7         J_YN    1044              NaN     NaN  NaN
8         G_YN     219              NaN     NaN  NaN
9         S_YN     353              NaN     NaN  NaN
10        H_YN     387              NaN     NaN  NaN
11     SIDO_CD    1045              NaN     NaN  NaN
12  SIGUNGU_CD    1043              NaN     NaN  NaN
13  SIGUNGU_NM    1044              NaN     NaN  NaN
14      TEL_NO     435              NaN     NaN  NaN
15     POST_NO     428              NaN     NaN  NaN
16       ADDR1    1045              NaN     NaN  NaN
17       ADDR2     217              NaN     NaN  NaN
18     X_COORD    1045              NaN     NaN  NaN
19     Y_COORD    1045              NaN     NaN  NaN
20      ORG_ID     317              NaN     NaN  NaN
21   DO_VIO_CD      37              NaN     NaN  NaN
22   KECO_S_YN    1022              NaN     NaN  NaN
23    REC_DATE    1045              NaN     NaN  NaN
24      REC_NM    1045              NaN     NaN  NaN
25    CHG_DATE    1045              NaN     NaN  NaN
26      CHG_NM    1045              NaN     NaN  NaN
27        T_YN      24              NaN     NaN  NaN

### [출력]

In [ ]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
t_df.to_excel(texcel, sheet_name='shape', index=True)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

# 코드 마지막