# Library

In [1]:
import pandas as pd
import os
import numpy as np
from tqdm import tqdm

## [load] file

In [4]:
# file path
# ODS : D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/ODS
# STD : D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/STD

In [5]:
ods_path = 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/ODS'
std_path = 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/STD'

## 1\. [e]자동차 등록정보
- STD_CEG_CAR_MIG_21.csv 파일 로드 오류

### 컬럼명 및 컬럼별 데이터 수 비교

In [49]:
def fuc(num):
   # 파일명, 파일경로 설정
   ods_file_name = f'ODS_CEG_CAR_MIG_{num}'
   std_file_name = f'STD_CEG_CAR_MIG_{num}'
   opath = os.path.join(ods_path, ods_file_name + '.csv')
   spath = os.path.join(std_path, std_file_name + '.csv')
   odf = pd.read_csv(opath)
   sdf = pd.read_csv(spath)

   # 분석
   olist = [
   'ACQS_AMT', 
   'ACQS_DE', 
   'BSPL_LEDO_CD', 
   'CRTN_DT', 
   'EMIS_CRTCNO', 
   'EMIS_GRD', 
   'EMIS_INSP_EFCT_DE', 
   'FST_MBERNO', 
   'FST_REG_DE', 
   'LEM_KND', 
   'LEM_STRCHG_YN', 
   'LEM_YN', 
   'NOW_MBERNO', 
   'OWNR_SE', 
   'PURPS', 
   'SRCMNNO', 
   'UPDT_DT', 
   'VHCL_ERSR_YN', 
   'VHCL_MNFCT_DE', 
   'VHCL_YRIDNW', 
   'VHCTY', 
   'VHMNO', 
   'VHRNO_NUM_INFO', 
   'VIN', 'VHRNO', 
   'NOW_OWNR_NM', 
   'BSPL_ADRS', 
   'OWNR_ADRS', 
   'BSPL_ZIP', 
   'FST_OWNR_NM', 
   'RMK', 
   'USER_ID'
   ]
   slist = [
   'ACQS_AMT', 
   'ACQS_YMD', 
   'BSPL_STDG_CD', 
   'VHCL_REG_DT', 
   'EXHST_GAS_CERT_NO', 
   'EXHST_GAS_GRD_CD', 
   'EXTGAS_INSP_VLD_YMD', 
   'FRST_MBR_NO', 
   'FRST_REG_YMD', 
   'LEM_KND_CD', 
   'STRCT_CHG_YN', 
   'LEM_YN', 
   'NOW_MBR_NO', 
   'VHCL_OWNR_CL_CD', 
   'PURPS_CD2', 
   'MANP_MNG_NO', 
   'MDFCN_DT', 
   'VHCL_ERSR_YN', 
   'VHCL_FBCTN_YMD', 
   'YRIDNW', 
   'VHCTY_CD', 
   'VHCL_MNG_NO', 
   'VHRNO_FGRE_INFO', 
   'VIN', 
   'VHRNO'
   ]
   odict = {
   '컬럼':olist,
   '내용':['취득금액', '취득일자', '본거지 법정동 코드', '생성 일시', '배출가스 인증번호', '배출가스 등급', '배출가스검사유효일자', '최초 회원번호', '최초 등록 일자', '저공해조치 종류', '저공해조치 구조변경 YN', '저공해조치 YN(미사용)', '현재 회원번호', '소유자 구분', '용도', '제원관리번호', '수정 일시', '차량 말소 YN', '차량 제작 일자', '차량 연식', '차종', '차량관리번호', '차량등록번호 숫자 정보', '차대번호', '미정', '미정', '미정', '미정', '미정', '미정', '미정', '미정']
   }
   ocol = pd.DataFrame(odict)

   sdict = {
      '컬럼':slist,
      '내용':['취득금액', '취득일자', '본거지법정동코드', '차량등록일시', '배출가스인증번호', '배출가스등급', '배출가스검사유효일자', '최초회원번호', '최초등록일자', '저공해조치종류코드', '구조변경여부', '저공해조치여부', '현재회원번호', '차량소유자분류코드', '용도코드2', '제원관리번호', '수정일시', '차량말소여부', '차량제작일자', '연식', '차종코드', '차량관리번호', np.nan, '차대번호', '미정']
      }
   scol = pd.DataFrame(sdict)

   odf2 = odf[olist]
   sdf2 = sdf[slist]

   ocount = odf2.count().reset_index()
   ocount.columns = ['oindex', 'ocount']

   scount = sdf2.count().reset_index()
   scount.columns = ['sindex', 'scount']
   oscount = pd.concat([ocount, scount], axis=1)
   oscount['차이'] = oscount['ocount'] - oscount['scount']

   # 분석 결과 파일로 출력
   texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
   ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
   scol.to_excel(texcel, sheet_name='STD_col', index=False)
   oscount.to_excel(texcel, sheet_name='count', index=False)
   # odf2.count().reset_index().to_excel(texcel, sheet_name='ODS_count',index=False)
   # sdf2.count().reset_index().to_excel(texcel, sheet_name='STD_count',index=False)
   texcel.save()
   
   print(f'======== {ods_file_name}_vs_{std_file_name} 비교 ========')
   print(odf2.shape, sdf2.shape)
   print(f'[정제]{ods_file_name}_vs_{std_file_name}.xlsx 출력 완료.')
   
   return oscount

In [88]:
tocount = np.array([0.0]*32)
tscount = np.array([0.0]*32)

for n in tqdm(range(1, 31)):
    try:
        temp = fuc(n)
        tocount += temp['ocount'].to_numpy()
        tscount += temp['scount'].to_numpy()
    except:
        pass

  0%|          | 0/30 [00:00<?, ?it/s]C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:7: DtypeWarning: Columns (13,15,26) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
  3%|▎         | 1/30 [00:20<09:42, 20.09s/it]

======== ODS_CEG_CAR_MIG_1_vs_STD_CEG_CAR_MIG_1 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_1_vs_STD_CEG_CAR_MIG_1.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:7: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
  7%|▋         | 2/30 [00:40<09:20, 20.01s/it]

======== ODS_CEG_CAR_MIG_2_vs_STD_CEG_CAR_MIG_2 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_2_vs_STD_CEG_CAR_MIG_2.xlsx 출력 완료.

 10%|█         | 3/30 [01:00<09:00, 20.01s/it]

======== ODS_CEG_CAR_MIG_3_vs_STD_CEG_CAR_MIG_3 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_3_vs_STD_CEG_CAR_MIG_3.xlsx 출력 완료.

 13%|█▎        | 4/30 [01:20<08:44, 20.18s/it]

======== ODS_CEG_CAR_MIG_4_vs_STD_CEG_CAR_MIG_4 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_4_vs_STD_CEG_CAR_MIG_4.xlsx 출력 완료.

 17%|█▋        | 5/30 [01:41<08:30, 20.41s/it]

======== ODS_CEG_CAR_MIG_5_vs_STD_CEG_CAR_MIG_5 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_5_vs_STD_CEG_CAR_MIG_5.xlsx 출력 완료.

 20%|██        | 6/30 [02:02<08:13, 20.57s/it]

======== ODS_CEG_CAR_MIG_6_vs_STD_CEG_CAR_MIG_6 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_6_vs_STD_CEG_CAR_MIG_6.xlsx 출력 완료.

 23%|██▎       | 7/30 [02:22<07:52, 20.56s/it]

======== ODS_CEG_CAR_MIG_7_vs_STD_CEG_CAR_MIG_7 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_7_vs_STD_CEG_CAR_MIG_7.xlsx 출력 완료.

 27%|██▋       | 8/30 [02:43<07:31, 20.52s/it]

======== ODS_CEG_CAR_MIG_8_vs_STD_CEG_CAR_MIG_8 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_8_vs_STD_CEG_CAR_MIG_8.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:7: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
 30%|███       | 9/30 [03:03<07:08, 20.41s/it]

======== ODS_CEG_CAR_MIG_9_vs_STD_CEG_CAR_MIG_9 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_9_vs_STD_CEG_CAR_MIG_9.xlsx 출력 완료.

 33%|███▎      | 10/30 [03:23<06:46, 20.32s/it]

======== ODS_CEG_CAR_MIG_10_vs_STD_CEG_CAR_MIG_10 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_10_vs_STD_CEG_CAR_MIG_10.xlsx 출력 완료.

 37%|███▋      | 11/30 [03:43<06:25, 20.27s/it]

======== ODS_CEG_CAR_MIG_11_vs_STD_CEG_CAR_MIG_11 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_11_vs_STD_CEG_CAR_MIG_11.xlsx 출력 완료.

 40%|████      | 12/30 [04:03<06:03, 20.22s/it]

======== ODS_CEG_CAR_MIG_12_vs_STD_CEG_CAR_MIG_12 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_12_vs_STD_CEG_CAR_MIG_12.xlsx 출력 완료.

 43%|████▎     | 13/30 [04:23<05:43, 20.21s/it]

======== ODS_CEG_CAR_MIG_13_vs_STD_CEG_CAR_MIG_13 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_13_vs_STD_CEG_CAR_MIG_13.xlsx 출력 완료.

 47%|████▋     | 14/30 [04:44<05:24, 20.26s/it]

======== ODS_CEG_CAR_MIG_14_vs_STD_CEG_CAR_MIG_14 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_14_vs_STD_CEG_CAR_MIG_14.xlsx 출력 완료.

 50%|█████     | 15/30 [05:04<05:03, 20.25s/it]

======== ODS_CEG_CAR_MIG_15_vs_STD_CEG_CAR_MIG_15 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_15_vs_STD_CEG_CAR_MIG_15.xlsx 출력 완료.

 53%|█████▎    | 16/30 [05:24<04:43, 20.22s/it]

======== ODS_CEG_CAR_MIG_16_vs_STD_CEG_CAR_MIG_16 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_16_vs_STD_CEG_CAR_MIG_16.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:7: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 57%|█████▋    | 17/30 [05:44<04:22, 20.22s/it]

======== ODS_CEG_CAR_MIG_17_vs_STD_CEG_CAR_MIG_17 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_17_vs_STD_CEG_CAR_MIG_17.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 60%|██████    | 18/30 [06:05<04:02, 20.20s/it]

======== ODS_CEG_CAR_MIG_18_vs_STD_CEG_CAR_MIG_18 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_18_vs_STD_CEG_CAR_MIG_18.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 63%|██████▎   | 19/30 [06:25<03:42, 20.22s/it]

======== ODS_CEG_CAR_MIG_19_vs_STD_CEG_CAR_MIG_19 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_19_vs_STD_CEG_CAR_MIG_19.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 67%|██████▋   | 20/30 [06:45<03:22, 20.27s/it]

======== ODS_CEG_CAR_MIG_20_vs_STD_CEG_CAR_MIG_20 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_20_vs_STD_CEG_CAR_MIG_20.xlsx 출력 완료.

 70%|███████   | 21/30 [06:56<02:35, 17.32s/it]C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 73%|███████▎  | 22/30 [07:16<02:26, 18.28s/it]

======== ODS_CEG_CAR_MIG_22_vs_STD_CEG_CAR_MIG_22 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_22_vs_STD_CEG_CAR_MIG_22.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 77%|███████▋  | 23/30 [07:37<02:13, 19.06s/it]

======== ODS_CEG_CAR_MIG_23_vs_STD_CEG_CAR_MIG_23 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_23_vs_STD_CEG_CAR_MIG_23.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 80%|████████  | 24/30 [07:58<01:57, 19.56s/it]

======== ODS_CEG_CAR_MIG_24_vs_STD_CEG_CAR_MIG_24 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_24_vs_STD_CEG_CAR_MIG_24.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 83%|████████▎ | 25/30 [08:19<01:39, 19.97s/it]

======== ODS_CEG_CAR_MIG_25_vs_STD_CEG_CAR_MIG_25 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_25_vs_STD_CEG_CAR_MIG_25.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 87%|████████▋ | 26/30 [08:39<01:20, 20.17s/it]

======== ODS_CEG_CAR_MIG_26_vs_STD_CEG_CAR_MIG_26 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_26_vs_STD_CEG_CAR_MIG_26.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 90%|█████████ | 27/30 [09:00<01:00, 20.31s/it]

======== ODS_CEG_CAR_MIG_27_vs_STD_CEG_CAR_MIG_27 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_27_vs_STD_CEG_CAR_MIG_27.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 93%|█████████▎| 28/30 [09:20<00:40, 20.36s/it]

======== ODS_CEG_CAR_MIG_28_vs_STD_CEG_CAR_MIG_28 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_28_vs_STD_CEG_CAR_MIG_28.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (1,9,15,18) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 97%|█████████▋| 29/30 [09:41<00:20, 20.43s/it]

======== ODS_CEG_CAR_MIG_29_vs_STD_CEG_CAR_MIG_29 비교 ========
(1000000, 32) (1000000, 25)
[정제]ODS_CEG_CAR_MIG_29_vs_STD_CEG_CAR_MIG_29.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\3225461045.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
100%|██████████| 30/30 [09:51<00:00, 19.71s/it]

======== ODS_CEG_CAR_MIG_30_vs_STD_CEG_CAR_MIG_30 비교 ========
(534047, 32) (415224, 25)
[정제]ODS_CEG_CAR_MIG_30_vs_STD_CEG_CAR_MIG_30.xlsx 출력 완료.

In [45]:
olist = [
    'ACQS_AMT', 
    'ACQS_DE', 
    'BSPL_LEDO_CD', 
    'CRTN_DT', 
    'EMIS_CRTCNO', 
    'EMIS_GRD', 
    'EMIS_INSP_EFCT_DE', 
    'FST_MBERNO', 
    'FST_REG_DE', 
    'LEM_KND', 
    'LEM_STRCHG_YN', 
    'LEM_YN', 
    'NOW_MBERNO', 
    'OWNR_SE', 
    'PURPS', 
    'SRCMNNO', 
    'UPDT_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_MNFCT_DE', 
    'VHCL_YRIDNW', 
    'VHCTY', 
    'VHMNO', 
    'VHRNO_NUM_INFO', 
    'VIN', 'VHRNO', 
    'NOW_OWNR_NM', 
    'BSPL_ADRS', 
    'OWNR_ADRS', 
    'BSPL_ZIP', 
    'FST_OWNR_NM', 
    'RMK', 
    'USER_ID'
    ]
odict = {
    '컬럼':olist,
    '내용':['취득금액', '취득일자', '본거지 법정동 코드', '생성 일시', '배출가스 인증번호', '배출가스 등급', '배출가스검사유효일자', '최초 회원번호', '최초 등록 일자', '저공해조치 종류', '저공해조치 구조변경 YN', '저공해조치 YN(미사용)', '현재 회원번호', '소유자 구분', '용도', '제원관리번호', '수정 일시', '차량 말소 YN', '차량 제작 일자', '차량 연식', '차종', '차량관리번호', '차량등록번호 숫자 정보', '차대번호', '미정', '미정', '미정', '미정', '미정', '미정', '미정', '미정']
    }
ocol = pd.DataFrame(odict)
ocol

                   컬럼             내용
0            ACQS_AMT           취득금액
1             ACQS_DE           취득일자
2        BSPL_LEDO_CD     본거지 법정동 코드
3             CRTN_DT          생성 일시
4         EMIS_CRTCNO      배출가스 인증번호
5            EMIS_GRD        배출가스 등급
6   EMIS_INSP_EFCT_DE     배출가스검사유효일자
7          FST_MBERNO        최초 회원번호
8          FST_REG_DE       최초 등록 일자
9             LEM_KND       저공해조치 종류
10      LEM_STRCHG_YN  저공해조치 구조변경 YN
11             LEM_YN  저공해조치 YN(미사용)
12         NOW_MBERNO        현재 회원번호
13            OWNR_SE         소유자 구분
14              PURPS             용도
15            SRCMNNO         제원관리번호
16            UPDT_DT          수정 일시
17       VHCL_ERSR_YN       차량 말소 YN
18      VHCL_MNFCT_DE       차량 제작 일자
19        VHCL_YRIDNW          차량 연식
20              VHCTY             차종
21              VHMNO         차량관리번호
22     VHRNO_NUM_INFO   차량등록번호 숫자 정보
23                VIN           차대번호
24              VHRNO             미정
25        NOW_OWNR_NM             미정
26          BSPL_ADRS             미정
27          OWNR_ADRS             미정
28           BSPL_ZIP             미정
29        FST_OWNR_NM             미정
30                RMK             미정
31            USER_ID             미정

In [46]:
slist = [
    'ACQS_AMT', 
    'ACQS_YMD', 
    'BSPL_STDG_CD', 
    'VHCL_REG_DT', 
    'EXHST_GAS_CERT_NO', 
    'EXHST_GAS_GRD_CD', 
    'EXTGAS_INSP_VLD_YMD', 
    'FRST_MBR_NO', 
    'FRST_REG_YMD', 
    'LEM_KND_CD', 
    'STRCT_CHG_YN', 
    'LEM_YN', 
    'NOW_MBR_NO', 
    'VHCL_OWNR_CL_CD', 
    'PURPS_CD2', 
    'MANP_MNG_NO', 
    'MDFCN_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_FBCTN_YMD', 
    'YRIDNW', 
    'VHCTY_CD', 
    'VHCL_MNG_NO', 
    'VHRNO_FGRE_INFO', 
    'VIN', 
    'VHRNO'
    ]
sdict = {
       '컬럼':slist,
       '내용':['취득금액', '취득일자', '본거지법정동코드', '차량등록일시', '배출가스인증번호', '배출가스등급', '배출가스검사유효일자', '최초회원번호', '최초등록일자', '저공해조치종류코드', '구조변경여부', '저공해조치여부', '현재회원번호', '차량소유자분류코드', '용도코드2', '제원관리번호', '수정일시', '차량말소여부', '차량제작일자', '연식', '차종코드', '차량관리번호', np.nan, '차대번호', '미정']
       }
scol = pd.DataFrame(sdict)
scol

                     컬럼          내용
0              ACQS_AMT        취득금액
1              ACQS_YMD        취득일자
2          BSPL_STDG_CD    본거지법정동코드
3           VHCL_REG_DT      차량등록일시
4     EXHST_GAS_CERT_NO    배출가스인증번호
5      EXHST_GAS_GRD_CD      배출가스등급
6   EXTGAS_INSP_VLD_YMD  배출가스검사유효일자
7           FRST_MBR_NO      최초회원번호
8          FRST_REG_YMD      최초등록일자
9            LEM_KND_CD   저공해조치종류코드
10         STRCT_CHG_YN      구조변경여부
11               LEM_YN     저공해조치여부
12           NOW_MBR_NO      현재회원번호
13      VHCL_OWNR_CL_CD   차량소유자분류코드
14            PURPS_CD2       용도코드2
15          MANP_MNG_NO      제원관리번호
16             MDFCN_DT        수정일시
17         VHCL_ERSR_YN      차량말소여부
18       VHCL_FBCTN_YMD      차량제작일자
19               YRIDNW          연식
20             VHCTY_CD        차종코드
21          VHCL_MNG_NO      차량관리번호
22      VHRNO_FGRE_INFO         NaN
23                  VIN        차대번호
24                VHRNO          미정

In [48]:
total_count = pd.concat([ocol, scol], axis=1)
total_count.columns = ['ODS_col', 'ODS_count', 'STD_col', 'STD_count']
total_count

              ODS_col      ODS_count              STD_col   STD_count
0            ACQS_AMT           취득금액             ACQS_AMT        취득금액
1             ACQS_DE           취득일자             ACQS_YMD        취득일자
2        BSPL_LEDO_CD     본거지 법정동 코드         BSPL_STDG_CD    본거지법정동코드
3             CRTN_DT          생성 일시          VHCL_REG_DT      차량등록일시
4         EMIS_CRTCNO      배출가스 인증번호    EXHST_GAS_CERT_NO    배출가스인증번호
5            EMIS_GRD        배출가스 등급     EXHST_GAS_GRD_CD      배출가스등급
6   EMIS_INSP_EFCT_DE     배출가스검사유효일자  EXTGAS_INSP_VLD_YMD  배출가스검사유효일자
7          FST_MBERNO        최초 회원번호          FRST_MBR_NO      최초회원번호
8          FST_REG_DE       최초 등록 일자         FRST_REG_YMD      최초등록일자
9             LEM_KND       저공해조치 종류           LEM_KND_CD   저공해조치종류코드
10      LEM_STRCHG_YN  저공해조치 구조변경 YN         STRCT_CHG_YN      구조변경여부
11             LEM_YN  저공해조치 YN(미사용)               LEM_YN     저공해조치여부
12         NOW_MBERNO        현재 회원번호           NOW_MBR_NO      현재회원번호
13            OWNR_SE         소유자 구분      VHCL_OWNR_CL_CD   차량소유자분류코드
14              PURPS             용도            PURPS_CD2       용도코드2
15            SRCMNNO         제원관리번호          MANP_MNG_NO      제원관리번호
16            UPDT_DT          수정 일시             MDFCN_DT        수정일시
17       VHCL_ERSR_YN       차량 말소 YN         VHCL_ERSR_YN      차량말소여부
18      VHCL_MNFCT_DE       차량 제작 일자       VHCL_FBCTN_YMD      차량제작일자
19        VHCL_YRIDNW          차량 연식               YRIDNW          연식
20              VHCTY             차종             VHCTY_CD        차종코드
21              VHMNO         차량관리번호          VHCL_MNG_NO      차량관리번호
22     VHRNO_NUM_INFO   차량등록번호 숫자 정보      VHRNO_FGRE_INFO         NaN
23                VIN           차대번호                  VIN        차대번호
24              VHRNO             미정                VHRNO          미정
25        NOW_OWNR_NM             미정                  NaN         NaN
26          BSPL_ADRS             미정                  NaN         NaN
27          OWNR_ADRS             미정                  NaN         NaN
28           BSPL_ZIP             미정                  NaN         NaN
29        FST_OWNR_NM             미정                  NaN         NaN
30                RMK             미정                  NaN         NaN
31            USER_ID             미정                  NaN         NaN

In [89]:
tocount

array([28150030., 28106125., 28534047., 28534047., 25177959., 28534015.,
       28533413., 28499737., 28534047.,   485612., 28534042., 27224405.,
       28524399., 28534047., 28534047., 28534047., 21219185., 28534047.,
       28109503., 28534047., 28534033., 28534047., 28534047., 28534047.,
       28534047., 28534045., 28534026., 28534044.,        0., 28534011.,
        9238485., 28534046.])

In [90]:
tscount

array([28034244., 27990333., 28415224., 28415224., 25121146., 28415192.,
       28414590., 28380914., 28415224.,   484560., 28415219., 27105633.,
       28405576., 28415224., 28415224., 28415224., 21033082., 28415224.,
       27990681., 28415224., 28415210., 28415224., 28415224., 28415224.,
       28415224.,       nan,       nan,       nan,       nan,       nan,
             nan,       nan])

In [91]:
total_count['ODS_count'] = tocount
total_count['STD_count'] = tscount

In [92]:
total_count

              ODS_col   ODS_count              STD_col   STD_count
0            ACQS_AMT  28150030.0             ACQS_AMT  28034244.0
1             ACQS_DE  28106125.0             ACQS_YMD  27990333.0
2        BSPL_LEDO_CD  28534047.0         BSPL_STDG_CD  28415224.0
3             CRTN_DT  28534047.0          VHCL_REG_DT  28415224.0
4         EMIS_CRTCNO  25177959.0    EXHST_GAS_CERT_NO  25121146.0
5            EMIS_GRD  28534015.0     EXHST_GAS_GRD_CD  28415192.0
6   EMIS_INSP_EFCT_DE  28533413.0  EXTGAS_INSP_VLD_YMD  28414590.0
7          FST_MBERNO  28499737.0          FRST_MBR_NO  28380914.0
8          FST_REG_DE  28534047.0         FRST_REG_YMD  28415224.0
9             LEM_KND    485612.0           LEM_KND_CD    484560.0
10      LEM_STRCHG_YN  28534042.0         STRCT_CHG_YN  28415219.0
11             LEM_YN  27224405.0               LEM_YN  27105633.0
12         NOW_MBERNO  28524399.0           NOW_MBR_NO  28405576.0
13            OWNR_SE  28534047.0      VHCL_OWNR_CL_CD  28415224.0
14              PURPS  28534047.0            PURPS_CD2  28415224.0
15            SRCMNNO  28534047.0          MANP_MNG_NO  28415224.0
16            UPDT_DT  21219185.0             MDFCN_DT  21033082.0
17       VHCL_ERSR_YN  28534047.0         VHCL_ERSR_YN  28415224.0
18      VHCL_MNFCT_DE  28109503.0       VHCL_FBCTN_YMD  27990681.0
19        VHCL_YRIDNW  28534047.0               YRIDNW  28415224.0
20              VHCTY  28534033.0             VHCTY_CD  28415210.0
21              VHMNO  28534047.0          VHCL_MNG_NO  28415224.0
22     VHRNO_NUM_INFO  28534047.0      VHRNO_FGRE_INFO  28415224.0
23                VIN  28534047.0                  VIN  28415224.0
24              VHRNO  28534047.0                VHRNO  28415224.0
25        NOW_OWNR_NM  28534045.0                  NaN         NaN
26          BSPL_ADRS  28534026.0                  NaN         NaN
27          OWNR_ADRS  28534044.0                  NaN         NaN
28           BSPL_ZIP         0.0                  NaN         NaN
29        FST_OWNR_NM  28534011.0                  NaN         NaN
30                RMK   9238485.0                  NaN         NaN
31            USER_ID  28534046.0                  NaN         NaN

In [93]:
total_count['diff'] = total_count['ODS_count'] - total_count['STD_count']
total_count

              ODS_col   ODS_count              STD_col   STD_count      diff
0            ACQS_AMT  28150030.0             ACQS_AMT  28034244.0  115786.0
1             ACQS_DE  28106125.0             ACQS_YMD  27990333.0  115792.0
2        BSPL_LEDO_CD  28534047.0         BSPL_STDG_CD  28415224.0  118823.0
3             CRTN_DT  28534047.0          VHCL_REG_DT  28415224.0  118823.0
4         EMIS_CRTCNO  25177959.0    EXHST_GAS_CERT_NO  25121146.0   56813.0
5            EMIS_GRD  28534015.0     EXHST_GAS_GRD_CD  28415192.0  118823.0
6   EMIS_INSP_EFCT_DE  28533413.0  EXTGAS_INSP_VLD_YMD  28414590.0  118823.0
7          FST_MBERNO  28499737.0          FRST_MBR_NO  28380914.0  118823.0
8          FST_REG_DE  28534047.0         FRST_REG_YMD  28415224.0  118823.0
9             LEM_KND    485612.0           LEM_KND_CD    484560.0    1052.0
10      LEM_STRCHG_YN  28534042.0         STRCT_CHG_YN  28415219.0  118823.0
11             LEM_YN  27224405.0               LEM_YN  27105633.0  118772.0
12         NOW_MBERNO  28524399.0           NOW_MBR_NO  28405576.0  118823.0
13            OWNR_SE  28534047.0      VHCL_OWNR_CL_CD  28415224.0  118823.0
14              PURPS  28534047.0            PURPS_CD2  28415224.0  118823.0
15            SRCMNNO  28534047.0          MANP_MNG_NO  28415224.0  118823.0
16            UPDT_DT  21219185.0             MDFCN_DT  21033082.0  186103.0
17       VHCL_ERSR_YN  28534047.0         VHCL_ERSR_YN  28415224.0  118823.0
18      VHCL_MNFCT_DE  28109503.0       VHCL_FBCTN_YMD  27990681.0  118822.0
19        VHCL_YRIDNW  28534047.0               YRIDNW  28415224.0  118823.0
20              VHCTY  28534033.0             VHCTY_CD  28415210.0  118823.0
21              VHMNO  28534047.0          VHCL_MNG_NO  28415224.0  118823.0
22     VHRNO_NUM_INFO  28534047.0      VHRNO_FGRE_INFO  28415224.0  118823.0
23                VIN  28534047.0                  VIN  28415224.0  118823.0
24              VHRNO  28534047.0                VHRNO  28415224.0  118823.0
25        NOW_OWNR_NM  28534045.0                  NaN         NaN       NaN
26          BSPL_ADRS  28534026.0                  NaN         NaN       NaN
27          OWNR_ADRS  28534044.0                  NaN         NaN       NaN
28           BSPL_ZIP         0.0                  NaN         NaN       NaN
29        FST_OWNR_NM  28534011.0                  NaN         NaN       NaN
30                RMK   9238485.0                  NaN         NaN       NaN
31            USER_ID  28534046.0                  NaN         NaN       NaN

In [95]:
total_count.to_excel('analysis/ODSvsSTD/[정제]ODS_CEG_CAR_MIG_vs_STD_CEG_CAR_MIG.xlsx', index=False)

#### 파일별 shape

In [40]:
def file_shape(num):
   # 파일명, 파일경로 설정
   ods_file_name = f'ODS_CEG_CAR_MIG_{num}'
   std_file_name = f'STD_CEG_CAR_MIG_{num}'
   opath = os.path.join(ods_path, ods_file_name + '.csv')
   spath = os.path.join(std_path, std_file_name + '.csv')
   odf = pd.read_csv(opath)
   sdf = pd.read_csv(spath)

   # 분석
   olist = [
   'ACQS_AMT', 
   'ACQS_DE', 
   'BSPL_LEDO_CD', 
   'CRTN_DT', 
   'EMIS_CRTCNO', 
   'EMIS_GRD', 
   'EMIS_INSP_EFCT_DE', 
   'FST_MBERNO', 
   'FST_REG_DE', 
   'LEM_KND', 
   'LEM_STRCHG_YN', 
   'LEM_YN', 
   'NOW_MBERNO', 
   'OWNR_SE', 
   'PURPS', 
   'SRCMNNO', 
   'UPDT_DT', 
   'VHCL_ERSR_YN', 
   'VHCL_MNFCT_DE', 
   'VHCL_YRIDNW', 
   'VHCTY', 
   'VHMNO', 
   'VHRNO_NUM_INFO', 
   'VIN', 'VHRNO', 
   'NOW_OWNR_NM', 
   'BSPL_ADRS', 
   'OWNR_ADRS', 
   'BSPL_ZIP', 
   'FST_OWNR_NM', 
   'RMK', 
   'USER_ID'
   ]
   slist = [
   'ACQS_AMT', 
   'ACQS_YMD', 
   'BSPL_STDG_CD', 
   'VHCL_REG_DT', 
   'EXHST_GAS_CERT_NO', 
   'EXHST_GAS_GRD_CD', 
   'EXTGAS_INSP_VLD_YMD', 
   'FRST_MBR_NO', 
   'FRST_REG_YMD', 
   'LEM_KND_CD', 
   'STRCT_CHG_YN', 
   'LEM_YN', 
   'NOW_MBR_NO', 
   'VHCL_OWNR_CL_CD', 
   'PURPS_CD2', 
   'MANP_MNG_NO', 
   'MDFCN_DT', 
   'VHCL_ERSR_YN', 
   'VHCL_FBCTN_YMD', 
   'YRIDNW', 
   'VHCTY_CD', 
   'VHCL_MNG_NO', 
   'VHRNO_FGRE_INFO', 
   'VIN', 
   'VHRNO'
   ]
   odict = {
   '컬럼':olist,
   '내용':['취득금액', '취득일자', '본거지 법정동 코드', '생성 일시', '배출가스 인증번호', '배출가스 등급', '배출가스검사유효일자', '최초 회원번호', '최초 등록 일자', '저공해조치 종류', '저공해조치 구조변경 YN', '저공해조치 YN(미사용)', '현재 회원번호', '소유자 구분', '용도', '제원관리번호', '수정 일시', '차량 말소 YN', '차량 제작 일자', '차량 연식', '차종', '차량관리번호', '차량등록번호 숫자 정보', '차대번호', '미정', '미정', '미정', '미정', '미정', '미정', '미정', '미정']
   }
   ocol = pd.DataFrame(odict)

   sdict = {
      '컬럼':slist,
      '내용':['취득금액', '취득일자', '본거지법정동코드', '차량등록일시', '배출가스인증번호', '배출가스등급', '배출가스검사유효일자', '최초회원번호', '최초등록일자', '저공해조치종류코드', '구조변경여부', '저공해조치여부', '현재회원번호', '차량소유자분류코드', '용도코드2', '제원관리번호', '수정일시', '차량말소여부', '차량제작일자', '연식', '차종코드', '차량관리번호', np.nan, '차대번호', '미정']
      }
   scol = pd.DataFrame(sdict)

   odf2 = odf[olist]
   sdf2 = sdf[slist]

   print(f'{ods_file_name}_vs_{std_file_name}')
   print(odf2.shape, sdf2.shape)

In [41]:
for n in tqdm(range(1, 31)):
    try:
        file_shape(n)
    except:
        pass

  0%|          | 0/30 [00:00<?, ?it/s]C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:7: DtypeWarning: Columns (13,15,26) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
  3%|▎         | 1/30 [00:15<07:27, 15.44s/it]

ODS_CEG_CAR_MIG_1_vs_STD_CEG_CAR_MIG_1
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:7: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
  7%|▋         | 2/30 [00:30<07:10, 15.37s/it]

ODS_CEG_CAR_MIG_2_vs_STD_CEG_CAR_MIG_2
(1000000, 32) (1000000, 25)

 10%|█         | 3/30 [00:46<06:55, 15.38s/it]

ODS_CEG_CAR_MIG_3_vs_STD_CEG_CAR_MIG_3
(1000000, 32) (1000000, 25)

 13%|█▎        | 4/30 [01:01<06:42, 15.48s/it]

ODS_CEG_CAR_MIG_4_vs_STD_CEG_CAR_MIG_4
(1000000, 32) (1000000, 25)

 17%|█▋        | 5/30 [01:17<06:27, 15.51s/it]

ODS_CEG_CAR_MIG_5_vs_STD_CEG_CAR_MIG_5
(1000000, 32) (1000000, 25)

 20%|██        | 6/30 [01:33<06:14, 15.60s/it]

ODS_CEG_CAR_MIG_6_vs_STD_CEG_CAR_MIG_6
(1000000, 32) (1000000, 25)

 23%|██▎       | 7/30 [01:48<06:00, 15.68s/it]

ODS_CEG_CAR_MIG_7_vs_STD_CEG_CAR_MIG_7
(1000000, 32) (1000000, 25)

 27%|██▋       | 8/30 [02:04<05:44, 15.65s/it]

ODS_CEG_CAR_MIG_8_vs_STD_CEG_CAR_MIG_8
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:7: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
 30%|███       | 9/30 [02:20<05:28, 15.64s/it]

ODS_CEG_CAR_MIG_9_vs_STD_CEG_CAR_MIG_9
(1000000, 32) (1000000, 25)

 33%|███▎      | 10/30 [02:35<05:11, 15.57s/it]

ODS_CEG_CAR_MIG_10_vs_STD_CEG_CAR_MIG_10
(1000000, 32) (1000000, 25)

 37%|███▋      | 11/30 [02:51<04:55, 15.55s/it]

ODS_CEG_CAR_MIG_11_vs_STD_CEG_CAR_MIG_11
(1000000, 32) (1000000, 25)

 40%|████      | 12/30 [03:06<04:40, 15.57s/it]

ODS_CEG_CAR_MIG_12_vs_STD_CEG_CAR_MIG_12
(1000000, 32) (1000000, 25)

 43%|████▎     | 13/30 [03:22<04:24, 15.57s/it]

ODS_CEG_CAR_MIG_13_vs_STD_CEG_CAR_MIG_13
(1000000, 32) (1000000, 25)

 47%|████▋     | 14/30 [03:37<04:08, 15.55s/it]

ODS_CEG_CAR_MIG_14_vs_STD_CEG_CAR_MIG_14
(1000000, 32) (1000000, 25)

 50%|█████     | 15/30 [03:53<03:53, 15.55s/it]

ODS_CEG_CAR_MIG_15_vs_STD_CEG_CAR_MIG_15
(1000000, 32) (1000000, 25)

 53%|█████▎    | 16/30 [04:08<03:37, 15.52s/it]

ODS_CEG_CAR_MIG_16_vs_STD_CEG_CAR_MIG_16
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:7: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 57%|█████▋    | 17/30 [04:24<03:21, 15.50s/it]

ODS_CEG_CAR_MIG_17_vs_STD_CEG_CAR_MIG_17
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 60%|██████    | 18/30 [04:39<03:06, 15.57s/it]

ODS_CEG_CAR_MIG_18_vs_STD_CEG_CAR_MIG_18
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 63%|██████▎   | 19/30 [04:55<02:50, 15.53s/it]

ODS_CEG_CAR_MIG_19_vs_STD_CEG_CAR_MIG_19
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 67%|██████▋   | 20/30 [05:10<02:35, 15.54s/it]

ODS_CEG_CAR_MIG_20_vs_STD_CEG_CAR_MIG_20
(1000000, 32) (1000000, 25)

 70%|███████   | 21/30 [05:21<02:06, 14.01s/it]C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 73%|███████▎  | 22/30 [05:37<01:56, 14.57s/it]

ODS_CEG_CAR_MIG_22_vs_STD_CEG_CAR_MIG_22
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 77%|███████▋  | 23/30 [05:53<01:45, 15.05s/it]

ODS_CEG_CAR_MIG_23_vs_STD_CEG_CAR_MIG_23
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 80%|████████  | 24/30 [06:09<01:32, 15.48s/it]

ODS_CEG_CAR_MIG_24_vs_STD_CEG_CAR_MIG_24
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 83%|████████▎ | 25/30 [06:26<01:18, 15.65s/it]

ODS_CEG_CAR_MIG_25_vs_STD_CEG_CAR_MIG_25
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 87%|████████▋ | 26/30 [06:41<01:02, 15.72s/it]

ODS_CEG_CAR_MIG_26_vs_STD_CEG_CAR_MIG_26
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 90%|█████████ | 27/30 [06:57<00:47, 15.74s/it]

ODS_CEG_CAR_MIG_27_vs_STD_CEG_CAR_MIG_27
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 93%|█████████▎| 28/30 [07:13<00:31, 15.75s/it]

ODS_CEG_CAR_MIG_28_vs_STD_CEG_CAR_MIG_28
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (1,9,15,18) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 97%|█████████▋| 29/30 [07:28<00:15, 15.63s/it]

ODS_CEG_CAR_MIG_29_vs_STD_CEG_CAR_MIG_29
(1000000, 32) (1000000, 25)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\2617053573.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
100%|██████████| 30/30 [07:36<00:00, 15.22s/it]

ODS_CEG_CAR_MIG_30_vs_STD_CEG_CAR_MIG_30
(534047, 32) (415224, 25)

### test

#### 파일명 설정

In [56]:
num = 4
ods_file_name = f'ODS_CEG_CAR_MIG_{num}'
std_file_name = f'STD_CEG_CAR_MIG_{num}'

In [57]:
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')

In [58]:
odf = pd.read_csv(opath)
sdf = pd.read_csv(spath)

#### 등록정보 분석

In [59]:
odf.columns

Index(['VHMNO', 'VHRNO', 'BSPL_LEDO_CD', 'OWNR_SE', 'VHCTY', 'PURPS',
       'NOW_OWNR_NM', 'NOW_MBERNO', 'BSPL_ADRS', 'OWNR_ADRS', 'VIN',
       'FST_REG_DE', 'VHCL_YRIDNW', 'VHCL_MNFCT_DE', 'EMIS_INSP_EFCT_DE',
       'SRCMNNO', 'EMIS_CRTCNO', 'EMIS_GRD', 'LEM_YN', 'LEM_KND',
       'LEM_STRCHG_YN', 'BSPL_ZIP', 'VHRNO_NUM_INFO', 'VHCL_ERSR_YN',
       'FST_OWNR_NM', 'FST_MBERNO', 'ACQS_DE', 'ACQS_AMT', 'RMK', 'CRTN_DT',
       'UPDT_DT', 'USER_ID'],
      dtype='object')

In [60]:
sdf.columns

Index(['ACQS_AMT', 'ACQS_YMD', 'BSPL_STDG_CD', 'VHCL_REG_DT',
       'EXHST_GAS_CERT_NO', 'EXHST_GAS_GRD_CD', 'EXTGAS_INSP_VLD_YMD',
       'FRST_MBR_NO', 'FRST_REG_YMD', 'LEM_KND_CD', 'STRCT_CHG_YN', 'LEM_YN',
       'NOW_MBR_NO', 'VHCL_OWNR_CL_CD', 'PURPS_CD2', 'MANP_MNG_NO', 'MDFCN_DT',
       'VHCL_ERSR_YN', 'VHCL_FBCTN_YMD', 'YRIDNW', 'VHCTY_CD', 'VHCL_MNG_NO',
       'VHRNO_FGRE_INFO', 'VIN', 'VHRNO'],
      dtype='object')

In [61]:
len(odf.columns), len(sdf.columns)

(32, 25)

In [62]:
odf.shape, sdf.shape

((1000000, 32), (1000000, 25))

##### 동일한 내용의 컬럼 확인

In [63]:
olist = [
    'ACQS_AMT', 
    'ACQS_DE', 
    'BSPL_LEDO_CD', 
    'CRTN_DT', 
    'EMIS_CRTCNO', 
    'EMIS_GRD', 
    'EMIS_INSP_EFCT_DE', 
    'FST_MBERNO', 
    'FST_REG_DE', 
    'LEM_KND', 
    'LEM_STRCHG_YN', 
    'LEM_YN', 
    'NOW_MBERNO', 
    'OWNR_SE', 
    'PURPS', 
    'SRCMNNO', 
    'UPDT_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_MNFCT_DE', 
    'VHCL_YRIDNW', 
    'VHCTY', 
    'VHMNO', 
    'VHRNO_NUM_INFO', 
    'VIN', 'VHRNO', 
    'NOW_OWNR_NM', 
    'BSPL_ADRS', 
    'OWNR_ADRS', 
    'BSPL_ZIP', 
    'FST_OWNR_NM', 
    'RMK', 
    'USER_ID'
    ]

In [64]:
odict = {
    '컬럼':olist,
    '내용':['취득금액', '취득일자', '본거지 법정동 코드', '생성 일시', '배출가스 인증번호', '배출가스 등급', '배출가스검사유효일자', '최초 회원번호', '최초 등록 일자', '저공해조치 종류', '저공해조치 구조변경 YN', '저공해조치 YN(미사용)', '현재 회원번호', '소유자 구분', '용도', '제원관리번호', '수정 일시', '차량 말소 YN', '차량 제작 일자', '차량 연식', '차종', '차량관리번호', '차량등록번호 숫자 정보', '차대번호', '미정', '미정', '미정', '미정', '미정', '미정', '미정', '미정']
    }

In [65]:
ocol = pd.DataFrame(odict)
ocol

                   컬럼             내용
0            ACQS_AMT           취득금액
1             ACQS_DE           취득일자
2        BSPL_LEDO_CD     본거지 법정동 코드
3             CRTN_DT          생성 일시
4         EMIS_CRTCNO      배출가스 인증번호
5            EMIS_GRD        배출가스 등급
6   EMIS_INSP_EFCT_DE     배출가스검사유효일자
7          FST_MBERNO        최초 회원번호
8          FST_REG_DE       최초 등록 일자
9             LEM_KND       저공해조치 종류
10      LEM_STRCHG_YN  저공해조치 구조변경 YN
11             LEM_YN  저공해조치 YN(미사용)
12         NOW_MBERNO        현재 회원번호
13            OWNR_SE         소유자 구분
14              PURPS             용도
15            SRCMNNO         제원관리번호
16            UPDT_DT          수정 일시
17       VHCL_ERSR_YN       차량 말소 YN
18      VHCL_MNFCT_DE       차량 제작 일자
19        VHCL_YRIDNW          차량 연식
20              VHCTY             차종
21              VHMNO         차량관리번호
22     VHRNO_NUM_INFO   차량등록번호 숫자 정보
23                VIN           차대번호
24              VHRNO             미정
25        NOW_OWNR_NM             미정
26          BSPL_ADRS             미정
27          OWNR_ADRS             미정
28           BSPL_ZIP             미정
29        FST_OWNR_NM             미정
30                RMK             미정
31            USER_ID             미정

In [66]:
# ocol.to_excel(f'analysis/ODSvsSTD/[정제][col]{ods_file_name}.xlsx', index=False)

In [67]:
slist = [
    'ACQS_AMT', 
    'ACQS_YMD', 
    'BSPL_STDG_CD', 
    'VHCL_REG_DT', 
    'EXHST_GAS_CERT_NO', 
    'EXHST_GAS_GRD_CD', 
    'EXTGAS_INSP_VLD_YMD', 
    'FRST_MBR_NO', 
    'FRST_REG_YMD', 
    'LEM_KND_CD', 
    'STRCT_CHG_YN', 
    'LEM_YN', 
    'NOW_MBR_NO', 
    'VHCL_OWNR_CL_CD', 
    'PURPS_CD2', 
    'MANP_MNG_NO', 
    'MDFCN_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_FBCTN_YMD', 
    'YRIDNW', 
    'VHCTY_CD', 
    'VHCL_MNG_NO', 
    'VHRNO_FGRE_INFO', 
    'VIN', 
    'VHRNO'
    ]

In [68]:
sdict = {
       '컬럼':slist,
       '내용':['취득금액', '취득일자', '본거지법정동코드', '차량등록일시', '배출가스인증번호', '배출가스등급', '배출가스검사유효일자', '최초회원번호', '최초등록일자', '저공해조치종류코드', '구조변경여부', '저공해조치여부', '현재회원번호', '차량소유자분류코드', '용도코드2', '제원관리번호', '수정일시', '차량말소여부', '차량제작일자', '연식', '차종코드', '차량관리번호', np.nan, '차대번호', '미정']
       }

In [69]:
scol = pd.DataFrame(sdict)
scol

                     컬럼          내용
0              ACQS_AMT        취득금액
1              ACQS_YMD        취득일자
2          BSPL_STDG_CD    본거지법정동코드
3           VHCL_REG_DT      차량등록일시
4     EXHST_GAS_CERT_NO    배출가스인증번호
5      EXHST_GAS_GRD_CD      배출가스등급
6   EXTGAS_INSP_VLD_YMD  배출가스검사유효일자
7           FRST_MBR_NO      최초회원번호
8          FRST_REG_YMD      최초등록일자
9            LEM_KND_CD   저공해조치종류코드
10         STRCT_CHG_YN      구조변경여부
11               LEM_YN     저공해조치여부
12           NOW_MBR_NO      현재회원번호
13      VHCL_OWNR_CL_CD   차량소유자분류코드
14            PURPS_CD2       용도코드2
15          MANP_MNG_NO      제원관리번호
16             MDFCN_DT        수정일시
17         VHCL_ERSR_YN      차량말소여부
18       VHCL_FBCTN_YMD      차량제작일자
19               YRIDNW          연식
20             VHCTY_CD        차종코드
21          VHCL_MNG_NO      차량관리번호
22      VHRNO_FGRE_INFO         NaN
23                  VIN        차대번호
24                VHRNO          미정

In [70]:
# scol.to_excel(f'analysis/ODSvsSTD/[정제][col]{std_file_name}.xlsx', index=False)

###### 데이터 info 확인

In [71]:
odf1_1 = odf[olist]
odf1_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ACQS_AMT           964979 non-null   float64
 1   ACQS_DE            965439 non-null   float64
 2   BSPL_LEDO_CD       1000000 non-null  int64
 3   CRTN_DT            1000000 non-null  object
 4   EMIS_CRTCNO        868166 non-null   object
 5   EMIS_GRD           1000000 non-null  object
 6   EMIS_INSP_EFCT_DE  999996 non-null   float64
 7   FST_MBERNO         1000000 non-null  object
 8   FST_REG_DE         1000000 non-null  int64
 9   LEM_KND            101089 non-null   float64
 10  LEM_STRCHG_YN      1000000 non-null  object
 11  LEM_YN             999949 non-null   object
 12  NOW_MBERNO         1000000 non-null  object
 13  OWNR_SE            1000000 non-null  object
 14  PURPS              1000000 non-null  object
 15  SRCMNNO            1000000 non-null  object
 16  UPDT_DT            771436 non-null   object
 17  VHCL_ERSR_YN       1000000 non-null  object
 18  VHCL_MNFCT_DE      999981 non-null   float64
 19  VHCL_YRIDNW        1000000 non-null  int64
 20  VHCTY              1000000 non-null  object
 21  VHMNO              1000000 non-null  object
 22  VHRNO_NUM_INFO     1000000 non-null  int64
 23  VIN                1000000 non-null  object
 24  VHRNO              1000000 non-null  object
 25  NOW_OWNR_NM        1000000 non-null  object
 26  BSPL_ADRS          1000000 non-null  object
 27  OWNR_ADRS          1000000 non-null  object
 28  BSPL_ZIP           0 non-null        float64
 29  FST_OWNR_NM        1000000 non-null  object
 30  RMK                79548 non-null    object
 31  USER_ID            1000000 non-null  object
dtypes: float64(6), int64(4), object(22)
memory usage: 244.1+ MB

In [72]:
ocount = odf1_1.count().reset_index()
ocount.columns = ['index', 'ocount']
ocount

                index   ocount
0            ACQS_AMT   964979
1             ACQS_DE   965439
2        BSPL_LEDO_CD  1000000
3             CRTN_DT  1000000
4         EMIS_CRTCNO   868166
5            EMIS_GRD  1000000
6   EMIS_INSP_EFCT_DE   999996
7          FST_MBERNO  1000000
8          FST_REG_DE  1000000
9             LEM_KND   101089
10      LEM_STRCHG_YN  1000000
11             LEM_YN   999949
12         NOW_MBERNO  1000000
13            OWNR_SE  1000000
14              PURPS  1000000
15            SRCMNNO  1000000
16            UPDT_DT   771436
17       VHCL_ERSR_YN  1000000
18      VHCL_MNFCT_DE   999981
19        VHCL_YRIDNW  1000000
20              VHCTY  1000000
21              VHMNO  1000000
22     VHRNO_NUM_INFO  1000000
23                VIN  1000000
24              VHRNO  1000000
25        NOW_OWNR_NM  1000000
26          BSPL_ADRS  1000000
27          OWNR_ADRS  1000000
28           BSPL_ZIP        0
29        FST_OWNR_NM  1000000
30                RMK    79548
31            USER_ID  1000000

In [73]:
# odf1_1.count().reset_index().to_excel(f'analysis/ODSvsSTD/[정제][count]{ods_file_name}.xlsx', index=False)

In [74]:
sdf1_1 = sdf[slist]
sdf1_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 25 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   ACQS_AMT             987951 non-null   float64
 1   ACQS_YMD             988042 non-null   float64
 2   BSPL_STDG_CD         1000000 non-null  int64
 3   VHCL_REG_DT          1000000 non-null  object
 4   EXHST_GAS_CERT_NO    890589 non-null   object
 5   EXHST_GAS_GRD_CD     1000000 non-null  object
 6   EXTGAS_INSP_VLD_YMD  999997 non-null   float64
 7   FRST_MBR_NO          1000000 non-null  object
 8   FRST_REG_YMD         1000000 non-null  int64
 9   LEM_KND_CD           30025 non-null    object
 10  STRCT_CHG_YN         1000000 non-null  object
 11  LEM_YN               999965 non-null   object
 12  NOW_MBR_NO           1000000 non-null  object
 13  VHCL_OWNR_CL_CD      1000000 non-null  object
 14  PURPS_CD2            1000000 non-null  object
 15  MANP_MNG_NO          1000000 non-null  object
 16  MDFCN_DT             762134 non-null   object
 17  VHCL_ERSR_YN         1000000 non-null  object
 18  VHCL_FBCTN_YMD       999992 non-null   float64
 19  YRIDNW               1000000 non-null  int64
 20  VHCTY_CD             1000000 non-null  object
 21  VHCL_MNG_NO          1000000 non-null  object
 22  VHRNO_FGRE_INFO      1000000 non-null  int64
 23  VIN                  1000000 non-null  object
 24  VHRNO                1000000 non-null  object
dtypes: float64(4), int64(4), object(17)
memory usage: 190.7+ MB

In [75]:
scount = sdf1_1.count().reset_index()
scount.columns = ['index', 'scount']
scount

                  index   scount
0              ACQS_AMT   987951
1              ACQS_YMD   988042
2          BSPL_STDG_CD  1000000
3           VHCL_REG_DT  1000000
4     EXHST_GAS_CERT_NO   890589
5      EXHST_GAS_GRD_CD  1000000
6   EXTGAS_INSP_VLD_YMD   999997
7           FRST_MBR_NO  1000000
8          FRST_REG_YMD  1000000
9            LEM_KND_CD    30025
10         STRCT_CHG_YN  1000000
11               LEM_YN   999965
12           NOW_MBR_NO  1000000
13      VHCL_OWNR_CL_CD  1000000
14            PURPS_CD2  1000000
15          MANP_MNG_NO  1000000
16             MDFCN_DT   762134
17         VHCL_ERSR_YN  1000000
18       VHCL_FBCTN_YMD   999992
19               YRIDNW  1000000
20             VHCTY_CD  1000000
21          VHCL_MNG_NO  1000000
22      VHRNO_FGRE_INFO  1000000
23                  VIN  1000000
24                VHRNO  1000000

In [76]:
# sdf1_1.count().reset_index().to_excel(f'analysis/ODSvsSTD/[정제][count]{std_file_name}.xlsx', index=False)

In [77]:
oscount = pd.concat([ocount, scount], axis=1)
oscount

                index   ocount                index     scount
0            ACQS_AMT   964979             ACQS_AMT   987951.0
1             ACQS_DE   965439             ACQS_YMD   988042.0
2        BSPL_LEDO_CD  1000000         BSPL_STDG_CD  1000000.0
3             CRTN_DT  1000000          VHCL_REG_DT  1000000.0
4         EMIS_CRTCNO   868166    EXHST_GAS_CERT_NO   890589.0
5            EMIS_GRD  1000000     EXHST_GAS_GRD_CD  1000000.0
6   EMIS_INSP_EFCT_DE   999996  EXTGAS_INSP_VLD_YMD   999997.0
7          FST_MBERNO  1000000          FRST_MBR_NO  1000000.0
8          FST_REG_DE  1000000         FRST_REG_YMD  1000000.0
9             LEM_KND   101089           LEM_KND_CD    30025.0
10      LEM_STRCHG_YN  1000000         STRCT_CHG_YN  1000000.0
11             LEM_YN   999949               LEM_YN   999965.0
12         NOW_MBERNO  1000000           NOW_MBR_NO  1000000.0
13            OWNR_SE  1000000      VHCL_OWNR_CL_CD  1000000.0
14              PURPS  1000000            PURPS_CD2  1000000.0
15            SRCMNNO  1000000          MANP_MNG_NO  1000000.0
16            UPDT_DT   771436             MDFCN_DT   762134.0
17       VHCL_ERSR_YN  1000000         VHCL_ERSR_YN  1000000.0
18      VHCL_MNFCT_DE   999981       VHCL_FBCTN_YMD   999992.0
19        VHCL_YRIDNW  1000000               YRIDNW  1000000.0
20              VHCTY  1000000             VHCTY_CD  1000000.0
21              VHMNO  1000000          VHCL_MNG_NO  1000000.0
22     VHRNO_NUM_INFO  1000000      VHRNO_FGRE_INFO  1000000.0
23                VIN  1000000                  VIN  1000000.0
24              VHRNO  1000000                VHRNO  1000000.0
25        NOW_OWNR_NM  1000000                  NaN        NaN
26          BSPL_ADRS  1000000                  NaN        NaN
27          OWNR_ADRS  1000000                  NaN        NaN
28           BSPL_ZIP        0                  NaN        NaN
29        FST_OWNR_NM  1000000                  NaN        NaN
30                RMK    79548                  NaN        NaN
31            USER_ID  1000000                  NaN        NaN

In [78]:
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount

                index   ocount                index     scount       차이
0            ACQS_AMT   964979             ACQS_AMT   987951.0 -22972.0
1             ACQS_DE   965439             ACQS_YMD   988042.0 -22603.0
2        BSPL_LEDO_CD  1000000         BSPL_STDG_CD  1000000.0      0.0
3             CRTN_DT  1000000          VHCL_REG_DT  1000000.0      0.0
4         EMIS_CRTCNO   868166    EXHST_GAS_CERT_NO   890589.0 -22423.0
5            EMIS_GRD  1000000     EXHST_GAS_GRD_CD  1000000.0      0.0
6   EMIS_INSP_EFCT_DE   999996  EXTGAS_INSP_VLD_YMD   999997.0     -1.0
7          FST_MBERNO  1000000          FRST_MBR_NO  1000000.0      0.0
8          FST_REG_DE  1000000         FRST_REG_YMD  1000000.0      0.0
9             LEM_KND   101089           LEM_KND_CD    30025.0  71064.0
10      LEM_STRCHG_YN  1000000         STRCT_CHG_YN  1000000.0      0.0
11             LEM_YN   999949               LEM_YN   999965.0    -16.0
12         NOW_MBERNO  1000000           NOW_MBR_NO  1000000.0      0.0
13            OWNR_SE  1000000      VHCL_OWNR_CL_CD  1000000.0      0.0
14              PURPS  1000000            PURPS_CD2  1000000.0      0.0
15            SRCMNNO  1000000          MANP_MNG_NO  1000000.0      0.0
16            UPDT_DT   771436             MDFCN_DT   762134.0   9302.0
17       VHCL_ERSR_YN  1000000         VHCL_ERSR_YN  1000000.0      0.0
18      VHCL_MNFCT_DE   999981       VHCL_FBCTN_YMD   999992.0    -11.0
19        VHCL_YRIDNW  1000000               YRIDNW  1000000.0      0.0
20              VHCTY  1000000             VHCTY_CD  1000000.0      0.0
21              VHMNO  1000000          VHCL_MNG_NO  1000000.0      0.0
22     VHRNO_NUM_INFO  1000000      VHRNO_FGRE_INFO  1000000.0      0.0
23                VIN  1000000                  VIN  1000000.0      0.0
24              VHRNO  1000000                VHRNO  1000000.0      0.0
25        NOW_OWNR_NM  1000000                  NaN        NaN      NaN
26          BSPL_ADRS  1000000                  NaN        NaN      NaN
27          OWNR_ADRS  1000000                  NaN        NaN      NaN
28           BSPL_ZIP        0                  NaN        NaN      NaN
29        FST_OWNR_NM  1000000                  NaN        NaN      NaN
30                RMK    79548                  NaN        NaN      NaN
31            USER_ID  1000000                  NaN        NaN      NaN

#### [출력] 분석내용

In [63]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
oscount.to_excel(texcel, sheet_name='count', index=False)
# odf1_1.count().reset_index().to_excel(texcel, sheet_name='ODS_count',index=False)
# sdf1_1.count().reset_index().to_excel(texcel, sheet_name='STD_count',index=False)
texcel.save()

## 2\. 자동차 제원정보 데이터 비교

### 파일명 설정

In [2]:
ods_file_name2 = 'ODS_CEG_CAR_SRC_MIG'
std_file_name2 = 'STD_CEG_CAR_SRC_MIG'

In [6]:
opath2 = os.path.join(ods_path, ods_file_name2 + '.csv')
spath2 = os.path.join(std_path, std_file_name2 + '.csv')

In [8]:
odf2 = pd.read_csv(opath2)
sdf2 = pd.read_csv(spath2)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\1557069306.py:1: DtypeWarning: Columns (21,22,24) have mixed types. Specify dtype option on import or set low_memory=False.
  odf2 = pd.read_csv(opath2)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\1557069306.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf2 = pd.read_csv(spath2)

In [9]:
odf2.columns

Index(['SRCMNNO', 'VHCNM', 'VHCTY', 'VHCTY_CL', 'VHCTY_TY', 'CAR_FRM',
       'MKR_NM', 'FUEL', 'EGINTY', 'EMPV_WGHT', 'TOT_WGHT', 'CRYNG_WGHT',
       'EGINPWR', 'DSPLVL', 'TKCAR_NMPR', 'VHCL_LT', 'VHCL_WH', 'VHCL_HG',
       'PLOR_NM', 'REPCAR_NM', 'DELE_YN', 'CNFRM_DE', 'DRV_FRM', 'GEARBOX_KND',
       'RMK', 'CRTN_DT', 'UPDT_DT', 'USER_ID'],
      dtype='object')

In [10]:
sdf2.columns

Index(['VHCL_FRM', 'APRV_YMD', 'VHCL_REG_DT', 'CRYNG_WGHT', 'DEL_YN',
       'VHCL_DRVE_FRM_CD', 'DSPLVL', 'EGIN_OTPT', 'EGIN_TY', 'EMPV_WGHT',
       'FUEL_CD', 'GEARBOX_KND_CD', 'MNFCTR_NM', 'FBCTN_NTN_NM', 'MANP_MNG_NO',
       'TKCAR_PSCP', 'TOTL_WGHT', 'MDFCN_DT', 'OVRHG', 'OVRLH', 'OVRWD',
       'VHCNM', 'VHCTY_CD', 'VHCTY_CL_CD', 'VHCTY_TY_CD2'],
      dtype='object')

In [11]:
len(odf2.columns), len(sdf2.columns)

(28, 25)

In [42]:
odf2.shape, sdf2.shape

((545374, 28), (545374, 25))

### 컬럼 확인

In [15]:
olist2 = [
    'CAR_FRM',
    'CNFRM_DE', 
    'CRTN_DT', 
    'CRYNG_WGHT',
    'DELE_YN', 
    'DRV_FRM', 
    'DSPLVL', 
    'EGINPWR', 
    'EGINTY', 
    'EMPV_WGHT', 
    'FUEL', 
    'GEARBOX_KND',
    'MKR_NM', 
    'PLOR_NM', 
    'SRCMNNO', 
    'TKCAR_NMPR', 
    'TOT_WGHT', 
    'UPDT_DT', 
    'VHCL_HG',
    'VHCL_LT', 
    'VHCL_WH', 
    'VHCNM', 
    'VHCTY', 
    'VHCTY_CL', 
    'VHCTY_TY', 

    'REPCAR_NM', 
    'RMK', 
    'USER_ID'
    ]

odict2 = {
    '컬럼':olist2,
    '내용':
    ['자동차 형식', 
    '승인 일자', 
    '생성 일시', 
    '적재 중량', 
    '삭제 YN', 
    '구동 형식', 
    '배기량', 
    '엔진출력', 
    '엔진형식', 
    '공차중량', 
    '연료', 
    '변속기 종류', 
    '제작사 명', 
    '원산지 명', 
    '제원관리번호', 
    '승차 인원', 
    '총 중량', 
    '수정 일시', 
    '차량 높이', 
    '차량 길이', 
    '차량 너비', 
    '차명', 
    '차종', 
    '차종 분류', 
    '차종 유형 (소분류)',
     
    '미정', 
    '미정', 
    '미정']
    }

ocol2 = pd.DataFrame(odict2)
ocol2

             컬럼           내용
0       CAR_FRM       자동차 형식
1      CNFRM_DE        승인 일자
2       CRTN_DT        생성 일시
3    CRYNG_WGHT        적재 중량
4       DELE_YN        삭제 YN
5       DRV_FRM        구동 형식
6        DSPLVL          배기량
7       EGINPWR         엔진출력
8        EGINTY         엔진형식
9     EMPV_WGHT         공차중량
10         FUEL           연료
11  GEARBOX_KND       변속기 종류
12       MKR_NM        제작사 명
13      PLOR_NM        원산지 명
14      SRCMNNO       제원관리번호
15   TKCAR_NMPR        승차 인원
16     TOT_WGHT         총 중량
17      UPDT_DT        수정 일시
18      VHCL_HG        차량 높이
19      VHCL_LT        차량 길이
20      VHCL_WH        차량 너비
21        VHCNM           차명
22        VHCTY           차종
23     VHCTY_CL        차종 분류
24     VHCTY_TY  차종 유형 (소분류)
25    REPCAR_NM           미정
26          RMK           미정
27      USER_ID           미정

In [16]:
slist2 = [
    'VHCL_FRM', 
    'APRV_YMD', 
    'VHCL_REG_DT', 
    'CRYNG_WGHT', 
    'DEL_YN',
    'VHCL_DRVE_FRM_CD', 
    'DSPLVL', 
    'EGIN_OTPT', 
    'EGIN_TY', 
    'EMPV_WGHT',
    'FUEL_CD', 
    'GEARBOX_KND_CD', 
    'MNFCTR_NM', 
    'FBCTN_NTN_NM', 
    'MANP_MNG_NO',
    'TKCAR_PSCP', 
    'TOTL_WGHT', 
    'MDFCN_DT', 
    'OVRHG', 
    'OVRLH', 
    'OVRWD',
    'VHCNM', 
    'VHCTY_CD', 
    'VHCTY_CL_CD', 
    'VHCTY_TY_CD2'
    ]

sdict2 = {
    '컬럼':slist2,
    '내용':
    ['차량형식', 
    '승인일자', 
    '차량등록일시', 
    '적재중량', 
    '삭제여부', 
    '차량구동형식코드', 
    '배기량', 
    '엔진출력', 
    '엔진형식', 
    '공차중량', 
    '연료코드', 
    '변속기종류코드', 
    '제작사명', 
    '제작국명', 
    '제원관리번호', 
    '승차정원', 
    '총중량', 
    '수정일시', 
    '전고', 
    '전장', 
    '전폭', 
    '차명', 
    '차종코드', 
    '차종분류코드', 
    '차종유형코드2']
    }

scol2 = pd.DataFrame(sdict2)
scol2

                  컬럼        내용
0           VHCL_FRM      차량형식
1           APRV_YMD      승인일자
2        VHCL_REG_DT    차량등록일시
3         CRYNG_WGHT      적재중량
4             DEL_YN      삭제여부
5   VHCL_DRVE_FRM_CD  차량구동형식코드
6             DSPLVL       배기량
7          EGIN_OTPT      엔진출력
8            EGIN_TY      엔진형식
9          EMPV_WGHT      공차중량
10           FUEL_CD      연료코드
11    GEARBOX_KND_CD   변속기종류코드
12         MNFCTR_NM      제작사명
13      FBCTN_NTN_NM      제작국명
14       MANP_MNG_NO    제원관리번호
15        TKCAR_PSCP      승차정원
16         TOTL_WGHT       총중량
17          MDFCN_DT      수정일시
18             OVRHG        전고
19             OVRLH        전장
20             OVRWD        전폭
21             VHCNM        차명
22          VHCTY_CD      차종코드
23       VHCTY_CL_CD    차종분류코드
24      VHCTY_TY_CD2   차종유형코드2

### 데이터 info

In [17]:
odf2_1 = odf2[olist2]
odf2_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545374 entries, 0 to 545373
Data columns (total 28 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   CAR_FRM      516295 non-null  object
 1   CNFRM_DE     532881 non-null  object
 2   CRTN_DT      545374 non-null  object
 3   CRYNG_WGHT   446181 non-null  float64
 4   DELE_YN      545374 non-null  object
 5   DRV_FRM      114619 non-null  object
 6   DSPLVL       510521 non-null  float64
 7   EGINPWR      471948 non-null  float64
 8   EGINTY       494157 non-null  object
 9   EMPV_WGHT    0 non-null       float64
 10  FUEL         503254 non-null  object
 11  GEARBOX_KND  540165 non-null  object
 12  MKR_NM       529017 non-null  object
 13  PLOR_NM      540392 non-null  object
 14  SRCMNNO      545374 non-null  object
 15  TKCAR_NMPR   545313 non-null  float64
 16  TOT_WGHT     541702 non-null  float64
 17  UPDT_DT      14578 non-null   object
 18  VHCL_HG      514732 non-null  float64
 19  VHCL_LT      514786 non-null  float64
 20  VHCL_WH      514799 non-null  float64
 21  VHCNM        545272 non-null  object
 22  VHCTY        545370 non-null  object
 23  VHCTY_CL     531367 non-null  object
 24  VHCTY_TY     531332 non-null  object
 25  REPCAR_NM    0 non-null       float64
 26  RMK          1 non-null       object
 27  USER_ID      545374 non-null  object
dtypes: float64(10), object(18)
memory usage: 116.5+ MB

In [18]:
ocount2 = odf2_1.count().reset_index()
ocount2.columns = ['index', 'ocount']
ocount2

          index  ocount
0       CAR_FRM  516295
1      CNFRM_DE  532881
2       CRTN_DT  545374
3    CRYNG_WGHT  446181
4       DELE_YN  545374
5       DRV_FRM  114619
6        DSPLVL  510521
7       EGINPWR  471948
8        EGINTY  494157
9     EMPV_WGHT       0
10         FUEL  503254
11  GEARBOX_KND  540165
12       MKR_NM  529017
13      PLOR_NM  540392
14      SRCMNNO  545374
15   TKCAR_NMPR  545313
16     TOT_WGHT  541702
17      UPDT_DT   14578
18      VHCL_HG  514732
19      VHCL_LT  514786
20      VHCL_WH  514799
21        VHCNM  545272
22        VHCTY  545370
23     VHCTY_CL  531367
24     VHCTY_TY  531332
25    REPCAR_NM       0
26          RMK       1
27      USER_ID  545374

In [19]:
sdf2_1 = sdf2[slist2]
sdf2_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545374 entries, 0 to 545373
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   VHCL_FRM          516295 non-null  object
 1   APRV_YMD          532881 non-null  object
 2   VHCL_REG_DT       545374 non-null  object
 3   CRYNG_WGHT        446181 non-null  float64
 4   DEL_YN            545374 non-null  object
 5   VHCL_DRVE_FRM_CD  114619 non-null  object
 6   DSPLVL            510521 non-null  float64
 7   EGIN_OTPT         471948 non-null  float64
 8   EGIN_TY           494157 non-null  object
 9   EMPV_WGHT         0 non-null       float64
 10  FUEL_CD           503254 non-null  object
 11  GEARBOX_KND_CD    540165 non-null  object
 12  MNFCTR_NM         528510 non-null  object
 13  FBCTN_NTN_NM      540392 non-null  object
 14  MANP_MNG_NO       545374 non-null  object
 15  TKCAR_PSCP        545313 non-null  float64
 16  TOTL_WGHT         541702 non-null  float64
 17  MDFCN_DT          14578 non-null   object
 18  OVRHG             514732 non-null  float64
 19  OVRLH             514786 non-null  float64
 20  OVRWD             514799 non-null  float64
 21  VHCNM             545272 non-null  object
 22  VHCTY_CD          545370 non-null  object
 23  VHCTY_CL_CD       531367 non-null  object
 24  VHCTY_TY_CD2      531332 non-null  object
dtypes: float64(9), object(16)
memory usage: 104.0+ MB

In [21]:
scount2 = sdf2_1.count().reset_index()
scount2.columns = ['index', 'scount']
scount2

               index  scount
0           VHCL_FRM  516295
1           APRV_YMD  532881
2        VHCL_REG_DT  545374
3         CRYNG_WGHT  446181
4             DEL_YN  545374
5   VHCL_DRVE_FRM_CD  114619
6             DSPLVL  510521
7          EGIN_OTPT  471948
8            EGIN_TY  494157
9          EMPV_WGHT       0
10           FUEL_CD  503254
11    GEARBOX_KND_CD  540165
12         MNFCTR_NM  528510
13      FBCTN_NTN_NM  540392
14       MANP_MNG_NO  545374
15        TKCAR_PSCP  545313
16         TOTL_WGHT  541702
17          MDFCN_DT   14578
18             OVRHG  514732
19             OVRLH  514786
20             OVRWD  514799
21             VHCNM  545272
22          VHCTY_CD  545370
23       VHCTY_CL_CD  531367
24      VHCTY_TY_CD2  531332

In [22]:
oscount2 = pd.concat([ocount2, scount2], axis=1)
oscount2

          index  ocount             index    scount
0       CAR_FRM  516295          VHCL_FRM  516295.0
1      CNFRM_DE  532881          APRV_YMD  532881.0
2       CRTN_DT  545374       VHCL_REG_DT  545374.0
3    CRYNG_WGHT  446181        CRYNG_WGHT  446181.0
4       DELE_YN  545374            DEL_YN  545374.0
5       DRV_FRM  114619  VHCL_DRVE_FRM_CD  114619.0
6        DSPLVL  510521            DSPLVL  510521.0
7       EGINPWR  471948         EGIN_OTPT  471948.0
8        EGINTY  494157           EGIN_TY  494157.0
9     EMPV_WGHT       0         EMPV_WGHT       0.0
10         FUEL  503254           FUEL_CD  503254.0
11  GEARBOX_KND  540165    GEARBOX_KND_CD  540165.0
12       MKR_NM  529017         MNFCTR_NM  528510.0
13      PLOR_NM  540392      FBCTN_NTN_NM  540392.0
14      SRCMNNO  545374       MANP_MNG_NO  545374.0
15   TKCAR_NMPR  545313        TKCAR_PSCP  545313.0
16     TOT_WGHT  541702         TOTL_WGHT  541702.0
17      UPDT_DT   14578          MDFCN_DT   14578.0
18      VHCL_HG  514732             OVRHG  514732.0
19      VHCL_LT  514786             OVRLH  514786.0
20      VHCL_WH  514799             OVRWD  514799.0
21        VHCNM  545272             VHCNM  545272.0
22        VHCTY  545370          VHCTY_CD  545370.0
23     VHCTY_CL  531367       VHCTY_CL_CD  531367.0
24     VHCTY_TY  531332      VHCTY_TY_CD2  531332.0
25    REPCAR_NM       0               NaN       NaN
26          RMK       1               NaN       NaN
27      USER_ID  545374               NaN       NaN

In [23]:
oscount2['차이'] = oscount2['ocount'] - oscount2['scount']
oscount2

          index  ocount             index    scount     차이
0       CAR_FRM  516295          VHCL_FRM  516295.0    0.0
1      CNFRM_DE  532881          APRV_YMD  532881.0    0.0
2       CRTN_DT  545374       VHCL_REG_DT  545374.0    0.0
3    CRYNG_WGHT  446181        CRYNG_WGHT  446181.0    0.0
4       DELE_YN  545374            DEL_YN  545374.0    0.0
5       DRV_FRM  114619  VHCL_DRVE_FRM_CD  114619.0    0.0
6        DSPLVL  510521            DSPLVL  510521.0    0.0
7       EGINPWR  471948         EGIN_OTPT  471948.0    0.0
8        EGINTY  494157           EGIN_TY  494157.0    0.0
9     EMPV_WGHT       0         EMPV_WGHT       0.0    0.0
10         FUEL  503254           FUEL_CD  503254.0    0.0
11  GEARBOX_KND  540165    GEARBOX_KND_CD  540165.0    0.0
12       MKR_NM  529017         MNFCTR_NM  528510.0  507.0
13      PLOR_NM  540392      FBCTN_NTN_NM  540392.0    0.0
14      SRCMNNO  545374       MANP_MNG_NO  545374.0    0.0
15   TKCAR_NMPR  545313        TKCAR_PSCP  545313.0    0.0
16     TOT_WGHT  541702         TOTL_WGHT  541702.0    0.0
17      UPDT_DT   14578          MDFCN_DT   14578.0    0.0
18      VHCL_HG  514732             OVRHG  514732.0    0.0
19      VHCL_LT  514786             OVRLH  514786.0    0.0
20      VHCL_WH  514799             OVRWD  514799.0    0.0
21        VHCNM  545272             VHCNM  545272.0    0.0
22        VHCTY  545370          VHCTY_CD  545370.0    0.0
23     VHCTY_CL  531367       VHCTY_CL_CD  531367.0    0.0
24     VHCTY_TY  531332      VHCTY_TY_CD2  531332.0    0.0
25    REPCAR_NM       0               NaN       NaN    NaN
26          RMK       1               NaN       NaN    NaN
27      USER_ID  545374               NaN       NaN    NaN

In [26]:
texcel2 = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name2}_vs_{std_file_name2}.xlsx')
ocol2.to_excel(texcel2, sheet_name='ODS_col', index=False)
scol2.to_excel(texcel2, sheet_name='STD_col', index=False)
oscount2.to_excel(texcel2, sheet_name='count', index=False)
texcel2.save()

## 3\. 배출가스 인증정보

In [136]:
ods_file_name3 = 'ODS_CEG_EMIS_CERTI_MIG'
std_file_name3 = 'STD_CEG_EMIS_CERTI_MIG'
opath3 = os.path.join(ods_path, ods_file_name3 + '.csv')
spath3 = os.path.join(std_path, std_file_name3 + '.csv')
odf3 = pd.read_csv(opath3)
sdf3 = pd.read_csv(spath3)
print(odf3.columns)
print(sdf3.columns)
print(len(odf3.columns), len(sdf3.columns))
print(odf3.shape, sdf3.shape)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\1065985962.py:5: DtypeWarning: Columns (14,18,19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  odf3 = pd.read_csv(opath3)

Index(['EMIS_CRTCNO', 'EMIS_CRTC_SNO', 'EMIS_CRTC_1_SE', 'EMIS_CRTC_2_SE',
       'DMSTC_INCM_MKR_SE', 'EMIS_VHCTY', 'FUEL', 'SAME_VHCTY_TY',
       'EMIS_CRTC_DE', 'MKR_NM', 'MNFCT_NM', 'PLOR_NM', 'EMIS_CRTC_STUS',
       'EMIS_CRTC_UNAVBL_DE', 'EMIS_CRTC_UNAVBL_RESN', 'ORGCAR_SRCMNNO',
       'REPCAR_EMIS_CRTCNO', 'REPCAR_VIN', 'EMIS_PERM_STDR_CD', 'EMIS_GRD',
       'RECP_FILE_NM', 'STRE_DE', 'SRCMNNO'],
      dtype='object')
Index(['DMSTC_IMP_MNFCTR_SE', 'EXHST_GAS_CERT_NO', 'EXHST_GAS_CERT_SE1',
       'EXHST_GAS_CERT_SE2', 'EXHST_GAS_CERT_YMD', 'EXHST_GAS_CERT_SN',
       'EXTGAS_CET_STS_CD', 'EXTGAS_CET_UNVBL_YMD', 'EXTGAS_CET_UNVBL_REN',
       'EXHST_GAS_GRD', 'EXTGAS_CET_PRM_CRTCD', 'VHCTY_CD', 'FUEL_CD',
       'MNFCTR_NM', 'MKR_NAME', 'MANP_MNG_NO', 'FBCTN_NTN_NM',
       'RPRSVH_EXTGAS_CET_NO', 'RPRS_CAR_VIN', 'VHCTY_TY_CD', 'DATA_STRG_YMD'],
      dtype='object')
23 21
(79725, 23) (79670, 21)

C:\Users\kbjung\AppData\Local\Temp\ipykernel_3828\1065985962.py:6: DtypeWarning: Columns (8,9,10,20) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf3 = pd.read_csv(spath3)

### 컬럼 확인

In [137]:
olist3 = [
    'DMSTC_INCM_MKR_SE', 
    'EMIS_CRTCNO', 
    'EMIS_CRTC_1_SE', 
    'EMIS_CRTC_2_SE',
    'EMIS_CRTC_DE', 
    'EMIS_CRTC_SNO', 
    'EMIS_CRTC_STUS',
    'EMIS_CRTC_UNAVBL_DE', 
    'EMIS_CRTC_UNAVBL_RESN', 
    'EMIS_GRD',
    'EMIS_PERM_STDR_CD', 
    'EMIS_VHCTY', 
    'FUEL', 
    'MKR_NM', 
    'MNFCT_NM', 
    'ORGCAR_SRCMNNO',
    'PLOR_NM', 
    'REPCAR_EMIS_CRTCNO', 
    'REPCAR_VIN', 
    'SAME_VHCTY_TY',
    'STRE_DE', 
    
    'RECP_FILE_NM', 
    'SRCMNNO'
    ]

odict3 = {
    '컬럼':olist3,
    '내용':
    ['국내 수입 제작사 구분', 
    '배출가스인증번호', 
    '배출가스 인증 1 구분', 
    '배출가스 인증 2 구분', 
    '배출가스 인증 일자', 
    '배출가스 인증 일련번호', 
    '배출가스 인증 상태', 
    '배출가스 인증 무효 일자', 
    '배출가스 인증 무효 사유', 
    '배출가스 등급', 
    '배출가스 허용 기준 코드', 
    '배출가스 차종', 
    '연료', 
    '제작사 명', 
    '제조사 명', 
    '기본차 제원관리번호', 
    '원산지 명', 
    '대표차 배출가스 인증번호', 
    '대표차 차대번호', 
    '동일 차종 유형', 
    '저장 일자',
     
    '미정', 
    '미정']
    }

ocol3 = pd.DataFrame(odict3)
ocol3

                       컬럼             내용
0       DMSTC_INCM_MKR_SE   국내 수입 제작사 구분
1             EMIS_CRTCNO       배출가스인증번호
2          EMIS_CRTC_1_SE   배출가스 인증 1 구분
3          EMIS_CRTC_2_SE   배출가스 인증 2 구분
4            EMIS_CRTC_DE     배출가스 인증 일자
5           EMIS_CRTC_SNO   배출가스 인증 일련번호
6          EMIS_CRTC_STUS     배출가스 인증 상태
7     EMIS_CRTC_UNAVBL_DE  배출가스 인증 무효 일자
8   EMIS_CRTC_UNAVBL_RESN  배출가스 인증 무효 사유
9                EMIS_GRD        배출가스 등급
10      EMIS_PERM_STDR_CD  배출가스 허용 기준 코드
11             EMIS_VHCTY        배출가스 차종
12                   FUEL             연료
13                 MKR_NM          제작사 명
14               MNFCT_NM          제조사 명
15         ORGCAR_SRCMNNO     기본차 제원관리번호
16                PLOR_NM          원산지 명
17     REPCAR_EMIS_CRTCNO  대표차 배출가스 인증번호
18             REPCAR_VIN       대표차 차대번호
19          SAME_VHCTY_TY       동일 차종 유형
20                STRE_DE          저장 일자
21           RECP_FILE_NM             미정
22                SRCMNNO             미정

In [138]:
slist3 = [
    'DMSTC_IMP_MNFCTR_SE', 
    'EXHST_GAS_CERT_NO', 
    'EXHST_GAS_CERT_SE1',
    'EXHST_GAS_CERT_SE2', 
    'EXHST_GAS_CERT_YMD', 
    'EXHST_GAS_CERT_SN',
    'EXTGAS_CET_STS_CD', 
    'EXTGAS_CET_UNVBL_YMD', 
    'EXTGAS_CET_UNVBL_REN',
    'EXHST_GAS_GRD', 
    'EXTGAS_CET_PRM_CRTCD', 
    'VHCTY_CD', 
    'FUEL_CD',
    'MNFCTR_NM', 
    'MKR_NAME', 
    'MANP_MNG_NO', 
    'FBCTN_NTN_NM',
    'RPRSVH_EXTGAS_CET_NO', 
    'RPRS_CAR_VIN', 
    'VHCTY_TY_CD', 
    'DATA_STRG_YMD'
    ]

sdict3 = {
    '컬럼':slist3,
    '내용':
    ['국내수입제작사구분', 
    '배출가스인증번호', 
    '배출가스인증구분1', 
    '배출가스인증구분2', 
    '배출가스인증일자', 
    '배출가스인증일련번호', 
    '배출가스인증상태코드', 
    '배출가스인증무효사유', 
    '배출가스인증무효사유', 
    '배출가스등급', 
    '배출가스인증허용기준코드', 
    '차종코드', 
    '연료코드', 
    '제작사명', 
    '제조사명', 
    '제원관리번호', 
    '제작국명', 
    '대표차배출가스인증번호', 
    '대표차차대번호', 
    '차종유형코드', 
    '자료저장일자']
    }

scol3 = pd.DataFrame(sdict3)
scol3

                      컬럼            내용
0    DMSTC_IMP_MNFCTR_SE     국내수입제작사구분
1      EXHST_GAS_CERT_NO      배출가스인증번호
2     EXHST_GAS_CERT_SE1     배출가스인증구분1
3     EXHST_GAS_CERT_SE2     배출가스인증구분2
4     EXHST_GAS_CERT_YMD      배출가스인증일자
5      EXHST_GAS_CERT_SN    배출가스인증일련번호
6      EXTGAS_CET_STS_CD    배출가스인증상태코드
7   EXTGAS_CET_UNVBL_YMD    배출가스인증무효사유
8   EXTGAS_CET_UNVBL_REN    배출가스인증무효사유
9          EXHST_GAS_GRD        배출가스등급
10  EXTGAS_CET_PRM_CRTCD  배출가스인증허용기준코드
11              VHCTY_CD          차종코드
12               FUEL_CD          연료코드
13             MNFCTR_NM          제작사명
14              MKR_NAME          제조사명
15           MANP_MNG_NO        제원관리번호
16          FBCTN_NTN_NM          제작국명
17  RPRSVH_EXTGAS_CET_NO   대표차배출가스인증번호
18          RPRS_CAR_VIN       대표차차대번호
19           VHCTY_TY_CD        차종유형코드
20         DATA_STRG_YMD        자료저장일자

### 데이터 info

In [139]:
odf3_1 = odf3[olist3]
odf3_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79725 entries, 0 to 79724
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   DMSTC_INCM_MKR_SE      79038 non-null  object
 1   EMIS_CRTCNO            79725 non-null  object
 2   EMIS_CRTC_1_SE         79725 non-null  object
 3   EMIS_CRTC_2_SE         79436 non-null  object
 4   EMIS_CRTC_DE           79670 non-null  float64
 5   EMIS_CRTC_SNO          79725 non-null  int64
 6   EMIS_CRTC_STUS         79681 non-null  float64
 7   EMIS_CRTC_UNAVBL_DE    361 non-null    float64
 8   EMIS_CRTC_UNAVBL_RESN  45 non-null     object
 9   EMIS_GRD               23923 non-null  object
 10  EMIS_PERM_STDR_CD      17746 non-null  object
 11  EMIS_VHCTY             79519 non-null  object
 12  FUEL                   79493 non-null  object
 13  MKR_NM                 78956 non-null  object
 14  MNFCT_NM               79554 non-null  object
 15  ORGCAR_SRCMNNO         60648 non-null  object
 16  PLOR_NM                29928 non-null  object
 17  REPCAR_EMIS_CRTCNO     26100 non-null  object
 18  REPCAR_VIN             55697 non-null  object
 19  SAME_VHCTY_TY          9155 non-null   object
 20  STRE_DE                79715 non-null  object
 21  RECP_FILE_NM           79707 non-null  object
 22  SRCMNNO                0 non-null      float64
dtypes: float64(4), int64(1), object(18)
memory usage: 14.0+ MB

In [140]:
ocount3 = odf3_1.count().reset_index()
ocount3.columns = ['index', 'ocount']
ocount3

                    index  ocount
0       DMSTC_INCM_MKR_SE   79038
1             EMIS_CRTCNO   79725
2          EMIS_CRTC_1_SE   79725
3          EMIS_CRTC_2_SE   79436
4            EMIS_CRTC_DE   79670
5           EMIS_CRTC_SNO   79725
6          EMIS_CRTC_STUS   79681
7     EMIS_CRTC_UNAVBL_DE     361
8   EMIS_CRTC_UNAVBL_RESN      45
9                EMIS_GRD   23923
10      EMIS_PERM_STDR_CD   17746
11             EMIS_VHCTY   79519
12                   FUEL   79493
13                 MKR_NM   78956
14               MNFCT_NM   79554
15         ORGCAR_SRCMNNO   60648
16                PLOR_NM   29928
17     REPCAR_EMIS_CRTCNO   26100
18             REPCAR_VIN   55697
19          SAME_VHCTY_TY    9155
20                STRE_DE   79715
21           RECP_FILE_NM   79707
22                SRCMNNO       0

In [141]:
sdf3_1 = sdf3[slist3]
sdf3_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79670 entries, 0 to 79669
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DMSTC_IMP_MNFCTR_SE   78984 non-null  object
 1   EXHST_GAS_CERT_NO     79670 non-null  object
 2   EXHST_GAS_CERT_SE1    79670 non-null  object
 3   EXHST_GAS_CERT_SE2    79383 non-null  object
 4   EXHST_GAS_CERT_YMD    79615 non-null  float64
 5   EXHST_GAS_CERT_SN     79670 non-null  int64
 6   EXTGAS_CET_STS_CD     79626 non-null  float64
 7   EXTGAS_CET_UNVBL_YMD  360 non-null    float64
 8   EXTGAS_CET_UNVBL_REN  45 non-null     object
 9   EXHST_GAS_GRD         23869 non-null  object
 10  EXTGAS_CET_PRM_CRTCD  17691 non-null  object
 11  VHCTY_CD              79464 non-null  object
 12  FUEL_CD               79435 non-null  object
 13  MNFCTR_NM             78901 non-null  object
 14  MKR_NAME              79500 non-null  object
 15  MANP_MNG_NO           60648 non-null  object
 16  FBCTN_NTN_NM          29873 non-null  object
 17  RPRSVH_EXTGAS_CET_NO  26100 non-null  object
 18  RPRS_CAR_VIN          55697 non-null  object
 19  VHCTY_TY_CD           9113 non-null   object
 20  DATA_STRG_YMD         79660 non-null  object
dtypes: float64(3), int64(1), object(17)
memory usage: 12.8+ MB

In [142]:
scount3 = sdf3_1.count().reset_index()
scount3.columns = ['index', 'scount']
scount3

                   index  scount
0    DMSTC_IMP_MNFCTR_SE   78984
1      EXHST_GAS_CERT_NO   79670
2     EXHST_GAS_CERT_SE1   79670
3     EXHST_GAS_CERT_SE2   79383
4     EXHST_GAS_CERT_YMD   79615
5      EXHST_GAS_CERT_SN   79670
6      EXTGAS_CET_STS_CD   79626
7   EXTGAS_CET_UNVBL_YMD     360
8   EXTGAS_CET_UNVBL_REN      45
9          EXHST_GAS_GRD   23869
10  EXTGAS_CET_PRM_CRTCD   17691
11              VHCTY_CD   79464
12               FUEL_CD   79435
13             MNFCTR_NM   78901
14              MKR_NAME   79500
15           MANP_MNG_NO   60648
16          FBCTN_NTN_NM   29873
17  RPRSVH_EXTGAS_CET_NO   26100
18          RPRS_CAR_VIN   55697
19           VHCTY_TY_CD    9113
20         DATA_STRG_YMD   79660

In [143]:
oscount3 = pd.concat([ocount3, scount3], axis=1)
oscount3

                    index  ocount                 index   scount
0       DMSTC_INCM_MKR_SE   79038   DMSTC_IMP_MNFCTR_SE  78984.0
1             EMIS_CRTCNO   79725     EXHST_GAS_CERT_NO  79670.0
2          EMIS_CRTC_1_SE   79725    EXHST_GAS_CERT_SE1  79670.0
3          EMIS_CRTC_2_SE   79436    EXHST_GAS_CERT_SE2  79383.0
4            EMIS_CRTC_DE   79670    EXHST_GAS_CERT_YMD  79615.0
5           EMIS_CRTC_SNO   79725     EXHST_GAS_CERT_SN  79670.0
6          EMIS_CRTC_STUS   79681     EXTGAS_CET_STS_CD  79626.0
7     EMIS_CRTC_UNAVBL_DE     361  EXTGAS_CET_UNVBL_YMD    360.0
8   EMIS_CRTC_UNAVBL_RESN      45  EXTGAS_CET_UNVBL_REN     45.0
9                EMIS_GRD   23923         EXHST_GAS_GRD  23869.0
10      EMIS_PERM_STDR_CD   17746  EXTGAS_CET_PRM_CRTCD  17691.0
11             EMIS_VHCTY   79519              VHCTY_CD  79464.0
12                   FUEL   79493               FUEL_CD  79435.0
13                 MKR_NM   78956             MNFCTR_NM  78901.0
14               MNFCT_NM   79554              MKR_NAME  79500.0
15         ORGCAR_SRCMNNO   60648           MANP_MNG_NO  60648.0
16                PLOR_NM   29928          FBCTN_NTN_NM  29873.0
17     REPCAR_EMIS_CRTCNO   26100  RPRSVH_EXTGAS_CET_NO  26100.0
18             REPCAR_VIN   55697          RPRS_CAR_VIN  55697.0
19          SAME_VHCTY_TY    9155           VHCTY_TY_CD   9113.0
20                STRE_DE   79715         DATA_STRG_YMD  79660.0
21           RECP_FILE_NM   79707                   NaN      NaN
22                SRCMNNO       0                   NaN      NaN

In [144]:
oscount3['차이'] = oscount3['ocount'] - oscount3['scount']
oscount3

                    index  ocount                 index   scount    차이
0       DMSTC_INCM_MKR_SE   79038   DMSTC_IMP_MNFCTR_SE  78984.0  54.0
1             EMIS_CRTCNO   79725     EXHST_GAS_CERT_NO  79670.0  55.0
2          EMIS_CRTC_1_SE   79725    EXHST_GAS_CERT_SE1  79670.0  55.0
3          EMIS_CRTC_2_SE   79436    EXHST_GAS_CERT_SE2  79383.0  53.0
4            EMIS_CRTC_DE   79670    EXHST_GAS_CERT_YMD  79615.0  55.0
5           EMIS_CRTC_SNO   79725     EXHST_GAS_CERT_SN  79670.0  55.0
6          EMIS_CRTC_STUS   79681     EXTGAS_CET_STS_CD  79626.0  55.0
7     EMIS_CRTC_UNAVBL_DE     361  EXTGAS_CET_UNVBL_YMD    360.0   1.0
8   EMIS_CRTC_UNAVBL_RESN      45  EXTGAS_CET_UNVBL_REN     45.0   0.0
9                EMIS_GRD   23923         EXHST_GAS_GRD  23869.0  54.0
10      EMIS_PERM_STDR_CD   17746  EXTGAS_CET_PRM_CRTCD  17691.0  55.0
11             EMIS_VHCTY   79519              VHCTY_CD  79464.0  55.0
12                   FUEL   79493               FUEL_CD  79435.0  58.0
13                 MKR_NM   78956             MNFCTR_NM  78901.0  55.0
14               MNFCT_NM   79554              MKR_NAME  79500.0  54.0
15         ORGCAR_SRCMNNO   60648           MANP_MNG_NO  60648.0   0.0
16                PLOR_NM   29928          FBCTN_NTN_NM  29873.0  55.0
17     REPCAR_EMIS_CRTCNO   26100  RPRSVH_EXTGAS_CET_NO  26100.0   0.0
18             REPCAR_VIN   55697          RPRS_CAR_VIN  55697.0   0.0
19          SAME_VHCTY_TY    9155           VHCTY_TY_CD   9113.0  42.0
20                STRE_DE   79715         DATA_STRG_YMD  79660.0  55.0
21           RECP_FILE_NM   79707                   NaN      NaN   NaN
22                SRCMNNO       0                   NaN      NaN   NaN

### [출력]

In [145]:
texcel3 = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name3}_vs_{std_file_name3}.xlsx')
ocol3.to_excel(texcel3, sheet_name='ODS_col', index=False)
scol3.to_excel(texcel3, sheet_name='STD_col', index=False)
oscount3.to_excel(texcel3, sheet_name='count', index=False)
texcel3.save()

## 4\. 배출가스 인증시험

In [97]:
ods_file_name4 = 'ODS_CEG_EMIS_CERTI_TEST_MIG'
std_file_name4 = 'STD_CEG_EMIS_CERTI_TEST_MIG'
opath4 = os.path.join(ods_path, ods_file_name4 + '.csv')
spath4 = os.path.join(std_path, std_file_name4 + '.csv')
odf4 = pd.read_csv(opath4, low_memory=False)
sdf4 = pd.read_csv(spath4, low_memory=False)
print(odf4.columns)
print(sdf4.columns)
print(len(odf4.columns), len(sdf4.columns))
print(odf4.shape, sdf4.shape)

Index(['EMIS_CRTCNO', 'EMIS_CRTC_SNO', 'EMIS_TEST_MOD_VAL', 'CO_PERM_STDR_VAL',
       'CO_TEST_RSLT', 'NMOG_PERM_STDR_VAL', 'NMOG_TEST_RSLT',
       'NMHC_PERM_STDR_VAL', 'NMHC_TEST_RSLT', 'HC_PERM_STDR_VAL',
       'HC_TEST_RSLT', 'NOX_PERM_STDR_VAL', 'NOX_TEST_RSLT',
       'NMOG_NOX_PERM_STDR_VAL', 'NMOG_NOX_TEST_RSLT', 'HC_NOX_PERM_STDR_VAL',
       'HC_NOX_TEST_RSLT', 'PM_PERM_STDR_VAL', 'PM_TEST_RSLT',
       'PN_PERM_STDR_VAL', 'PN_TEST_RSLT', 'RECP_FILE_NM', 'STRE_DE'],
      dtype='object')
Index(['COX_PRMT_VAL', 'COX_TEST_RSLT', 'EXHST_GAS_CERT_NO',
       'EXHST_GAS_CERT_SN', 'FBVH_EXTGAS_TES_TYCD', 'HC3_NOX_PRMT_VAL',
       'HC3_NOX_TES_RSLTVL', 'HC3_PRMT_VAL', 'HC3_TEST_RSLT_VAL',
       'HC2_PRMT_VAL', 'HC2_TEST_RSLT_VAL', 'HC1_NOX_PRMT_VAL',
       'HC1_NOX_TES_RSLTVL', 'HC1_PRMT_VAL', 'HC_TEST_RSLT_VAL',
       'NOX_PRMT_VAL', 'NOX_TEST_RSLT_VAL', 'PM_CRTR_VAL', 'PM_CRTR',
       'PARTCL_CNT_CRTR_VAL', 'PN_CRTR'],
      dtype='object')
23 21
(86406, 23) (86406, 21)

### 컬럼 확인

In [98]:
olist4 = [
    'CO_PERM_STDR_VAL',
    'CO_TEST_RSLT', 
    'EMIS_CRTCNO', 
    'EMIS_CRTC_SNO', 
    'EMIS_TEST_MOD_VAL', 
    'HC_NOX_PERM_STDR_VAL',
    'HC_NOX_TEST_RSLT', 
    'HC_PERM_STDR_VAL',
    'HC_TEST_RSLT', 
    'NMHC_PERM_STDR_VAL', 
    'NMHC_TEST_RSLT', 
    'NMOG_NOX_PERM_STDR_VAL', 
    'NMOG_NOX_TEST_RSLT', 
    'NMOG_PERM_STDR_VAL', 
    'NMOG_TEST_RSLT',
    'NOX_PERM_STDR_VAL', 
    'NOX_TEST_RSLT',
    'PM_PERM_STDR_VAL', 
    'PM_TEST_RSLT',
    'PN_PERM_STDR_VAL', 
    'PN_TEST_RSLT', 

    'RECP_FILE_NM', 
    'STRE_DE'
    ]

odict4 = {
    '컬럼':olist4,
    '내용':
    ['일산화탄소 허용 기준 값', 
    '일산화탄소 시험 결과', 
    '배출가스 인증번호', 
    '배출가스 인증 일련번호', 
    '배출가스 시험 모드 값', 
    '탄화수소3 질소산화물 허용 기준 값', 
    '탄화수소3 질소산화물 시험 결과', 
    '탄화수소3 허용 기준 값', 
    '탄화수소3 시험 결과', 
    '탄화수소2 허용 기준 값', 
    '탄화수소2 시험 결과', 
    '탄화수소1 질소산화물 허용 기준 값', 
    '탄화수소1 질소산화물 시험 결과', 
    '탄화수소1 허용 기준 값', 
    '탄화수소1 시험 결과', 
    '질소산화물 허용 기준 값', 
    '질소산화물 시험 결과', 
    '입자상물질 허용 기준 값', 
    '입자상물질 시험 결과', 
    '입자개수 허용 기준 값', 
    '입자개수 시험 결과',
     
    '미정', 
    '미정']
    }

ocol4 = pd.DataFrame(odict4)
ocol4

                        컬럼                   내용
0         CO_PERM_STDR_VAL        일산화탄소 허용 기준 값
1             CO_TEST_RSLT          일산화탄소 시험 결과
2              EMIS_CRTCNO            배출가스 인증번호
3            EMIS_CRTC_SNO         배출가스 인증 일련번호
4        EMIS_TEST_MOD_VAL         배출가스 시험 모드 값
5     HC_NOX_PERM_STDR_VAL  탄화수소3 질소산화물 허용 기준 값
6         HC_NOX_TEST_RSLT    탄화수소3 질소산화물 시험 결과
7         HC_PERM_STDR_VAL        탄화수소3 허용 기준 값
8             HC_TEST_RSLT          탄화수소3 시험 결과
9       NMHC_PERM_STDR_VAL        탄화수소2 허용 기준 값
10          NMHC_TEST_RSLT          탄화수소2 시험 결과
11  NMOG_NOX_PERM_STDR_VAL  탄화수소1 질소산화물 허용 기준 값
12      NMOG_NOX_TEST_RSLT    탄화수소1 질소산화물 시험 결과
13      NMOG_PERM_STDR_VAL        탄화수소1 허용 기준 값
14          NMOG_TEST_RSLT          탄화수소1 시험 결과
15       NOX_PERM_STDR_VAL        질소산화물 허용 기준 값
16           NOX_TEST_RSLT          질소산화물 시험 결과
17        PM_PERM_STDR_VAL        입자상물질 허용 기준 값
18            PM_TEST_RSLT          입자상물질 시험 결과
19        PN_PERM_STDR_VAL         입자개수 허용 기준 값
20            PN_TEST_RSLT           입자개수 시험 결과
21            RECP_FILE_NM                   미정
22                 STRE_DE                   미정

In [100]:
slist4 = [
    'COX_PRMT_VAL', 
    'COX_TEST_RSLT', 
    'EXHST_GAS_CERT_NO',
    'EXHST_GAS_CERT_SN', 
    'FBVH_EXTGAS_TES_TYCD', 
    'HC3_NOX_PRMT_VAL',
    'HC3_NOX_TES_RSLTVL', 
    'HC3_PRMT_VAL', 
    'HC3_TEST_RSLT_VAL',
    'HC2_PRMT_VAL', 
    'HC2_TEST_RSLT_VAL', 
    'HC1_NOX_PRMT_VAL',
    'HC1_NOX_TES_RSLTVL', 
    'HC1_PRMT_VAL', 
    'HC_TEST_RSLT_VAL',
    'NOX_PRMT_VAL', 
    'NOX_TEST_RSLT_VAL', 
    'PM_CRTR_VAL', 
    'PM_CRTR',
    'PARTCL_CNT_CRTR_VAL', 
    'PN_CRTR'
    ]

sdict4 = {
    '컬럼':slist4,
    '내용':
    ['일산화탅소허용기준값', 
    '일산화탅소시험결과', 
    '배출가스인증번호', 
    '배출가스인증일련번호', 
    '제작차배출가스시험유형코드', 
    '탄화수소3질소산화물허용값', 
    '탄화수소3질소산화물시험결과값', 
    '탄화수소3허용값', 
    '탄화수소3시험결과값', 
    '탄화수소2허용값', 
    '탄화수소2시험결과값', 
    '탄화수소1질소산화물허용값', 
    '탄화수소1질소산화물시험결과값', 
    '탄화수소1허용값', 
    '탄화수소시험결과값', 
    '질소산화물허용값', 
    '질소산화물시험결과값', 
    'PM기준값', 
    'PM기준', 
    '입자개수기준값', 
    'PM기준']
    }

scol4 = pd.DataFrame(sdict4)
scol4

                      컬럼               내용
0           COX_PRMT_VAL       일산화탅소허용기준값
1          COX_TEST_RSLT        일산화탅소시험결과
2      EXHST_GAS_CERT_NO         배출가스인증번호
3      EXHST_GAS_CERT_SN       배출가스인증일련번호
4   FBVH_EXTGAS_TES_TYCD    제작차배출가스시험유형코드
5       HC3_NOX_PRMT_VAL    탄화수소3질소산화물허용값
6     HC3_NOX_TES_RSLTVL  탄화수소3질소산화물시험결과값
7           HC3_PRMT_VAL         탄화수소3허용값
8      HC3_TEST_RSLT_VAL       탄화수소3시험결과값
9           HC2_PRMT_VAL         탄화수소2허용값
10     HC2_TEST_RSLT_VAL       탄화수소2시험결과값
11      HC1_NOX_PRMT_VAL    탄화수소1질소산화물허용값
12    HC1_NOX_TES_RSLTVL  탄화수소1질소산화물시험결과값
13          HC1_PRMT_VAL         탄화수소1허용값
14      HC_TEST_RSLT_VAL        탄화수소시험결과값
15          NOX_PRMT_VAL         질소산화물허용값
16     NOX_TEST_RSLT_VAL       질소산화물시험결과값
17           PM_CRTR_VAL            PM기준값
18               PM_CRTR             PM기준
19   PARTCL_CNT_CRTR_VAL          입자개수기준값
20               PN_CRTR             PM기준

### 데이터 info

In [101]:
odf4_1 = odf4[olist4]
odf4_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86406 entries, 0 to 86405
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CO_PERM_STDR_VAL        16761 non-null  float64
 1   CO_TEST_RSLT            17868 non-null  float64
 2   EMIS_CRTCNO             86406 non-null  object
 3   EMIS_CRTC_SNO           86406 non-null  int64
 4   EMIS_TEST_MOD_VAL       85442 non-null  object
 5   HC_NOX_PERM_STDR_VAL    8513 non-null   float64
 6   HC_NOX_TEST_RSLT        8548 non-null   float64
 7   HC_PERM_STDR_VAL        12176 non-null  float64
 8   HC_TEST_RSLT            12236 non-null  float64
 9   NMHC_PERM_STDR_VAL      20 non-null     float64
 10  NMHC_TEST_RSLT          268 non-null    float64
 11  NMOG_NOX_PERM_STDR_VAL  4229 non-null   float64
 12  NMOG_NOX_TEST_RSLT      4783 non-null   float64
 13  NMOG_PERM_STDR_VAL      43 non-null     float64
 14  NMOG_TEST_RSLT          3116 non-null   float64
 15  NOX_PERM_STDR_VAL       13893 non-null  float64
 16  NOX_TEST_RSLT           16856 non-null  float64
 17  PM_PERM_STDR_VAL        2770 non-null   float64
 18  PM_TEST_RSLT            6460 non-null   float64
 19  PN_PERM_STDR_VAL        1978 non-null   float64
 20  PN_TEST_RSLT            0 non-null      float64
 21  RECP_FILE_NM            86406 non-null  object
 22  STRE_DE                 86406 non-null  object
dtypes: float64(18), int64(1), object(4)
memory usage: 15.2+ MB

In [105]:
ocount4 = odf4_1.count().reset_index()
ocount4.columns = ['oindex', 'ocount']
ocount4

                    oindex  ocount
0         CO_PERM_STDR_VAL   16761
1             CO_TEST_RSLT   17868
2              EMIS_CRTCNO   86406
3            EMIS_CRTC_SNO   86406
4        EMIS_TEST_MOD_VAL   85442
5     HC_NOX_PERM_STDR_VAL    8513
6         HC_NOX_TEST_RSLT    8548
7         HC_PERM_STDR_VAL   12176
8             HC_TEST_RSLT   12236
9       NMHC_PERM_STDR_VAL      20
10          NMHC_TEST_RSLT     268
11  NMOG_NOX_PERM_STDR_VAL    4229
12      NMOG_NOX_TEST_RSLT    4783
13      NMOG_PERM_STDR_VAL      43
14          NMOG_TEST_RSLT    3116
15       NOX_PERM_STDR_VAL   13893
16           NOX_TEST_RSLT   16856
17        PM_PERM_STDR_VAL    2770
18            PM_TEST_RSLT    6460
19        PN_PERM_STDR_VAL    1978
20            PN_TEST_RSLT       0
21            RECP_FILE_NM   86406
22                 STRE_DE   86406

In [103]:
sdf4_1 = sdf4[slist4]
sdf4_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86406 entries, 0 to 86405
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   COX_PRMT_VAL          16761 non-null  float64
 1   COX_TEST_RSLT         17868 non-null  float64
 2   EXHST_GAS_CERT_NO     86406 non-null  object
 3   EXHST_GAS_CERT_SN     86406 non-null  int64
 4   FBVH_EXTGAS_TES_TYCD  85442 non-null  object
 5   HC3_NOX_PRMT_VAL      8513 non-null   float64
 6   HC3_NOX_TES_RSLTVL    8548 non-null   float64
 7   HC3_PRMT_VAL          12176 non-null  float64
 8   HC3_TEST_RSLT_VAL     12236 non-null  float64
 9   HC2_PRMT_VAL          20 non-null     float64
 10  HC2_TEST_RSLT_VAL     268 non-null    float64
 11  HC1_NOX_PRMT_VAL      4229 non-null   float64
 12  HC1_NOX_TES_RSLTVL    4783 non-null   float64
 13  HC1_PRMT_VAL          43 non-null     float64
 14  HC_TEST_RSLT_VAL      3116 non-null   float64
 15  NOX_PRMT_VAL          13893 non-null  float64
 16  NOX_TEST_RSLT_VAL     16856 non-null  float64
 17  PM_CRTR_VAL           2770 non-null   float64
 18  PM_CRTR               6460 non-null   float64
 19  PARTCL_CNT_CRTR_VAL   1978 non-null   float64
 20  PN_CRTR               0 non-null      float64
dtypes: float64(18), int64(1), object(2)
memory usage: 13.8+ MB

In [106]:
scount4 = sdf4_1.count().reset_index()
scount4.columns = ['sindex', 'scount']
scount4

                  sindex  scount
0           COX_PRMT_VAL   16761
1          COX_TEST_RSLT   17868
2      EXHST_GAS_CERT_NO   86406
3      EXHST_GAS_CERT_SN   86406
4   FBVH_EXTGAS_TES_TYCD   85442
5       HC3_NOX_PRMT_VAL    8513
6     HC3_NOX_TES_RSLTVL    8548
7           HC3_PRMT_VAL   12176
8      HC3_TEST_RSLT_VAL   12236
9           HC2_PRMT_VAL      20
10     HC2_TEST_RSLT_VAL     268
11      HC1_NOX_PRMT_VAL    4229
12    HC1_NOX_TES_RSLTVL    4783
13          HC1_PRMT_VAL      43
14      HC_TEST_RSLT_VAL    3116
15          NOX_PRMT_VAL   13893
16     NOX_TEST_RSLT_VAL   16856
17           PM_CRTR_VAL    2770
18               PM_CRTR    6460
19   PARTCL_CNT_CRTR_VAL    1978
20               PN_CRTR       0

In [107]:
oscount4 = pd.concat([ocount4, scount4], axis=1)
oscount4

                    oindex  ocount                sindex   scount
0         CO_PERM_STDR_VAL   16761          COX_PRMT_VAL  16761.0
1             CO_TEST_RSLT   17868         COX_TEST_RSLT  17868.0
2              EMIS_CRTCNO   86406     EXHST_GAS_CERT_NO  86406.0
3            EMIS_CRTC_SNO   86406     EXHST_GAS_CERT_SN  86406.0
4        EMIS_TEST_MOD_VAL   85442  FBVH_EXTGAS_TES_TYCD  85442.0
5     HC_NOX_PERM_STDR_VAL    8513      HC3_NOX_PRMT_VAL   8513.0
6         HC_NOX_TEST_RSLT    8548    HC3_NOX_TES_RSLTVL   8548.0
7         HC_PERM_STDR_VAL   12176          HC3_PRMT_VAL  12176.0
8             HC_TEST_RSLT   12236     HC3_TEST_RSLT_VAL  12236.0
9       NMHC_PERM_STDR_VAL      20          HC2_PRMT_VAL     20.0
10          NMHC_TEST_RSLT     268     HC2_TEST_RSLT_VAL    268.0
11  NMOG_NOX_PERM_STDR_VAL    4229      HC1_NOX_PRMT_VAL   4229.0
12      NMOG_NOX_TEST_RSLT    4783    HC1_NOX_TES_RSLTVL   4783.0
13      NMOG_PERM_STDR_VAL      43          HC1_PRMT_VAL     43.0
14          NMOG_TEST_RSLT    3116      HC_TEST_RSLT_VAL   3116.0
15       NOX_PERM_STDR_VAL   13893          NOX_PRMT_VAL  13893.0
16           NOX_TEST_RSLT   16856     NOX_TEST_RSLT_VAL  16856.0
17        PM_PERM_STDR_VAL    2770           PM_CRTR_VAL   2770.0
18            PM_TEST_RSLT    6460               PM_CRTR   6460.0
19        PN_PERM_STDR_VAL    1978   PARTCL_CNT_CRTR_VAL   1978.0
20            PN_TEST_RSLT       0               PN_CRTR      0.0
21            RECP_FILE_NM   86406                   NaN      NaN
22                 STRE_DE   86406                   NaN      NaN

In [108]:
oscount4['차이'] = oscount4['ocount'] - oscount4['scount']
oscount4

                    oindex  ocount                sindex   scount   차이
0         CO_PERM_STDR_VAL   16761          COX_PRMT_VAL  16761.0  0.0
1             CO_TEST_RSLT   17868         COX_TEST_RSLT  17868.0  0.0
2              EMIS_CRTCNO   86406     EXHST_GAS_CERT_NO  86406.0  0.0
3            EMIS_CRTC_SNO   86406     EXHST_GAS_CERT_SN  86406.0  0.0
4        EMIS_TEST_MOD_VAL   85442  FBVH_EXTGAS_TES_TYCD  85442.0  0.0
5     HC_NOX_PERM_STDR_VAL    8513      HC3_NOX_PRMT_VAL   8513.0  0.0
6         HC_NOX_TEST_RSLT    8548    HC3_NOX_TES_RSLTVL   8548.0  0.0
7         HC_PERM_STDR_VAL   12176          HC3_PRMT_VAL  12176.0  0.0
8             HC_TEST_RSLT   12236     HC3_TEST_RSLT_VAL  12236.0  0.0
9       NMHC_PERM_STDR_VAL      20          HC2_PRMT_VAL     20.0  0.0
10          NMHC_TEST_RSLT     268     HC2_TEST_RSLT_VAL    268.0  0.0
11  NMOG_NOX_PERM_STDR_VAL    4229      HC1_NOX_PRMT_VAL   4229.0  0.0
12      NMOG_NOX_TEST_RSLT    4783    HC1_NOX_TES_RSLTVL   4783.0  0.0
13      NMOG_PERM_STDR_VAL      43          HC1_PRMT_VAL     43.0  0.0
14          NMOG_TEST_RSLT    3116      HC_TEST_RSLT_VAL   3116.0  0.0
15       NOX_PERM_STDR_VAL   13893          NOX_PRMT_VAL  13893.0  0.0
16           NOX_TEST_RSLT   16856     NOX_TEST_RSLT_VAL  16856.0  0.0
17        PM_PERM_STDR_VAL    2770           PM_CRTR_VAL   2770.0  0.0
18            PM_TEST_RSLT    6460               PM_CRTR   6460.0  0.0
19        PN_PERM_STDR_VAL    1978   PARTCL_CNT_CRTR_VAL   1978.0  0.0
20            PN_TEST_RSLT       0               PN_CRTR      0.0  0.0
21            RECP_FILE_NM   86406                   NaN      NaN  NaN
22                 STRE_DE   86406                   NaN      NaN  NaN

### [출력]

In [109]:
texcel4 = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name4}_vs_{std_file_name4}.xlsx')
ocol4.to_excel(texcel4, sheet_name='ODS_col', index=False)
scol4.to_excel(texcel4, sheet_name='STD_col', index=False)
oscount4.to_excel(texcel4, sheet_name='count', index=False)
texcel4.save()

## 5\. [e]배출가스인증 자동차정보
- 파일 없음 : STD_CEG_EMIS_CERTI_VEH_MIG.csv

In [110]:
ods_file_name5 = 'ODS_CEG_EMIS_CERTI_VEH_MIG'
std_file_name5 = 'STD_CEG_EMIS_CERTI_VEH_MIG'
opath5 = os.path.join(ods_path, ods_file_name5 + '.csv')
spath5 = os.path.join(std_path, std_file_name5 + '.csv')
odf5 = pd.read_csv(opath5, low_memory=False)
sdf5 = pd.read_csv(spath5, low_memory=False)
print(odf5.columns)
print(sdf5.columns)
print(len(odf5.columns), len(sdf5.columns))
print(odf5.shape, sdf5.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/STD\\STD_CEG_EMIS_CERTI_VEH_MIG.csv'

### 컬럼 확인

In [ ]:
olist5 = [
    'CO_PERM_STDR_VAL',
    'CO_TEST_RSLT', 
    'EMIS_CRTCNO', 
    'EMIS_CRTC_SNO', 
    'EMIS_TEST_MOD_VAL', 
    'HC_NOX_PERM_STDR_VAL',
    'HC_NOX_TEST_RSLT', 
    'HC_PERM_STDR_VAL',
    'HC_TEST_RSLT', 
    'NMHC_PERM_STDR_VAL', 
    'NMHC_TEST_RSLT', 
    'NMOG_NOX_PERM_STDR_VAL', 
    'NMOG_NOX_TEST_RSLT', 
    'NMOG_PERM_STDR_VAL', 
    'NMOG_TEST_RSLT',
    'NOX_PERM_STDR_VAL', 
    'NOX_TEST_RSLT',
    'PM_PERM_STDR_VAL', 
    'PM_TEST_RSLT',
    'PN_PERM_STDR_VAL', 
    'PN_TEST_RSLT', 

    'RECP_FILE_NM', 
    'STRE_DE'
    ]

odict5 = {
    '컬럼':olist5,
    '내용':
    ['일산화탄소 허용 기준 값', 
    '일산화탄소 시험 결과', 
    '배출가스 인증번호', 
    '배출가스 인증 일련번호', 
    '배출가스 시험 모드 값', 
    '탄화수소3 질소산화물 허용 기준 값', 
    '탄화수소3 질소산화물 시험 결과', 
    '탄화수소3 허용 기준 값', 
    '탄화수소3 시험 결과', 
    '탄화수소2 허용 기준 값', 
    '탄화수소2 시험 결과', 
    '탄화수소1 질소산화물 허용 기준 값', 
    '탄화수소1 질소산화물 시험 결과', 
    '탄화수소1 허용 기준 값', 
    '탄화수소1 시험 결과', 
    '질소산화물 허용 기준 값', 
    '질소산화물 시험 결과', 
    '입자상물질 허용 기준 값', 
    '입자상물질 시험 결과', 
    '입자개수 허용 기준 값', 
    '입자개수 시험 결과',
     
    '미정', 
    '미정']
    }

ocol5 = pd.DataFrame(odict5)
ocol5

                        컬럼                   내용
0         CO_PERM_STDR_VAL        일산화탄소 허용 기준 값
1             CO_TEST_RSLT          일산화탄소 시험 결과
2              EMIS_CRTCNO            배출가스 인증번호
3            EMIS_CRTC_SNO         배출가스 인증 일련번호
4        EMIS_TEST_MOD_VAL         배출가스 시험 모드 값
5     HC_NOX_PERM_STDR_VAL  탄화수소3 질소산화물 허용 기준 값
6         HC_NOX_TEST_RSLT    탄화수소3 질소산화물 시험 결과
7         HC_PERM_STDR_VAL        탄화수소3 허용 기준 값
8             HC_TEST_RSLT          탄화수소3 시험 결과
9       NMHC_PERM_STDR_VAL        탄화수소2 허용 기준 값
10          NMHC_TEST_RSLT          탄화수소2 시험 결과
11  NMOG_NOX_PERM_STDR_VAL  탄화수소1 질소산화물 허용 기준 값
12      NMOG_NOX_TEST_RSLT    탄화수소1 질소산화물 시험 결과
13      NMOG_PERM_STDR_VAL        탄화수소1 허용 기준 값
14          NMOG_TEST_RSLT          탄화수소1 시험 결과
15       NOX_PERM_STDR_VAL        질소산화물 허용 기준 값
16           NOX_TEST_RSLT          질소산화물 시험 결과
17        PM_PERM_STDR_VAL        입자상물질 허용 기준 값
18            PM_TEST_RSLT          입자상물질 시험 결과
19        PN_PERM_STDR_VAL         입자개수 허용 기준 값
20            PN_TEST_RSLT           입자개수 시험 결과
21            RECP_FILE_NM                   미정
22                 STRE_DE                   미정

In [ ]:
slist5 = [
    'COX_PRMT_VAL', 
    'COX_TEST_RSLT', 
    'EXHST_GAS_CERT_NO',
    'EXHST_GAS_CERT_SN', 
    'FBVH_EXTGAS_TES_TYCD', 
    'HC3_NOX_PRMT_VAL',
    'HC3_NOX_TES_RSLTVL', 
    'HC3_PRMT_VAL', 
    'HC3_TEST_RSLT_VAL',
    'HC2_PRMT_VAL', 
    'HC2_TEST_RSLT_VAL', 
    'HC1_NOX_PRMT_VAL',
    'HC1_NOX_TES_RSLTVL', 
    'HC1_PRMT_VAL', 
    'HC_TEST_RSLT_VAL',
    'NOX_PRMT_VAL', 
    'NOX_TEST_RSLT_VAL', 
    'PM_CRTR_VAL', 
    'PM_CRTR',
    'PARTCL_CNT_CRTR_VAL', 
    'PN_CRTR'
    ]

sdict5 = {
    '컬럼':slist5,
    '내용':
    ['일산화탅소허용기준값', 
    '일산화탅소시험결과', 
    '배출가스인증번호', 
    '배출가스인증일련번호', 
    '제작차배출가스시험유형코드', 
    '탄화수소3질소산화물허용값', 
    '탄화수소3질소산화물시험결과값', 
    '탄화수소3허용값', 
    '탄화수소3시험결과값', 
    '탄화수소2허용값', 
    '탄화수소2시험결과값', 
    '탄화수소1질소산화물허용값', 
    '탄화수소1질소산화물시험결과값', 
    '탄화수소1허용값', 
    '탄화수소시험결과값', 
    '질소산화물허용값', 
    '질소산화물시험결과값', 
    'PM기준값', 
    'PM기준', 
    '입자개수기준값', 
    'PM기준']
    }

scol5 = pd.DataFrame(sdict5)
scol5

                      컬럼               내용
0           COX_PRMT_VAL       일산화탅소허용기준값
1          COX_TEST_RSLT        일산화탅소시험결과
2      EXHST_GAS_CERT_NO         배출가스인증번호
3      EXHST_GAS_CERT_SN       배출가스인증일련번호
4   FBVH_EXTGAS_TES_TYCD    제작차배출가스시험유형코드
5       HC3_NOX_PRMT_VAL    탄화수소3질소산화물허용값
6     HC3_NOX_TES_RSLTVL  탄화수소3질소산화물시험결과값
7           HC3_PRMT_VAL         탄화수소3허용값
8      HC3_TEST_RSLT_VAL       탄화수소3시험결과값
9           HC2_PRMT_VAL         탄화수소2허용값
10     HC2_TEST_RSLT_VAL       탄화수소2시험결과값
11      HC1_NOX_PRMT_VAL    탄화수소1질소산화물허용값
12    HC1_NOX_TES_RSLTVL  탄화수소1질소산화물시험결과값
13          HC1_PRMT_VAL         탄화수소1허용값
14      HC_TEST_RSLT_VAL        탄화수소시험결과값
15          NOX_PRMT_VAL         질소산화물허용값
16     NOX_TEST_RSLT_VAL       질소산화물시험결과값
17           PM_CRTR_VAL            PM기준값
18               PM_CRTR             PM기준
19   PARTCL_CNT_CRTR_VAL          입자개수기준값
20               PN_CRTR             PM기준

### 데이터 info

In [ ]:
odf5_1 = odf5[olist5]
odf5_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86406 entries, 0 to 86405
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CO_PERM_STDR_VAL        16761 non-null  float64
 1   CO_TEST_RSLT            17868 non-null  float64
 2   EMIS_CRTCNO             86406 non-null  object
 3   EMIS_CRTC_SNO           86406 non-null  int64
 4   EMIS_TEST_MOD_VAL       85442 non-null  object
 5   HC_NOX_PERM_STDR_VAL    8513 non-null   float64
 6   HC_NOX_TEST_RSLT        8548 non-null   float64
 7   HC_PERM_STDR_VAL        12176 non-null  float64
 8   HC_TEST_RSLT            12236 non-null  float64
 9   NMHC_PERM_STDR_VAL      20 non-null     float64
 10  NMHC_TEST_RSLT          268 non-null    float64
 11  NMOG_NOX_PERM_STDR_VAL  4229 non-null   float64
 12  NMOG_NOX_TEST_RSLT      4783 non-null   float64
 13  NMOG_PERM_STDR_VAL      43 non-null     float64
 14  NMOG_TEST_RSLT          3116 non-null   float64
 15  NOX_PERM_STDR_VAL       13893 non-null  float64
 16  NOX_TEST_RSLT           16856 non-null  float64
 17  PM_PERM_STDR_VAL        2770 non-null   float64
 18  PM_TEST_RSLT            6460 non-null   float64
 19  PN_PERM_STDR_VAL        1978 non-null   float64
 20  PN_TEST_RSLT            0 non-null      float64
 21  RECP_FILE_NM            86406 non-null  object
 22  STRE_DE                 86406 non-null  object
dtypes: float64(18), int64(1), object(4)
memory usage: 15.2+ MB

In [ ]:
ocount5 = odf5_1.count().reset_index()
ocount5.columns = ['oindex', 'ocount']
ocount5

                    oindex  ocount
0         CO_PERM_STDR_VAL   16761
1             CO_TEST_RSLT   17868
2              EMIS_CRTCNO   86406
3            EMIS_CRTC_SNO   86406
4        EMIS_TEST_MOD_VAL   85442
5     HC_NOX_PERM_STDR_VAL    8513
6         HC_NOX_TEST_RSLT    8548
7         HC_PERM_STDR_VAL   12176
8             HC_TEST_RSLT   12236
9       NMHC_PERM_STDR_VAL      20
10          NMHC_TEST_RSLT     268
11  NMOG_NOX_PERM_STDR_VAL    4229
12      NMOG_NOX_TEST_RSLT    4783
13      NMOG_PERM_STDR_VAL      43
14          NMOG_TEST_RSLT    3116
15       NOX_PERM_STDR_VAL   13893
16           NOX_TEST_RSLT   16856
17        PM_PERM_STDR_VAL    2770
18            PM_TEST_RSLT    6460
19        PN_PERM_STDR_VAL    1978
20            PN_TEST_RSLT       0
21            RECP_FILE_NM   86406
22                 STRE_DE   86406

In [ ]:
sdf5_1 = sdf5[slist5]
sdf5_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86406 entries, 0 to 86405
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   COX_PRMT_VAL          16761 non-null  float64
 1   COX_TEST_RSLT         17868 non-null  float64
 2   EXHST_GAS_CERT_NO     86406 non-null  object
 3   EXHST_GAS_CERT_SN     86406 non-null  int64
 4   FBVH_EXTGAS_TES_TYCD  85442 non-null  object
 5   HC3_NOX_PRMT_VAL      8513 non-null   float64
 6   HC3_NOX_TES_RSLTVL    8548 non-null   float64
 7   HC3_PRMT_VAL          12176 non-null  float64
 8   HC3_TEST_RSLT_VAL     12236 non-null  float64
 9   HC2_PRMT_VAL          20 non-null     float64
 10  HC2_TEST_RSLT_VAL     268 non-null    float64
 11  HC1_NOX_PRMT_VAL      4229 non-null   float64
 12  HC1_NOX_TES_RSLTVL    4783 non-null   float64
 13  HC1_PRMT_VAL          43 non-null     float64
 14  HC_TEST_RSLT_VAL      3116 non-null   float64
 15  NOX_PRMT_VAL          13893 non-null  float64
 16  NOX_TEST_RSLT_VAL     16856 non-null  float64
 17  PM_CRTR_VAL           2770 non-null   float64
 18  PM_CRTR               6460 non-null   float64
 19  PARTCL_CNT_CRTR_VAL   1978 non-null   float64
 20  PN_CRTR               0 non-null      float64
dtypes: float64(18), int64(1), object(2)
memory usage: 13.8+ MB

In [ ]:
scount5 = sdf5_1.count().reset_index()
scount5.columns = ['sindex', 'scount']
scount5

                  sindex  scount
0           COX_PRMT_VAL   16761
1          COX_TEST_RSLT   17868
2      EXHST_GAS_CERT_NO   86406
3      EXHST_GAS_CERT_SN   86406
4   FBVH_EXTGAS_TES_TYCD   85442
5       HC3_NOX_PRMT_VAL    8513
6     HC3_NOX_TES_RSLTVL    8548
7           HC3_PRMT_VAL   12176
8      HC3_TEST_RSLT_VAL   12236
9           HC2_PRMT_VAL      20
10     HC2_TEST_RSLT_VAL     268
11      HC1_NOX_PRMT_VAL    4229
12    HC1_NOX_TES_RSLTVL    4783
13          HC1_PRMT_VAL      43
14      HC_TEST_RSLT_VAL    3116
15          NOX_PRMT_VAL   13893
16     NOX_TEST_RSLT_VAL   16856
17           PM_CRTR_VAL    2770
18               PM_CRTR    6460
19   PARTCL_CNT_CRTR_VAL    1978
20               PN_CRTR       0

In [ ]:
oscount5 = pd.concat([ocount5, scount5], axis=1)
oscount5

                    oindex  ocount                sindex   scount
0         CO_PERM_STDR_VAL   16761          COX_PRMT_VAL  16761.0
1             CO_TEST_RSLT   17868         COX_TEST_RSLT  17868.0
2              EMIS_CRTCNO   86406     EXHST_GAS_CERT_NO  86406.0
3            EMIS_CRTC_SNO   86406     EXHST_GAS_CERT_SN  86406.0
4        EMIS_TEST_MOD_VAL   85442  FBVH_EXTGAS_TES_TYCD  85442.0
5     HC_NOX_PERM_STDR_VAL    8513      HC3_NOX_PRMT_VAL   8513.0
6         HC_NOX_TEST_RSLT    8548    HC3_NOX_TES_RSLTVL   8548.0
7         HC_PERM_STDR_VAL   12176          HC3_PRMT_VAL  12176.0
8             HC_TEST_RSLT   12236     HC3_TEST_RSLT_VAL  12236.0
9       NMHC_PERM_STDR_VAL      20          HC2_PRMT_VAL     20.0
10          NMHC_TEST_RSLT     268     HC2_TEST_RSLT_VAL    268.0
11  NMOG_NOX_PERM_STDR_VAL    4229      HC1_NOX_PRMT_VAL   4229.0
12      NMOG_NOX_TEST_RSLT    4783    HC1_NOX_TES_RSLTVL   4783.0
13      NMOG_PERM_STDR_VAL      43          HC1_PRMT_VAL     43.0
14          NMOG_TEST_RSLT    3116      HC_TEST_RSLT_VAL   3116.0
15       NOX_PERM_STDR_VAL   13893          NOX_PRMT_VAL  13893.0
16           NOX_TEST_RSLT   16856     NOX_TEST_RSLT_VAL  16856.0
17        PM_PERM_STDR_VAL    2770           PM_CRTR_VAL   2770.0
18            PM_TEST_RSLT    6460               PM_CRTR   6460.0
19        PN_PERM_STDR_VAL    1978   PARTCL_CNT_CRTR_VAL   1978.0
20            PN_TEST_RSLT       0               PN_CRTR      0.0
21            RECP_FILE_NM   86406                   NaN      NaN
22                 STRE_DE   86406                   NaN      NaN

In [ ]:
oscount5['차이'] = oscount5['ocount'] - oscount5['scount']
oscount5

                    oindex  ocount                sindex   scount   차이
0         CO_PERM_STDR_VAL   16761          COX_PRMT_VAL  16761.0  0.0
1             CO_TEST_RSLT   17868         COX_TEST_RSLT  17868.0  0.0
2              EMIS_CRTCNO   86406     EXHST_GAS_CERT_NO  86406.0  0.0
3            EMIS_CRTC_SNO   86406     EXHST_GAS_CERT_SN  86406.0  0.0
4        EMIS_TEST_MOD_VAL   85442  FBVH_EXTGAS_TES_TYCD  85442.0  0.0
5     HC_NOX_PERM_STDR_VAL    8513      HC3_NOX_PRMT_VAL   8513.0  0.0
6         HC_NOX_TEST_RSLT    8548    HC3_NOX_TES_RSLTVL   8548.0  0.0
7         HC_PERM_STDR_VAL   12176          HC3_PRMT_VAL  12176.0  0.0
8             HC_TEST_RSLT   12236     HC3_TEST_RSLT_VAL  12236.0  0.0
9       NMHC_PERM_STDR_VAL      20          HC2_PRMT_VAL     20.0  0.0
10          NMHC_TEST_RSLT     268     HC2_TEST_RSLT_VAL    268.0  0.0
11  NMOG_NOX_PERM_STDR_VAL    4229      HC1_NOX_PRMT_VAL   4229.0  0.0
12      NMOG_NOX_TEST_RSLT    4783    HC1_NOX_TES_RSLTVL   4783.0  0.0
13      NMOG_PERM_STDR_VAL      43          HC1_PRMT_VAL     43.0  0.0
14          NMOG_TEST_RSLT    3116      HC_TEST_RSLT_VAL   3116.0  0.0
15       NOX_PERM_STDR_VAL   13893          NOX_PRMT_VAL  13893.0  0.0
16           NOX_TEST_RSLT   16856     NOX_TEST_RSLT_VAL  16856.0  0.0
17        PM_PERM_STDR_VAL    2770           PM_CRTR_VAL   2770.0  0.0
18            PM_TEST_RSLT    6460               PM_CRTR   6460.0  0.0
19        PN_PERM_STDR_VAL    1978   PARTCL_CNT_CRTR_VAL   1978.0  0.0
20            PN_TEST_RSLT       0               PN_CRTR      0.0  0.0
21            RECP_FILE_NM   86406                   NaN      NaN  NaN
22                 STRE_DE   86406                   NaN      NaN  NaN

### [출력]

In [ ]:
texcel5 = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name5}_vs_{std_file_name5}.xlsx')
ocol5.to_excel(texcel5, sheet_name='ODS_col', index=False)
scol5.to_excel(texcel5, sheet_name='STD_col', index=False)
oscount5.to_excel(texcel5, sheet_name='count', index=False)
texcel5.save()

## 6\. CEG_EMIS_STD_MIG

In [146]:
ods_file_name = 'ODS_CEG_EMIS_STD_MIG'
std_file_name = 'STD_CEG_EMIS_STD_MIG'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

21 21
(1212, 21) (1212, 21)

In [147]:
odf.columns.to_list()

['EMIS_PERM_STDR_CD',
 'EMIS_PERM_STDR_SML_SE',
 'FUEL_GRP',
 'EMIS_VHCTY',
 'TEST_BGIN_WGHT',
 'TEST_END_WGHT',
 'APLI_DE',
 'EMIS_TEST_MOD_VAL',
 'CO_PERM_STDR_VAL',
 'NMOG_PERM_STDR_VAL',
 'NMHC_PERM_STDR_VAL',
 'HC_PERM_STDR_VAL',
 'NOX_PERM_STDR_VAL',
 'NMOG_NOX_PERM_STDR_VAL',
 'HC_NOX_PERM_STDR_VAL',
 'PM_PERM_STDR_VAL',
 'PN_PERM_STDR_VAL',
 'EMIS_PERM_STDR_SE',
 'EMIS_GRD_USE_YN',
 'EMIS_GRD',
 'EMIS_PERM_STDR_LEVL']

In [148]:
sdf.columns.to_list()

['APLCN_YMD',
 'COX_PRMT_VAL',
 'EXHST_GAS_GRD_CD',
 'EXHST_GAS_GRD_USE_YN',
 'EXHST_GAS_CERT_PRMT_CRTR_CD',
 'EXHST_GAS_CERT_PRMT_CRTR_LEVL',
 'EXHST_GAS_CERT_PRMT_CRTR_SE',
 'EXHST_GAS_CERT_PRMT_CRTRSCL_SE',
 'EXHST_GAS_TEST_MOD',
 'EXHST_GAS_INSP_VHCTY',
 'FUEL_CL_CD',
 'HC3_NOX_PRMT_VAL',
 'HC3_PRMT_VAL',
 'HC2_PRMT_VAL',
 'HC1_NOX_PRMT_VAL',
 'HC1_PRMT_VAL',
 'NOX_PRMT_VAL',
 'PARTCLT_PRMT_VAL',
 'PARTCL_CNT_CRTR_VAL',
 'TEST_BGNG_WGHT',
 'TEST_END_WGHT']

### 컬럼 확인

In [ ]:
olist = [
    'EMIS_PERM_STDR_CD',
    'EMIS_PERM_STDR_SML_SE',
    'FUEL_GRP',
    'EMIS_VHCTY',
    'TEST_BGIN_WGHT',
    'TEST_END_WGHT',
    'APLI_DE',
    'EMIS_TEST_MOD_VAL',
    'CO_PERM_STDR_VAL',
    'NMOG_PERM_STDR_VAL',
    'NMHC_PERM_STDR_VAL',
    'HC_PERM_STDR_VAL',
    'NOX_PERM_STDR_VAL',
    'NMOG_NOX_PERM_STDR_VAL',
    'HC_NOX_PERM_STDR_VAL',
    'PM_PERM_STDR_VAL',
    'PN_PERM_STDR_VAL',
    'EMIS_PERM_STDR_SE',
    'EMIS_GRD_USE_YN',
    'EMIS_GRD',
    'EMIS_PERM_STDR_LEVL'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정']
    }

ocol = pd.DataFrame(odict)
ocol

                             컬럼                내용
0          ELPDSRC_LST_CNFRM_YN        조기폐차최종승인YN
1               ELPDSRC_STUS_CD          조기폐차상태코드
2                       ERSR_DE              말소일자
3                 MNTNG_IMPR_YN  저감장치 미개발(부착불가)여부
4                     RCPT_SIDO              접수시도
..                          ...               ...
172        PFMINPC_BUFFER_DVICE                미정
173              PFMINPC_WINDOW                미정
174                PFMINPC_TIRE                미정
175        PFMINPC_ASSMI_DEVICE                미정
176  PFMINPC_ELPDSRC_GNRLZ_RESN                미정

[177 rows x 2 columns]

In [149]:
slist = [
    'APLCN_YMD',
    'COX_PRMT_VAL',
    'EXHST_GAS_GRD_CD',
    'EXHST_GAS_GRD_USE_YN',
    'EXHST_GAS_CERT_PRMT_CRTR_CD',
    'EXHST_GAS_CERT_PRMT_CRTR_LEVL',
    'EXHST_GAS_CERT_PRMT_CRTR_SE',
    'EXHST_GAS_CERT_PRMT_CRTRSCL_SE',
    'EXHST_GAS_TEST_MOD',
    'EXHST_GAS_INSP_VHCTY',
    'FUEL_CL_CD',
    'HC3_NOX_PRMT_VAL',
    'HC3_PRMT_VAL',
    'HC2_PRMT_VAL',
    'HC1_NOX_PRMT_VAL',
    'HC1_PRMT_VAL',
    'NOX_PRMT_VAL',
    'PARTCLT_PRMT_VAL',
    'PARTCL_CNT_CRTR_VAL',
    'TEST_BGNG_WGHT',
    'TEST_END_WGHT'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정']
    }

scol = pd.DataFrame(sdict)
scol

                                컬럼  내용
0                        APLCN_YMD  미정
1                     COX_PRMT_VAL  미정
2                 EXHST_GAS_GRD_CD  미정
3             EXHST_GAS_GRD_USE_YN  미정
4      EXHST_GAS_CERT_PRMT_CRTR_CD  미정
5    EXHST_GAS_CERT_PRMT_CRTR_LEVL  미정
6      EXHST_GAS_CERT_PRMT_CRTR_SE  미정
7   EXHST_GAS_CERT_PRMT_CRTRSCL_SE  미정
8               EXHST_GAS_TEST_MOD  미정
9             EXHST_GAS_INSP_VHCTY  미정
10                      FUEL_CL_CD  미정
11                HC3_NOX_PRMT_VAL  미정
12                    HC3_PRMT_VAL  미정
13                    HC2_PRMT_VAL  미정
14                HC1_NOX_PRMT_VAL  미정
15                    HC1_PRMT_VAL  미정
16                    NOX_PRMT_VAL  미정
17                PARTCLT_PRMT_VAL  미정
18             PARTCL_CNT_CRTR_VAL  미정
19                  TEST_BGNG_WGHT  미정
20                   TEST_END_WGHT  미정

### 데이터 info

In [ ]:
odf2 = odf[olist]
odf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 770311 entries, 0 to 770310
Columns: 177 entries, ELPDSRC_LST_CNFRM_YN to PFMINPC_ELPDSRC_GNRLZ_RESN
dtypes: float64(56), int64(3), object(118)
memory usage: 1.0+ GB

In [ ]:
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount

                         oindex  ocount
0          ELPDSRC_LST_CNFRM_YN  680625
1               ELPDSRC_STUS_CD  770311
2                       ERSR_DE  684061
3                 MNTNG_IMPR_YN   97839
4                     RCPT_SIDO  769418
..                          ...     ...
172        PFMINPC_BUFFER_DVICE   11734
173              PFMINPC_WINDOW   11734
174                PFMINPC_TIRE   11734
175        PFMINPC_ASSMI_DEVICE   11734
176  PFMINPC_ELPDSRC_GNRLZ_RESN       0

[177 rows x 2 columns]

In [ ]:
sdf2 = sdf[slist]
sdf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 770117 entries, 0 to 770116
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ELPDSRC_LST_APRV_YN    679295 non-null  object
 1   ELPDSRC_STTS_CD        770117 non-null  object
 2   ERSR_YMD               683275 non-null  float64
 3   RDCDVC_EXTRNS_YN       97645 non-null   object
 4   STDG_CTPV_NM           769224 non-null  object
 5   LEM_KND_CD             770117 non-null  object
 6   SCCAR_REG_DRVNG_DSNC   769749 non-null  float64
 7   VHRNO                  770117 non-null  object
 8   VIN                    770117 non-null  object
 9   CRTN_DT                770117 non-null  int64
 10  STDG_SGG_NM            769188 non-null  object
 11  SCRCAR_ENTRPS_NM       682680 non-null  object
 12  ELPDSRC_LAST_APRV_YMD  679297 non-null  float64
 13  SBSIDY_TRGT_YN         765430 non-null  object
 14  ELPDSRC_MNG_NO         770117 non-null  int64
dtypes: float64(3), int64(2), object(10)
memory usage: 88.1+ MB

In [ ]:
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount

                   sindex  scount
0     ELPDSRC_LST_APRV_YN  679295
1         ELPDSRC_STTS_CD  770117
2                ERSR_YMD  683275
3        RDCDVC_EXTRNS_YN   97645
4            STDG_CTPV_NM  769224
5              LEM_KND_CD  770117
6    SCCAR_REG_DRVNG_DSNC  769749
7                   VHRNO  770117
8                     VIN  770117
9                 CRTN_DT  770117
10            STDG_SGG_NM  769188
11       SCRCAR_ENTRPS_NM  682680
12  ELPDSRC_LAST_APRV_YMD  679297
13         SBSIDY_TRGT_YN  765430
14         ELPDSRC_MNG_NO  770117

In [ ]:
oscount = pd.concat([ocount, scount], axis=1)
oscount

                         oindex  ocount               sindex    scount
0          ELPDSRC_LST_CNFRM_YN  680625  ELPDSRC_LST_APRV_YN  679295.0
1               ELPDSRC_STUS_CD  770311      ELPDSRC_STTS_CD  770117.0
2                       ERSR_DE  684061             ERSR_YMD  683275.0
3                 MNTNG_IMPR_YN   97839     RDCDVC_EXTRNS_YN   97645.0
4                     RCPT_SIDO  769418         STDG_CTPV_NM  769224.0
..                          ...     ...                  ...       ...
172        PFMINPC_BUFFER_DVICE   11734                  NaN       NaN
173              PFMINPC_WINDOW   11734                  NaN       NaN
174                PFMINPC_TIRE   11734                  NaN       NaN
175        PFMINPC_ASSMI_DEVICE   11734                  NaN       NaN
176  PFMINPC_ELPDSRC_GNRLZ_RESN       0                  NaN       NaN

[177 rows x 4 columns]

In [ ]:
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount

                         oindex  ocount               sindex    scount      차이
0          ELPDSRC_LST_CNFRM_YN  680625  ELPDSRC_LST_APRV_YN  679295.0  1330.0
1               ELPDSRC_STUS_CD  770311      ELPDSRC_STTS_CD  770117.0   194.0
2                       ERSR_DE  684061             ERSR_YMD  683275.0   786.0
3                 MNTNG_IMPR_YN   97839     RDCDVC_EXTRNS_YN   97645.0   194.0
4                     RCPT_SIDO  769418         STDG_CTPV_NM  769224.0   194.0
..                          ...     ...                  ...       ...     ...
172        PFMINPC_BUFFER_DVICE   11734                  NaN       NaN     NaN
173              PFMINPC_WINDOW   11734                  NaN       NaN     NaN
174                PFMINPC_TIRE   11734                  NaN       NaN     NaN
175        PFMINPC_ASSMI_DEVICE   11734                  NaN       NaN     NaN
176  PFMINPC_ELPDSRC_GNRLZ_RESN       0                  NaN       NaN     NaN

[177 rows x 5 columns]

### [출력]

In [ ]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 99\. 사후관리 사후점검

In [111]:
ods_file_name = 'ODS_DLM_TB_ERP_CLEAN_SCREEN'
std_file_name = 'STD_DLM_TB_ERP_CLEAN_SCREEN'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(odf.columns)
print(sdf.columns)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

Index(['CHK_RCPT_NO', 'REDUC_REG_NO', 'RCPT_DE', 'CHK_DE', 'CHK_ODR',
       'RCPT_SIGNGU', 'EXTRNS_REMDEL_STUS', 'SLF_DGNSS_DVICE',
       'FUEL_SPLORE_PICK', 'PLLTN_DNSTY_MEASUVL', 'SMO_CO_VAL', 'SMO_HC_VAL',
       'CHK_RSLT', 'DIRTN_MTTR', 'RCPT_RESN_01_YN', 'RCPT_RESN_02_YN',
       'RCPT_RESN_03_YN', 'RCPT_RESN_04_YN', 'RCPT_RESN_05_YN',
       'RCPT_RESN_06_YN', 'RCPT_RESN_07_YN', 'RCPT_RESN_08_YN',
       'RCPT_RESN_09_YN', 'RCPT_RESN_10_YN', 'RCPT_RESN_11_YN',
       'RCPT_ETC_RESN', 'BPLC_ADRS', 'BPLC_TELNO', 'BPLC_RPRSTV_NM',
       'REG_INST_CD', 'INPT_DE', 'RETR_NM', 'LST_CHNG_DE', 'LST_EDIR_NM',
       'TRTMNT_MTTR_1_YN', 'TRTMNT_MTTR_2_YN', 'TRTMNT_MTTR_3_YN',
       'TRTMNT_MTTR_4_YN', 'TRTMNT_DTLS', 'RETR_ID'],
      dtype='object')
Index(['CHCK_DT', 'CHCK_ODR_CD', 'CHCK_RSLT_CD', 'DIRTN_MTTR_CD',
       'DVIE_EXTNS_REMDL_STS_CD', 'PLLTN_CCNTRA_MSTVL', 'RDCDVC_REG_NO',
       'ACTN_BRKWN'],
      dtype='object')
40 8
(64951, 40) (64951, 8)

### 컬럼 확인

In [112]:
olist = [
    'CHK_DE', 
    'CHK_ODR',
    'CHK_RSLT', 
    'DIRTN_MTTR', 
    'EXTRNS_REMDEL_STUS', 
    'PLLTN_DNSTY_MEASUVL', 
    'REDUC_REG_NO', 
    'TRTMNT_DTLS', 

    'CHK_RCPT_NO', 
    'RCPT_DE', 
    'RCPT_SIGNGU', 
    'SLF_DGNSS_DVICE',
    'FUEL_SPLORE_PICK', 
    'SMO_CO_VAL', 
    'SMO_HC_VAL',
    'RCPT_RESN_01_YN', 
    'RCPT_RESN_02_YN',
    'RCPT_RESN_03_YN', 
    'RCPT_RESN_04_YN', 
    'RCPT_RESN_05_YN',
    'RCPT_RESN_06_YN', 
    'RCPT_RESN_07_YN', 
    'RCPT_RESN_08_YN',
    'RCPT_RESN_09_YN', 
    'RCPT_RESN_10_YN', 
    'RCPT_RESN_11_YN',
    'RCPT_ETC_RESN', 
    'BPLC_ADRS', 
    'BPLC_TELNO', 
    'BPLC_RPRSTV_NM',
    'REG_INST_CD', 
    'INPT_DE', 
    'RETR_NM', 
    'LST_CHNG_DE', 
    'LST_EDIR_NM',
    'TRTMNT_MTTR_1_YN', 
    'TRTMNT_MTTR_2_YN', 
    'TRTMNT_MTTR_3_YN',
    'TRTMNT_MTTR_4_YN', 
    'RETR_ID'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['점검일자', 
    '점검차수',
    '점검결과', 
    '지시사항', 
    '부착개조상태', 
    '오염농도측정값', 
    '저감등록번호', 
    '조치내역', 

    '미정', 
    '미정', 
    '미정', 
    '미정',
    '미정', 
    '미정', 
    '미정',
    '미정', 
    '미정',
    '미정', 
    '미정', 
    '미정',
    '미정', 
    '미정', 
    '미정',
    '미정', 
    '미정', 
    '미정',
    '미정', 
    '미정', 
    '미정', 
    '미정',
    '미정', 
    '미정', 
    '미정', 
    '미정', 
    '미정',
    '미정', 
    '미정', 
    '미정',
    '미정', 
    '미정']
    }

ocol = pd.DataFrame(odict)
ocol

                     컬럼       내용
0                CHK_DE     점검일자
1               CHK_ODR     점검차수
2              CHK_RSLT     점검결과
3            DIRTN_MTTR     지시사항
4    EXTRNS_REMDEL_STUS   부착개조상태
5   PLLTN_DNSTY_MEASUVL  오염농도측정값
6          REDUC_REG_NO   저감등록번호
7           TRTMNT_DTLS     조치내역
8           CHK_RCPT_NO       미정
9               RCPT_DE       미정
10          RCPT_SIGNGU       미정
11      SLF_DGNSS_DVICE       미정
12     FUEL_SPLORE_PICK       미정
13           SMO_CO_VAL       미정
14           SMO_HC_VAL       미정
15      RCPT_RESN_01_YN       미정
16      RCPT_RESN_02_YN       미정
17      RCPT_RESN_03_YN       미정
18      RCPT_RESN_04_YN       미정
19      RCPT_RESN_05_YN       미정
20      RCPT_RESN_06_YN       미정
21      RCPT_RESN_07_YN       미정
22      RCPT_RESN_08_YN       미정
23      RCPT_RESN_09_YN       미정
24      RCPT_RESN_10_YN       미정
25      RCPT_RESN_11_YN       미정
26        RCPT_ETC_RESN       미정
27            BPLC_ADRS       미정
28           BPLC_TELNO       미정
29       BPLC_RPRSTV_NM       미정
30          REG_INST_CD       미정
31              INPT_DE       미정
32              RETR_NM       미정
33          LST_CHNG_DE       미정
34          LST_EDIR_NM       미정
35     TRTMNT_MTTR_1_YN       미정
36     TRTMNT_MTTR_2_YN       미정
37     TRTMNT_MTTR_3_YN       미정
38     TRTMNT_MTTR_4_YN       미정
39              RETR_ID       미정

In [113]:
slist = [
    'CHCK_DT', 
    'CHCK_ODR_CD', 
    'CHCK_RSLT_CD', 
    'DIRTN_MTTR_CD',
    'DVIE_EXTNS_REMDL_STS_CD', 
    'PLLTN_CCNTRA_MSTVL', 
    'RDCDVC_REG_NO',
    'ACTN_BRKWN'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['점검일시', 
    '점검차수코드', 
    '점검결과코드', 
    '지시사항코드',
    '장치부착개조상태', 
    '오염농도측정값', 
    '저감장치등록번호',
    '조치내역']
    }

scol = pd.DataFrame(sdict)
scol

                        컬럼        내용
0                  CHCK_DT      점검일시
1              CHCK_ODR_CD    점검차수코드
2             CHCK_RSLT_CD    점검결과코드
3            DIRTN_MTTR_CD    지시사항코드
4  DVIE_EXTNS_REMDL_STS_CD  장치부착개조상태
5       PLLTN_CCNTRA_MSTVL   오염농도측정값
6            RDCDVC_REG_NO  저감장치등록번호
7               ACTN_BRKWN      조치내역

### 데이터 info

In [114]:
odf2 = odf[olist]
odf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64951 entries, 0 to 64950
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CHK_DE               64951 non-null  int64
 1   CHK_ODR              50015 non-null  object
 2   CHK_RSLT             64890 non-null  object
 3   DIRTN_MTTR           11070 non-null  object
 4   EXTRNS_REMDEL_STUS   64951 non-null  object
 5   PLLTN_DNSTY_MEASUVL  62121 non-null  object
 6   REDUC_REG_NO         64951 non-null  int64
 7   TRTMNT_DTLS          1697 non-null   object
 8   CHK_RCPT_NO          64951 non-null  int64
 9   RCPT_DE              45629 non-null  float64
 10  RCPT_SIGNGU          64885 non-null  object
 11  SLF_DGNSS_DVICE      64569 non-null  object
 12  FUEL_SPLORE_PICK     50276 non-null  object
 13  SMO_CO_VAL           210 non-null    object
 14  SMO_HC_VAL           169 non-null    float64
 15  RCPT_RESN_01_YN      1109 non-null   object
 16  RCPT_RESN_02_YN      43 non-null     object
 17  RCPT_RESN_03_YN      6 non-null      object
 18  RCPT_RESN_04_YN      6 non-null      object
 19  RCPT_RESN_05_YN      10 non-null     object
 20  RCPT_RESN_06_YN      4 non-null      object
 21  RCPT_RESN_07_YN      4 non-null      object
 22  RCPT_RESN_08_YN      0 non-null      float64
 23  RCPT_RESN_09_YN      5 non-null      object
 24  RCPT_RESN_10_YN      290 non-null    object
 25  RCPT_RESN_11_YN      344 non-null    object
 26  RCPT_ETC_RESN        287 non-null    object
 27  BPLC_ADRS            21739 non-null  object
 28  BPLC_TELNO           34020 non-null  object
 29  BPLC_RPRSTV_NM       36498 non-null  object
 30  REG_INST_CD          64888 non-null  object
 31  INPT_DE              42770 non-null  float64
 32  RETR_NM              42700 non-null  object
 33  LST_CHNG_DE          42873 non-null  object
 34  LST_EDIR_NM          42733 non-null  object
 35  TRTMNT_MTTR_1_YN     48 non-null     object
 36  TRTMNT_MTTR_2_YN     71 non-null     object
 37  TRTMNT_MTTR_3_YN     1744 non-null   object
 38  TRTMNT_MTTR_4_YN     137 non-null    object
 39  RETR_ID              71 non-null     object
dtypes: float64(4), int64(3), object(33)
memory usage: 19.8+ MB

In [115]:
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount

                 oindex  ocount
0                CHK_DE   64951
1               CHK_ODR   50015
2              CHK_RSLT   64890
3            DIRTN_MTTR   11070
4    EXTRNS_REMDEL_STUS   64951
5   PLLTN_DNSTY_MEASUVL   62121
6          REDUC_REG_NO   64951
7           TRTMNT_DTLS    1697
8           CHK_RCPT_NO   64951
9               RCPT_DE   45629
10          RCPT_SIGNGU   64885
11      SLF_DGNSS_DVICE   64569
12     FUEL_SPLORE_PICK   50276
13           SMO_CO_VAL     210
14           SMO_HC_VAL     169
15      RCPT_RESN_01_YN    1109
16      RCPT_RESN_02_YN      43
17      RCPT_RESN_03_YN       6
18      RCPT_RESN_04_YN       6
19      RCPT_RESN_05_YN      10
20      RCPT_RESN_06_YN       4
21      RCPT_RESN_07_YN       4
22      RCPT_RESN_08_YN       0
23      RCPT_RESN_09_YN       5
24      RCPT_RESN_10_YN     290
25      RCPT_RESN_11_YN     344
26        RCPT_ETC_RESN     287
27            BPLC_ADRS   21739
28           BPLC_TELNO   34020
29       BPLC_RPRSTV_NM   36498
30          REG_INST_CD   64888
31              INPT_DE   42770
32              RETR_NM   42700
33          LST_CHNG_DE   42873
34          LST_EDIR_NM   42733
35     TRTMNT_MTTR_1_YN      48
36     TRTMNT_MTTR_2_YN      71
37     TRTMNT_MTTR_3_YN    1744
38     TRTMNT_MTTR_4_YN     137
39              RETR_ID      71

In [116]:
sdf2 = sdf[slist]
sdf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64951 entries, 0 to 64950
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CHCK_DT                  64951 non-null  int64
 1   CHCK_ODR_CD              50015 non-null  object
 2   CHCK_RSLT_CD             64890 non-null  object
 3   DIRTN_MTTR_CD            11069 non-null  object
 4   DVIE_EXTNS_REMDL_STS_CD  64894 non-null  object
 5   PLLTN_CCNTRA_MSTVL       62121 non-null  object
 6   RDCDVC_REG_NO            64951 non-null  int64
 7   ACTN_BRKWN               1697 non-null   object
dtypes: int64(2), object(6)
memory usage: 4.0+ MB

In [117]:
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount

                    sindex  scount
0                  CHCK_DT   64951
1              CHCK_ODR_CD   50015
2             CHCK_RSLT_CD   64890
3            DIRTN_MTTR_CD   11069
4  DVIE_EXTNS_REMDL_STS_CD   64894
5       PLLTN_CCNTRA_MSTVL   62121
6            RDCDVC_REG_NO   64951
7               ACTN_BRKWN    1697

In [118]:
oscount = pd.concat([ocount, scount], axis=1)
oscount

                 oindex  ocount                   sindex   scount
0                CHK_DE   64951                  CHCK_DT  64951.0
1               CHK_ODR   50015              CHCK_ODR_CD  50015.0
2              CHK_RSLT   64890             CHCK_RSLT_CD  64890.0
3            DIRTN_MTTR   11070            DIRTN_MTTR_CD  11069.0
4    EXTRNS_REMDEL_STUS   64951  DVIE_EXTNS_REMDL_STS_CD  64894.0
5   PLLTN_DNSTY_MEASUVL   62121       PLLTN_CCNTRA_MSTVL  62121.0
6          REDUC_REG_NO   64951            RDCDVC_REG_NO  64951.0
7           TRTMNT_DTLS    1697               ACTN_BRKWN   1697.0
8           CHK_RCPT_NO   64951                      NaN      NaN
9               RCPT_DE   45629                      NaN      NaN
10          RCPT_SIGNGU   64885                      NaN      NaN
11      SLF_DGNSS_DVICE   64569                      NaN      NaN
12     FUEL_SPLORE_PICK   50276                      NaN      NaN
13           SMO_CO_VAL     210                      NaN      NaN
14           SMO_HC_VAL     169                      NaN      NaN
15      RCPT_RESN_01_YN    1109                      NaN      NaN
16      RCPT_RESN_02_YN      43                      NaN      NaN
17      RCPT_RESN_03_YN       6                      NaN      NaN
18      RCPT_RESN_04_YN       6                      NaN      NaN
19      RCPT_RESN_05_YN      10                      NaN      NaN
20      RCPT_RESN_06_YN       4                      NaN      NaN
21      RCPT_RESN_07_YN       4                      NaN      NaN
22      RCPT_RESN_08_YN       0                      NaN      NaN
23      RCPT_RESN_09_YN       5                      NaN      NaN
24      RCPT_RESN_10_YN     290                      NaN      NaN
25      RCPT_RESN_11_YN     344                      NaN      NaN
26        RCPT_ETC_RESN     287                      NaN      NaN
27            BPLC_ADRS   21739                      NaN      NaN
28           BPLC_TELNO   34020                      NaN      NaN
29       BPLC_RPRSTV_NM   36498                      NaN      NaN
30          REG_INST_CD   64888                      NaN      NaN
31              INPT_DE   42770                      NaN      NaN
32              RETR_NM   42700                      NaN      NaN
33          LST_CHNG_DE   42873                      NaN      NaN
34          LST_EDIR_NM   42733                      NaN      NaN
35     TRTMNT_MTTR_1_YN      48                      NaN      NaN
36     TRTMNT_MTTR_2_YN      71                      NaN      NaN
37     TRTMNT_MTTR_3_YN    1744                      NaN      NaN
38     TRTMNT_MTTR_4_YN     137                      NaN      NaN
39              RETR_ID      71                      NaN      NaN

In [119]:
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount

                 oindex  ocount                   sindex   scount    차이
0                CHK_DE   64951                  CHCK_DT  64951.0   0.0
1               CHK_ODR   50015              CHCK_ODR_CD  50015.0   0.0
2              CHK_RSLT   64890             CHCK_RSLT_CD  64890.0   0.0
3            DIRTN_MTTR   11070            DIRTN_MTTR_CD  11069.0   1.0
4    EXTRNS_REMDEL_STUS   64951  DVIE_EXTNS_REMDL_STS_CD  64894.0  57.0
5   PLLTN_DNSTY_MEASUVL   62121       PLLTN_CCNTRA_MSTVL  62121.0   0.0
6          REDUC_REG_NO   64951            RDCDVC_REG_NO  64951.0   0.0
7           TRTMNT_DTLS    1697               ACTN_BRKWN   1697.0   0.0
8           CHK_RCPT_NO   64951                      NaN      NaN   NaN
9               RCPT_DE   45629                      NaN      NaN   NaN
10          RCPT_SIGNGU   64885                      NaN      NaN   NaN
11      SLF_DGNSS_DVICE   64569                      NaN      NaN   NaN
12     FUEL_SPLORE_PICK   50276                      NaN      NaN   NaN
13           SMO_CO_VAL     210                      NaN      NaN   NaN
14           SMO_HC_VAL     169                      NaN      NaN   NaN
15      RCPT_RESN_01_YN    1109                      NaN      NaN   NaN
16      RCPT_RESN_02_YN      43                      NaN      NaN   NaN
17      RCPT_RESN_03_YN       6                      NaN      NaN   NaN
18      RCPT_RESN_04_YN       6                      NaN      NaN   NaN
19      RCPT_RESN_05_YN      10                      NaN      NaN   NaN
20      RCPT_RESN_06_YN       4                      NaN      NaN   NaN
21      RCPT_RESN_07_YN       4                      NaN      NaN   NaN
22      RCPT_RESN_08_YN       0                      NaN      NaN   NaN
23      RCPT_RESN_09_YN       5                      NaN      NaN   NaN
24      RCPT_RESN_10_YN     290                      NaN      NaN   NaN
25      RCPT_RESN_11_YN     344                      NaN      NaN   NaN
26        RCPT_ETC_RESN     287                      NaN      NaN   NaN
27            BPLC_ADRS   21739                      NaN      NaN   NaN
28           BPLC_TELNO   34020                      NaN      NaN   NaN
29       BPLC_RPRSTV_NM   36498                      NaN      NaN   NaN
30          REG_INST_CD   64888                      NaN      NaN   NaN
31              INPT_DE   42770                      NaN      NaN   NaN
32              RETR_NM   42700                      NaN      NaN   NaN
33          LST_CHNG_DE   42873                      NaN      NaN   NaN
34          LST_EDIR_NM   42733                      NaN      NaN   NaN
35     TRTMNT_MTTR_1_YN      48                      NaN      NaN   NaN
36     TRTMNT_MTTR_2_YN      71                      NaN      NaN   NaN
37     TRTMNT_MTTR_3_YN    1744                      NaN      NaN   NaN
38     TRTMNT_MTTR_4_YN     137                      NaN      NaN   NaN
39              RETR_ID      71                      NaN      NaN   NaN

### [출력]

In [120]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

## 99\. 노후차 조기폐차 관리정보(수도권)

In [121]:
ods_file_name = 'ODS_DLM_TB_ERP_EARLY_ERASE_AEA'
std_file_name = 'STD_DLM_TB_ERP_EARLY_ERASE_AEA'
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')
odf = pd.read_csv(opath, low_memory=False)
sdf = pd.read_csv(spath, low_memory=False)
print(len(odf.columns), len(sdf.columns))
print(odf.shape, sdf.shape)

Index(['ELPDSRC_MNGT_NO', 'ELPDSRC_STUS_CD', 'RDCDVC_SE', 'INST_ID_CD',
       'OWNR_NM', 'USER_BIZRNO', 'USER_TELNO', 'FXNUM', 'USER_ZIP',
       'USER_1_ADRS',
       ...
       'PRE_SCRAP_CAR_YN', 'DEP_YN', 'VIRT_ACC_NO', 'ELCTY_HYDRO_CAR_ADD_AMT',
       'PFMINPC_ITSL_APPRNC', 'PFMINPC_BUFFER_DVICE', 'PFMINPC_WINDOW',
       'PFMINPC_TIRE', 'PFMINPC_ASSMI_DEVICE', 'PFMINPC_ELPDSRC_GNRLZ_RESN'],
      dtype='object', length=177)
Index(['ELPDSRC_LST_APRV_YN', 'ELPDSRC_STTS_CD', 'ERSR_YMD',
       'RDCDVC_EXTRNS_YN', 'STDG_CTPV_NM', 'LEM_KND_CD',
       'SCCAR_REG_DRVNG_DSNC', 'VHRNO', 'VIN', 'CRTN_DT', 'STDG_SGG_NM',
       'SCRCAR_ENTRPS_NM', 'ELPDSRC_LAST_APRV_YMD', 'SBSIDY_TRGT_YN',
       'ELPDSRC_MNG_NO'],
      dtype='object')
177 15
(770311, 177) (770117, 15)

In [125]:
odf.columns.to_list()

['ELPDSRC_MNGT_NO',
 'ELPDSRC_STUS_CD',
 'RDCDVC_SE',
 'INST_ID_CD',
 'OWNR_NM',
 'USER_BIZRNO',
 'USER_TELNO',
 'FXNUM',
 'USER_ZIP',
 'USER_1_ADRS',
 'USER_2_ADRS',
 'RCPT_SIDO',
 'RCPT_SIGNGU',
 'VHRNO',
 'VIN',
 'VHCL_YRIDNW',
 'EGINCTY',
 'VHCL_PSCP',
 'VHCL_WGHT',
 'TOT_WGHT',
 'CRYNG_WGHT',
 'VHCNM',
 'VHCL_FRM',
 'VHCTY',
 'VHCL_PURPS',
 'FST_REG_DE',
 'SCRCAR_REG_DRVNG_DSTNC',
 'SCRCAR_ERA_DRVNG_DSTNC',
 'VHCL_FUEL',
 'PRCINSP_DE',
 'INSPOF_NM',
 'PRCINSP_JDGMNT_YN',
 'PRCINSP_RSLT_VAL',
 'PRCINSP_JDGMNT_STDR_VAL',
 'RCPT_DE',
 'INPT_DE',
 'RETR_NM',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_TRGT_1_AT',
 'ELPDSRC_TRGT_2_AT',
 'ELPDSRC_TRGT_3_AT',
 'ELPDSRC_TRGT_4_AT',
 'ELPDSRC_TRGT_5_AT',
 'ELPDSRC_TRGT_6_AT',
 'ELPDSRC_TRGT_7_AT',
 'ELPDSRC_TRGT_CNFRM_REG_DE',
 'ELPDSRC_TRGT_CNFRM_REGR_NM',
 'PYMT_CNFRM_YN',
 'EXPC_SPRT_AMT',
 'DCIS_SPRT_AMT',
 'SBSIDY_UNPAY_RESN',
 'SBSIDY_RQEST_DE',
 'SBSIDY_RQEST_REGR_NM',
 'DOC_CNFRM_NO',
 'DOC_OUTT_DE',
 'INSP_RQT_SIWA_MTHD',
 'INSP_RQT_DE',
 'INSP_RQT_TM',
 'VRSC_ENTRPS_NM',
 'AGENT_ZIP',
 'AGENT_1_ADRS',
 'AGENT_2_ADRS',
 'AGENT_TELNO',
 'AGENT_CRTC_NO',
 'INSP_RQT_REG_DE',
 'INSP_RQT_REGR_NM',
 'PFMINPC_DE',
 'PFMINPC_1_ITM',
 'PFMINPC_2_ITM',
 'PFMINPC_3_ITM',
 'PFMINPC_4_ITM',
 'PFMINPC_5_ITM',
 'PFMINPC_ETC_ITM',
 'PFMINPC_ITM_ETC_CMPNT_NM',
 'PFMINPC_FILE_ATT_YN',
 'PFMINPC_ELPDSRC_YN',
 'PFMINPC_ELPDSRC_IMPSBL_RESN',
 'PFMINPC_REG_DE',
 'PFMINPC_REGR_NM',
 'PFMINPC_PAPE_OUTT_DE',
 'TRTMNT_DE',
 'ERSR_DE',
 'NCAR_PUCH_PLAN_DE',
 'NCAR_PUCH_PLAN_VHCL_NM',
 'SCRCAR_ENTRPS_NM',
 'SCRCAR_ENTRPS_ZIP',
 'SCRCAR_ENTRPS_1_ADRS',
 'SCRCAR_ENTRPS_2_ADRS',
 'ELPDSRC_ATT_FILE_1_YN',
 'ELPDSRC_ATT_FILE_2_YN',
 'ELPDSRC_ATT_FILE_3_YN',
 'ELPDSRC_REG_DE',
 'ELPDSRC_REGR_NM',
 'ELPDSRC_LST_CNFRM_YN',
 'ELPDSRC_LST_UNAP_RESN',
 'SBSIDY_PYMT_DE',
 'SBSIDY_BIZ_YR',
 'ELPDSRC_LST_CNFRM_DE',
 'ELPDSRC_LST_APRR_NM',
 'LST_CHNG_DE',
 'LST_EDIR_NM',
 'LWBCT_YN',
 'NOW_VHRNO',
 'ELPDSRC_ATT_FILE_4_YN',
 'BANK_NM',
 'BANK_ACC_NO',
 'PRCINSP_SE',
 'RCPT_LOCGOV_CD',
 'RPRSTV_NM',
 'BIZCND',
 'TYPBIZ',
 'EMAIL',
 'RCPT_SE',
 'INSP_SE',
 'ELPDSRC_TRGT_AT_ETC_RESN',
 'HST_MNGT_NO',
 'CTNT',
 'VHCTY_SE',
 'ELPDSRC_GRP',
 'BTHDY',
 'JURIRNO',
 'STDR_YM',
 'STDR_AMT',
 'WHL_EXCS_CNFRM_DE',
 'WHL_EXCS_APRR_NM',
 'MNFCT_DE',
 'OLD_SIDO',
 'OLD_SIGNGU',
 'OLD_RCPT_LOCGOV_CD',
 'OLD_1_ADRS',
 'OLD_2_ADRS',
 'OLD_VHCL_PURPS',
 'BAI_ID',
 'ADITOR_NM',
 'REG_NO',
 'RQEST_ARVL_DE',
 'RQEST_ARVL_YN',
 'BIL_CNFRMR_NM',
 'ADD_AMT',
 'SAMNS_CNFRM',
 'ADD_RQEST_ARVL_YN',
 'ADD_RQEST_ARVL_DE',
 'ADD_RQEST_CNFRMR_NM',
 'ATT_PAPE_CNFRM_AT',
 'BEF_STUS_CD',
 'WAREHOUSING_DE',
 'WAREHOUSING_YN',
 'MNTNG_IMPR_YN',
 'MNTNG_IMPR_AMT',
 'ELPDSRC_ATT_FILE_5_YN',
 'ELPDSRC_VRSC_INST_NO',
 'SMAL_BUSIN_YN',
 'INPT_MTHD_FLAG',
 'ELPDSRC_ATT_FILE_7_YN',
 'STNDRD',
 'ENGINE_RPM',
 'MAKER',
 'CAR_GRADE',
 'AID_RJCT_DE',
 'IMG_LGCLFL1',
 'IMG_PHYSCL1',
 'IMG_LGCLFL2',
 'IMG_PHYSCL2',
 'IMG_LGCLFL3',
 'IMG_PHYSCL3',
 'IMG_LGCLFL4',
 'IMG_PHYSCL4',
 'PRE_SCRAP_CAR_YN',
 'DEP_YN',
 'VIRT_ACC_NO',
 'ELCTY_HYDRO_CAR_ADD_AMT',
 'PFMINPC_ITSL_APPRNC',
 'PFMINPC_BUFFER_DVICE',
 'PFMINPC_WINDOW',
 'PFMINPC_TIRE',
 'PFMINPC_ASSMI_DEVICE',
 'PFMINPC_ELPDSRC_GNRLZ_RESN']

In [126]:
sdf.columns.to_list()

['ELPDSRC_LST_APRV_YN',
 'ELPDSRC_STTS_CD',
 'ERSR_YMD',
 'RDCDVC_EXTRNS_YN',
 'STDG_CTPV_NM',
 'LEM_KND_CD',
 'SCCAR_REG_DRVNG_DSNC',
 'VHRNO',
 'VIN',
 'CRTN_DT',
 'STDG_SGG_NM',
 'SCRCAR_ENTRPS_NM',
 'ELPDSRC_LAST_APRV_YMD',
 'SBSIDY_TRGT_YN',
 'ELPDSRC_MNG_NO']

### 컬럼 확인

In [127]:
olist = [
    'ELPDSRC_LST_CNFRM_YN',
    'ELPDSRC_STUS_CD',
    'ERSR_DE',
    'MNTNG_IMPR_YN',
    'RCPT_SIDO',
    'RDCDVC_SE',
    'SCRCAR_REG_DRVNG_DSTNC',
    'VHRNO',
    'VIN',

    'ELPDSRC_MNGT_NO',
    'INST_ID_CD',
    'OWNR_NM',
    'USER_BIZRNO',
    'USER_TELNO',
    'FXNUM',
    'USER_ZIP',
    'USER_1_ADRS',
    'USER_2_ADRS',
    'RCPT_SIGNGU',
    'VHCL_YRIDNW',
    'EGINCTY',
    'VHCL_PSCP',
    'VHCL_WGHT',
    'TOT_WGHT',
    'CRYNG_WGHT',
    'VHCNM',
    'VHCL_FRM',
    'VHCTY',
    'VHCL_PURPS',
    'FST_REG_DE',
    'SCRCAR_ERA_DRVNG_DSTNC',
    'VHCL_FUEL',
    'PRCINSP_DE',
    'INSPOF_NM',
    'PRCINSP_JDGMNT_YN',
    'PRCINSP_RSLT_VAL',
    'PRCINSP_JDGMNT_STDR_VAL',
    'RCPT_DE',
    'INPT_DE',
    'RETR_NM',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_TRGT_1_AT',
    'ELPDSRC_TRGT_2_AT',
    'ELPDSRC_TRGT_3_AT',
    'ELPDSRC_TRGT_4_AT',
    'ELPDSRC_TRGT_5_AT',
    'ELPDSRC_TRGT_6_AT',
    'ELPDSRC_TRGT_7_AT',
    'ELPDSRC_TRGT_CNFRM_REG_DE',
    'ELPDSRC_TRGT_CNFRM_REGR_NM',
    'PYMT_CNFRM_YN',
    'EXPC_SPRT_AMT',
    'DCIS_SPRT_AMT',
    'SBSIDY_UNPAY_RESN',
    'SBSIDY_RQEST_DE',
    'SBSIDY_RQEST_REGR_NM',
    'DOC_CNFRM_NO',
    'DOC_OUTT_DE',
    'INSP_RQT_SIWA_MTHD',
    'INSP_RQT_DE',
    'INSP_RQT_TM',
    'VRSC_ENTRPS_NM',
    'AGENT_ZIP',
    'AGENT_1_ADRS',
    'AGENT_2_ADRS',
    'AGENT_TELNO',
    'AGENT_CRTC_NO',
    'INSP_RQT_REG_DE',
    'INSP_RQT_REGR_NM',
    'PFMINPC_DE',
    'PFMINPC_1_ITM',
    'PFMINPC_2_ITM',
    'PFMINPC_3_ITM',
    'PFMINPC_4_ITM',
    'PFMINPC_5_ITM',
    'PFMINPC_ETC_ITM',
    'PFMINPC_ITM_ETC_CMPNT_NM',
    'PFMINPC_FILE_ATT_YN',
    'PFMINPC_ELPDSRC_YN',
    'PFMINPC_ELPDSRC_IMPSBL_RESN',
    'PFMINPC_REG_DE',
    'PFMINPC_REGR_NM',
    'PFMINPC_PAPE_OUTT_DE',
    'TRTMNT_DE',
    'NCAR_PUCH_PLAN_DE',
    'NCAR_PUCH_PLAN_VHCL_NM',
    'SCRCAR_ENTRPS_NM',
    'SCRCAR_ENTRPS_ZIP',
    'SCRCAR_ENTRPS_1_ADRS',
    'SCRCAR_ENTRPS_2_ADRS',
    'ELPDSRC_ATT_FILE_1_YN',
    'ELPDSRC_ATT_FILE_2_YN',
    'ELPDSRC_ATT_FILE_3_YN',
    'ELPDSRC_REG_DE',
    'ELPDSRC_REGR_NM',
    'ELPDSRC_LST_UNAP_RESN',
    'SBSIDY_PYMT_DE',
    'SBSIDY_BIZ_YR',
    'ELPDSRC_LST_CNFRM_DE',
    'ELPDSRC_LST_APRR_NM',
    'LST_CHNG_DE',
    'LST_EDIR_NM',
    'LWBCT_YN',
    'NOW_VHRNO',
    'ELPDSRC_ATT_FILE_4_YN',
    'BANK_NM',
    'BANK_ACC_NO',
    'PRCINSP_SE',
    'RCPT_LOCGOV_CD',
    'RPRSTV_NM',
    'BIZCND',
    'TYPBIZ',
    'EMAIL',
    'RCPT_SE',
    'INSP_SE',
    'ELPDSRC_TRGT_AT_ETC_RESN',
    'HST_MNGT_NO',
    'CTNT',
    'VHCTY_SE',
    'ELPDSRC_GRP',
    'BTHDY',
    'JURIRNO',
    'STDR_YM',
    'STDR_AMT',
    'WHL_EXCS_CNFRM_DE',
    'WHL_EXCS_APRR_NM',
    'MNFCT_DE',
    'OLD_SIDO',
    'OLD_SIGNGU',
    'OLD_RCPT_LOCGOV_CD',
    'OLD_1_ADRS',
    'OLD_2_ADRS',
    'OLD_VHCL_PURPS',
    'BAI_ID',
    'ADITOR_NM',
    'REG_NO',
    'RQEST_ARVL_DE',
    'RQEST_ARVL_YN',
    'BIL_CNFRMR_NM',
    'ADD_AMT',
    'SAMNS_CNFRM',
    'ADD_RQEST_ARVL_YN',
    'ADD_RQEST_ARVL_DE',
    'ADD_RQEST_CNFRMR_NM',
    'ATT_PAPE_CNFRM_AT',
    'BEF_STUS_CD',
    'WAREHOUSING_DE',
    'WAREHOUSING_YN',
    'MNTNG_IMPR_AMT',
    'ELPDSRC_ATT_FILE_5_YN',
    'ELPDSRC_VRSC_INST_NO',
    'SMAL_BUSIN_YN',
    'INPT_MTHD_FLAG',
    'ELPDSRC_ATT_FILE_7_YN',
    'STNDRD',
    'ENGINE_RPM',
    'MAKER',
    'CAR_GRADE',
    'AID_RJCT_DE',
    'IMG_LGCLFL1',
    'IMG_PHYSCL1',
    'IMG_LGCLFL2',
    'IMG_PHYSCL2',
    'IMG_LGCLFL3',
    'IMG_PHYSCL3',
    'IMG_LGCLFL4',
    'IMG_PHYSCL4',
    'PRE_SCRAP_CAR_YN',
    'DEP_YN',
    'VIRT_ACC_NO',
    'ELCTY_HYDRO_CAR_ADD_AMT',
    'PFMINPC_ITSL_APPRNC',
    'PFMINPC_BUFFER_DVICE',
    'PFMINPC_WINDOW',
    'PFMINPC_TIRE',
    'PFMINPC_ASSMI_DEVICE',
    'PFMINPC_ELPDSRC_GNRLZ_RESN'
    ]

odict = {
    '컬럼':olist,
    '내용':
    ['조기폐차최종승인YN',
    '조기폐차상태코드',
    '말소일자',
    '저감장치 미개발(부착불가)여부',
    '접수시도',
    '저감장치구분',
    '폐차등록주행거리',
    '차량등록번호',
    '차대번호',

    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정']
    }

ocol = pd.DataFrame(odict)
ocol

                             컬럼                내용
0          ELPDSRC_LST_CNFRM_YN        조기폐차최종승인YN
1               ELPDSRC_STUS_CD          조기폐차상태코드
2                       ERSR_DE              말소일자
3                 MNTNG_IMPR_YN  저감장치 미개발(부착불가)여부
4                     RCPT_SIDO              접수시도
..                          ...               ...
172        PFMINPC_BUFFER_DVICE                미정
173              PFMINPC_WINDOW                미정
174                PFMINPC_TIRE                미정
175        PFMINPC_ASSMI_DEVICE                미정
176  PFMINPC_ELPDSRC_GNRLZ_RESN                미정

[177 rows x 2 columns]

In [128]:
slist = [
    'ELPDSRC_LST_APRV_YN',
    'ELPDSRC_STTS_CD',
    'ERSR_YMD',
    'RDCDVC_EXTRNS_YN',
    'STDG_CTPV_NM',
    'LEM_KND_CD',
    'SCCAR_REG_DRVNG_DSNC',
    'VHRNO',
    'VIN',

    'CRTN_DT',
    'STDG_SGG_NM',
    'SCRCAR_ENTRPS_NM',
    'ELPDSRC_LAST_APRV_YMD',
    'SBSIDY_TRGT_YN',
    'ELPDSRC_MNG_NO'
    ]

sdict = {
    '컬럼':slist,
    '내용':
    ['조기폐차최종승인여부',
    '조기폐차상태코드',
    '말소일자',
    '저감장치부착여부',
    '법정동시도명',
    '저공해조치종류코드',
    '폐차등록주행거리',
    '자동차등록번호',
    '차대번호',
    
    '미정',
    '미정',
    '미정',
    '미정',
    '미정',
    '미정']
    }

scol = pd.DataFrame(sdict)
scol

                       컬럼          내용
0     ELPDSRC_LST_APRV_YN  조기폐차최종승인여부
1         ELPDSRC_STTS_CD    조기폐차상태코드
2                ERSR_YMD        말소일자
3        RDCDVC_EXTRNS_YN    저감장치부착여부
4            STDG_CTPV_NM      법정동시도명
5              LEM_KND_CD   저공해조치종류코드
6    SCCAR_REG_DRVNG_DSNC    폐차등록주행거리
7                   VHRNO     자동차등록번호
8                     VIN        차대번호
9                 CRTN_DT          미정
10            STDG_SGG_NM          미정
11       SCRCAR_ENTRPS_NM          미정
12  ELPDSRC_LAST_APRV_YMD          미정
13         SBSIDY_TRGT_YN          미정
14         ELPDSRC_MNG_NO          미정

### 데이터 info

In [129]:
odf2 = odf[olist]
odf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 770311 entries, 0 to 770310
Columns: 177 entries, ELPDSRC_LST_CNFRM_YN to PFMINPC_ELPDSRC_GNRLZ_RESN
dtypes: float64(56), int64(3), object(118)
memory usage: 1.0+ GB

In [130]:
ocount = odf2.count().reset_index()
ocount.columns = ['oindex', 'ocount']
ocount

                         oindex  ocount
0          ELPDSRC_LST_CNFRM_YN  680625
1               ELPDSRC_STUS_CD  770311
2                       ERSR_DE  684061
3                 MNTNG_IMPR_YN   97839
4                     RCPT_SIDO  769418
..                          ...     ...
172        PFMINPC_BUFFER_DVICE   11734
173              PFMINPC_WINDOW   11734
174                PFMINPC_TIRE   11734
175        PFMINPC_ASSMI_DEVICE   11734
176  PFMINPC_ELPDSRC_GNRLZ_RESN       0

[177 rows x 2 columns]

In [131]:
sdf2 = sdf[slist]
sdf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 770117 entries, 0 to 770116
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ELPDSRC_LST_APRV_YN    679295 non-null  object
 1   ELPDSRC_STTS_CD        770117 non-null  object
 2   ERSR_YMD               683275 non-null  float64
 3   RDCDVC_EXTRNS_YN       97645 non-null   object
 4   STDG_CTPV_NM           769224 non-null  object
 5   LEM_KND_CD             770117 non-null  object
 6   SCCAR_REG_DRVNG_DSNC   769749 non-null  float64
 7   VHRNO                  770117 non-null  object
 8   VIN                    770117 non-null  object
 9   CRTN_DT                770117 non-null  int64
 10  STDG_SGG_NM            769188 non-null  object
 11  SCRCAR_ENTRPS_NM       682680 non-null  object
 12  ELPDSRC_LAST_APRV_YMD  679297 non-null  float64
 13  SBSIDY_TRGT_YN         765430 non-null  object
 14  ELPDSRC_MNG_NO         770117 non-null  int64
dtypes: float64(3), int64(2), object(10)
memory usage: 88.1+ MB

In [132]:
scount = sdf2.count().reset_index()
scount.columns = ['sindex', 'scount']
scount

                   sindex  scount
0     ELPDSRC_LST_APRV_YN  679295
1         ELPDSRC_STTS_CD  770117
2                ERSR_YMD  683275
3        RDCDVC_EXTRNS_YN   97645
4            STDG_CTPV_NM  769224
5              LEM_KND_CD  770117
6    SCCAR_REG_DRVNG_DSNC  769749
7                   VHRNO  770117
8                     VIN  770117
9                 CRTN_DT  770117
10            STDG_SGG_NM  769188
11       SCRCAR_ENTRPS_NM  682680
12  ELPDSRC_LAST_APRV_YMD  679297
13         SBSIDY_TRGT_YN  765430
14         ELPDSRC_MNG_NO  770117

In [133]:
oscount = pd.concat([ocount, scount], axis=1)
oscount

                         oindex  ocount               sindex    scount
0          ELPDSRC_LST_CNFRM_YN  680625  ELPDSRC_LST_APRV_YN  679295.0
1               ELPDSRC_STUS_CD  770311      ELPDSRC_STTS_CD  770117.0
2                       ERSR_DE  684061             ERSR_YMD  683275.0
3                 MNTNG_IMPR_YN   97839     RDCDVC_EXTRNS_YN   97645.0
4                     RCPT_SIDO  769418         STDG_CTPV_NM  769224.0
..                          ...     ...                  ...       ...
172        PFMINPC_BUFFER_DVICE   11734                  NaN       NaN
173              PFMINPC_WINDOW   11734                  NaN       NaN
174                PFMINPC_TIRE   11734                  NaN       NaN
175        PFMINPC_ASSMI_DEVICE   11734                  NaN       NaN
176  PFMINPC_ELPDSRC_GNRLZ_RESN       0                  NaN       NaN

[177 rows x 4 columns]

In [134]:
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount

                         oindex  ocount               sindex    scount      차이
0          ELPDSRC_LST_CNFRM_YN  680625  ELPDSRC_LST_APRV_YN  679295.0  1330.0
1               ELPDSRC_STUS_CD  770311      ELPDSRC_STTS_CD  770117.0   194.0
2                       ERSR_DE  684061             ERSR_YMD  683275.0   786.0
3                 MNTNG_IMPR_YN   97839     RDCDVC_EXTRNS_YN   97645.0   194.0
4                     RCPT_SIDO  769418         STDG_CTPV_NM  769224.0   194.0
..                          ...     ...                  ...       ...     ...
172        PFMINPC_BUFFER_DVICE   11734                  NaN       NaN     NaN
173              PFMINPC_WINDOW   11734                  NaN       NaN     NaN
174                PFMINPC_TIRE   11734                  NaN       NaN     NaN
175        PFMINPC_ASSMI_DEVICE   11734                  NaN       NaN     NaN
176  PFMINPC_ELPDSRC_GNRLZ_RESN       0                  NaN       NaN     NaN

[177 rows x 5 columns]

### [출력]

In [135]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
oscount.to_excel(texcel, sheet_name='count', index=False)
texcel.save()

# 코드 마지막