# Library

In [1]:
import pandas as pd
import os
import numpy as np
from tqdm import tqdm

## [load] file

In [2]:
# file path
# ODS : D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/ODS
# STD : D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/STD

In [3]:
ods_path = 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/ODS'
std_path = 'D:/과업/[한국환경공단]자동차 환경 빅데이터 구축 2차/data/STD'

## 함수화

In [4]:
def fuc(num):
   # 파일명, 파일경로 설정
   ods_file_name = f'ODS_CEG_CAR_MIG_{num}'
   std_file_name = f'STD_CEG_CAR_MIG_{num}'
   opath = os.path.join(ods_path, ods_file_name + '.csv')
   spath = os.path.join(std_path, std_file_name + '.csv')
   odf = pd.read_csv(opath)
   sdf = pd.read_csv(spath)

   # 분석
   olist = [
   'ACQS_AMT', 
   'ACQS_DE', 
   'BSPL_LEDO_CD', 
   'CRTN_DT', 
   'EMIS_CRTCNO', 
   'EMIS_GRD', 
   'EMIS_INSP_EFCT_DE', 
   'FST_MBERNO', 
   'FST_REG_DE', 
   'LEM_KND', 
   'LEM_STRCHG_YN', 
   'LEM_YN', 
   'NOW_MBERNO', 
   'OWNR_SE', 
   'PURPS', 
   'SRCMNNO', 
   'UPDT_DT', 
   'VHCL_ERSR_YN', 
   'VHCL_MNFCT_DE', 
   'VHCL_YRIDNW', 
   'VHCTY', 
   'VHMNO', 
   'VHRNO_NUM_INFO', 
   'VIN', 'VHRNO', 
   'NOW_OWNR_NM', 
   'BSPL_ADRS', 
   'OWNR_ADRS', 
   'BSPL_ZIP', 
   'FST_OWNR_NM', 
   'RMK', 
   'USER_ID'
   ]
   slist = [
   'ACQS_AMT', 
   'ACQS_YMD', 
   'BSPL_STDG_CD', 
   'VHCL_REG_DT', 
   'EXHST_GAS_CERT_NO', 
   'EXHST_GAS_GRD_CD', 
   'EXTGAS_INSP_VLD_YMD', 
   'FRST_MBR_NO', 
   'FRST_REG_YMD', 
   'LEM_KND_CD', 
   'STRCT_CHG_YN', 
   'LEM_YN', 
   'NOW_MBR_NO', 
   'VHCL_OWNR_CL_CD', 
   'PURPS_CD2', 
   'MANP_MNG_NO', 
   'MDFCN_DT', 
   'VHCL_ERSR_YN', 
   'VHCL_FBCTN_YMD', 
   'YRIDNW', 
   'VHCTY_CD', 
   'VHCL_MNG_NO', 
   'VHRNO_FGRE_INFO', 
   'VIN', 
   'VHRNO'
   ]
   odict = {
   '컬럼':olist,
   '내용':['취득금액', '취득일자', '본거지 법정동 코드', '생성 일시', '배출가스 인증번호', '배출가스 등급', '배출가스검사유효일자', '최초 회원번호', '최초 등록 일자', '저공해조치 종류', '저공해조치 구조변경 YN', '저공해조치 YN(미사용)', '현재 회원번호', '소유자 구분', '용도', '제원관리번호', '수정 일시', '차량 말소 YN', '차량 제작 일자', '차량 연식', '차종', '차량관리번호', '차량등록번호 숫자 정보', '차대번호', '미정', '미정', '미정', '미정', '미정', '미정', '미정', '미정']
   }
   ocol = pd.DataFrame(odict)

   sdict = {
      '컬럼':slist,
      '내용':['취득금액', '취득일자', '본거지법정동코드', '차량등록일시', '배출가스인증번호', '배출가스등급', '배출가스검사유효일자', '최초회원번호', '최초등록일자', '저공해조치종류코드', '구조변경여부', '저공해조치여부', '현재회원번호', '차량소유자분류코드', '용도코드2', '제원관리번호', '수정일시', '차량말소여부', '차량제작일자', '연식', '차종코드', '차량관리번호', np.nan, '차대번호', '미정']
      }
   scol = pd.DataFrame(sdict)

   odf2 = odf[olist]
   sdf2 = sdf[slist]

   ocount = odf2.count().reset_index()
   ocount.columns = ['index', 'ocount']

   scount = sdf2.count().reset_index()
   scount.columns = ['index', 'scount']
   oscount = pd.concat([ocount, scount], axis=1)
   oscount['차이'] = oscount['ocount'] - oscount['scount']

   # 분석 결과 파일로 출력
   texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
   ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
   scol.to_excel(texcel, sheet_name='STD_col', index=False)
   oscount.to_excel(texcel, sheet_name='count', index=False)
   # odf2.count().reset_index().to_excel(texcel, sheet_name='ODS_count',index=False)
   # sdf2.count().reset_index().to_excel(texcel, sheet_name='STD_count',index=False)
   texcel.save()

   return print(f'[정제]{ods_file_name}_vs_{std_file_name}.xlsx 출력 완료.')

In [6]:
for n in tqdm(range(1, 31)):
    try:
        fuc(n)
    except:
        pass

  0%|          | 0/30 [00:00<?, ?it/s]C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:7: DtypeWarning: Columns (13,15,26) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
  3%|▎         | 1/30 [00:20<09:51, 20.40s/it]

[정제]ODS_CEG_CAR_MIG_1_vs_STD_CEG_CAR_MIG_1.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:7: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
  7%|▋         | 2/30 [00:40<09:28, 20.32s/it]

[정제]ODS_CEG_CAR_MIG_2_vs_STD_CEG_CAR_MIG_2.xlsx 출력 완료.

 10%|█         | 3/30 [01:00<09:06, 20.23s/it]

[정제]ODS_CEG_CAR_MIG_3_vs_STD_CEG_CAR_MIG_3.xlsx 출력 완료.

 13%|█▎        | 4/30 [01:20<08:45, 20.22s/it]

[정제]ODS_CEG_CAR_MIG_4_vs_STD_CEG_CAR_MIG_4.xlsx 출력 완료.

 17%|█▋        | 5/30 [01:41<08:25, 20.23s/it]

[정제]ODS_CEG_CAR_MIG_5_vs_STD_CEG_CAR_MIG_5.xlsx 출력 완료.

 20%|██        | 6/30 [02:01<08:07, 20.31s/it]

[정제]ODS_CEG_CAR_MIG_6_vs_STD_CEG_CAR_MIG_6.xlsx 출력 완료.

 23%|██▎       | 7/30 [02:22<07:47, 20.31s/it]

[정제]ODS_CEG_CAR_MIG_7_vs_STD_CEG_CAR_MIG_7.xlsx 출력 완료.

 27%|██▋       | 8/30 [02:42<07:26, 20.29s/it]

[정제]ODS_CEG_CAR_MIG_8_vs_STD_CEG_CAR_MIG_8.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:7: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
 30%|███       | 9/30 [03:02<07:05, 20.26s/it]

[정제]ODS_CEG_CAR_MIG_9_vs_STD_CEG_CAR_MIG_9.xlsx 출력 완료.

 33%|███▎      | 10/30 [03:22<06:44, 20.25s/it]

[정제]ODS_CEG_CAR_MIG_10_vs_STD_CEG_CAR_MIG_10.xlsx 출력 완료.

 37%|███▋      | 11/30 [03:42<06:23, 20.21s/it]

[정제]ODS_CEG_CAR_MIG_11_vs_STD_CEG_CAR_MIG_11.xlsx 출력 완료.

 40%|████      | 12/30 [04:03<06:04, 20.28s/it]

[정제]ODS_CEG_CAR_MIG_12_vs_STD_CEG_CAR_MIG_12.xlsx 출력 완료.

 43%|████▎     | 13/30 [04:23<05:45, 20.35s/it]

[정제]ODS_CEG_CAR_MIG_13_vs_STD_CEG_CAR_MIG_13.xlsx 출력 완료.

 47%|████▋     | 14/30 [04:44<05:28, 20.52s/it]

[정제]ODS_CEG_CAR_MIG_14_vs_STD_CEG_CAR_MIG_14.xlsx 출력 완료.

 50%|█████     | 15/30 [05:04<05:06, 20.45s/it]

[정제]ODS_CEG_CAR_MIG_15_vs_STD_CEG_CAR_MIG_15.xlsx 출력 완료.

 53%|█████▎    | 16/30 [05:26<04:50, 20.76s/it]

[정제]ODS_CEG_CAR_MIG_16_vs_STD_CEG_CAR_MIG_16.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:7: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 57%|█████▋    | 17/30 [05:47<04:30, 20.81s/it]

[정제]ODS_CEG_CAR_MIG_17_vs_STD_CEG_CAR_MIG_17.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 60%|██████    | 18/30 [06:07<04:08, 20.71s/it]

[정제]ODS_CEG_CAR_MIG_18_vs_STD_CEG_CAR_MIG_18.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 63%|██████▎   | 19/30 [06:28<03:48, 20.78s/it]

[정제]ODS_CEG_CAR_MIG_19_vs_STD_CEG_CAR_MIG_19.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 67%|██████▋   | 20/30 [06:49<03:26, 20.66s/it]

[정제]ODS_CEG_CAR_MIG_20_vs_STD_CEG_CAR_MIG_20.xlsx 출력 완료.

 70%|███████   | 21/30 [07:00<02:39, 17.75s/it]C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 73%|███████▎  | 22/30 [07:20<02:29, 18.67s/it]

[정제]ODS_CEG_CAR_MIG_22_vs_STD_CEG_CAR_MIG_22.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 77%|███████▋  | 23/30 [07:42<02:16, 19.47s/it]

[정제]ODS_CEG_CAR_MIG_23_vs_STD_CEG_CAR_MIG_23.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 80%|████████  | 24/30 [08:03<02:00, 20.08s/it]

[정제]ODS_CEG_CAR_MIG_24_vs_STD_CEG_CAR_MIG_24.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:7: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  odf = pd.read_csv(opath)
C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 83%|████████▎ | 25/30 [08:25<01:42, 20.51s/it]

[정제]ODS_CEG_CAR_MIG_25_vs_STD_CEG_CAR_MIG_25.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 87%|████████▋ | 26/30 [08:46<01:23, 20.82s/it]

[정제]ODS_CEG_CAR_MIG_26_vs_STD_CEG_CAR_MIG_26.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 90%|█████████ | 27/30 [09:08<01:03, 21.11s/it]

[정제]ODS_CEG_CAR_MIG_27_vs_STD_CEG_CAR_MIG_27.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 93%|█████████▎| 28/30 [09:29<00:42, 21.14s/it]

[정제]ODS_CEG_CAR_MIG_28_vs_STD_CEG_CAR_MIG_28.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (1,9,15,18) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
 97%|█████████▋| 29/30 [09:51<00:21, 21.34s/it]

[정제]ODS_CEG_CAR_MIG_29_vs_STD_CEG_CAR_MIG_29.xlsx 출력 완료.

C:\Users\kbjung\AppData\Local\Temp\ipykernel_13072\2172881546.py:8: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  sdf = pd.read_csv(spath)
100%|██████████| 30/30 [10:02<00:00, 20.07s/it]

[정제]ODS_CEG_CAR_MIG_30_vs_STD_CEG_CAR_MIG_30.xlsx 출력 완료.

### 파일명 설정

In [28]:
num = 4
ods_file_name = f'ODS_CEG_CAR_MIG_{num}'
std_file_name = f'STD_CEG_CAR_MIG_{num}'

In [29]:
opath = os.path.join(ods_path, ods_file_name + '.csv')
spath = os.path.join(std_path, std_file_name + '.csv')

In [30]:
odf = pd.read_csv(opath)
sdf = pd.read_csv(spath)

## 제원정보 분석

In [31]:
odf.columns

Index(['VHMNO', 'VHRNO', 'BSPL_LEDO_CD', 'OWNR_SE', 'VHCTY', 'PURPS',
       'NOW_OWNR_NM', 'NOW_MBERNO', 'BSPL_ADRS', 'OWNR_ADRS', 'VIN',
       'FST_REG_DE', 'VHCL_YRIDNW', 'VHCL_MNFCT_DE', 'EMIS_INSP_EFCT_DE',
       'SRCMNNO', 'EMIS_CRTCNO', 'EMIS_GRD', 'LEM_YN', 'LEM_KND',
       'LEM_STRCHG_YN', 'BSPL_ZIP', 'VHRNO_NUM_INFO', 'VHCL_ERSR_YN',
       'FST_OWNR_NM', 'FST_MBERNO', 'ACQS_DE', 'ACQS_AMT', 'RMK', 'CRTN_DT',
       'UPDT_DT', 'USER_ID'],
      dtype='object')

In [32]:
sdf.columns

Index(['ACQS_AMT', 'ACQS_YMD', 'BSPL_STDG_CD', 'VHCL_REG_DT',
       'EXHST_GAS_CERT_NO', 'EXHST_GAS_GRD_CD', 'EXTGAS_INSP_VLD_YMD',
       'FRST_MBR_NO', 'FRST_REG_YMD', 'LEM_KND_CD', 'STRCT_CHG_YN', 'LEM_YN',
       'NOW_MBR_NO', 'VHCL_OWNR_CL_CD', 'PURPS_CD2', 'MANP_MNG_NO', 'MDFCN_DT',
       'VHCL_ERSR_YN', 'VHCL_FBCTN_YMD', 'YRIDNW', 'VHCTY_CD', 'VHCL_MNG_NO',
       'VHRNO_FGRE_INFO', 'VIN', 'VHRNO'],
      dtype='object')

In [33]:
len(odf.columns), len(sdf.columns)

(32, 25)

In [34]:
odf.shape, sdf.shape

((1000000, 32), (1000000, 25))

### 동일한 내용의 컬럼 확인

In [35]:
olist = [
    'ACQS_AMT', 
    'ACQS_DE', 
    'BSPL_LEDO_CD', 
    'CRTN_DT', 
    'EMIS_CRTCNO', 
    'EMIS_GRD', 
    'EMIS_INSP_EFCT_DE', 
    'FST_MBERNO', 
    'FST_REG_DE', 
    'LEM_KND', 
    'LEM_STRCHG_YN', 
    'LEM_YN', 
    'NOW_MBERNO', 
    'OWNR_SE', 
    'PURPS', 
    'SRCMNNO', 
    'UPDT_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_MNFCT_DE', 
    'VHCL_YRIDNW', 
    'VHCTY', 
    'VHMNO', 
    'VHRNO_NUM_INFO', 
    'VIN', 'VHRNO', 
    'NOW_OWNR_NM', 
    'BSPL_ADRS', 
    'OWNR_ADRS', 
    'BSPL_ZIP', 
    'FST_OWNR_NM', 
    'RMK', 
    'USER_ID'
    ]

In [36]:
odict = {
    '컬럼':olist,
    '내용':['취득금액', '취득일자', '본거지 법정동 코드', '생성 일시', '배출가스 인증번호', '배출가스 등급', '배출가스검사유효일자', '최초 회원번호', '최초 등록 일자', '저공해조치 종류', '저공해조치 구조변경 YN', '저공해조치 YN(미사용)', '현재 회원번호', '소유자 구분', '용도', '제원관리번호', '수정 일시', '차량 말소 YN', '차량 제작 일자', '차량 연식', '차종', '차량관리번호', '차량등록번호 숫자 정보', '차대번호', '미정', '미정', '미정', '미정', '미정', '미정', '미정', '미정']
    }

In [37]:
ocol = pd.DataFrame(odict)
ocol

                   컬럼             내용
0            ACQS_AMT           취득금액
1             ACQS_DE           취득일자
2        BSPL_LEDO_CD     본거지 법정동 코드
3             CRTN_DT          생성 일시
4         EMIS_CRTCNO      배출가스 인증번호
5            EMIS_GRD        배출가스 등급
6   EMIS_INSP_EFCT_DE     배출가스검사유효일자
7          FST_MBERNO        최초 회원번호
8          FST_REG_DE       최초 등록 일자
9             LEM_KND       저공해조치 종류
10      LEM_STRCHG_YN  저공해조치 구조변경 YN
11             LEM_YN  저공해조치 YN(미사용)
12         NOW_MBERNO        현재 회원번호
13            OWNR_SE         소유자 구분
14              PURPS             용도
15            SRCMNNO         제원관리번호
16            UPDT_DT          수정 일시
17       VHCL_ERSR_YN       차량 말소 YN
18      VHCL_MNFCT_DE       차량 제작 일자
19        VHCL_YRIDNW          차량 연식
20              VHCTY             차종
21              VHMNO         차량관리번호
22     VHRNO_NUM_INFO   차량등록번호 숫자 정보
23                VIN           차대번호
24              VHRNO             미정
25        NOW_OWNR_NM             미정
26          BSPL_ADRS             미정
27          OWNR_ADRS             미정
28           BSPL_ZIP             미정
29        FST_OWNR_NM             미정
30                RMK             미정
31            USER_ID             미정

In [38]:
# ocol.to_excel(f'analysis/ODSvsSTD/[정제][col]{ods_file_name}.xlsx', index=False)

In [39]:
slist = [
    'ACQS_AMT', 
    'ACQS_YMD', 
    'BSPL_STDG_CD', 
    'VHCL_REG_DT', 
    'EXHST_GAS_CERT_NO', 
    'EXHST_GAS_GRD_CD', 
    'EXTGAS_INSP_VLD_YMD', 
    'FRST_MBR_NO', 
    'FRST_REG_YMD', 
    'LEM_KND_CD', 
    'STRCT_CHG_YN', 
    'LEM_YN', 
    'NOW_MBR_NO', 
    'VHCL_OWNR_CL_CD', 
    'PURPS_CD2', 
    'MANP_MNG_NO', 
    'MDFCN_DT', 
    'VHCL_ERSR_YN', 
    'VHCL_FBCTN_YMD', 
    'YRIDNW', 
    'VHCTY_CD', 
    'VHCL_MNG_NO', 
    'VHRNO_FGRE_INFO', 
    'VIN', 
    'VHRNO'
    ]

In [40]:
sdict = {
       '컬럼':slist,
       '내용':['취득금액', '취득일자', '본거지법정동코드', '차량등록일시', '배출가스인증번호', '배출가스등급', '배출가스검사유효일자', '최초회원번호', '최초등록일자', '저공해조치종류코드', '구조변경여부', '저공해조치여부', '현재회원번호', '차량소유자분류코드', '용도코드2', '제원관리번호', '수정일시', '차량말소여부', '차량제작일자', '연식', '차종코드', '차량관리번호', np.nan, '차대번호', '미정']
       }

In [41]:
scol = pd.DataFrame(sdict)
scol

                     컬럼          내용
0              ACQS_AMT        취득금액
1              ACQS_YMD        취득일자
2          BSPL_STDG_CD    본거지법정동코드
3           VHCL_REG_DT      차량등록일시
4     EXHST_GAS_CERT_NO    배출가스인증번호
5      EXHST_GAS_GRD_CD      배출가스등급
6   EXTGAS_INSP_VLD_YMD  배출가스검사유효일자
7           FRST_MBR_NO      최초회원번호
8          FRST_REG_YMD      최초등록일자
9            LEM_KND_CD   저공해조치종류코드
10         STRCT_CHG_YN      구조변경여부
11               LEM_YN     저공해조치여부
12           NOW_MBR_NO      현재회원번호
13      VHCL_OWNR_CL_CD   차량소유자분류코드
14            PURPS_CD2       용도코드2
15          MANP_MNG_NO      제원관리번호
16             MDFCN_DT        수정일시
17         VHCL_ERSR_YN      차량말소여부
18       VHCL_FBCTN_YMD      차량제작일자
19               YRIDNW          연식
20             VHCTY_CD        차종코드
21          VHCL_MNG_NO      차량관리번호
22      VHRNO_FGRE_INFO         NaN
23                  VIN        차대번호
24                VHRNO          미정

In [42]:
# scol.to_excel(f'analysis/ODSvsSTD/[정제][col]{std_file_name}.xlsx', index=False)

#### 데이터 info 확인

In [43]:
odf2 = odf[olist]
odf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   ACQS_AMT           960945 non-null   float64
 1   ACQS_DE            961739 non-null   float64
 2   BSPL_LEDO_CD       1000000 non-null  int64
 3   CRTN_DT            1000000 non-null  object
 4   EMIS_CRTCNO        682748 non-null   object
 5   EMIS_GRD           1000000 non-null  object
 6   EMIS_INSP_EFCT_DE  999991 non-null   float64
 7   FST_MBERNO         1000000 non-null  object
 8   FST_REG_DE         1000000 non-null  int64
 9   LEM_KND            112210 non-null   float64
 10  LEM_STRCHG_YN      1000000 non-null  object
 11  LEM_YN             999940 non-null   object
 12  NOW_MBERNO         1000000 non-null  object
 13  OWNR_SE            1000000 non-null  object
 14  PURPS              1000000 non-null  object
 15  SRCMNNO            1000000 non-null  object
 16  UPDT_DT            793696 non-null   object
 17  VHCL_ERSR_YN       1000000 non-null  object
 18  VHCL_MNFCT_DE      999991 non-null   float64
 19  VHCL_YRIDNW        1000000 non-null  int64
 20  VHCTY              1000000 non-null  object
 21  VHMNO              1000000 non-null  object
 22  VHRNO_NUM_INFO     1000000 non-null  int64
 23  VIN                1000000 non-null  object
 24  VHRNO              1000000 non-null  object
 25  NOW_OWNR_NM        1000000 non-null  object
 26  BSPL_ADRS          1000000 non-null  object
 27  OWNR_ADRS          1000000 non-null  object
 28  BSPL_ZIP           0 non-null        float64
 29  FST_OWNR_NM        1000000 non-null  object
 30  RMK                47850 non-null    object
 31  USER_ID            1000000 non-null  object
dtypes: float64(6), int64(4), object(22)
memory usage: 244.1+ MB

In [59]:
ocount = odf2.count().reset_index()
ocount.columns = ['index', 'ocount']
ocount

                index   ocount
0            ACQS_AMT   960945
1             ACQS_DE   961739
2        BSPL_LEDO_CD  1000000
3             CRTN_DT  1000000
4         EMIS_CRTCNO   682748
5            EMIS_GRD  1000000
6   EMIS_INSP_EFCT_DE   999991
7          FST_MBERNO  1000000
8          FST_REG_DE  1000000
9             LEM_KND   112210
10      LEM_STRCHG_YN  1000000
11             LEM_YN   999940
12         NOW_MBERNO  1000000
13            OWNR_SE  1000000
14              PURPS  1000000
15            SRCMNNO  1000000
16            UPDT_DT   793696
17       VHCL_ERSR_YN  1000000
18      VHCL_MNFCT_DE   999991
19        VHCL_YRIDNW  1000000
20              VHCTY  1000000
21              VHMNO  1000000
22     VHRNO_NUM_INFO  1000000
23                VIN  1000000
24              VHRNO  1000000
25        NOW_OWNR_NM  1000000
26          BSPL_ADRS  1000000
27          OWNR_ADRS  1000000
28           BSPL_ZIP        0
29        FST_OWNR_NM  1000000
30                RMK    47850
31            USER_ID  1000000

In [45]:
# odf2.count().reset_index().to_excel(f'analysis/ODSvsSTD/[정제][count]{ods_file_name}.xlsx', index=False)

In [46]:
sdf2 = sdf[slist]
sdf2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 25 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   ACQS_AMT             986324 non-null   float64
 1   ACQS_YMD             986391 non-null   float64
 2   BSPL_STDG_CD         1000000 non-null  int64
 3   VHCL_REG_DT          1000000 non-null  object
 4   EXHST_GAS_CERT_NO    869167 non-null   object
 5   EXHST_GAS_GRD_CD     1000000 non-null  object
 6   EXTGAS_INSP_VLD_YMD  999991 non-null   float64
 7   FRST_MBR_NO          1000000 non-null  object
 8   FRST_REG_YMD         1000000 non-null  int64
 9   LEM_KND_CD           34624 non-null    object
 10  STRCT_CHG_YN         999999 non-null   object
 11  LEM_YN               999961 non-null   object
 12  NOW_MBR_NO           1000000 non-null  object
 13  VHCL_OWNR_CL_CD      1000000 non-null  object
 14  PURPS_CD2            1000000 non-null  object
 15  MANP_MNG_NO          1000000 non-null  object
 16  MDFCN_DT             757616 non-null   object
 17  VHCL_ERSR_YN         1000000 non-null  object
 18  VHCL_FBCTN_YMD       999995 non-null   float64
 19  YRIDNW               1000000 non-null  int64
 20  VHCTY_CD             1000000 non-null  object
 21  VHCL_MNG_NO          1000000 non-null  object
 22  VHRNO_FGRE_INFO      1000000 non-null  int64
 23  VIN                  1000000 non-null  object
 24  VHRNO                1000000 non-null  object
dtypes: float64(4), int64(4), object(17)
memory usage: 190.7+ MB

In [60]:
scount = sdf2.count().reset_index()
scount.columns = ['index', 'scount']
scount

                  index   scount
0              ACQS_AMT   986324
1              ACQS_YMD   986391
2          BSPL_STDG_CD  1000000
3           VHCL_REG_DT  1000000
4     EXHST_GAS_CERT_NO   869167
5      EXHST_GAS_GRD_CD  1000000
6   EXTGAS_INSP_VLD_YMD   999991
7           FRST_MBR_NO  1000000
8          FRST_REG_YMD  1000000
9            LEM_KND_CD    34624
10         STRCT_CHG_YN   999999
11               LEM_YN   999961
12           NOW_MBR_NO  1000000
13      VHCL_OWNR_CL_CD  1000000
14            PURPS_CD2  1000000
15          MANP_MNG_NO  1000000
16             MDFCN_DT   757616
17         VHCL_ERSR_YN  1000000
18       VHCL_FBCTN_YMD   999995
19               YRIDNW  1000000
20             VHCTY_CD  1000000
21          VHCL_MNG_NO  1000000
22      VHRNO_FGRE_INFO  1000000
23                  VIN  1000000
24                VHRNO  1000000

In [48]:
# sdf2.count().reset_index().to_excel(f'analysis/ODSvsSTD/[정제][count]{std_file_name}.xlsx', index=False)

In [61]:
oscount = pd.concat([ocount, scount], axis=1)
oscount

                index   ocount                index     scount
0            ACQS_AMT   960945             ACQS_AMT   986324.0
1             ACQS_DE   961739             ACQS_YMD   986391.0
2        BSPL_LEDO_CD  1000000         BSPL_STDG_CD  1000000.0
3             CRTN_DT  1000000          VHCL_REG_DT  1000000.0
4         EMIS_CRTCNO   682748    EXHST_GAS_CERT_NO   869167.0
5            EMIS_GRD  1000000     EXHST_GAS_GRD_CD  1000000.0
6   EMIS_INSP_EFCT_DE   999991  EXTGAS_INSP_VLD_YMD   999991.0
7          FST_MBERNO  1000000          FRST_MBR_NO  1000000.0
8          FST_REG_DE  1000000         FRST_REG_YMD  1000000.0
9             LEM_KND   112210           LEM_KND_CD    34624.0
10      LEM_STRCHG_YN  1000000         STRCT_CHG_YN   999999.0
11             LEM_YN   999940               LEM_YN   999961.0
12         NOW_MBERNO  1000000           NOW_MBR_NO  1000000.0
13            OWNR_SE  1000000      VHCL_OWNR_CL_CD  1000000.0
14              PURPS  1000000            PURPS_CD2  1000000.0
15            SRCMNNO  1000000          MANP_MNG_NO  1000000.0
16            UPDT_DT   793696             MDFCN_DT   757616.0
17       VHCL_ERSR_YN  1000000         VHCL_ERSR_YN  1000000.0
18      VHCL_MNFCT_DE   999991       VHCL_FBCTN_YMD   999995.0
19        VHCL_YRIDNW  1000000               YRIDNW  1000000.0
20              VHCTY  1000000             VHCTY_CD  1000000.0
21              VHMNO  1000000          VHCL_MNG_NO  1000000.0
22     VHRNO_NUM_INFO  1000000      VHRNO_FGRE_INFO  1000000.0
23                VIN  1000000                  VIN  1000000.0
24              VHRNO  1000000                VHRNO  1000000.0
25        NOW_OWNR_NM  1000000                  NaN        NaN
26          BSPL_ADRS  1000000                  NaN        NaN
27          OWNR_ADRS  1000000                  NaN        NaN
28           BSPL_ZIP        0                  NaN        NaN
29        FST_OWNR_NM  1000000                  NaN        NaN
30                RMK    47850                  NaN        NaN
31            USER_ID  1000000                  NaN        NaN

In [62]:
oscount['차이'] = oscount['ocount'] - oscount['scount']
oscount

                index   ocount                index     scount        차이
0            ACQS_AMT   960945             ACQS_AMT   986324.0  -25379.0
1             ACQS_DE   961739             ACQS_YMD   986391.0  -24652.0
2        BSPL_LEDO_CD  1000000         BSPL_STDG_CD  1000000.0       0.0
3             CRTN_DT  1000000          VHCL_REG_DT  1000000.0       0.0
4         EMIS_CRTCNO   682748    EXHST_GAS_CERT_NO   869167.0 -186419.0
5            EMIS_GRD  1000000     EXHST_GAS_GRD_CD  1000000.0       0.0
6   EMIS_INSP_EFCT_DE   999991  EXTGAS_INSP_VLD_YMD   999991.0       0.0
7          FST_MBERNO  1000000          FRST_MBR_NO  1000000.0       0.0
8          FST_REG_DE  1000000         FRST_REG_YMD  1000000.0       0.0
9             LEM_KND   112210           LEM_KND_CD    34624.0   77586.0
10      LEM_STRCHG_YN  1000000         STRCT_CHG_YN   999999.0       1.0
11             LEM_YN   999940               LEM_YN   999961.0     -21.0
12         NOW_MBERNO  1000000           NOW_MBR_NO  1000000.0       0.0
13            OWNR_SE  1000000      VHCL_OWNR_CL_CD  1000000.0       0.0
14              PURPS  1000000            PURPS_CD2  1000000.0       0.0
15            SRCMNNO  1000000          MANP_MNG_NO  1000000.0       0.0
16            UPDT_DT   793696             MDFCN_DT   757616.0   36080.0
17       VHCL_ERSR_YN  1000000         VHCL_ERSR_YN  1000000.0       0.0
18      VHCL_MNFCT_DE   999991       VHCL_FBCTN_YMD   999995.0      -4.0
19        VHCL_YRIDNW  1000000               YRIDNW  1000000.0       0.0
20              VHCTY  1000000             VHCTY_CD  1000000.0       0.0
21              VHMNO  1000000          VHCL_MNG_NO  1000000.0       0.0
22     VHRNO_NUM_INFO  1000000      VHRNO_FGRE_INFO  1000000.0       0.0
23                VIN  1000000                  VIN  1000000.0       0.0
24              VHRNO  1000000                VHRNO  1000000.0       0.0
25        NOW_OWNR_NM  1000000                  NaN        NaN       NaN
26          BSPL_ADRS  1000000                  NaN        NaN       NaN
27          OWNR_ADRS  1000000                  NaN        NaN       NaN
28           BSPL_ZIP        0                  NaN        NaN       NaN
29        FST_OWNR_NM  1000000                  NaN        NaN       NaN
30                RMK    47850                  NaN        NaN       NaN
31            USER_ID  1000000                  NaN        NaN       NaN

### [출력] 분석내용

In [63]:
texcel = pd.ExcelWriter(f'analysis/ODSvsSTD/[정제]{ods_file_name}_vs_{std_file_name}.xlsx')
ocol.to_excel(texcel, sheet_name='ODS_col', index=False)
scol.to_excel(texcel, sheet_name='STD_col', index=False)
oscount.to_excel(texcel, sheet_name='count', index=False)
# odf2.count().reset_index().to_excel(texcel, sheet_name='ODS_count',index=False)
# sdf2.count().reset_index().to_excel(texcel, sheet_name='STD_count',index=False)
texcel.save()